### ISSUE TITLE
10000

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimism#10000]
# Congrats Monorepo!

![image](https://github.com/ethereum-optimism/optimism/assets/23033765/a028f74c-38de-46ab-a5ce-fc1dd3ed9bc8)

**Comment by clabby** [comment]
![242171bf7834d095](https://github.com/ethereum-optimism/optimism/assets/8406232/e6fb8d6d-9516-4a3d-b057-b764083e7917)

**Comment by roninjin10** [comment]
Impressive it's over 9000

**Comment by Harpethr** [comment]
![image (7)](https://github.com/ethereum-optimism/optimism/assets/69322641/dbda4844-5b91-4b4d-b4f9-2ba75959f801)

**Comment by smartcontracts** [comment]
Wooooo

**Comment by pegahcarter** [comment]
:1st_place_medal:

**Comment by protolambda** [comment]
Looking forward to #20000

**Comment by sebastianst** [comment]
It's there @protolambda #20000 🎉
