### ISSUE TITLE
Deploy the L1 contracts occurs: error code -32000: max priority fee per gas higher than max fee per gas

### ISSUE THREAD

**Issue by AlfredYyong** [ethereum-optimism/optimism#10095]
**Bug Description**
Occurs when deploying L1 contracts:
```
Error: 
Failed to send transaction

Context:
- server returned an error response: error code -32000: max priority fee per gas higher than max fee per gas
```
**Steps to Reproduce**

1. Follow the guide to deploy an L2 chain with Sepolia as the L1: [Creating Your Own L2 Rollup Testnet](https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#deploy-the-l1-contracts)
2. Unable to deploy the contract to L1 when the step 'Deploy the L1 contracts' is executed.

**Expected behavior**
Not sure which of my getting-start.json configurations is at fault.

**Environment Information:**
 - Operating System: AWS Linux 2023
 - Package Version (or commit hash): optimism v1.7.2
 ```
 Dependency | Minimum         | Actual
git          2                2.40.1
go           1.21             1.21.5
node         20               20.11.1
pnpm         8                8.14.0
foundry      0.2.0 (a5efe4f)  0.2.0 (4603195)
make         3                4.3
jq           1.6              1.6
direnv       2                2.34.0
```

**Configurations:**
Refer to `sepolia.json` for other configurations, I've only listed the gas related configurations.
```
{
  "finalSystemOwner": "0xxxx",
  "superchainConfigGuardian": "0xxxx",
  "l1StartingBlockTag": "0xd9943312c4ebd63abcfa0533c371b8d535cc3dd3eb4159f5389d8b20679b9557",
  ...
  "gasPriceOracleOverhead": 2100,
  "gasPriceOracleScalar": 1000000,

  "eip1559Denominator": 50,
  "eip1559DenominatorCanyon": 250,
  "eip1559Elasticity": 6,
  ...
```

**Logs:**
```
$ forge script scripts/Deploy.s.sol:Deploy --private-key $GS_ADMIN_PRIVATE_KEY --broadcast --rpc-url $L1_RPC_URL --slow
[⠒] Compiling...
No files changed, compilation skipped
Script ran successfully.

== Logs ==
  Writing artifact to /home/ec2-user/op/optimism/packages/contracts-bedrock/deployments/getting-started/.deploy
  Connected to network with chainid 11155111
  DeployConfig: reading file /home/ec2-user/op/optimism/packages/contracts-bedrock/deploy-config/getting-started.json
  Deploying a fresh OP Stack including SuperchainConfig
  Deploying Safe
  ...
  Running chain assertions on the DelayedWETH

## Setting up 1 EVM.

==========================

Chain 11155111

Estimated gas price: 0.001137278 gwei

Estimated total gas used for script: 68784315

Estimated amount required: 0.00007822688819457 ETH

==========================
##
Sending transactions [0 - 0].

Transactions saved to: /home/ec2-user/op/optimism/packages/contracts-bedrock/broadcast/Deploy.s.sol/11155111/run-latest.json

Sensitive values saved to: /home/ec2-user/op/optimism/packages/contracts-bedrock/cache/Deploy.s.sol/11155111/run-latest.json

Error: 
Failed to send transaction

Context:
- server returned an error response: error code -32000: max priority fee per gas higher than max fee per gas
```

**Additional context**

---

⚠️ **Notice:** Issues that do not include the following sections will be subject to closure:
- Bug Description
- Steps to Reproduce
- Environment Information

Please ensure all required sections are filled out accurately to expedite the debugging process and improve issue resolution efficiency.

**Comment by 522923331** [comment]
I am also encountering this issue.
And the optimism version I am using is v1.7.0,  the op-contract version I am using is v1.2.0.

**Comment by AlfredYyong** [comment]
Solve the problem by adding the `--with-gas-price` flags.

Whole command:
```
forge script scripts/Deploy.s.sol:Deploy --private-key $GS_ADMIN_PRIVATE_KEY --broadcast --rpc-url $L1_RPC_URL --with-gas-price 1.7gwei
```
Specific gas price values can be found in the browser: [Sepolia Blockscout Gas Tracker](https://eth-sepolia.blockscout.com/gas-tracker)

**Comment by 522923331** [comment]
I didn't add the `--with-gas-price` flag when I successfully deployed the L1 contract half a month ago，And the guide also does not use this flag.
Do you know why it is needed now?  @420516460

**Comment by AlfredYyong** [comment]
> I didn't add the `--with-gas-price` flag when I successfully deployed the L1 contract half a month ago，And the guide also does not use this flag. Do you know why it is needed now? @420516460

yep, i have deployed it successfully before without the need to use `--with-gas-price` flag, in guide use '--slow'.

Did you need to run `forge script scripts/Deploy.s.sol:Deploy --sig 'sync()' --rpc-url $L1_RPC_URL` when you deployed it before? in the lastest version, these command no longer needs to be executed

In optimism v1.7.2 version, there have been many changes to op contracts, for example use `OptimismPortal2` instead of `OptimismPortal`.

 in my opinion, It should be that more contracts need to be deployed and there is a huge gap in `estimate gas`, you can see my error log, it prompts: 
 ```
Estimated gas price: 0.001137278 gwei
 ```
 in [sepolia blockscout](https://eth-sepolia.blockscout.com/gas-tracker), the slowest gas price is 3.5gwei, that is a big difference!!! so i think that is the key reason.
