### ISSUE TITLE
Syncing deployment DisputeGameFactory: contract DisputeGameFactory.0.8.15. script failed: Error parsing version

### ISSUE THREAD

**Issue by wy51084915** [ethereum-optimism/optimism#10114]
**Bug Description**
i'm trying to build my first L2 chain in the guide of https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup,when i finished deploying the L1 contract with the command :
 `forge script scripts/Deploy.s.sol:Deploy --private-key $GS_ADMIN_PRIVATE_KEY --broadcast --rpc-url $L1_RPC_URL --slow`  it worked well with the output:

`ONCHAIN EXECUTION COMPLETE & SUCCESSFUL.
Total Paid: 0.103279203582127804 ETH (34057669 gas * avg 3.031470256 gwei)

Transactions saved to: /Users/user/optimism/packages/contracts-bedrock/broadcast/Deploy.s.sol/11155111/run-latest.json

Sensitive values saved to: /Users/user/optimism/packages/contracts-bedrock/cache/Deploy.s.sol/11155111/run-latest.json

then i ran 
`forge script scripts/Deploy.s.sol:Deploy --sig 'sync()' --rpc-url $L1_RPC_URL` 
to Generate contract artifacts and an error occured :

**Logs:**
`\": []\n  },\n  \"additionalContracts\": [],\n  \"isFixedGasLimit\": false\n}'"])
    │   └─ ← [Return] 0x6e756c6c
    ├─ [0] VM::ffi(["bash", "-c", "echo DisputeGameFactory.0.8.15 | sed -E 's/[.][0-9]+\\.[0-9]+\\.[0-9]+//g'"])
    │   └─ ← [Return] 0x4469737075746547616d65466163746f7279
    ├─ [0] VM::getCode("DisputeGameFactory.sol:DisputeGameFactory.0.8.15") [staticcall]
    │   └─ ← [Revert] Error parsing version
    └─ ← [Revert] Error parsing version

== Logs ==
  Connected to network with chainid 11155111
  Storing temp deployment data in /Users/user/optimism/packages/contracts-bedrock/deployments/getting-started/.deploy
  DeployConfig: reading file /Users/user/optimism/packages/contracts-bedrock/deploy-config/getting-started.json
  Deploying from Deploy
  Deployment context: getting-started
  Syncing 27 deployments
  Using deployment artifact /Users/user/optimism/packages/contracts-bedrock/broadcast/Deploy.s.sol/11155111/run-latest.json
  Syncing deployment AddressManager: contract AddressManager
  Syncing deployment DisputeGameFactory: contract DisputeGameFactory.0.8.15
Error: 
script failed: Error parsing version`

**Environment Information:**
 - Operating System: MacOs M1
 - Package Version
      git      2.44.0
      go      1.22.1
      node      21.7.1
      pnpm    8.15.6
      foundry       0.2.0
      make      3.81
      jq       1.7.1
      direnv      2.34.0
      solc.     0.8.15

anybody can help solve this? Thx!

**Comment by AlfredYyong** [comment]
can you show more specify foundry version? in path xxx/optimism to run command:
`forge --version`

will get like this: 
`forge 0.2.0 (4603195 2024-04-10T00:17:25.834634784Z)`

and what is your optimism branch version number? is it `tutorials/chain`?

**Comment by Ajmali124** [comment]
i have got the same problem 

The forge version is 
forge 0.2.0 (14daacf 2024-04-09T00:17:09.802796000Z)

and yes it is the tutorials/chain

**Comment by AlfredYyong** [comment]
> i have got the same problem
> 
> The forge version is forge 0.2.0 (14daacf 2024-04-09T00:17:09.802796000Z)
> 
> and yes it is the tutorials/chain

your version is right, have you checked if contracts have been deployed to L1? 

in the latest version of optimism(v1.7.2+), we don‘t rely on the artifacts, so it's fine in latest version no need to run this command.

i m not sure this changes if have been sync to the branch `tutorials/chain`, i will retry what you did

**Comment by wy51084915** [comment]
> can you show more specify foundry version? in path xxx/optimism to run command: `forge --version`
> 
> will get like this: `forge 0.2.0 (4603195 2024-04-10T00:17:25.834634784Z)`
> 
> and what is your optimism branch version number? is it `tutorials/chain`?

yes, i got forge version == 0.2.0 and i'm under the branch `tutorials/chain`
i finally choose to skip the step and just copy the artifacts from its peer folder(sepolia), which may be generated by optimism earlier, and that worked.

**Comment by wy51084915** [comment]
> > i have got the same problem
> > The forge version is forge 0.2.0 (14daacf 2024-04-09T00:17:09.802796000Z)
> > and yes it is the tutorials/chain
> 
> your version is right, have you checked if contracts have been deployed to L1?
> 
> in the latest version of optimism(v1.7.2+), we don‘t rely on the artifacts, so it's fine in latest version no need to run this command.
> 
> i m not sure this changes if have been sync to the branch `tutorials/chain`, i will retry what you did

yes , the deployment is successful , but under the branch "tutorials/chain", to generate the L2's genesis files need the artifacts.So i have to get it.

**Comment by AlfredYyong** [comment]
> > > i have got the same problem
> > > The forge version is forge 0.2.0 (14daacf 2024-04-09T00:17:09.802796000Z)
> > > and yes it is the tutorials/chain
> > 
> > 
> > your version is right, have you checked if contracts have been deployed to L1?
> > in the latest version of optimism(v1.7.2+), we don‘t rely on the artifacts, so it's fine in latest version no need to run this command.
> > i m not sure this changes if have been sync to the branch `tutorials/chain`, i will retry what you did
> 
> yes , the deployment is successful , but under the branch "tutorials/chain", to generate the L2's genesis files need the artifacts.So i have to get it.

wooo nice! yep i have met some similar issues, the `artifacts` are practically no longer needed at this time, but the documentation hasn't been updated yet.

i m guessing you need to change this when you run the `go run cmd/main.go genesis l2 \` step:
```
...
 --deployment-dir . /packages/contracts-bedrock/deployments/getting-started/ \
...
```
this flag need `artifacts`.

**Comment by wy51084915** [comment]
> > > > i have got the same problem
> > > > The forge version is forge 0.2.0 (14daacf 2024-04-09T00:17:09.802796000Z)
> > > > and yes it is the tutorials/chain
> > > 
> > > 
> > > your version is right, have you checked if contracts have been deployed to L1?
> > > in the latest version of optimism(v1.7.2+), we don‘t rely on the artifacts, so it's fine in latest version no need to run this command.
> > > i m not sure this changes if have been sync to the branch `tutorials/chain`, i will retry what you did
> > 
> > 
> > yes , the deployment is successful , but under the branch "tutorials/chain", to generate the L2's genesis files need the artifacts.So i have to get it.
> 
> wooo nice! yep i have met some similar issues, the `artifacts` are practically no longer needed at this time, but the documentation hasn't been updated yet.
> 
> i m guessing you need to change this when you run the `go run cmd/main.go genesis l2 \` step:
> 
> ```
> ...
>  --deployment-dir . /packages/contracts-bedrock/deployments/getting-started/ \
> ...
> ```
> 
> this flag need `artifacts`.

yes, just change the `--deployment-dir . /packages/contracts-bedrock/deployments/getting-started/ ` to `--deployment-dir . /packages/contracts-bedrock/deployments/sepolia/` , and everything will be fine

**Comment by wy51084915** [comment]
> > > > i have got the same problem我有同样的问题
> > > > The forge version is forge 0.2.0 (14daacf 2024-04-09T00:17:09.802796000Z)forge版本为forge 0.2.0 (14daacf 2024-04-09T00:17:09.802796000Z)
> > > > and yes it is the tutorials/chain 是的，这是教程/链
> > > 
> > > 
> > > your version is right, have you checked if contracts have been deployed to L1?你的版本是对的，你检查过合约是否已经部署到L1了吗？
> > > in the latest version of optimism(v1.7.2+), we don‘t rely on the artifacts, so it's fine in latest version no need to run this command. 在最新版本的 optimism(v1.7.2+) 中，我们不依赖于工件，因此在最新版本中无需运行此命令就可以了。
> > > i m not sure this changes if have been sync to the branch `tutorials/chain`, i will retry what you did 我不确定此更改是否已同步到分支 `tutorials/chain` ，我将重试您所做的事情
> > 
> > 
> > yes , the deployment is successful , but under the branch "tutorials/chain", to generate the L2's genesis files need the artifacts.So i have to get it.是的，部署成功了，但是在“tutorials/chain”分支下，生成L2的创世文件需要工件。所以我必须得到它。
> 
> wooo nice! yep i have met some similar issues, the `artifacts` are practically no longer needed at this time, but the documentation hasn't been updated yet.哇好极了！是的，我遇到了一些类似的问题，此时实际上不再需要 `artifacts` ，但文档尚未更新。
> 
> i m guessing you need to change this when you run the `go run cmd/main.go genesis l2 \` step:我猜您在运行 `go run cmd/main.go genesis l2 \` 步骤时需要更改此设置：
> 
> ```
> ...
>  --deployment-dir . /packages/contracts-bedrock/deployments/getting-started/ \
> ...
> ```
> 
> this flag need `artifacts`.该标志需要 `artifacts` 。

sorry, i was wrong!simply copy the artifact files can solve the problem for a while, but will lead to other mistakes latter!
 i have checked the README.md in `/packages/contracts-bedrock` and found the right command : 
`forge script -vvv scripts/Deploy.s.sol:Deploy --sig 'sync()' --rpc-url $L1_RPC_URL --broadcast --private-key $GS_ADMIN_PRIVATE_KEY`
with this command , we can get the right artifacts successfully.
i should have known that simplily copy the artifacts from other folder will lead to the mismatch of contracts' address! sry for misleading you, and this is the right way to go!
