### ISSUE TITLE
Error: withdrawal index 0 out of bounds. There are 0 withdrawals

### ISSUE THREAD

**Issue by ahyammona** [ethereum-optimism/optimism#10112]
^
Error: withdrawal index 0 out of bounds. There are 0 withdrawals
    at CrossChainMessenger.toCrossChainMessage (C:\Users\Asus\Projects\AUTOMATED-TELEGRAM-BOT\InhumaneBot(public)\node_modules\@eth-optimism\sdk\src\cross-chain-messenger.ts:676:15)
    at processTicksAndRejections (node:internal/process/task_queues:

please any help would do

**Comment by Diegomiguelvidela** [comment]
Hola sabes qe tengo un token el metamask de 3 WLD y no puedo retirarlo

**Comment by tynes** [comment]
cc @smartcontracts

**Comment by danielsimao** [comment]
@ahyammona you should give more context on what you are doing. My guess is that you are using `waitForMessageReceipt` wrong.

You should only use `waitForMessageReceipt` for cross chain messages (deposit and withdraw).

If you are trying to wait for example erc20 tx, make sure you use `tx.wait()`

**Comment by tynes** [comment]
The sdk is no longer maintained
