### ISSUE TITLE
Reduce Speed that L1 GasPrice is updated

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#1012]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
optimistic-geth updates the L1 gas price over time in the `RollupGasPriceOracle`. If the gas price is volatile upwards between calling `eth_estimateGas` and sending the transaction, it is possible for the transaction to be rejected. We should update the L1 gas price less often so that this race condition isn't ran into as often. The longer we wait to update the L1 gas price, the more risk that we are giving a bad quote and will pay more when actually submitting the batch to L1. This also reduces the number of API requests, which ought to be included in the cost structure but isn't.

**Describe alternatives you've considered**
Allow for a buffer when accepting transactions - this will be gamed by people that want to save money. If transactions are still accepted by the sequencer up to 10% lower than its current fee, it will eliminate the race condition unless gas prices are extremely volatile.

A future solution would be depositing the `BASE_FEE` over time and have the L1 gas price live in L2 state. This could be useful for applications generally on L2. Arbers would be incentivied to deposit the `BASE_FEE` when it goes down to make the L2 transactions cheaper and the sequencer would be incentivized to deposit the `BASE_FEE` when it goes up to make sure that it can pay for its L1 gas costs.

**Comment by smartcontracts** [comment]
Closing, won't happen before Bedrock makes this a non-issue
