### ISSUE TITLE
Having issue in generating artifacts

### ISSUE THREAD

**Issue by Ajmali124** [ethereum-optimism/optimism#10155]
I ran this 2 week ago it worked fine but now i m trying to run on Sepolia Testnet but i am getting issue 

muhammadajmal@Muhammads-MacBook-Pro contracts-bedrock % forge script scripts/Deploy.s.sol:Deploy --sig 'sync()' --rpc-url $L1_RPC_URL
[⠆] Compiling...
[⠰] Compiling 1 files with 0.5.17
[⠔] Compiling 331 files with 0.8.15
[⠒] Compiling 135 files with 0.8.19
[⠢] Solc 0.5.17 finished in 40.41ms
[⠊] Solc 0.8.19 finished in 5.77s
[⠒] Solc 0.8.15 finished in 87.40s
Compiler run successful!
Script ran successfully.

== Logs ==
  Connected to network with chainid 11155111
  Storing temp deployment data in /Users/muhammadajmal/optimism/packages/contracts-bedrock/deployments/getting-started/.deploy
  DeployConfig: reading file /Users/muhammadajmal/optimism/packages/contracts-bedrock/deploy-config/getting-started.json
  Deploying from Deploy
  Deployment context: getting-started
  Syncing 27 deployments
  Using deployment artifact /Users/muhammadajmal/optimism/packages/contracts-bedrock/broadcast/Deploy.s.sol/11155111/run-latest.json
  Deploy Tx not found for AddressManager skipping deployment artifact generation
  Deploy Tx not found for DisputeGameFactory skipping deployment artifact generation
  Deploy Tx not found for DisputeGameFactoryProxy skipping deployment artifact generation
  Deploy Tx not found for L1CrossDomainMessenger skipping deployment artifact generation
  Deploy Tx not found for L1CrossDomainMessengerProxy skipping deployment artifact generation
  Deploy Tx not found for L1ERC721Bridge skipping deployment artifact generation
  Deploy Tx not found for L1ERC721BridgeProxy skipping deployment artifact generation
  Deploy Tx not found for L1StandardBridge skipping deployment artifact generation
  Deploy Tx not found for L1StandardBridgeProxy skipping deployment artifact generation
  Deploy Tx not found for L2OutputOracle skipping deployment artifact generation
  Deploy Tx not found for L2OutputOracleProxy skipping deployment artifact generation
  Deploy Tx not found for Mips skipping deployment artifact generation
  Deploy Tx not found for OptimismMintableERC20Factory skipping deployment artifact generation
  Deploy Tx not found for OptimismMintableERC20FactoryProxy skipping deployment artifact generation
  Deploy Tx not found for OptimismPortal skipping deployment artifact generation
  Deploy Tx not found for OptimismPortalProxy skipping deployment artifact generation
  Deploy Tx not found for PreimageOracle skipping deployment artifact generation
  Deploy Tx not found for ProtocolVersions skipping deployment artifact generation
  Deploy Tx not found for ProtocolVersionsProxy skipping deployment artifact generation
  Deploy Tx not found for ProxyAdmin skipping deployment artifact generation
  Deploy Tx not found for SafeProxyFactory skipping deployment artifact generation
  Deploy Tx not found for SafeSingleton skipping deployment artifact generation
  Deploy Tx not found for SuperchainConfig skipping deployment artifact generation
  Deploy Tx not found for SuperchainConfigProxy skipping deployment artifact generation
  Deploy Tx not found for SystemConfig skipping deployment artifact generation
  Deploy Tx not found for SystemConfigProxy skipping deployment artifact generation
  Deploy Tx not found for SystemOwnerSafe skipping deployment artifact generation
  Synced temp deploy files, deleting /Users/muhammadajmal/optimism/packages/contracts-bedrock/deployments/getting-started/.deploy
  
  
  
  I have deployed the contracts successfully 
  
  
 ##
Sending transactions [45 - 45].
⠤ [00:09:38] [#####################################################################################################################################################################################] 46/46 txes (0.0s)##
Waiting for receipts.
⠉ [00:00:13] [###################################################################################################################################################################################] 1/1 receipts (0.0s)
##### sepolia
✅  [Success]Hash: 0xb8dc284fe104c114b522a9e82cc1720a1af0b7ea6523ae507cf4c175883910c2
Block: 5704519
Paid: 0.00013120598489472 ETH (33570 gas * 3.908429696 gwei)

==========================

ONCHAIN EXECUTION COMPLETE & SUCCESSFUL.
Total Paid: 0.129445396874885295 ETH (34057681 gas * avg 3.746442412 gwei)

Transactions saved to: /Users/muhammadajmal/optimism/packages/contracts-bedrock/broadcast/Deploy.s.sol/11155111/run-latest.json

Sensitive values saved to: /Users/muhammadajmal/optimism/packages/contracts-bedrock/cache/Deploy.s.sol/11155111/run-latest.json

i can see the contract in run-latest.json

I don't what i m doing worng

**Comment by tynes** [comment]
Generating artifacts in this style is out of date. No need to call `sync()` anymore, just run the following command:

```bash
forge script -vvv scripts/Deploy.s.sol:Deploy
```

And include `--broadcast` and private key material for live deploys

**Comment by wy51084915** [comment]
> Generating artifacts in this style is out of date. No need to call `sync()` anymore, just run the following command:
> 
> ```shell
> forge script -vvv scripts/Deploy.s.sol:Deploy
> ```
> 
> And include `--broadcast` and private key material for live deploys

i 'm running the command:
`forge script -vvv scripts/Deploy.s.sol:Deploy  --rpc-url $L1_RPC_URL --broadcast --private-key $GS_ADMIN_PRIVATE_KEY `
it seems not work well. Without calling 'sync()', the command is just the same as the deploy command, and no artifacts are generated, which is needed when generating the L2 config files.

**Comment by nitantchhajed** [comment]
you dont need the artifacts anymore to generate the genesis and rollup files. The op-node now takes a new flag `--l1-deploments` which will take a json file as an input like [this](https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/extra/addresses/sepolia/base.json). so just create a json file and put your contract addresses

**Comment by nitantchhajed** [comment]
you can refer to this - https://github.com/ethereum-optimism/developers/discussions/329#discussion-6441347

**Comment by tynes** [comment]
Thanks for the help @nitantchhajed !
