### ISSUE TITLE
Watcher can fail to find transactions in a specific edge-case

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#1018]
**Describe the bug**
The [Watcher utility](https://github.com/ethereum-optimism/optimism/blob/develop/packages/core-utils/src/watcher.ts) can fail to find transactions when transaction volume is particularly high. Here's my best explanation of what's going on:

1. Watcher first tries to find all existing events: https://github.com/ethereum-optimism/optimism/blob/1c1e405cc53c0ef5c0f3e6db471a69a6f1f076fa/packages/core-utils/src/watcher.ts#L76-L91
2. If the watcher can't find the message relay event in historical blocks, it then installs an event listener until the event is found: https://github.com/ethereum-optimism/optimism/blob/1c1e405cc53c0ef5c0f3e6db471a69a6f1f076fa/packages/core-utils/src/watcher.ts#L107-L125

This causes an issue in the following case:
1. Spam a lot of L1 => L2 transactions.
2. Attempt to wait for L1 => L2 transaction N, assume it hasn't been processed yet because L2 geth is still processing all transactions 0...N-1.
3. Assume the highest block at step (1) above is some M < N. Step (1) will NOT find the event for transaction N.
4. Assume that in between step (1) and step (2), transactions M...P, P > N are processed.
5. Step (2) will NOT find the event for transaction N because the listener is installed AFTER the event has already been emitted.

**To Reproduce**
Somewhat difficult to reproduce. I discovered this while working on https://github.com/ethereum-optimism/optimism/pull/971. You can try to reproduce by building that branch and executing [this test](https://github.com/ethereum-optimism/optimism/pull/971/files#diff-0f1742d0ed9aef19c2442abdd9004489ebc95d44dfaf7198344e76735e4fde54R65-R80).

**Expected behavior**
Watcher will find all transactions even in cases of high system load.

**Proposed fix**
Install the listener BEFORE searching for historical transactions. I think. We just need some new code that 100% guarantees that all blocks will be searched. We could also alternatively NOT make use of the listeners and instead simply scan blocks "the old fashioned way" (in ranges of blocks).

**Comment by rajivpo** [comment]
Alright if this is still unclaimed, I'm down to work on it.
