### ISSUE TITLE
Submit L2 -> L2 transfer with 0.015 gwei results in error

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#1026]
This issue is coming from Discord.

**Describe the bug**
I will quote the Discord user @alvaro_villalba's issue below:

> i'm trying to transfer optimistic-kovan ETH from one account to another using metamask. Metamask is suggesting 0.015 gwei gasPrice and 21k gasLimit (which is obviously wrong gaslimit)
> 
> when i try to submit it i get an error that gasLimit should be 4701000, which sounds ok for optimistic, but trying to submit it with 0.015 gwei gasPrice and 4701000 gaslimit i get the following error:
> ```[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"invalid transaction: exceeds block gas limit"}}}'```
> 
> however, if i manually call eth_estimageGas with postman i get a different gasLimit value (3720012) that if i use in metamask, works
> seems like the node response 
> ```[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"fee too low: 315000000000, use at least tx.gasLimit = 4701000 and tx.gasPrice = 15000000"}}}'```
> 
> suggesting a gasLimit is not in sync with the actual gasLimit requirement and is suggesting a higher value
> 
> I've also checked the OVM_CanonicalTransactionChain contract resolved by the AddressManager that gets called when using the standard ETH bridge for optimistic-kovan and seems not to be fed with batches since 8 days ago https://kovan.etherscan.io/address/0x895eabb95d684c15fa46dc00a6b7557450083def
> 
>  is this normal?

**Additional context**
I saw that you (@K-Ho) and Matt worked on a new doc for how gas fees work that sounds a bit familiar to this question, so maybe you can provide some insight here

**Comment by tynes** [comment]
Note that varying L1 gas prices can causes the returned gasLimit to change. Due to the way that the L2 gas limit is scaled down to fit in the lower order bits of the `tx.gasLimit`, it is possible to run into the `Transaction exceeds block gas limit` error pretty easily if the return value of `eth_estimateGas` is not used as `tx.gasLimit`

**Comment by platocrat** [comment]
Should we close this?

**Comment by smartcontracts** [comment]
I'm gonna close this since there's insufficient info to do anything about this now and we're about to move away from this fee scheme anyway.
