### ISSUE TITLE
Function `sync()` is not implemented in your script

### ISSUE THREAD

**Issue by starlzy** [ethereum-optimism/optimism#10303]
when I  deploy a local node with the branch `feat/custom-gas-token`,  I got an error like this:

forge script scripts/Deploy.s.sol:Deploy --sig 'sync()' --rpc-url $L1_RPC_URL

[⠆] Compiling...
No files changed, compilation skipped
Error: 
Function `sync()` is not implemented in your script

**Comment by tynes** [comment]
cc @sbvegan - are we sure that the docs say to check out a particular commit? We can remove calling `sync()` as part of the deployment

**Comment by priyanshuthapliyal55** [comment]
> when I deploy a local node with the branch `feat/custom-gas-token`, I got an error like this:
> 
> forge script scripts/Deploy.s.sol:Deploy --sig 'sync()' --rpc-url $L1_RPC_URL
> 
> [⠆] Compiling... No files changed, compilation skipped Error: Function `sync()` is not implemented in your script

Were you able to deploy with this branch? If yes can you please tell me the step as well? I am also trying to deploy custom erc 20 as a gas token

**Comment by tynes** [comment]
See the setup guide link here: https://github.com/ethereum-optimism/specs/discussions/140#discussion-6530747
