### ISSUE TITLE
op-batcher: Use the new DA server spec

### ISSUE THREAD

**Issue by trianglesphere** [ethereum-optimism/optimism#10312]
With commitment type 0, keccak commitments, the batcher can pre-compute the commitment prior to giving it to the DA server.  With a generic DA commitment, this is not always possible. The batcher should be modified to use the new `put` method which does not pre-compute.

Note: the existing centralized DA server should have to be modified. We made need a new flag here in the batcher to control this behavior.

https://github.com/ethereum-optimism/specs/pull/156 - fixing specs

specs: https://github.com/ethereum-optimism/specs/blob/main/specs/experimental/plasma.md#da-server

**Comment by ethenotethan** [comment]
@trianglesphere would love to take this on!
