### ISSUE TITLE
Broken links to deprecated repo

### ISSUE THREAD

**Issue by m1cm1c** [ethereum-optimism/optimism#1034]
https://community.optimism.io/docs/protocol/protocol.html#bridge-contracts links to https://github.com/ethereum-optimism/contracts/blob/master/contracts/optimistic-ethereum/OVM/bridge/messenging/OVM_L1CrossDomainMessenger.sol which yields a 404. Furthermore, the repo it links to is a deprecated (archived) repo.

**Comment by smartcontracts** [comment]
Good catch, thanks! I'll update the links today.

**Comment by smartcontracts** [comment]
Should be fixed: https://github.com/ethereum-optimism/community-hub/commit/22d2a7f92608fd179e0c966817ec8a07099b9812
