### ISSUE TITLE
Cannot deploy in ops tool L2 chain

### ISSUE THREAD

**Issue by ajsantander** [ethereum-optimism/optimism#1035]
When starting a local L2 chain and attempting to deploy a contract in it, I'm getting the error:
```
Error: Returned Error: invalid transaction: exceeds block gas limit
```

To reproduce, start the ops tool in the latest master commit, and run the following commands in the synthetix project folder  (latest commit in develop):
`npx hardhat test:integration:l2 --compile --deploy`

This is part of our integration tests that run in our CI. The error can be seen in the CI at a commit in our develop branch that passed before:
https://app.circleci.com/pipelines/github/Synthetixio/synthetix/7404/workflows/0ab30bf1-e14c-4f4a-a273-d970002eb3ba/jobs/69611

Using the previous commit in your master branch `86708bb5758cd2b647b3ca2be698beb5aa3af81f` does not produce the error. We don't know if this is the last commit that does not produce the error. Our CI is currently pinned to that commit.

Update: The latest commit that seems to not produce the error is `8082d16c306aab1e53a019ecbce7038d2f1415ca`. However it seems to be producing timeout errors in L1+L2 tests: https://app.circleci.com/pipelines/github/Synthetixio/synthetix/7425/workflows/6745e40d-91b2-48ff-8352-a78e6ca24d0b/jobs/69894 so `86708bb5758cd2b647b3ca2be698beb5aa3af81f` might be more trustworthy.

**Comment by smartcontracts** [comment]
Will look into this today.

**Comment by smartcontracts** [comment]
Actually I have a lot of other priorities to tackle today, will try to get to this tomorrow or thursday but can't promise anything.

**Comment by ajsantander** [comment]
Thanks @smartcontracts !!

**Comment by tynes** [comment]
Are you using `eth_estimateGas` to fill in `tx.gasLimit`? Since the L2 gas limit is encoded and scaled in the lower order bits of `tx.gasLimit`, it is possible to send a transaction with too much gas by setting the lower order bits too high

**Comment by tynes** [comment]
> > Are you using `eth_estimateGas` to fill in `tx.gasLimit`? Since the L2 gas limit is encoded and scaled in the lower order bits of `tx.gasLimit`, it is possible to send a transaction with too much gas by setting the lower order bits too high
> 
> Gas limit is set to max: 8999999

The L2 gas limit is encoded in the lower order bits of `tx.gasLimit`. To decode it, use the formula:

`(tx.gasLimit % 10,000) * 10,000`

Try using `eth_estimateGas` or try `8900999` for a `9990000` L2 gas limit which is below the gas limit of a transaction


Implementations:
- https://github.com/ethereum-optimism/optimism/blob/cc742715ecbca98248367d67f51a5f03038f5ba2/packages/core-utils/src/fees.ts#L46-L52
- https://github.com/ethereum-optimism/optimism/blob/cc742715ecbca98248367d67f51a5f03038f5ba2/l2geth/rollup/fees/rollup_fee.go#L85-L88

**Comment by ajsantander** [comment]
@tynes ok, I gave it a try with lower gas limits, but I get the same `exceeds block gas limit` error.

**Comment by tynes** [comment]
What is the return value of `eth_estimateGas`? Could you provide a repo case?

**Comment by ajsantander** [comment]
Estimate gas returns `12960042`. Which is super weird, because this is a very small contract.

**Comment by ajsantander** [comment]
Oh and @tynes re "Could you provide a repo case?" I've left all the info to reproduce the issue in the description.

**Comment by ajsantander** [comment]
Tweaked it a bit and I seem to be getting deployments thru! Perhaps this means that you guys have compatibility issues with web3?

**Comment by ajsantander** [comment]
This is a Pr showing my changes to get some contracts deployed: https://github.com/Synthetixio/synthetix/pull/1329

**Comment by K-Ho** [comment]
resolved!

**Comment by ajsantander** [comment]
@tynes just discussed with @K-Ho 
It worked with ethers because I was setting the gas to `8000000` instead of `8800999`. So it wasn't really a web3/ethers issue, but a gas issue. I need to understand what L2 gas limit is. I recommended that you guys show a more descriptive error, something like "you're specifying a gas limit of 8800999, which encodes to 89777777 or whatever on L2".
