### ISSUE TITLE
[op-node]  l1.rpckind=reth_db fails even when compiled with rethdb tag

### ISSUE THREAD

**Issue by olivain** [ethereum-optimism/optimism#10365]
Hi there,

On my debian, I followed the instructions of this page: 
https://paradigmxyz.github.io/reth/run/optimism.html
in order to compile op-node locally with the **rethdb-reader** dylib:

```
git clone git@github.com:ethereum-optimism/optimism.git
cd optimism/op-service/rethdb-reader && cargo build --release
cd ../op-node
go build -v -tags rethdb -o ./bin/op-node ./cmd/main.go
mv bin/op-node /usr/bin/op-node

```
 Compilation went well with no issues. But when i try to run op-node with the following flags:

 --l1.rpckind=reth_db --l1.rethdb=/root/.local/share/reth_data/db

op-node fails with the following error :

>  msg="Application failed" message="invalid value \"reth_db\" for flag -l1.rpckind: unknown rpc kind: \"reth_db\""

Is the rethdb-reader still a thing ? is the tutorial i followed outdated ? Is there any way to precise to op-node that the l1 rpc runnng locally is reth ? What am i missing here ?

**Comment by protolambda** [comment]
`--l1.rethdb` has to be set to a non-empty value, and the build flag should be used, for the reth DB to be used. There's no such thing as a `reth_db` RPC Kind as far as I am aware, but this may have been simplified as part of prior reth-db related changes.
