### ISSUE TITLE
op-node: Add the Generic Commitment Type

### ISSUE THREAD

**Issue by trianglesphere** [ethereum-optimism/optimism#10399]
Add support for DA commitment type 1, da-service commitment inside op-node. No validation should be done. It does not need to reach out to the DA server yet.

The purpose of this ticket is to simply create the type that the op-batcher + op-node will use.

https://github.com/ethereum-optimism/specs/blob/main/specs/experimental/plasma.md#input-commitment-submission

**Comment by axelKingsley** [comment]
https://github.com/ethereum-optimism/optimism/pull/10458
