### ISSUE TITLE
Custom gastoken  Withdraw  fail

### ISSUE THREAD

**Issue by dome** [ethereum-optimism/optimism#10422]
Deploy optimism lates develop branch with   
  "useCustomGasToken": true,
  "customGasTokenAddress": "my erc20 token"
deposit work fine but withdraw fail. L1CrossDomainMessengerProxy can't transfer ERC20 out. (got revert)
![Screenshot 2567-05-07 at 01 50 48](https://github.com/ethereum-optimism/optimism/assets/322569/e1a8bf5c-7a8e-42ef-8dfd-26f3b545000c)

**Comment by tynes** [comment]
Can you include a link to your transaction hash?

**Comment by dome** [comment]
https://exp.testnet.jibchain.net/tx/0xf4e5cbaaed3d840d7db32e58411ba2c53f9f6c1ed2ff1a485fee514764cf1993?tab=internal

Can you provide example code for withdraw ?
may be opsdk not support custome token right now.
https://github.com/alt-research/optimism-tutorial/blob/main/cross-dom-bridge-eth/index.js

**Comment by tynes** [comment]
It looks like you are attempting to withdraw through the `L2StandardBridge` - that doesn't work with the native asset on the L2. You will want to send a transaction to the `L2ToL1MessagePasser` [contract](https://github.com/ethereum-optimism/optimism/blob/c41bb739f15005412f227a130474433e168faf8c/packages/contracts-bedrock/src/L2/L2ToL1MessagePasser.sol#L73) to facilicate a withdrawal of the native asset

**Comment by tynes** [comment]
I updated the FAQ in https://github.com/ethereum-optimism/specs/discussions/140 with more information on how to deposit and withdrawal

**Comment by dome** [comment]
Thanks it's work. (littel revert)
https://exp.testnet.jibchain.net/tx/0x1096fa0d522ea088f1d2f200dba461e849984f2231f8e9e9f6ef9a7eac0e746d?tab=internal

**Comment by dome** [comment]
fix in frontend.

**Comment by tynes** [comment]
Can you confirm if this is impacting you? https://github.com/ethereum-optimism/optimism/pull/10440#discussion_r1593150252

**Comment by dome** [comment]
deposit not effect
