### ISSUE TITLE
Inconsistent storage location naming across repo

### ISSUE THREAD

**Issue by pegahcarter** [ethereum-optimism/optimism#10427]
Examples:
https://github.com/ethereum-optimism/optimism/blob/c67c67a8e0781db1092bcc088a529f5195a81587/packages/contracts-bedrock/src/L1/SystemConfig.sol#L75-L78
https://github.com/ethereum-optimism/optimism/blob/c67c67a8e0781db1092bcc088a529f5195a81587/packages/contracts-bedrock/src/L1/SuperchainConfig.sol#L19

**Recommendation:** Use the same style for namespaces across contracts (ideally with ProperCase contracts and camelCase variables [[example]](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/683b6729cd061ceecf0ebdc29b00a01930fcc8e7/contracts/access/AccessControlUpgradeable.sol#L64)).

**Comment by tynes** [comment]
This definitely slipped through review, I think its unlikely that we will migrate away from this now as there are more important things to focus on. You are right its better to standardize
