### ISSUE TITLE
fjord: Use new large RLP limit in the batcher

### ISSUE THREAD

**Issue by trianglesphere** [ethereum-optimism/optimism#10428]
Right now we use the parameter `SafeMaxRLPBytesPerChannel` throughout the op-node channel building & op-batcher. We should remove this constant and use the chain spec instead. The specific timestamp to use is the timestamp of the L1 origin of the newest L2 block in the channel. Technically in derivation the new limit will be applied for channels that get processed after the L1 origin of the CB is past the activation time.

**Comment by BlocksOnAChain** [comment]
@sebastianst should we pick this one up and work on it for Fjord or it's a lower priority item?
