### ISSUE TITLE
Harcoded `DEFAULT_RESOURCE_CONFIG` leads to invalid `ChainAssertion` of upgraded `SystemConfig`

### ISSUE THREAD

**Issue by pegahcarter** [ethereum-optimism/optimism#10426]
The `ChainAssertions` script is, from what I know, one of the best current ways to validate state transition after protocol upgrades.  One issue appears when validating state of the `SystemConfig` after its' values have been changed.  Specifically, `ChainAssertions.checkSystemConfig()` depends on the default values provided:
https://github.com/ethereum-optimism/optimism/blob/29c7b445e17763aee0e73676e19053d08e712821/packages/contracts-bedrock/scripts/ChainAssertions.sol#L80

https://github.com/ethereum-optimism/optimism/blob/29c7b445e17763aee0e73676e19053d08e712821/packages/contracts-bedrock/src/libraries/Constants.sol#L40-L51

This means that if a protocol deploys an op-stack and later updates their resource config, this assertion will fail as it validates state on the original value.

I suggest these values are migrated from hardcoding to imports.

**Comment by tynes** [comment]
These values are hardcoded as we do not recommend changing them from these values. It is possible to create a set of values that breaks deposits
