### ISSUE TITLE
How to set L2_CHAIN_ID before deploying L2 using Custom Gas Token 

### ISSUE THREAD

**Issue by starlzy** [ethereum-optimism/optimism#10448]
CONTRACT_ADDRESSES_PATH=deployments/artifact.json \
DEPLOY_CONFIG_PATH=<PATH_TO_MY_DEPLOY_CONFIG> \
STATE_DUMP_PATH=<PATH_TO_WRITE_L2_ALLOCS> \
  forge script scripts/L2Genesis.s.sol:L2Genesis \
  --sig 'runWithStateDump()' --chain-id $L2_CHAIN_ID

**Comment by tynes** [comment]
The L2 chain id is pulled from the deploy config, see [here](https://github.com/ethereum-optimism/optimism/blob/c41bb739f15005412f227a130474433e168faf8c/packages/contracts-bedrock/deploy-config/mainnet.json#L6)
