### ISSUE TITLE
SDK not working for Mode withdraws

### ISSUE THREAD

**Issue by jtfirek** [ethereum-optimism/optimism#10460]
**Bug Description**
I am using a bot to automate withdraws from a bunch of OP stack chains for our native minting system at ether.fi. The script workings for base and blast, but not for Mode. I have confirmed with their team that the configuration is correct. 

Error throw by the script below
```
Error: withdrawal index 0 out of bounds. There are 0 withdrawals
    at CrossChainMessenger.toCrossChainMessage (/Users/jacobfirek/Desktop/js-bot-runner/node_modules/.pnpm/@eth-optimism+sdk@3.1.0_ethers@5.7.2/node_modules/@eth-optimism/sdk/dist/cross-chain-messenger.js:448:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CrossChainMessenger.getMessageStatus (/Users/jacobfirek/Desktop/js-bot-runner/node_modules/.pnpm/@eth-optimism+sdk@3.1.0_ethers@5.7.2/node_modules/@eth-optimism/sdk/dist/cross-chain-messenger.js:454:26)
    at async checkAndProveMessage (/Users/jacobfirek/Desktop/js-bot-runner/botMode.js:45:32)
```

**Steps to Reproduce**
Here is a simple script I have made that recreates the issue
```
const ethers = require('ethers');
const optimism = require('@eth-optimism/sdk');
require('dotenv').config();

// set up RPC providers, wallets and contract addresses
const l1Provider = new ethers.providers.JsonRpcProvider('https://mainnet.infura.io/v3/3cfca4bf32d54476ae33585ba8983c52');
const modeProvider = new ethers.providers.JsonRpcProvider('https://mode-mainnet.blastapi.io/816787c6-56dc-4717-8354-5f5f4128590b');
const l1Wallet = new ethers.Wallet(process.env.PRIVATE_KEY, l1Provider);
const l2Wallet = new ethers.Wallet(process.env.PRIVATE_KEY, modeProvider);

// configuring mode contracts
const AddressManager = '0x50eF494573f28Cad6B64C31b7a00Cdaa48306e15';
// Proxy addresses below
const L1CrossDomainMessenger = '0x95bDCA6c8EdEB69C98Bd5bd17660BaCef1298A6f';
const L1StandardBridge = '0x735aDBbE72226BD52e818E7181953f42E3b0FF21'; 
const OptimismPortal = '0x8B34b14c7c7123459Cf3076b8Cb929BE097d0C07';
const L2OutputOracle = '0x4317ba146D4933D889518a3e5E11Fe7a53199b04';

// configure the mode messenger
const modeMessenger = new optimism.CrossChainMessenger({
    l1ChainId: 1,
    l2ChainId: 34443,
    l1SignerOrProvider: l1Wallet,
    l2SignerOrProvider: l2Wallet,

    contracts: {
        l1: {
          AddressManager,
          L1CrossDomainMessenger,
          L1StandardBridge,
          OptimismPortal,
          L2OutputOracle,
     
          // Need to be set to zero for this version of the SDK.
          StateCommitmentChain: ethers.constants.AddressZero,
          CanonicalTransactionChain: ethers.constants.AddressZero,
          BondManager: ethers.constants.AddressZero,
        }
      }
});

async function checkAndProveMessage(withdraw) {
    console.log(`Checking message ${withdraw}`);
    try {
        let curMessageStatus = await modeMessenger.getMessageStatus(withdraw);
        console.log(`Message ${withdraw} status: ${optimism.MessageStatus[curMessageStatus]}`);

        if (curMessageStatus === optimism.MessageStatus.READY_TO_PROVE) {
            console.log(`Proving message ${withdraw}`);
            const res = await modeMessenger.proveMessage(withdraw);
            console.log(`Proving result: ${res}`);
        }
    } catch (error) {
        console.error(error);
    }
}

// https://explorer.mode.network/tx/0x803c0fc86ad9d12a42c3cda863971c661943e8be819d353e02d8be6141ffe3e3
checkAndProveMessage('0x803c0fc86ad9d12a42c3cda863971c661943e8be819d353e02d8be6141ffe3e3');
```
**Expected behavior**
It identifies the transaction as a withdraw and begins the proving process.

**Environment Information:**
package.json
```
{
	"dependencies": {
		"ethers": "^5",
		"@eth-optimism/sdk": "3.1.0",
		"dotenv": "^10.0.0"
	}
}
```

**Comment by jtfirek** [comment]
I have found a diff between the mode deployment and other OP stack chains: 

Other OP stack chains have 0x4200000000000000000000000000000000000007 as the L2CrossDomainMessenger address and Mode's is deployed at:
L2CrossDomainMessenger 0xC0d3c0d3c0D3c0D3C0d3C0D3C0D3c0d3c0d30007

Is it possible that this diff is what is causing the SDK to not work for Mode?

**Comment by tynes** [comment]
> I have found a diff between the mode deployment and other OP stack chains:
> 
> Other OP stack chains have 0x4200000000000000000000000000000000000007 as the L2CrossDomainMessenger address and Mode's is deployed at: L2CrossDomainMessenger 0xC0d3c0d3c0D3c0D3C0d3C0D3C0D3c0d3c0d30007
> 
> Is it possible that this diff is what is causing the SDK to not work for Mode?

`0xC0d3c0d3c0D3c0D3C0d3C0D3C0D3c0d3c0d30007` is the implementation and not the proxy. You should interact with `0x4200000000000000000000000000000000000007`.

I am not sure why this problem would exist on mode and not other chains. It is likely a bug in the sdk. cc @smartcontracts. Perhaps something with an off by one 

You should consider using [viem](https://github.com/wevm/viem) for this as the sdk has been deprecated and is no longer maintained

**Comment by jtfirek** [comment]
Do you have any code examples for constructing the proof for withdraws via viem @tynes ?

**Comment by tynes** [comment]
> Do you have any code examples for constructing the proof for withdraws via viem @tynes ?

https://github.com/wevm/viem/blob/d6ae8fa770679306d1eb86b5fb24d3bf2c764aa6/site/pages/op-stack/guides/withdrawals.md

This took a quick search thru their docs page to find

**Comment by jtfirek** [comment]
Thanks
