### ISSUE TITLE
Who pays to relay L2 to L1 transactions on Ethereum?

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#1050]
Coming from Discord:

**Question**
1. Who will pay the fee for submitted a batch of txs to L1? 
Batches are sent by the sequencer, so would it be sequencers who pay the gas on L1?

**Comment by TransmissionsDev** [comment]
sequencers

**Comment by TransmissionsDev** [comment]
you're not giving proper context for the actual question asked here 😅 

the guy who asked thisquestionn is asking about withdrawing an L2 token to L1, not just a general batch of txs

**Comment by TransmissionsDev** [comment]
the answer rn is "anyone" and the sequencer has no obligation or incentive atm— but @ben-chain has talked about working on a paid relay service for it

**Comment by smartcontracts** [comment]
Currently the user who makes the withdrawal will pay for the L2 => L1 transaction.

**Comment by smartcontracts** [comment]
One cool project would be to create a paid relay service where the user pays on L2 when making the withdrawal and a relayer can unlock the funds by proving that they submitted the transaction on L1.

**Comment by smartcontracts** [comment]
Going to close this unless there are further questions.

**Comment by TransmissionsDev** [comment]
> One cool project would be to create a paid relay service where the user pays on L2 when making the withdrawal and a relayer can unlock the funds by proving that they submitted the transaction on L1.

Would y'all accept this as a contribution to the optimism project instead of a whole separate thing? Happy to make a PR sometime

**Comment by smartcontracts** [comment]
@TransmissionsDev absolutely, probably as a replacement for the message-relayer. Hit me on discord and we can chat about it.
