### ISSUE TITLE
out of gas error when calling `debug.traceBlockByNumber`

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#1055]
Coming from Discord user @vegarsti

## Describe the bug
Quoting @vegarsti:
> Hi! I'm trying to call debug.traceBlockByNumber and am getting "Error: out of gas" for some blocks, for instance for block 181 (which seems to correspond to Transaction Index?). But it doesn't look like anything failed based on output here:
> https://optimistic.etherscan.io/tx/0x4e41f7dddd6f5bceacb3782deea6019336696b991611231c141404a2358a5811
> 
> I see that this error is returned several places, but I haven't been able to deduce why it happens here. https://github.com/ethereum-optimism/optimism/search?q=ErrOutOfGas

### Additional context
@vegarsti if there's any other clarifying info you think should be added to this question, feel free to comment below :)

**Comment by smartcontracts** [comment]
I have a feeling this probably doesn't happen in OVM 2.0, but I'm not 100% sure. We should get `debug_trace*` methods covered in CI.

**Comment by smartcontracts** [comment]
We have integration testing around the debug_trace* methods. I don't think this occurs anymore after the OVM 2.0 upgrade, so closing.
