### ISSUE TITLE
Decentralization over `L2OutputOracle.proposer`

### ISSUE THREAD

**Issue by pegahcarter** [ethereum-optimism/optimism#10596]
From my understanding, this state variable is only a single private key as a hex string:
https://github.com/ethereum-optimism/optimism/blob/9300db95bbd721e1700211a3e795b22c8290d780/packages/contracts-bedrock/src/L1/L2OutputOracle.sol#L36-L38

Are there plans to decentralize this privileged role, and if so, what are they?

**Comment by smartcontracts** [comment]
Yes, see the Fault Proofs governance proposal here: https://gov.optimism.io/t/upgrade-proposal-fault-proofs/8161

Check the `OptimismPortal2` and the `DisputeGameFactory`/`FaultDisputeGame` contracts for concrete implementations.

**Comment by tynes** [comment]
If you are running a pre fault proof system, you could imagine setting the `proposer` to a smart contract that has logic around multiple proposers, although it would require custom code. Like @smartcontracts mentioned, the fault proof based system is the real solution to this

**Comment by pegahcarter** [comment]
Makes sense.  Thanks guys.
