### ISSUE TITLE
[Tracker] Release: Upgrade #10

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#10592]
This ticket is meant to operate as a changelog for tracking modifications to smart contracts so that it is easier to create releases. There should be a section for each contract and a table that includes the PR that modifies the contract, the version the contract is updated to as well as a small description of the change.

## Contract Versions

These are the versions of contracts that will be included as part of the release.

| Name       | Version        |
|------------|------------|
| `SystemConfig` | `2.3.0` |
| `OptimismPortal` | `2.8.1` |
| `L1ERC721Bridge` | `2.1.1` |

## SystemConfig

| PR       | Version        | Description         |
|------------|------------|--------------------|
| https://github.com/ethereum-optimism/optimism/pull/10226    | `2.3.0-beta.1`         | Clean Ecotone API           |

## OptimismPortal

| PR       | Version        | Description         |
|------------|------------|--------------------|
| https://github.com/ethereum-optimism/optimism/pull/10585   | `2.8.1-beta.1`         | Overridable `version()`          |

## L1ERC721Bridge

| PR       | Version        | Description         |
|------------|------------|--------------------|
| https://github.com/ethereum-optimism/optimism/pull/10755   | `2.1.1-beta.1`         | Minor type fix          |

**Comment by mds1** [comment]
I've updated the title to `Upgrade #10 Release Tracker`, per the new smart contract versioning rules, since Upgrade #9 (Fjord) is the most recent one

**Comment by tynes** [comment]
Closing this issue because it is out of date
