### ISSUE TITLE
Document on production deployment

### ISSUE THREAD

**Issue by zhiqiangxu** [ethereum-optimism/optimism#10626]
[Here](https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup) is the document on deploying OP Stack, but it has a [callout](https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#build-the-optimism-monorepo) that says this is not for production use.

So I think there should be dedicated documents on production deployment?

**Comment by tynes** [comment]
I added information on this to the contracts package here: https://github.com/ethereum-optimism/optimism/pull/10678

**Comment by tynes** [comment]
I added information on this to the `op-node` package here: https://github.com/ethereum-optimism/optimism/pull/10679

**Comment by zhiqiangxu** [comment]
@tynes Thanks for the update, that's very useful! 

Another big concern for production deployment is how to choose proper configuration values, it will be great if there're guides about this.

**Comment by tynes** [comment]
I recommend checking out the values used by OP Mainnet. Some of the values have since become hardcoded as part of consensus as it only adds cognitive overhead being able to modify them and we found sane values
