### ISSUE TITLE
Error while generating artifacts

### ISSUE THREAD

**Issue by mohit6b** [ethereum-optimism/optimism#10634]
How should I resolve the below bug

1. I have change the IMPL_SALT 3-4 times
2. I have used below commands multiple times
   forge script -vvv scripts/Deploy.s.sol:Deploy --broadcast --private-key $GS_ADMIN_PRIVATE_KEY --rpc-url $L1_RPC_URL
   forge script scripts/Deploy.s.sol:Deploy --sig 'sync()' --rpc-url $L1_RPC_URL
   
   
   
   ├─ [0] VM::envOr("IMPL_SALT", "ethers phoenix")
    │   └─ ← [Return] <env var value>
    ├─ [8937393460513673534] Create2Deployer::create2()
    │   ├─ [8937393460513640213] → new <unknown>@0x3Fb409AF4E0EC3a2a49554DC82f106C315BE88F7
    │   │   └─ ← [CreateCollision] 0 bytes of code
    │   └─ ← [Revert] EvmError: Revert
    └─ ← [Revert] EvmError: Revert

== Logs ==
  Connected to network with chainid 11155111
  Storing temp deployment data in /Users/mohitvashistha/optimism/packages/contracts-bedrock/deployments/getting-started/.deploy
  DeployConfig: reading file /Users/mohitvashistha/optimism/packages/contracts-bedrock/deploy-config/getting-started.json
  Deploying from Deploy
  Deployment context: getting-started
  Deploying a fresh OP Stack including SuperchainConfig
  Deploying Safe
  New SystemOwnerSafe deployed at 0xba5FDa07E6Ca1697a728A65f8CbB76B3E370b952
  Setting up Superchain
  Deploying AddressManager
  AddressManager deployed at 0x3aF5571A355e45D5473B82121993B0de618D602e
  Deploying ProxyAdmin
  ProxyAdmin deployed at 0x4b644d8B30c621403287726Ca6644811974b02BF
  ProxyAdmin ownership transferred to Safe at: 0xba5FDa07E6Ca1697a728A65f8CbB76B3E370b952
  Deploying ERC1967 proxy forSuperchainConfigProxy
     at 0x1A4282176226583FB1C39B812c213f8A472A0586
Error: 
script failed: <empty revert data>
<img width="952" alt="Screenshot 2024-05-24 at 1 02 18 AM" src="https://github.com/ethereum-optimism/optimism/assets/26293267/bbd64841-58b0-42c5-8715-563101553e07">

**Comment by tynes** [comment]
Are you sure the `IMPL_SALT` is different? We really need a way to just deploy proxies and configure them to the shared implementations

**Comment by mohit6b** [comment]
Yes, I am sure IMPLT_SALT is different.
I tried all these below values but still getting the same above error. I am using "tutorials/chain" branch

export IMPL_SALT=$(openssl rand -hex 32)
export IMPL_SALT=$(openssl rand -hex 64)
export IMPL_SALT=$(openssl rand -hex 128)
export IMPL_SALT=$(openssl rand -hex 32768)
export IMPL_SALT=$(openssl rand -hex 9899)
export IMPL_SALT=$(openssl rand -hex 91357)
export IMPL_SALT=$(openssl rand -hex 76426)
export IMPL_SALT=$(openssl rand -hex 33554431)

**Comment by InoMurko** [comment]
Similar issue here:
running 1.7.6
```
    ├─ [8937393460516496946] 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2::createProxyWithNonce(0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552, 0xb63e800d0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000005c51ae978595a5c367ac03ca5e33bd6cb4b876f20000000000000000000000000000000000000000000000000000000000000000, 57493239949579596273554895313127079449756098686046701190193136806895817983202 [5.749e76])
    │   ├─ [8937393460516461789] → new <unknown>@0x25Facc9A623Ea37609d2293C3413a11E709795f9
    │   │   └─ ← [CreateCollision] 0 bytes of code
    │   └─ ← [Revert] revert: Create2 call failed
    └─ ← [Revert] revert: Create2 call failed
```

<img width="924" alt="image" src="https://github.com/ethereum-optimism/optimism/assets/2582555/e6b93672-fcf8-450e-8ae0-7f4236dd812a">


```
IMPL_SALT=$(openssl rand -hex 32) DEPLOYMENT_CONTEXT=deployer DEPLOY_CONFIG_PATH=deploy-config/deployer.json forge script -vvv scripts/Deploy.s.sol:Deploy ...
```

**Comment by tynes** [comment]
This looks like its an issue with the deployment of the safe, its not the implementations that are clashing but the safe. This is something that needs to be fixed. cc @maurelian

**Comment by mohit6b** [comment]
Okay. Can you please suggest an alternative till it gets fixed? @tynes 
I am also trying with branch "op-contracts/v1.3.0" but getting the same issue.

**Comment by tynes** [comment]
Try https://github.com/ethereum-optimism/optimism/pull/10660

**Comment by mohit6b** [comment]
Okay, thanks. Let me try this one.
Should i use --sig 'sync()' function or not?

**Comment by tynes** [comment]
> Should i use --sig 'sync()' function or not?

This has been deprecated, you shouldn't need to call that function. See [this](https://oplabs.notion.site/EXTERNAL-How-to-run-a-Custom-Gas-Token-chain-d88c68306f934790be051f87213a0b1d) document for updated instructions, these should be reflected in our devdocs soon

**Comment by mohit6b** [comment]
The script is still failing and I am getting below error.

Also, it only allows for sepolia in deploy-config. How should I configure my custom testnet?



 │   │   │   │   │   ├─ [427] 0x2f5497904A8Dc32F078AfF9eFB5e061015367836::decimals() [staticcall]
    │   │   │   │   │   │   └─ ← [Return] 18
    │   │   │   │   │   ├─ [3421] 0x2f5497904A8Dc32F078AfF9eFB5e061015367836::name() [staticcall]
    │   │   │   │   │   │   └─ ← [Return] "Op Token"
    │   │   │   │   │   ├─ [3464] 0x2f5497904A8Dc32F078AfF9eFB5e061015367836::symbol() [staticcall]
    │   │   │   │   │   │   └─ ← [Return] "OPT"
    │   │   │   │   │   ├─ [707] Proxy::setGasPayingToken(0x2f5497904A8Dc32F078AfF9eFB5e061015367836, 18, 0x4f7020546f6b656e000000000000000000000000000000000000000000000000, 0x4f50540000000000000000000000000000000000000000000000000000000000)
    │   │   │   │   │   │   ├─ [212] OptimismPortal2::setGasPayingToken(0x2f5497904A8Dc32F078AfF9eFB5e061015367836, 18, 0x4f7020546f6b656e000000000000000000000000000000000000000000000000, 0x4f50540000000000000000000000000000000000000000000000000000000000) [delegatecall]
    │   │   │   │   │   │   │   └─ ← [Revert] EvmError: Revert
    │   │   │   │   │   │   └─ ← [Revert] EvmError: Revert
    │   │   │   │   │   └─ ← [Revert] EvmError: Revert
    │   │   │   │   └─ ← [Revert] revert: Proxy: delegatecall to new implementation contract failed
    │   │   │   └─ ← [Revert] revert: Proxy: delegatecall to new implementation contract failed
    │   │   └─ ← [Revert] revert: GS013
    │   └─ ← [Revert] revert: GS013
    └─ ← [Revert] revert: GS013



== Logs ==
  Writing artifact to deployments/artifact.json
  Connected to network with chainid 11155111
  Commit hash: ��vAVqy���������
  DeployConfig: reading file /Users/mohitvashistha/optimism/packages/contracts-bedrock/deploy-config/sepolia.json
  Deploying a fresh OP Stack including SuperchainConfig
  start of L1 Deploy!
  Deploying Safe
  Saving SafeProxyFactory: 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2
  Saving SafeSingleton: 0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552
  Saving SystemOwnerSafe: 0x076246e59A402cdc80D1D9923E5629DC659C5045
  New safe: SystemOwnerSafe deployed at 0x076246e59A402cdc80D1D9923E5629DC659C5045
    Note that this safe is owned by the deployer key
  deployed Safe!
  Setting up Superchain
  Deploying AddressManager
  Saving AddressManager: 0x4994F291bb9910fE6Aa3B1085180192b52E0490b
  AddressManager deployed at 0x4994F291bb9910fE6Aa3B1085180192b52E0490b
  Deploying ProxyAdmin
  Saving ProxyAdmin: 0x5434DD370992B5FC72a6F0aaF70Dd81E2cb3E802
  ProxyAdmin deployed at 0x5434DD370992B5FC72a6F0aaF70Dd81E2cb3E802
  ProxyAdmin ownership transferred to Safe at: 0x076246e59A402cdc80D1D9923E5629DC659C5045
  Deploying ERC1967 proxy for SuperchainConfigProxy
  Saving SuperchainConfigProxy: 0xE9c13dA229b6865da0AC0a345fd34a945253939A
     at 0xE9c13dA229b6865da0AC0a345fd34a945253939A
  Saving SuperchainConfig: 0x3C63FDeE5DA2781dCc23a34F817071aE47277727
  SuperchainConfig deployed at 0x3C63FDeE5DA2781dCc23a34F817071aE47277727
  Running chain assertions on the SuperchainConfig
  Deploying ERC1967 proxy for ProtocolVersionsProxy
  Saving ProtocolVersionsProxy: 0xFd3f08CBc07753F9AE29EAFC9ea5793e539Bc878
     at 0xFd3f08CBc07753F9AE29EAFC9ea5793e539Bc878
  Deploying ProtocolVersions implementation
  Saving ProtocolVersions: 0xC5c9BB5434612250b78b07BCB2287166152d972E
  ProtocolVersions deployed at 0xC5c9BB5434612250b78b07BCB2287166152d972E
  Running chain assertions on the ProtocolVersions
  Upgrading and initializing ProtocolVersions proxy
  ProtocolVersions version: 1.0.0
  Running chain assertions on the ProtocolVersions
  set up superchain!
  Deploying OP Chain
  Deploying proxies
  Deploying ERC1967 proxy for OptimismPortalProxy
  Saving OptimismPortalProxy: 0xbF243F9462EB1de5e8824e6baB60b43cAB39cA9A
     at 0xbF243F9462EB1de5e8824e6baB60b43cAB39cA9A
  Deploying ERC1967 proxy for SystemConfigProxy
  Saving SystemConfigProxy: 0x75917B7F267F47c2fFF6ad196E6516754eDf39e2
     at 0x75917B7F267F47c2fFF6ad196E6516754eDf39e2
  Deploying proxy for L1StandardBridge
  Saving L1StandardBridgeProxy: 0x24214FE6FF029E98A67eeE3b33adA694BD4a533a
  L1StandardBridgeProxy deployed at 0x24214FE6FF029E98A67eeE3b33adA694BD4a533a
  Deploying proxy for L1CrossDomainMessenger
  Saving L1CrossDomainMessengerProxy: 0x3BB0353Cecc69E00B8Ba560F8143a1b6277f1c2E
  L1CrossDomainMessengerProxy deployed at 0x3BB0353Cecc69E00B8Ba560F8143a1b6277f1c2E
  Deploying ERC1967 proxy for OptimismMintableERC20FactoryProxy
  Saving OptimismMintableERC20FactoryProxy: 0x48b224034DA08140001A2Ab5dBd2C0c0248Fa178
     at 0x48b224034DA08140001A2Ab5dBd2C0c0248Fa178
  Deploying ERC1967 proxy for L1ERC721BridgeProxy
  Saving L1ERC721BridgeProxy: 0xd0D0bAA677Dea50ba0d74FD75e35D2593C6D6080
     at 0xd0D0bAA677Dea50ba0d74FD75e35D2593C6D6080
  Deploying ERC1967 proxy for DisputeGameFactoryProxy
  Saving DisputeGameFactoryProxy: 0xbCBfd98B1a6e0dD8D28E24D0B00Cf038Dbe8b487
     at 0xbCBfd98B1a6e0dD8D28E24D0B00Cf038Dbe8b487
  Deploying ERC1967 proxy for L2OutputOracleProxy
  Saving L2OutputOracleProxy: 0x2FE5ed399dd9C14408D2b00F61e6d3868Bea656c
     at 0x2FE5ed399dd9C14408D2b00F61e6d3868Bea656c
  Deploying ERC1967 proxy for DelayedWETHProxy
  Saving DelayedWETHProxy: 0x1bc6daf1950A4Eb7c5db16ff7B4FCCe13Ab56052
     at 0x1bc6daf1950A4Eb7c5db16ff7B4FCCe13Ab56052
  Deploying ERC1967 proxy for AnchorStateRegistryProxy
  Saving AnchorStateRegistryProxy: 0x6a488E1A84C6dE3A2DB8D04CEd5FE52d0D94D4b1
     at 0x6a488E1A84C6dE3A2DB8D04CEd5FE52d0D94D4b1
  Transferring AddressManager ownership to ProxyAdmin
  AddressManager ownership transferred to 0x5434DD370992B5FC72a6F0aaF70Dd81E2cb3E802
  Deploying implementations
  Deploying L1CrossDomainMessenger implementation
  Saving L1CrossDomainMessenger: 0xf54d8C2377448A188Eee08CaED4ff70D612dc42a
  L1CrossDomainMessenger deployed at 0xf54d8C2377448A188Eee08CaED4ff70D612dc42a
  Running chain assertions on the L1CrossDomainMessenger
  Deploying OptimismMintableERC20Factory implementation
  Saving OptimismMintableERC20Factory: 0x13865c6A1bDad1708F3CE7A097eeee79a60071B2
  OptimismMintableERC20Factory deployed at 0x13865c6A1bDad1708F3CE7A097eeee79a60071B2
  Running chain assertions on the OptimismMintableERC20Factory
  Deploying SystemConfig implementation
  Saving SystemConfig: 0xC829e6A687bb3dC85148bCD41e439C05714D3adA
  SystemConfig deployed at 0xC829e6A687bb3dC85148bCD41e439C05714D3adA
  Running chain assertions on the SystemConfig
  Deploying L1StandardBridge implementation
  Saving L1StandardBridge: 0x6d84EDb112Ca1C012C1b8832202845b51CbE1C1B
  L1StandardBridge deployed at 0x6d84EDb112Ca1C012C1b8832202845b51CbE1C1B
  Running chain assertions on the L1StandardBridge
  Deploying L1ERC721Bridge implementation
  Saving L1ERC721Bridge: 0x2E83D8E3557C17B434FCB88F182CF730379B2fe5
  L1ERC721Bridge deployed at 0x2E83D8E3557C17B434FCB88F182CF730379B2fe5
  Running chain assertions on the L1ERC721Bridge
  Deploying OptimismPortal implementation
  Saving OptimismPortal: 0x7E17F3b7F2245648F4A82c0760875FbC0E110A15
  OptimismPortal deployed at 0x7E17F3b7F2245648F4A82c0760875FbC0E110A15
  Running chain assertions on the OptimismPortal
  Guardian has no code: 0xfd1D2e729aE8eEe2E146c033bf4400fE75284301
  Deploying L2OutputOracle implementation
  Saving L2OutputOracle: 0x1Cf3815989cbEd3d81c41Fa98E775d8F77eF1429
  L2OutputOracle deployed at 0x1Cf3815989cbEd3d81c41Fa98E775d8F77eF1429
  Running chain assertions on the L2OutputOracle
  Deploying OptimismPortal2 implementation
  Saving OptimismPortal2: 0x513E2C5beE10F32346D33243Ba1fD87B87667B49
  OptimismPortal2 deployed at 0x513E2C5beE10F32346D33243Ba1fD87B87667B49
  Running chain assertions on the OptimismPortal2
  Guardian has no code: 0xfd1D2e729aE8eEe2E146c033bf4400fE75284301
  Deploying DisputeGameFactory implementation
  Saving DisputeGameFactory: 0xD65D3789384Efb31FcD6a8D694C43D49C0D33356
  DisputeGameFactory deployed at 0xD65D3789384Efb31FcD6a8D694C43D49C0D33356
  Running chain assertions on the DisputeGameFactory
  Deploying DelayedWETH implementation
  Saving DelayedWETH: 0xa0C58eB144EeC561d698fFCB192cB02baa333A8A
  DelayedWETH deployed at 0xa0C58eB144EeC561d698fFCB192cB02baa333A8A
  Running chain assertions on the DelayedWETH
  Deploying PreimageOracle implementation
  Saving PreimageOracle: 0x2f669A729e40A8006eFac22bBDA515d21A12643D
  PreimageOracle deployed at 0x2f669A729e40A8006eFac22bBDA515d21A12643D
  Deploying Mips implementation
  Saving Mips: 0x868a938026ffc715514f7bC82AD962440be91860
  MIPS deployed at 0x868a938026ffc715514f7bC82AD962440be91860
  Deploying AnchorStateRegistry implementation
  Saving AnchorStateRegistry: 0x5c8e5A31f53Bd6E0bB9694a142c3353750605a21
  AnchorStateRegistry deployed at 0x5c8e5A31f53Bd6E0bB9694a142c3353750605a21
  Initializing implementations
  WARNING: FPAC is enabled. Initializing the OptimismPortal proxy with the OptimismPortal2.
  Upgrading and initializing OptimismPortal2 proxy
  OptimismPortal2 version: 3.8.0
  Running chain assertions on the OptimismPortal2
  Guardian has no code: 0xfd1D2e729aE8eEe2E146c033bf4400fE75284301
  Upgrading and initializing SystemConfig proxy
Error: 
script failed: revert: GS013
