### ISSUE TITLE
Generate the bytecode of contracts via `snapshots` command

### ISSUE THREAD

**Issue by lesterli** [ethereum-optimism/optimism#10656]
**Is your feature request related to a problem? Please describe.**
Currently, the [snapshots script](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/scripts/autogen/generate-snapshots.ts) does not generate the bytecode of contracts. This omission causes issues in tests that rely on the deploy method in the Go bindings file, which is generated with the bytecode(via `abigen --bin <bytecode>`). 

**Describe the solution you'd like**
I would like the snapshots script to be updated to include the generation of contract bytecode. E.g. our [PR](https://github.com/babylonchain/optimism/pull/4) updated the script.

**Describe alternatives you've considered**
Maybe update the test function that does not call the deploy method in the Go bindings file. E.g. for the [abi_test.go](https://github.com/babylonchain/optimism/blob/develop-babylon/op-proposer/proposer/abi_test.go#L42) in the `op-proposer`. Does anyone know if this is possible to update these test codes?

**Additional context**
The previous Go bindings [generation script](https://github.com/ethereum-optimism/optimism/blob/op-bindings/v0.10.14/op-bindings/gen_bindings.sh#L41) always generates the bytecode.

**Comment by tynes** [comment]
We do not want to check bytecode into the repo itself as that creates large and unnecessary diffs. It was a massive pain for devs to maintain the `op-bindings` package which is why it was deleted. It is not up to individual services to generate bindings, see this [justfile](https://github.com/babylonchain/optimism/blob/7cbda018196b58a71e2c0b4bc9e31a289235074e/op-chain-ops/justfile) for an example of how to do so. We no longer need the bytecode as the L2 genesis is created using a foundry script

**Comment by lesterli** [comment]
@tynes Thanks for your reply. 
But how to handle the case that needs the deploy method in the Go bindings file? E.g. for the [abi_test.go](https://github.com/ethereum-optimism/optimism/blob/develop/op-proposer/proposer/abi_test.go#L42) in the op-proposer, this test function calls the deploy method `bindings.DeployL2OutputOracle(opts, backend)` which is in the [bindings](https://github.com/ethereum-optimism/optimism/blob/develop/op-e2e/bindings/l2outputoracle.go#L53). If using the justfile you mention to generate bindings file, it would not generate this deploy method. To generate the deploy method it needs to run `abigen` with the option `--bin <bytecode>`.

**Comment by tynes** [comment]
The maintainers of that service will need to regenerate their bindings with new bytecode. I don't recommend following that sort of pattern for unit tests, `op-e2e` is guaranteed to have the latest bytecode present. Its possible to update the example that I linked with a `--bin $(jq .bytecode < forge-artifact.json)` flag (just an example, would need to build the right `jq` query). That is an old test and the e2e tests do cover submitting outputs to the `L2OutputOracle`. Once fault proofs are live, we will delete the `L2OutputOracle` from the codebase as it will be considered legacy. There is a permissioned fault proof game type that offers similar security properties as the existing `L2OutputOracle`

**Comment by lesterli** [comment]
Got it, thanks.

**Comment by bap2pecs** [comment]
thanks @tynes for the quick response! a few more questions:

1. do you know when we can expect the fault proof be ready (roughly)?
2. it's likely we can't wait for the fault proof. in this case, which branch do you recommend us to build upon?
3. is there anything we can read to understand the new system architecture? will there still be the 4 components (e.g. op-geth, op-node, op-submitter, op-proposer)?
4. how will fault proof affect existing OP Stack based L2s? will is be easy for them to upgrade or do you expect most of them still will be on the legacy version for a while?

happy to chat more to give you more context on what we are building. my TG: zidongz

**Comment by tynes** [comment]
The fault proof release is currently out for [governance vote](https://gov.optimism.io/t/final-protocol-upgrade-7-fault-proofs/8161). This should contain details about how the system is changing. See the [docs](https://docs.optimism.io/stack/protocol/fault-proofs/overview) for more information. If the vote passes, then it will go live within 2-3 weeks on OP Mainnet. It has been live on our testnet for some time. The upgrade code can be found in https://github.com/ethereum-optimism/superchain-ops/pull/206. It should be possible for OP Stack chains to inherit our work depending on the sorts of changes to the codebase that were made. Chains that opt into revenue share for retroPGF will receive more help with the upgrade

**Comment by bap2pecs** [comment]
thanks @tynes! we will start to look into the links you shared here

**Comment by lesterli** [comment]
It works fine @tynes suggestions. Close it.
