### ISSUE TITLE
challenger: Deduplicate code between cannon and asterisc integrations

### ISSUE THREAD

**Issue by ajsutton** [ethereum-optimism/optimism#10652]
There is a significant amount of shared code between the cannon and asterisc trace provider types that we should look to deduplicate. In particular around snapshot and prestate management.

We should work through this in small steps, not try to deduplicate everything at once. Likely need a shared module (currently have some shared code in `util` but that's not a great name).

**Comment by estensen** [comment]
I would love to work on this

**Comment by ajsutton** [comment]
Closing this - we've deduplicated a lot of the code and I think it's generally got a good balance between avoiding duplicate code and yet not conflating different concepts which happen to be able to share code currently.  The balance is definitely not set in stone, but we don't need to track this as an issue to work on now.
