### ISSUE TITLE
Question: how can I track L1 gas usage?

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#1068]
Question coming from @0xOsprey from discord.

**Question**
He is looking to track our gas usage on L1 to help create gas simulations.

> 1. I want to do some simulations/put together a piece that looks at some potential usage situations around the end of the summer and how that translates to L1 gas

**Additional context**
@0xOsprey feel free to add more info here that you think is missing :D

**Comment by smartcontracts** [comment]
@0xOsprey what sort of information are you looking to track? Maybe I can point you in the right direction.

**Comment by smartcontracts** [comment]
Closing this for now since @0xOsprey has not provided any additional context. I'm happy to open this issue back up if it's still relevant.
