### ISSUE TITLE
Flickering test: hardhat-example

### ISSUE THREAD

**Issue by snario** [ethereum-optimism/optimism#1069]
```
TransactionExecutionError: Assertion failed
```

Example: https://github.com/ethereum-optimism/optimism/pull/1066/checks?check_run_id=2805582378

**Comment by smartcontracts** [comment]
#1071 "fixes" this in the sense that it temporarily disables the tests. We need a real fix eventually, though.

**Comment by smartcontracts** [comment]
We removed this from the monorepo
