### ISSUE TITLE
DockerFiles mising in v1.76 Release

### ISSUE THREAD

**Issue by nitantchhajed** [ethereum-optimism/optimism#10699]
I want to build Docker Images of op-node, op-batcher, op-proposer on local, but the DockerFiles are not present in respective op-node, op-batcher, op-proposer directories anymore. 
I built the image for op-stack-go on local from `ops/docker/op-stack-go/DockerFile` .

**Comment by ajsutton** [comment]
The docker builds are done via the `docker-bake.hcl` in the top level of the repository.  Simplest option to build them is to run `make golang-docker` in the top level dir.
