### ISSUE TITLE
Warn or throw an error when sequencer and proposer addresses are the same

### ISSUE THREAD

**Issue by cby3149** [ethereum-optimism/optimism#1072]
When the batch submitter submits tx batches and state root batches, it might have the nonce error.
The problem is cause by running the two submitters at the same time, so both submitters might use the same nonce to submit the batches.
https://github.com/ethereum-optimism/optimism/blob/85362d44fc13966f00bee26172dd04e6a442a6c6/packages/batch-submitter/src/exec/run-batch-submitter.ts#L457-L462

**Comment by smartcontracts** [comment]
The batch submitter is (unfortunately) poorly documented. You should set both of these environment variables with *different* keys to avoid getting nonce errors:

https://github.com/ethereum-optimism/optimism/blob/85362d44fc13966f00bee26172dd04e6a442a6c6/packages/batch-submitter/src/exec/run-batch-submitter.ts#L60-L61

**Comment by smartcontracts** [comment]
We will be working on improving the batch submitter over the coming months, improvements and refactors are always welcome.

**Comment by smartcontracts** [comment]
Ideally we throw an error (or at least give a warning) when `sequencerAddress == proposerAddress`
