### ISSUE TITLE
Verifier runs in Sequencer mode

### ISSUE THREAD

**Issue by CAPtheorem** [ethereum-optimism/optimism#1076]
**Describe the bug**
Using the standard command for spinning up the system with a Verifier, (`docker-compose up --scale verifier=1 --build`), a second gethl2 starts called "verifier_1", but based on its debug output and behavior, it thinks it's a sequencer, leading to confusion for all parties. 

**To Reproduce**
1. Run `docker-compose up --scale verifier=1 --build` per Readme.
2. Inspect system log output: 
```
verifier_1           | INFO [06-13|00:49:53.875] Regenerated local transaction journal    transactions=0 accounts=0
verifier_1           | INFO [06-13|00:49:53.875] Running in sequencer mode                sync-backend=l1
verifier_1           | INFO [06-13|00:49:53.875] Sanitizing timestamp refresh threshold to 3 minutes 
```

**Expected behavior**
Running `docker-compose up --scale verifier=1` should yield a system with **one** sequencer and **one** verifier.

**Fix**
In the `docker-compose.yaml`, replace `IS_VERIFIER: "true"` with `ROLLUP_VERIFIER_ENABLE: "true"`

**Comment by snario** [comment]
There is a PR fixing this currently under review: https://github.com/ethereum-optimism/optimism/pull/981/

**Comment by CAPtheorem** [comment]
Great, thanks!

**Comment by smartcontracts** [comment]
cc @annieke @tynes is this issue fixed?

**Comment by annieke** [comment]
yup fixed with the linked PR! thanks for catching
