### ISSUE TITLE
failed transaction error when sending an L2 tx using Metamask

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#1078]
Coming from Discord user @yipikaye

**Describe the bug**
Quoting from Discord:
> I'm not too sure how to get the full message from windows we use for development at work :pensive: I an 99% sure it's complaining the gas fee calculation is wrong but when I use the bare minimum or something really high it gives same error. I can reproduce by trying to transfer any token. Weth, my own or even updating a contract

**Additional context**
![image](https://user-images.githubusercontent.com/37757724/121825562-c1882900-cc78-11eb-9d2a-588d73d1d5ce.png)

@yipikaye if there's any additional info you think would be helpful, don't hesitate to comment below! :)

**Comment by yipikaye** [comment]
I can reproduce this error by doing the following:

1. Transfer tokens "Blocks" from Owner to any wallet
2. Transfer between wallets works fine
3. Transfer back to owner fails

It seems etherscan is down so i cannot get more info. Attached are some screenshots of the working transactions and the failed transactions x2.

Sample transfer between wallets OK
![Transfer 1](https://user-images.githubusercontent.com/12209170/121842197-521b4380-cd23-11eb-9b78-66434538b90e.png)
![Transfer 2](https://user-images.githubusercontent.com/12209170/121842203-547d9d80-cd23-11eb-949e-12a5ace42251.png)
![Transfer 3 (worked)](https://user-images.githubusercontent.com/12209170/121842212-57788e00-cd23-11eb-9bc0-0f135d724317.png)


Sample transfer to owner x2
![Failed Transfer](https://user-images.githubusercontent.com/12209170/121842236-65c6aa00-cd23-11eb-88ff-d3ddf62bdbbc.png)
![Failed Transfer 2](https://user-images.githubusercontent.com/12209170/121842246-69f2c780-cd23-11eb-9e22-6ed99a4a8d18.png)

Error:
![Error](https://user-images.githubusercontent.com/12209170/121842257-6f501200-cd23-11eb-8a83-1dee5d8f7840.png)

**Comment by smartcontracts** [comment]
I believe this is fixed in OVM 2.0. Going to close this issue. Happy to reopen if someone else finds the same issue.
