### ISSUE TITLE
`make test-unit` fails in latest release

### ISSUE THREAD

**Issue by fahimahmedx** [ethereum-optimism/optimism#10803]
**Bug Description**
5 sub-tests of 1 test fail when running `make test-unit`.

**Steps to Reproduce**
`pnpm install`
`make test-unit`

**Environment Information:**
 - Operating System: MacOS Sonoma 14.5
 - Package Version (or commit hash): optimism 384e2dc

**Logs:**

      Failing tests:
      Encountered 1 failing test in test/Safe/DeputyGuardianModule.t.sol:DeputyGuardianModule_NoPortalCollisions_Test
      [FAIL. Reason: FfiFailed("Command: bash -c jq '.methodIdentifiers | keys' < /Users/fahimahmed/projects/optimism/packages/contracts-bedrock/forge-artifacts/Errors.sol/Errors.json \nError: jq: error (at <stdin>:0): null (null) has no keys\n")] test_noPortalCollisions_succeeds() (gas: 1054500)
      
      Encountered 1 failing test in test/dispute/FaultDisputeGame.t.sol:FaultDisputeGame_Test
      [FAIL. Reason: expected call to 0x4ABBBC7A947c5EF1F22b604B8ed8ddF5e31Ad131 with data 0x6361506d7fa9385be102ac3eac297483dd6233d62b3e1496010000000000000000000000000000000000000000000000000000000000000ac89efdaa54c0f20c7adf612882df0950f5a951637e0307cdcb4c672f298b8bc60000000000000000000000000000000000000000000000000000000000000010 to be called 1 time, but was called 0 times] test_cwiaCalldata_userCannotControlSelector_succeeds() (gas: 24611)
      
      Encountered 2 failing tests in test/legacy/ResolvedDelegateProxy.t.sol:ResolvedDelegateProxy_Test
      [FAIL. Reason: expected call to 0x2e234DAe75C793f67A35089C9d99245E1C58470b with data 0x2fbebd389b2ea4bcffffffffffffffffffffffffffffffffffffffffffffffffffffffff to be called 1 time, but was called 0 times; counterexample: calldata=0xdee955099b2ea4bcffffffffffffffffffffffffffffffffffffffffffffffffffffffff args=[70190903477216889620958137006540445838647024586572570533902173535105653407743 [7.019e76]]] testFuzz_fallback_delegateCallFoo_succeeds(uint256) (runs: 0, μ: 0, ~: 0)
      [FAIL. Reason: expected call to 0x2e234DAe75C793f67A35089C9d99245E1C58470b with data 0xfebb0f7e to be called 1 time, but was called 0 times] test_fallback_delegateCallBar_reverts() (gas: 24780)
      
      Encountered 1 failing test in test/periphery/Transactor.t.sol:TransactorTest
      [FAIL. Reason: expected call to 0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f with data 0xafc874d2 to be called 1 time, but was called 0 times] test_delegateCall_succeeds() (gas: 20910)
      
      Encountered a total of 5 failing tests, 1364 tests succeeded

**Comment by tynes** [comment]
Appreciate you opening this issue. Its likely that these are flakes as the tests do pass in CI

**Comment by tynes** [comment]
Closing this due to the tests all passing in CI
