### ISSUE TITLE
op plasma finalize stucked

### ISSUE THREAD

**Issue by 0xyjk** [ethereum-optimism/optimism#10824]
**Bug Description**
finalize won't increase when using plasma mode and set batcher max pending tx > 1

**Steps to Reproduce**
1. set batcher's `--max-pending-tx` > 1
2. let batcher submit multiple txs in the same block
3. op node finalize will stuck at this block

**Environment Information:**
 - Package Version: op-node v1.7.6, op-batcher v1.7.6
 
**Additional context**
more details can be found in https://github.com/ethereum-optimism/optimism/pull/10392 comments

**Comment by tynes** [comment]
Your PR was auto closed from being stale, I reopened it. Closing this issue
