### ISSUE TITLE
GovToken: Implement with `GovernanceDelegation`

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#10862]
# Definition of Done

Fully implemented and tested GovToken that exists in the monorepo. This should follow the "solidity feature development plan" noted in https://github.com/ethereum-optimism/design-docs/pull/8 so that we don't modify the existing GovToken yet. We will modify the existing GovToken in the future.

The testing should ensure to cover the invariants defined in the spec

Assume specs are complete. Use spec to drive code review.

## Decisions
- Make alligator a predeploy
- Use the hook based approach in the GovToken to update alligator

### How to Handle GovToken
- Update existing `GovToken` with overrides (no diff to bytecode so backwards compatible)
- Add alligator to `Predeploys` library - used in on token transfer hook
- Create a `GovTokenInterop` contract that inherits from `GovToken`
- Unit test that the hook makes a call
  - The specific call might need to be modified in the future when we pull alligator in as a predeploy
- Bump version on `GovToken` or add a semver if it doesn't yet exist using the `-beta.1+interop` suffix
  - We want to be backwards compatible, so this needs to live on `GovTokenInterop` if there isn't semver on `GovToken` today
- Update semver lock

**Comment by 0xfuturistic** [comment]
implementing on this branch: https://github.com/voteagora/governor/pull/28
