### ISSUE TITLE
Design doc todo: concrete deploy-config changes

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#10878]
Based on ideas surfaced in ethereum-optimism/protocol-quest#221, write a concrete proposal of what attributes should go in the superchain-deployconfig and what attributes should go into a chain-deployconfig.

Tagging @mds1 because this is linked to the OP Stack Manager work, ideally we can clean up abstractions in the deploy config with the release of OP Stack manager

https://www.notion.so/oplabs/Super-DeployConfig-c87aea690dce460db6b4cdbea17fc635#017b590bf4bc457e8eba5af385b4d303

**Comment by mds1** [comment]
@protolambda Is this closeable or are there future design docs still needed?

**Comment by protolambda** [comment]
@mds1 can be closed, but we do need to follow-up with implementation steps next week
