### ISSUE TITLE
SuperchainERC20: Factory Spec

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#10873]
The specs need to be updated with the `SuperchainERC20Factory` spec. We know some things about this factory but still need to make some decisions. This factory should make it really easy to spin up interoperable tokens across the superchain

- Is is a predeploy, what is its address?
- It should be create3 based to prevent coupling to bytecode
- Where should the bytecode live that ends up being deployed? A predeploy?
- The salt should commit to the unique erc20 properties - name, symbol, decimals
- Should the salt also commit to a version? Leaves open to add extensions to the interface in the future

**Comment by tynes** [comment]
There is a big design space here, its possible that we may want to limit the scope to supporting https://github.com/ethereum-optimism/optimism/issues/10899

**Comment by 0xParti** [comment]
We are discussing the base design in the following [Design Doc PR](https://github.com/ethereum-optimism/design-docs/pull/50). We will move into a spec once the [Liquidity Migration Spec](https://github.com/ethereum-optimism/specs/pull/294) is merged.

**Comment by 0xParti** [comment]
https://github.com/ethereum-optimism/specs/pull/332
