### ISSUE TITLE
SuperchainERC20: Spec

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#10876]
We need to clearly specify the SuperchainERC20. This ticket is considered done when we have a spec that we are confident in merged into the specs repo. This is being interated on as part of https://github.com/ethereum-optimism/specs/pull/71

**Comment by 0xParti** [comment]
This issue has been completed and merged to main from the [same PR](https://github.com/ethereum-optimism/specs/pull/71). 
It might be slightly modified after implementation.
