### ISSUE TITLE
SuperchainERC20: Spike xERC20 over New Standard

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#10875]
This ticket involves spiking out what an xERC20 based superchain erc20 standard would like like compared to the one proposed in https://github.com/ethereum-optimism/specs/pull/71. The learnings of this spike should be used to drive updates to the spec. We need to update the spec including the specific reasons behind the decision to go with one standard over the other.

**Comment by 0xParti** [comment]
@tynes we think this task is outdated and should be deprecated. How should we handle it?

**Comment by skeletor-spaceman** [comment]
closing this issue, since we already went with the superc20 vanilla design, while keeping SuperOPxERC20 as a custom implementation.

**Comment by stas** [comment]
@skeletor-spaceman where's the best place to follow the work on SuperOPxERC20?

**Comment by skeletor-spaceman** [comment]
hey @stas ! I just created the parent ticket for the SuperOPxERC20 standard :)
You'll be able to follow progress there: https://github.com/ethereum-optimism/optimism/issues/11485
First we need the Custom Implementation Factory, to then create the xERC20 flavor on top :)

**Comment by stas** [comment]
Ty ty! Excited!!!
