### ISSUE TITLE
Interop: devnet infra resources

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#10880]
Once the Devnet milestone (see https://github.com/ethereum-optimism/protocol-quest/milestone/6 ) spec and implementation work completes we will need infrastructure-support to run ephemeral (~3 weeks) L2 devnets on, that will form an interop dependency set.

This ticket can be considered done when there are 2 chains running in the cloud as part of the interop devnet. They should be functioning end to end, submitting batches to L1 Sepolia.

**Comment by tynes** [comment]
All communications with the devinfra team should go through the following ticket: https://github.com/ethereum-optimism/devinfra-pod/issues/165

We need to keep them up to date with our progress and give them clear instructions on what software to run and with which deploy configs

**Comment by tynes** [comment]
Work in progress PR can be found here: https://github.com/ethereum-optimism/k8s/pull/4015

**Comment by tynes** [comment]
Lets make the devnet available at `interop-devnet.optimism.io`

**Comment by protolambda** [comment]
Working towards stable devnet milestone now, closing this.
