### ISSUE TITLE
Interop: devnet chain configs

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#10881]
For the interop devnet, we will need chain-configs for each L2 chain, such that we can create multiple L2s for interop testing. This excludes prior pre-interop history, to keep the interop devnet scope small; i.e. exclude the network-upgrade transactions or FP migration.

This is considered complete when there are 2 genesis/rollup configs that can be used to spin up a devnet.

**Comment by tynes** [comment]
We could add the configs to the [superchain-registry](https://github.com/ethereum-optimism/superchain-registry) to make it easy for people to run their own nodes on the devnet but I believe that will just add extra overhead. We can make the genesis data available through alternative means

**Comment by protolambda** [comment]
Working towards stable devnet milestone now, closing this.
