### ISSUE TITLE
Interop: Interoperable Ether Tracking

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#10898]
# Overview

This ticket is meant to track the completion of the interoperable ether feature of the devnet. This is a critical feature for the devnet v2 milestone. This ticket can be considered done when interoperable ether is ready to be deployed as part of the devnet.

We removed support for sending ether natively as part of interop in https://github.com/ethereum-optimism/specs/pull/78. This was to derisk the ability to support interop between custom gas token chains and chains that use ether to pay for gas. We ultimately do need this feature as its a huge UX improvement, a design doc for adding it back in can be found here: https://github.com/ethereum-optimism/design-docs/pull/25

**Comment by skeletor-spaceman** [comment]
Both PRs have been merged, marking this as Done!
