### ISSUE TITLE
Interop: Configuration Library

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#10893]
There needs to be a portable library that can read config for an arbitrary number of chain ids to rpc urls. We should be sure to write this library once and up front so that everything that requires RPC URL config can be configured in the same way.

It isn't immediately obvious how this should work but seems most simple to use a file that contains key value pairs. It could potentially also work with flags or env vars.

**Comment by hamdiallam** [comment]
cc @protolambda @tynes 

Here's a PR i had on interop config https://github.com/ethereum-optimism/optimism/pull/8990. An open question was if we want to refactor of the L1Client/L1Endpoint tooling into general client tooling

**Comment by hamdiallam** [comment]
Note from our call:

- With the sidecar pattern actually don't need op-node to directly configure with peers like in the linked PR. The service likely can bootstrap itself and provide an interface to be used by both op-node & op-geth

**Comment by hamdiallam** [comment]
My thoughts on approaching this:

Config: Isolated interop go module within the monorepo. Configuration is simple, only requiring peer endpoint configuration and can internally and maintain clients as in op-node. Utils to populate this config with flags/env variables is straightforwward

```go
type InteropConfig struct {
    PeerChainCfgs map[uint64]EndpointConfig
}
```

**Comment by tynes** [comment]
Closing this as legacy work
