### ISSUE TITLE
Interop: Migrated Liquidity

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#10899]
It is important to have a clear upgrade path for deposited ERC20 tokens so that they are interop enabled. This means that any `OptimismMintableERC20Token` should have a migration path.

**Comment by tynes** [comment]
Design doc: https://github.com/ethereum-optimism/design-docs/pull/35

**Comment by tynes** [comment]
Related design doc: https://github.com/ethereum-optimism/design-docs/pull/36

**Comment by tynes** [comment]
Another design doc:  https://github.com/ethereum-optimism/design-docs/pull/37

**Comment by 0xParti** [comment]
We are closing the design on the following [PR](https://github.com/ethereum-optimism/specs/pull/294) to the Specs Repo.

**Comment by 0xParti** [comment]
Merged into main: https://github.com/ethereum-optimism/specs/pull/294
