### ISSUE TITLE
Question: tests on throughput of OE?

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#1090]
From discord user `@Domrom`.
The question is asking whether Optimism has run any tests to gauge the throughput of L2.

**Question**
> Have there been any tests done on the throughput of optimism? How many transactions can be handled per second, say over an hour, or indefinitely?

**Comment by smartcontracts** [comment]
I do think it's worth having benchmarks in CI. We could catch performance regressions introduced in PRs that way.

**Comment by smartcontracts** [comment]
Actually this is covered in #508, so I'm going to close this issue.
