### ISSUE TITLE
Add log downloading for sync integration tests

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#1095]
**Is your feature request related to a problem? Please describe.**
Seems like we've recently added sync tests to our integration tests: https://github.com/ethereum-optimism/optimism/blob/develop/.github/workflows/sync-tests.yml. However, the sync tests do not upload the logs as artifacts to GitHub like the integration tests do. This makes it very difficult to debug the tests.

**Describe the solution you'd like**
I'd like to see these lines added to the sync tests: https://github.com/ethereum-optimism/optimism/blob/c87e4c74e6165ca890d8dc138f5bdc1e4cba8d20/.github/workflows/integration.yml#L97-L113

**Comment by annieke** [comment]
added to https://github.com/ethereum-optimism/optimism/pull/981
