### ISSUE TITLE
Interop: op-supervisor: Handle reorgs

### ISSUE THREAD

**Issue by ajsutton** [ethereum-optimism/optimism#11026]
Insert a stage into the fetching pipeline to identify when a reorg has occurred.  Output an event down the pipeline that will rollback stages as needed (e.g. the log fetcher will need to rewind its record of the last block it fetched to the common ancestor of the fork).  Rewind the log database for the chain back to the common ancestor.

**Comment by protolambda** [comment]
Closing as stale / duplicate of https://github.com/ethereum-optimism/optimism/issues/11693
