### ISSUE TITLE
Interop: op-supervisor: Implement backend CheckMessage

### ISSUE THREAD

**Issue by ajsutton** [ethereum-optimism/optimism#11030]
https://github.com/ethereum-optimism/optimism/blob/cc86dc18424c0cb69abc0804a5e56c7ee70c4c90/op-supervisor/supervisor/backend/backend.go#L85-L88

**Comment by protolambda** [comment]
Completed in:
- https://github.com/ethereum-optimism/optimism/pull/11586
- https://github.com/ethereum-optimism/optimism/pull/11621
