### ISSUE TITLE
Interop: op-supervisor: Make RPC client options configurable

### ISSUE THREAD

**Issue by ajsutton** [ethereum-optimism/optimism#11032]
Add CLI options to configure the RPC client options e.g.
```
const epochPollInterval = 30 * time.Second
const pollInterval = 2 * time.Second
const trustRpc = false
const rpcKind = sources.RPCKindStandard
```

Or for those that don't need to be configurable, confirm that the value used is reasonable.

**Comment by protolambda** [comment]
Closing this, RPC clients are used differently, and in different places than when this was opened.
