### ISSUE TITLE
Error on Challenger Node - Failed to progress games: failed batch-retrieval: 429 Too Many Requests

### ISSUE THREAD

**Issue by AaronLee22** [ethereum-optimism/optimism#11079]
Description:

I am operating a challenger node and encountered the following error:

`ERROR[07-04|18:32:35.936] Failed to progress games                 err="failed to load games: failed to fetch games: failed to fetch batch: failed batch-retrieval: 429 Too Many Requests: {\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32005,\"message\":\"batch item count exceeded\"}}"`

Here are the details of my setup:

L1 & L2 ETH-RPC: Infura
L1 Beacon & Rollup-RPC: QuickNode

Command Used:

```
./bin/op-challenger \     
   --trace-type cannon \
   --l1-eth-rpc= \
   --l1-beacon= \
   --l2-eth-rpc= \
   --rollup-rpc=/ \
   --selective-claim-resolution \
   --private-key= \
   --network=op-sepolia \
   --datadir=/data \
   --cannon-prestate=./op-program/bin/prestate.json \
   --cannon-bin=./path-to-cannon-binary/cannon \
   --cannon-server=./op-program/bin/op-program  

```
Logs:

```
INFO [07-04|18:32:21.557] Starting op-challenger                   version=v0.0.0-0fb2bb18-1718470952
INFO [07-04|18:32:23.862] starting scheduler
INFO [07-04|18:32:23.862] starting monitoring
INFO [07-04|18:32:23.862] challenger game service start completed
ERROR[07-04|18:32:35.936] Failed to progress games                 err="failed to load games: failed to fetch games: failed to fetch batch: failed batch-retrieval: 429 Too Many Requests: {\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32005,\"message\":\"batch item count exceeded\"}}"
^CINFO [07-04|18:32:39.442] stopping challenger game service
INFO [07-04|18:32:39.443] stopped challenger game service          err=<nil>
```

Any help or guidance would be greatly appreciated.

Thank you!

**Comment by tynes** [comment]
Seems like the issue is that the RPC batch call size is too large. Perhaps the max RPC batch size is different depending on the RPC provider

https://github.com/ethereum-optimism/optimism/blob/46c49968de23bbc5f820b3710de248b21b7f05c4/op-challenger/game/fault/contracts/gamefactory.go#L95

The default value is used
https://github.com/ethereum-optimism/optimism/blob/46c49968de23bbc5f820b3710de248b21b7f05c4/op-service/sources/batching/multicall.go#L12

Is this an issue with other RPC providers like Alchemy or Infura?

**Comment by ajsutton** [comment]
You'll almost certainly want to use your own local nodes when running `op-challenger`.  You are placing a lot of trust in those nodes (you will lose funds if they give inaccurate info) and `op-challenger` will send a _lot_ of requests as part of monitoring all those games.

That said, I'd certainly be open to accepting a PR that made the max batch size configurable for `op-challenger`.  I suspect you will still hit a lot of rate limits or rack up very large bills though.

**Comment by AaronLee22** [comment]
I see.... Thank you for your answer I'm currently trying to run a local node for l1 rpc.
