### ISSUE TITLE
Interop: op-supervisor: Store chain index rather than chain ID

### ISSUE THREAD

**Issue by ajsutton** [ethereum-optimism/optimism#11105]
The log database format only uses a uint32 to store the chain identifier. This is intended to just store the index of the chain in the dependency set but is currently storing the full chain ID.  Since chain IDs could be larger than uint32 (up to uint256) this needs to be changed to allow recording the full range of chain IDs.

The conversion between chain ID and dependency set will need to be done in a way that's compatible with hard forks that modify the dependency set.

**Comment by protolambda** [comment]
There's a chain index and chain ID type now, with translation done by the dependency set object. Closing this as done.
