### ISSUE TITLE
`reentrantAware` modifier is not used.

### ISSUE THREAD

**Issue by pegahcarter** [ethereum-optimism/optimism#11128]
`reentrantAware` modifier is present here but does not actually do anything.

I suggest changing to a regular transient reentrant protection.

https://github.com/ethereum-optimism/optimism/blob/69d2d47b0f4ea0a41905b0ef52f3fa343ea7633e/packages/contracts-bedrock/src/L2/CrossL2Inbox.sol#L115

**Comment by tynes** [comment]
What do you mean it does nothing? It does do something. The implementation is here

https://github.com/ethereum-optimism/optimism/blob/d091bb33ceba0931205584d88b8c2bd84404e466/packages/contracts-bedrock/src/libraries/TransientContext.sol#L65-L69

It allows for reentrancy without clobbering transient storage

**Comment by pegahcarter** [comment]
Right, I understand that the storage is incremented.  However, this storage is not checked or managed elsewhere so I do not understand the purpose of tracking the number of entrances.

**Comment by tynes** [comment]
It is used here:

https://github.com/ethereum-optimism/optimism/blob/69d2d47b0f4ea0a41905b0ef52f3fa343ea7633e/packages/contracts-bedrock/src/L2/CrossL2Inbox.sol#L136
