### ISSUE TITLE
Design motivation for reverting views?

### ISSUE THREAD

**Issue by pegahcarter** [ethereum-optimism/optimism#11127]
Quick question: what is the design motivation for creating reverting reviews over views that return null values?

https://github.com/ethereum-optimism/optimism/blob/69d2d47b0f4ea0a41905b0ef52f3fa343ea7633e/packages/contracts-bedrock/src/L2/CrossL2Inbox.sol#L74

**Comment by tynes** [comment]
You cannot tell the difference between a 0 value and a null value. Therefore revert on a null value (the value is not set).
