### ISSUE TITLE
Optimism build gets stuck and then fails

### ISSUE THREAD

**Issue by ntegrals** [ethereum-optimism/optimism#11146]
I'm trying to build the Optimism repo on a Digital Ocean droplet (2 vCPUs 4GB / 50GB Disk) and the build gets stuck and then returns an error.

Is my machine not powerful enough, or is there another reason?

This is the stage I get stuck at:

>  NX   Running target build for 8 projects

    →    Executing 1/6 remaining tasks...
 
    ⠼    nx run @eth-optimism/contracts-bedrock:build
 
    ✔    2/2 succeeded [2 read from cache]

This is the error I got after a while:
>  NX   Ran target build for 8 projects (15m)
 
    ✔    2/3 succeeded [2 read from cache]
 
    ✖    1/3 targets failed, including the following:
         - nx run @eth-optimism/contracts-bedrock:build
 
   View structured, searchable error logs at https://nx.app/runs/Unk4kZMGDH

 ELIFECYCLE  Command failed with exit code 1.

**Comment by tynes** [comment]
It is possible that you are oom'ing while building the contracts. We would like to split the contracts up a bit better to prevent this sort of issue

Message in logs:

```
solc exited with signal: 9 (SIGKILL)
```

**Comment by ntegrals** [comment]
That makes sense! Thanks for the help.

Do you know the required hardware specs to build the contracts and run a test net? (I haven't found any requirements so far)
