### ISSUE TITLE
op-proposer: Uniform proposal intervals across restarts

### ISSUE THREAD

**Issue by sebastianst** [ethereum-optimism/optimism#11193]
When starting a new proposer instance, it just waits for a full proposal interval until submitting its first proposal, see `loopDGF()`.

It is better to inspect at startup when the last proposal was submitted and then adjust the first submission interval accordingly, to achieve uniform proposal intervals across proposer restarts. The [`DisputeGameFactory`](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/dispute/DisputeGameFactory.sol) contains getters to get the latest game.

The op-challenger uses contract bindings to query for this. Some code duplication could be done here by moving the common code into its own reuseable package like `op-dispute-contracts` and then use it from the challenger and proposer.

Since the L2OO is being deprecated, this should only be implemented for the DGF.

The value for metric `op_proposer_default_refs_number` should also be set at startup, so that there's no large gap in metrics while waiting until the next proposal.

**Comment by protolambda** [comment]
Related: the `op_proposer_default_refs_number` metrics needs to be updated on startup, not only after the first proposal, for alerts to be more reliable across restarts.
