### ISSUE TITLE
EVM Engineering: remove autogenerated invariant docs

### ISSUE THREAD

**Issue by mds1** [ethereum-optimism/optimism#11251]
I don't think our autogenerated invariant docs are referenced frequently by many people, and they are also not a comprehensive list of invariants—some invariants get tested with standard fuzz tests as opposed to invariant tests. As a result we should consider simplifying things by removing these autogenerated docs

Inspired by discussion with @smartcontracts and @tynes in https://github.com/ethereum-optimism/optimism/pull/11042#discussion_r1690575031

**Comment by tynes** [comment]
The source of truth for invariants should be the specs
