### ISSUE TITLE
FMA: OptimismSuperchainERC20

### ISSUE THREAD

**Issue by 0xng** [ethereum-optimism/optimism#11270]
- [FMA template](https://github.com/ethereum-optimism/design-docs/blob/fma/assets/fma-template.md)
- [Example FMA for Fjord](https://github.com/ethereum-optimism/design-docs/blob/main/security/fma-fjord.md)

**Comment by gotzenx** [comment]
https://github.com/ethereum-optimism/design-docs/blob/main/security/fma-superchainerc20-standard.md
