### ISSUE TITLE
Random list of stuff to turn into full issues

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#1128]
Just keeping a record. Will tick these off once issues get created:
- [x] Figure out how to get rid of the [`CTC_DEPLOYMENT_HEIGHT`](https://github.com/ethereum-optimism/optimism/blob/8d67991aba584c1703692ea46273ea8a1ef45f56/l2geth/cmd/utils/flags.go#L812-L816) flag. There's no reason why we need to be setting this value manually, services should be able to retrieve it automatically.
- [ ] Use the Deployer container for production deployments. We're doing deployments relatively manually when we can just be using the Deployer container.
- [ ] Review and update READMEs:
  - [ ] `/ops`
  - [ ] `/specs`
  - [ ] `/packages/batch-submitter`
  - [ ] `/packages/common-ts`
  - [ ] `/packages/contracts`
  - [ ] `/packages/core-utils`
  - [ ] `/packages/data-transport-layer`
  - [ ] `/packages/hardhat-ovm`
  - [ ] `/packages/message-relayer`
  - [ ] `/packages/smock`
- [ ] Review `/specs` and remove any outdated documents.
- [ ] We need a README inside `/examples`.
- [ ] Update primary README to explain changesets + release process.
- [ ] Docs for running different types of nodes.
- [ ] Add examples back into the integration tests.
- [ ] Publish Docker images so we can instruct people to use the published containers instead of building manually.
  - [ ] Also update docs to reflect this.
- [x] Review `core-utils` for any outdated or unnecessary utilities.
- [ ] Review `/patches` and see if everything in there is still necessary.
- [ ] Update integration tests not to use the `message-relayer`.

Bigger projects:
- [ ] Change the name of the DTL to something better like "L1 Rollup Data Indexer".
- [ ] Rebuild the DTL as a part of Geth instead of as an external TypeScript service.
- [ ] Rework the base TypeScript `Service` class.
- [ ] Simplify the `message-relayer`.
- [ ] Significantly improve test coverage of `core-utils`.
- [ ] Determine and apply a new contract code style that can be enforced with a formatter.
- [ ] Rename `hardhat-ovm` (maybe? it's just not a great name IMO).
- [ ] Rewrite the `batch-submitter` using the common `Service` class (we really need to rewrite this, we've learned a lot since it was first built).

Stuff we could consider for fun:
- [ ] Automatically generate part of our primary README based on changes to sub-packages.

**Comment by rajivpo** [comment]
down to help with test coverage if you're open to help 😃

**Comment by smartcontracts** [comment]
> down to help with test coverage if you're open to help 😃

I think adding test coverage for `core-utils` would be a great project for someone to tackle! It's relatively straightforward stuff (just testing stateless utility functions with a limited scope). I'll create an issue for that, if you want to work on it feel free to leave a comment when I make the issue :-)

**Comment by smartcontracts** [comment]
Also "Review core-utils for any outdated or unnecessary utilities" might also be a zen ticket

**Comment by smartcontracts** [comment]
Created #1186
