### ISSUE TITLE
Interop: setup interop tests in op-e2e

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#11280]
Run multiple L2s, attached to the same L1, with an op-supervisor, in op-e2e.

Pre-requisites:
- [x] Forge deployment code lands #11490 
- [x] Deploy-config organization (Go side): https://github.com/ethereum-optimism/optimism/pull/11189
- [x] https://github.com/ethereum-optimism/optimism/issues/11493
- [x] ~https://github.com/ethereum-optimism/optimism/pull/11591~
- [x] https://github.com/ethereum-optimism/optimism/pull/11850

**Comment by SkandaBhat** [comment]
@protolambda I am interested in contributing to interop. Is there anything from this tests epic or from the milestone that I can pick up?

**Comment by protolambda** [comment]
@SkandaBhat this ticket is currently not actionable, due to blockers on the chain-deployment integration into op-e2e. See the above mentioned design docs.
