### ISSUE TITLE
Interop: API to use Heads Database

### ISSUE THREAD

**Issue by axelKingsley** [ethereum-optimism/optimism#11308]
Calls into the supervisor currently do not consult the Heads Database, which is needed for accuracy when responding to message-safety checks.

Contexts:
* https://github.com/ethereum-optimism/optimism/pull/11009
* https://github.com/ethereum-optimism/optimism/pull/11139

These PRs demonstrate the implementation of the Head Persistence which needs to be incorporated into message-safety.

The head pointers should be used when responding to API requests

**Comment by axelKingsley** [comment]
https://github.com/ethereum-optimism/optimism/pull/11586

**Comment by protolambda** [comment]
Can this be closed now?
