### ISSUE TITLE
bug:  withdrawals confirmed on gateway, but balances unchanged

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#1130]
**Describe the bug**
On the https://gateway.optimism.io, after a withdrawal has been made and confirmed by MetaMask, my L2 balance does not change to reflect the withdrawn amount of ETH.

**To Reproduce**
1. Go to https://gateway.optimism.io
2. Make a withdrawal of ETH
3. Wait for tx to be confirmed by MetaMask.
4. Go back to withdrawal page.
5. See L2 balance is virtually unchanged (minus gas fees). You can also see your balance is unchanged on the MetaMask UI.

**Expected behavior**
L2 Balances should update.

**Comment by besoeasy** [comment]
Was not able to reproduce, do you have a screenshot or a small video recording ?

**Comment by platocrat** [comment]
> Was not able to reproduce, do you have a screenshot or a small video recording ?

Closing since issue has gone stale
