### ISSUE TITLE
CrossL2Inbox: add alternative `validateMessage` implementation

### ISSUE THREAD

**Issue by skeletor-spaceman** [ethereum-optimism/optimism#11310]
We need to add a function in charge of validating a message to the CrossL2Inbox. It should perform all the required checks to ensure a given message is valid. Here's a possible implementation:
```solidity
/// @notice Validates a cross chain message.
/// @param _id      Identifier of the message.
/// @param _messageHash Message payload to call target with.
function validateMessage(Identifier calldata _id, bytes32 _messageHash) external {
  if (_id.timestamp > block.timestamp) revert InvalidTimestamp();
  if (!IDependencySet(Predeploys.L1_BLOCK_ATTRIBUTES).isInDependencySet(_id.chainId)) {
    revert InvalidChainId();
  }

  emit ExecutingMessage(_id, _messageHash);
}
```
The flow would be:

A user sends a message on ChainA, which emits an initiating message. Then the user calls a contract, let's say the relayMessage function in the L2CrossDomainMessenger directly, and this function validates the message being passed to it by calling this validateMessage function in the CrossL2Inbox

This is an alternative we want to ADD to what we now have which is ALWAYS using the CrossL2Inbox as the unique entry-point.
We think this will allow for more experimentation and potentially better ux/dx on both the on&off-chain parts.

**Comment by tynes** [comment]
Closed by https://github.com/ethereum-optimism/optimism/pull/11322
