### ISSUE TITLE
Holocene-D: Write Steady Batch Derivation Specs

### ISSUE THREAD

**Issue by sebastianst** [ethereum-optimism/optimism#11313]
Write specs, based on [design doc](https://github.com/ethereum-optimism/design-docs/pull/20).

**Comment by tynes** [comment]
Based on a convo with @axelKingsley in discord, thinking about span batch validity rules

I see 4 options when there is a single invalid block in a span batch

- full span batch invalid
- valid blocks up to invalid block, rest are dropped
- valid blocks up to invalid block, invalid block is deposits only, rest are dropped
- valid blocks up to invalid block, invalid block and rest are deposit only

Right now we believe the 4th case is the best behavior as it results in the most predictable amount of resource usage
