### ISSUE TITLE
About Optimism's Three-Step Process for Contract Implementation Upgrades

### ISSUE THREAD

**Issue by zhiqiangxu** [ethereum-optimism/optimism#11327]
I found the rule for upgrades in the [Optimism Style Guide](https://github.com/ethereum-optimism/optimism/blob/9d31040ecf8590423adf267ad24b03bc1bf7273b/packages/contracts-bedrock/STYLE_GUIDE.md). The process for upgrading the implementation is as follows:

1. Upgrade the implementation to the StorageSetter contract.
2. Use that to set the initialized slot (typically slot 0) to zero.
3. Upgrade the implementation to the desired new implementation and initialize it.

It would be helpful if there were examples demonstrating this process.

**Comment by tynes** [comment]
See [here](https://github.com/ethereum-optimism/superchain-ops/blob/55e9520e27c7e916d8992ce351c6d5cfa8a511d8/tasks/eth/009-fp-upgrade/EXEC.md?plain=1#L6) for an example
