### ISSUE TITLE
Holocene-D: Partial Span Batch Validity

### ISSUE THREAD

**Issue by sebastianst** [ethereum-optimism/optimism#11330]
_Partial Span Batch Validity_ determines the validity of singular batches within span batches on a case by case basis, and invalid singular batches are immediately dropped. Only the remaining span batch is forwards-invalidated, as opposed to backwards-invalidating the whole span batch.

## Tasks
- [x] #11513
- [x] #11514
- [x] #11515
- [x] #11516

Note: No batcher hardening expected to be necessary for this.

**Comment by BlocksOnAChain** [comment]
@sebastianst based on our recent chats with @ajsutton - should we increase the priority for this feature?
CC: @alfonso-op for visibility.
