### ISSUE TITLE
Interop: Add new role for dependency set management

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#11366]
# Overview

The `SystemConfigInterop` contract manages the interop dependency set. Right now the `owner` of the `SystemConfig` can add and remove dependencies. The owner of the `SystemConfig` is considered the chain operator. We want to allow for a different role to manage the dependency set so that in production the dependency set can be managed by governance rather than the chain operator.

# Definition of Done

- [ ] [Specs](https://github.com/ethereum-optimism/specs/blob/afadeea642d05eda6e111d9098c9a842c2ecf322/specs/interop/dependency-set.md) are updated with this new role
  - Could follow [this](https://github.com/ethereum-optimism/specs/blob/main/specs/interop/token-bridging.md#functions) spec, how there is a "Functions" header and subheaders for each function 
  - What should this role be called?
- [ ] Source code is implemented
- [ ] Full test coverage

**Comment by AmadiMichael** [comment]
The intention here is to have only one authorized caller of each of the 2 functions at a time right? e.g `addDependency` cannot have multiple authorized callers at once...

**Comment by tynes** [comment]
Yes exactly, just 1 account that can call `addDependency`/`removeDependency` that MAY or MAY NOT be different than the `owner` from `Ownable`. Then for the standard config definition, the account that can add remove dependencies MUST be the foundation multisig

**Comment by AmadiMichael** [comment]
Ah yes thanks, was about to ask that now, 
where can i find the foundation multisig address?

**Comment by tynes** [comment]
You can see in the docs [here](https://docs.optimism.io/chain/security/faq#op-mainnet-multisig) although we do not want to hardcode any addresses, it would be an argument to `initialize` at deploy time

**Comment by AmadiMichael** [comment]
> You can see in the docs [here](https://docs.optimism.io/chain/security/faq#op-mainnet-multisig) although we do not want to hardcode any addresses, it would be an argument to `initialize` at deploy time

will this be modifiable and if so, by whom?
