### ISSUE TITLE
Interop: design doc for refactor of deployer tooling, using Go forge script execution

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#11360]
Last week we drafted a design doc on "deployment chains", the idea of incremental builds of deployments, to integrate the forge scripts efficiently into op-e2e.

A newer alternative solution is to run the forge scripts directly in Go. This might make the setup fast enough to avoid the complexity of caching, and generally improves integration (we can capture any intermediate deployment behavior/outputs as necessary).

This new idea needs a design-doc, so we can compare it against the cache based solution.

**Comment by gosunuts** [comment]
I think some logic in solidity (such as dump json allocs) can replaced to golang native code.
Deployment process using solidity is super slow
