### ISSUE TITLE
Interop: Create a CREATE3 or CREATEX spec

### ISSUE THREAD

**Issue by 0xParti** [ethereum-optimism/optimism#11389]

**Comment by 0xParti** [comment]
Blocked by Factory review

**Comment by tynes** [comment]
The decision has been made to go with createx

**Comment by 0xParti** [comment]
We will rollback to CREATE3 for the factory, but will introduce the CREATEX preinstall anyway
https://github.com/ethereum-optimism/specs/pull/341

**Comment by tynes** [comment]
Since we are going with create3, it would be nice to just have an explanation in the specs of what create3 does and why it is used. We can use an existing create3 implementation like the t11s implementation
