### ISSUE TITLE
Flickering sync test 

### ISSUE THREAD

**Issue by annieke** [ethereum-optimism/optimism#1140]
**Describe the bug**
Before merging https://github.com/ethereum-optimism/optimism/pull/1123, we used to have flickering sync tests:
- https://github.com/ethereum-optimism/optimism/runs/2862090073?check_suite_focus=true
- https://github.com/ethereum-optimism/optimism/runs/2861968072?check_suite_focus=true

The most likely cause to this is starting docker-compose multiple times, which I have experienced while developing locally.

As follow ups, the best course of action would be to
1. Fix the root cause of verifier mismatches that's forcing us to do this test in a separate workflow
2. Bring the verifier up with the rest of the stack instead of individually during this test, to fix flakiness

**To Reproduce**
See linked CI failures above.

**Expected behavior**
Sync tests only fail when a change causes a state root divergence, not randomly. 

**Additional context**
This is also related to mismatched verifier state roots.

**Comment by smartcontracts** [comment]
I'm going to close this since I haven't seen any movement on it and I don't think it's relevant at the moment.
