### ISSUE TITLE
Different outputs from `debug_traceBlockByNumber` and `debug_traceTransaction`

### ISSUE THREAD

**Issue by annieke** [ethereum-optimism/optimism#1142]
**Describe the bug**

From Dune Analytics

> Our workload on e.g. Ethereum consists of calling a batch of [eth_getBlockByNumber, debug_traceBlockByNumber] and a batch of [eth_getTransactionReceipt, ....] for each transaction.
> 
> This works on Optimism, but we see that all "blocks" have exactly 1 transaction, which leads us to the question: what exactly is returned by the eth_getBlockByNumber method? Furthermore the index of the single returned transaction is always the returned block number + 1.
>
> In addition we could use some help to interpret the output of the tracing module in l2geth. We see different outputs from debug_traceBlockByNumber and debug_traceTransaction.

**To Reproduce**
`curl -s -X POST --data '{"jsonrpc": "2.0", "method": "debug_traceTransaction", "params": ["0x6fc01b75e3dbfddab9ac94fc94301d8e6383bf929ed3233e8083837197377ea2", {"tracer": "callTracer", "timeout": "60s"}], "id": "1"}' -H "Content-Type: application/json" replica-endpoint`

vs.

`curl -s -X POST --data '{"jsonrpc": "2.0", "method": "debug_traceBlockByNumber", "params": ["0x4cf", {"tracer": "callTracer", "timeout": "60s"}], "id": "1"}' -H "Content-Type: application/json" replica-endpoint`

**Expected behavior**

Since each block only contains one transaction, we expect the traces to be similar if not the same.

**Additional context**

Current recommendation is to use `debug_traceTransaction`. May be related to https://github.com/ethereum-optimism/optimism/issues/427

**Comment by smartcontracts** [comment]
@annieke is this still an issue in OVM 2.0? Can we get Dune to test this?

**Comment by annieke** [comment]
i think we can close this with ovm 2.0
