### ISSUE TITLE
Where is the block timestamp set?

### ISSUE THREAD

**Issue by Mattiatore** [ethereum-optimism/optimism#11421]
Can someone please point me to where in the code the block timestamp is set? By block timestamp I mean the one that is returned in the 'timestamp' field after an rpc call with method 'eth_getBlockByNumber'

**Comment by tynes** [comment]
The timestamp deterministically increments by 2 seconds each block

**Comment by tynes** [comment]
You can see here: https://github.com/ethereum-optimism/op-geth/blob/ee83530a242132150c9f067e6c4135f67ab4bba2/internal/ethapi/api.go#L889

**Comment by Mattiatore** [comment]
Thanks for clarifying, can you please point to where the block timestamp is set?
