### ISSUE TITLE
What should we do with restructure_tests.py?

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#11433]
[restructure_tests.py](https://github.com/ethereum-optimism/optimism/blob/773e476b18ed6004aa7dade19a55519deb188942/packages/contracts-bedrock/scripts/restructure_tests.py) is a bit awkward. It's useful but we don't seem to enforce it in CI. I feel like we should either enforce it in CI or remove it.

**Comment by tynes** [comment]
I think now that its been used, we can delete it
