### ISSUE TITLE
Deprecated `selfdestruct` usage in `SafeSend.sol`

### ISSUE THREAD

**Issue by siddharth0a** [ethereum-optimism/optimism#11440]
**Bug Description**
The `selfdestruct` operation used in the `SafeSend.sol` file is deprecated and its behavior has changed following the Cancun hard fork, potentially leading to unexpected behavior and security issues.

**Steps to Reproduce**

1. Open the `src/universal/SafeSend.sol` file.
2. Navigate to line 9.
3. Observe the use of the `selfdestruct` operation.

when 
build with command "pnpm build"

**Expected behavior**
The `selfdestruct` operation should be avoided in new contracts, and an alternative method should be used to handle Ether transfers securely.

**Environment Information:**
- Operating System: [e.g. Ubuntu 20.04]
- Package Version (or commit hash): [e.g. op-node v1.9.0]

**Configurations:**

**Logs:**
```plaintext
Warning (5159): "selfdestruct" has been deprecated. Note that, starting from the Cancun hard fork, the underlying opcode no longer deletes the code and data associated with an account and only transfers its Ether to the beneficiary, unless executed in the same transaction in which the contract was created (see EIP-6780). Any use in newly deployed contracts is strongly discouraged even if the new behavior is taken into account. Future changes to the EVM might further reduce the functionality of the opcode.
 --> src/universal/SafeSend.sol:9:9:
  |
9 |         selfdestruct(_recipient);
  |         ^^^^^^^^^^^^

**Comment by tynes** [comment]
This is a non issue and is the desired behavior per EIP-6780
