### ISSUE TITLE
Web3.js Plugin not working

### ISSUE THREAD

**Issue by SantiagoDevRel** [ethereum-optimism/optimism#11461]
Hi guys, I was using the [Optimism web3.js plugin](https://www.npmjs.com/package/@eth-optimism/web3.js-plugin) and I noticed that the methods that are interacting with the L2 are not working properly (returning `0n`)
```js
await web3.op.getBaseFee(); 
// 0n
await web3.op.getGasPrice(); 
// 0n 
```
We are hosting 3 hackathons/bounties with the [web3.js africa tour](https://x.com/web3_js/status/1822193833964195989) and we wanted to promote this plugin there as well, but I've noticed is not working properly, are you able to solve this asap so we can still include the plugin for the hackathons?

Thanks.

**Comment by SantiagoDevRel** [comment]
@spacesailor24 💪

**Comment by Redoudou** [comment]
@spacesailor24  maybe you can help.  Thank you

**Comment by tynes** [comment]
Hey @SantiagoDevRel, we are no longer maintaining this package. The latest hardfork likely broke it due to modifications to how gas pricing works

**Comment by SantiagoDevRel** [comment]
Ohh ok @tynes , we will take out the plugin for the Africa tour hackathon, thanks for letting me know

**Comment by Redoudou** [comment]
@tynes we would love to continue supporting the Optimism for Web3js users. We use the Op stack at Chainsafe. Who would the right person we could talk at Op to discuss options ?
