### ISSUE TITLE
SuperchainERC20: Custom Implementation Factory

### ISSUE THREAD

**Issue by skeletor-spaceman** [ethereum-optimism/optimism#11485]

**Comment by gotzenx** [comment]
After a lot of research and design for this task, we realized blueprints were unnecessary, so the need for CREATE3 was minimal, so we decided to use CREATE2 instead.
Long story short, we realized the final design would be very similar to the existing Create2Deployer but with an added deployment registry. We don't think it makes sense to introduce a new factory just for that, and suggest using the preinstall instead. 
If, at any point, someone is interested in having a deployment history, they could introduce an additional factory contract that calls the Create2Deployer and thats it. No need for it to be a predeploy.

All of this was discussed with @tynes, and he agreed with us.
