### ISSUE TITLE
batch-submitter num_txs_per_batch_* metrics are always zero

### ISSUE THREAD

**Issue by optimisticben** [ethereum-optimism/optimism#1149]
**Describe the bug**
The metrics presented by the batch-submitter for the following metrics are always 0.
`num_txs_per_batch_bucket`
`num_txs_per_batch_count`
`num_txs_per_batch_sum`

`batch_size_in_bytes_sum` seems to be working for the entire batch size.

**Expected behavior**
The system should provide an accurate count of the number of transactions per batch. Maybe the transaction sizes too?

**Additional context**
https://github.com/ethereum-optimism/optimism/blob/develop/packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts#L247

**Comment by smartcontracts** [comment]
Closing, relates to the old batch submitter
