### ISSUE TITLE
Integration Tests `expectApprox` Function Signature Clarity

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#1154]
**Is your feature request related to a problem? Please describe.**
The integration tests use a helper function that asserts the return value is within a range, the last two arguments specify how much higher and lower the value can be from what it is being asserted on. When seeing the function being used in practice, its hard to know what the numbers mean unless you are very familiar with the function params and its not easy to remember which comes first.

https://github.com/ethereum-optimism/optimism/blob/0112650986a5c8c65ad0765741157f0ac1351ff6/integration-tests/test/shared/utils.ts#L145-L150

**Describe the solution you'd like**
A quick fix would be to use a pattern similar to Python's kwargs where the third argument is turned into an object and then the keys of the object specify the `upperDeviation` and the `lowerDeviation`. This would allow the person looking at the test to instantly know what the function is actually asserting on and help ensure correctness.

See this comment for additional discussion: https://github.com/ethereum-optimism/optimism/pull/1137#discussion_r657387399

This is a great issue for a new contributor to take on

**Comment by snario** [comment]
Fixed by https://github.com/ethereum-optimism/optimism/pull/1187
