### ISSUE TITLE
op-heartbeat: Running op-heartbeat is quite challenging

### ISSUE THREAD

**Issue by joohhnnn** [ethereum-optimism/optimism#11615]
1. There is a lack of guidance documentation for op-heartbeat.

2. It seems to fail during the default startup due to a configuration issue with the pprof flag, showing the error: `Error -> panic: interface conversion: interface {} is nil, not *flags.PathFlag.`

3. It's difficult to determine the expected results of the operation.

**Comment by protolambda** [comment]
We are removing the op-heartbeat service, see #11622
