### ISSUE TITLE
Metamask on Optimistic Kovan returns incorrect L2GasLimit

### ISSUE THREAD

**Issue by K-Ho** [ethereum-optimism/optimism#1162]
**Describe the bug**
When trying to send a transaction on Optimistic Kovan and setting the `gasLimit` via `estimateGas`, the last 4 digits consistently contain a 5 in the significant digit, see screenshot below:

**To Reproduce**
1. Go to Metamask on Optimistic Kovan
2. Click to send an ERC20 transfer
3. See gasLimit value
4. Send tx and get RPC error `Invalid transaction: exceeds block gas limit"

**Expected behavior**
the leading 5 in the L2GasLimit should be a 0.

**Screenshots**
<img width="345" alt="Screen Shot 2021-06-24 at 4 48 24 PM" src="https://user-images.githubusercontent.com/5341583/123345928-253a0e00-d525-11eb-94ff-7c8d877c6dae.png">

**Comment by K-Ho** [comment]
Closing since this is a metamask specific issue

**Comment by Moderator01** [comment]
Are you using the latest version?

**Comment by Moderator01** [comment]
https://metamask-io.medium.com/metamask-io-browser-extension-update-d2add72208e3
