### ISSUE TITLE
Refactor mips.go and MIPS.sol

### ISSUE THREAD

**Issue by Inphi** [ethereum-optimism/optimism#11639]
The MT-FPVM will be implemented in source control as a separate VM. This is so we can continue to support the existing VM until we've fully upgraded all FP deployments.

mips.go and MIPS.sol should be refactored so that common code (such as instruction decode and logic and arithmetic instruction execution) can be reused across both VM implementations. Care should be taken not to introduce stateful constructs in the refactor as it would be inconvenient to do so in solidity.

**Comment by mbaxter** [comment]
Refactor complete - closing.
