### ISSUE TITLE
MT Cannon Specification Draft

### ISSUE THREAD

**Issue by Inphi** [ethereum-optimism/optimism#11644]
Write up a spec for MT Cannon. We can start with a rough sketch of MT Cannon. Then finalize this with a draft spec in the specs repo.

**Comment by mbaxter** [comment]
Draft started [here](https://www.notion.so/oplabs/Multithreaded-Cannon-8a2e8079764a46f094804436b123332f)

**Comment by Inphi** [comment]
Will create a final spec for later.
