### ISSUE TITLE
cannon: Add more robust validation in Cannon fuzz tests

### ISSUE THREAD

**Issue by mbaxter** [ethereum-optimism/optimism#11651]
## Description

Following up on https://github.com/ethereum-optimism/optimism/issues/11634, there are a few fuzz tests that don't fully validate the post-state updates on the FPVMState.  Creating this ticket to address some TODOs added in ethereum-optimism/optimism#11634 to make these tests more robust.  

TODOs can be seen here: https://github.com/ethereum-optimism/optimism/pull/11573/commits/b9917d6459559e4ed6e3dd7eb1c7c6016d3885b0

**Comment by Inphi** [comment]
We've knocked off a couple of todos. Is this still needed?

**Comment by mbaxter** [comment]
Yeah, we should go ahead and finish cleaning this up - I can have a look.
