### ISSUE TITLE
Offchain MTCannon: Clean up memprofile handling

### ISSUE THREAD

**Issue by mbaxter** [ethereum-optimism/optimism#11660]
## Description

Clean up our approach to disabling memory profiling for go programs loaded into Cannon. 

As part of https://github.com/ethereum-optimism/optimism/pull/11188, we reworked our approach to disabling memory profiling.  For details, see commits [here](https://github.com/ethereum-optimism/optimism/pull/11188/commits/4fd9c3917baf9c17d1642576d73eea53616cc440) and [here](https://github.com/ethereum-optimism/optimism/pull/11188/commits/9e80acf4a653b068d490e187baa2e3cf1c38c672).  The original approached directly overwrote the`MemProfileRate` symbol in the compiled MIPS bytecode in order to disable memory profiling for performance reasons.  The current approach sets `runtime.MemProfileRate` in the op-program itself, which is less hacky, but has the disadvantage that any go program we want to run needs to separately ensure that mem profiling is disabled. 

The suggested approach is to move the memprofile handling back to `patch.go` and out of op-program, but to handle this in a cleaner way by setting an envar on the initial program stack.  You can see where the initial stacks envars are set up in `PatchStack()` [here](https://github.com/ethereum-optimism/optimism/blob/05a9c478264302a257f30daad877449a31b0aaeb/cannon/mipsevm/program/patch.go#L74).  For documentation on the initial stack see this [MIPS ABI documentation](https://refspecs.linuxfoundation.org/elf/mipsabi.pdf) "Figure 3-26: Initial Process Stack" . The envar set is currently empty, but we can push the value `GODEBUG=memprofilerate=0` in order to inform the runtime to disable mem profiling.  Documentation on go runtime envars is available [here](https://pkg.go.dev/runtime#hdr-Environment_Variables).

**Comment by Inphi** [comment]
Assigning to myself as I already have a local patch that fixes this.
