### ISSUE TITLE
Periodically run MTCannon on real-world data

### ISSUE THREAD

**Issue by mbaxter** [ethereum-optimism/optimism#11662]
## Description

Create a job that periodically runs op-program on MTCannon with real-world data.  

We have a similar recurring job that runs cannon natively that we can use as a model.  See the[ circleci fpp-verify job](https://github.com/ethereum-optimism/optimism/blob/69d2d47b0f4ea0a41905b0ef52f3fa343ea7633e/.circleci/config.yml#L1424-L1435).

**Comment by Inphi** [comment]
#11649 fixes this.

**Comment by Inphi** [comment]
Closing in favor of #11649
