### ISSUE TITLE
Finalize MTCannon Specification

### ISSUE THREAD

**Issue by mbaxter** [ethereum-optimism/optimism#11664]
Depends on: https://github.com/ethereum-optimism/optimism/issues/11644

Finalize the Multithreaded Cannon (MTCannon) [draft spec](https://www.notion.so/oplabs/Multithreaded-Cannon-8a2e8079764a46f094804436b123332f) and update the specs repo.  While we are supporting both MT and original Cannon implementations, we should keep the existing [Cannon spec](https://specs.optimism.io/fault-proof/cannon-fault-proof-vm.html) and add an additional spec for MTCannon.

**Comment by tynes** [comment]
Is there a plan to migrate the spec to the specs repo?

**Comment by mbaxter** [comment]
> Is there a plan to migrate the spec to the specs repo?

Yep - the output of this issue should be a PR to the specs repo.
