### ISSUE TITLE
Holocene: spike Withdrawals-root feature

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#11721]
Adding the withdrawals-contract storage-root to the block-header, e.g. in place of the L1 beacon withdrawals-root, would enable proposers to function without archive-node requirement.

See original specs by @clabby here: https://github.com/ethereum-optimism/specs/pull/374

This might become part of the Holocene upgrade, if we can agree on specs, and if the implementation scope is reasonable.

This issue tracks the idea of doing a quick 1-3 day spike, to review where the specs are at, and what implementation/testing of this feature would take.

**Comment by BlocksOnAChain** [comment]
@protolambda thanks for creating this issue, this sounds like a solid plan to me.

**Comment by sebastianst** [comment]
We need to make sure infra services that depend on header format don’t break.

**Comment by protolambda** [comment]
Done: https://github.com/ethereum-optimism/optimism/issues/12044

Created a draft PR of op-geth changes, and a detailed plan of what I think is necessary to complete this work for Holocene.
