### ISSUE TITLE
OPSM: Finish adding all OPStackManager Implementation Setters

### ISSUE THREAD

**Issue by blmalone** [ethereum-optimism/optimism#11815]
As per PR discussion: https://github.com/ethereum-optimism/optimism/pull/11623#discussion_r1750759110 

More contracts need to be added to the OPStackManager. Namely, `DelayedWETH` and `DisputeGameFactory`. This issue is tracking that work so it doesn't get lost amidst all the other feature requests.

**Comment by mds1** [comment]
Closing as this was completed
