### ISSUE TITLE
Interop: Handle Empty Databases

### ISSUE THREAD

**Issue by axelKingsley** [ethereum-optimism/optimism#11836]
In working on `op-e2e` for interop, I discovered an edge case that needs to get dealt with.

If chains don't ever produce logs, their databases stay empty. Then, when `CheckBlock` calls come in, the backend fails with an EOF because there's no content.

For now, I've added a clause that makes EOF an ok outcome during the backend CheckBlock, but this is also not right, as it exposes the risk of being given an intentional future block number in order to force an EOF. I *think* this could still be ok, because the individual Safety indexes still get checked.

The best solutions are to:
* Gracefully/Explicitly check for situations where there's just no data recorded for a given block.
* Add block checkpoints after every block.

**Comment by protolambda** [comment]
Closing, the main thing left to improve initialization of is selecting a trusted cross-safe point. Tracked in https://github.com/ethereum-optimism/optimism/pull/12841
And reading to the end of the DB is generally handled with the `types.ErrFuture` error now.
