### ISSUE TITLE
Review core-utils for outdated or unused stuff

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#1186]
**Is your feature request related to a problem? Please describe.**
[`@eth-optimism/core-utils`](https://github.com/ethereum-optimism/optimism/tree/develop/packages/core-utils) holds a bunch of small utilities that we use all over the place. Sometimes these utilities become outdated or end up not being used. We should remove utilities that aren't being used.

**Describe the solution you'd like**
The main task here is to remove any functions that aren't actively being used. The way to check if a function is being used or not is simply to ctrl+F/grep/whatever the whole codebase and see if there are any references to the function. For example, the function `getRandomAddress()` is not being used anywhere:
https://github.com/ethereum-optimism/optimism/blob/26b39199bef0bea62a2ff070cd66fd92918a556f/packages/core-utils/src/common/addresses.ts#L8-L10

Similarly, the `assert` function here doesn't get imported anywhere:
https://github.com/ethereum-optimism/optimism/blob/26b39199bef0bea62a2ff070cd66fd92918a556f/packages/core-utils/src/common/common.ts#L1-L9

Feel free to also do some cleanup to remove unused variables or parameters like:
https://github.com/ethereum-optimism/optimism/blob/26b39199bef0bea62a2ff070cd66fd92918a556f/packages/core-utils/src/fees.ts#L8

**Comment by rajivpo** [comment]
I'll take a stab at this.
