### ISSUE TITLE
OptimismMintableERC20: Add permit support + native permit2 support

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#11880]
Add `permit` support to the `OptimismMintableERC20` token implementation. This can easily be done using the `ERC20Permit` contract in openzeppelin. Also add native support for `permit2` by enforcing that the `allowance` for `permit2` always returns `type(uint256).max`.

**Comment by marktoda** [comment]
- clear requirements, why they need permit + permit2
  - Default support for [ERC2612](https://eips.ethereum.org/EIPS/eip-2612) permits is a pretty clear UX improvement, enabling single tx actions and gas abstraction without native token in wallet to pay for an initial approve
  - Permit2 has become the primary approval mechanism for all Uniswap interface interactions and is integrated by many other DeFi protocols that I'm aware of. Directly integrating tokens with it saves an entire approval step for users, simplifying the user experience of interacting with these protocols. It also synergizes well with intents-based trading systems like UniswapX, where users could submit a trade with a single signature without ever requiring any native token to set up for the trade

- is there precendent for baking permit2 support directly into a token? why/why not? related to prior bullet what does this give vs. normal out-of-token support
  - One I'm aware of is the [Pol token](https://github.com/0xPolygon/pol-token/blob/fa3de37f6443b99584db402b97b30c25712796fd/src/PolygonEcosystemToken.sol#L68)

**Comment by mds1** [comment]
Thanks @marktoda! One follow up: What's the value of standard ERC2612 permit if permit2 is directly integrated? It seems to me permit2 is a superset of permit. I'm ok with adding both—I see POL has both as well—just curious if there's a different use case for permit vs. permit2, or if it's just to give users/devs more options?

**Comment by maurelian** [comment]
@marktoda can you confirm that we should enable this setting to `_givePermit2InfiniteAllowance` in the Solady ERC20? Is that a basic requirement to make the ERC20 Permit2 compatible?
