### ISSUE TITLE
Fix TODO tags, properly fail CI on invalid TODO tags

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#11949]
We have a scheduled job in CI that checks for TODO tags. I don't think this job is particularly useful because the job doesn't error out if the TODO tag format is invalid. 

We should introduce a new script to verify TODO tag formats. This script should NOT check if the corresponding issues exist because that would cause CI to randomly fail on unrelated PRs and we don't want that. Use this PR to also fix any existing TODO tags.

**Comment by ajsutton** [comment]
I think you mean add an additional check here which I support.  The existing TODO check has been very useful but it is just a first step - we didn't want to delay fault proofs to take on cleaning up every TODO in the codebase.  Having it flag when an issue is closed that still has an open TODO is really useful, but that definitely shouldn't be a blocking check as noted.  If someone has time to clean up all the existing TODOs then having a check for the format as a requirement to merge would be an excellent addition.
