### ISSUE TITLE
Add JSON-RPC commands for tests

### ISSUE THREAD

**Issue by CodeSandwich** [ethereum-optimism/optimism#1194]
**Is your feature request related to a problem? Please describe.**
I need to write tests for a contract, where the passage of time is important. With Hardhat Ethereum client I can call `evm_mine`, `evm_setNextBlockTimestamp` and `evm_snapshot` which can be used to move forward and even rewind time. With Optimism I can't run such tests.

**Describe the solution you'd like**
I would like `evm_mine`, `evm_setNextBlockTimestamp` and `evm_snapshot` or some equivalents exposed by the local client.

**Describe alternatives you've considered**
None, this is probably the most elegant and developer-friendly.

**Additional context**
Nope.

**Comment by hubba-bubba-776** [comment]
Yeah, that one is huge. The only way to test Optimism contract right now is to test part of the functions on EVM and others on OVM 😅

**Comment by tynes** [comment]
You can use `evm_setNextBlockTimestamp` then `evm_mine` on the L1 node and then do a deposit to update the timestamp on L2 because a deposit updates the L2 timestamp to the timestamp of the L1 transaction
