### ISSUE TITLE
MTCannon: Finalize parameter values

### ISSUE THREAD

**Issue by mbaxter** [ethereum-optimism/optimism#11978]
## Description

We have a few somewhat arbitrary parameters in MTCannon:
- FutexTimeoutSteps
- SchedQuantum

We should do some experimentation to optimize and finalize these values.

**Comment by Inphi** [comment]
We should revise these parameters after 64-bit MT-Cannon is done.

**Comment by Inphi** [comment]
Some results on varying `SchedQuantum` values on the alloc.go program compiled using go1.22.

| Allocations | Steps       | Memory Usage | Sched Quantum |
| ----------- | ----------- | ------------ | ------------- |
| 5 64MiB     | 161,662,466 | 130 KiB      | 1K            |
| 5 64MiB     | 95,424,684  | 130 KiB      | 100K          |
| 5 64MiB     | 119,790,368 | 66 KiB       | 10M           |
| 5 64MiB     | 119,720,072 | 66 KiB       | 1B            |
| 10 32MiB    | 223,633,093 | 66 KiB       | 1K            |
| 10 32MiB    | 130,323,045 | 66 KiB       | 100K          |
| 10 32MiB    | 139,783,031 | 34 KiB       | 10M           |
| 10 32MiB    | 139,705,518 | 34 KiB       | 1B            |
| 5 128MiB    | 312,313,355 | 258 KiB      | 1K            |
| 5 128MiB    | 183,023,995 | 258 KiB      | 100K          |
| 5 128MiB    | 232,945,968 | 130 KiB      | 10M           |
| 5 128MiB    | 232,821,887 | 130 KiB      | 1B            |


![Image](https://github.com/user-attachments/assets/a54b7627-8608-4c37-b6a6-6f0ab943e383)

![Image](https://github.com/user-attachments/assets/64145169-9ca1-4ad2-8760-5fb5b192d699)

So the current values are pretty optimal for alloc.go. We should confirm this on a more complex program like the op-program.

**Comment by Inphi** [comment]
## Cannon MT-64 `SCHED_QUANTUM` Measurements

I tried different `SCHED_QUANTUM` values for the Cannon64 VM to run the op-program. The run is a single block derivation on op-mainnet with the following inputs:
```
 --l1.head 0x9fb4b58ecbe4822ea967cbd6ff38ecd09a81e2e83533e48f87188bc1dd454691\
 --l2.head 0xb36bc7bf9947ddcc351bcd552b41159e5f023e0f097f8e643753772cfd0513ce\
 --l2.outputroot 0x04536468464499093b83c3b4a27d83df7ccff8a2a8767222c3909e141d4dffdb\
 --l2.claim 0x3cc206ddaf5f4392d62d289a6c27dfef63b63bccafdf91c94ab7f7c94f4e8f73\
 --l2.blocknumber 129090338\
 --network op-mainnet
```
Note that the prestate is fixed for each run.

| Sched Quantum    | Memory Used (MiB) | Steps (billions)         |
|---------------------|-------------------|--------------------|
| 1K     | 210.3             | 81    |
| 100K             | 227.9             | 45 |
| 10M    | 239.6             | 44    |
| 1B     | 277.4             | 41 |


The performance characteristic is similar to the `alloc.go` measurements for the 32-bit multithreaded VM. In both cases, the current `SCHED_QUANTUM` value of 100_000 offers a good balance between trace length and memory efficiency. It's not terribly advantageous to increase or decrease the `SCHED_QUANTUM` values.

**Comment by Inphi** [comment]
I ran 64-bit Cannon on the same op-program and inputs as above using 10K, 100K, and 1M values for `FutexTimeoutSteps`. This has no impact on execution trace length (steps) and memory usage. This indicates either that futexes do not timeout or they all timeout for longer than 1M steps. In any case, The current 10K timeout value seems adequate for the op-program.
