### ISSUE TITLE
MTCannon: Test behavior when both thread stacks are empty

### ISSUE THREAD

**Issue by mbaxter** [ethereum-optimism/optimism#11977]
## Description

Add differential test (`cannon/mipsevm/tests/evm_multithreaded_test.go`) that validates consistent and correct behavior when the thread stacks are in an invalid state (VM should panic).  The thread state is invalid if the active stack is empty.  

We can improve consistency across implementations by at least updating the [empty threads check here](https://github.com/ethereum-optimism/optimism/blob/6d874d5f543ae4d528e70eab27e9ca1aa687d25e/packages/contracts-bedrock/src/cannon/MIPS2.sol#L165-L167) to this:
```
            if ((state.traverseRight && state.rightThreadStack == EMPTY_THREAD_ROOT) || (!state.traverseRight && state.leftThreadStack == EMPTY_THREAD_ROOT)) {
                revert("MIPS2: illegal vm state");
            }
```

**Comment by Inphi** [comment]
@joohhnnn Would you be able to take a look at this?

**Comment by joohhnnn** [comment]
> @joohhnnn Would you be able to take a look at this?

Sure, would love to.

**Comment by mbaxter** [comment]
After discussion, it looks like we should improve consistency across the go and solidity vm implementations by updating the [empty threads check here](https://github.com/ethereum-optimism/optimism/blob/6d874d5f543ae4d528e70eab27e9ca1aa687d25e/packages/contracts-bedrock/src/cannon/MIPS2.sol#L165-L167) to this:
```
            if ((state.traverseRight && state.rightThreadStack == EMPTY_THREAD_ROOT) || (!state.traverseRight && state.leftThreadStack == EMPTY_THREAD_ROOT)) {
                revert("MIPS2: illegal vm state");
            }
```
