### ISSUE TITLE
MTCannon: Test wakeup traversal across exited thread

### ISSUE THREAD

**Issue by mbaxter** [ethereum-optimism/optimism#11976]
## Description

Add differential test (`cannon/mipsevm/tests/evm_multithreaded_test.go`) that confirms we will not drop exited threads during wakeup traversal.  Existing wakeup traversal tests are [here](https://github.com/ethereum-optimism/optimism/blob/2f2554af50f88840d5ff6f38ba967737878cd933/cannon/mipsevm/tests/evm_multithreaded_test.go#L1330-L1330).

**Comment by Inphi** [comment]
@joohhnnn could you take a look at this?

**Comment by joohhnnn** [comment]
> @joohhnnn could you take a look at this?

Sure 💯

**Comment by Inphi** [comment]
Hey @joohhnnn, what's the status of this issue?

**Comment by joohhnnn** [comment]
> Hey @joohhnnn, what's the status of this issue?

Sorry for the delay, updated in #12551 now
