### ISSUE TITLE
MTCannon: Evaluate potential thread starvation scenarios

### ISSUE THREAD

**Issue by mbaxter** [ethereum-optimism/optimism#11980]
### Description

Try to write a non-buggy Go-based test (see [example](https://github.com/ethereum-optimism/optimism/blob/418fb5e98061da931fdd5fa57436d7f4fc416500/cannon/mipsevm/multithreaded/instrumented_test.go#L37-L58)) that gets the VM into a state where one thread is hogging execution and other threads are not able to progress.  This will allow us to think through mitigations. 

Here is an example of a low-level scenario where a single thread never gets force-preempted (via [the `SchedQuantum` check](https://github.com/ethereum-optimism/optimism/blob/d03509635184369828a27506d85f6f75a2a50099/cannon/mipsevm/multithreaded/mips.go#L281)) leading to thread starvation:
- the last thread thread on the right thread stack requests a [Futex Wakeup](https://github.com/ethereum-optimism/optimism/blob/d204c1f1d28e045f1c2c4442a1395879c44e3257/cannon/mipsevm/multithreaded/mips.go#L127-L127)
- the VM traverses through all of the threads, finding no thread to wakeup
- the VM has now traversed back to last thread with a reset `stepsSinceLastContextSwitch` counter
- this thread gets another full quantum to run, and could repeat the process by calling wakeup again
- if this cycle continues to repeat, no other thread gets executed

**Comment by Inphi** [comment]
Let's timebox this for 2 days.
