### ISSUE TITLE
interop: fix empty log-db starting point edge-case

### ISSUE THREAD

**Issue by axelKingsley** [ethereum-optimism/optimism#12004]
NextLog appears to sometimes (always?) return 0 for the index value. I haven't had time to look into this specific issue, and I've been able to work around it by using the iterator's `Index()`, which should be equal to the returned index.

@protolambda is also making changes to the iterator system which may resolve this bug incidentally.

**Comment by protolambda** [comment]
This was fixed in https://github.com/ethereum-optimism/optimism/pull/12031 and needs to be ported into an isolated PR.

Specifically, it shouldn't return 0, but when opening a starting point it should return `ok=false` when asked if there is a ready block to append to.
