### ISSUE TITLE
OPSM: Add default values when reading input toml files.

### ISSUE THREAD

**Issue by blmalone** [ethereum-optimism/optimism#12008]
This feature request comes from a [comment](https://github.com/ethereum-optimism/optimism/pull/11975#discussion_r1765730126) in a recent PR.

We should figure out what the default values should be for each of the input properties of our TOML files. Keep in might what safe default values should be and then also which values shouldn't have defaults.

**Comment by mds1** [comment]
This is being handled by op-deployer, so closing this
