### ISSUE TITLE
Interop: cross-safe head verification

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#12075]
Cross-safe block verification needs to handle a few edge-cases, which require a more advanced approach than previously implemented.

## L1-derived-from edge case

The `cross-safe` depends on view (= known blocks of L1):
the L2 blocks have `cross-safe` dependencies that may only be batch-submitted much later, outside of the current view.
The cross-safety updater logic needs to apply these L1-view constraints to cross-L2 safety checks.

```
                                              (time = left to right)
      D0                 ________D2______                    L1 DA blocks
      |                 /                \
  ____A0___    -    ____A1___    -    ____A2___              chain A blocks
 /  |   \  \       /  |   \  \       /  |   \  \
e - e - e - e     e - e - e - E*    e - e - e - e            chain A events
    |                 |   x
    x                 x   |
e - e - e - e     e - e - e - e     e - e - e - e            chain B events
 \__|___|__/       \__|___|__/       \__|___|__/
      B0       -        B1       -        B2                 chain B blocks
       \_______________/                  |
               D1                         D3                 L1 DA blocks
To determine:
At D0: A0 is cross-safe.
At D1: B0 is cross-safe, B1 cannot be validated/invalidated yet.
At D2: A1 is invalid, breaks B1. And A2 is invalid because of A1. B1 should be forced to be empty.
At D3: B2 is valid, only if building on an empty B1.
```

## Partial validity edge-case

The cross-safe logic also needs to handle the edge case where a later log invalidates a block that was already partially read:
```
B - e - e - e < E - B - e - e B - e - B
            | _____/
            x
B - e - e - e - B - e - B

B = block
e = log event
E = invalid log event
< = highlighted dependency
x = executing message
```
Notice how an `x` really needs a link to the block-seal B, to not assume that just because the prior events were good, that the events can be consumed. The block that emits the initiating event, as a whole, needs to be valid for executing events to be allowed to consume them.

## intra-block cycle edge-case

Between blocks, to offer low-latency interop, we need to prevent the following:
```
X - a - b - Y     L2 chain A
    x   i
     \ /
      X
     / \
    x   i
P - d - e - Q     L2 chain B

X = cross over, creating the cycle
x = executing
i = initiating
a,b,d,e = messages
X = parent block
Y = block containing a,b
P = parent block
Q = block containing d,e
```
Here you could pay yourself in `a` with an assumed grant from `e`, and then emit the assumed grant in `e` by using the funds you pull into `d`. Essentially an arbitrary flash-loan.
We need to detect and prevent this cyclic intra-block messaging, to ensure the safety of interop.
The individual messages need to form a directed acyclic graph.

**Comment by tynes** [comment]
Some additional notes on the problem:
- https://hackmd.io/@clabby/HkbN4CBkke
- https://gist.github.com/protolambda/4269a1c54ccccf77580e5fc03c8099a4

**Comment by protolambda** [comment]
Mostly done in https://github.com/ethereum-optimism/optimism/pull/12624
Remaining work is tracked in https://github.com/ethereum-optimism/optimism/issues/12682
