### ISSUE TITLE
smoddit: add array modification support

### ISSUE THREAD

**Issue by 0xGorilla** [ethereum-optimism/optimism#1212]
**Is your feature request related to a problem? Please describe.**
Add support for modifying storage arrays

**Describe the solution you'd like**
A possible function call could be:
`await myContract.smodify.array.push('myArray', 123);` in order to push 123
`await myContract.smodify.array.set('myArray', 0, 123);` in order to set 123 to the index 0
`await myContract.smodify.array.remove('myArray', 0);` in order to delete the item at the index 0

**Comment by smartcontracts** [comment]
Hmmm this is an interesting idea. TBH, the `smoddit` API generally needs a refresh. So does the `smock` call assertion API. Currently `smoddit` only supports `setStorage(...)` but ideally it would work in a manner similar to `smock` (`await myContract.smodify.variableName.will.equal(...)` or something).

**Comment by kiwi745** [comment]
It sounds like a great idea maintaining the same naming as smock. So why then not joining smock and smod into a single one?

**Comment by kiwi745** [comment]
Hey guys,

After reading about @smartcontracts 's idea of making some sort of refactor, I went on and created a forked project called [lopt](https://github.com/defi-wonderland/lopt), that contains all of the things you can find in `smock` and some more (you can check out the [docs](https://lopt.readthedocs.io/en/latest/)).

It would be cool if you could just join [this discord server](https://discord.gg/6BzgSEWsdw), and we could talk more about the future of mocking libraries in Solidity 😁
