### ISSUE TITLE
op-e2e enhancement

### ISSUE THREAD

**Issue by zhiqiangxu** [ethereum-optimism/optimism#12142]
Currently it's not so clear which tests depend on external devnet, which don't.

It's better to establish a rule and stick to that.

**Comment by tynes** [comment]
I believe there is only a couple of tests that depend on an external devnet. We are deprecating the docker compose devnet soon

**Comment by protolambda** [comment]
These devnet-dependent tests were removed in https://github.com/ethereum-optimism/optimism/pull/12216
However, with ongoing platforms work on Kurtosis we are bringing back more full-service end to end testing, outside of op-e2e.
And the devnet-allocs dependency in op-e2e is on its way out with the introduction of OPCM and op-deployer.
