### ISSUE TITLE
Batch Submitter can't fix batch

### ISSUE THREAD

**Issue by Boyuan-Chen** [ethereum-optimism/optimism#1214]
**Describe the bug**
The batch submitter can't submit batches, because the queued element doesn't match L1. The timestamp of the queued element is `1625222121`, but the timestamp of the L1 block is `1625222120`. The block numbers of the queued element and L1 block are the same.

It can't be fixed in `fixSkippedDeposits` function, because the wrong element is still pushed to `fixBatch` array.
It doesn't fit any circumstances of `fixMonotonicity` function, so it can't be fixed by `fixMonotonicity`.
It returns error when I picked `fixDoublePlayedDeposits`.

**Expected behavior**
Ideally, `fixSkippedDeposits` shouldn't push the wrong element to `fixBatch` array.

**Comment by smartcontracts** [comment]
Please note that we are rewriting the batch submitter in Go. Not exactly sure where that work is being performed cc @cfromknecht.

**Comment by smartcontracts** [comment]
TypeScript batch submitter has been fully deprecated in favor of the Go batch submitter. Going to close this issue since it's no longer relevant.
