### ISSUE TITLE
MT-Cannon: Support go1.22

### ISSUE THREAD

**Issue by Inphi** [ethereum-optimism/optimism#12146]
Ensure Go programs compiled by Go 1.22 are compatible with MT-Cannon. Compatibility includes syscall interface and ensuring that the go gc works as expected (see [alloc tests](https://github.com/ethereum-optimism/optimism/blob/develop/cannon/mipsevm/multithreaded/instrumented_test.go#L60)). 

Note: Early an implementation of MT-Cannon had issues with the Go 1.22 gc. Though this may no longer be the case.

**Comment by Inphi** [comment]
I manually tested go1.22 programs, particularly alloc.go, on MT-Cannon and it works fine. The Go GC is utilized and alloc.go succeeds in reducing maximum memory usage throughout its MT-Cannon execution.
All that's left is to recompile the Go programs for go1.22. This gives us coverage on singlethreaded and multithreaded VMs for go1.22

**Comment by ajsutton** [comment]
I think it was go1.23 that caused issues for me with cannon-mt - it used a new syscall.

**Comment by Inphi** [comment]
> I think it was go1.23 that caused issues for me with cannon-mt - it used a new syscall.

Yup. I think I tested go1.23 as well when I ran into gc issues. We'll deal with go1.23 compat when the time is right.
