### ISSUE TITLE
op-node can't create genesis.json 

### ISSUE THREAD

**Issue by dome** [ethereum-optimism/optimism#12168]
op-node can't create genesis.json 
in Step 3 Generating L2 Genesis
https://docs.optimism.io/builders/chain-operators/features/custom-gas-token

got error 
lvl=crit msg="Application failed" message="failed to fetch startBlock from SystemConfig: failed to call startBlock: failed to fetch batch: execution reverted"

**Comment by dome** [comment]
tags op-contracts/v2.0.0-beta.3 work fine

**Comment by askucher** [comment]
But it was working correctly before on v1.9.1
