### ISSUE TITLE
MTCannon: Add more test coverage over Go concurrency primitives

### ISSUE THREAD

**Issue by mbaxter** [ethereum-optimism/optimism#12162]
## Description

Add more test coverage over Go concurrency primitives.  In particular, we should make sure to exercise [ll/sc instructions](https://github.com/ethereum-optimism/optimism/pull/11906) as this behavior is new in MTCannon. 

We already have [an existing multithreaded Go test](https://github.com/ethereum-optimism/optimism/blob/829728e095532fbe20779b95f06fada985da54ad/cannon/testdata/example/multithreaded/main.go#L11-L46), but we could increase our test coverage around this.  For example, maybe we have a test that does massively parallel atomic updates.

We should consider porting over the tests from [Go's sync package](https://github.com/golang/go/tree/master/src/sync) wholesale.

**Comment by Inphi** [comment]
@GrapeBaBa what do you think of taking this on?

**Comment by GrapeBaBa** [comment]
> @GrapeBaBa what do you think of taking this on?

Of course, please assign it to me.

**Comment by Inphi** [comment]
@GrapeBaBa Are you working on this?

**Comment by GrapeBaBa** [comment]
> @GrapeBaBa Are you working on this?

Yes, just starting out. Sorry for late, If it's not urgent, you can continue to assign it to me; if it's urgent, you can reassign it.

**Comment by Inphi** [comment]
> > [@GrapeBaBa](https://github.com/GrapeBaBa) Are you working on this?
> 
> Yes, just starting out. Sorry for late, If it's not urgent, you can continue to assign it to me; if it's urgent, you can reassign it.

It's not super urgent. Though we're hoping to get this done in the next 2 weeks. Does that time work for you?

**Comment by GrapeBaBa** [comment]
> > > [@GrapeBaBa](https://github.com/GrapeBaBa) Are you working on this?
> > 
> > 
> > Yes, just starting out. Sorry for late, If it's not urgent, you can continue to assign it to me; if it's urgent, you can reassign it.
> 
> It's not super urgent. Though we're hoping to get this done in the next 2 weeks. Does that time work for you?

That should be OK for me.
