### ISSUE TITLE
MT-Cannon: Assert that current thread stack is non-empty

### ISSUE THREAD

**Issue by Inphi** [ethereum-optimism/optimism#12160]
For all MT-Cannon state transitions, a post condition must be that the current thread stack is non-empty. This is a check the VM should enforce. Every thread stack operation, including push, pop and preempt, require a thread to exist. And this assumption is maintained after the operation.

**Comment by mbaxter** [comment]
Reopening to track changes to MIPS2.sol [here](https://github.com/ethereum-optimism/optimism/pull/12815)
