### ISSUE TITLE
Interop: Handle when Local Head exceeds Database

### ISSUE THREAD

**Issue by axelKingsley** [ethereum-optimism/optimism#12186]
In the Supervisor's UpdateLocal functions, it sets the local head pointer to whatever the parameter is. However, it's possible the database doesn't have that data yet. We should detect this case and reject it. We could also use this signal to focus more on syncing the database, as nodes have obviously exceeded the supervisor's index.

**Comment by protolambda** [comment]
No longer the case now that the local unsafe head depends on the tip of the events-DB data. Closing
