### ISSUE TITLE
Interop: use older cross-safe data for finalization

### ISSUE THREAD

**Issue by axelKingsley** [ethereum-optimism/optimism#12184]
When finality lags behind a long way, we need to be able to use older cross-safe data to advance finalization

Today, the L1 dependency is assumed to be based on the cross safe's last sealed block hash, but it's possible this could diverge if finalization is lagging
```
		// TODO we need to consider older cross-safe data,
		//  if we want to finalize something at all on longer lagging finality signal.
		// Could consider just iterating over all derivedFrom contents?
		l1Dep := r.derivedFrom[chainID][crossSafe.LastSealedBlockHash]
```

**Comment by protolambda** [comment]
The safey-index solved this, closing now.
