### ISSUE TITLE
64-bit MT-FPVM Specification

### ISSUE THREAD

**Issue by Inphi** [ethereum-optimism/optimism#12253]
Create a specification for the 64-bit FPVM. This replaces the 32-bit MT-FPVM spec.

**Comment by BlocksOnAChain** [comment]
@Inphi is this something we can close or we plan to open new PRs relevant to specs work?

**Comment by Inphi** [comment]
> @Inphi is this something we can close or we plan to open new PRs relevant to specs work?

The latter.
