### ISSUE TITLE
Bug - auto-calculated `gasLimit` is too low when sending tx w/MetaMask

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#1229]
**Describe the bug**
Several users reported an issue when trying to send an L2 Mainnet tx via MetaMask.
The default auto-calculated `gasLimit` and `gasPrice` appear to be too low, thus making txs fail if a user confirms a tx with the default values.

**To Reproduce**
1. Try to send some amount of ETH to another L2 address.
2. See `gasPrice` and `gasLimit`
3. Try sending tx with default values.
4. Wait for confirmation or failing tx.

**Expected behavior**
Default `gasLimit` and `gasPrice` values should not result in txs failing for users.

**Screenshots**
Taken from discord user messages:

<img width="396" alt="Screen Shot 2021-07-07 at 10 12 12 AM" src="https://user-images.githubusercontent.com/37757724/124784712-cd7ba980-df0b-11eb-9709-97652c416825.png">

<img width="466" alt="Screen Shot 2021-07-07 at 10 22 35 AM" src="https://user-images.githubusercontent.com/37757724/124786339-416a8180-df0d-11eb-8f25-9fae5dfab1b3.png">

**Additional context**
Issue came from reports in discord

**Comment by snario** [comment]
MetaMsk has a fix in an upcoming build https://github.com/MetaMask/metamask-extension/pull/11439#issuecomment-875085717

**Comment by besoeasy** [comment]
Its an issue from META MASK not optimism 🚀

**Comment by K-Ho** [comment]
I believe this was fixed in the latest MM build
