### ISSUE TITLE
Watcher throws if multiple txs found relaying same message

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#1230]
**Feature request**
This request is coming from discord user @Hsiu-Ping(Nicholas) Lin.

Why does the watcher throw an error if multiple transactions are found to be relaying the same message?
Why not return all the transactions that are found?

**Additional context**
See [packages/core-utils/src/watcher.ts#115](https://github.com/ethereum-optimism/optimism/blob/26b39199bef0bea62a2ff070cd66fd92918a556f/packages/core-utils/src/watcher.ts#L111-L117)

**Comment by jgresham** [comment]
A PR is opened for Watcher being removed: https://github.com/ethereum-optimism/optimism/issues/2055
Maybe something fixed in the SDK?

**Comment by smartcontracts** [comment]
This is indeed fixed within the SDK. I'll close this issue out once we've fully deleted the Watcher code.

**Comment by smartcontracts** [comment]
Watcher code has been deleted and SDK v1.0.0 is now out. Closing!
