### ISSUE TITLE
MTCannon: Make the VM's emptythread check more robust

### ISSUE THREAD

**Issue by joohhnnn** [ethereum-optimism/optimism#12409]
Background Information: 
The `<0-bytes-thread>` represents 0x00000000...000, matching the length of the serialized thread.
The` <nil-bytes-thread> `represents no data. 

While addressing issue #11977, it was discovered that the handling of nil and empty threads in the VM is not robust and lacks uniformity. For instance, the GoVm only checks the active thread, whereas the EVM checks both left and right threads for emptiness. Moreover, the scenarios involving nil threads (no bytes) and empty (zero bytes) threads have not been adequately considered.

Here are some stack may be handled.

1. handle these two case both in EVM and GoVM, for example, add `isZeroThreadState` check in https://github.com/ethereum-optimism/optimism/blob/9bbc54b7b5782d41cb71ecaac4ed1e3c3bfcdb10/cannon/mipsevm/multithreaded/state.go#L111

2. Make EVM using `leftThreadStack&!traverseRight` and `rightThreadStack&traverseRight` to check the Thread

3. TBD

**Comment by mbaxter** [comment]
I think the only change we need to make to improve consistency is to update the [empty threads check here](https://github.com/ethereum-optimism/optimism/blob/6d874d5f543ae4d528e70eab27e9ca1aa687d25e/packages/contracts-bedrock/src/cannon/MIPS2.sol#L165-L167) to this:
```
            if ((state.traverseRight && state.rightThreadStack == EMPTY_THREAD_ROOT) || (!state.traverseRight && state.leftThreadStack == EMPTY_THREAD_ROOT)) {
                revert("MIPS2: illegal vm state");
            }
```

**Comment by mbaxter** [comment]
The basic constraint that needs to hold is that there is always an active thread, meaning the active stack has at least one thread.  Otherwise, the vm should revert / panic.

**Comment by joohhnnn** [comment]
The revert reason is appropriate here? Maybe `MIPS2: active thread stack is empty` fit in here？

**Comment by mbaxter** [comment]
Sure that works 👍

**Comment by mbaxter** [comment]
Folded my suggestion into the original ticket, closing this one.
