### ISSUE TITLE
interop: deduplicate payloadHashToLogHash and executing-message utils

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#12424]
The utils that parse and convert log-events are duplicated and should be cleaned up:
- Various functions to convert log-events into an executing message
- `payloadHashToLogHash` to hash a payload-hash and origin-address into log-hash
- Some types/utils that are embedded in op-geth (see PR ), and can be reused in the monorepo once the op-geth functionality lands in the main op-geth branch. Types/helper functions can be aliased in the `supervisor/types` package, so we don't have to guess whether it's in the monorepo package or the geth types package.

**Comment by axelKingsley** [comment]
Fixed in: https://github.com/ethereum-optimism/optimism/pull/12659/files#diff-5b1637bd0d3dff4ded82fe9917a50c832fd717e4d0e209df4710dc250b6d7f2e
