### ISSUE TITLE
op-chain-ops: Cleanup L1 Genesis Generation

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#12518]
We still have codepaths to generate an L1 chainspec that configures clique. The clique engine is no longer maintained as part of `go-ethereum`, we should remove support for it. Once we shipped Ecotone as part of the OP Stack, we enabled blob transactions (EIP-4844). geth running clique does not support blobs, which we generally want to use as part of a local devnet.

This ticket can be considered complete when the following codepath is removed:

https://github.com/ethereum-optimism/optimism/blob/27c12a132d3238b8dda4ea73d947fdd46677a712/op-chain-ops/genesis/genesis.go#L156-L163

As well as removing the `L1UseClique` and `CliqueSignerAddress` fields from the `DeployConfig`

**Comment by mahmudsudo** [comment]
can i take on this issue ?

**Comment by tynes** [comment]
> can i take on this issue ?

Yes definitely!
