### ISSUE TITLE
Remove `onlySuperchainTokenBridge` modifier from SuperchainERC20

### ISSUE THREAD

**Issue by gotzenx** [ethereum-optimism/optimism#12553]
As discussed with @mds1 on [SuperchainWETH Redesign PR](https://github.com/ethereum-optimism/optimism/pull/12514#discussion_r1806432214) to follow on an internal best practice, we will not use modifiers if they dont have code before and after `;`.

**Change**
Remove `onlySuperchainTokenBridge` from `SuperchainERC20` and add the check line to the functions directly.

**Comment by tynes** [comment]
Could we also update the tenses of the events so that they match the spec in this PR?

**Comment by gotzenx** [comment]
> Could we also update the tenses of the events so that they match the spec in this PR?

Yes, we already had this change ready but we were waiting on the SuperchainWETH Redesign to be merged.
Events changes PR: https://github.com/ethereum-optimism/optimism/pull/12564

@tynes
