### ISSUE TITLE
optimism_rollupConfig returns channel_timeout: 300 on Granite

### ISSUE THREAD

**Issue by Wazabie** [ethereum-optimism/optimism#12572]
**Bug Description**

The RPC call `optimism_rollupConfig` returns `channel_timeout: 300` on Granite, for OP dev/test/main net, while it should be `50` according to [specs](https://specs.optimism.io/protocol/granite/derivation.html)

I wanted to confirm that `channel_timeout` is actually `50` and that the correct value is returned by the RPC call as it seems a RPC layer bug.

**Steps to Reproduce**

Make the `optimism_rollupConfig` RPC call

**Expected behavior**

`channel_timeout` should be `50` on Granite according to [specs](https://specs.optimism.io/protocol/granite/derivation.html)

**Environment Information:**

This occurs on Granite, on all OP nets - dev/test/main

---

⚠️ **Notice:** Issues that do not include the following sections will be subject to closure:
- Bug Description
- Steps to Reproduce
- Environment Information

Please ensure all required sections are filled out accurately to expedite the debugging process and improve issue resolution efficiency.

**Comment by Wazabie** [comment]
cc @sbvegan

**Comment by protolambda** [comment]
Starting at the Granite hardfork, the channel-timeout is a constant, and no longer configured through the rollup config. The timeout value in the rollup-config is the pre-Granite value, to support historical syncing. Unfortunately it's not named "historicalTimeout" in the config, but that is what it is.
