### ISSUE TITLE
Cannon64: Migrate 32-bit tests to be forward-compatible

### ISSUE THREAD

**Issue by mbaxter** [ethereum-optimism/optimism#12598]
## Description

After enabling 64-bit tests in CI (https://github.com/ethereum-optimism/optimism/issues/12252),  which will likely involve skipping failing tests temporarily, rework failing 32-bit tests to be forward-compatible with 64-bit Cannon. 

When this ticket is complete, we should no longer be skipping any relevant tests for the 64-bit VM.

**Comment by Inphi** [comment]
https://github.com/ethereum-optimism/optimism/issues/12032 partially blocks this. We can begin the work of migrating existing 32-bit tests. But newly added 32-bit tests will have to be forward compatible as well. This issue cannot be completed until #12032 is complete and the tests introduced are forwards-compatible.
