### ISSUE TITLE
Gas golf for bridge - cloning L2StandardERC20 in the OVM_L2StandardTokenFactory.

### ISSUE THREAD

**Issue by 0xkonata** [ethereum-optimism/optimism#1259]
**Is your feature request related to a problem? Please describe.**
The [factory](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L2StandardTokenFactory.sol#L26) seems building plain [token](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/contracts/optimistic-ethereum/libraries/standards/L2StandardERC20.sol) instance everytime.

**Describe the solution you'd like**
The [EIP-1167 minimal proxy](https://eips.ethereum.org/EIPS/eip-1167) in the factory. The proxy is 45bytes and it can have the implementation address within its bytes. Hence every each token deployment would be far lighter.

**Describe alternatives you've considered**
Just keep using current one.

**Comment by tynes** [comment]
If you open a PR against the `regenesis/0.5.0` branch with this change, it would be greatly appreciated.
https://github.com/ethereum-optimism/optimism/tree/regenesis/0.5.0

**Comment by TransmissionsDev** [comment]
> **Is your feature request related to a problem? Please describe.**
> The [factory](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L2StandardTokenFactory.sol#L26) seems building plain [token](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/contracts/optimistic-ethereum/libraries/standards/L2StandardERC20.sol) instance everytime.
> 
> **Describe the solution you'd like**
> The [EIP-1167 minimal proxy](https://eips.ethereum.org/EIPS/eip-1167) in the factory. The proxy is 45bytes and it can have the implementation address within its bytes. Hence every each token deployment would be far lighter.
> 
> **Describe alternatives you've considered**
> Just keep using current one.

a) The EIP-1167 minimal proxy cannot be deployed on Optimism. It uses unsafe opcodes.

b) I'd argue not using proxies is a good design choice here as tokens don't need to be created by end users frequently. Proxies shift the gas burden from the creator to users (as delegatecalls add an additional 700 gas on each call), and creators really don't need to be optimized for here.

**Comment by 0xkonata** [comment]
Agreed. I close this issue.
