### ISSUE TITLE
EVM Engineering: convert SemverLock.s.sol to Go

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#12637]
Most of the scripts we're running in `contracts-bedrock` are written in Go now, would be nice for consistency if everything else were written in Go too. Also means that semver locking could be made parallel in theory. I'll leave that one up to the implementer, it's probably fine if it's not parallel, doubt the script is particularly slow. Recommend looking at other go scripts inside of `checks` and `autogen` for examples of how to write such scripts.

**Comment by tynes** [comment]
This is a great task for Claude

**Comment by smartcontracts** [comment]
Yep, definitely. cc @AmadiMichael
