### ISSUE TITLE
EVM Engineering: put deploy scripts in the deploy folder

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#12652]
We have a number of deploy scripts that sit at the top-level of the `scripts` folder, like `DeployImplementations.s.sol`. All of these should probably go inside of `scripts/deploy`. Opening this issue as a brief place for discussion, if I get a thumbs up from @mds1 and @maurelian I'd say that this should be executed on.

**Comment by maurelian** [comment]
Totally on board with this.

**Comment by mds1** [comment]
Also onboard

**Comment by smartcontracts** [comment]
@AmadiMichael please also move `scripts/utils/BaseDeployIO.sol` to `scripts/deploy/BaseDeployIO.sol` when doing this change
