### ISSUE TITLE
EVM Engineering: move all snapshot files into snapshots folder

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#12671]
I'd like to propose moving `.gas-snapshot` and `semver-lock.json` into the `snapshots` folder where all of the other snapshots live. I don't see a good reason to have them at the root of the contracts package.

Thoughts?

**Comment by ControlCplusControlV** [comment]
I support this, especially given `.gas-snapshot` is literally a snapshot
