### ISSUE TITLE
EVM Engineering: move top-level markdown files into meta/docs folder

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#12670]
I'd like to propose that top-level markdown files like `VERSIONING.md` and `CONTRIBUTING.md` go into a `docs` or `meta` folder or something like that. No real opinion on what the folder is called. All of those files clog up the top-level folder and we can easily just link to them in the README.

Thoughts?

**Comment by ControlCplusControlV** [comment]
This is worth it imo, I would vote for the folder `/meta`, do you know if README needs to stay top level for github though?

**Comment by smartcontracts** [comment]
Yeah README needs to be top-level

**Comment by ControlCplusControlV** [comment]
Actually, since these files clutter both `./` and `./packages/contracts-bedrock` should we move these top level files to `/meta` and `/meta/contracts-bedrock` or `/meta` and `/packages/contracts-bedrock/meta` ?

**Comment by smartcontracts** [comment]
I'd prefer `contracts-bedrock/meta` for now

**Comment by ControlCplusControlV** [comment]
Fixed in #12727
