### ISSUE TITLE
EVM Engineering: add semgrep rule to disallow bare imports in Solidity

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#12689]
We want to disallow imports of the form:

```solidity
import "SomeContract.sol";
```

and instead have

```solidity
import { Something } from "SomeContract.sol";
```

I believe the following rule should work:

```
  - id: sol-style-no-bare-imports
    languages: [solidity]
    severity: ERROR
    message: Import specific components instead of the entire file
    pattern-regex: ^import\s+"[^"]+"\s*;
```

Tasks here are:

- [ ] Implement the rule
- [ ] Add tests for the rule
- [ ] Apply the rule to everything EXCEPT test files

These three should be in one PR to keep things clean

After these are implemented:

- [ ] Apply the rule to test files

**Comment by AmadiMichael** [comment]
I believe this can be checked with go though... It was part of the interface gen script i was working on.

**Comment by smartcontracts** [comment]
I like using semgrep as much as possible since it's easier than adding go scripts for everything

**Comment by smartcontracts** [comment]
Basically for anything that's just simple pattern matching I would use semgrep

**Comment by AmadiMichael** [comment]
> Basically for anything that's just simple pattern matching I would use semgrep

ah okay, makes sense 🫡
