### ISSUE TITLE
Smock: `smodify.put` bool with value `true` gets stored as `false`

### ISSUE THREAD

**Issue by j1mmie** [ethereum-optimism/optimism#1275]
**Describe the bug**
In some cases, `smodify.put` attempts to stores a bool with value `true` and completes without error, but upon checking the value, it appears to have been stored as `false`.

**To Reproduce**
Example repository with repro case here:
https://github.com/j1mmie/Smock_1.1.9_Test

The gist of it is that this sort of test should NEVER fail:

```
# SmockTest.sol
contract SmockTest {
  bool public booleanOne = true;
  bool public booleanTwo = true;
}

#SmockTest.spec.ts
expect(await contract.booleanTwo()).to.be.equal(true)
await contract.smodify.put({ booleanTwo: true })
expect(await contract.booleanTwo()).to.be.equal(true)
```

But in the above repo, the test fails.

**Expected behavior**
`smodify.put` should store boolean values correctly

**System Specs:**
 - OS: macOS 10.15.7
 - Package Version (or commit hash): @eth-optimism/smock@1.1.9
 - node @ v16.3.0
 - @nomiclabs/hardhat-ethers@2.0.2
 - @nomiclabs/hardhat-waffle@2.0.1
 - @types/chai@4.2.18
 - @types/mocha@8.2.2
 - @types/node@15.12.2
 - chai@4.3.4
 - ethereum-waffle@3.3.0
 - ethers@5.3.1
 - hardhat@2.3.3
 - solc@0.8.4
 - ts-node@10.0.0
 - typescript@4.3.2

**Additional context**
The test passes when the first boolean (`booleanOne`) is removed from the Solidity contract, even though `booleanOne` is not referenced in the tests or anywhere else.

I added some debug output to the Smock code, in `smoddit.js` I output the values of the parameters that are passed to `putContractStorage`:

```
for (const slot of slots) {
    const a = common_1.toFancyAddress(contract.address)
    console.log('a:', a)
    const b = core_utils_1.fromHexString(slot.hash.toLowerCase())
    console.log('b:', b)
    const c = core_utils_1.fromHexString(slot.value)
    console.log('c:', c)

    await pStateManager.putContractStorage(a, b, c);
}
```

The output is:

```
a:  <Buffer 5f bd b2 31 56 78 af ec b3 67 f0 32 d9 3f 64 2f 64 18 0a a3, buf: <Buffer 5f bd b2 31 56 78 af ec b3 67 f0 32 d9 3f 64 2f 64 18 0a a3>, toString: [Function (anonymous)]>
b:  <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0a>
c: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01>
```

So it appears the value is correctly being interpreted correctly as a `1` / `true`. Maybe the issue is with the VM state manager

**Comment by smartcontracts** [comment]
Hey! Sorry, I took last week off. Just getting back to this now. This is very weird, I'm going to take a look and see what's going on...

**Comment by smartcontracts** [comment]
Ah ok, I know what the issue is. Let me think about the easiest way to fix...

**Comment by smartcontracts** [comment]
Ok the issue was related to the way that Solidity packs storage slots together in order to save gas. I made a quick fix in the PR linked above.

**Comment by j1mmie** [comment]
That’s huge - thanks for you help with this @smartcontracts
