### ISSUE TITLE
inheritance inconsistency between interface and implementation for L1Block

### ISSUE THREAD

**Issue by zhiqiangxu** [ethereum-optimism/optimism#12801]
Currently [`L1BlockInterop`](https://github.com/ethereum-optimism/optimism/blob/c73832d58507d283a7ef0ee4aa5391bb32b145ab/packages/contracts-bedrock/src/L2/L1BlockInterop.sol#L35) inherits `L1Block`, but [`IL1BlockInterop`](https://github.com/ethereum-optimism/optimism/blob/c73832d58507d283a7ef0ee4aa5391bb32b145ab/packages/contracts-bedrock/src/L2/interfaces/IL1BlockInterop.sol#L10) doesn't inherit `IL1Block`.

Is this by purpose? Otherwise I think it's more maintainable for `IL1BlockInterop` to inherit `IL1Block`.

**Comment by smartcontracts** [comment]
This is on purpose, at least for now. We plan to generate interfaces automatically it's easier to do the automated interface generation if you don't have to deal with inheritance. Might change our minds though.

**Comment by zhiqiangxu** [comment]
> This is on purpose, at least for now. We plan to generate interfaces automatically it's easier to do the automated interface generation if you don't have to deal with inheritance. Might change our minds though.

Thanks!
