### ISSUE TITLE
Make `ops/scripts/wait-for-sequencer.sh` wait when the docker-compose node isn't running at all

### ISSUE THREAD

**Issue by qbzzt** [ethereum-optimism/optimism#1280]
**Is your feature request related to a problem? Please describe.**

The purpose of this script is to wait until the node started by `docker-compose up` is available. Exiting when there is no such node available is suboptimal.

**Describe the solution you'd like**

Have the script wait, or exit with an error message "You need to issue docker-compose up to bring it online".

**Describe alternatives you've considered**

None

**Additional context**

N/A

**Comment by smartcontracts** [comment]
I just ran wait-for-sequencer.sh and it appears to work fine, even when the node is not running. Closing.
