### ISSUE TITLE
Allow applications to cancel L2 => L1 messages

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#1283]
**Is your feature request related to a problem? Please describe.**
I've seen several users ask in Discord about cancelling withdrawals once submitted. Currently, we do NOT support this as a feature. I'd like to see some solution(s) that make this possible.

**Describe the solution you'd like**
I can immediately come up with two potential solutions:
1. Add some special function to the L1 side of the Standard Bridge that (1) blocks the L2 => L1 transaction and (2) sends an L1 => L2 transaction that tells the L2 bridge to release the funds. This is the "blunt tool" approach. It's relatively easy, but kinda ugly and forces the user to make an L1 transaction to block the transaction.
2. Replace `OVM_L2ToL1MessagePasser.sentMessages` with another `mapping (bytes32 => uint8)` where the mapping is to an enum that describes the status of the message ("sent" or "cancelled"). Maybe the `OVM_L2ToL1MessagePasser` would allow the sender to change the status of the message within X amount of time and the message can only be relayed if the status is still "sent" after the challenge period. Something something, add X amount of time to the challenge period, something something. It definitely works but I haven't specced it out yet.

**Comment by vaibhavchellani** [comment]
This would increase the latency for L2->L1 communication, so selecting the delay interval carefully is important I think. Do you have a number in mind yet?

**Comment by smartcontracts** [comment]
> This would increase the latency for L2->L1 communication, so selecting the delay interval carefully is important I think. Do you have a number in mind yet?

Yeah it would definitely add latency. Generally I'm assuming that *if* users want to cancel an action they probably want to do it within a relatively short period of time ("I didn't mean to submit that withdrawal!"). So maybe something even as short as <1hr would work. Wdyt?

**Comment by vaibhavchellani** [comment]
So I come from a perspective of offering fast withdrawal services to end-users, what I think cross-domain use cases will need is finality guarantees i.e post a tx-batch on-chain as quickly as possible and do not change it.

From here on its a comparison of "how many users need fast withdraws" and "how many users need withdraw cancellations"

I believe more users need fast withdrawal services, but I am biased.

If we really want to add withdrawal cancellations, I would limit it to even shorter time durations i.e 15-30mins. Curious to wdyt?

**Comment by smartcontracts** [comment]
Yeah, I think you're actually correct. Fast withdrawals essentially makes cancellations unnecessary. You can't cancel an L1 transaction, assuming you get the money pretty much right away on L1 after submitting a withdrawal then you won't be *too* upset about not being able to cancel the withdrawal.
