### ISSUE TITLE
Question:  How to connect Optimistic Mainnet replica to Ethereum Mainnet

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#1287]
Questions coming from Discord community members.

**Questions**
1. How do I run an Optimistic Mainnet replica (from the [op-replica](https://github.com/optimisticben/op-replica) repository)? The README is confusing.
2. Once I have an Optimistic Mainnet replica running, how do I connect it to Ethereum Mainnet? 

**Discord links to the original questions**
* [From `@jure`](https://discord.com/channels/667044843901681675/676980316518481930/867053549263126559)
* [From `@4doce8`](https://discord.com/channels/667044843901681675/676980316518481930/867414361811320842)

**Screenshots**
Screenshot of original questions:

<img width="410" alt="Screen Shot 2021-07-21 at 6 28 54 PM" src="https://user-images.githubusercontent.com/37757724/126572561-21972505-9d51-4f46-9f82-ee5fc2a92d8a.png">

<img width="410" alt="Screen Shot 2021-07-21 at 6 31 44 PM" src="https://user-images.githubusercontent.com/37757724/126572575-2b91da4a-88a5-4d58-816e-b3c8f1f04652.png">

**Comment by smartcontracts** [comment]
I just followed the op-replica tutorial and it was pretty straightforward. Just change `ETH_NETWORK_RPC_PROVIDER` in `.env` to point to your L1 node. Going to close this unless there are additional questions.
