### ISSUE TITLE
Review the Gov Proposal with the Protocol team

### ISSUE THREAD

**Issue by BlocksOnAChain** [ethereum-optimism/optimism#12922]
Early draft is here :https://www.notion.so/oplabs/Holocene-governance-proposal-initial-draft-version-0-3-129f153ee16280598230fde765b718f2

We need review it internally before we share it on the gov website.

Good example doc for us is Fjord Gov proposal: https://gov.optimism.io/t/upgrade-proposal-9-fjord-network-upgrade/8236

**Comment by protolambda** [comment]
Is this done? Can this be closed?

**Comment by BlocksOnAChain** [comment]
Yes, I will close it
final gov proposal version is [here](https://gov.optimism.io/t/upgrade-proposal-11-holocene-network-upgrade/9313)
