### ISSUE TITLE
Add READMEs to Important Packages

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#12967]
It is important to scale context between individuals and teams by reducing the amount of implicit context that is only captured in one person's head. We plan on doing this by adding a `README.md` to each package using the [following template](https://gist.github.com/protolambda/de70584c6f8a8a0348c2a50062f62a9d).

The following packages should be covered:
- [x] `op-batcher`
- [x] `op-node`
- [x] `op-e2e`
- [x] `op-proposer`
- [x] `op-challenger`
- [ ] `op-supervisor`

**Comment by dhir1007** [comment]
can I take this issue?
