### ISSUE TITLE
Proofs: account transaction monitoring service

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#13053]
As part of deploying Drippie for managing hot wallet funds for challenger addresses, we need to create a new monitoring service that can detect transactions coming out of the challenger to unrecognized addresses. Should be part of monitorism.

Includes several sub-tasks:
- [x] Specify the expected behavior of the service
- [x] Create and unit test the service
- [ ] Test the service in a production environment
- [ ] Define appropriate alerting thresholds
- [ ] Test alerts in production
- [ ] Write a runbook for how to handle each alert
- [ ] Launch the service into production with the configured alerts

**Comment by ControlCplusControlV** [comment]
> Specify the expected behavior of the service

The service should be a monotorism based service which takes in a key-value mapping of an address, and all whitelisted addresses it can interact with it. Then it should emit logs everytime the address is involved in sending a transaction, with warn/errors when the addresses it interacts with is outside of the allowed whitelist. It should only require an rpc/ws connection to an Optimism or Ethereum mainnet node, and function regardless of the chain. Additionally it should also warn for suspicious incoming activity
