### ISSUE TITLE
[Smock] - using ".will.return.with([false])" the function still returns true

### ISSUE THREAD

**Issue by JasoonS** [ethereum-optimism/optimism#1305]
**Describe the bug**
When smocking a function that returns a single boolean, using `.will.return.with([false])` on the function still returns `true`.

**Expected behavior**
It should return `false` not `true` if it is told to return `false`.

**Screenshots**

**System Specs:**
 - Package Version (or commit hash): 1.1.10

**Comment by smartcontracts** [comment]
Smock has moved to https://github.com/defi-wonderland/smock. I'm going to try to replicate this with Smock v2 and see what happens. If it still happens, I'll make an issue over there.
