### ISSUE TITLE
Help, I want to fraud proof mainnet ovm tx, but I don't know where to sync the l2geth genesis state.

### ISSUE THREAD

**Issue by r1cs** [ethereum-optimism/optimism#1315]
Help, I want to fraud proof mainnet ovm tx, but I don't know where to sync the l2geth genesis state.
please tell me how can I get all the genesis state info, so I can make fraud proof to eth mainnet ovm tx

**Comment by tynes** [comment]
See https://github.com/optimisticben/op-replica

**Comment by r1cs** [comment]
thx bro!
