### ISSUE TITLE
Problems in deploying L1 contracts for a Custom Gas Token Chain

### ISSUE THREAD

**Issue by monk07-01** [ethereum-optimism/optimism#13157]
Hi @tynes  and/or anybody who could answer. I am trying to build my custom token chain and have reproduced tutorial steps  multiple times.

Dependencies:
Dependency | Minimum         | Actual
git                      2.25.1
go                    1.21.13
node                   22.7.0
foundry        0.2.0 (7a23a5c)
make                      4.2.1
jq                        1.6
direnv                       2.21.2
just                    1.37.0

I am able to produce all the steps up until "Configure your network" section. I usually checkout the tag "op-contracts/v.2.0.0-beta.3" after this section and before deploying contracts. I am following your script as per [Custom Gas Token: Catch-all Discussion + Q&A #140](https://github.com/ethereum-optimism/specs/discussions/140)

I already added the following in getting-started.json 

"useCustomGasToken":true,
"customGasTokenAddress":""

Script for L1 contracts deployement

DEPLOYMENT_OUTFILE=deployments/artifact.json \
DEPLOY_CONFIG_PATH= deploy-config/getting-started.json \
  forge script scripts/deploy/Deploy.s.sol:Deploy \
  --broadcast --private-key $PRIVATE_KEY \
  --rpc-url $ETH_RPC_URL

DEPLOYMENT_OUTFILE=deployments/artifact.json DEPLOY_CONFIG_PATH=deploy-config/getting-started.json   forge script scripts/deploy/Deploy.s.sol:Deploy   --broadcast --private-key $PRIVATE_KEY   --rpc-url $L1_RPC_URL
[⠃] Compiling...2024-12-02T03:31:01.400500Z ERROR foundry_compilers_artifacts_solc::sources: error="/home/monk/optimism/packages/contracts-bedrock/lib/safe-contracts/contracts/GnosisSafe.sol": No such file or directory (os error 2)
[⠊] Compiling...
Error: failed to resolve file: "/home/$USER/optimism/packages/contracts-bedrock/lib/safe-contracts/contracts/GnosisSafe.sol": No such file or directory (os error 2); check configured remappings
        --> /home/$USER/optimism/packages/contracts-bedrock/scripts/deploy/Deploy.s.sol
        safe-contracts/GnosisSafe.sol

It could be because of Safe-contracts library update which names the above file as Safe.sol rather than GnosisSafe.sol

I tried changing the names all over the repo using grep and sed but that created a whole bunch of errors

I am able to complete this tutorial without any problems if following without custom token.

Just to let you know that I have tried multiple variations as to checkout the tag  "op-contracts/v.2.0.0-beta.3"  before building node, proposer, sequencer and geth but that gives error. I stay in tutorials/chain head and change the above tag after all is build.

Please advise as to If I am doing something wrong or what is the best way to resolve.

Also I am building this on cloud architecture Ubuntu 20.04LTS

**Comment by priyanshuthapliyal** [comment]
Hi @monk07-01 you might need to update your foundry version with "just" command then you need to use 
`just build`  command in `/packages/contract-bedrock` directory. It should work after this.
