### ISSUE TITLE
op-proposer: create new game fail if outputRoot is unchanged

### ISSUE THREAD

**Issue by PierreOssun** [ethereum-optimism/optimism#13262]
**Bug Description**

In a staging environment with permissioned fault proofs, when no transactions are received for a period longer than `proposal-interval`, the proposer transaction fails with `GameAlreadyExists`. The op-proposer logs show this error repeating every proposal-interval:

```shell
msg="Failed to send proposal transaction" err="failed to create the tx: operation failed permanently after 30 attempts: failed to estimate gas: execution reverted, reason: 0x014f6fe5b1915a2b357e091ddbe16c95c0ca28488326b894aa1dbc7ca249712ce2ba619a" l1blocknum=7210390 l1blockhash=0x443ccd38f29b4971458d4519c56ef7eae1cdc0e2375bba58581638ec78f7ed8b l1head=7210400
```

**Steps to Reproduce**

Run `op-prosposer` with permissioned fault proof and don't send transactions.

**Expected behavior**

The op-proposer should:

1. Check if the new outputRoot matches the latest output from DGF
2. If they match:
- Log a debug message 
- return `shouldPropose = false`
3. Skip proposal attempt instead of failing with GameAlreadyExists

**Environment Information:**

**Configurations:**

**Logs:**

**Additional context**

I've committed a potential fix here: [Commit](https://github.com/PierreOssun/optimism/commit/da7a97023d0e713ee9ee79a177f538e310442d07#diff-80c3f3adf66ddb226563d36a0cd6bcd1220d22e123364eefa3fb624377730372L87)
Please have a look and I will add tests and open PR after your first look

Thanks

**Comment by ajsutton** [comment]
This is expected if the safe head hasn't advanced.  There is no value in proposing the same output root again - any withdrawals could just use the existing proposal.

**Comment by ajsutton** [comment]
Sorry, hit enter too soon.  It's expected behaviour from the contracts, but making the proposer smarter does make sense - can you open that as a PR?
