### ISSUE TITLE
Having trouble generating L2 Allocs and L2 Genesis : Help needed to name the files that would save the allocs and genesis

### ISSUE THREAD

**Issue by monk07-01** [ethereum-optimism/optimism#13309]
Hi ,

I am trying to create my custom token chain and have been using the script to do it: https://oplabs.notion.site/EXTERNAL-How-to-run-a-Custom-Gas-Token-chain-d88c68306f934790be051f87213a0b1d 

The 1st step has been completed, deploying your Contracts.

**L2 ALLOCS:**

2nd step to generate L2 allocs: Having troubles in naming state_dump_file path and executing it. I tried naming Fjord or Latest but doesn't work 

CONTRACT_ADDRESSES_PATH=deployments/artifact.json \
DEPLOY_CONFIG_PATH=deploy-config/getting-started.json \
STATE_DUMP_PATH= state-dump-fjord.json\                                  
  forge script scripts/L2Genesis.s.sol:L2Genesis \
  --sig 'runWithStateDump()' --chain-id $L2_CHAIN_ID

Need help in naming STATE_DUMP_PATH

I did refer to the below page for naming state_dump_path : https://docs.optimism.io/builders/chain-operators/deploy/genesis

**L2 GENESIS:**

3rd step is to generate L2 genesis after allocs which has the following command to execute

op-node genesis l2 \
  --l1-rpc $ETH_RPC_URL \
  --deploy-config <PATH_TO_MY_DEPLOY_CONFIG> \
  --l2-allocs <PATH_TO_L2_ALLOCS> \
  --l1-deployments <PATH_TO_L1_DEPLOY_ARTIFACT> \
  --outfile.l2 <PATH_TO_WRITE_L2_GENESIS> \
  --outfile.rollup <PATH_TO_WRITE_OP_NODE_CONFIG>

Need help in naming  

--l1-deployments =
--outfile.l2 = 
--outfile.rollup =

please advise as to what filename should be used or to be generated?

Did check all the open and closed issues and other documents but cannot find it. Kindly advise

**Comment by blockchaindevsh** [comment]
You can try [this](https://github.com/zhiqiangxu/opup ) tool which automatically takes care of the parameters.

**Comment by monk07-01** [comment]
I dont think so if that is the right way to do it, that might be the reason why you are having errors in https://github.com/ethereum-optimism/optimism/issues/13327

@priyanshuthapliyal or @tynes  Could you help?

**Comment by tynes** [comment]
> 2nd step to generate L2 allocs: Having troubles in naming state_dump_file path and executing it. I tried naming Fjord or Latest but doesn't work

The `STATE_DUMP_PATH` is the output file that is created. You can name it anything. What is the specific error you see? It could be due to the fs permissions for foundry, you should make sure its writing to a file that has write perms in `foundry.toml`
