### ISSUE TITLE
[Conductor] two sequencer could be active in one cluster

### ISSUE THREAD

**Issue by siddharth0a** [ethereum-optimism/optimism#13438]
## TLDR

- conductor system is not stable
- two sequencer be active status itself

### Log
```
-----------K8S--------------
Seq0
Check Sequencer Active
{"jsonrpc":"2.0","id":1,"result":true}

Check Leadership
{"jsonrpc":"2.0","id":1,"result":false}

Check Sequencer Healthy
{"jsonrpc":"2.0","id":1,"result":true}

Seq1
Check Sequencer Active
{"jsonrpc":"2.0","id":1,"result":true}

Check Leadership
{"jsonrpc":"2.0","id":1,"result":true}

Check Sequencer Healthy
{"jsonrpc":"2.0","id":1,"result":true}

Seq2
Check Sequencer Active
{"jsonrpc":"2.0","id":1,"result":false}

Check Leadership
{"jsonrpc":"2.0","id":1,"result":false}

Check Sequencer Healthy
{"jsonrpc":"2.0","id":1,"result":true}
```

## situation
I setup 3 sequencer set with conductor and make cluster of them. 
status: seq-2 active, and seq-1, seq-0 are follwer.

After some time goes on, there was two sequencer active status. this situation is not proper for conductor purpose.
status: seq-1, seq-2 active, and seq-0 is follwer.

Although the second sequencer cannot commit block on conductor cluster, it could makes disorder to cluster

I'm analyzing the specific logic for this disorder.

Let's make solution for this fail situation.

**Comment by 0x00101010** [comment]
Hi @siddharth0a this is a "normal" situation that the system has considered.

1. Raft guarantees that at any point in time there will only be one leader
2. There might be issues with closing / stopping sequencer (thus active sequencer), or even the conductor process is gone entirely and the way we guarantee it not cause disruption to the network is to have active sequencer commit unsafe payload to conductor first before gossiping it out, this way we make sure that the unsafe head is agreed upon during all the sequencers.

So as a result, I don't think it could `makes disorder to cluster`. You just need to do normal recovery for that node (figure out why it cannot be stopped, and restart it). The situation currently feels like a misconfig between conductor and sequencer that conductor somehow cann't stop sequencer from sequencing after leadership is transferred

**Comment by 0x00101010** [comment]
Close due to not further activities
