### ISSUE TITLE
[Conductor] Suggest for op-conductor action Channel queue increase

### ISSUE THREAD

**Issue by siddharth0a** [ethereum-optimism/optimism#13434]
There are still race condition for op-conductor status change work

## Problem Description
The current implementation of `queueAction()` in the `OpConductor` has a race condition that can lead to missed state updates when multiple state changes occur simultaneously.

## Current Behavior
- When multiple state updates occur near-simultaneously, only one action may be queued
- The `default` case in `select` statement causes subsequent state change actions to be silently dropped

## Specific Scenarios
- Leadership status changes
- Health status changes
both status changes can not be handled and only one would be change

## Potential Solutions
1. Implement a buffered channel
2. Create a synchronized worker queue
3. Use an atomic state tracking mechanism with a more robust queuing strategy

https://github.com/ethereum-optimism/optimism/blob/68f77aaa317b9184cbbcd1526bc57bce1722906b/op-conductor/conductor/service.go#L72

https://github.com/ethereum-optimism/optimism/blob/68f77aaa317b9184cbbcd1526bc57bce1722906b/op-conductor/conductor/service.go#L597-L604

I would like to suggest first solution that doesn't change much current code like 
```
actionCh:     make(chan struct{}, 10),
```

@0x00101010

**Comment by 0x00101010** [comment]
Hey @siddharth0a, thanks for the suggestion and time to put up this issue.

However, I believe the system works as intended now, please note that the action handles situation where both leader status and health status are updated. Thus we only keep a size one buffer for action queue, we don't need to perform multiple actions to do state transition, the [action](https://github.com/ethereum-optimism/optimism/blob/develop/op-conductor/conductor/service.go#L634) itself handles all possible state transition cases.
