### ISSUE TITLE
Tell me when I trace a transaction that hasn't been finalized

### ISSUE THREAD

**Issue by qbzzt** [ethereum-optimism/optimism#1345]
**Is your feature request related to a problem? Please describe.**

`core-utils/watcher` (https://github.com/ethereum-optimism/optimism/blob/develop/packages/core-utils/src/watcher.ts) lets me resolve a withdrawal's hash to the hash of the transaction that finalizes it:

```
const lookupL2toL1 = async () => {
    console.log(`withdrawal L2 TX hash: ${withdrawalL2TxHash}`)  
    const [withdrawalHash] = await kovanWatcher.getMessageHashesFromL2Tx(withdrawalL2TxHash)
    console.log(`withdrawal hash: ${withdrawalHash}`)
    const l1withdrawalReceipt = await kovanWatcher.getL1TransactionReceipt(withdrawalHash)
    console.log(`withdrawal L1 TX hash: ${l1withdrawalReceipt.transactionHash}`)
}
```

There is a significant time lag between when a withdrawal transaction starts and when it is finalized. This time lag is
composed of two separate periods:

1. Between the initial transaction and when the transaction can be finalized (the challenge period, one minute on kovan and a week on mainnet)
2. Between when the transaction can be finalized and when it actually is finalized (depends on the user)

I am not sure what happens during the first period, but during the second period, if you try to use the watcher (`kovanWatcher.getL1TransactionReceipt`), the Promise never resolves.

**Describe the solution you'd like**

I want the option to get back "No answer yet", or "still waiting for it to be finalized" instead of just hanging there.

**Comment by smartcontracts** [comment]
This will be resolved as part of the SDK.

**Comment by smartcontracts** [comment]
Resolved in the SDK
