### ISSUE TITLE
Suggestion: use dorny/paths-filter GitHub action instead of custom scripts

### ISSUE THREAD

**Issue by paulrberg** [ethereum-optimism/optimism#1347]
**Is your feature request related to a problem? Please describe.**

Some of the steps that check the modified files are unnecessarily verbose. E.g. https://github.com/ethereum-optimism/optimism/blob/796dbda597bf249cf31dfe4feb026c9968e26aaf/.github/workflows/ts-packages.yml#L78-L96.

**Describe the solution you'd like**

The number of lines would shrink if you used the GitHub action [dorny/paths-filter](https://github.com/dorny/paths-filter).

**Comment by smartcontracts** [comment]
Would be a good first issue for someone to tackle

**Comment by 0xB548E** [comment]
This part has been removed in the meantime @[21b17eddaf](https://github.com/ethereum-optimism/optimism/commit/21b17eddafd5619843e7cd9bd06506312ab8c36b#diff-87ee5504a3e25ac558b343724c905f2f7949e8cec3d92b9c4300bb922afa164f)

We can probably close this issue. Pls someone correct me if I'm wrong.

**Comment by smartcontracts** [comment]
@0xB548E you are correct. Closing out this issue!
