### ISSUE TITLE
Delete L2OutputOracle and legacy OptimismPortal

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimism#13482]
The `L2OutputOracle.sol` contract is no longer needed since it has been replaced by fault proofs in the system. We should remove this legacy contract to reduce maintenance burden and avoid confusion.

## Steps to Remove

1. Delete the contract file
2. Update Setup.sol and Deploy.s.sol to remove L2OutputOracle-related code
3. Delete or Update any test files that import or reference L2OutputOracle
4. Remove L2OutputOracle references from deployment configs and scripts
5. Remove go tests that use the legacy config, or do not use fault proofs.

**Comment by maurelian** [comment]
Oh, also all of the above applies to the Legacy OptimismPortal as well. 

In order to keep things simple, I think that we should not yet rename `OptimismPortal2`. If we decide to do so, it can be done in a follow up PR

**Comment by tynes** [comment]
> In order to keep things simple, I think that we should not yet rename OptimismPortal2. If we decide to do so, it can be done in a follow up PR

Agree on follow up PR

**Comment by jonas089** [comment]
Now that the L2OutputOracle is deprecated, how can I get the latest L2 root from Ethereum? Is that even possible anymore?

@maurelian
