### ISSUE TITLE
feature request: allowe configuring event query block range in watcher service

### ISSUE THREAD

**Issue by NIC619** [ethereum-optimism/optimism#1379]
**Is your feature request related to a problem? Please describe.**
The public endpoint now limits the block range of the event queries so when using the watcher service the endpoint will return with `eth_getLogs are limited to a 10,000 blocks range` error. But there's currently no way to set the `startingBlock` in the watcher service as `NUM_BLOCKS_TO_FETCH` is hardcoded atm.
https://github.com/ethereum-optimism/optimism/blob/e23b26430b7252057abc800a134d8484af14f917/packages/core-utils/src/watcher.ts#L86
https://github.com/ethereum-optimism/optimism/blob/e23b26430b7252057abc800a134d8484af14f917/packages/core-utils/src/watcher.ts#L20

**Describe the solution you'd like**
1. Add a note in the doc to inform developers that they should run their own node when using watcher service.
2. Allow passing in the `startingBlock` param of the event query or configuring `NUM_BLOCKS_TO_FETCH ` in watcher service

**Additional context**
Thread on Discord: https://discord.com/channels/667044843901681675/676980316518481930/879581524373172274

**Comment by TransmissionsDev** [comment]
this is already possible. just mutate the `NUM_BLOCKS_TO_FETCH` field like `watcherInstance.NUM_BLOCKS_TO_FETCH = 100`

**Comment by tynes** [comment]
This has been merged and released in https://github.com/ethereum-optimism/optimism/releases/tag/%40eth-optimism%2Fcore-utils%400.5.3
