### ISSUE TITLE
ERC20 token stuck in gateway

### ISSUE THREAD

**Issue by tobias-gp** [ethereum-optimism/optimism#1380]
**Describe the bug**
When using the gateway with custom token addresses, my transfer has not succeeded but the amount is still bound to the gateway's address. 

**To Reproduce**
1. Go to the Optimistic Gateway
2. Transfer sUSD (ETH token address: 0x57ab1ec28d129707052df4df418d58a2d46d5f51, Optimistic token address: 0x8c6f28f2f1a3c87f0f938b96d27520d9751ec8d9)
3. Transaction is executed. 

**Expected behavior**
Amount should be in the Optimistic wallet. 

**Additional context**
Exemplary transaction: https://etherscan.io/tx/0xf13d4e3594edd062e858620211facaaef34c668da74200943612db50c45211aa 

I would be grateful for completing the transfer on your side :)

**Comment by gigamesh** [comment]
@tobias-gp here is the gas refund + extra ETH that @smartcontracts promised. :) 

https://etherscan.io/tx/0x9197bd51a80b89b0bc5553a3438c7fd22d2c28181aceceaf87aab2af61ec1f1b

**Comment by tobias-gp** [comment]
@gigamesh : This is amazing, thank you very much. I see that the sUSD are still on the gateway.

I would have never expected this, you are a truly great dev team! 👍

**Comment by tobias-gp** [comment]
> @gigamesh : This is amazing, thank you very much. I see that the sUSD are still on the gateway, is the system going to refund those automatically?
> 
> I would have never expected this, you are a truly great dev team! 👍

@smartcontracts : Just raising this, thanks so much for the handling so far!

**Comment by smartcontracts** [comment]
Hi @tobias-gp, I just relayed the transaction to send your funds back on Ethereum :-) https://etherscan.io/tx/0x3d0a9165bffe719398b2467a2528d85d935e392006d68322c34623fe251e5e21 I'll send you an email as well to confirm.

**Comment by smartcontracts** [comment]
I'm closing this issue as it's now fully handled! Sorry for the inconvenience here, and thank you for your patience.
