### ISSUE TITLE
Not expected behavior of `mapping(address => bool)` when compiled under ovm.

### ISSUE THREAD

**Issue by IgorSenychCW** [ethereum-optimism/optimism#1381]
Two exactly same contracts have been deployed to [kovan](https://kovan.etherscan.io/address/0x5FEa37E6d51DA49ee71bb7F1919F9163633817ab#code) and [kovan-optimistic](https://kovan-optimistic.etherscan.io/address/0x62Ba967F475c1D4ca59B0e57F9677FD1cCd42fD7#code)

![image](https://user-images.githubusercontent.com/72256997/130573305-47f4bd85-bd6f-4c39-b51e-bc260fb35b18.png)

In case of contract deployed to [kovan-optimistic](https://kovan-optimistic.etherscan.io/address/0x62Ba967F475c1D4ca59B0e57F9677FD1cCd42fD7#code), when calling function `whitelist(address)` from [Etherscan](https://kovan-optimistic.etherscan.io/address/0x62Ba967F475c1D4ca59B0e57F9677FD1cCd42fD7#readContract) or another contract, I'm getting an error `Error: Invalid JSON RPC response: ""` or reverted transaction. 

Does it mean that when compiled under OVM `mapping (address => bool)` works in a different way or am I missing something?

**Comment by TransmissionsDev** [comment]
this is an etherscan issue, not an ovm issue

**Comment by IgorSenychCW** [comment]
@TransmissionsDev Yes, I can confirm that it's only Etherscan issue. Thanks!

**Comment by IgorSenychCW** [comment]
@TransmissionsDev Not sure if I have to open new issue, but [this is another really simple contract](https://kovan-optimistic.etherscan.io/address/0x76558205e4791A1A2F7B31fe9B6734320b7b2956#code) and functions `withdaw1` and `withdaw2` always revert. Those functions are responsible for transferring contract's balance and I don't see any reasons why it should fail. In documentation it's said that we can use [transfer function](https://community.optimism.io/docs/protocol/evm-comparison.html#native-eth) from Solidity in a usual way.

**Comment by smartcontracts** [comment]
Closing this issue since it's an issue with Etherscan and not with the OVM.
