### ISSUE TITLE
User bug:  cannot start `ops` tool docker containers on M1 Mac

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#1405]
**Describe the bug**
I was trying to help debug @matYang's error while starting the docker containers of the `ops` tool.

His error when starting the containers:
![image](https://user-images.githubusercontent.com/37757724/131599919-a4ee119c-ffad-452b-a850-a271256fbb5d.png)

![image](https://user-images.githubusercontent.com/37757724/131599931-5dc0d5e2-31af-4c43-bbd8-ec3b44e4491b.png)

**To Reproduce**

NOTE:  I was not able to reproduce this error with the steps below, but @matYang ran through these steps and received an error. More on what Matt and I did is described by Matt in his comments below this comment :)

1. Git clone repository: `git clone https://github.com/ethereum-optimism/optimism.git`
2. Install and build deps:  ` yarn && yarn build
3. Start and build containers:  `cd ops && docker-compose build && docker-compose up`
4. See errors as shown above

**Expected behavior**
Docker containers should build and start without any errors.

**System Specs:**
 - OS:  M1 Mac
 - Package Version (or commit hash):  docker v20.xx, docker desktop v3.6

**Additional context**
@matYang tried following the repro steps on both a Rosetta and a regular terminal on his M1 Mac.

**Comment by matYang** [comment]
Thanks @platocrat for taking the time to help me.

I should clarify that the error in the screenshot above are results of trying to run

`docker-compose -f docker-compose-nobuild.yml up `

What I am seeing is:
1. l1_chain_1 is able to boot up
2. deployer_1 is able to boot up
3. l2geth_1 initially is able to boot up and waits for dtl
4. dtl_1 tries to bootup, dtl_1 says 'Service has started', then immediately raises network error (the 1st screenshot)

`dtl_1      | {"level":50,"time":1630460045555,"extra":{"message":"Error: could not detect network (event=\"noNetwork\", code=NETWORK_ERROR, version=providers/5.4.4)","stack":"Error: could not detect network (event=\"noNetwork\", code=NETWORK_ERROR, version=providers/5.4.4)\n    at Logger.makeError (/opt/optimism/node_modules/@ethersproject/logger/lib/index.js:187:21)\n    at Logger.throwError (/opt/optimism/node_modules/@ethersproject/logger/lib/index.js:196:20)\n    at JsonRpcProvider.<anonymous> (/opt/optimism/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:491:54)\n    at step (/opt/optimism/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.throw (/opt/optimism/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)\n    at rejected (/opt/optimism/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","code":"NETWORK_ERROR"},"msg":"Caught an unhandled error"}`

5. l2geth_1 throws sag fault (the 2nd screenshot)

`qemu: uncaught target signal 11 (Segmentation fault) - core dumped`

6. all the other containers say connection refused when trying to connect to l2geth_1 and dtl_1

This happens consistently.
I tried to separate the contains and start them one-by-one and this still happens.
This happens in native terminal as well as Rosetta terminal.

**Comment by matYang** [comment]
After failing to run nobuild version, we also tried to follow in instructions on https://github.com/ethereum-optimism/optimism

which we:
pruned Docker containers with `docker system prune -a`
followed instructions and ran

```
cd optimism
yarn clean
yarn build
cd ops
docker-compose down -v
docker-compose build 
```

Build successfully builds `builder` and `l1_chain`, but fails consistently when trying to build `deployer` with error 
```
 => ERROR [stage-1  8/24] COPY --from=builder /optimism/packages/hardhat-ovm/package.json ./packages/hardhat-ovm/packa  0.0s
 => ERROR [stage-1  9/24] COPY --from=builder /optimism/packages/hardhat-ovm/dist ./packages/hardhat-ovm/dist           0.0s
...
 => ERROR [stage-1 15/24] COPY --from=builder /optimism/packages/contracts/artifacts-ovm ./artifacts-ovm                0.0s
```
![image](https://user-images.githubusercontent.com/2754307/131602012-6456ff6c-c2f5-4dd8-aede-99449b28fe6c.png)

This happens for me consistently.
This happens for me in native terminal as well as Rosetta terminal.
This happens for me on develop branch as well as master branch.

**Comment by 0xB548E** [comment]
I just ran it with latest `develop` and it seems like it works fine on M1 now

<img width="828" alt="Screenshot 2021-12-09" src="https://user-images.githubusercontent.com/95565981/145460804-f86c9a72-5c6f-4840-b68c-12ed658b7ebb.png">

**Comment by 0xB548E** [comment]
Important notice: I've increased RAM allocation from 2GB to 6GB for Docker

**Comment by smartcontracts** [comment]
Going to close this, there hasn't been much movement on this issue since it was created and @0xB548E noted that it appears to be working fine. If someone else has issues building on an M1 we can re-open later.
