### ISSUE TITLE
Bug: simple contract with `transfer()` function works on L1 but not on Optimism

### ISSUE THREAD

**Issue by moreira-a** [ethereum-optimism/optimism#1407]
**Describe the bug**
A simple contract with withdraw functions that use the `transfer()` function works normally on L1 but fails on Optimism.
At first, without hardcoding the `gasLimit`, the tests fails with `code=UNPREDICTABLE_GAS_LIMIT`.
As suggested on the Discord channel, I set a `gasLimit` for the deploy and each function call. This way the transaction simply fails.

**To Reproduce**
1. clone the repo at https://github.com/moreira-a/optimism-test
2. Run `npx hardhat test`. It works normally
3. Start a Optimism development node
4. Run `npx hardhat --network optimism test`. It fails

**Expected behavior**
A simple contract like this should work normally on L2

**Screenshots**
Without hardcoded `gasLimit`:
![image](https://user-images.githubusercontent.com/70960269/131689767-fc998f95-be84-4672-a269-9dd80eb0f6fc.png)

With hardcoded `gasLimit`:
![image](https://user-images.githubusercontent.com/70960269/131690077-43371c96-2745-4b41-b7f1-3502bf494a97.png)

**System Specs:**
 - OS: Ubuntu 18.04
 
**Additional context**
Thread on Optimism Discord about this https://discord.com/channels/667044843901681675/667044844366987296/881710177047425054

**Comment by smartcontracts** [comment]
Fixed in the `experimental` branch. Should be merged into develop this week.

**Comment by smartcontracts** [comment]
Please note that this is fixed in OVM 2.0. I'm going to close this issue. OVM 2.0 is already live on Kovan and will be live on Mainnet in exactly 1 week.
