### ISSUE TITLE
User bug:  truffle migration fails

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#1415]
**Describe the bug**
Tried to debug a user's truffle migration script but was unsuccessful.

The error that we both ran into when attempting to run the migration script was:
```
"Organisation" -- L2 gas limit too low: 0, use at least 100000.
```

**To Reproduce**
1. Git clone project and checkout branch: `https://github.com/platocrat/eth-dapp.git && git checkout fix/deployment`
2. `cd ./truffle\ project/`
4. Install deps:  `yarn`
6. Compile contracts: `yarn truffle compile --config truffle-config-ovm.js`
7. Run migrations:  `yarn truffle migrate --config truffle-config-ovm.js`
8. See error

**Expected behavior**
Since the setup of this project is quite similar to Optimism's Truffle tutorial, migrations should deploy contracts without errors.

**System Specs:**
 - OS: MacOS
 - Package Version (or commit hash):

**Additional context**
* ~~[Reference to the changes i made to their repository to run the migrations script](https://github.com/CryptoBROKE-rs/eth-dapp/pull/4#issuecomment-912179558)~~ Ignore this since they have since made their repository private :rip:

**Comment by qbzzt** [comment]
It looks like you're deploying to Kovan (https://github.com/platocrat/eth-dapp/blob/fix/deployment/truffle%20project/truffle-config-ovm.js#L9-L19). 

There is a known problem here. https://github.com/trufflesuite/truffle/issues/4217

**Comment by matYang** [comment]
running into exact same problem here, tried to specify gas parameter for the deployer and still no luck, it is weird because I'm explicitly specifying a value for gas limit in tx options, but Truffle is still saying `gas limit too low: 0`

**Comment by matYang** [comment]
Was trying to figure this out, what surprised me was, when I did a clean start, i.e.

```
truffle unbox optimism
// set our Kovan mnemonic and Infura ID
truffle compile
truffle test --config truffle-config.ovm.js --network optimistic_kovan
```

I'm now getting this same error, while it used to succeed two days ago.

**Comment by matYang** [comment]
and this replicates consistently on Truffle 5.4.9 and 5.3.2

**Comment by matYang** [comment]
Found that manually setting gas: 0 actually gets around this issue and makes some transactions succeed, now I have a new problem, when deploying a new contract, I got
`fee too low: 164999985000000, use at least tx.gasLimit = 24659999 and tx.gasPrice = 15000000`
then I tried the suggested gas limit and got
'invalid transaction: exceeds block gas limit'

**Comment by harshmaur** [comment]
The L2 gas too low is also coming up on remix and hardhat. It's not exclusive to truffle.

**Comment by smartcontracts** [comment]
We're fixing this in the `experimental` branch. Should be ready in the next few days.

**Comment by matYang** [comment]
Truffle starts working for me again after they pulled in a merge that would call eth_estimateGas in their provider, here: https://github.com/trufflesuite/truffle/pull/4296

The fix is merged into Truffle release 5.4.11

**Comment by matYang** [comment]
After latest Truffle version 5.4.11 pulled in https://github.com/trufflesuite/truffle/pull/4296 which would call eth_estimateGas for gas limit, the error now becomes the following:

```
Error:  *** Deployment Failed ***

"SimpleStorageTest" exceeded the block limit (using Truffle's estimate).
   * Block limit: 11000000 (0xa7d8c0)
   * Report this error in the Truffle issues on Github. It should not happen.
   * Try: setting gas manually in 'truffle-config.js' or as parameter to 'deployer.deploy'
```

**Comment by matYang** [comment]
Of course if we use the suggest solution, that is providing a gas limit override in tx options, we get the same 

`SimpleStorageTest" -- L2 gas limit too low: 0, use at least 100000.`

**Comment by matYang** [comment]
Setting a gas limit manually with Truffle 5.4.11 also fails:

If I set gas limit to 4999999, I get
```
"SimpleStorage" exceeded the block limit (with a gas value you set).
   * Block limit:  11000000 (0xa7d8c0)
   * Gas sent:     4999999 (0x4c4b3f)
```

If I set gas limit to 4000000, I get 
"SimpleStorage" -- L2 gas limit too low: 0, use at least 100000.

**Comment by smartcontracts** [comment]
Should be fixed on Optimistic Kovan. I'm going to close this issue. I highly recommend trying Truffle out with OP Kovan and confirming that everything is working as expected!
