### ISSUE TITLE
cannot change wallet address 

### ISSUE THREAD

**Issue by r-hou** [ethereum-optimism/optimism#1443]
**Describe the bug**
I cannot change my wallet address on "https://gateway.optimism.io/". Everytime, I disconnect the wallet and change my account on metamask, then I reconnect to metamask. the account showed on the webpage doesn't change even I clear all the cache in Chrome.

**Expected behavior**
I expect I can change the my account smoothly.

**Screenshots**

**System Specs:**
 - OS: MacOS
 - Package Version (or commit hash): Chrome

**Additional context**

**Comment by smartcontracts** [comment]
Hmmm, are you able to record your screen and show us exactly what you're doing? Will make it easier to debug.

**Comment by smartcontracts** [comment]
Hi, this issue has been quiet for a while now. I'm going to close this issue unless anyone has reports of a similar experience, in which case I will happily re-open it.
