### ISSUE TITLE
L1 Stake ERC20 Decimal Place Gas Miscalculation

### ISSUE THREAD

**Issue by gamedazed** [ethereum-optimism/optimism#1446]
**Describe the bug**

The gas price has 18 decimal places appended to the Gwei cost when depositing DAI, this results in a very high gas price, but also notable that the UI shows no indication the deposit failed due to insufficient funds.

##### notable: I tried USDC and was able to stake without such issues so it's not affecting all ERC20

**To Reproduce**

- Network: Rinkeby L1
- Page: Earn
    * DAI Deposit
        * 300 DAI in possession
        * .049 ETH in possession
        * 250 DAI deposit attempt

- Failed to add Liquidity error message produced in UI

![image](https://user-images.githubusercontent.com/66543372/132995196-faee3e6d-6f9c-40d7-bfbf-f1403df10a3b.png)

- Open the console to see messages such as what follows:

```js
11:01:15.202 MetaMask - RPC Error: err: insufficient funds for gas * price + value: address 0x3529B4E50AbbED0a82371d26049d471280540464 
    have      49 066 321 516 461 071
    want 250 000 000 000 000 000 000 (supplied gas 15010499) 
Object { code: -32000, message: "err: insufficient funds for gas * price + value: address 0x3529B4E50AbbED0a82371d26049d471280540464 have 49066321516461071 want 250000000000000000000 (supplied gas 15010499)" }
​
code: -32000
​
message: "err: insufficient funds for gas * price + value: address 0x3529B4E50AbbED0a82371d26049d471280540464 have 49066321516461071 want 250000000000000000000 (supplied gas 15010499)"
```

``` js
11:01:15.205 Error: insufficient funds for intrinsic transaction cost (error={"code":-32000,"message":"err: insufficient funds for gas * price + value: address 0x3529B4E50AbbED0a82371d26049d471280540464 have 49066321516461071 want 250000000000000000000 (supplied gas 15010499)"}, method="estimateGas", transaction={"from":"0x3529B4E50AbbED0a82371d26049d471280540464","to":"0x99F5557012b681A51E5FBf39FbAa1469D6DDb390","value":{"type":"BigNumber","hex":"0x0d8d726b7177a80000"},"data":"0xc95f9d0e00000000000000000000000000000000000000000000000d8d726b7177a800000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, code=INSUFFICIENT_FUNDS, version=providers/5.4.5)
    value https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    value https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    _e https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    r https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    c https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    _invoke https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    b https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    s https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    promise callback*u https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    ke https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    ke https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    value https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    t https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    c https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    _invoke https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    b https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    a https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    promise callback*u https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    a https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    promise callback*u https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    re https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    re https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    value https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    value https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    t https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    c https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    _invoke https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    b https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    a https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    promise callback*u https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    ke https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    ke https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    value https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    r https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    c https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    _invoke https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    b https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    a https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    promise callback*u https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    Ee https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    Ee https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    Pe https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    e https://gateway.boba.network/static/js/main.2cc9c140.chunk.js:1
    c https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    _invoke https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    b https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    n https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    s https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
    o https://gateway.boba.network/static/js/2.eb185448.chunk.js:2
main.2cc9c140.chunk.js:1:2206853
```

**Expected behavior**
Produce a gas price of 250 000 000 000 000, in other words, with 6 fewer 0's appended and if insufficient funds lead to a failed transaction, that the info be relayed over the UI.

**Comment by smartcontracts** [comment]
Is this a bug with https://gateway.boba.network?

**Comment by gamedazed** [comment]
Yes, sorry that I forgot to mention that in the issue. I tested it on
Rinkeby's L1 of gateway.boba.network, if you'd like any other details I'll
know to watch for inquiries here.
----------------------------------------------------------------
     Some of the console's log in plain text
---------------------------------------------------------------

MetaMask - RPC Error: err: insufficient funds for gas * price + value:
address 0x3529B4E50AbbED0a82371d26049d471280540464 have 48936664440596691
want 100000000000000000000 (supplied gas 14995837)

=================================================================================================================================================================================

06:58:15.381 Error: insufficient funds for intrinsic transaction cost
(error={"code":-32000,"message":"err: insufficient funds for gas * price +
value: address 0x3529B4E50AbbED0a82371d26049d471280540464 have
48936664440596691 want 100000000000000000000 (supplied gas 14995837)"},
method="estimateGas",
transaction={"from":"0x3529B4E50AbbED0a82371d26049d471280540464","to":"0x99F5557012b681A51E5FBf39FbAa1469D6DDb390","value":{"type":"BigNumber","hex":"0x056bc75e2d63100000"},"data":"0xc95f9d0e0000000000000000000000000000000000000000000000056bc75e2d631000000000000000000000000000000000000000000000000000000000000000000000","accessList":null},
code=INSUFFICIENT_FUNDS, version=providers/5.4.5)
    value https://gateway.boba.network/static/js/2.92938e42.chunk.js:2
    value https://gateway.boba.network/static/js/2.92938e42.chunk.js:2
    _e https://gateway.boba.network/static/js/2.92938e42.chunk.js:2
    r https://gateway.boba.network/static/js/2.92938e42.chunk.js:2
    c https://gateway.boba.network/static/js/2.92938e42.chunk.js:2
    _invoke https://gateway.boba.network/static/js/2.92938e42.chunk.js:2
    b https://gateway.boba.network/static/js/2.92938e42.chunk.js:2
    s https://gateway.boba.network/static/js/2.92938e42.chunk.js:2
main.fa700544.chunk.js:1:2204302

--------------------------------------------------------

p.s. I'm sure it's obvious, but title title and math were both wrong in the
issue I opened, I think, but I did test this with USDC with no ability to
reproduce the issue. I believe it was introduced around the time that
decimal places for the ERC20 tokens were being distinguished from a purely
18 digit expectation, no evidence of that though.

**Comment by smartcontracts** [comment]
Since this is related to https://github.com/omgnetwork/optimism and not to our repository, I'm going to close this issue. Please open an issue on the Boba repository over at https://github.com/omgnetwork/optimism/issues.
