### ISSUE TITLE
Upgrade to Solidity 0.8.9

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#1499]
Solidity 0.8.9 was just released to fix a few bugs in 0.8.8. We upgraded to 0.8.8 a few days ago, but we might as well upgrade again. Just need to go into the contract files and bump anything that has 0.8.8 at the top. Also need to bump the version in hardhat.config.ts. Ez pz!

**Comment by elenadimitrova** [comment]
Closed by #1500
