### ISSUE TITLE
Add threshold check for contract code coverage

### ISSUE THREAD

**Issue by elenadimitrova** [ethereum-optimism/optimism#1554]
We run `solidity-coverage` to produce contract code coverage metrics. We should check these against thresholds for branch coverage to ensure we don't fall below the current state of `experimental` branch (`experimental` will soon be merged to `develop` but at the time of writing it's the branch you should be targeting). 
For this threshold check, it's recommended to use `istanbul check-coverage` although we're open to alternative suggestions.

**Comment by spiyer99** [comment]
@elenadimitrova, I'd like to work on this if possible. I just had a few questions:
- `solidity-coverage` doesn't seem to be used as a shell command [anymore](https://github.com/sc-forks/solidity-coverage#solidity-coverage). How are you producing the contract code coverage metrics?
- I can't seem to access the ref link on linear.app for some reason? Could you share a public link?

Thanks!

**Comment by elenadimitrova** [comment]
Done as part of #1646
