### ISSUE TITLE
Can't import  CanonicalTransactionChain.sol

### ISSUE THREAD

**Issue by makoto** [ethereum-optimism/optimism#1585]
**Describe the bug**

**To Reproduce**
1. update `package.json` with `@eth-optimism/contracts": "0.0.0-2021914184730`
2. Create new solidity file including these.

```
import { CanonicalTransactionChain } from "@eth-optimism/contracts/L1/rollup/CanonicalTransactionChain.sol";
import { StateCommitmentChain } from "@eth-optimism/contracts/L1/rollup/StateCommitmentChain.sol";
```

3. Run `npx hardhat compile`

**Expected behavior**

Contract compiles

**Screenshots**

<img width="2339" alt="Screenshot 2021-10-15 at 17 53 03" src="https://user-images.githubusercontent.com/2630/137524497-426b2fe2-e7a1-4da4-86e4-16f25109f447.png">

**System Specs:**
 - OS: OSX
 - Package Version (or commit hash):@eth-optimism/contracts": "0.0.0-2021914184730

**Comment by smartcontracts** [comment]
Now fixed in `regenesis-0.5.0`
