### ISSUE TITLE
Error: Request for method 'eth_chainId on https://mainnet.optimism.io/ failed

### ISSUE THREAD

**Issue by Barukimang** [ethereum-optimism/optimism#1598]
**Describe the bug**
Cannot connect Metamask to Optimism network

**To Reproduce**
1. Go to https://chainlist.org/
2. Click on Optimistic Ethereum
3. See error: Request for method 'eth_chainId on https://mainnet.optimism.io/ failed

**Expected behavior**
A connection to Metamask

**Screenshots**

**Additional context**
Same issue when manually trying to add to Metamask

**Comment by t0od** [comment]
Is it possible that it is a firewall problem? Just like I am in China, if I open a proxy, eth_chainId can be returned correctly every time

**Comment by smartcontracts** [comment]
Closing this, I think it was an issue with QuickNode. We now cache `eth_chainId` on our own proxy infrastructure, seems unlikely this issue will come back.
