### ISSUE TITLE
data-transport-layer doesn't exit on SIGTERM

### ISSUE THREAD

**Issue by optimisticben** [ethereum-optimism/optimism#1657]
**Is your feature request related to a problem? Please describe.**
The data-transport-layer doesn't respond to a SIGTERM signal and shutdown cleanly.

**Describe the solution you'd like**
Add a listener for the termination and stop the running services.

**Describe alternatives you've considered**
After a timeout, docker will forcibly stop the container resulting in possible data loss.

**Comment by smartcontracts** [comment]
Closed by https://github.com/ethereum-optimism/optimism/pull/1838
