### ISSUE TITLE
replica-healthcheck should not exit if endpoints are down

### ISSUE THREAD

**Issue by optimisticben** [ethereum-optimism/optimism#1661]
**Is your feature request related to a problem? Please describe.**
The replica-healthcheck should not exit if it detects **any** errors. This original behaviour is causing issues with how components are started and isn't mindful of the different environments where the software may be running.

**Describe the solution you'd like**
Replica-healthcheck should start and run until a SIGTERM signal is received from the operating system.

New metrics should be added.
- `replica_health_connected` with a label of "sequencer/upstream" or "replica". The value `1` when network connections are successful, `0` when it's failing.
- `replica_health_matching_state_root` metric where `1` means we're currently matching `0`, we're not matching ( and maybe `-1` not enough data)

**Comment by smartcontracts** [comment]
New replica healthcheck no longer has this problem.
