### ISSUE TITLE
Clean up unused imports in the integration tests

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#1682]
**Is your feature request related to a problem? Please describe.**
Our integration test files have a bunch of unused imports. For example, this import is not used:

https://github.com/ethereum-optimism/optimism/blob/214473692184dbc1f0953a1e6078a9ab318a109f/integration-tests/test/fee-payment.spec.ts#L7

**Describe the solution you'd like**
I would like to have someone review all integration tests and delete any unused imports. In vscode, you can see that an import is not used because it's greyed out:

![2021-11-03_13-10](https://user-images.githubusercontent.com/14298799/140133431-0dfb91aa-acf9-4da8-b259-f6612c703779.png)

**NOTE**: Please target the `regenesis/0.5.0` branch.

**Comment by coreyar** [comment]
I turned on this rule for eslint and saw that there are a small number of unused vars in other parts of the project.
Seems like it makes sense to turn on this rule and remove unused vars from the whole project

**Comment by smartcontracts** [comment]
That's fantastic! Thank you :-)

**Comment by smartcontracts** [comment]
Closing! Nice work @coreyar. Send me an ETH address and I'll draw you an op contributor NFT :-)

**Comment by coreyar** [comment]
@smartcontracts Sure thanks! I'm happy to jump on another ticket and keep learning the code base if there is another priority
