### ISSUE TITLE
Canary release versioning scheme can break past releases

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#1687]
**Describe the bug**
Our canary release versioning scheme can break when a new canary release is published on a different branch that is incompatible with existing canary releases. For instance, we recently published canary release version `0.0.0-202192720115` of the `@eth-optimism/message-relayer` package based on the `regenesis/0.5.0` branch. This package relies on the `@eth-optimism/contracts` package as shown in the `package.json`:

https://github.com/ethereum-optimism/optimism/blob/regenesis/0.5.0/packages/message-relayer/package.json#L38

However, note that the version specified here is `"^0.4.13"` with a `^` denoting that it will accept any versions of the `@eth-optimism/contracts` package 0.4.XX where XX > 13. Apparently this caret constraint is carried over to the canary version of the release, so the published package has the following constraint:

`    "@eth-optimism/contracts": "^0.0.0-202192720115",`

`yarn` resolves this to the highest version number that satisfies the constraint, which in this case ends up being `0.0.0-alpha.1` and is not at all what we want. We have a similar issue whenever a new canary release is published because we use `yarn changeset version --snapshot`, which publishes with a version number `0.0.0-DATETIMESTAMP`. Any canary releases published AFTER your desired canary release will have a greater DATETIMESTAMP and therefore will take precedence if a caret constraint exists.

I think we can solve this by entirely removing caret constraints for packages imported within the monorepo, but I need to double-check this.

**Comment by smartcontracts** [comment]
![Screenshot from 2021-11-03 16-59-53](https://user-images.githubusercontent.com/14298799/140191907-ec24dffa-708b-4835-b659-5507b05accc7.png)

**Comment by tynes** [comment]
Good catch, I'm good with being very explicit about versioning of the packages when they import other packages that exist in the monorepo. It is less scalable, but another way to do this is `yarn link` or `npm link`

**Comment by smartcontracts** [comment]
Bleh I think the issue with being explicit is just that it will require manually bumping package versions and we lose a lot of the benefits of changesets. I was hoping that there would be some way to get changesets to pin versions only when releasing a canary release.

**Comment by smartcontracts** [comment]
We could try to use the following experimental option:

https://github.com/atlassian/changesets/blob/9dcc364bf19e48f8f2824ebaf967d9ef41b6fc04/packages/config/src/index.test.ts#L31_L34

This would release canary releases as `<actual version>-<DATETIMESTAMP>` instead of `0.0.0-DATETIMESTAMP`.

**Comment by smartcontracts** [comment]
Scratch that, automatic versioning does still apply when not using caret constraints: https://github.com/ethereum-optimism/optimism/pull/1655/files#diff-39e4ba51a41e33f6e8a570c2bc4dbb8d0e35685a4f819f3157efed7f1b22e2d6R37
