### ISSUE TITLE
Add depcheck to CI

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#1706]
**Is your feature request related to a problem? Please describe.**
Every so often I go through the repository and prune unused dependencies. Dependencies can become unused over time when we remove code and I prefer to get rid of any dependencies that aren't actively being used. I typically make use of [depcheck](https://github.com/depcheck/depcheck) to find unused deps. `depcheck` can also be used to find dependencies that are used but not reflected in the `package.json` file. I think we can use `depcheck` in a more automated way.

**Describe the solution you'd like**
I think it would be best if we had a CI step that ran `depcheck` in each package (including the `integration-tests`) and threw an error if it detected any unused packages. Note that we would have to be able to configure exceptions for certain packages. For example, running `depcheck` inside of `packages/contracts` will catch packages like `@openzeppelin/contracts` which are only used inside the Solidity files and hence not detected by `depcheck`. We could add a `.depcheckignore` file to any packages where this is necessary and use the `--ignore-path` option that `depcheck` provides.

This check should probably live inside the `ts-packages` workflow file: https://github.com/ethereum-optimism/optimism/blob/develop/.github/workflows/ts-packages.yml

**Comment by smartcontracts** [comment]
And you will get this NFT for completing this task 😊 https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/34765029840658706893803010833957019895695699803719888420488474718048794705921

![detective](https://user-images.githubusercontent.com/14298799/140594631-8bed70f1-3705-400a-8c7e-42f5cb1f80dc.png)

**Comment by smartcontracts** [comment]
@noahlitvin just wanted to hop in here and thank you again for implementing this! It's been extremely useful in catching unused dependencies after changes :-) here's a CI run where we realized we could remove `lodash` as a dependency from core-utils after deleting some code: https://github.com/ethereum-optimism/optimism/runs/5128072344?check_suite_focus=true#step:10:8

**Comment by noahlitvin** [comment]
Glad to hear it! 🙌
