### ISSUE TITLE
Move transaction relaying utils into core-utils

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#1707]
**Is your feature request related to a problem? Please describe.**
Our transaction relaying utilities currently live inside of the `message-relayer` package: https://github.com/ethereum-optimism/optimism/blob/develop/packages/message-relayer/src/relay-tx.ts

However, the `message-relayer` is a very specific service that's meant to be used ONLY for the local development environment and the transaction relaying utilities are more useful than the `message-relayer` itself. I'd rather move these utilities and their tests into `core-utils`.

**Describe the solution you'd like**
I think it would be best to move everything inside `relay-tx.ts` and its corresponding tests over to `core-utils`. This would make it easier to deprecate the `message-relayer`. Once this is done, we could actually go as far as making the `message-relayer` package private.

**Comment by smartcontracts** [comment]
And I'll send you this NFT for completing this project 😉 
![unnamed](https://user-images.githubusercontent.com/14298799/140594461-d7a6492f-f82d-478d-a6ca-9570b8ac44e3.png)

**Comment by 0xYYY** [comment]
I can try to tackle this issue, if it's not assigned yet.

**Comment by 0xYYY** [comment]
Moving `relay-tx` to `core-utils` will create a dependency cycle.
`@eth-optimism/contracts -> @eth-optimism/core-utils -> @eth-optimism/contracts`

https://github.com/ethereum-optimism/optimism/blob/c17a73bf8f9baea1380e2201293b70d396211dcc/packages/message-relayer/src/relay-tx.ts#L9

**Comment by smartcontracts** [comment]
Hmm... maybe this belongs in a different (new) package instead. I need to ruminate. We probably do want a specific package for typescript utilities that people can use to interact with the contracts. Maybe that belongs in `@eth-optimism/contracts`? Anyone have thoughts?

**Comment by smartcontracts** [comment]
Going to close this issue in favor of moving these utilities over to the proposed `sdk` package.
