### ISSUE TITLE
Add necessary reminder: A reminder for optimism users to keep enough ETH on the L2 network as Gas

### ISSUE THREAD

**Issue by silentwars** [ethereum-optimism/optimism#1711]
**Is your feature request related to a problem? Please describe.**
When I was active in the community for a long time and volunteered to help, I found that many people exchange all ETH for other currencies on the Uniswap V3 Optimism L2 network. As a result, they did not have enough ETH as Gas for other operations, and their assets were trapped in Optimism. L2, but if you deposit ETH from L1 to L2 through Optimism, it will cost a high amount of Gas, which is bound to bring unnecessary asset loss and a bad experience to users.

**Describe the solution you'd like**
Through technical means or necessary reminders, the problem that users cannot perform other operations on Optimism L2 due to insufficient ETH is reduced.

**Describe alternatives you've considered**
There are a few suggestions: 
1. On Uniswap V3 or other swap Optimism networks, users should give reminders at necessary locations; 
2. Add reminders in the docs/users/deposit or withdrawal tutorial; 
3. gateway.optimism.io/deposit page gives necessary reminders; 
4. On Twitter, Discord FAQ and other media, give reminders at appropriate times and columns;
5. Remind on the corresponding page position of the third-party asset bridge such as celer Bridge, Hop Bridge, etc.
6. Make improvements in the technical aspects. At present, I do not have too mature suggestions on the technical aspects.

**Additional context**
![Reminders on Uniswap](https://user-images.githubusercontent.com/22576479/140534424-60f41a1b-5114-4c96-8d1c-d31e49cb76a5.png)

![Optimistic D or W](https://user-images.githubusercontent.com/22576479/140544922-8bd432a0-6418-4ac4-a107-275c7528350b.png)

![Optimistic dpage](https://user-images.githubusercontent.com/22576479/140534778-20da0f01-8fd5-4b68-85b2-7eafd84a7f91.png)

![celer bridge](https://user-images.githubusercontent.com/22576479/140544867-835b3025-2ba6-4884-a878-4982eeef9cbc.png)

**Comment by smartcontracts** [comment]
I think the main thing we could do here is add a multicall contract that allows users to deposit ETH alongside their token deposits. Would reduce the number of people who complain because they deposit tokens but don't want to spend a bunch more $$$ to deposit ETH.

**Comment by smartcontracts** [comment]
Closing this, I agree it could be useful but needs to be re-opened as an issue in the Gateway repository. Will handle that.
