### ISSUE TITLE
Remove Dictator's from Deployments README

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimism#1737]
**Context**

We have recently introduced a couple 'Dictator' contracts which we use during the deployment of our L1 contracts: #1612. 

Once the deployment is complete, these contracts are no longer used, and are not a component of the system, but they are currently included in the generated [deployments README](https://github.com/ethereum-optimism/optimism/blob/regenesis/0.5.0/packages/contracts/deployments/README.md#mainnet-trial) file.

**Describe the solution you'd like**

Modify the `generate-markdown` script to do something like [how it handles the implementation contracts](https://github.com/ethereum-optimism/optimism/blob/439a5151aff309412ef536f9b178e0388d443251/packages/contracts/scripts/generate-markdown.js#L83-L92), except don't even put them into a comment. They can and should just be ignored.

**Note:** please set the target branch to `regenesis/0.5.0` on a PR.

**Comment by smartcontracts** [comment]
This is resolved now.
