### ISSUE TITLE
Optimism Gateway: Deposit Contract link is incorrect

### ISSUE THREAD

**Issue by Cheshyr** [ethereum-optimism/optimism#1766]
**Describe the bug**
Clicking on the Github icon on the bottom left of gateway.optimism.io takes me to a github 404 error.

**To Reproduce**
1. Go to https://gateway.optimism.io/
2. Click on the github icon next to "Deposit Contract: v0.5.0"
3. See github 404

**Expected behavior**
The link currently goes to "https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1StandardBridge.sol"

I believe it is supposed to go to: "https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/contracts/L1/messaging/L1StandardBridge.sol" but I'm not entirely sure.

**Comment by smartcontracts** [comment]
Confirmed. cc @SmitV

**Comment by smartcontracts** [comment]
Resolved by @SmitV. Thanks for the report!
