### ISSUE TITLE
Have replicas forward write requests to the Sequencer

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#1781]
**Is your feature request related to a problem? Please describe.**
Infrastructure providers (Infura, Alchemy, QuickNode, etc.) currently forward write requests to the Sequencer with custom proxy infrastructure that inspects the JSON-RPC request and checks the method. I have received various requests to build this functionality into the replica node software so that other people can run replicas too and can choose not to rely on infra providers for write requests.

**Describe the solution you'd like**
Modify L2Geth so that replica nodes will forward write requests to the Sequencer if configured with a Sequencer RPC url.

**Comment by n8wb** [comment]
This would be very helpful. This application not being able to accept incoming transactions was very unexpected for me. It would make a lot more sense for them to be automatically forwarded

**Comment by mccordnate** [comment]
Can we get this prioritized? It would greatly simplify requirements for node operators to run their own Optimism nodes.
