### ISSUE TITLE
Help fix this .. i used to get error sometimes when i want to swap on optimism uniswap even if i have enough gas

### ISSUE THREAD

**Issue by holleezy** [ethereum-optimism/optimism#1793]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Specs:**
 - OS:
 - Package Version (or commit hash):

**Additional context**

**Comment by holleezy** [comment]
Great project

**Comment by smartcontracts** [comment]
Hi, please add more detail to the issue! Right now it's not possible to debug your problem.

**Comment by smartcontracts** [comment]
I'm going to close this issue for a lack of detail. Please feel free to open a new issue with additional detail.
