### ISSUE TITLE
opimism,提款的时候遇到页面老是提示

### ISSUE THREAD

**Issue by arcchen008** [ethereum-optimism/optimism#1812]
**Describe the bug**

**To Reproduce**
4. See  @kesar 
![微信图片_20211124143001](https://user-images.githubusercontent.com/90959178/143186754-1c306264-7f88-46e0-960c-fe3c70b857e0.png)
提款页面出现

**Expected behavior**

**Screenshots**

**System Specs:**
 - OS:
 - Package Version (or commit hash):

**Additional context**

**Comment by smartcontracts** [comment]
Confirmed, we have a fix for this in review.

**Comment by smartcontracts** [comment]
This should be resolved now! Going to close. Please let me know if you're still experiencing the issue and I'll reopen this.
