### ISSUE TITLE
docker-compose.yml needs to be at least 3.4 instead of just 3

### ISSUE THREAD

**Issue by saurik** [ethereum-optimism/optimism#1815]
With the current Optimism code, using Docker 20.10.8 and docker-compose 1.25.5:

```
# docker-compose build && echo "Build complete"
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.batch_submitter.build contains unsupported option: 'target'
services.dtl.build contains unsupported option: 'target'
services.deployer.build contains unsupported option: 'target'
services.integration_tests.build contains unsupported option: 'target'
services.relayer.build contains unsupported option: 'target'
```

See this similar issue someone filed against Docker in 2018: https://github.com/docker/compose/issues/5714

> The issue was I've used version 3 which is not the latest from 3.x series as I thought. One needs to use at least version 3.4 for build target to work.

After modifying docker-compose.yml to change the "3" to "3.7", per the above issue:

```
# docker-compose build && echo "Build complete"
WARNING: Some services (gas_oracle, integration_tests, replica, verifier) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
WARNING: Native build is an experimental feature and could change at any time
Building l1_chain
[+] Building 21.5s (11/11) FINISHED
...
```

**Comment by smartcontracts** [comment]
cc @tynes

**Comment by tynes** [comment]
It seems like the `docker-compose` setup relies on some features in specific versions. I will try building with different versions and pin it to the version that supports the features that are used. Note that under the following versions, the `docker-compose` setup is known to work, from my machine:

```bash
$ uname -or
5.10.70-1-MANJARO GNU/Linux

$ docker-compose --version
Docker Compose version 2.0.1

$ docker --version
Docker version 20.10.9, build c2ea9bc90b
```
