### ISSUE TITLE
Upgrade to WETH10 from WETH9, to implement native flashminting

### ISSUE THREAD

**Issue by jessielesbian** [ethereum-optimism/optimism#1839]

**Comment by smartcontracts** [comment]
Interesting. We could just deploy a second WETH instance (but WETH10 this time?). Honestly, anyone could do this but we'd want to popularize it.

**Comment by smartcontracts** [comment]
Going to close this, I think it'd be better for us to deploy WETH10 separately (NOT as a pre-deployed contract, but instead as a normal contract on L2).
