### ISSUE TITLE
Permissionless listing function

### ISSUE THREAD

**Issue by xiaoming-007** [ethereum-optimism/optimism#1840]
At present, the competition on the l2 track is fierce, and arb is already far ahead. Considering the strong periodicity of the blockchain industry, in order for the op to survive the cold winter, I hope that the op will leave the whitelist as soon as possible and turn on the permissionless currency listing function. arb has already turned on permissionless Coin listing function, and ecological construction has been far ahead! From the experience of Ethereum, permissionlessness is an important part of the development ecology of blockchain projects. It is precisely because of permissionlessness that uni, aave and other projects can develop rapidly. In 2019, the star projects of the defi track are now basically in the second place. The track, because of permissionless, the Ethereum ecology shines, so for the rapid development of the ecology, I hope that the project party will start the permissionless listing as soon as possible, so that more projects and more projects can try on the op; The important point is that based on past experience and combined technology and macroeconomic analysis, the bull market of blockchain is likely to be coming to an end. There is still a pull up and it is entering a bear market again. If we can’t develop ecology and accumulate in the bull market Funds, then it is difficult for us to survive the cold winter!
I hope that the project party can operate as soon as possible and solve problems in development, rather than waiting!
The heartfelt words of an op lover!

**Comment by xiaoming-007** [comment]
We have been waiting for too long. As the star project of the l2 track, is it really going to repeat history? Do latecomers always want to top it?

**Comment by xiaoming-007** [comment]
We have been waiting for too long, and we hope that the project party can make changes as soon as possible

**Comment by xiaoming-007** [comment]
Op has been testing for a long time, there is no need for a whitelist at all, maybe it’s time for permissionless

**Comment by smartcontracts** [comment]
The whitelist has now been removed :-)
