### ISSUE TITLE
Potential bug in buyGas function in l2Geth

### ISSUE THREAD

**Issue by mask-pp** [ethereum-optimism/optimism#1922]
Is it reasonable if the balance of the FROM address is less than both GAS *gasLimit and l1Fee?

Please consider carefully, the code link is as follows:
https://github.com/ethereum-optimism/optimism/blob/2b7436788e6998cddbeaae4beac4137047f0efff/l2geth/core/state_transition.go#L187

**Comment by tynes** [comment]
This codepath should never trigger and was added as a failsafe to protect against a particular race condition that has been fixed recently. It will be removed in a future release and it should not be possible to trigger due to checks in the `SyncService`
