### ISSUE TITLE
"Cannot get sync status" error if syncing hasn't yet started

### ISSUE THREAD

**Issue by saurik** [ethereum-optimism/optimism#1970]
When the indexing service doesn't yet know anything, `/eth/syncing?backend=l2` returns `{"syncing":true,"highestKnownTransactionIndex":-1,"currentTransactionIndex":0}` which rollup/client.go attempts to parse into a SyncStatus so rollup/sync_service.go can check `status.Syncing`... only `json: cannot unmarshal number -1 into Go struct field SyncStatus.highestKnownTransactionIndex of type uint64`. (FWIW, the core reason I was actually seeing this was because I should have been using `--rollup.backend l1` instead of `l2`, but clearly the schema is wrong.)

**Comment by smartcontracts** [comment]
:sweat_smile: took a while to get to this, but I've opened #2371 to fix this. Thanks for the report! :pray:

**Comment by smartcontracts** [comment]
Upon further review, I think the "better" fix here would to have Geth automatically pick the sync backend from the DTL (and make a change to the DTL so that it can only have one sync backend or the other).
