### ISSUE TITLE
The construction of community-centric DAO is imminent

### ISSUE THREAD

**Issue by xiaoming-007** [ethereum-optimism/optimism#1977]
With the birth of SOS, people’s calls for DAO are getting louder and more and more community-based populist movements. In order to prevent others from stealing the results of the team, it is recommended that the team build DAO and introduce community governance and incentives, which can not only promote ecological development. , And it can promote the enthusiasm of community participation, make up for the current gap with competitors, and achieve overtaking in corners.

**Comment by smartcontracts** [comment]
Hi @xiaoming-007, we very much appreciate your enthusiasm for the Optimism community :-). We're hard at work trying to grow the ecosystem. Please try to keep issues on this GitHub repository to concrete questions about the code at hand. You're welcome to create more open-ended discussions on the Discussions page: https://github.com/ethereum-optimism/optimism/discussions. Thank you!
