### ISSUE TITLE
Verify contracts in sourcify on deploy

### ISSUE THREAD

**Issue by elenadimitrova** [ethereum-optimism/optimism#1983]
**Is your feature request related to a problem? Please describe.**
Following our last regenesis on 14th November 2021 we verified contracts in both `optimistic-kovan` and `optimistic-mainnet` in `sourcify` and added support for optimism networks there:
https://github.com/ethereum/sourcify/pull/550
https://github.com/ethereum/sourcify/pull/581

This process was manual for the regenesis however for future deployments we should automate that as part of the deploy process. 

**Describe the solution you'd like**
Update the `DeployAndVerifyAndThen` script to add `sourcify` verification step.

**Additional context**
#1722 Adds source code verification on Etherscan during the deployment process. 
#1726 add better error handling into that process. 
#1534 Adds metadata settings to solc to enable contract verification on Sourcify

**Comment by K-Ho** [comment]
@rajivpo has expressed some interest in taking this issue <3. Will leave it to y'all to discuss
