### ISSUE TITLE
Make sure default sender is address(0)

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#1998]
**Describe the bug**
Sort of a bug, but more of a standardization thing between us and other clients. Currently Geth is not defaulting to address(0) when doing a `call` or `estimateGas` without providing a `from` address. It's because of this block of code:

https://github.com/ethereum-optimism/optimism/blob/94d8320cc9340b86bcbb2fead33d1e21ec6a0f76/l2geth/internal/ethapi/api.go#L802-L806

Since every node is considered a mining node (we supply a private key for the mining account), there ends up being a key loaded into the account and therefore `call` and `estimateGas` transactions are being sent from the mining address. I deployed this basic contract on Kovan to confirm that this is the case:

```
contract Tester {
    fallback() external payable {
        assembly {
            mstore(0, caller())
            return(0, 0x20)
        }
    }
}
```
I then sent a `call` to this contract and got the following address back: `0x00000398232E2064F896018496b4b44b3D62751F`. This is the block signer address. Since we don't support in-node wallets for now anyway, I think the easiest fix is to put the block I linked above behind a `if !rcfg.UsingOVM` block.

**Comment by tynes** [comment]
Good catch, this should be a very simple fix
