### ISSUE TITLE
Use hardhat-ethers for importing factories in integration tests

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#2016]
**Is your feature request related to a problem? Please describe.**
Some files in the integration tests still use an older method of importing contract artifacts directly instead of going through `hardhat-ethers`. For example, [basic-l1-l2-communication.spec.ts](https://github.com/ethereum-optimism/optimism/blob/develop/integration-tests/test/basic-l1-l2-communication.spec.ts) includes the following import:

https://github.com/ethereum-optimism/optimism/blob/e634bf2ca62b895db678531c4488aa2d2e2e1a2c/integration-tests/test/basic-l1-l2-communication.spec.ts#L8

This file then creates a contract factory using the JSON object imported from this file:

https://github.com/ethereum-optimism/optimism/blob/e634bf2ca62b895db678531c4488aa2d2e2e1a2c/integration-tests/test/basic-l1-l2-communication.spec.ts#L25-L29

This is not clean.

**Describe the solution you'd like**
It's cleaner to replace this with the functionality already provided by the `hardhat-ethers` plugin. Simply import `ethers` from `hardhat`:

```ts
import { ethers } from 'hardhat'
```

Then import the factory from `ethers`:

```ts
const SimpleStorageFactory = await ethers.getContractFactory('SimpleStorage')
```

Doing this allows us to remove the long (and brittle) JSON imports. Please check other `.spec.ts` files within `integration-tests/test` to see if there are other places where this can also be fixed. :heart:

**Comment by gbalbuena** [comment]
I did a little bit more of digging and got to this pr #2023
