### ISSUE TITLE
Blocknumber monotonicity violation on 0.5.6

### ISSUE THREAD

**Issue by yorickdowne** [ethereum-optimism/optimism#2033]
**Describe the bug**

Updated a synced 0.5.5 replica to l2geth 0.5.6. With every new block, I'd see `Blocknumber monotonicity violation`.

Dropping it back down to 0.5.5 resolved the error messages.

I can likely reproduce this at will: Let me know what is useful to you to track down root cause.

**Comment by tynes** [comment]
Thanks for the report. I believe it is fixed in https://github.com/ethereum-optimism/optimism/pull/2040 but I need to reproduce it locally to be sure. I believe that its falsely reporting that there is a monotonicity error due to the branching logic before the logline.
