### ISSUE TITLE
Improve docstrings and tests for utils inside misc.ts

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#2052]
This is the first in a series of issues related to improving the test coverage within the `core-utils` package.

It should be very easy to add some tests for the functions inside of [misc.ts](https://github.com/ethereum-optimism/optimism/blob/develop/packages/core-utils/src/common/misc.ts). These are all very simple functions. We should aim to have 100% test coverage for this file. As part of this issue, I would also like to improve the docstrings for each function. See the docstring for [reqenv](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/packages/core-utils/src/common/misc.ts#L22-L27) as an example of a good docstring. We need to add docstrings for [clone](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/packages/core-utils/src/common/misc.ts#L15) and [getenv](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/packages/core-utils/src/common/misc.ts#L36).

You can find a [coverage report here](https://app.codecov.io/gh/ethereum-optimism/optimism/blob/develop/packages/core-utils/src/common/misc.ts) for the list of functions and lines that need to be tested.

**Comment by lordofthedance** [comment]
I'm giving this a go, will update if I get blocked.
