### ISSUE TITLE
Improve docstrings and tests for utils inside of hex-strings.ts

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#2053]
This is part of a series of good first issues with the aim to improve the test coverage of the `core-utils` package. Our goal is to get to 100% test coverage within this package :-)

We need to improve the docstrings and test coverage of the utilities that can be found in the [hex-strings.ts](https://github.com/ethereum-optimism/optimism/blob/develop/packages/core-utils/src/common/hex-strings.ts) file within the `core-utils` package. Here is a [coverage report for this file](https://app.codecov.io/gh/ethereum-optimism/optimism/blob/develop/packages/core-utils/src/common/hex-strings.ts) which shows the lines that need to be covered by tests.

The following functions also need docstrings:
- [toRpcHexString](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/packages/core-utils/src/common/hex-strings.ts#L59)
- [padHexString](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/packages/core-utils/src/common/hex-strings.ts#L74)
- [encodeHex](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/packages/core-utils/src/common/hex-strings.ts#L82)
- [hexStringEquals](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/packages/core-utils/src/common/hex-strings.ts#L85)
- [bytes32ify](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/packages/core-utils/src/common/hex-strings.ts#L97)

Please see [toHexString](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/packages/core-utils/src/common/hex-strings.ts#L45-L51) for an example of a good docstring.

Feel free to leave a comment here if you would like to work on this issue and you are not sure about the purpose of these functions. Then I can explain the functions for you so that you'll be able to write a good docstring!

**Comment by jgresham** [comment]
I'll take a try at this today!

**Comment by smartcontracts** [comment]
> I'll take a try at this today!

Wonderful! Let me know if you have any issues :-)
