### ISSUE TITLE
Improve test coverage for address aliasing utils 

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#2054]
This issue is part of a series of issues intended to get the test coverage of `core-utils` up to 100%. 

We use an address aliasing scheme to prevent certain attack vectors where a contract on L1 could impersonate a contract on L2 and vice versa. As part of this, we maintain utilities for clients to be able to compute the aliased version of a given contract address. [The utilities can be found here](https://github.com/ethereum-optimism/optimism/blob/develop/packages/core-utils/src/alias.ts). We're almost at 100% test coverage for this file but a few lines still need to be tested. [You can find a coverage report for this file here](https://app.codecov.io/gh/ethereum-optimism/optimism/blob/develop/packages/core-utils/src/alias.ts).

The goal of this issue is to add tests that cover the lines not covered within the linked coverage report. Should be pretty straightforward!

**Comment by RasenGUY** [comment]
Hi I added a pr to this issue. Hopefully this little one helps out a bit :)

**Comment by smartcontracts** [comment]
Thank you @RasenGUY! I'm running the integration tests on your PR now, if everything passes I think it should be good to ship.

**Comment by RasenGUY** [comment]
Hi @smartcontracts  I is there anything I can do from my side ? It seems the 
integration (go-batch-submitter) did not run or failed to run
