### ISSUE TITLE
Replace Watcher with new SDK in integration tests

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#2055]
I'm labeling this as a "good first issue" but it could be more suited for contributors who have contributed to the codebase a few times already. It's definitely on the meatier side. A new contributor might prove me wrong, so it's worth a shot!

We are in the process of [replacing certain utilities with the new Optimism SDK](https://github.com/ethereum-optimism/optimism/discussions/1898). We are planning to remove the [`Watcher` class from the `core-utils` package](https://github.com/ethereum-optimism/optimism/blob/develop/packages/core-utils/src/watcher.ts). As part of this process, we need to remove any usage of the `Watcher` from within this repository.

Currently, the `Watcher` is only being used inside of this repository as part of the [integration tests](https://github.com/ethereum-optimism/optimism/tree/develop/integration-tests). The goal of this issue is to replace all usage of the `Watcher` in the integration tests with the utilities that can be found in the [`CrossChainProvider`](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/packages/sdk/src/cross-chain-provider.ts#L37) class from the new `@eth-optimism/sdk` package.

Here's how I think this needs to be done:
1. Instead of [creating a `Watcher` when making the `OptimismEnv`](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/integration-tests/test/shared/env.ts#L83), create a `CrossChainProvider` instead.
2. Get rid of the [`watcher-utils`](https://github.com/ethereum-optimism/optimism/blob/develop/integration-tests/test/shared/watcher-utils.ts) file. The only useful function here is `waitForXDomainTransaction`, which is fully replaced by [`CrossChainProvider.waitForMessageReceipt`](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/packages/sdk/src/cross-chain-provider.ts#L399).

I *think* this is it, but there might be additional steps required. You don't actually need to delete the `Watcher` yet, we'll be doing a deprecation notice for that once we confirm this works as a good replacement for the `Watcher`. As always, feel free to ask clarifying questions here if you're interested in working on this but aren't 100% sure about something.

Bonus points if you're willing to give some feedback about how it feels to use the SDK!

**Comment by jgresham** [comment]
I've only made one small contribution, but will try to take a look at this. If this is more urgent, perhaps someone else should take it on. I'll update here if I think I am making good progress.

**Comment by smartcontracts** [comment]
@jgresham this isn't particularly urgent, feel free to have a go at it! I'll get back to this conversation later if we end up wanting to get this done faster but no urgency for now.

**Comment by jgresham** [comment]
Without any changes, I'm trying to run integration tests. I followed this to run optimism local env https://community.optimism.io/docs/developers/build/dev-node/#option-2-building-from-source

then running `yarn test:integration` results in ~30% of tests failing. 

Are there any other steps to run integration tests for local env? I only see steps for live integration tests in integration tests README for https://github.com/ethereum-optimism/optimism/tree/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/integration-tests

**Comment by indeavr** [comment]
> Without any changes, I'm trying to run integration tests. I followed this to run optimism local env https://community.optimism.io/docs/developers/build/dev-node/#option-2-building-from-source
> 
> then running `yarn test:integration` results in ~30% of tests failing.
> 
> Are there any other steps to run integration tests for local env? I only see steps for live integration tests in integration tests README for https://github.com/ethereum-optimism/optimism/tree/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/integration-tests

What OS are you running them under ? 
You can try with docker - 
```docker-compose run integration-tests```

**Comment by smartcontracts** [comment]
@jgresham can you try spinning up the system with `docker-compose up -f docker-compose.yml -f docker-compose.ts-batch-submitter.yml`? I think there might be an issue in the docs right now because we're testing a new batch submitter codebase.

**Comment by smartcontracts** [comment]
@jgresham we're preparing to run an alpha test program of the SDK, I'm going to start digging around in the integration tests to see if I can use the SDK to make other improvements. You're more than welcome to continue work here, or if it's too much I can take the issue over.

**Comment by smartcontracts** [comment]
Yeah I didn't realize how many updates to the integration tests would be required to make this fully work. I'd be happy to take it over if it's too complex.

**Comment by jgresham** [comment]
I was "OOO" this past week and haven't gotten further. 

I'll start digging around tomorrow and see what I can learn about the integration tests. That being said I don't know what all this takes and idk where the SDK is at, so don't feel like you're stepping on toes if you take it over :)

**Comment by jgresham** [comment]
I tried for this today. Commit on my fork [here](https://github.com/jgresham/optimism/commit/4a9461052a667136a8b7d3a577e53819acae3df7). About 5 tests in native-eth.spec.ts are failing on gas fee calculations.

Couple questions @smartcontracts : 
1. Any quick guidance on how to calculate gas fees would be helpful. I see the [MessageReceipt](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/packages/sdk/src/interfaces/types.ts#L198) returned from [CrossChainProvider.waitForMessageReceipt](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/packages/sdk/src/cross-chain-provider.ts#L399) contains [TransactionReceipt](https://docs.ethers.io/v5/api/providers/types/#providers-TransactionReceipt) with numerous properties that could be used to calculate gas fees but I also see additional (`l1GasPrice`, `l1GasUsed`, `l1Fee`). I didn't see `effectiveGasPrice` set on deposit messages, but saw it set on withdraws.
2. Do you want to keep [env.wait](https://github.com/jgresham/optimism/commit/4a9461052a667136a8b7d3a577e53819acae3df7#diff-ddcad9599e1f38130f84505d2605b25aa8b5ef273c02d7244fa2162481c06ba8R149) as far as I can tell it would now just be a single line `return this.messenger.waitForMessageReceipt(tx)`?

**Comment by jgresham** [comment]
I'll use this commit as a reference for making additional changes https://github.com/ethereum-optimism/optimism/commit/3535fb2f79e54c4e1e4af7fa7ddefe78c385ccba

**Comment by smartcontracts** [comment]
> I'll use this commit as a reference for making additional changes [3535fb2](https://github.com/ethereum-optimism/optimism/commit/3535fb2f79e54c4e1e4af7fa7ddefe78c385ccba)

@jgresham I think the best way to handle this is by slightly modifying `waitForXDomainTransaction` to use the CrossChainMessenger for now, see this commit: https://github.com/ethereum-optimism/optimism/pull/2160/commits/dac55f31194c8bc27ebb66a301c47094feeabaf2#diff-fb18fb2767f25c27f31de34f54e12e87ae6a0fb294bc0d8cbcca9f7b92420882R20

**Comment by smartcontracts** [comment]
And then we can get rid of `waitForXDomainTransaction` in the future

**Comment by jgresham** [comment]
> @jgresham I think the best way to handle this is by slightly modifying `waitForXDomainTransaction` to use the CrossChainMessenger for now, see this commit: [dac55f3#diff-fb18fb2767f25c27f31de34f54e12e87ae6a0fb294bc0d8cbcca9f7b92420882R20](https://github.com/ethereum-optimism/optimism/commit/dac55f31194c8bc27ebb66a301c47094feeabaf2#diff-fb18fb2767f25c27f31de34f54e12e87ae6a0fb294bc0d8cbcca9f7b92420882R20)
> 
> Doing this allows you to only slightly modify those other tests without worrying about the gas issues: [dac55f3#diff-ddcad9599e1f38130f84505d2605b25aa8b5ef273c02d7244fa2162481c06ba8R156](https://github.com/ethereum-optimism/optimism/commit/dac55f31194c8bc27ebb66a301c47094feeabaf2#diff-ddcad9599e1f38130f84505d2605b25aa8b5ef273c02d7244fa2162481c06ba8R156)

Looks like I was missing quite a bit here... will take a closer look

**Comment by smartcontracts** [comment]
I've also closed my other PR to give you a chance to tackle this!

**Comment by smartcontracts** [comment]
Amazing work here @jgresham! Not sure if you've already emailed me, but hit me up at [kelvin AT optimism DOT io] if you'd like a hand-drawn contributor NFT :-)
