### ISSUE TITLE
Remove unused variable from integration tests

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#2110]
Simple task, just need to remove this unused variable from the integration tests:

https://github.com/ethereum-optimism/optimism/blob/137f7765b87c862256f0b847d40e18f597895593/integration-tests/test/shared/utils.ts#L148-L149

This variable is used within the `native-eth.spec.ts` test file to get a `sequencerBalance`, but the `sequencerBalance` variable is never actually used after that:

https://github.com/ethereum-optimism/optimism/blob/137f7765b87c862256f0b847d40e18f597895593/integration-tests/test/native-eth.spec.ts#L34-L36

So we can just remove `PROXY_SEQUENCER_ENTRYPOINT_ADDRESS` and `sequencerBalance`. 

---

Please remember to read the [Contributing Guidelines](https://github.com/ethereum-optimism/optimism/blob/develop/CONTRIBUTING.md) if this is your first time contributing to Optimism! It contains useful information that will make the contributing process as easy as possible.

**Comment by RishiKumarRay** [comment]
@smartcontracts can i go for this?

**Comment by RishiKumarRay** [comment]
@smartcontracts please review
