### ISSUE TITLE
Remove unused constants in data-transport-layer

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#2111]
I found some more unused constants in the `data-transport-layer` package: 

https://github.com/ethereum-optimism/optimism/blob/137f7765b87c862256f0b847d40e18f597895593/packages/data-transport-layer/src/utils/constants.ts#L1-L3

`SEQUENCER_ENTRYPOINT_ADDRESS` is entirely unused and can be deleted. `SEQUENCER_GAS_LIMIT` is used here:

https://github.com/ethereum-optimism/optimism/blob/137f7765b87c862256f0b847d40e18f597895593/packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts#L68

But we never actually use the `extraData.gasLimit` value in the rest of the code. We can safely delete both the constant and this variable from the object that gets returned. Note that this will require updating the `SequencerBatchAppendedExtraData` type to remove the `gasLimit` field: 

https://github.com/ethereum-optimism/optimism/blob/137f7765b87c862256f0b847d40e18f597895593/packages/data-transport-layer/src/types/event-handler-types.ts#L39-L53

---

Please remember to read the [Contributing Guidelines](https://github.com/ethereum-optimism/optimism/blob/develop/CONTRIBUTING.md) if this is your first time contributing to Optimism! It contains useful information that will make the contributing process as easy as possible.

**Comment by RishiKumarRay** [comment]
@smartcontracts hey , just a bit curious that's why i am asking , did my email reached to you ?
