### ISSUE TITLE
Outdated /packages/contracts README

### ISSUE THREAD

**Issue by vbaranov** [ethereum-optimism/optimism#2124]
1. `yarn build:dump` task is no longer a part of `yarn build` according to package.json https://github.com/ethereum-optimism/optimism/blob/b6dedc3e448b433223ef86d25079066aa4aba014/packages/contracts/package.json#L20
2. In order to run `build:dump` task, next ENV variables are required:
```
export WHITELIST_OWNER=...
export GAS_PRICE_ORACLE_OWNER=...
export L2_BLOCK_GAS_LIMIT=...
export L2_CHAIN_ID=...
export BLOCK_SIGNER_ADDRESS=...
export L1_STANDARD_BRIDGE_ADDRESS=...
export L1_FEE_WALLET_ADDRESS=...
export L1_CROSS_DOMAIN_MESSENGER_ADDRESS=...
```
, what, I suppose, is worth mentioning in the README.
3. `--ovm-relayer-address` parameter currently is not acceptable by `npx hardhat deploy`. I suppose it should be removed from the README.

**Comment by smartcontracts** [comment]
Ah yeah, I'll go ahead and fix this README

**Comment by smartcontracts** [comment]
Going to do this as a series of PRs cleaning up the contracts README

**Comment by smartcontracts** [comment]
README is now updated.
