### ISSUE TITLE
Remove unnecessary variable in whitelist.spec.ts

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#2154]
Very simple task. [whitelist.spec.ts](https://github.com/ethereum-optimism/optimism/blob/fd6f47d3e61b2aa9e9bae1b758b6b6d930300cbc/integration-tests/test/whitelist.spec.ts) imports this variable:

https://github.com/ethereum-optimism/optimism/blob/fd6f47d3e61b2aa9e9bae1b758b6b6d930300cbc/integration-tests/test/whitelist.spec.ts#L9

However, this same variable already exists on the OptimismEnv object created later:

https://github.com/ethereum-optimism/optimism/blob/fd6f47d3e61b2aa9e9bae1b758b6b6d930300cbc/integration-tests/test/whitelist.spec.ts#L20

Specifically:

```
env.l2Provider
```

We can get rid of the extra import by using `env.l2Provider` instead of `l2Provider` directly.

**Comment by tonykogias** [comment]
I noticed the same happens in [ovmcontext.spec.ts](https://github.com/ethereum-optimism/optimism/blob/develop/integration-tests/test/ovmcontext.spec.ts) and [rpc.spec.ts](https://github.com/ethereum-optimism/optimism/blob/develop/integration-tests/test/rpc.spec.ts)

Do you want me to change those files accordingly or create a new issue & PR ?

**Comment by smartcontracts** [comment]
@tonykogias changing those files as well would be great!
