### ISSUE TITLE
Question: HeaderByNumber(ctx, nil) not returning the correct latest Tx Index.

### ISSUE THREAD

**Issue by FeurJak** [ethereum-optimism/optimism#2174]
Sometimes when I query cl.HeaderByNumber(ctx, nil) or cl.BlockNumber(ctx) (cl -> EthClient from "github.com/ethereum/go-ethereum/ethclient"), I get an incorrect response. 

I.e., at Timestamp: 1644351292, I should be getting Tx Index 3349732 but sometimes I get Tx Index 2758341 which is incorrect. 

Even retrying 90 times with 1 second sleep time per loop, HeaderByNumber or BlockNumber still responds incorrectly.  But after a while, a correct response is given. 

Can anyone fill me in as to why HeaderByNumber() responds incorrectly ?

**Comment by tynes** [comment]
Are you running your own node or what infra provider are you using?

**Comment by FeurJak** [comment]
We're running our own node.

**Comment by tynes** [comment]
What do you mean by incorrect here? It looks like you are querying for the tip by passing `nil`, which changes over time

**Comment by FeurJak** [comment]
I'm trying to get the latest Header. 

cl.BlockNumber(ctx) should return me the latest Number but it doesn't sometimes, i..e. Where I should get 3349948 I get  2758341. 

If I try cl.HeaderByNumber(ctx, nil) where "nil" should return me the latest header, it's the same case, sometimes I get the right response i.e. 3349948 for Number but sometimes I get the wrong response i.e. 2758341.

**Comment by FeurJak** [comment]
Okay I think i know the issue. Looks like I've been using the wrong Archive Node. I'l close this issue.
