### ISSUE TITLE
Ops: relayer container throws errors

### ISSUE THREAD

**Issue by palango** [ethereum-optimism/optimism#2179]
**Describe the bug**
When running the private optimism setup with the relayer container enabled, it crashes with an internal error.

**To Reproduce**
1. Go to `/ops`
2. Run `docker-compose -f docker-compose-nobuild.yml -f docker-compose.yml up --scale relayer=1 -d`
3. Wait a bit
4. Check `relayer` logs to see error:
```
$ docker-compose logs -f relayer
ops-relayer-1  | node:internal/modules/cjs/loader:936
ops-relayer-1  |   throw err;
ops-relayer-1  |   ^
ops-relayer-1  |
ops-relayer-1  | Error: Cannot find module '/opt/optimism/packages/message-relayer/exec/run-message-relayer.js'
ops-relayer-1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ops-relayer-1  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ops-relayer-1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
ops-relayer-1  |     at node:internal/main/run_main_module:17:47 {
ops-relayer-1  |   code: 'MODULE_NOT_FOUND',
ops-relayer-1  |   requireStack: []
ops-relayer-1  | }
```

**Expected behavior**
The relayer should work

**Comment by smartcontracts** [comment]
But yeah this needs to be fixed if we're trying to support the relayer container at all

**Comment by palango** [comment]
> Are you able to try using the SDK instead? See here for an example of how to relay messages with the SDK:

I'm working in an environment that doesn't use type script right now. So the container was the easier solution for me to use.

Will you support some stand-alone tool to relay certain messages or will the SDK the only supported interface? I'm asking because this seems to be a common enough problem to provide a solution for.

**Comment by smartcontracts** [comment]
I'll work on a fix for the relayer package for now. I do agree that it's useful for non-TypeScript/JavaScript environments.

**Comment by smartcontracts** [comment]
Ok #2182 is merged, we'll need to cut a release but at least if you're working directly off this repository then the relayer should work again

**Comment by palango** [comment]
@smartcontracts Thanks for fixing this so quickly. Using the develop branch is fine for me.
