### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'stateRoot')--replica-healthcheck

### ISSUE THREAD

**Issue by masayil** [ethereum-optimism/optimism#2207]
![image](https://user-images.githubusercontent.com/65291464/153752103-e9edbf26-4633-4730-bc98-8c124aeade3a.png)
replica-healthcheck:0.3.7
What caused it?  block:3501433  get wrong?

My l2geth client still keep syncing blocks and works normally

**Comment by smartcontracts** [comment]
I believe this is a duplicate of #1994.

**Comment by masayil** [comment]
thanks.
