### ISSUE TITLE
Listing request from NOWNodes

### ISSUE THREAD

**Issue by NOWNodesNOW** [ethereum-optimism/optimism#2229]
Hello Optimism team! I`m Liza from NOWNodes. We find your platform very interesting and useful
At http://nownodes.io/ we provide access to explorers & nodes APIs of 47 most popular blockchain networks. We are interested in listing here https://community.optimism.io/docs/useful-tools/providers/# Is it possible?

Have a great day!
With best regards,
Elizabeth

**Comment by smartcontracts** [comment]
Hi! Do you offer access to Optimism nodes? I couldn't find Optimism on this page: https://nownodes.io/nodes

If you do offer access to Optimism nodes, I'd be happy to test the service out and then add it to the docs

**Comment by NOWNodesNOW** [comment]
Yes, we offer access to Optimism nodes by request, it is dedicated . So unfortunately we don’t have rights to allow you go there. But, when we get many request for sharing node wich is "by request” we do it. Listing on your website and may be some co-marketing activities in social media can contribute and speed up this process.

**Comment by NOWNodesNOW** [comment]
Hey, we discussed the potential collaboration with you with my team today and want to offer you some variants:

1. We will list Optimism node here https://nownodes.io/nodes <https://nownodes.io/nodes> 
2. We will write and article about Optimisms node ( you may recommend topic or choose theme)
3. We will write short review in Docs which explain that we have may provide access to Optimism BY REQUEST. But if Optimism community will be active and show big volume of requests well make it open. Now we can link your docs there. So our client will know the we have Optimism node and your community will get possibility to use API   

When we will  share Optimism for everybody, of course your team would test it for free 
What do you think?

**Comment by smartcontracts** [comment]
Would you mind filling out this form so we can get in touch? https://optimismpbc.typeform.com/get-in-touch 

This is the best way to get directly in contact with the ecosystem team. When we're ready to add NOWNodes to the documentation website I will open another issue :-)

**Comment by NOWNodesNOW** [comment]
Ok, thank you

вт, 1 мар. 2022 г. в 01:26, smartcontracts ***@***.***>:

**Comment by NOWNodesNOW** [comment]
Hello again! Yesterday we filled out the form. Would you please check?

About testing node, in couple of days I will bring you a free API key to do
it.
вт, 1 мар. 2022 г. в 12:50, Elizabeth B ***@***.***>:
