### ISSUE TITLE
Delete unused variables

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#2274]
I've found some unused variables to delete. Great issue for a first-time contributor. I'll link each of the variables here:

https://github.com/ethereum-optimism/optimism/blob/51a527b8e3fe69940fb8c0f5e4aa2e0ae8ee294c/packages/contracts/test/helpers/constants.ts#L11-L11

https://github.com/ethereum-optimism/optimism/blob/51a527b8e3fe69940fb8c0f5e4aa2e0ae8ee294c/packages/contracts/test/helpers/constants.ts#L4-L9

Deleting `DEFAULT_ACCOUNTS_HARDHAT` also means you can delete this import:

https://github.com/ethereum-optimism/optimism/blob/51a527b8e3fe69940fb8c0f5e4aa2e0ae8ee294c/packages/contracts/test/helpers/constants.ts#L1-L2

This entire JSON file apparently: https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/test/data/json/libraries/trie/Lib_MerkleTrie.test.json

And this line as a result:

https://github.com/ethereum-optimism/optimism/blob/51a527b8e3fe69940fb8c0f5e4aa2e0ae8ee294c/packages/contracts/test/data/index.ts#L5-L5

Should be relatively straightforward, just delete the stuff! Since it's all within the test helpers we don't need to add a changeset. As always, leave a comment below if you'd like to tackle this issue or if you're confused about anything.

**Comment by wkktoria** [comment]
I would like to tackle this issue as my first contribution practice.

**Comment by smartcontracts** [comment]
@wkktoria that would be great, please feel free to make a pull request at your convenience

**Comment by wkktoria** [comment]
I've deleted variables and JSON file that are linked here. Now, I'm trying to recompile packages on my branch, but `yarn build` (I run `yarn clean` before)  returns some errors, test also doesn't pass.

I attach an output which shows up after `yarn build`:
![output](https://user-images.githubusercontent.com/67728762/157336445-c18b46bd-fc65-4af3-906a-ed7aea5670ba.png)

**Comment by smartcontracts** [comment]
Ah... oops. I guess those two variables can't be deleted. My linting tool failed me! Sorry about that.

**Comment by wkktoria** [comment]
After deleting only JSON file `yarn build` works, but there's problem with tests. It looks like this file also cannot be deleted.

I attach output:
![output](https://user-images.githubusercontent.com/67728762/157398719-64c484ce-afae-4c57-9dcb-900d9488d6f2.png)

**Comment by smartcontracts** [comment]
Ah you should also be able to delete this line of code which hopefully will resolve the issue: https://github.com/ethereum-optimism/optimism/blob/7af146daec4dc7fe335aa7ff1349c61cea30157c/packages/contracts/test/data/index.ts#L5

**Comment by wkktoria** [comment]
Everything works now. I've sent a pull request.

**Comment by smartcontracts** [comment]
Great work @wkktoria! See my comment in your pull request regarding the Contributor Club NFT.
