### ISSUE TITLE
Removed outdated section of primary package.json

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#2280]
Tiny issue, great for a first-time contributor. Just need to delete these lines from the primary package.json:

https://github.com/ethereum-optimism/optimism/blob/dfd5ac6eee3f9711f2102cedc69bec8c25a0e0c9/package.json#L15-L17

`examples` no longer exists.

**Comment by amoweolubusayo** [comment]
Kindly check out my PR @ https://github.com/ethereum-optimism/optimism/pull/2303
