### ISSUE TITLE
gas-oracle exited immediately when run by docker-compose

### ISSUE THREAD

**Issue by kiltum** [ethereum-optimism/optimism#2295]
**Describe the bug**
After starting optimism node in docker-comppose, gas-oracle exited almost immediately

**To Reproduce**
1. git clone https://github.com/ethereum-optimism/optimism.git -b develop
2. cd optimism/ops
3. docker-compose -f docker-compose-nobuild.yml up -t 600 -d (or docker-compose -f docker-compose.yml up -d --build --force-recreate - it does not matter)
4. docker ps -a
5. docker logs ID_OF_EXITED_GAS_ORACLE

```
ERROR[03-09|10:23:43.193] Unable to connect to layer two           addr=http://127.0.0.1:9545
CRIT [03-09|10:23:43.197] application failed                       message="Post \"http://127.0.0.1:9545\": dial tcp 127.0.0.1:9545: connect: connection refused"
```

Looks like Sequencer HTTP Endpoint (GAS_PRICE_ORACLE_LAYER_TWO_HTTP_URL) is not set properly.

**Expected behavior**
gas-oracle start successfully

**Comment by smartcontracts** [comment]
Likely fixed by https://github.com/ethereum-optimism/optimism/pull/2300

Can you try again and see if the issue still persists?

**Comment by kiltum** [comment]
Just check from scratch. Problem is exist with same error :(

**Comment by smartcontracts** [comment]
I'll check on this today and see if I can fix

**Comment by smartcontracts** [comment]
Sorry this took a while to get to. Confirmed that this bug exists, trying to figure out why.

**Comment by smartcontracts** [comment]
Alright, I was able to fix this! It hasn't been released yet, but if you build locally from the `develop` branch it should work :-)
