### ISSUE TITLE
Unable to fetch genesis file within the specified timeout

### ISSUE THREAD

**Issue by igorline** [ethereum-optimism/optimism#2299]
**Describe the bug**
It's taking longer than 60 seconds to fetch genesis json.
Timeout was changed recently https://github.com/ethereum-optimism/optimism/blob/27f511688f19db89e66c73cd1337597d855bd511/l2geth/cmd/geth/chaincmd.go#L645 but it's still not helping much

**Expected behavior**
Have an option to specify timeout in the config file. Currently I cannot use https://github.com/optimisticben/op-replica/ docker setup due to the issue.

**Comment by smartcontracts** [comment]
Yeah we should ideally have a configurable timeout here

**Comment by smartcontracts** [comment]
@igorline we've merged #2370 which added support for a new flag `ROLLUP_GENESIS_TIMEOUT_SECONDS` which you can set to change the default timeout from 60 seconds to whatever you need it to be. It should be released in a few days, but if you want to use it sooner you can build from source from the `develop` branch. Thank you for reporting this! :pray:
