### ISSUE TITLE
Hi I am Mohamad 

### ISSUE THREAD

**Issue by Karammohamad** [ethereum-optimism/optimism#2323]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Specs:**
 - OS:
 - Package Version (or commit hash):

**Additional context**

**Comment by smartcontracts** [comment]
Hi Mohamad! Welcome to the Optimism monorepo. I'm going to close this issue since it doesn't include any content, but it's nice to meet you!
