### ISSUE TITLE
Bug: replica-healthcheck docker image 1.0.1 fails

### ISSUE THREAD

**Issue by yorickdowne** [ethereum-optimism/optimism#2351]
**Describe the bug**

replica-healthcheck 1.0.1 started from official docker image fails with

```
replica-healthcheck_1   | npm ERR! A complete log of this run can be found in:
replica-healthcheck_1   | npm ERR!     /root/.npm/_logs/2022-03-22T14_08_43_686Z-debug.log
replica-healthcheck_1   | npm ERR! code ENOENT
replica-healthcheck_1   | npm ERR! syscall open
replica-healthcheck_1   | npm ERR! path /opts/optimism/packages/replica-healthcheck/package.json
replica-healthcheck_1   | npm ERR! errno -2
replica-healthcheck_1   | npm ERR! enoent ENOENT: no such file or directory, open '/opts/optimism/packages/replica-healthcheck/package.json'
replica-healthcheck_1   | npm ERR! enoent This is related to npm not being able to find a file.
replica-healthcheck_1   | npm ERR! enoent
```

**Expected behavior**

Can an enhancement request be added? replica-healthcheck docker images have been unhealthy for a while. How about adding CI/CD that specifically tests the docker build pipeline for it?

**Comment by smartcontracts** [comment]
cc @mslipper, I agree that the replica-healthcheck packages need to be included as part of CI or we're going to continue to have these issues

**Comment by smartcontracts** [comment]
Ok I'm working on a quick fix to get this added to CI to avoid issues like this in the future.

**Comment by smartcontracts** [comment]
Alright @yorickdowne thanks again for the report here. I've updated #2352 to include a basic integration test that will, at the very least, confirm that future changes do not result in issues like this where service doesn't start correctly.

**Comment by smartcontracts** [comment]
Sorry about that, and thanks again for the report here. Now that the healthcheck is included as part of the integration tests, stuff like this shouldn't happen again in the future. :pray:
