### ISSUE TITLE
Delete update code from Lib_MerkleTrie

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimism#2377]
**Description**

Since removing the OVM, we no longer use the `update()` functionality in `Lib_SecureMerkleTrie` (for reference the call [occurred here](https://github.com/ethereum-optimism/optimism/blob/86a13dcb0cfc2050317797d031917a2585ce2a49/packages/contracts/contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitioner.sol#L439)). 

We shouldn't have unused code lying around, so we should remove `Lib_SecureMerkleTrie.update()`, and any code which was used only by it.

**ToDo**

1. Delete [the `update()` function](https://github.com/ethereum-optimism/optimism/blob/3dee2651d720f492eb4b5d7fcebf2cd29f485afc/packages/contracts/contracts/libraries/trie/Lib_SecureMerkleTrie.sol#L48) in the secure trie lib.

2. Delete [the `update()` function](https://github.com/ethereum-optimism/optimism/blob/3dee2651d720f492eb4b5d7fcebf2cd29f485afc/packages/contracts/contracts/libraries/trie/Lib_MerkleTrie.sol#L92) in the regular trie lib. 

3. Delete any other `internal` helper functions which were only used in `update()` and so are no longer used. (Keep deleting code until the compiler complains about it).

4. Delete any tests that tested the deleted code.

**Comment by sam0110** [comment]
I'll take this!

**Comment by Michael-Vander-Meiden** [comment]
Hey, sam0110! I am currently working on this just FYI but a little bit of redundancy isn't a bad thing. :)
