### ISSUE TITLE
Last deploy task fails on Hardhat

### ISSUE THREAD

**Issue by jannikluhn** [ethereum-optimism/optimism#2419]
**Describe the bug**
The last deploy task, `016-fund-accounts.ts`, fails due to missing funds on Hardhat:

```
Error HH604: Error running JSON-RPC server: ERROR processing .../packages/contracts/deploy/016-fund-accounts.ts:
InvalidInputError: sender doesn't have enough funds to send tx. The max upfront cost is: 5306998372000000 and the sender's account only has: 0
```

**To Reproduce**
1. create a hardhat deploy config (I just copied `local.ts` to `hardhat.ts` and renamed the network to `hardhat`)
2. run `npx hardhat node`

**Expected behavior**
The command should succeed.

**System Specs:**
 - OS: Linux
 - Package Version (or commit hash): b4756bcba6b28e9901ff8bbe0717b659f2183ae5 (develop)

**Additional context**

The problem seems to be that there's a mismatch between the [accounts defined in hardhat config file](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/hardhat.config.ts#L31) and the [accounts doing the  funding](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/deploy/016-fund-accounts.ts#L4). The former is ultimately [imported from waffle](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/test/helpers/constants.ts#L2), the latter [from a hardhat-internal variable](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/deploy/016-fund-accounts.ts#L4).

Hardhat accounts:

```
[
  {
    balance: '10000000000000000000000000000000000',
    privateKey: '0x29f3edee0ad3abf8e2699402e0e28cd6492c9be7eaab00d732a791c33552f797'
  },
  {
    balance: '10000000000000000000000000000000000',
    privateKey: '0x5c8b9227cd5065c7e3f6b73826b8b42e198c4497f6688e3085d5ab3a6d520e74'
  },
  {
    balance: '10000000000000000000000000000000000',
    privateKey: '0x50c8b3fc81e908501c8cd0a60911633acaca1a567d1be8e769c5ae7007b34b23'
  },
...
```

Funding accounts:
```
{
  initialIndex: 0,
  count: 20,
  path: "m/44'/60'/0'/0",
  passphrase: '',
  mnemonic: 'test test test test test test test test test test test junk',
  accountsBalance: '10000000000000000000000'
}
[
  {
    privateKey: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80',
    balance: '10000000000000000000000'
  },
  {
    privateKey: '0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d',
    balance: '10000000000000000000000'
  },
  {
    privateKey: '0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a',
    balance: '10000000000000000000000'
  },
...
```

**Comment by smartcontracts** [comment]
Good catch! Thank you. Let me see if I can put together a quick fix.
