### ISSUE TITLE
public rpc node cannot get the latest block

### ISSUE THREAD

**Issue by masayil** [ethereum-optimism/optimism#2483]
`curl -X POST -H 'content-type:application/json' -d '{"jsonrpc": "2.0","method": "eth_blockNumber","params":[],"id": 1}' https://mainnet.optimism.io`
`{"jsonrpc":"2.0","result":"0x5c4e8e","id":1}`

10:30 4/20 2022 UTC+8

**Comment by mslipper** [comment]
We're aware of this issue. Please see https://status.optimism.io for updates.
