### ISSUE TITLE
wrong provider inside check-block-hashes integration test

### ISSUE THREAD

**Issue by lucadonnoh** [ethereum-optimism/optimism#2532]
https://github.com/ethereum-optimism/optimism/blob/84e4e2c64892b61a7369288bc18a51a3950694d5/integration-tests/tasks/check-block-hashes.ts#L25

i'm not sure but i think this line should be `netB = await providerB.getNetwork() `

**Comment by smartcontracts** [comment]
Lol, nice catch. Could "fix" via this issue: https://github.com/ethereum-optimism/optimism/issues/2520

**Comment by smartcontracts** [comment]
Fixed by #2535
