### ISSUE TITLE
Error when building local optimistic ethereum

### ISSUE THREAD

**Issue by fainashalts** [ethereum-optimism/optimism#2538]
Hi there, I have encountered an issue when trying to run the local optimistic ethereum setup for testing. Please let me know if I am missing something. Thanks! 

**Describe the bug**
When following the steps here: https://community.optimism.io/docs/developers/build/dev-node/#

I encounter errors, whether using docker hub or not. 

**To Reproduce**
1. In a clean directory, run `git clone https://github.com/ethereum-optimism/optimism.git`
2. `cd optimism/ops`
3. `docker-compose -f docker-compose-nobuild.yml up -t 600 --no-start`

**Expected behavior**
Local Optimistic Ethereum is ready for use

** Actual Behavior **
`ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-nobuild.yml'`

**System Specs:**
 - OS: M1 Mac, Monterey

**Additional context**
If following the alternative set of steps in the documentation, to build from source, an error is also encountered, though different:
`ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose.ts-batch-submitter.yml'`

**Comment by smartcontracts** [comment]
We removed the `docker-compose-nobuild.yml` file. You may need to clear your cache to see the latest version of the docs (shift + refresh). You should just be able to use `docker-compose up` without any extra parameters.

**Comment by fainashalts** [comment]
Thanks @smartcontracts, `docker-compose up` does work just fine! It was a caching issue for me. Closing this issue as there is nothing else needed here. Thank you!
