### ISSUE TITLE
Nonce is required in TransactionRequest parameter object in estimateL1Gas & estimateL1GasCost

### ISSUE THREAD

**Issue by Sednaoui** [ethereum-optimism/optimism#2555]
**Describe the bug**
In the sdk `estimateL1Gas` and `estimateL1GasCost`, the nonce is converted to a number using toNumber without checking if it is defined. 

see [estimateL1Gas](https://github.com/ethereum-optimism/optimism/blob/7b89c07212f906b210c52ecda97534e5ad968b46/packages/sdk/src/l2-provider.ts#L60) and [estimateL1GasCost](https://github.com/ethereum-optimism/optimism/blob/7b89c07212f906b210c52ecda97534e5ad968b46/packages/sdk/src/l2-provider.ts#L84)

**To Reproduce**
1. Go to the sdk
2. call estimateL1Gas or estimateL1GasCost with a TransactionRequest object with nonce undefined
3. See error

**Expected behavior**
If I am not mistaken, functions should estimate gas without requiring nonce since the nonce is automatically populated with etherjs

**System Specs:**
 - Package Version (or commit hash): 1.1.4

**Additional context**
can take care of opening a PR

**Comment by smartcontracts** [comment]
Good catch! Will make a PR to fix this soon.
