### ISSUE TITLE
data-transport-layer Caught an unhandled error

### ISSUE THREAD

**Issue by imtipi** [ethereum-optimism/optimism#2573]
**Describe the bug**
l2geth log
INFO [05-17|15:43:35.354] Loaded most recent local header          number=0 hash=7ca38a…3fa48b td=1 age=53y1mo2w
INFO [05-17|15:43:35.354] Loaded most recent local full block      number=0 hash=7ca38a…3fa48b td=1 age=53y1mo2w
INFO [05-17|15:43:35.354] Loaded most recent local fast block      number=0 hash=7ca38a…3fa48b td=1 age=53y1mo2w
INFO [05-17|15:43:35.357] Loaded local transaction journal         transactions=0 dropped=0
INFO [05-17|15:43:35.357] Regenerated local transaction journal    transactions=0 accounts=0
INFO [05-17|15:43:35.364] Running in verifier mode                 sync-backend=l2
INFO [05-17|15:43:35.365] Configured rollup client                 url=http://data-transport-layer:7878 chain-id=10 ctc-deploy-height=13596466
INFO [05-17|15:43:35.370] Cannot connect to upstream service       msg="Cannot connect to data service: Cannot fetch eth context: Get \"http://data-transport-layer:7878/eth/context/latest\": dial tcp 192.168.48.4:7878: connect: connection refused"
INFO [05-17|15:43:45.939] Connected to upstream service 
ERROR[05-17|15:43:45.961] Cannot get sync status 
ERROR[05-17|15:43:55.947] Cannot get sync status 
ERROR[05-17|15:44:05.961] Cannot get sync status 
ERROR[05-17|15:44:15.944] Cannot get sync status 
ERROR[05-17|15:44:25.942] Cannot get sync status 
ERROR[05-17|15:44:35.944] Cannot get sync status 
ERROR[05-17|15:44:45.942] Cannot get sync status 
ERROR[05-17|15:44:55.943] Cannot get sync status 

at the same time,data-transport-layer log:
{"level":30,"time":1652802216443,"msg":"Service is starting..."}
{"level":30,"time":1652802216444,"msg":"Service is initializing..."}
{"level":30,"time":1652802216445,"msg":"Initializing L1 Data Transport Service..."}
{"level":30,"time":1652802216744,"msg":"L2 chain ID is: 10"}
{"level":30,"time":1652802216744,"msg":"BSS HF1 will activate at: 2824317"}
{"level":30,"time":1652802216753,"msg":"Service is initializing..."}
{"level":30,"time":1652802216765,"defaultBackend":"l2","l1GasPriceBackend":"l2","msg":"HTTP Server Options"}
{"level":30,"time":1652802216767,"url":"https://eth-mainnet.alchemyapi.io/v2/redacted","msg":"HTTP Server L1 RPC Provider initialized"}
{"level":30,"time":1652802216767,"url":"https://opt-mainnet.g.alchemy.com/v2/redacted","msg":"HTTP Server L2 RPC Provider initialized"}
{"level":30,"time":1652802216767,"msg":"Service has initialized."}
{"level":30,"time":1652802216767,"msg":"Service is initializing..."}
{"level":30,"time":1652802216768,"msg":"Service has initialized."}
{"level":30,"time":1652802216768,"msg":"Service has initialized."}
{"level":30,"time":1652802216772,"msg":"Service is starting..."}
{"level":30,"time":1652802216772,"msg":"Service is starting..."}
{"level":30,"time":1652802216778,"host":"0.0.0.0","port":7878,"msg":"Server started and listening"}
{"level":30,"time":1652802216782,"msg":"Service has started"}
{"level":30,"time":1652802217049,"fromBlock":1,"toBlock":1001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
{"level":50,"time":1652802217153,"extra":{"message":"Error: Request failed with status code 400","stack":"Error: Request failed with status code 400\n    at createError (/opt/optimism/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/opt/optimism/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/opt/optimism/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (node:events:527:28)\n    at RedirectableRequest.emit (node:domain:475:12)\n    at RedirectableRequest._processResponse (/opt/optimism/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/opt/optimism/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n    at ClientRequest.emit (node:domain:475:12)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1652802217755,"fromBlock":1,"toBlock":1001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
{"level":50,"time":1652802217857,"extra":{"message":"Error: Request failed with status code 400","stack":"Error: Request failed with status code 400\n    at createError (/opt/optimism/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/opt/optimism/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/opt/optimism/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (node:events:527:28)\n    at RedirectableRequest.emit (node:domain:475:12)\n    at RedirectableRequest._processResponse (/opt/optimism/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/opt/optimism/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n    at ClientRequest.emit (node:domain:475:12)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1652802218488,"fromBlock":1,"toBlock":1001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
{"level":50,"time":1652802218592,"extra":{"message":"Error: Request failed with status code 400","stack":"Error: Request failed with status code 400\n    at createError (/opt/optimism/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/opt/optimism/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/opt/optimism/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (node:events:527:28)\n    at RedirectableRequest.emit (node:domain:475:12)\n    at RedirectableRequest._processResponse (/opt/optimism/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/opt/optimism/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n    at ClientRequest.emit (node:domain:475:12)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1652802219231,"fromBlock":1,"toBlock":1001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
{"level":50,"time":1652802219431,"extra":{"message":"Error: Request failed with status code 400","stack":"Error: Request failed with status code 400\n    at createError (/opt/optimism/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/opt/optimism/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/opt/optimism/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (node:events:527:28)\n    at RedirectableRequest.emit (node:domain:475:12)\n    at RedirectableRequest._processResponse (/opt/optimism/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/opt/optimism/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n    at ClientRequest.emit (node:domain:475:12)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1652802220041,"fromBlock":1,"toBlock":1001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
{"level":50,"time":1652802220134,"extra":{"message":"Error: Request failed with status code 400","stack":"Error: Request failed with status code 400\n    at createError (/opt/optimism/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/opt/optimism/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/opt/optimism/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (node:events:527:28)\n    at RedirectableRequest.emit (node:domain:475:12)\n    at RedirectableRequest._processResponse (/opt/optimism/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/opt/optimism/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n    at ClientRequest.emit (node:domain:475:12)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1652802220726,"fromBlock":1,"toBlock":1001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
{"level":50,"time":1652802220821,"extra":{"message":"Error: Request failed with status code 400","stack":"Error: Request failed with status code 400\n    at createError (/opt/optimism/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/opt/optimism/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/opt/optimism/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (node:events:527:28)\n    at RedirectableRequest.emit (node:domain:475:12)\n    at RedirectableRequest._processResponse (/opt/optimism/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/opt/optimism/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n    at ClientRequest.emit (node:domain:475:12)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1652802221449,"fromBlock":1,"toBlock":1001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
{"level":50,"time":1652802221530,"extra":{"message":"Error: Request failed with status code 400","stack":"Error: Request failed with status code 400\n    at createError (/opt/optimism/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/opt/optimism/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/opt/optimism/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (node:events:527:28)\n    at RedirectableRequest.emit (node:domain:475:12)\n    at RedirectableRequest._processResponse (/opt/optimism/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/opt/optimism/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n    at ClientRequest.emit (node:domain:475:12)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1652802222141,"fromBlock":1,"toBlock":1001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
{"level":50,"time":1652802222300,"extra":{"message":"Error: Request failed with status code 400","stack":"Error: Request failed with status code 400\n    at createError (/opt/optimism/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/opt/optimism/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/opt/optimism/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (node:events:527:28)\n    at RedirectableRequest.emit (node:domain:475:12)\n    at RedirectableRequest._processResponse (/opt/optimism/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/opt/optimism/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n    at ClientRequest.emit (node:domain:475:12)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1652802222924,"fromBlock":1,"toBlock":1001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
{"level":50,"time":1652802223021,"extra":{"message":"Error: Request failed with status code 400","stack":"Error: Request failed with status code 400\n    at createError (/opt/optimism/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/opt/optimism/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/opt/optimism/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (node:events:527:28)\n    at RedirectableRequest.emit (node:domain:475:12)\n    at RedirectableRequest._processResponse (/opt/optimism/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/opt/optimism/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n    at ClientRequest.emit (node:domain:475:12)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1652802223612,"fromBlock":1,"toBlock":1001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}

**To Reproduce**
use this .env file

COMPOSE_PROJECT_NAME=op-replica
COMPOSE_FILE=replica.yml:replica-shared.yml:replica-toml.yml
ETH_NETWORK=mainnet
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=https://eth-mainnet.alchemyapi.io/v2/redacted
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://opt-mainnet.g.alchemy.com/v2/redacted
REPLICA_HEALTHCHECK__ETH_NETWORK_RPC_PROVIDER=https://opt-mainnet.g.alchemy.com/v2/redacted
SEQUENCER_CLIENT_HTTP=https://opt-mainnet.g.alchemy.com/v2/redacted
SHARED_ENV_PATH=../envs/mainnet
GCMODE=full
L2GETH_IMAGE_TAG=latest
DTL_IMAGE_TAG=latest
HC_IMAGE_TAG=latest
L2GETH_HTTP_PORT=9991
L2GETH_WS_PORT=9992
DTL_PORT=7878
GETH_INIT_SCRIPT=check-for-chaindata-berlin.sh
USING_OVM=true
RESTART=unless-stopped

then docker compose up -d

**Expected behavior**
it should start sync blocks(just like three day ago)

**Screenshots**
no

**System Specs:**
 - OS:debian10 with docker 20.10.16(go version: go1.17.10)
 - Package Version (or commit hash):latest

**Additional context**
if i use blockvision or mainnet.optimism.io as rpc ,it works, but if i use alchemy it just stop working,and it was working 36 hours ago.

**Comment by imtipi** [comment]
update #1: when i change DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT to blockvision,it works,no matter what L2 rpc it use.maybe it is L1 rpc issue

**Comment by 108356037** [comment]
This issue is related to alchemy, they don't support eth_getBlockRange method.
[
![Screen Shot 2022-06-23 at 4 07 09 PM](https://user-images.githubusercontent.com/65017949/175249248-be91ae4d-14f2-4189-8313-637b1d652543.png)
](url)
