### ISSUE TITLE
Problem synching op-replica 

### ISSUE THREAD

**Issue by yunfangjuan** [ethereum-optimism/optimism#2590]
**Describe the bug**
I am trying to run a mainnet optimism replica locally. But it failed with some verification error 

**To Reproduce**
Here is what I did: 
1.  `mv default-mainnet.env .env`
2.  edit my .env file to 

COMPOSE_PROJECT_NAME=op-replica
COMPOSE_FILE=replica.yml:replica-shared.yml:replica-toml.yml
ETH_NETWORK=mainnet
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=<my_alchemy_ethereum_mainnet_endpoint>
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://mainnet.optimism.io
REPLICA_HEALTHCHECK__ETH_NETWORK_RPC_PROVIDER=https://mainnet.optimism.io
SEQUENCER_CLIENT_HTTP=https://mainnet.optimism.io
SHARED_ENV_PATH=../envs/mainnet
GCMODE=full
L2GETH_IMAGE_TAG=0.5.12
DTL_IMAGE_TAG=0.5.20
HC_IMAGE_TAG=latest
L2GETH_HTTP_PORT=9991
L2GETH_WS_PORT=9992
DTL_PORT=7878
GETH_INIT_SCRIPT=check-for-chaindata-berlin.sh
RESTART=unless-stopped

3. start my script `docker-compose up -d`

It was synching fine. Until I got the following errors: 

op-replica-l2geth-replica-1  | DEBUG[05-18|23:35:34.550] Transaction failed, account skipped      hash=e04155…859fb0 err="insufficient balance for transfer"
op-replica-l2geth-replica-1  | ERROR[05-18|23:35:34.550] Problem committing transaction           msg="insufficient balance for transfer"
op-replica-l2geth-replica-1  | ERROR[05-18|23:35:34.550] Got error waiting for transaction to be added to chain msg="insufficient balance for transfer"
op-replica-l2geth-replica-1  | ERROR[05-18|23:35:34.550] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: insufficient balance for transfer"
op-replica-l2geth-replica-1  | INFO [05-18|23:35:35.548] Syncing transaction range                start=6530034 end=8561969 backend=l2
op-replica-l2geth-replica-1  | DEBUG[05-18|23:35:35.550] Applying transaction to tip              index=6530034 hash=0xe041555381044008873ad8ee2c28c2424e245fe6f1373b3b45af970786859fb0 origin=sequencer
op-replica-l2geth-replica-1  | DEBUG[05-18|23:35:35.550] Attempting to commit rollup transaction  hash=0xe041555381044008873ad8ee2c28c2424e245fe6f1373b3b45af970786859fb0
op-replica-l2geth-replica-1  | DEBUG[05-18|23:35:35.550] Transaction failed, account skipped      hash=e04155…859fb0 err="insufficient balance for transfer"
op-replica-l2geth-replica-1  | ERROR[05-18|23:35:35.550] Problem committing transaction           msg="insufficient balance for transfer"
op-replica-l2geth-replica-1  | ERROR[05-18|23:35:35.550] Got error waiting for transaction to be added to chain msg="insufficient balance for transfer"
op-replica-l2geth-replica-1  | ERROR[05-18|23:35:35.550] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: insufficient balance for transfer"
^Ccanceled

Please advise.

**Comment by yunfangjuan** [comment]
I upgraded  DTL to 0.5.30 and l2geth to 0.5.19 and was able to synch thru the 6530034  block

**Comment by smartcontracts** [comment]
@yunfangjuan if you were able to sync past the target block, can I close this issue?

**Comment by yunfangjuan** [comment]
Yes. go ahead

**Comment by wangtao19911111** [comment]
do this need to sync from 0？

**Comment by Tab-ops** [comment]
I also encountered this problem. Do I need to change the version and then resynchronize? @yunfangjuan

**Comment by smartcontracts** [comment]
@Tab-ops yes you will need to resynchronize with the lastest version

**Comment by Tab-ops** [comment]
@smartcontracts Is it like this？
L2GETH_IMAGE_TAG=latest
DTL_IMAGE_TAG=latest
HC_IMAGE_TAG=latest
