### ISSUE TITLE
Why can't all faucets get test coins?

### ISSUE THREAD

**Issue by coder-chenda** [ethereum-optimism/optimism#2630]
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/83049018/171137110-85497979-83d2-4174-8bd0-8d9ee26cd828.png">

**Comment by smartcontracts** [comment]
The Paradigm faucet does somewhat strict checks to prevent bots from draining the faucet. Do you have an older Twitter account that you can connect to the faucet instead?
