### ISSUE TITLE
yarn start

### ISSUE THREAD

**Issue by KevinTMitnick** [ethereum-optimism/optimism#2641]
{"level":50,"time":1654079102977,"extra":{"message":"Error: Request failed with status code 400","stack":"Error: Request failed with status code 400\n    at createError (/data/op/optimism/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/data/op/optimism/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/data/op/optimism/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (node:events:527:28)\n    at RedirectableRequest.emit (node:domain:475:12)\n    at RedirectableRequest._processResponse (/data/op/optimism/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/data/op/optimism/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n    at ClientRequest.emit (node:domain:475:12)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1654079108689,"fromBlock":1,"toBlock":1001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
{"level":50,"time":1654079109306,"extra":{"message":"Error: Request failed with status code 400","stack":"Error: Request failed with status code 400\n    at createError (/data/op/optimism/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/data/op/optimism/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/data/op/optimism/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (node:events:527:28)\n    at RedirectableRequest.emit (node:domain:475:12)\n    at RedirectableRequest._processResponse (/data/op/optimism/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/data/op/optimism/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n    at ClientRequest.emit (node:domain:475:12)"},"msg":"Caught an unhandled error"}

**Comment by norswap** [comment]
Not a proper issue, just some random logs. Might be related to the high load experienced yesterday during the airdrop.
