### ISSUE TITLE
I run a node but it returns a request limit error

### ISSUE THREAD

**Issue by vae520283995** [ethereum-optimism/optimism#2642]
```
"error": {
  "code": -32000,
  "message": "This request has been rate limited."
 }
```

**Comment by vae520283995** [comment]
@smartcontracts please help

**Comment by norswap** [comment]
You're sending too many RPC requests to the endpoint. Alternatively, there's a small chance it was due to the high network load yesterday. Try again, and make sure you're not sending a lot of requests.

**Comment by vae520283995** [comment]
> You're sending too many RPC requests to the endpoint. Alternatively, there's a small chance it was due to the high network load yesterday. Try again, and make sure you're not sending a lot of requests.

I ran node according to this documentation
https://github.com/ethereum-optimism/optimism/tree/develop/infra/op-replica/docker-compose#running-a-network-node
Optimism is listed on our exchange, but sending rpc requests to nodes returns too many request limit errors
```
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://mainnet.optimism.io
REPLICA_HEALTHCHECK__ETH_NETWORK_RPC_PROVIDER=https://mainnet.optimism.io
SEQUENCER_CLIENT_HTTP=https://mainnet.optimism.io
```
Is it because of these 3 configurations?Can I run this service myself?
