### ISSUE TITLE
I started a node but it doesn't sync data

### ISSUE THREAD

**Issue by blocknodehub** [ethereum-optimism/optimism#2643]
docker run -itd -p 8545:8545 -p 8546:8546 -p 30303:30303 -e DATA_TRANSPORT_LAYER__NODE_ENV=production -e DATA_TRANSPORT_LAYER__ETH_NETWORK_NAME=mainnet -e DATA_TRANSPORT_LAYER__ADDRESS_MANAGER=0xdE1FCfB0851916CA5101820A69b13a4E276bd81F -e DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true -e DATA_TRANSPORT_LAYER__SYNC_FROM_L2=false -e DATA_TRANSPORT_LAYER__L2_CHAIN_ID=10 -e ETH_NETWORK=mainnet -e DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=http://eth-0.eth.blocknodehub.com:8545 -e DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://mainnet.optimism.io ethereumoptimism/l2geth:0.5.19 --nousb --verbosity=4 --maxpeers=5000
<img width="1312" alt="截屏2022-06-01 19 43 53" src="https://user-images.githubusercontent.com/100512407/171397152-c0d8cbc0-5575-4a4c-8552-c593bd3fb78b.png">

**Comment by norswap** [comment]
Which instructions are you following? Afaik the canonical instructions are here and not involve docker: https://community.optimism.io/docs/developers/build/run-a-node/#

**Comment by smartcontracts** [comment]
Please try following the instructions here: https://community.optimism.io/docs/developers/build/run-a-node/#
