### ISSUE TITLE
sync from l1 failed

### ISSUE THREAD

**Issue by pagefault0** [ethereum-optimism/optimism#2686]
**logs of syncing**
TRACE[06-05|16:12:33.107] Applying batched transaction             index=6530033
TRACE[06-05|16:12:33.107] Applying indexed transaction             index=6530033
DEBUG[06-05|16:12:33.107] Historical transaction matches           index=6530033  hash=0x3ded5e2a61614df4e2573ff08f51ea257010aecc87f4b9dc8849d61bf061135a
TRACE[06-05|16:12:33.107] Applying batched transaction             index=6530034
TRACE[06-05|16:12:33.107] Applying indexed transaction             index=6530034
DEBUG[06-05|16:12:33.107] Applying transaction to tip              index=6530034  hash=0xe041555381044008873ad8ee2c28c2424e245fe6f1373b3b45af970786859fb0 origin=sequencer
TRACE[06-05|16:12:33.107] Waiting for transaction to be added to chain hash=0xe041555381044008873ad8ee2c28c2424e245fe6f1373b3b45af970786859fb0
DEBUG[06-05|16:12:33.107] Attempting to commit rollup transaction  hash=0xe041555381044008873ad8ee2c28c2424e245fe6f1373b3b45af970786859fb0
DEBUG[06-05|16:12:33.108] Adding L1 fee                            l1-fee=301015397889740
DEBUG[06-05|16:12:33.108] VM returned with error                   err="insufficient balance for transfer"    ret=0x
DEBUG[06-05|16:12:33.108] Transaction failed, account skipped      hash=e04155…859fb0 err="insufficient balance for transfer"
ERROR[06-05|16:12:33.108] Problem committing transaction           msg="insufficient balance for transfer"
ERROR[06-05|16:12:33.108] Got error waiting for transaction to be added to chain msg="insufficient balance for transfer"
ERROR[06-05|16:12:33.108] Could not verify                         error="Verifier cannot sync transaction batches to tip: Cannot sync transaction batches to tip: Cannot sync batches: cannot apply batched transaction: Cannot apply batched transaction: insufficient balance for transfer"

**l2geth-replica.env**
#more envs/mainnet/l2geth-replica.env
CHAIN_ID=10
DATADIR=/geth
NETWORK_ID=10
NO_DISCOVER=true
NO_USB=true
GASPRICE=0
GCMODE=archive
BLOCK_SIGNER_ADDRESS=0x00000398232E2064F896018496b4b44b3D62751F
BLOCK_SIGNER_PRIVATE_KEY=6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27
BLOCK_SIGNER_PRIVATE_KEY_PASSWORD=pwd
ETH1_CTC_DEPLOYMENT_HEIGHT=13596466
ETH1_L1_FEE_WALLET_ADDRESS=0x391716d440c151c42cdf1c95c1d83a5427bca52c
ETH1_L1_CROSS_DOMAIN_MESSENGER_ADDRESS=0x25ace71c97B33Cc4729CF772ae268934F7ab5fA1
ETH1_L1_STANDARD_BRIDGE_ADDRESS=0x99C9fc46f92E8a1c0deC1b1747d010903E884bE1
ETH1_SYNC_SERVICE_ENABLE=true
L2GETH_GENESIS_URL=https://storage.googleapis.com/optimism/mainnet/genesis-berlin.json
L2GETH_GENESIS_HASH=0x106b0a3247ca54714381b1109e82cc6b7e32fd79ae56fbcc2e7b1541122f84ea
#L2GETH_GENESIS_HASH=0x361ff81fff4cc71e5f0bf43b0b982f5cfd08d068f730b9a61516fe1fa8fd914a
L2GETH_BERLIN_ACTIVATION_HEIGHT=3950000
ROLLUP_ADDRESS_MANAGER_OWNER_ADDRESS=0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A
ROLLUP_BACKEND=l1
ROLLUP_CLIENT_HTTP=http://data-transport-layer:7878
ROLLUP_DISABLE_TRANSFERS=false
ROLLUP_ENABLE_L2_GAS_POLLING=false
ROLLUP_GAS_PRICE_ORACLE_OWNER_ADDRESS=0x648E3e8101BFaB7bf5997Bd007Fb473786019159
ROLLUP_MAX_CALLDATA_SIZE=40000
ROLLUP_POLL_INTERVAL_FLAG=1s
ROLLUP_SYNC_SERVICE_ENABLE=true
ROLLUP_TIMESTAMP_REFRESH=5m
ROLLUP_VERIFIER_ENABLE=true
RPC_ADDR=0.0.0.0
RPC_API=eth,rollup,net,web3,debug
RPC_CORS_DOMAIN=*
RPC_ENABLE=true
RPC_PORT=8545
RPC_VHOSTS=*
TARGET_GAS_LIMIT=15000000
USING_OVM=true
WS_ADDR=0.0.0.0
WS_API=eth,rollup,net,web3,debug
WS_ORIGINS=*
WS=true

**System Specs:**
 - OS:
 - Package Version (or commit hash):
L2GETH_IMAGE_TAG=0.5.12
DTL_IMAGE_TAG=0.5.20

**Additional context**

**Comment by smartcontracts** [comment]
You will need to use L2Geth >= 0.5.14

**Comment by malingzhao** [comment]
> **logs of syncing** TRACE[06-05|16:12:33.107] Applying batched transaction index=6530033 TRACE[06-05|16:12:33.107] Applying indexed transaction index=6530033 DEBUG[06-05|16:12:33.107] Historical transaction matches index=6530033 hash=0x3ded5e2a61614df4e2573ff08f51ea257010aecc87f4b9dc8849d61bf061135a TRACE[06-05|16:12:33.107] Applying batched transaction index=6530034 TRACE[06-05|16:12:33.107] Applying indexed transaction index=6530034 DEBUG[06-05|16:12:33.107] Applying transaction to tip index=6530034 hash=0xe041555381044008873ad8ee2c28c2424e245fe6f1373b3b45af970786859fb0 origin=sequencer TRACE[06-05|16:12:33.107] Waiting for transaction to be added to chain hash=0xe041555381044008873ad8ee2c28c2424e245fe6f1373b3b45af970786859fb0 DEBUG[06-05|16:12:33.107] Attempting to commit rollup transaction hash=0xe041555381044008873ad8ee2c28c2424e245fe6f1373b3b45af970786859fb0 DEBUG[06-05|16:12:33.108] Adding L1 fee l1-fee=301015397889740 DEBUG[06-05|16:12:33.108] VM returned with error err="insufficient balance for transfer" ret=0x DEBUG[06-05|16:12:33.108] Transaction failed, account skipped hash=e04155…859fb0 err="insufficient balance for transfer" ERROR[06-05|16:12:33.108] Problem committing transaction msg="insufficient balance for transfer" ERROR[06-05|16:12:33.108] Got error waiting for transaction to be added to chain msg="insufficient balance for transfer" ERROR[06-05|16:12:33.108] Could not verify error="Verifier cannot sync transaction batches to tip: Cannot sync transaction batches to tip: Cannot sync batches: cannot apply batched transaction: Cannot apply batched transaction: insufficient balance for transfer"
> 
> **l2geth-replica.env** #more envs/mainnet/l2geth-replica.env CHAIN_ID=10 DATADIR=/geth NETWORK_ID=10 NO_DISCOVER=true NO_USB=true GASPRICE=0 GCMODE=archive BLOCK_SIGNER_ADDRESS=0x00000398232E2064F896018496b4b44b3D62751F BLOCK_SIGNER_PRIVATE_KEY=6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27 BLOCK_SIGNER_PRIVATE_KEY_PASSWORD=pwd ETH1_CTC_DEPLOYMENT_HEIGHT=13596466 ETH1_L1_FEE_WALLET_ADDRESS=0x391716d440c151c42cdf1c95c1d83a5427bca52c ETH1_L1_CROSS_DOMAIN_MESSENGER_ADDRESS=0x25ace71c97B33Cc4729CF772ae268934F7ab5fA1 ETH1_L1_STANDARD_BRIDGE_ADDRESS=0x99C9fc46f92E8a1c0deC1b1747d010903E884bE1 ETH1_SYNC_SERVICE_ENABLE=true L2GETH_GENESIS_URL=https://storage.googleapis.com/optimism/mainnet/genesis-berlin.json L2GETH_GENESIS_HASH=0x106b0a3247ca54714381b1109e82cc6b7e32fd79ae56fbcc2e7b1541122f84ea #L2GETH_GENESIS_HASH=0x361ff81fff4cc71e5f0bf43b0b982f5cfd08d068f730b9a61516fe1fa8fd914a L2GETH_BERLIN_ACTIVATION_HEIGHT=3950000 ROLLUP_ADDRESS_MANAGER_OWNER_ADDRESS=0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A ROLLUP_BACKEND=l1 ROLLUP_CLIENT_HTTP=http://data-transport-layer:7878 ROLLUP_DISABLE_TRANSFERS=false ROLLUP_ENABLE_L2_GAS_POLLING=false ROLLUP_GAS_PRICE_ORACLE_OWNER_ADDRESS=0x648E3e8101BFaB7bf5997Bd007Fb473786019159 ROLLUP_MAX_CALLDATA_SIZE=40000 ROLLUP_POLL_INTERVAL_FLAG=1s ROLLUP_SYNC_SERVICE_ENABLE=true ROLLUP_TIMESTAMP_REFRESH=5m ROLLUP_VERIFIER_ENABLE=true RPC_ADDR=0.0.0.0 RPC_API=eth,rollup,net,web3,debug RPC_CORS_DOMAIN=* RPC_ENABLE=true RPC_PORT=8545 RPC_VHOSTS=* TARGET_GAS_LIMIT=15000000 USING_OVM=true WS_ADDR=0.0.0.0 WS_API=eth,rollup,net,web3,debug WS_ORIGINS=* WS=true
> 
> **System Specs:**
> 
> * OS:
> * Package Version (or commit hash):
>   L2GETH_IMAGE_TAG=0.5.12
>   DTL_IMAGE_TAG=0.5.20
> 
> **Additional context** Add any other context about the problem here.

Hi , can you give me your node install documentation

**Comment by pagefault0** [comment]
> > **logs of syncing** TRACE[06-05|16:12:33.107] Applying batched transaction index=6530033 TRACE[06-05|16:12:33.107] Applying indexed transaction index=6530033 DEBUG[06-05|16:12:33.107] Historical transaction matches index=6530033 hash=0x3ded5e2a61614df4e2573ff08f51ea257010aecc87f4b9dc8849d61bf061135a TRACE[06-05|16:12:33.107] Applying batched transaction index=6530034 TRACE[06-05|16:12:33.107] Applying indexed transaction index=6530034 DEBUG[06-05|16:12:33.107] Applying transaction to tip index=6530034 hash=0xe041555381044008873ad8ee2c28c2424e245fe6f1373b3b45af970786859fb0 origin=sequencer TRACE[06-05|16:12:33.107] Waiting for transaction to be added to chain hash=0xe041555381044008873ad8ee2c28c2424e245fe6f1373b3b45af970786859fb0 DEBUG[06-05|16:12:33.107] Attempting to commit rollup transaction hash=0xe041555381044008873ad8ee2c28c2424e245fe6f1373b3b45af970786859fb0 DEBUG[06-05|16:12:33.108] Adding L1 fee l1-fee=301015397889740 DEBUG[06-05|16:12:33.108] VM returned with error err="insufficient balance for transfer" ret=0x DEBUG[06-05|16:12:33.108] Transaction failed, account skipped hash=e04155…859fb0 err="insufficient balance for transfer" ERROR[06-05|16:12:33.108] Problem committing transaction msg="insufficient balance for transfer" ERROR[06-05|16:12:33.108] Got error waiting for transaction to be added to chain msg="insufficient balance for transfer" ERROR[06-05|16:12:33.108] Could not verify error="Verifier cannot sync transaction batches to tip: Cannot sync transaction batches to tip: Cannot sync batches: cannot apply batched transaction: Cannot apply batched transaction: insufficient balance for transfer"
> > **l2geth-replica.env** #more envs/mainnet/l2geth-replica.env CHAIN_ID=10 DATADIR=/geth NETWORK_ID=10 NO_DISCOVER=true NO_USB=true GASPRICE=0 GCMODE=archive BLOCK_SIGNER_ADDRESS=0x00000398232E2064F896018496b4b44b3D62751F BLOCK_SIGNER_PRIVATE_KEY=6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27 BLOCK_SIGNER_PRIVATE_KEY_PASSWORD=pwd ETH1_CTC_DEPLOYMENT_HEIGHT=13596466 ETH1_L1_FEE_WALLET_ADDRESS=0x391716d440c151c42cdf1c95c1d83a5427bca52c ETH1_L1_CROSS_DOMAIN_MESSENGER_ADDRESS=0x25ace71c97B33Cc4729CF772ae268934F7ab5fA1 ETH1_L1_STANDARD_BRIDGE_ADDRESS=0x99C9fc46f92E8a1c0deC1b1747d010903E884bE1 ETH1_SYNC_SERVICE_ENABLE=true L2GETH_GENESIS_URL=https://storage.googleapis.com/optimism/mainnet/genesis-berlin.json L2GETH_GENESIS_HASH=0x106b0a3247ca54714381b1109e82cc6b7e32fd79ae56fbcc2e7b1541122f84ea #L2GETH_GENESIS_HASH=0x361ff81fff4cc71e5f0bf43b0b982f5cfd08d068f730b9a61516fe1fa8fd914a L2GETH_BERLIN_ACTIVATION_HEIGHT=3950000 ROLLUP_ADDRESS_MANAGER_OWNER_ADDRESS=0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A ROLLUP_BACKEND=l1 ROLLUP_CLIENT_HTTP=http://data-transport-layer:7878 ROLLUP_DISABLE_TRANSFERS=false ROLLUP_ENABLE_L2_GAS_POLLING=false ROLLUP_GAS_PRICE_ORACLE_OWNER_ADDRESS=0x648E3e8101BFaB7bf5997Bd007Fb473786019159 ROLLUP_MAX_CALLDATA_SIZE=40000 ROLLUP_POLL_INTERVAL_FLAG=1s ROLLUP_SYNC_SERVICE_ENABLE=true ROLLUP_TIMESTAMP_REFRESH=5m ROLLUP_VERIFIER_ENABLE=true RPC_ADDR=0.0.0.0 RPC_API=eth,rollup,net,web3,debug RPC_CORS_DOMAIN=* RPC_ENABLE=true RPC_PORT=8545 RPC_VHOSTS=* TARGET_GAS_LIMIT=15000000 USING_OVM=true WS_ADDR=0.0.0.0 WS_API=eth,rollup,net,web3,debug WS_ORIGINS=* WS=true
> > **System Specs:**
> > 
> > * OS:
> > * Package Version (or commit hash):
> >   L2GETH_IMAGE_TAG=0.5.12
> >   DTL_IMAGE_TAG=0.5.20
> > 
> > **Additional context** Add any other context about the problem here.
> 
> Hi , can you give me your node install documentation

https://community.optimism.io/docs/developers/build/run-a-node/#

**Comment by smartcontracts** [comment]
You will need to upgrade to L2Geth >=0.5.14 and resync

**Comment by jquesnelle** [comment]
It might be useful to bump the default versions in `infra/op-replica/docker-compose` since just running `docker-compose up -d` according to the docs now will result in a starting a node that fails to sync
