### ISSUE TITLE
L2 geth waits for DTL to sync

### ISSUE THREAD

**Issue by malingzhao** [ethereum-optimism/optimism#2689]
![image](https://user-images.githubusercontent.com/50159440/172081894-ba0e6840-e84c-4717-925f-73ba7527d6d3.png)
I am using synchronous L1, but when it reaches a certain block height, it will not be synchronized down. I am using the master version, can you give me some advice?

**Comment by smartcontracts** [comment]
It's waiting for the DTL to sync. We're working on a change that will allow L2Geth to sync in parallel with the DTL: https://github.com/ethereum-optimism/optimism/pull/2656

**Comment by smartcontracts** [comment]
#2656 has been merged which should fix the issue. Pull latest images if you're running your nodes via docker.
