### ISSUE TITLE
build error while run command: yarn build

### ISSUE THREAD

**Issue by maldiohead** [ethereum-optimism/optimism#2713]
**Describe the bug**

when run the yarn build command, error occur:

**To Reproduce**
follow the steps in https://community.optimism.io/docs/developers/build/dev-node/#option-1-downloading-from-docker-hub-recommended
and when run the command yarn build, exception occur.

**Expected behavior**
_Error Log:_

yarn run v1.22.19
$ yarn lerna run build
$ /home/ccc/optimism/node_modules/.bin/lerna run build
lerna notice cli v4.0.0
lerna info versioning independent
lerna info Executing command in 11 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@eth-optimism/core-utils' in 3.6s:
$ tsc -p tsconfig.json
lerna ERR! yarn run build exited 1 in '@eth-optimism/contracts-bedrock'
lerna ERR! yarn run build stdout:
$ hardhat compile && tsc && hardhat typechain

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
Solidity 0.8.10 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/reference/solidity-support

An unexpected error occurred:
TypeError: Cannot read property 'code' of null
    at analyzeModuleNotFoundError (/home/ccc/optimism/node_modules/hardhat/src/internal/core/config/config-loading.ts:161:13)
    at Environment.run (/home/ccc/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:136:33)
    at async main (/home/ccc/optimism/node_modules/hardhat/src/internal/cli/cli.ts:218:5)
error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in '@eth-optimism/contracts-bedrock'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**System Specs:**
 - OS:Ubuntu x64 20.04 lts
 - Package Version (or commit hash): 
 master branch 
 06192c49e4093e90836fd10953669ec52c55e656

**Comment by norswap** [comment]
We had quite a few issues with the build in the last week, but things should now be fixed. Can you retry?

Also, I recommend first running `git clean -xdh` (preview) then `git clean -xdf` which will remove everything untracked by git including .gitignored files (make sure to commit beforehand!). Otherwise old outputs can cause problem with the new build.

If you're interested in running the develop environment (i.e. bedrock), building should be done using `yarn && make build`.

**Comment by maldiohead** [comment]
> We had quite a few issues with the build in the last week, but things should now be fixed. Can you retry?
> 
> Also, I recommend first running `git clean -xdh` (preview) then `git clean -xdf` which will remove everything untracked by git including .gitignored files (make sure to commit beforehand!). Otherwise old outputs can cause problem with the new build.
> 
> If you're interested in running the develop environment (i.e. bedrock), building should be done using `yarn && make build`.

thank you, it works~

**Comment by rlgns98kr** [comment]
Is it work now?
I faced the same issue.
But I already tried to running `git clean -xdf`, it doesn't work in the both `master` and `develop` branch

master commit hash: `85c1658313b8029f23584f8ab82fe19ea2cc05ad`
develop commit hash: `f99057e11290d7d327fb6cc6d9e2532a5f8561bf`

**Comment by rlgns98kr** [comment]
I installed [`forge`](https://github.com/foundry-rs/foundry). And it works.
Thank you.
