### ISSUE TITLE
Replica node HALTS without any error message

### ISSUE THREAD

**Issue by 0xsShady** [ethereum-optimism/optimism#2762]
Hi!

I don't know why my replica node halts after some hours running..if I restart manually the node (sudo docker-compose up -d
 + sudo docker-compose down) it works properly again.

Kind regards

**Comment by smartcontracts** [comment]
I believe this is an issue we fixed recently. Try pulling latest images.

```
docker-compose down
docker-compose pull
docker-compose up -d
```

**Comment by 0xsShady** [comment]
thank for the reply!
