### ISSUE TITLE
DepositFeed implementation link gives a 404

### ISSUE THREAD

**Issue by lucadonnoh** [ethereum-optimism/optimism#2820]
https://github.com/ethereum-optimism/optimism/blob/6b76465ee8dcd3d33b1840f188fb5f338285ea6a/specs/deposits.md?plain=1#L282

maybe it shoud link to [OptimismPortal.sol](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol)?

**Comment by lucadonnoh** [comment]
looks like also https://github.com/ethereum-optimism/optimism/blob/6b76465ee8dcd3d33b1840f188fb5f338285ea6a/specs/deposits.md?plain=1#L224
is broken and should point to [L1Block.sol](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/contracts/L2/L1Block.sol)

**Comment by smartcontracts** [comment]
Fixed now!
