### ISSUE TITLE
Custom reverts don't revert with a message

### ISSUE THREAD

**Issue by qbzzt** [ethereum-optimism/optimism#2821]
**Describe the bug**

Text reverts return with a message, but custom reverts return without one.

**To Reproduce**

1. [Go to this contract](https://kovan-optimistic.etherscan.io/address/0xbec72ee5e46b39831d077f41f99d39ca1fc1fa9a#writeContract).
2. Connect your wallet and execute **oldRevert** (or use the link below to see what happened when I ran it).
3. See that [the transaction is reverted with the correct result, `oldRevert`](https://kovan-optimistic.etherscan.io/tx/0xe75051aa110fb02307121dd23cd3447d40a08fb234c61d42d6b7e7f2322019fb).
    [Click here to see the transaction on tenderly](https://dashboard.tenderly.co/tx/optimistic-kovan/0xe75051aa110fb02307121dd23cd3447d40a08fb234c61d42d6b7e7f2322019fb).
4. Execute **newRevert** (or use the link below to see what happened when I ran it)
5. See that [the transaction is reverted without a result](https://kovan-optimistic.etherscan.io/tx/0x1f683b5bc56c6375de070f74df8287c931850f78f560a10f8451c5f2482e68ee).
    [Click here to see the transaction on tenderly](https://dashboard.tenderly.co/tx/optimistic-kovan/0x1f683b5bc56c6375de070f74df8287c931850f78f560a10f8451c5f2482e68ee).

[Click here for the source code](https://kovan-optimistic.etherscan.io/address/0xbec72ee5e46b39831d077f41f99d39ca1fc1fa9a#code)

**Expected behavior**

I'd expect the revert to include the message.

**System Specs:**
 - Package Version (or commit hash): Solidity compiler v. 0.8.15, the latest.

**Additional context**
[Based on a report from the Discord](https://discord.com/channels/667044843901681675/887914409207414785/987778328691871824).

**Comment by pradyuman-verma** [comment]
Optimism chain normal revert function `revert(string)` doesn't even revert with string in the inline assembly. 

Here is the contract address - [0x60F9054214066a62550AEc23EFA4c78013F4a2ee](https://optimistic.etherscan.io/address/0x60f9054214066a62550aec23efa4c78013f4a2ee#code)
Testing script - https://play.instadapp.io/KAuGiQCsGqMxBt1L9Wn3X

If we try to do the revert without inline assembly, it returns the string data with escaped characters.
Contract - [0x3595d71b4d96a155Ef08f0B7643384751AdeD9f4](https://optimistic.etherscan.io/address/0x3595d71b4d96a155Ef08f0B7643384751AdeD9f4#code)
Testing script - https://play.instadapp.io/Rn7LPAc7Zxy8Li-vQcoX5


It is blocking a feature that we are building on top of uniswap v3. It would be great if it gets fixed quickly.

**Comment by smartcontracts** [comment]
@pradyuman-verma Have you tested this on an Ethereum testnet? I don't think what you're trying to do will work, because Solidity explicitly encodes errors using a special format `abi.encodeWithSelector("Error(string), err)`.

**Comment by smartcontracts** [comment]
```
/**
 *Submitted for verification at optimistic.etherscan.io on 2022-06-20
*/

//SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
pragma experimental ABIEncoderV2;

contract revertTry {
    function revertNow() public {
        bytes memory revertData = abi.encodeWithSignature("Error(string)", "testing");
        assembly {
            let revertData_size := mload(revertData)
            revert(add(32, revertData), revertData_size)
        }
    }
}
```

**Comment by smartcontracts** [comment]
I believe this is the current Geth behavior. Custom reverts do not start with `keccak256("Error(string)")[0:4]` and therefore the errors aren't being decoded. Here I've replicated this behavior on Goerli:

oldRevert: https://goerli.etherscan.io/tx/0x65b706dadd528e3103b24cc54e1775d15b4f8ddbe8192e6c8a24af2b6f41f16a
newRevert: https://goerli.etherscan.io/tx/0xbcdeec25dc16c8f5e8c783d91cda4e64dda2855b0ca526343b931ea90d493458

Same behavior

**Comment by pradyuman-verma** [comment]
@smartcontracts Alright, I got your point. 
But I think the first point was that the optimism chain doesn't support custom revert, I have tested that on another chain it works fine, but on optimism, the custom revert doesn't work.

**Comment by qbzzt** [comment]
New style reverts seem to be supported on Goerli (see [the contract](https://goerli.etherscan.io/address/0x6d86ae3e08960f04932ec8e38c5ac692351114ba#code) and the [tx with a new revert](https://goerli.etherscan.io/tx/0xa37c446496073baac32c439257e133ccec965333eda633f9987a336dea4f4c64)). This is different from the behavior on Optimistic Kovan ([see tx here](https://kovan-optimistic.etherscan.io/tx/0x1f683b5bc56c6375de070f74df8287c931850f78f560a10f8451c5f2482e68ee)).

**Comment by smartcontracts** [comment]
> New style reverts seem to be supported on Goerli (see [the contract](https://goerli.etherscan.io/address/0x6d86ae3e08960f04932ec8e38c5ac692351114ba#code) and the [tx with a new revert](https://goerli.etherscan.io/tx/0xa37c446496073baac32c439257e133ccec965333eda633f9987a336dea4f4c64)). This is different from the behavior on Optimistic Kovan ([see tx here](https://kovan-optimistic.etherscan.io/tx/0x1f683b5bc56c6375de070f74df8287c931850f78f560a10f8451c5f2482e68ee)).

Is this the behavior of Etherscan? Or the behavior of our version of Geth?
