### ISSUE TITLE
Wrong receipt status for early contract creation blocked by whitelist

### ISSUE THREAD

**Issue by hahn659** [ethereum-optimism/optimism#2822]
There is a problem. The "0x9ed8f713b2cc6439657db52dcd2fdb9cc944915428f3c6e2a7703e242b259cb9" transaction has no error field, The status of txReceipt is not a failed transaction, but it is in https://optimistic.etherscan.io is marked as a failed transaction. How to judge whether this transaction fails?

**Comment by smartcontracts** [comment]
I believe this may have been a bug with the whitelisting logic, which was known to have broken a few things early on. Note that the error is "deployer address not whitelisted".
