### ISSUE TITLE
Is there a rule in L1 contract which enforces the monotonic increase of timestamp?

### ISSUE THREAD

**Issue by NIC619** [ethereum-optimism/optimism#2833]
**Describe the bug**
In [CTC.appendSequencerBatch](https://github.com/ethereum-optimism/optimism/blob/b81eae576bc577200bcfacf221b9e9076be5a91d/packages/contracts/contracts/L1/rollup/CanonicalTransactionChain.sol#L346-L347), it seems that for the transactions sent by sequencer, timestamp is simply taken from the value provided by the sequencer. If sequencer accidentally or maliciously provide timestamps breaking the assumption that timestamp should be monotonically increasing, dApps relying on this assumption will be in trouble.

**Expected behavior**
When appending new transactions, their timestamp should be checked by the contract to make sure timestamp is monotonically increased.

**Comment by tynes** [comment]
Fixed by bedrock
