### ISSUE TITLE
invalid transaction: insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by ImagineYao** [ethereum-optimism/optimism#2834]
When I set my transfer amount equals to balance - gasPrice * gas and broadcast transaction, I get this error. How can I do to solve it?

**Comment by ImagineYao** [comment]
Thanks a lot!

**Comment by ImagineYao** [comment]
> You need to account for the L1 security fee. See https://community.optimism.io/docs/developers/build/transaction-fees/ .
> 
> To estimate that value, see https://github.com/ethereum-optimism/optimism-tutorial/tree/main/sdk-estimate-gas

Sorry to bother you again. When I follow the doc and calculate the l1 gas used with the link https://kovan-optimistic.etherscan.io//address/0x420000000000000000000000000000000000000F#readContract, but always I get a number that 60 greater than the actual gas used.
My test transaction is
https://kovan-optimistic.etherscan.io/tx/0x02cf852d6f9c11d824d5e5a2af264b968e01b52bd5abf7350a9568079f251551

The estimated L1 gas used is 4536, but the actual on the explorer is 4486.
<img width="737" alt="截屏2022-06-30 11 15 52" src="https://user-images.githubusercontent.com/38421751/176585241-2a9f5074-fffd-42ad-a0ea-cd19f113106d.png">

Here is how I set up my unsigned transaction.

```
tx := types.NewTransaction(0, common.HexToAddress("0x05d132975d8efcd67262980c54f9030319c91af0"), big.NewInt(404993102026570), 80000, big.NewInt(9000000000), []byte{})
rawTxBytes, _ := tx.MarshalBinary()
fmt.Println(hexutil.Encode(rawTxBytes))
// 0xec80850218711a00830138809405d132975d8efcd67262980c54f9030319c91af087017056cdfb974a80808080
```

**Comment by ares0x** [comment]
I have encountered the same problem when transferring OP.How did you solve the problem?
