### ISSUE TITLE
Address contracts-bedrock linter and compiler warnings

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimism#2883]
The `contracts-bedrock` packages print a ton of warnings when running either `yarn build` or `yarn lint:contracts`. 

**Spec:**

We should address these warnings, and tighten up our solhint config so that all warnings become errors (we're clearly not paying attention to warnings, so they are pointless). 

Suggested approach: break the work up into a few PRs. For a given PR you might: 
- fix all instances of a specific warning across multiple files
- fix all warnings in a specific file

**Comment by shastings8** [comment]
Agrred

**Comment by smartcontracts** [comment]
No more compiler warnings in contracts-bedrock, closing!
