### ISSUE TITLE
@eth-optimism/contracts npm package does not include typechain factories

### ISSUE THREAD

**Issue by tuler** [ethereum-optimism/optimism#2977]
The `@eth-optimism/contracts` npm package includes types generated by typechain, but does not include the factories, which are generated at `dist/types/factories` and included by `dist/types/index.ts`.

The [configuration of npm package files](https://github.com/ethereum-optimism/optimism/blob/6f74ca9f81cc9e26886b64cb1ef1c951b22ebb95/packages/contracts/package.json#L10) is not including files in subdirectories of `dist/types`.

**Comment by tynes** [comment]
A new package has been release, please re-open if it doesn't fix your problem
