### ISSUE TITLE
About L1 to L2 recharge action call chain

### ISSUE THREAD

**Issue by af913337456** [ethereum-optimism/optimism#3062]
Hi, i am learning the OP source code, met some problem which confuse me, about the Deposit ETH action.

1. User try to deposit ETH to his OP address;
2. Call contract "L1StanderBridge.sol 's depositETH function" ;
3. Core code: `bytes memory message = abi.encodeWithSelector(
            IL2ERC20Bridge.finalizeDeposit.selector,
            address(0),
            Lib_PredeployAddresses.OVM_ETH,
            _from,
            _to,
            msg.value,
            _data
        );`
4. On the third point above, the "finalizeDeposit" function will be call on the L2StanderBridge.sol to finish the deposit action.

Question is:
     When did the "finalizeDeposit" being called and by which character? the Relayer?

Some job i have done:
      I been searching the "message-relayer" project which wrote by typescript, but didn't find any sign of the L2StanderBridge's "finalizeDeposit" calling. The call of "relayMessage" is also limited, and only the L1 contract can be called.

Would you pls help me, thanks alot.

**Comment by af913337456** [comment]
@maurelian 

Thank you very much for your answer. I read the source code of all components further according to your tips, and came to the following conclusion. It should be correct. Could you please help me review it again? This will be the first complete code level call process in the whole network.

👇👇👇👇

L1 Deposit Action:

L1StanderdBridge.sol’s depositETH —> _initiateETHDeposit
 —> sendCrossDomainMessage —> sendMessage —> L1CrossDomainMessenger.sol’s sendMessage —> _sendXDomainMessage —> enqueue —> Event_TransactionEnqueued

TransactionEnqueued’s tx_message contains the “finalizeDeposit” function

DataTransportLayer:

filter_TransactionEnqueued ---> StorageEnqueued

Sequencer:

load_TransactionEnqueued —> Execute_Tx —> finalizeDeposit being executed —> done

**Comment by maurelian** [comment]
Yep, that's looks right to me.

**Comment by af913337456** [comment]
> Yep, that's looks right to me.

@maurelian 

I have another doubt:

We know that "batch submitter" will extract transactions from L2 block, and then submit them in batches to L1 CTC. In our conclusion above, will the recharge transaction also be submitted? If so, but it has completed the recharge action in L2. Is it unnecessary to submit it to CTC again, because it does not need to be challenged.

**Comment by af913337456** [comment]
@maurelian

**Comment by af913337456** [comment]
> > Yep, that's looks right to me.
> 
> @maurelian
> 
> I have another doubt:
> 
> We know that "batch submitter" will extract transactions from L2 block, and then submit them in batches to L1 CTC. In our conclusion above, will the recharge transaction also be submitted? If so, but it has completed the recharge action in L2. Is it unnecessary to submit it to CTC again, because it does not need to be challenged.

@maurelian are you still here sir

**Comment by af913337456** [comment]
> Once `appendSequencerBatch()` has successfully run, there should be no need to ever submit the same batches again.

@maurelian 

Thank you. I know that the same transaction will only be submitted once in `appendsequencerbatch`. What I want to know is that the last step of recharge transaction has been completed in L2, that is, `finalizedeposit`. At this time, it is no longer necessary to be submitted to L1 by `appendsequencerbatch`, right? If so, I didn't find this in the code. If not, we know that the transactions submitted by `appendsequencerbatch` to L1 will eventually be executed in L1, and the recharge action does not need to be executed at all.

**Comment by af913337456** [comment]
> > Once `appendSequencerBatch()` has successfully run, there should be no need to ever submit the same batches again.
> 
> @maurelian
> 
> Thank you. I know that the same transaction will only be submitted once in `appendsequencerbatch`. What I want to know is that the last step of recharge transaction has been completed in L2, that is, `finalizedeposit`. At this time, it is no longer necessary to be submitted to L1 by `appendsequencerbatch`, right? If so, I didn't find this in the code. If not, we know that the transactions submitted by `appendsequencerbatch` to L1 will eventually be executed in L1, and the recharge action does not need to be executed at all.

@maurelian wait for you sir

**Comment by Inphi** [comment]
@af913337456 what do you mean by a "recharge transaction"?

**Comment by af913337456** [comment]
> @af913337456 what do you mean by a "recharge transaction"?

the deposit action, "_initiateETHDeposit"

**Comment by af913337456** [comment]
> > Once `appendSequencerBatch()` has successfully run, there should be no need to ever submit the same batches again.
> 
> @maurelian
> 
> Thank you. I know that the same transaction will only be submitted once in `appendsequencerbatch`. What I want to know is that the last step of recharge transaction has been completed in L2, that is, `finalizedeposit`. At this time, it is no longer necessary to be submitted to L1 by `appendsequencerbatch`, right? If so, I didn't find this in the code. If not, we know that the transactions submitted by `appendsequencerbatch` to L1 will eventually be executed in L1, and the recharge action does not need to be executed at all.

@maurelian pls help me sir

**Comment by maurelian** [comment]
I do not understand. So that we can try to answer your question efficiently:

1. Please summarize your question from the beginning without simply quoting your previous questions.
2. Please describe the flow you are asking about, including which parts you do understand, and which parts are unclear.
3. Please provide links to the locations in the code that you are unclear about.

**Comment by af913337456** [comment]
> We know that "batch submitter" will extract transactions from L2 block, and then submit them in batches to L1 CTC. In our conclusion above, will the recharge transaction also be submitted? If so, but it has completed the recharge action in L2. Is it unnecessary to submit it to CTC again, because it does not need to be challenged.

@maurelian 

Thanks. I will now explain it from the complete process, combined with the project components and the code call chain process.
	
1. User try to `deposit` ETH to his `OP` address;
2. Call contract `L1_StanderBridge.sol' s depositETH function`;
3. `L1_StanderBridge.sol` core code: `bytes memory message = abi.encodeWithSelector( IL2ERC20Bridge.finalizeDeposit.selector, address(0), Lib_PredeployAddresses.OVM_ETH, _from, _to, msg.value, _data )`;
4. On the third point above, will call to the `sendCrossDomainMessage --> L1CrossDomainMessenger's sendMessage --> _sendXDomainMessage --> CanonicalTransactionChain's enqueue --> TransactionEnqueued`
5. On the fourth point above, the `finalizeDeposit` function will be included in `TransactionEnqueued`;
6. And the `DataTransportLayer` scan the block transactions and filter the `TransactionEnqueued`, then storage the `TransactionEnqueued`;
7. `Sequencer` load the `TransactionEnqueued` from the DB, and execute the Tx which contains the `finalizeDeposit` message, this will call to the `L2_StanderBridge.sol 's finalizeDeposit function`;
8. So far, the user's deposit process has been completed. His L2 address also has a corresponding recharge token;
9. In the above steps, the `Tx` of the message containing `finalizeDeposit` is also packaged in the L2 block;
10. `batch-submitter` will extract transactions from L2 block and pack them in `tx-batches` to L1's CTC;
11. The tinth point, `deposit transaction` also be submitted by `batch-submitter`, because it is packaged in L2 block;
12. `tx-batches` which in L1's CTC, wait for the `challenge time` pass;
13. the the `challenge time` passed, now the `relayer` call to `L1CrossDomainMessenger's relayMessage`;
14. Now the problem comes, the user's `deposit` action has completed in L2, you can see it at the `eighth point`. And now will it be executed again in 'l1crossdomainmessenger's relaymessage'? If not, why not? According to the process, it has indeed been submitted here.

**Comment by af913337456** [comment]
> > We know that "batch submitter" will extract transactions from L2 block, and then submit them in batches to L1 CTC. In our conclusion above, will the recharge transaction also be submitted? If so, but it has completed the recharge action in L2. Is it unnecessary to submit it to CTC again, because it does not need to be challenged.
> 
> @maurelian
> 
> Thanks. I will now explain it from the complete process, combined with the project components and the code call chain process.
> 
> 1. User try to `deposit` ETH to his `OP` address;
> 2. Call contract `L1_StanderBridge.sol' s depositETH function`;
> 3. `L1_StanderBridge.sol` core code: `bytes memory message = abi.encodeWithSelector( IL2ERC20Bridge.finalizeDeposit.selector, address(0), Lib_PredeployAddresses.OVM_ETH, _from, _to, msg.value, _data )`;
> 4. On the third point above, will call to the `sendCrossDomainMessage --> L1CrossDomainMessenger's sendMessage --> _sendXDomainMessage --> CanonicalTransactionChain's enqueue --> TransactionEnqueued`
> 5. On the fourth point above, the `finalizeDeposit` function will be included in `TransactionEnqueued`;
> 6. And the `DataTransportLayer` scan the block transactions and filter the `TransactionEnqueued`, then storage the `TransactionEnqueued`;
> 7. `Sequencer` load the `TransactionEnqueued` from the DB, and execute the Tx which contains the `finalizeDeposit` message, this will call to the `L2_StanderBridge.sol 's finalizeDeposit function`;
> 8. So far, the user's deposit process has been completed. His L2 address also has a corresponding recharge token;
> 9. In the above steps, the `Tx` of the message containing `finalizeDeposit` is also packaged in the L2 block;
> 10. `batch-submitter` will extract transactions from L2 block and pack them in `tx-batches` to L1's CTC;
> 11. The tinth point, `deposit transaction` also be submitted by `batch-submitter`, because it is packaged in L2 block;
> 12. `tx-batches` which in L1's CTC, wait for the `challenge time` pass;
> 13. the the `challenge time` passed, now the `relayer` call to `L1CrossDomainMessenger's relayMessage`;
> 14. Now the problem comes, the user's `deposit` action has completed in L2, you can see it at the `eighth point`. And now will it be executed again in 'l1crossdomainmessenger's relaymessage'? If not, why not? According to the process, it has indeed been submitted here.

@Inphi @smartcontracts here

**Comment by af913337456** [comment]
@maurelian sir

**Comment by maurelian** [comment]
> And now will it be executed again in 'l1crossdomainmessenger's relaymessage' ? If not, why not? According to the process, it has indeed been submitted here.

`relayMessage()` will only succeed if this check passes: 

https://github.com/ethereum-optimism/optimism/blob/2a7be367634f147736f960eb2f38a77291cdfcad/packages/contracts/contracts/L1/messaging/L1CrossDomainMessenger.sol#L180

`_verifyXDomainMessage` requires that the message is stored in the L2ToL1MessagePassers state.
