### ISSUE TITLE
gas required exceeds allowance

### ISSUE THREAD

**Issue by ares0x** [ethereum-optimism/optimism#3072]
When I try to construct an ETH transaction and use EstimateGas() to estimate the miner's fee, it says: gas required exceeds allowance(xxxxx)

**Comment by smartcontracts** [comment]
Usually happens if the transaction is reverting. Do you have the transaction you're trying to estimate gas for?

**Comment by smartcontracts** [comment]
Going to close this for lack of activity. If this is still occurring, please let us know and I will reopen.
