### ISSUE TITLE
Hardhat config error while building bedrock

### ISSUE THREAD

**Issue by lucadonnoh** [ethereum-optimism/optimism#3087]
**Describe the bug**
```zsh
hardhat.config.ts:54:5 - error TS2322: Type '{ deploy: string; deployments: string; deployConfig: string; }' is not assignable to type 'ProjectPathsUserConfig'.
  Object literal may only specify known properties, and 'deployConfig' does not exist in type 'ProjectPathsUserConfig'.
```
while building bedrock

**To Reproduce**
1. clone repo
2. `cd optimism/packages/contracts-bedrock`
3. `yarn`
4. `yarn build`

**Screenshots**
![image](https://user-images.githubusercontent.com/30298476/180664137-87a430d9-81f9-4385-b1d2-db6cd0ce2654.png)

**Additional context**
Foundry is installed.

**Comment by wsdt** [comment]
same issue

**Comment by bradyjoestar** [comment]
same issue here.

**Comment by smartcontracts** [comment]
Investigating

**Comment by smartcontracts** [comment]
Do you observe the same issue if you build at the root level? `cd optimism && yarn clean && yarn install && yarn build`

**Comment by smartcontracts** [comment]
My guess is that you need to build the `hardhat-deploy-config` package first. I generally recommend building at the root level, which should automatically figure out the dependency graph and build packages in the correct order.

**Comment by lucadonnoh** [comment]
> Do you observe the same issue if you build at the root level? `cd optimism && yarn clean && yarn install && yarn build`

nope it works

**Comment by wsdt** [comment]
receiving this now:

```
 "C:\Users\Kevin Riedl\Desktop\boba\bedrock\optimism\packages\contracts-bedrock\node_modules\.bin\\node.exe"  "C:\Users\Kevin Riedl\Desktop\boba\bedrock\optimi
sm\packages\contracts-bedrock\node_modules\.bin\\..\..\..\..\node_modules\typechain\dist\cli\cli.js" --target ethers-v5 --out-dir dist/types --glob 'artifacts/!(build-info)/**/+([a-zA-Z0-9_]).json'
```

**Comment by smartcontracts** [comment]
@wsdt are you on Windows?

**Comment by wsdt** [comment]
yes

**Comment by wsdt** [comment]
ok yeah it only doesn't work on windows

**Comment by wsdt** [comment]
Windows is the issue

**Comment by tynes** [comment]
Unfortunately we don't have anybody on the team that uses windows without WSL so its hard to keep compatibility. Definitely recommend a unix based environment.

Also be sure to build from the root because the `contracts-bedrock` package imports from other packages in the monorepo

**Comment by wsdt** [comment]
Yes used WSL then and it worked. Thanks

**Comment by ivanvpan** [comment]
Seeing the issue on Linux.

**Comment by GrapeBaBa** [comment]
I met this issue on macOS

**Comment by GrapeBaBa** [comment]
> Mac use `npm install @eth-optimism/hardhat-deploy-config` success！

it doesn't works for me

**Comment by GrapeBaBa** [comment]
It seems I found the issue, the node version must be `16.16.0`
