### ISSUE TITLE
Concern about current OP tx pattern in Bedrock limitations

### ISSUE THREAD

**Issue by diwu1989** [ethereum-optimism/optimism#3142]
**Describe the bug**
Recently, TX per second on OP is reaching 5 tx/s due to popularity and volume of trading.
Today, each TX can consume the full execution gas of the L2 block, since its 1 block per tx, 15M gas.

In Bedrock spec, it will be 1 block per 2s, with 20M gas cap.
If you replay the recent week's transactions against Bedrock spec, you will see that there will be massive congestion due to the 20M gas block cap.

So I feel like the outcome could become:
- Bedrock L2 execution gas price get bid up like crazy because execution is not 15M gas per tx anymore, its now 20M gas per 2s
- Or, if L2 gas price is still kept low like today, there will be congestion due to 20M gas per 2s is simply not enough anymore

There's a design goal for Bedrock to have the cheapest L2 execution gas price, but given congestion, market gas price will get bid up and OP won't be so cheap as it is today due to gas bidding.

Am I missing something here? How will you plan on keeping L2 gas price cheaper than Arbitrum Nitro AND solve the congestion issue?

**Comment by tynes** [comment]
Please reopen if you have concerns now that the system is live
