### ISSUE TITLE
Incorrect import path in L1 and L2 ERC721 bridges in `@eth-optimism/contracts-periphery`

### ISSUE THREAD

**Issue by sam-goldman** [ethereum-optimism/optimism#3331]
**Describe the bug**
Installing the package `@eth-optimism/contracts-periphery` and importing `L1ERC721Bridge.sol` in a contract results in the following error: 
```
Error HH404: File @eth-optimism/contracts/contracts/libraries/bridge/CrossDomainEnabled.sol, imported from @eth-optimism/contracts-periphery/contracts/L1/L1ERC721Bridge.sol, not found.
```
Likewise, importing `L2ERC721Bridge.sol` results in:
```
Error HH404: File @eth-optimism/contracts/contracts/libraries/bridge/CrossDomainEnabled.sol, imported from @eth-optimism/contracts-periphery/contracts/L2/L2ERC721Bridge.sol, not found.
```

This error originates from the L1ERC721Bridge [here](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-periphery/contracts/L1/L1ERC721Bridge.sol#L4-L6) and the L2ERC721Bridge [here](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-periphery/contracts/L2/L2ERC721Bridge.sol#L4-L6). Changing these paths to `@eth-optimism/contracts/libraries...` fixes the issue, but would cause the build process in the monorepo to fail.

**To Reproduce**
1. `git clone git@github.com:sam-goldman/bridge-imports.git`. This is just Hardhat's default project with the appropriate dependencies from `@eth-optimism` installed and imported in `Lock.sol`.
2. `cd bridge-imports && npm install`
3. `npx hardhat compile`. This should result in the error above.

**Comment by smartcontracts** [comment]
Ahh this year-old issue returns! https://github.com/ethereum-optimism/optimism/issues/850
