### ISSUE TITLE
Deposit of SNX token hungs

### ISSUE THREAD

**Issue by quantbrothers** [ethereum-optimism/optimism#3335]
**Describe the bug**
My app did deposit of SNX ERC20 token but all this amount still not received by Opitmism side.

**To Reproduce**
All info are existing in mainnet transaction
0x577c4b7323f5cd6fa595d2fca8a9dfa8dcf41624a391bffaa38dd6a1a356d6ca

I am used DepositERC20To function of the Optimism Gateway contract

**Expected behavior**
Expected to receive it

**Screenshots**

**System Specs:**

**Additional context**

**Comment by smartcontracts** [comment]
SNX uses a custom bridge implementation and cannot be bridged to Optimism using the standard bridge. You can follow logic [like what we use in the SDK](https://github.com/ethereum-optimism/optimism/blob/f772f66cfcb59e57d43bdd0419baf5a5ee96228e/packages/sdk/src/adapters/standard-bridge.ts#L153-L198) to check if a given bridge can be deposited via the standard bridge. I generally recommend using the SDK to transfer tokens to avoid problems like this.

**Comment by smartcontracts** [comment]
Our standard bridge does its best to detect failed deposits like this and will send them back to Ethereum. You should be able to recover these funds by relaying this withdrawal transaction on Ethereum: https://optimistic.etherscan.io/messagerelayer?search=0xfc74b0684c049eb896cdd5950e807607f4a91961598240651c41f9780993427e

The funds will be sent back to the address that deposited the funds in the first place. It looks like the funds will be returned to [0x364c90218f6664f6c8b154ad9c3e31947cd3640c](https://etherscan.io/address/0x364c90218f6664f6c8b154ad9c3e31947cd3640c).

**Comment by quantbrothers** [comment]
Thank you, it works! Problem solved

**Comment by smartcontracts** [comment]
I'm glad it worked! Going to close this issue
