### ISSUE TITLE
Binding generation can be extremely slow

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#3344]
**Describe the bug**
Running `make all` inside `op-bindings` can be extremely slow when on a low-powered machine. I believe this is mainly because the contracts are being repeatedly recompiled (which can take upwards of a minute on a laptop PER compilation run meaning the whole process can take 10-15 minutes). Binding generation would be much faster if we only compiled the contracts once and then generated as many bindings as possible based on that one compilation.

**Comment by smartcontracts** [comment]
As per @mslipper running `make` with some parallelism may help (e.g., `make -j 8`)

**Comment by tynes** [comment]
I usually run with `make -j $(nproc)` and tried adding that to CI but it would break in CI. `foundry` sometimes is smart enough to not recompile, we def need a better solution for building the bindings

**Comment by smartcontracts** [comment]
I believe this is fixed now. @mslipper did something to make it faster and I can confirm it's much faster now. Compilation happens just once.
