### ISSUE TITLE
Typo after abi formatting using interface.format function

### ISSUE THREAD

**Issue by Kharabet** [ethereum-optimism/optimism#3372]
**Describe the bug**
I was trying to get l1BaseFee using `OVMGasPriceOracle` contract. I have initialized it using the following code:

```
  const OVMGasPriceOracle = getContractFactory('OVM_GasPriceOracle').attach(
    predeploys.OVM_GasPriceOracle
  )
  const formatted = OVMGasPriceOracle.interface.format(ethers.utils.FormatTypes.json) as string
  const abi = JSON.parse(formatted)
  return new web3.eth.Contract(abi, OVMGasPriceOracle.address)
```

In `formatted`  there is a typo in abi structure: `ouput` instead of `output` which doesn't allow to parse the result of the method call

![image](https://user-images.githubusercontent.com/14793248/189368201-7e33f767-e157-4ff0-a8f6-f125eade8dee.png)

**Additional context**
The issue comes actually from ethers.js formatter and they have fixed it here https://github.com/ethers-io/ethers.js/issues/1275 in version 5.0.29 

In package json I see ethers.js v 5.0.0 as a dependency. Upgrading it to v 5.0.29 would resolve the issue

**Comment by smartcontracts** [comment]
The `@eth-optimism/contracts` package has `ethers@^5` as a peer dependency, so the version of ethers will depend on the version you have installed in your project. If you install the latest version of ethers within your project, this should work.
