### ISSUE TITLE
[QUESTION] What is the default genesis file used when running the Docker image from /ops

### ISSUE THREAD

**Issue by cyborgdennett** [ethereum-optimism/optimism#3461]
Hello, I am benchmarking the local Optimism docker image. By going to `optimism/ops` and then running `docker compose up`.

To complete my benchmark, I have to know the exact blocktime and configs used in the ethereum and optimism node running. 

The way I understand it, ethereum in hardhat is running POA clique consensus algo. What I need is the following information `period` and `epoch`, normally specified in the `genesis { config }`  genesis.json

```json
"config": {
        "chainId": <yourChainId>,
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "clique": {
            "period": <yourPeriodInSecs>,
            "epoch": <yourEpochInBlocks>
        }
    },
```

Any help would be highly appreciated.

**Comment by tynes** [comment]
Hardhat doesn't run clique, it just automines blocks as transactions come in

**Comment by cyborgdennett** [comment]
@tynes Do you know where I can find the genesis files or the configs?

**Comment by tynes** [comment]
After bringing up `ops`, look at `localhost:8081`, the geth docker image fetches the genesis.json from there
https://github.com/ethereum-optimism/optimism/blob/df041c0ec4289dd74b80879bbb6942c43d97c8d4/ops/scripts/deployer.sh#L59

**Comment by cyborgdennett** [comment]
@tynes Thank you. This is the genesis file for the optimism network. I tried to get the chainId's in Geth. and this is what I got:
```
ethereum: 31337
optimism: 17
```

So now I have the genesis for optimism, but I am still looking for the genesis of ethereum(there is no genesis file with chainId 31337 at localhost:8080).

**Comment by tynes** [comment]
I believe the L1 runs hardhat, so there is no genesis.json

**Comment by cyborgdennett** [comment]
```> global.network.config
{
  hardfork: 'muirGlacier',
  blockGasLimit: 9500000,
  gas: 9500000,
  gasPrice: 8000000000,
  chainId: 31337,
  throwOnTransactionFailures: true,
  throwOnCallFailures: true,
  allowUnlimitedContractSize: false,
  mining: { auto: true, interval: 0 },
  accounts: {
    initialIndex: 0,
    count: 20,
    path: "m/44'/60'/0'/0",
    mnemonic: 'test test test test test test test test test test test junk',
    accountsBalance: '10000000000000000000000'
  },
  loggingEnabled: false,
  gasMultiplier: 1
}
```
Yes true, I am wondering how to interpret benchmark results in this way

**Comment by tynes** [comment]
I don't think that the `ops` setup is particularly good for benchmarking because using hardhat as L1 is not going to produce realistic results. How are you planning on benchmarking things?

**Comment by cyborgdennett** [comment]
In my setup, I deploy a contract to L1 and then benchmark all the functions, then I do the same on L2.
