### ISSUE TITLE
Replacement for Kovan sequencer for supporting deprecated OP Kovan?

### ISSUE THREAD

**Issue by Aracki** [ethereum-optimism/optimism#3692]
For the old Optimism Kovan, our `dtl` stopped working. Although we have Kovan synced with latest state, we are getting:

```
{"level":30,"time":1665558869430,"msg":"Cannot connect to L2, retrying 20/20"}
{"level":30,"time":1665558869430,"msg":"Cannot connect to L2, shutting down"}
{"level":30,"time":1665558869430,"msg":"Service is stopping..."}
{"level":30,"time":1665558869430,"msg":"Service has stopped"}
```

Probably related is the fact that:
```
https://kovan-sequencer.optimism.io/
```
is not live anymore. What should we do to support old deprecated blocks from OP Kovan...?

**Comment by tynes** [comment]
You can run `l2geth` without the dtl and serve all requests if you remove this config when running `l2geth` - https://github.com/ethereum-optimism/optimism/blob/7cfeb99fd7741cc7a137192b7c58591bc301efe6/l2geth/cmd/utils/flags.go#L810

It will no longer try to sync and just serve static data

**Comment by smartcontracts** [comment]
DTL and L2Geth should probably gracefully handle chain shutdowns though

**Comment by Aracki** [comment]
Thank you @tynes, it's working 🙌🏼
