### ISSUE TITLE
Fix verifyFoundryInstall script name

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#3778]
Simple issue for a first-time contributor! `verifyFoundryInstall.ts` should be `verify-foundry-install.ts`, we don't use camel case for file names. https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/scripts/verifyFoundryInstall.ts

**Comment by chriswolfdesign** [comment]
I attempted to complete this issue with this PR: https://github.com/ethereum-optimism/optimism/pull/3780

Some of the automation is failing but I'm unsure why.  Any feedback would be appreciated.

**Comment by smartcontracts** [comment]
Thanks @chriswolfdesign!
