### ISSUE TITLE
Remove unused tasks in contracts-bedrock

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#3779]
Simple task for a first-time contributor. [rollup-config](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/tasks/rollup-config.ts) and [check-l2-config](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/tasks/check-l2-config.ts) are unused and can safely be deleted.

**Comment by nfl0** [comment]
resolved
