### ISSUE TITLE
Quality of life: canary release should have option to release only specific packages

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#3808]
**Is your feature request related to a problem? Please describe.**
I use the [canary release action very frequently](https://github.com/ethereum-optimism/optimism/blob/develop/.github/workflows/publish-canary.yml). However, this action publishes every single package when I usually just want to publish one package. This spams our releases and makes unnecessary packages.

**Describe the solution you'd like**
I would like to see the workflow updated with an input that would allow me to specify which packages to release. If the input is empty, then the canary release would run as it currently does.

**Comment by lucadidomenico** [comment]
Hi, I would like to work on this!
