### ISSUE TITLE
debug_traceBlockByHash takes a lot of time to get traces and times out

### ISSUE THREAD

**Issue by aditya17cb** [ethereum-optimism/optimism#3867]
**Describe the bug**
Hello, I am an engineer at Coinbase working on getting Optimism traces for our service. We are seeing a lot of timeouts when calling debug_traceBlockByHash method and it takes a lot of time to get the data. Is this a known issue? And is there any fix for this to speed up the process of getting the traces.

For context, I am using Quicknode to get the Optimism data.

**Comment by jsvisa** [comment]
@aditya17cb maybe you can try `jsvisa/optimism-l2geth:v0.2` this docker image, FYI https://github.com/ethereum-optimism/optimism/pull/3097
