### ISSUE TITLE
op-replica-data-transport-layer-1:TypeError: Cannot read properties of null 

### ISSUE THREAD

**Issue by zhy827827** [ethereum-optimism/optimism#3992]
**Describe the bug**
#op-replica-data-transport-layer-1 error logs:

op-replica-data-transport-layer-1  | {"level":50,"time":1668411148974,"extra":{"message":"TypeError: Cannot read properties of null (reading 'from')","stack":"TypeError: Cannot read properties of null (reading 'from')\n    at Object.getExtraData (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/handlers/sequencer-batch-appended.js:27:38)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async L1IngestionService._syncEvents (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:230:39)\n    at async L1IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:140:17)\n    at async L1IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async Promise.all (index 1)\n    at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:69:13)\n    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:77:9"},"msg":"Caught an unhandled error"}

 .env config file:
`
COMPOSE_PROJECT_NAME=op-replica
COMPOSE_FILE=replica.yml:replica-shared.yml:replica-toml.yml
ETH_NETWORK=mainnet
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=http://192.1.1.17:8545
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://mainnet.optimism.io
SEQUENCER_CLIENT_HTTP=https://mainnet.optimism.io
SHARED_ENV_PATH=../envs/mainnet
GCMODE=archive
L2GETH_IMAGE_TAG=0.5.29
DTL_IMAGE_TAG=0.5.48
HC_IMAGE_TAG=1.1.12
L2GETH_HTTP_PORT=9991
L2GETH_WS_PORT=9992
DTL_PORT=7878
GETH_INIT_SCRIPT=check-for-chaindata-berlin.sh
HEALTHCHECK__REFERENCE_RPC_PROVIDER=https://mainnet.optimism.io
HEALTHCHECK__TARGET_RPC_PROVIDER=http://l2geth-replica:8545

RESTART=unless-stopped

\# Sync source
ROLLUP_BACKEND=l2
DATA_TRANSPORT_LAYER__DEFAULT_BACKEND=l2
DATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND=l2
DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
DATA_TRANSPORT_LAYER__SYNC_FROM_L2=true
`
then: docker-compose up -d && docker-compose logs -f 
found this issuse at this time

How can I solve this problem ？？？？

**Comment by smartcontracts** [comment]
Please try setting DATA_TRANSPORT_LAYER__SYNC_FROM_L1=false

**Comment by zhy827827** [comment]
no,

**Comment by zhy827827** [comment]
> 

no, i can't set  DATA_TRANSPORT_LAYER__SYNC_FROM_L1=false, i use DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=http://192.1.1.17:8545/  for sync.

We are RPC providers,If we use other L2 providers, we will be laughed at by others？？？

Now that we use L1, the blocks are no longer synchronized. How can we solve this problem? @smartcontracts

**Comment by sanbotto** [comment]
I have the same issue... We need to sync from L1.

The same config that is not working for new nodes is working properly for a node created about 20 days ago, it just stopped working for nodes created more recently than 20 days ago so, given that this issue was opened 16 days ago, I guess this is caused by some update that happened 16 to 20 days ago.

**Comment by smartcontracts** [comment]
@zhy827827 I saw that you had 

```
ROLLUP_BACKEND=l2
DATA_TRANSPORT_LAYER__DEFAULT_BACKEND=l2
DATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND=l2
DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
DATA_TRANSPORT_LAYER__SYNC_FROM_L2=true
```

Configured so I assumed you were trying to sync from L2. If you want to sync from L1 then you will need to set `SYNC_FROM_L2=false`.

**Comment by smartcontracts** [comment]
> I have the same issue... We need to sync from L1.
> 
> The same config that is not working for new nodes is working properly for a node created about 20 days ago, it just stopped working for nodes created more recently than 20 days ago so, given that this issue was opened 16 days ago, I guess this is caused by some update that happened 16 to 20 days ago.

I don't immediately see anything in the recent changes that would cause this issue. I know of someone else who ran into this problem and fixed it, going to ask them how they fixed it.

**Comment by sanbotto** [comment]
> I don't immediately see anything in the recent changes that would cause this issue. I know of someone else who ran into this problem and fixed it, going to ask them how they fixed it.

Thanks! I'm still seeing this exact same issue no matter how I deploy the new nodes, using both the Docker and the non-Docker way of deploying, so that would be helpful.

**Comment by hub-il** [comment]
@sanbotto were you able to get this issue resolved? I have the same issue and can't figure out what is causing it.  My L1 is serving up just fine to other L2 chains.

**Comment by zhy827827** [comment]
> 



> > I have the same issue... We need to sync from L1.
> > The same config that is not working for new nodes is working properly for a node created about 20 days ago, it just stopped working for nodes created more recently than 20 days ago so, given that this issue was opened 16 days ago, I guess this is caused by some update that happened 16 to 20 days ago.
> 
> I don't immediately see anything in the recent changes that would cause this issue. I know of someone else who ran into this problem and fixed it, going to ask them how they fixed it.

if i use l1,then 'ethereumoptimism/data-transport-layer:latest' have error:

{"level":50,"time":1670926343808,"extra":{"message":"TypeError: Cannot read properties of null (reading 'from')","stack":"TypeError: Cannot read properties of null (reading 'from')\n at Object.getExtraData (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/handlers/sequencer-batch-appended.js:27:38)\n at runMicrotasks ()\n at processTicksAndRejections (node:internal/process/task_queues:96:5)\n at async L1IngestionService._syncEvents (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:277:39)\n at async L1IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:156:17)\n at async L1IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n at async Promise.all (index 1)\n at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:69:13)\n at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:78:9"},"msg":"Caught an unhandled error"}
{"level":30,"time":1670926344318,"highestSyncedL1Block":13596466,"targetL1Block":13598466,"msg":"Synchronizing events from Layer 1 (Ethereum)"}

**Comment by zhy827827** [comment]
> @zhy827827 I saw that you had
> 
> ```
> ROLLUP_BACKEND=l2
> DATA_TRANSPORT_LAYER__DEFAULT_BACKEND=l2
> DATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND=l2
> DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
> DATA_TRANSPORT_LAYER__SYNC_FROM_L2=true
> ```
> 
> Configured so I assumed you were trying to sync from L2. If you want to sync from L1 then you will need to set:
> 
> ```
> ROLLUP_BACKEND=l1
> DATA_TRANSPORT_LAYER__DEFAULT_BACKEND=l1
> DATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND=l1
> DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
> DATA_TRANSPORT_LAYER__SYNC_FROM_L2=false
> ```

if i use l1 to data sync,then ethereumoptimism/data-transport-layer:latest  have error:

{"level":50,"time":1670926343808,"extra":{"message":"TypeError: Cannot read properties of null (reading 'from')","stack":"TypeError: Cannot read properties of null (reading 'from')\n    at Object.getExtraData (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/handlers/sequencer-batch-appended.js:27:38)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async L1IngestionService._syncEvents (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:277:39)\n    at async L1IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:156:17)\n    at async L1IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async Promise.all (index 1)\n    at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:69:13)\n    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:78:9"},"msg":"Caught an unhandled error"}
{"level":30,"time":1670926344318,"highestSyncedL1Block":13596466,"targetL1Block":13598466,"msg":"Synchronizing events from Layer 1 (Ethereum)"}

and ethereumoptimism/data-transport-layer:latest not sync block. I really don't know how to solve the problem of optimism。

**Comment by hub-il** [comment]
I am having the exact same issue as @zhy827827 using a Geth 1.10.26 archive node.

**Comment by sanbotto** [comment]
To anyone having the error "Cannot read properties of null", take a look at this resolved issue: https://github.com/ethereum-optimism/optimism/issues/4235

**Comment by hub-il** [comment]
> To anyone having the error "Cannot read properties of null", take a look at this resolved issue: #4235

Where you able to determine what was going on with Geth that was causing the issue?  From what I understand, you resolved it by using different Ethereum node software all together.

**Comment by sanbotto** [comment]
> Where you able to determine what was going on with Geth that was causing the issue? From what I understand, you resolved it by using different Ethereum node software all together.

No. I thought the missing `--http.api` and `--ws.api` flags were the issue but I'm now using `--http.api "eth,txpool,debug,web3,net"` and `--ws.api "eth,txpool,debug,web3,net"` and nothing has changed on the Optimism side, I'm still getting the `Cannot read properties of null` error. Maybe I'm missing a particular API that I don't know about, but that geth node works fine with absolutely everything else...

I haven't had issues with Infura or Alchemy. I'm using both on different nodes.

**Comment by hub-il** [comment]
@sanbotto @zhy827827 I think I figured the issue.  Back in Feb 2021 Geth started unindexing txs by hash after 1 year.  So you are no longer able to look up transactions by their hashes.  I did some looking at how Optimism is finding transactions and it is trying to look up transactions by hash.

The way to fix this should be to set `--txlookuplimit=0` and the Geth node should start reindexing again.  After I set this and restarted Geth I am seeing:
~~~~
INFO [12-14|22:19:18.060] Indexing transactions                    blocks=12838 txs=2,399,722 tail=13,789,288 total=13,802,126 elapsed=25.016s
~~~~

You can check to see if this is your issue by running the command below:
~~~~
curl http://your-eth-node:8545 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getTransactionByHash","params":["0x896440b9bb3a942e8891a964fd70b4fff8338b89d7b66e3c06978b4ee98d9d3c"],"id":1,"jsonrpc":"2.0"}'
~~~~

**Comment by zhy827827** [comment]
> 

Let me test it. Thank you, guys

**Comment by zhaoxiangjunupi** [comment]
> @hub-il 大家好，感谢你们帮我解决了这个问题。我找到了原因：DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT= "erigon eth archive node" can be sync！

在吗哥

**Comment by zhy827827** [comment]
> > @hub-il 大家好，感谢你们帮我解决了这个问题。我找到了原因：DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT= "erigon eth archive node" can be sync！
> 
> 在吗哥

在

**Comment by zhaoxiangjunupi** [comment]
> > > @hub-il 大家好，感谢你们帮我解决了这个问题。我找到了原因：DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT= "erigon eth archive node" can be sync！
> > 
> > 
> > 在吗哥
> 
> 在

![image](https://user-images.githubusercontent.com/101166067/210950196-b4c77ce5-4516-4de7-a7c2-b69603709b96.png)
我运行了一个dtl，然后正常同步呢，我又运行了一个l2geth，然后它一直卡在这，怎么办

**Comment by zhy827827** [comment]
你源码起的？

**Comment by zhy827827** [comment]
data-transport-layer_1  | {"level":30,"time":1672989241263,"method":"GET","url":"/transaction/index/55325184?backend=l2","elapsed":1,"msg":"Served HTTP Request"}
l2geth-replica_1        | DEBUG[01-06|07:14:01.264] Applying transaction to tip              index=55325184 hash=0xe0c1dbea6786a6b71622e9fe3b1122869481c1e96598eed10ce9b06afb4dac2d origin=sequencer
l2geth-replica_1        | DEBUG[01-06|07:14:01.264] Attempting to commit rollup transaction  hash=0xe0c1dbea6786a6b71622e9fe3b1122869481c1e96598eed10ce9b06afb4dac2d
l2geth-replica_1        | INFO [01-06|07:14:01.289] New block                                index=55325184 l1-timestamp=1672034664 l1-blocknumber=16266965 tx-hash=0xe0c1dbea6786a6b71622e9fe3b1122869481c1e96598eed10ce9b06afb4dac2d queue-orign=sequencer gas=1012223  fees=1.012223e-06    elapsed=25.217ms
l2geth-replica_1        | DEBUG[01-06|07:14:01.295] Miner got new head                       height=55325185 block-hash=0x7b47125bbf9135fddffe5ad25e97c503c65b7f60aa709a1173ab50c54cac0836 tx-hash=0xe0c1dbea6786a6b71622e9fe3b1122869481c1e96598eed10ce9b06afb4dac2d tx-hash=0xe0c1dbea6786a6b71622e9fe3b1122869481c1e96598eed10ce9b06afb4dac2d
data-transport-layer_1  | {"level":30,"time":1672989241303,"method":"GET","url":"/transaction/index/55325185?backend=l2","elapsed":0,"msg":"Served HTTP Request"}
l2geth-replica_1        | DEBUG[01-06|07:14:01.304] Applying transaction to tip              index=55325185 hash=0x59e98b28ef428328b83a1c12d6a85d7a57266248effd29976b85fdafb4c3f24d origin=sequencer
l2geth-replica_1        | DEBUG[01-06|07:14:01.304] Attempting to commit rollup transaction  hash=0x59e98b28ef428328b83a1c12d6a85d7a57266248effd29976b85fdafb4c3f24d

**Comment by zhy827827** [comment]
正常是这样的

**Comment by zhaoxiangjunupi** [comment]
> 正常是这样的

这是l2geth日志呗

**Comment by zhaoxiangjunupi** [comment]
> 正常是这样的

我靠，那我差哪了呢，‘
docker run -it --rm -v /data/zxj/l2geth:/root --name optimisml2 \
-p 8545:8545 -p 8546:8546 -p 8547:8547 -p 30303:30303  \
-e DATADIR=/geth  \
-e CHAIN_ID=10 -e NETWORK_ID=10 \
-e NO_DISCOVER=true -e NO_USB=true \
-e RPC_ADDR=0.0.0.0 -e RPC_API=eth,rollup,net,web3,debug \
-e RPC_CORS_DOMAIN=* -e RPC_ENABLE=true  \
-e RPC_PORT=8545 -e RPC_VHOSTS=* \
-e WS_ADDR=0.0.0.0 -e WS_API=eth,rollup,net,web3,debug  \
-e WS_ORIGINS=* -e WS=true \
-e ROLLUP_BACKEND=l1 -e ROLLUP_SYNC_SERVICE_ENABLE=true  \
-e USING_OVM=true  \
-e SEQUENCER_CLIENT_HTTP=https://mainnet.optimism.io  \
-e ETH1_SYNC_SERVICE_ENABLE=true  \
-e L2GETH_GENESIS_URL=https://storage.googleapis.com/optimism/mainnet/genesis-berlin.json  \
-e L2GETH_GENESIS_HASH=0x106b0a3247ca54714381b1109e82cc6b7e32fd79ae56fbcc2e7b1541122f84ea  \
-e ROLLUP_CLIENT_HTTP=http://172.17.0.2:7878  \
-e ROLLUP_MAX_CALLDATA_SIZE=40000 -e ROLLUP_DISABLE_TRANSFERS=false \
-e ROLLUP_POLL_INTERVAL_FLAG=1s  -e ROLLUP_ENABLE_L2_GAS_POLLING=false \
-e ROLLUP_VERIFIER_ENABLE=true  -e ETH1_CTC_DEPLOYMENT_HEIGHT=13596466  \
-e BLOCK_SIGNER_ADDRESS=0x00000398232E2064F896018496b4b44b3D62751F \
-e BLOCK_SIGNER_PRIVATE_KEY=6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27  \
-e ROLLUP_ADDRESS_MANAGER_OWNER_ADDRESS=0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A  \
-e ROLLUP_GAS_PRICE_ORACLE_OWNER_ADDRESS=0x648E3e8101BFaB7bf5997Bd007Fb473786019159 \
ethereumoptimism/l2geth:prerelease-0.0.0-sequencer-sync-bug   --cache 100000 --maxpeers 100  --graphql  --graphql.addr 0.0.0.0  --vmodule=eth/*=5,miner=4,rpc=5,rollup=4,consensus/clique=1   --allow-insecure-unlock  --metrics  --syncmode full  --verbosity=5
这 是我的运行命令，哥你帮忙看看

**Comment by zhy827827** [comment]
为啥不直接docker-compose up -d 直接就起了？

**Comment by zhaoxiangjunupi** [comment]
> 为啥不直接docker-compose up -d 直接就起了？

哈哈哈哈哈我肯定是被迫啊哥
![image](https://user-images.githubusercontent.com/101166067/210952310-a2f17b63-af9c-4427-8ead-e92b15793627.png)
DEBUG[01-06|07:12:47.761] Allowed origin(s) for WS RPC interface [*]
INFO [01-06|07:12:47.761] WebSocket endpoint opened                url=ws://[::]:8546
DEBUG[01-06|07:12:49.858] Couldn't add port mapping                proto=tcp extport=30303 intport=30303 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered"





DEBUG[01-06|07:18:59.833] Served eth_blockNumber                   conn=172.17.0.1:50182 reqid=1 t=29.792µs
DEBUG[01-06|07:19:01.196] Served eth_blockNumber                   conn=172.17.0.1:50184 reqid=1 t=26.446µs

^[[A^[[B
DEBUG[01-06|07:22:15.824] Served eth_blockNumber                   conn=172.17.0.1:50186 reqid=1 t=29.171µs



TRACE[01-06|07:27:47.756] Refreshing port mapping                  proto=tcp extport=30303 intport=30303 interface="UPnP or NAT-PMP"
DEBUG[01-06|07:27:47.756] Couldn't add port mapping                proto=tcp extport=30303 intport=30303 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered"
这是啥问题啊哥

**Comment by zhy827827** [comment]
我看看，稍等

**Comment by zhaoxiangjunupi** [comment]
> 我看看，稍等

麻烦哥了

**Comment by zhy827827** [comment]
https://community.optimism.io/docs/developers/build/run-a-node/#the-optimism-client-software
你对比一下你的参数呢

**Comment by zhy827827** [comment]
还有 data-transport-layer_1的配置是啥样的？ 官方文档的意思先首先是部署这个

**Comment by zhaoxiangjunupi** [comment]
> 还有 data-transport-layer_1的配置是啥样的？ 官方文档的意思先首先是部署这个

![image](https://user-images.githubusercontent.com/101166067/210953899-f8390344-6620-4a60-927e-208a9d900828.png)
这是 data-transport-layer_1的配置，我请求一下 curl -s http://localhost:7878/eth/syncing?backend=l1
他返回这个
{"syncing":true,"highestKnownTransactionIndex":60968054,"currentTransactionIndex":1100795}
正常的应该

**Comment by zhy827827** [comment]
我也整不懂了，我是docker-compose 跑的。经验告诉我，这个鸟链如果从L1同步到后面，会出问题的

**Comment by zhy827827** [comment]
你的网络是不是有问题哦

**Comment by zhaoxiangjunupi** [comment]
> ### [Jan 6, 2023](#issuecomment-1373285684)



> 你的网络是不是有问题哦

哈？这是网络的问题吗？

**Comment by zhy827827** [comment]
我建议你先 docker-compose 先跑一下。再拆出来running.

**Comment by zhaoxiangjunupi** [comment]
> 

行，麻烦哥了，我再鼓捣鼓捣

**Comment by zhy827827** [comment]
你服务器在哪里

**Comment by zhy827827** [comment]
docker-compose 和你docker run 没啥区别啊。你也可以修改文件 start.sh

**Comment by zhaoxiangjunupi** [comment]
> 你服务器在哪里

东京

**Comment by zhaoxiangjunupi** [comment]
> docker-compose 和你docker run 没啥区别啊。你也可以修改文件 start.sh

好，我再试试

**Comment by zhy827827** [comment]
哦，那就是不是网络问题。但是你docker run : port mapping 问题

**Comment by zhy827827** [comment]
docker run 还不如 源码安装

**Comment by zhaoxiangjunupi** [comment]
> 哦，那就是不是网络问题。但是你docker run : port mapping 问题

谢谢哥
