### ISSUE TITLE
Deposit of wstETH token failed 

### ISSUE THREAD

**Issue by quantbrothers** [ethereum-optimism/optimism#4087]
**Describe the bug**
I did MainNet -> Optimism deposit of wstETH token
mainnet transaction https://etherscan.io/tx/0x3ebf3ee83a2df5b7fce786c788072f1ce82b3ee859c011e75d7af7165d2beab9

then message relayed to L2 with Optimism transaction
https://optimistic.etherscan.io/tx/0x160727e302d15f4d311c7de5dbfff5b7ad16c952a6a48744423d2bb58c724950

But this transaction has DepositFailed log message

**To Reproduce**
I tried refund with message relayer 
but this does not work https://optimistic.etherscan.io/messagerelayer?search=0x160727e302d15f4d311c7de5dbfff5b7ad16c952a6a48744423d2bb58c724950

**Expected behavior**
How to refund funds?

**Comment by smartcontracts** [comment]
Hi, please use [discord](discord.optimism.io) for support-related issues!

**Comment by quantbrothers** [comment]
Discord did not help (

This well known issue as i know. Previously i did refund using "message relayer"
https://github.com/ethereum-optimism/optimism/issues/3335

but now this seems to be does not work. How refund funds now?
