### ISSUE TITLE
target client not connected,geth port 8545 is not started

### ISSUE THREAD

**Issue by zhy827827** [ethereum-optimism/optimism#4088]
i run optimism with docker-compose
there have a error log: replica-healthcheck_1   | {"level":50,"time":1669517394843,"msg":"target client not connected"}
I check ethereumoptimism/l2geth:0.5.29,

/usr/local/bin # netstat -anutlp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:33075        0.0.0.0:*               LISTEN      -
udp        0      0 127.0.0.11:36488        0.0.0.0:*                           -

**geth port 8545 is not started**

why? The official can help me
my docker-compose  .env config:

`COMPOSE_PROJECT_NAME=op-replica
COMPOSE_FILE=replica.yml:replica-shared.yml:replica-toml.yml
ETH_NETWORK=mainnet
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=http://192.1.1.17:8545
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://mainnet.optimism.io
SEQUENCER_CLIENT_HTTP=https://mainnet.optimism.io
SHARED_ENV_PATH=../envs/mainnet
GCMODE=full
L2GETH_IMAGE_TAG=0.5.29
DTL_IMAGE_TAG=0.5.48
HC_IMAGE_TAG=1.1.12
L2GETH_HTTP_PORT=9991
L2GETH_WS_PORT=9992
DTL_PORT=7878
GETH_INIT_SCRIPT=check-for-chaindata-berlin.sh
HEALTHCHECK__REFERENCE_RPC_PROVIDER=https://mainnet.optimism.io
HEALTHCHECK__TARGET_RPC_PROVIDER=http://l2geth-replica:8545

RESTART=unless-stopped

ROLLUP_BACKEND=l2
DATA_TRANSPORT_LAYER__DEFAULT_BACKEND=l2
DATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND=l2
DATA_TRANSPORT_LAYER__SYNC_FROM_L1=false
DATA_TRANSPORT_LAYER__SYNC_FROM_L2=ture
`

**Comment by smartcontracts** [comment]
If you are syncing from L1 then you will need to use the following configuration:

```
ROLLUP_BACKEND=l1
DATA_TRANSPORT_LAYER__DEFAULT_BACKEND=l1
DATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND=l1
DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
DATA_TRANSPORT_LAYER__SYNC_FROM_L2=false
```

**Comment by smartcontracts** [comment]
I recommend using https://github.com/smartcontracts/simple-optimism-node

**Comment by zhy827827** [comment]
thankcccc guys!!!

**Comment by zhy827827** [comment]
When the block is synchronized to 48791252 ，optimism not running.  i use DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://opt-mainnet.g.alchemy.com/v2/mpF51jIbCUlylwLZKlo2JNLqFIjWr9T**  sync  optimism block. 

Now ethereumoptimism/data-transport-layer:0.5.49 prompt error :
{"level":30,"time":1670920919267,"fromBlock":48826241,"toBlock":48826281,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}

How can this be solved?

**Comment by zhy827827** [comment]
> > When the block is synchronized to 48791252 ，optimism not running. i use DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://opt-mainnet.g.alchemy.com/v2/mpF51jIbCUlylwLZKlo2JNLqFIjWr9T** sync optimism block.
> > Now ethereumoptimism/data-transport-layer:0.5.49 prompt error : {"level":30,"time":1670920919267,"fromBlock":48826241,"toBlock":48826281,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
> > How can this be solved?
> 
> Are you sure that is an error message? Looks like an info level log

Synchronizing unconfirmed transactions from Layer 2 (Optimism)  not sync blocks
