### ISSUE TITLE
run `make build` with main branch, will occur errors: Could not open '/lib64/ld-linux-x86-64.so.2'

### ISSUE THREAD

**Issue by agnarsong** [ethereum-optimism/optimism#4137]
**Describe the bug**
run `make build` with main branch, will occur errors: Could not open '/lib64/ld-linux-x86-64.so.2'

**To Reproduce**
1. git clone git@github.com:ethereum-optimism/optimism.git
2. cd optimism
3. make build

**Expected behavior**
will running optimism in localnetwork

**Screenshots**
![image](https://user-images.githubusercontent.com/98442960/204994316-40e59a5f-616b-4978-94f7-7c471d7b4217.png)

**System Specs:**
![image](https://user-images.githubusercontent.com/98442960/204994623-a95d3af2-1882-4fd8-a095-2cc5d972cbbc.png)

**Additional context**
I tried the following, but I still encountered the same error
update every service in docker-compose.yml like this:
![image](https://user-images.githubusercontent.com/98442960/204995223-e89e6618-4323-44ad-98ae-714b7549a37d.png)

**Comment by tynes** [comment]
This looks like `solc` is having issues, not sure what the problem is exactly. Looks like you are building under rosetta, perhaps see if you can get the missing library installed on your machine
