### ISSUE TITLE
Add More Integration Tests

### ISSUE THREAD

**Issue by gakonst** [ethereum-optimism/optimism#419]
Currently, we're missing the following integration tests:
* [x] [OVM Context](https://github.com/ethereum-optimism/integration-tests/blob/b269df601703b57aea1150baa8060d5b0a14e94a/packages/x-domain/test/ovmcontext.spec.ts): Imported in https://github.com/ethereum-optimism/optimism/pull/522
* [ ] [Automatic Fraud Prover](https://github.com/ethereum-optimism/optimism-ts-services/blob/2fc4521af2efc20932f219d53973c9a68ff6e21d/src/services/fraud-prover.service.ts)

**Comment by jliphard** [comment]
For the automatic fraud prover, it would be very useful to have `FRAUD=true` and `FRAUD_RATE=3` .env parameters for the sequencer, that instruct it to occasionally commit fraudulent state roots (e.g. 3 of 10). The integration test would then consist of spinning up an L2 Geth docker with those .env parameters set and then also bringing up a verifier and fraud prover, and checking some defined number of state roots, knowing that some fraction of them are incorrect.

**Comment by smartcontracts** [comment]
I think this issue is a bit too vague and will end up never being closed, so I'm just going to close it now. If we want to do an automatic fraud prover we should have a separate ticket for it.
