### ISSUE TITLE
Assign CODEOWNERS

### ISSUE THREAD

**Issue by gakonst** [ethereum-optimism/optimism#420]
The [CODEOWNERS.md](https://github.com/ethereum-optimism/optimism/blob/master/CODEOWNERS.md) should be updated to include who owns what.

**Comment by smartcontracts** [comment]
I'd like to be assigned the following:

```
l2geth/*
packages/smock/*
pacakges/core-utils/*
packages/contracts/*
```

**Comment by maurelian** [comment]
`packages/contracts/*`

I'd also like to follow `smock` and `core-utils` more closely and hopefully support @smartcontracts with that, so let's add:
`packages/smock/*`
`packages/core-utils/*`

**Comment by annieke** [comment]
`packages/batch-submitter/*`
also down to be on `packages/data-transport-layer/*` and `packages/core-utils/*` if necessary

**Comment by tynes** [comment]
`l2geth/*`
`ops/*` (assuming @gakonst isn't going to maintain long term)
`integration-tests/*`

**Comment by karlfloersch** [comment]
`batch-submitter` for sure
`l2geth` while we don't have more folks working on it
Can also do `ops` to support Mark while we don't have more folks working on it

**Comment by K-Ho** [comment]
Can own `packages/core-utils/watcher` , `message-relayer`

**Comment by ben-chain** [comment]
```
packages/contracts/*
packages/core-utils/* if that isn't overloaded, I want to follow more but don't have much experience
```
