### ISSUE TITLE
Malformed batch error if there are no sequencer transactions

### ISSUE THREAD

**Issue by drinkius** [ethereum-optimism/optimism#4205]
**Describe the bug**
We are working of creating an Optimism fork and currently trying to deploy the unchanged contracts from the master branch, commit 2b3b09be. When the first bridge transactions are appearing on L2 (although they are failing, which might contribute to the issue) - when the Batch Submitter service tries to create a batch out of those blocks created on l2geth - we are getting the **ErrMalformedBatch** error.

The culprit seems to be hidden in commit [fe680568](https://github.com/ethereum-optimism/optimism/commit/fe6805684da30b6b8d223e9eeff772fff267bb7a) - here there is a condition marked: [_There must be transactions if there are contexts_](https://github.com/ethereum-optimism/optimism/blob/fe6805684da30b6b8d223e9eeff772fff267bb7a/go/batch-submitter/drivers/sequencer/encoding.go#L185) 
If the batch doesn't contain any Sequencer transactions (only the bridge transactions from L1) - then the **AppendSequencerBatchParams** object doesn't contain any Txs since they are added [only for the Sequenced transactions](https://github.com/ethereum-optimism/optimism/blob/fe6805684da30b6b8d223e9eeff772fff267bb7a/go/batch-submitter/drivers/sequencer/batch.go#L140)

Maybe we are missing something in the setup here, or maybe the service has already been updated for Bedrock release which we currently are ignoring and trying to deploy the existing Optimism release

**To Reproduce**
1. Deploy new version of the contracts from commit 2b3b09be
2. Run the L2 from scratch

**Expected behavior**
Batches exclusively with transactions originating from the L1 are written by the Sequencer using Batch Submitter service

**System Specs:**
 - OS: Ubuntu 20.04
 - Package Version (or commit hash): 2b3b09be

**Comment by smartcontracts** [comment]
We're currently all hands on deck getting Bedrock out the door, so work on fixes to the legacy codebase may be slow right now. I'll get this triaged for you.

**Comment by tynes** [comment]
You should consider using the new system over the legacy system, its a lot better

**Comment by drinkius** [comment]
Thanks, when should we expect the Bedrock release then? If you think it's not worth investing time in the legacy system then we'd better wait with the development ourselves. Is it worth trying to run Bedrock testnet for ourselves if it's even a possibility?

**Comment by tynes** [comment]
> Thanks, when should we expect the Bedrock release then - couldn't dig up anything besides the Q4 2022 roadmap entry? If you think it's not worth investing time in the legacy system then we'd better wait with the development ourselves. Is it worth trying to run Bedrock testnet for ourselves if it's even a possibility?

Bedrock is definitely ready to be ran as a testnet, we are currently running a private bedrock testnet ourselves. We are in the final stages of testing and working through our migration before upgrading our public goerli testnet
