### ISSUE TITLE
Pull in example repositories

### ISSUE THREAD

**Issue by gakonst** [ethereum-optimism/optimism#421]
Currently, we have 3 kinds of examples:
* waffle: https://github.com/ethereum-optimism/Truffle-ERC20-Example
* truffle: https://github.com/ethereum-optimism/Waffle-ERC20-Example
* hardhat: https://github.com/ethereum-optimism/optimism-tutorial

These should all be pulled in this repo under an `examples/` directory, and tested in CI. IMO showing the step-by-step evolution of the example repo is better done as content in a blogpost/for the community hub, and not for the github repo

**Comment by smartcontracts** [comment]
This is done now
