### ISSUE TITLE
Cache CI Layers

### ISSUE THREAD

**Issue by gakonst** [ethereum-optimism/optimism#422]
Currently, the docker images are always re-built from scratch. Ideally, we should be able to cache the layers after each CI build, so that it does not take 10m to run a cold build to run integration tests.

**Comment by snario** [comment]
Attempted to use `satackey/action-docker-layer-caching` but it runs out of space: https://github.com/ethereum-optimism/optimism/actions/runs/900003279

**Comment by gakonst** [comment]
The cause seems to be https://github.com/satackey/action-docker-layer-caching/issues/78#issuecomment-754896508

**Comment by gakonst** [comment]
The cause seems to be https://github.com/satackey/action-docker-layer-caching/issues/78#issuecomment-754896508
