### ISSUE TITLE
Reapply git history of packages within monorepo

### ISSUE THREAD

**Issue by snario** [ethereum-optimism/optimism#428]
To expedite this repository, we didn't add the git commit history of the prior repositories. This isn't an urgent issue, but is something we should resolve soon to ensure we keep that history.

**Comment by snario** [comment]
Starting with contracts in #466

**Comment by maurelian** [comment]
I think this can be closed @snario?

**Comment by snario** [comment]
@maurelian some other packages don't have their history in yet. Just `contracts` do.

**Comment by smartcontracts** [comment]
Seems like the commit history for specific contracts still doesn't exist. Is it possible to include that? Or is that prohibitively difficult? I find `blame` quite useful sometimes.

**Comment by maurelian** [comment]
+1. I thought I brought all that in but just I realize what happened: the PR that had all the commit history was never merged because it also included a bunch of unrelated stuff.

I'll have to go through that process again, but I'm a bit worried about how much the repo is already changing now. Could make it more difficult￼.

**Comment by maurelian** [comment]
@snario Further to what @smartcontracts said above: 
> Seems like the commit history for specific contracts still doesn't exist. Is it possible to include that? Or is that prohibitively difficult? I find blame quite useful sometimes.

I see that #466 should have imported all the history for the contracts, but looking at the blame for some of our most important contracts (ex. [EM](https://github.com/ethereum-optimism/optimism/blame/master/packages/contracts/contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol), [SafetyChecker](https://github.com/ethereum-optimism/optimism/blame/master/packages/contracts/contracts/optimistic-ethereum/OVM/execution/OVM_StateManager.sol)), it's still mostly just showing the original import commit.

**Comment by snario** [comment]
You're right... I'll investigate this.

**Comment by smartcontracts** [comment]
I think it's too late for this now. Oh well. Closing.
