### ISSUE TITLE
Flickering integration test #1 (symptom: tests timeout past 100s)

### ISSUE THREAD

**Issue by gakonst** [ethereum-optimism/optimism#430]
The Native ETH communication integration test seems to be flaky [sometimes](https://github.com/ethereum-optimism/optimism/runs/2326405216) ([other example](https://github.com/ethereum-optimism/optimism/pull/429/checks?check_run_id=2326656165)) at the [`withdrawTo` and `withdraw` tests](https://github.com/ethereum-optimism/optimism/blob/master/integration-tests/test/native-eth.spec.ts#L90-L180).

This is probably due to the <s>message relayer</s> batch submitter not working as expected, but the core issue is still unidentified.

**Comment by snario** [comment]
@gakonst is this not fixed by #432? If not let's re-open this issue.

**Comment by gakonst** [comment]
It looks like it is not happening any more.

**Comment by gakonst** [comment]
Reopened as this started happening again. I am convinced that this is the batch submitter not submitting batches and I suspect is the same bug which we encountered on mainnet and required a restart.

**Comment by snario** [comment]
In order to debug this, I'd like to see #485 get done. It seems like the flicker is a timeout, and it's not obvious how to reproduce locally, so I'd want to see exactly what's going on in CI from the logs of each service.

**Comment by smartcontracts** [comment]
I haven't seen this issue in a long time. I'm going to close this unless someone sees it again.
