### ISSUE TITLE
How to get block data before re-genesis?

### ISSUE THREAD

**Issue by yj0x0x** [ethereum-optimism/optimism#4309]
**Describe the bug**

I want to get block data before regenesis. 
Based on the document below there are time gap between current block history from the pre-genesis( before jun 4th 2021) till the current change start ( around Nov 11th, 2021). 

https://community.optimism.io/docs/useful-tools/explorers/#pre-23-june-2021-history

More than  5 months has gap. 

Please let me know how to get `RAW` block data before regenesis. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Specs:**
 - OS:
 - Package Version (or commit hash):

**Additional context**

**Comment by witem** [comment]
@tynes is there any ways to get this data?
