### ISSUE TITLE
eth_syncing reporting false when node is behind

### ISSUE THREAD

**Issue by kaladinlight** [ethereum-optimism/optimism#4393]
**Describe the bug**
When attempting to use the `eth_syncing` rpc method to determine if the node is synced or not, it returns `false` even though it is not in sync

**To Reproduce**
1. Run `eth_blockNumber` against local node and reference node
2. Observe local node is behind reference node
3. Run `eth_syncing` against local node
4. Observe `false` returned implying node is synced

**Expected behavior**
`eth_syncing` to return block sync data when not fully synced and only return false when synced.

**Screenshots**
```
/usr/local/bin # curl -d '{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}' -H "Content-Type:application/json" http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":"0x2e4e7e6"}
/usr/local/bin # curl -d '{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}' -H "Content-Type:application/json" https://mainnet.optimism.io
{"jsonrpc":"2.0","result":"0x2e4ed7c","id":1}
/usr/local/bin # curl -d '{"jsonrpc":"2.0","id":1,"method":"eth_syncing","params":[]}' -H "Content-Type:application/json" http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":false}
/usr/local/bin # curl -d '{"jsonrpc":"2.0","id":1,"method":"eth_syncing","params":[]}' -H "Content-Type:application/json" https://mainnet.optimism.io
{"jsonrpc":"2.0","result":false,"id":1}
```

**System Specs:**
 - OS: Alpine Linux v3.15
 - Package Version (or commit hash): Geth/v1.9.10-stable/linux-amd64/go1.18

**Additional context**
l2geth syncing against l1

**Comment by tynes** [comment]
This is a known problem and will be fixed with the launch of the bedrock release. There are no plans to fix it before then

**Comment by kaladinlight** [comment]
> This is a known problem and will be fixed with the launch of the bedrock release. There are no plans to fix it before then

Ok, thank you for the info!
