### ISSUE TITLE
op-node stuck after a derivation temporary error

### ISSUE THREAD

**Issue by Kelvyne** [ethereum-optimism/optimism#4496]
**Describe the bug**
For some reason, the L1 RPC returned an invalid receipt for a tx at block 8132846 (on Goerli)

```
ops-bedrock-op-node-1      | WARN [12-15|09:19:57.203] Derivation process temporary error       attempts=8143 err="temp: failed to fetch receipts of L1 block 0xd2e567dc9d620f1a17ca79c229d3f0e92200931918273580c3cc799bf662c5f6:8132846 for L1 sysCfg update: receipt 20 has unexpected tx index 0"
```

I relaunched `op-node` ~24 hours later, it seemed to be stuck (no logs after startup). 

**To Reproduce**

I don't know

**Expected behavior**
It should 

**Screenshots**

**System Specs:**
 - OS:  Debian GNU/Linux 11 (bullseye)
 - Package Version (or commit hash): 0b7963ebeb5f8ba62fa365576a8a5b62686206de

**Additional context**

I deployed contracts on Goerli and run a batcher, proposer and node on the same server.

I tried to deduce what was the problem. 
I fetched the faulty block using the same L1 RPC : 
```node
  const block = await hre.ethers.provider.getBlockWithTransactions(8132846);

  console.log(block.hash);
  for (let i = 0; i < block.transactions.length; i++) {
    const tx = block.transactions[i];
    const receipt = await hre.ethers.provider.getTransactionReceipt(tx.hash);
    console.log(receipt.transactionIndex, i);

  }
```

The transaction indexes seem to match the order.

It looks like the EthClient that fetches receipts has them in cache. I believe it cached the response of the RPC that had an error in it.

What do you guys think ? I can also provide rollup configuration or genesis.

Obviously, if the cache is the problem, I'd love to propose a PR to fix the problem.

**Comment by Kelvyne** [comment]
Little update on the matter: the same temporary error happened this weekend at a different height using the same L1 RPC.
This time, re-running op-node made it resync and fixed the issue.
I'll take some time to try and make the bug reproducible.

**Comment by Kelvyne** [comment]
I believe this was fixed by #4494

**Comment by Mrigesh901** [comment]
I am facing a similar issue but don't know how to resolve it. Can you give a little more detail on how to fix this. I am setting up a base mainnet node and sync is stuck from a day. logs of op-node container shows the same err warning.

**Comment by koraykoska** [comment]
This happens on op-goerli now

**Comment by wangjiangw** [comment]
also happens now, op-node version is v1.4.0

**Comment by Rogalek** [comment]
I am seeing these error right now in my node:
```
Mar 12 09:42:10 ip-my-server bash[4347]: t=2024-03-10T09:42:10+0000 lvl=warn msg="Derivation process temporary error" attempts=27896 err="temp: failed to fetch receipts of L1 block 0x8132291a8005c6d4e325b42f588149e80e5e15ac88ff6850ee54ab5aeca5e18a:18916133 (parent: 0x2b15a6b95357ebfa4e3a525dc048b218d62104adf2e4922db3e3702afe54c257:18916132) for L1 sysCfg update: invalid receipts: receipt 160 has unexpected tx index 0"
```

How to fix that?

**Comment by sahfd4eiugf** [comment]
Having same issue here with Blast (optimism fork)
Is it possible to clear the specific cache on my L1 for this specific block?
