### ISSUE TITLE
@eth-optimism/sdk doesn't work in react/browser

### ISSUE THREAD

**Issue by miguelmota** [ethereum-optimism/optimism#4501]
**Describe the bug**

The package `@eth-optimism/sdk` can't be imported in a browser react app.

**To Reproduce**

```sh
npx create-react-app my-app
cd my-app
npm i @eth-optimism/sdk --save
```

Import in `src/App.js`

```js
import * as op from '@eth-optimism/sdk'
import logo from './logo.svg';
import './App.css';

console.log(op)
```

**Expected behavior**

No import errors

**Screenshots**

![DeepinScreenshot_select-area_20221215102821](https://user-images.githubusercontent.com/168240/207939558-621fb5c5-2ae1-440c-8e43-f1a2054beefc.png)

**System Specs:**
 - OS: N/A
 - Package Version (or commit hash):     `"@eth-optimism/sdk": "^1.8.0"`

**Additional context**

Trying the suggested steps of installing `browserify-zlib` and `assert` didn't resolve it either.

**Comment by smartcontracts** [comment]
Looking into it!

**Comment by smartcontracts** [comment]
Working on this in #4506. Would you mind testing out this canary release for me? I'm away from my computer for the rest of the evening. Otherwise I can test for myself tomorrow. https://www.npmjs.com/package/@eth-optimism/sdk/v/0.0.0-20221115223117

**Comment by smartcontracts** [comment]
@roninjin10 would you mind hopping in here?

**Comment by roninjin10** [comment]
@miguelmota working on this now should be fixed sometime next week

**Comment by roninjin10** [comment]
@miguelmota actually I'm working on a different issue.  Your problem is only that you need to add a pollyfill.   Search for information about pollyfilling node builtins like zlib and you should be good to go.  Let me know if you run into issues

**Comment by miguelmota** [comment]
Thanks for looking into this. The use case is to be able to exit transactions in the browser and check the message status. It's not ideal that it'll require dev's to add polyfills but fortunately I found this simple enough solution for create-react-app:

`npm i -D @craco/craco`

`craco.config.js`

```js
module.exports = {
  webpack: {
    configure: {
      resolve: {
        fallback: {
          zlib: require.resolve('zlib-browserify')
        }
      }
    }
  }
}
```

`package.json`

```
  "scripts": {
    "start": "craco start",
  }
```

Important to note that `browserify-zlib` did not work (albeit more popular), and `zlib-browserify` does work.

**Comment by roninjin10** [comment]
Glad you found a solution @miguelmota .  I added your feedback to our list for SDK 3.0 upgrades
