### ISSUE TITLE
How to run an Optimism node in Docker mode？

### ISSUE THREAD

**Issue by zhaoxiangjunupi** [ethereum-optimism/optimism#4567]
I use the official image:  ethereumoptimism/l2geth: latest。
But I don't know the command to run it。
I don't know what other dependencies or components are. Can someone tell me how to run an Optimism node？

**Comment by harveyff** [comment]
https://github.com/smartcontracts/simple-optimism-node

**Comment by zhaoxiangjunupi** [comment]
> https://github.com/smartcontracts/simple-optimism-node

ou only provide the dockercompose mode here, and what do you need to run to run an Optimism node? Is it just a l2 get?

**Comment by smartcontracts** [comment]
You need L2Geth and the DTL. I would recommend looking at simple-optimism-node to get an idea of how the components fit together, then you should be able to run it manually with docker if necessary. Is there a reason why Docker Compose wouldn't work?

**Comment by zhaoxiangjunupi** [comment]
> You need L2Geth and the DTL. I would recommend looking at simple-optimism-node to get an idea of how the components fit together, then you should be able to run it manually with docker if necessary. Is there a reason why Docker Compose wouldn't work?

Have you run any successful commands?

**Comment by jsvisa** [comment]
@zhaoxiangjunupi maybe you can try https://github.com/jsvisa/ethereum-tsdb/tree/main/startup/optimistic this docker-compose script
