### ISSUE TITLE
call the withdrawTo function in bridge smart contract

### ISSUE THREAD

**Issue by JhinQaQ** [ethereum-optimism/optimism#4610]
Hi, I run a local Optimism node on my machine and send some transactions there.

I deploy those smart contracts
<img width="294" alt="截屏2023-01-05 下午5 12 09" src="https://user-images.githubusercontent.com/41276005/210890137-0e41ca9e-1200-4ed9-8c49-c3d07e09543d.png">

When I call the function withdrawTo/depositTo, this error occurs:

Error: Transaction reverted without a reason string.
<img width="1300" alt="2023-01-05 3 09 59" src="https://user-images.githubusercontent.com/41276005/210889787-9f7dd052-ba36-43f3-88b7-48951bbac630.png">

Only the donate function works on my machine.
Any help will be much appreciated.

**Comment by tynes** [comment]
Try deploying the contracts using `hardhat deploy` - otherwise there is no guarantee they are deployed correctly

**Comment by JhinQaQ** [comment]
> 

Thanks for your help!
I try to use hardhat, but it said the argument for ovmSequencerAddess is not provided.
<img width="543" alt="截屏2023-01-06 下午3 59 31" src="https://user-images.githubusercontent.com/41276005/211099257-224843b2-b7ec-437d-84e1-601c68d247a6.png">
I already create a deploy-config folder and a local.ts in it.
<img width="666" alt="截屏2023-01-06 下午4 00 00" src="https://user-images.githubusercontent.com/41276005/211100435-deb8a139-7c0e-4ba8-b819-8493fe3a2cf0.png">

**Comment by JhinQaQ** [comment]
Besides, I just want to use [the bridge contracts](https://community.optimism.io/docs/developers/bridge/standard-bridge/) directly in my local chain.
I noticed that layer 2's standard bridge is already pre deploy there but didn't see the l1 standard bridge. Can you give me some advice?

**Comment by lucasprelancamentos** [comment]
A fusão deste PR não causará um aumento de versão para nenhum pacote. Se essas alterações não resultarem em uma nova versão, você está pronto para ir. Se essas alterações resultarem em um aumento de versão, você precisará adicionar um conjunto de alterações.

**Comment by tynes** [comment]
I recommend using the bedrock contracts as the legacy contracts are no longer maintained
