### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by gakonst** [ethereum-optimism/optimism#463]
* Some readmes are still pointing to the old repos (e.g. Contracts)
* It'd be nice if we added some "common failure modes" and ways to work around them (e.g. setting the RETRIES higher when bringing up the docker stack)
* Showing how to bring up individual components of the docker stack and showing how to configure them in a more granular way

**Comment by platocrat** [comment]
I can help start this, but I need more info on what the failure modes are and the images in the docker stack.

**Comment by snario** [comment]
@gakonst this may be relevant again after some of the comments found in situations such as #570

**Comment by smartcontracts** [comment]
I think we should close this in favor of more specific issues asking for improvements to specific READMEs. We can *always* improve our READMEs (for the most part). Otherwise I feel like this issue is just gonna sit open forever.
