### ISSUE TITLE
Asking whether Uncle/Stale block occur or not.

### ISSUE THREAD

**Issue by yj0x0x** [ethereum-optimism/optimism#4666]
**Describe the bug**

Wondering that current network composition, uncle/stale block couldn't be possible. 
Because of block producer/miner is an only entity. 
Especially, node are syncing based on the L1 only uncle/stale block couldn't happened. 
Data from the L1 is finalized one not else. 

Can Someone confirm about this?

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Specs:**
 - OS:
 - Package Version (or commit hash):

**Additional context**

**Comment by tynes** [comment]
Uncles are not possible, block production is race free
