### ISSUE TITLE
L2 total fee issue

### ISSUE THREAD

**Issue by PoulWalcker** [ethereum-optimism/optimism#4717]
**Hello Optimism!** @smartcontracts 

We are GTON team 
@drinkius @slavastartsev

We faced with fee issue while deploying fork of pre-bedrock develop branch on BSC testnet network. 
Total fee is a sum of l1 fee and l2 fee.
RPC request does transactions with low trx fees which includes only l2fee. We've checked l2geth logs and they are all good. Also we can see  l1fee and l2fee in method CalculateTotalFee. But metamask and other libraries like web3js don`t include l1fee.

**Logs of l2geth container:**

`l2geth_1           | ERROR[01-16|09:58:13.651] verifyFee =>                             gpo="&{l1GasPrice:0xc025fd22a0 l2GasPrice:0xc025fd2260 overhead:0xc025fd22e0 scalar:0xc014f83230 l1GasPriceLock:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0} l2GasPriceLock:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0} overheadLock:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0} scalarLock:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0}}"
l2geth_1           | ERROR[01-16|09:58:13.652] CalculateTotalFee =>                     raw="[239 131 1 94 78 133 99 234 65 114 128 130 82 8 148 158 29 197 147 195 69 175 137 71 86 88 196 254 53 47 102 71 202 107 88 136 13 224 182 179 167 100 0 0 128]" overhead=2750 l1GasPrice=3000000000000 scalar=1
l2geth_1           | ERROR[01-16|09:58:13.652] CalculateTotalFee =>                     l1Fee=13602000000000000
l2geth_1           | ERROR[01-16|09:58:13.652] CalculateTotalFee =>                     l2GasLimit=21000
l2geth_1           | ERROR[01-16|09:58:13.652] CalculateTotalFee =>                     l2Fee=9011770320000000
l2geth_1           | ERROR[01-16|09:58:13.652] CalculateTotalFee =>                     fee=22613770320000000
l2geth_1           | ERROR[01-16|09:58:13.652] verifyFee =>                             cost=1000000000000000000
l2geth_1           | ERROR[01-16|09:58:13.652] Updating cost 
l2geth_1           | ERROR[01-16|09:58:13.652] verifyFee =>                             cost=1022613770320000000
l2geth_1           | ERROR[01-16|09:58:13.652] verifyFee =>                             state="&{db:0xc000169b60 trie:0xc02e83cbe0 stateObjects:map[] stateObjectsPending:map[] stateObjectsDirty:map[] dbErr:<nil> refund:0 thash:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] bhash:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] txIndex:0 logs:map[] logSize:0 preimages:map[] accessList:0xc02e983220 journal:0xc02e983200 validRevisions:[] nextRevisionId:0 AccountReads:0s AccountHashes:0s AccountUpdates:0s AccountCommits:0s StorageReads:0s StorageHashes:0s StorageUpdates:0s StorageCommits:0s}"
l2geth_1           | ERROR[01-16|09:58:13.652] verifyFee =>                             from=0x1bD26a3054C7B47CE4DCeE3E1078a2e3EdC34581
l2geth_1           | ERROR[01-16|09:58:13.652] verifyFee =>                             l2GasPrice=429131920000
l2geth_1           | ERROR[01-16|09:58:13.652] verifyFee =>                             opts="{UserGasPrice:+429131920000 ExpectedGasPrice:+429131920000 ThresholdUp:+1.1 ThresholdDown:+0.9}"
l2geth_1           | TRACE[01-16|09:58:13.652] Sequencer transaction validation         hash=0xc2637230acdb4cfb3a88fc948ae930321ab3495526468ec49234628b2d484cbe
l2geth_1           | INFO [01-16|09:58:13.653] Updating latest timestamp                timestamp=2023-01-16T09:58:13+0000 unix=1673863093
l2geth_1           | DEBUG[01-16|09:58:13.653] Applying transaction to tip              index=153803 hash=0xc2637230acdb4cfb3a88fc948ae930321ab3495526468ec49234628b2d484cbe origin=sequencer
l2geth_1           | TRACE[01-16|09:58:13.653] Waiting for transaction to be added to chain hash=0xc2637230acdb4cfb3a88fc948ae930321ab3495526468ec49234628b2d484cbe
l2geth_1           | DEBUG[01-16|09:58:13.653] Attempting to commit rollup transaction  hash=0xc2637230acdb4cfb3a88fc948ae930321ab3495526468ec49234628b2d484cbe
l2geth_1           | DEBUG[01-16|09:58:13.654] Served eth_chainId                       conn=172.21.0.5:36182      reqid=15352                                t=27.91µs
l2geth_1           | ERROR[01-16|09:58:13.655] ApplyTransaction =>                      l1Fee=13602000000000000 l1GasPrice=3000000000000 l1GasUsed=4534 scalar=1
l2geth_1           | ERROR[01-16|09:58:13.656] ApplyMessage =>                          NewStateTransition="&{gp:0xc02e98dec0 msg:{to:0xc02df794b8 from:[27 210 106 48 84 199 180 124 228 220 238 62 16 120 162 227 237 195 69 129] nonce:89678 amount:0xc02e982f40 gasLimit:21000 gasPrice:0xc02e9d8240 data:[] checkNonce:true accessList:[] l1Timestamp:1673863093 l1BlockNumber:0xc02e9833e0 queueOrigin:0} gas:0 gasPrice:0xc02e9d8240 initialGas:0 value:0xc02e982f40 data:[] 
`

**Metamask request:**
<img width="360" alt="Screen Shot 2023-01-16 at 2 02 41 PM" src="https://user-images.githubusercontent.com/67789432/212651328-97ef40b9-89b0-4940-87fc-8d34c7271dce.png">

* GasPrice was increased and equals 429131920000

**Optimism-tutorial/sdk-estimate-gas script**
<img width="659" alt="Screen Shot 2023-01-16 at 1 53 24 PM" src="https://user-images.githubusercontent.com/67789432/212649473-c88d5b9d-c16b-4a16-b615-c411e3bd5937.png">

Pull request: https://github.com/GTON-capital/optimism/pull/2 

ChainID: 50021
Currency symbol: GCD
RPC URL: http://170.187.138.20:8545/ 

We used a Berin block set at 152250 block height. You can check genesis setup here http://170.187.138.20:8080/state-dump.latest.json. Other flags for hardforks of genesis were taken from optimism deployment config.

**Comment by tynes** [comment]
metamask will need to add the L1 fee and L2 fee together. The L1 fee is fetched from the `GasPriceOracle` and the L2 fee is fetched just like how you would fetch the fee on an L1 network. I believe metamask turns on features based on chain ids

**Comment by tynes** [comment]
Closing this because it is not an optimism issue, you will need to bump fees in metamask manually or talk to them about supporting your chain id

**Comment by drinkius** [comment]
@tynes It's not Metamask's issue, the gas isn't being taken at the l2geth's level and the transactions are being added to chain despite taking only the L2 portion of gas, no L1 portion is taken
