### ISSUE TITLE
Document running a replica

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#473]
Note: this is out of date, see later comments for the `v0.3.0` config which is up to date

The instructions for running a replica should be clearly documented in a way that does not go stale over time.
The deployed addresses can be found here: https://github.com/ethereum-optimism/optimism/blob/master/packages/contracts/addresses.md

An example of running a replica for mainnet as of 4/14/21 can be found below. This depends on running a local data transport layer that is syncing from L2. The addresses in the config can be found in the above link, note that the `Proxy__*` are used instead of the actual contracts themselves. The state dump files are becoming too large to keep in normal `git`, we need a better way of managing them. Note that both geth and the data transport layer must run together.

```bash
#!/bin/bash

USING_OVM=true ./build/bin/geth \
    --datadir $HOME/.ethereum \
    --eth1.syncservice \
    --eth1.l1crossdomainmessengeraddress 0xD1EC7d40CCd01EB7A305b94cBa8AB6D17f6a9eFE \
    --eth1.l1ethgatewayaddress 0xF20C38fCdDF0C790319Fd7431d17ea0c2bC9959c \
    --rollup.addressmanagerowneraddress 0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A \
    --rollup.statedumppath https://storage.googleapis.com/optimism/mainnet/3.json \
    --eth1.ctcdeploymentheight 12207792 \
    --rollup.clienthttp http://localhost:7878 \
    --rollup.verifier \
    --rpc \
    --dev \
    --chainid 10 \
    --rpcaddr 0.0.0.0 \
    --rpcport 8545 \
    --rpcvhosts '*' \
    --rpccorsdomain '*' \
    --ws \
    --wsaddr 0.0.0.0 \
    --wsport 8546 \
    --wsorigins '*' \
    --rpcapi 'eth,net,rollup,web3' \
    --gasprice 0 \
    --miner.gastarget 9000000 \
    --miner.gaslimit 9000000 \
    --nousb \
    --gcmode=archive \
    --ipcdisable \
    --verbosity=3
```

Config for the data transport layer
```
DATA_TRANSPORT_LAYER__DB_PATH=<my-db-path>
DATA_TRANSPORT_LAYER__SERVER_HOSTNAME=0.0.0.0
DATA_TRANSPORT_LAYER__SERVER_PORT=7878
DATA_TRANSPORT_LAYER__ADDRESS_MANAGER=0xd3EeD86464Ff13B4BFD81a3bB1e753b7ceBA3A39
DATA_TRANSPORT_LAYER__L1_START_HEIGHT=12207737
DATA_TRANSPORT_LAYER__CONFIRMATIONS=10
DATA_TRANSPORT_LAYER__POLLING_INTERVAL=5000
DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL=2000

DATA_TRANSPORT_LAYER__SYNC_FROM_L1=false
DATA_TRANSPORT_LAYER__SYNC_FROM_L2=true
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://mainnet.optimism.io
DATA_TRANSPORT_LAYER__L2_CHAIN_ID=10

DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL=1000
DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS=true
DATA_TRANSPORT_LAYER__LEGACY_SEQUENCER_COMPATIBILITY=false
DATA_TRANSPORT_LAYER__STOP_L2_DEFAULT_BACKEND=l1
```

**Comment by tynes** [comment]
A replica syncs from the sequencer and has the config:

``
DATA_TRANSPORT_LAYER__SYNC_FROM_L1=false
DATA_TRANSPORT_LAYER__SYNC_FROM_L2=true
```

A verifier syncs from the L1 contracts and has the config:

```
DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
DATA_TRANSPORT_LAYER__SYNC_FROM_L2=false
```

**Comment by smartcontracts** [comment]
I believe @optimisticben has done a sufficient job documenting this in https://github.com/optimisticben/op-replica/blob/main/README.md
