### ISSUE TITLE
Asking eth_getTransactionReceipt & eth_getTransactionByHash return value's semantic. 

### ISSUE THREAD

**Issue by yj0x0x** [ethereum-optimism/optimism#4750]
**Describe the bug**

I'm wonder that json-rpc return value's semantic. 
- `eth_getTransactionReceipt`
    - ```
       "l1Fee": "0x51dac9e39908",
       "l1FeeScalar": "1",
       "l1GasPrice": "0x36a4129df",
       "l1GasUsed": "0x17f8",
       ```
 l1fee is l1GasPrice multiply l1GasUsed?? 
 and what is `l1FeeScalar` stands for? 
 
 - `eth_getTransactionByHash`
     -  ```
        "queueOrigin": "sequencer",
        "l1TxOrigin": null,
        "l1BlockNumber": "0xf625fc",
        "l1Timestamp": "0x63904da5",
        ```
  queueOrigin meant that where tx came from ?
  if value is `sequencer` that is. L2 -> L2 transaction or this includes L2 -> L1 transaction too?
  what for `l1TxOrigin`? 
  `l1BlockNumber & l1Timstamp` stand for sent tx confirmed on L1 side information? 
  
  
  If anyone let me know about above information would be appreciated. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Specs:**
 - OS:
 - Package Version (or commit hash):

**Additional context**

**Comment by smartcontracts** [comment]
Some answers for you:

> l1fee is l1GasPrice multiply l1GasUsed??

Yes, `l1Fee` is computed as `l1GasPrice` multiplied by `l1GasUsed`.

> and what is l1FeeScalar stands for?

`l1FeeScalar` is an additional multiplier that is added to the actual L1 gas used to account for dynamic costs on L1. Currently this value is set to 1, so it has no impact on the L1 gas used.

> queueOrigin meant that where tx came from ?

`queueOrigin` is either `sequencer` or `l1`. Transactions sent directly to the sequencer will have a value of `sequencer` while transactions that were created as L1 to L2 messages will have a value of `l1`.

> what for l1TxOrigin?

`l1TxOrigin` applies only for L1 to L2 messages and olds the address that sent the message to L2.

> l1BlockNumber & l1Timstamp stand for sent tx confirmed on L1 side information?

`l1BlockNumber` and `l1Timestamp` tell you the timestamp and block number on L1 when the transaction was processed.
