### ISSUE TITLE
Contract selfdestructs and sends the remaining balance to itself

### ISSUE THREAD

**Issue by SomethingFromNothing** [ethereum-optimism/optimism#4771]
Describe the bug
I have found that if a contract self-destructs and sends the remaining balance to itself, that balance remains in the contract after it is destroyed. Behavior of the EVM, in this case leaves the contract with a zero balance, this is different. Destroying some of the ether balance.

To Reproduce

Deploy a contract that has some function which selfdestructs the contract sending remaining balance to itself. eg:
```
contract testSelfdestructs {
    constructor() payable {
      testSelfdestructs (payable(address(this)));
    }
}
```
Expand this contract and perform the operation.
contract balance should be 0

**Comment by smartcontracts** [comment]
This a known issue and will be resolved as part of the Bedrock release: https://github.com/ethereum-optimism/optimism/issues/2604
