### ISSUE TITLE
Current Optimism L2 devnet setup only supports up to 20 TPS

### ISSUE THREAD

**Issue by crypto-matto** [ethereum-optimism/optimism#4792]
**Is your feature request related to a problem? Please describe.**
Hi dev team,

I’ve setup 1 node for L1 and 1 node for L2 on 2 separate machines. I'm benchmarking the nodes by blasting a range of TPS to see their behaviors. I found some unexpected behaviors and would like to ask for advices. 🙌 

```
Spec of the node running L1:
CPU: 8 core (ARM64)
RAM memory: 6GM
Storage: 80GB

Spec of the node running L2:
CPU: 4 core (x64)
RAM memory: 6GM
Storage: 80GB

Configs:
GasLimit: 1000000
GasPrice: 5000000000000
```

### Findings
- L2 TPS is around 20 TPS only, while L1 TPS tolerance can go as high as 27 TPS. 
- Each CPU core usage under tx blasting are within 50% until TPS above certain level. RAM Memory usage seems not a big deal as its usage is pretty much same as when the node is in idle. Therefore, we're thinking whether the CPU is the main hardware bottleneck or not. 
- Above its highest TPS it could sustain (27TPS on L1, 20TPS on L2), let’s say I tried with blasting with a 50 TPS, L1 becomes unresponsive to most of the broadcasted transactions. The result drops to single digit, like less than 5 TPS. L2 may still sustain a 10+ TPS under similar circumstances.

### Things we’d like to know
- Am I using a proper `GasLimit` & `GasPrice`? What would you suggest to facilitate with L2 Optimism?
- Is it normal & why is there a significant drop in TPS under high traffic?

Thanks.

**Describe the solution you'd like**
Looking for advices to increase the L2 TPS tolerance, e.g. 500+ TPS. Any optimizations ranging from Hardware, config setup, deployment environment, etc. 

**Describe alternatives you've considered**

**Additional context**

**Comment by tynes** [comment]
Its not very meaningful to benchmark something without making it reproducible. Are you running bedrock or legacy? Are you using the legacy `ops` setup that uses hardhat as the L1? Also you shouldn't benchmark in TPS because not all transactions are created equally, you should benchmark in gas per second.

If you'd like to contribute to the Optimism Collective, please start a thread at https://gov.optimism.io/

**Comment by crypto-matto** [comment]
Hi @tynes ,
> Are you running bedrock or legacy? 

Yes I'm using legacy. I revise the original `ops` setup, breaks the original `docker-compose.yml` down into 2 so that I may deploy on 2 separate machines: 
`docker-compose-l1.yml`: L1 & indexing services
`docker-compose-l2.yml`: L2 & all other services

> Are you using the legacy ops setup that uses hardhat as the L1?
The L1 isn't running on hardhat, as I use my own image, which is running a real EVM client.

> Also you shouldn't benchmark in TPS because not all transactions are created equally, you should benchmark in gas per second
That is a new point to me 👍🏻 I tried to blast a bunch of identical transfer transactions with the same `value`, `gasPrice` & `gasLimit`. 

> If you'd like to contribute to the Optimism Collective, please start a thread at https://gov.optimism.io/

I'll check it out.

**Comment by tynes** [comment]
I recommend using `ops-bedrock` over `ops`

Reopen if you have any issues
