### ISSUE TITLE
Stop syncing

### ISSUE THREAD

**Issue by 0xsShady** [ethereum-optimism/optimism#4818]
Hi! I've been trying to sync my replica node and it seems that it was working properly (even though I've been syncing for 3-4 days already) but now suddently an error araises:

simple-optimism-node-l2geth-1 | ERROR[02-01|11:30:29.717] Mismatched transaction                   index=31245290
simple-optimism-node-l2geth-1 | ERROR[02-01|11:30:29.717] Mismatched transaction                   index=31245291
simple-optimism-node-l2geth-1 | ERROR[02-01|11:30:29.717] Mismatched transaction                   index=31245292
simple-optimism-node-l2geth-1 | DEBUG[02-01|11:30:29.717] Historical transaction matches           index=31245293 hash=0xd45dbe4bb11ebf6abafd40bc7a152b8732e5d4c0bbf001aacef3cdd98cbc90d7
simple-optimism-node-l2geth-1 | DEBUG[02-01|11:30:29.717] Applying transaction to tip              index=31245294 hash=0x58366777b8df7ffc318b2a91685b2f92285d12aadfb02fea9e6dea55a643faf2 origin=sequencer
simple-optimism-node-l2geth-1 | DEBUG[02-01|11:30:29.717] Attempting to commit rollup transaction  hash=0x58366777b8df7ffc318b2a91685b2f92285d12aadfb02fea9e6dea55a643faf2
simple-optimism-node-l2geth-1 | ERROR[02-01|11:30:29.718] Problem committing transaction           msg="nonce too high"
simple-optimism-node-l2geth-1 | ERROR[02-01|11:30:29.718] Got error waiting for transaction to be added to chain msg="nonce too high"
simple-optimism-node-l2geth-1 | ERROR[02-01|11:30:29.718] Could not verify                         error="Verifier cannot sync transaction batches to tip: Cannot sync transaction batches to tip: Cannot sync batches: cannot apply batched transaction: Cannot apply batched transaction: nonce too high"
simple-optimism-node-l2geth-1 | INFO [02-01|11:30:30.711] Syncing transaction batch range          start=221001 end=511186
simple-optimism-node-l2geth-1 | DEBUG[02-01|11:30:30.711] Fetching transaction batch               index=221001
simple-optimism-node-l2geth-1 | ERROR[02-01|11:30:30.718] Mismatched transaction                   index=31245288
simple-optimism-node-l2geth-1 | ERROR[02-01|11:30:30.718] Mismatched transaction                   index=31245289
simple-optimism-node-l2geth-1 | ERROR[02-01|11:30:30.718] Mismatched transaction                   index=31245290
simple-optimism-node-l2geth-1 | ERROR[02-01|11:30:30.718] Mismatched transaction                   index=31245291
simple-optimism-node-l2geth-1 | ERROR[02-01|11:30:30.718] Mismatched transaction                   index=31245292
simple-optimism-node-l2geth-1 | DEBUG[02-01|11:30:30.718] Historical transaction matches           index=31245293 hash=0xd45dbe4bb11ebf6abafd40bc7a152b8732e5d4c0bbf001aacef3cdd98cbc90d7
simple-optimism-node-l2geth-1 | DEBUG[02-01|11:30:30.718] Applying transaction to tip              index=31245294 hash=0x58366777b8df7ffc318b2a91685b2f92285d12aadfb02fea9e6dea55a643faf2 origin=sequencer
simple-optimism-node-l2geth-1 | DEBUG[02-01|11:30:30.718] Attempting to commit rollup transaction  hash=0x58366777b8df7ffc318b2a91685b2f92285d12aadfb02fea9e6dea55a643faf2
simple-optimism-node-l2geth-1 | ERROR[02-01|11:30:30.719] Problem committing transaction           msg="nonce too high"
simple-optimism-node-l2geth-1 | ERROR[02-01|11:30:30.719] Got error waiting for transaction to be added to chain msg="nonce too high"
simple-optimism-node-l2geth-1 | ERROR[02-01|11:30:30.719] Could not verify                         error="Verifier cannot sync transaction batches to tip: Cannot sync transaction batches to tip: Cannot sync batches: cannot apply batched transaction: Cannot apply batched transaction: nonce too high"

Can anyone help me?

Thanks!

**Comment by 0xsShady** [comment]
alo?:D

**Comment by smartcontracts** [comment]
You may need to `debug_setHead` to before the failure and attempt to resync from there. This is an annoying issue that happens occasionally when l2geth doesn't shut down cleanly. It's fixed in Bedrock but will continue to be an issue in the legacy node until we upgrade to Bedrock next month.

**Comment by 0xsShady** [comment]
> You may need to `debug_setHead` to before the failure and attempt to resync from there. This is an annoying issue that happens occasionally when l2geth doesn't shut down cleanly. It's fixed in Bedrock but will continue to be an issue in the legacy node until we upgrade to Bedrock next month.

Thanks for your reply! 

How can I set the "debug_setHead" ?:)

Regards

**Comment by smartcontracts** [comment]
It's a debug RPC endpoint: https://etclabscore.github.io/core-geth/JSON-RPC-API/modules/debug/#debug_sethead

You should be able to use the endpoint if you have the `debug` namespace enabled on your node. You would want to set the head to a block maybe 100k blocks behind where you currently are and restart the node.

**Comment by smartcontracts** [comment]
Ahhh it's `Mismatched transaction index` again... ok I need to finally figure out what's causing this issue. Such a nuisance.

**Comment by 0xsShady** [comment]
yep...it's really annoying because i was almost sync (it lasted like 5 days) and then that appeared :(

**Comment by 0xsShady** [comment]
okay! thanks for the reply !

**Comment by zhy827827** [comment]
hello. @0xsShady  How do you solve this issues??
