### ISSUE TITLE
Geth RPC does not return revert reason when transaction reverts

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#484]
**Describe the bug**
When testing for whether an OVM-based transaction will revert, the transaction will revert without the expected error message being thrown. Instead, the following error message is returned from L2 geth.

**To Reproduce**
1. Git clone [Waffle](https://github.com/ethereum-optimism/Waffle-ERC20-Example) or [Truffle](https://github.com/ethereum-optimism/Truffle-ERC20-Example) repository
2. Yarn install, yarn compile for the OVM, and run tests
4. For Waffle, see _all but_ the last 2 reversion tests pass, and for Truffle, see no tests pass since contract deployment fails with `insufficient gas` error.

**Expected behavior**
If the transaction fails, L2 geth should get the revert reason returned from the contract instead of throwing an estimate gas error.

**Screenshots**
<img width="923" alt="Screen Shot 2021-04-17 at 7 59 58 PM" src="https://user-images.githubusercontent.com/37757724/115132724-41bb4680-9fc8-11eb-82d0-dabdfbf5e238.png">

**Comment by snario** [comment]
I think this is a duplicate issue with https://github.com/ethereum-optimism/optimism/issues/474?
