### ISSUE TITLE
Split apart large integration tests logs files on Github Actions

### ISSUE THREAD

**Issue by snario** [ethereum-optimism/optimism#485]
In the `optimism-integration` repo, [we added code to do some parsing on the output of `docker-compose up`](https://github.com/ethereum-optimism/optimism-integration/commit/2194477e68d2c8baeb9cf56aeb8bcbca883a209c) such that the logs from running many services were more easily parseable and [accessible from Github Actions](https://github.com/ethereum-optimism/optimism-integration/commit/f07118bc3b39dc53abc48d5e01f95bb43f9004d4). I think we should revisit this work and port it for use in this repository.

**Comment by gakonst** [comment]
Why would we want to view logs on CI? You can view the logs locally by running `docker-compose logs --follow <name of service>`

**Comment by snario** [comment]
> Why would we want to view logs on CI? You can view the logs locally by running `docker-compose logs --follow <name of service>`

I find that it makes it much easier to demonstrate the circumstances that lead to failing test cases in a way that can be linked to over the internet. 

This means I can parse through the logs without having to do any local configuration and develop an intuition for a bug. 

It also removes all possibility of some local development quirk leading to a false positive bug report or reproduction steps. 

Also, when trying to demonstrate a successful example of something working when someone is unsure about it, I can link to an exact snippet of the logs demonstrating some functionality.

In general I'd say viewing CI logs improves a developer team's productivity.

**Comment by snario** [comment]
Fixed by #1020 and #1098
