### ISSUE TITLE
Batch submitter miscalculates gas costs sometimes

### ISSUE THREAD

**Issue by snario** [ethereum-optimism/optimism#486]
This is just an observation of a phenomenon I'm seeing right now. See [here](https://etherscan.io/txs?a=0xfd7d4de366850c08ee2cba32d851385a3071ec8d&f=1) for a list of failed transactions by the batch submitter on mainnet and [here](https://kovan.etherscan.io/txs?a=0xfd7d4de366850c08ee2cba32d851385a3071ec8d&f=1) for a similar list on Kovan. 

We ought to investigate this further.

**Comment by smartcontracts** [comment]
No longer relevant, Go batch submitter handles this mostly correctly.
