### ISSUE TITLE
Optimism Bridge Issue(L1<->L2)

### ISSUE THREAD

**Issue by fsl-kyungmin** [ethereum-optimism/optimism#4875]
**Describe the bug**
Can Send Message From L1 to L2
But, Can't Send Message From L2 to L1
I don't know root cause but it's not working

**To Reproduce**
1. Follow This Guide(https://trufflesuite.com/boxes/optimism-bridge/)
 + L1: Geth(Go-Ethereum)
 + L2: Op-Geth(Optimism get image from Dockerhub)

**Expected behavior**
Can Send Message From Both side

**Screenshots**
<img width="711" alt="screenshot" src="https://user-images.githubusercontent.com/121072152/218676827-ca072bdf-9583-4ee9-b9b5-e93e00754b4c.png">

<img width="998" alt="스크린샷 2023-02-14 오후 5 10 13" src="https://user-images.githubusercontent.com/121072152/218676643-6f148dd2-bd20-4d61-a335-61415342676e.png">

**System Specs:**
 - OS: MacOS 13.1(22C65)
 - Package Version (or commit hash):

**Additional context**
Please help me want to solve this problem

**Comment by jackylee0424** [comment]
the tutorial worked for me. did u send 2 followup tx on L1 for finalizing L2 -> L1 withdraw?

**Comment by fsl-kyungmin** [comment]
Umm not yet. how to send followup tx???????? Don't know how to send I just refer this tutorial(https://trufflesuite.com/boxes/optimism-bridge/)

Could you teach me how to send follow tx?? @jackylee0424

**Comment by fsl-kyungmin** [comment]
<img width="635" alt="스크린샷 2023-02-20 오후 1 55 34" src="https://user-images.githubusercontent.com/121072152/220012642-09d2d30a-bb4f-4c2b-bfab-7cc381a0e9ca.png">
I'm testing now, still don't know how to send finalize tx.

**Comment by jackylee0424** [comment]
hi there. you should be able to finalize ur withdraw on L1 with these two steps:
1. `tx = await crossChainMessenger.proveMessage(hash)` - https://github.com/ethereum-optimism/optimism-tutorial/tree/main/cross-dom-comm#optimism-message-to-ethereum-withdrawal
2. `tx = await crossChainMessenger.finalizeMessage(hash)` - https://github.com/ethereum-optimism/optimism-tutorial/tree/main/cross-dom-comm#receive-the-message

**Comment by tynes** [comment]
Try using the devnet with `make devnet-up`
