### ISSUE TITLE
Backwards log in op-node

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#4892]
Log message here is backwards, the config should be treated as the source of truth, not the node you're connected to. I'd also like if the log could be a little more clear about which chain ID is coming from the config and which is coming from the L2 node. Just looking at log there's no way to tell unless you know the structure of the log already. I had to dig through the source to figure this out.

https://github.com/ethereum-optimism/optimism/blob/1e780a398d000bea75954a62d9a67eefa5c652ab/op-node/rollup/types.go#L151

**Comment by Somchai99** [comment]
Goddddd
