### ISSUE TITLE
Distinguish development, test, and prod environment for services

### ISSUE THREAD

**Issue by annieke** [ethereum-optimism/optimism#491]
**Is your feature request related to a problem? Please describe.**
Our services (at least batch-submitter and data-transport-layer) are currently environment agnostic. However, being environment-aware helps us conditionally launch monitoring apps (eg Sentry and prom-client) and send tags to them accordingly.

**Describe the solution you'd like**
Details need to be spiked out, but ideally during application start we can retrieve some variable for which environment the services runs in. We should also be able to tag logs with this environment. 

**Describe alternatives you've considered**
If adding overall environment management is too much of an overhead, we could temporarily use env vars for these services such as `ENABLE_SENTRY=true`

**Additional context**
Currently only related to TypeScript services, but could be extended to other code we run.

**Comment by snario** [comment]
Typically Node processes use `NODE_ENV` to distinguish between `production` and `development`.

**Comment by reubenr0d** [comment]
This seems like a great first issue for me to get started with, so need to modify the startup scripts to specify `NODE_ENV` and enable sentry only if `NODE_ENV==production`? Is there anything else that needs is configured based on the environment? 
Thanks.

**Comment by annieke** [comment]
@reubenr0d that sounds like a good place to start! let me know if you need any help

**Comment by annieke** [comment]
note: we will also want to distinguish goerli and deploy sentry there with 100% trace rate

**Comment by reubenr0d** [comment]
So, please correct me where I am wrong, if I understand right I would need the following changes:
- Add NODE_ENV to .env.examples
- Add NODE_ENV=developement/test to the necessary scripts in package.jsons
- Add another condition before [this](https://github.com/ethereum-optimism/optimism/blob/master/packages/core-utils/src/common/logger.ts#L35) in the logger: `if (NODE_ENV == 'prodcution')`
- Set `traceSampleRate` to 100 [here](https://github.com/ethereum-optimism/optimism/blob/d64b66dbc7c4054a6cc535df0ba70cb43f5a2198/packages/batch-submitter/src/exec/run-batch-submitter.ts#L25) and [here](https://github.com/ethereum-optimism/optimism/blob/d1f264457b606652d0f68e29eddffd482ecda119/packages/data-transport-layer/src/services/server/service.ts#L117)(maye setup a single config var for it), if Goerli, ie. `if(chainIdFlag == 5)` - or is it that we want to set the network based on the environment?
- Add a NODE_ENV to the label for prom-client [here](https://github.com/ethereum-optimism/optimism/blob/795d91437bfcfc5c683d25ea77bb0a39141781de/packages/core-utils/src/base-service.ts#L29).
- Do we also want to enable sentry in any other environments and tag the logs appropriately? Or just keep it enabled on `production`?

Can you please verify? Is there anything else that should be added or any other suggestions ? 
Thanks.

**Comment by annieke** [comment]
@reubenr0d that mostly sounds good! i'd suggest making the first PR smaller (just adding `NODE_ENV` and changing the scripts) so we can merge it faster, then do the rest as followups. are you able to do this in the next 2 days? if not i'll take it over and can find another good first issue for you!

**Comment by reubenr0d** [comment]
I would be a bit held up during the week, @annieke , I think best get started, and I can probably handle some of the followups or look for other issues I can help with over the weekend.
