### ISSUE TITLE
Upgrade the Solidity compiler to simplify pre-deploy contract code

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/optimism#495]
Our predeploys are currently written with an extremely error prone pattern using the `SafeExecutionManagerWrapper`. An example can be found [here](https://github.com/ethereum-optimism/optimism/blob/35b99b07cf9f3e02496783c565b3f82f7fb55fef/packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_DeployerWhitelist.sol#L78-L89):

https://github.com/ethereum-optimism/optimism/blob/35b99b07cf9f3e02496783c565b3f82f7fb55fef/packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_DeployerWhitelist.sol#L78-L89

This (anti) pattern was particularly tricky when [implementing RLP transactions](https://github.com/ethereum-optimism/optimism/issues/496) because we need to compile REVERT and that proved difficult for the RLP contracts. This change is therefore blocking RLP.

**Describe the solution you'd like**
Implement `kall` which allows contracts to call low level execution manager functions when compiled with the normal OVM compiler.

TODO:

- [x] Update `solc` to include `kall` - https://github.com/ethereum-optimism/solidity/pull/22
- [x] Update predeploys to use `kall` and test them in the `integration-tests` vs in the `contracts` package. - https://github.com/ethereum-optimism/optimism/pull/475

**Comment by karlfloersch** [comment]
After doing more debugging it seems this is a bug in the compiler, probably related to `kall`. You can reproduce a relatively simple case by running this integration test:

https://github.com/ethereum-optimism/optimism/blob/d76f0ce33b7e012539fe7839b0acc51c985e56cd/integration-tests/test/rpc.spec.ts#L84-L100

And then observing the L2Geth logs.

@ben-chain is going to look into this

**Comment by ben-chain** [comment]
Closing this completed via:
- https://github.com/ethereum-optimism/solidity/pull/22
- https://github.com/ethereum-optimism/optimism/pull/545
- https://github.com/ethereum-optimism/optimism/pull/546
- https://github.com/ethereum-optimism/optimism/pull/548
- https://github.com/ethereum-optimism/optimism/pull/561/files
