### ISSUE TITLE
Change default transaction encoding to be RLP in order to support value field

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/optimism#496]
**Is your feature request related to a problem? Please describe.**
We currently do not have the ability to send a `value` with our transactions. This was due to a custom encoding format which we implemented which didn't have a `value` field -- that's dumb! Additionally, supporting a custom tx format is annoying for staying 1:1 with eth1.x, especially with the introduction of transaction envelopes. 

Once we've added support for RLP transactions we will be in a much better place with our transaction ingestion logic.

**Describe the solution you'd like**
_Pretty much blocked by_ https://github.com/ethereum-optimism/optimism/issues/495

TODO

- [x] Update `SequencerEntrypoint` to decode RLP transactions instead of custom encoding.
- [x] Update batch submitter to operate on raw transactions
- [x] Change `core-utils` (maybe `data-transport-layer` as well) to use the new RLP encoding format
- [x] Update `l2geth` to encode using RLP, not our custom format.

# In Depth
## Contracts
Implementation: https://github.com/ethereum-optimism/contracts/pull/300/files

Finish and merge this PR.

## Batch Submitter
Implementation: https://github.com/ethereum-optimism/batch-submitter/pull/56

Finish and merge this PR.

## core-utils
Update the encoding which we use here: https://github.com/ethereum-optimism/optimism/blob/master/packages/core-utils/src/coders/ecdsa-coder.ts#L54

Rename this encoding to `EIP155Transaction` because right now it's a weird name "ECDSA transaction" which is not descriptive.

## data transport layer
Re-integrate: https://github.com/ethereum-optimism/data-transport-layer/pull/72

All contain references to old types. We've got to update these.

## l2geth
Remove:
- https://github.com/ethereum-optimism/optimism/blob/41cfbd166e9a1c52a9caf7782662bcda2cc2dd9f/l2geth/internal/ethapi/api.go#L1747

Update:
- https://github.com/ethereum-optimism/optimism/blob/41cfbd166e9a1c52a9caf7782662bcda2cc2dd9f/l2geth/rollup/sync_service.go#L711
- https://github.com/ethereum-optimism/optimism/blob/7e9ca1eb2d1e1665539eaeadfb573a768bb6f601/l2geth/rollup/client.go#L105

**Comment by karlfloersch** [comment]
@gakonst for issues that touch multiple codebases (eg. geth, contracts, & core-utils) should I add labels for all of the relevant components as I did here?

**Comment by gakonst** [comment]
https://github.com/ethereum-optimism/optimism/issues/495 is now merged.
