### ISSUE TITLE
Convert Echidna tests to Forge invariantes

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimism#4980]
We currently have a suite of [Echidna tests](https://github.com/ethereum-optimism/optimism/blob/24edceb652b5a812313b0b742f74acaa0f3ea3a5/packages/contracts-bedrock/contracts/echidna) in our `contracts-bedrock` package which use Echidna for property testing. 

We also have a suite of forge [invariant tests](https://github.com/ethereum-optimism/optimism/blob/24edceb652b5a812313b0b742f74acaa0f3ea3a5/packages/contracts-bedrock/contracts/test/invariants). 

In order to standardize our tooling, we'd like to convert the echidna tests over to Forge invariant tests. External contributors would be very welcome here. 

A suggested workflow would be to open one PR per converted test file: 

- [ ] FuzzAddressAliasing.sol
- [ ] FuzzBurn.sol
- [ ] FuzzEncoding.sol
- [ ] FuzzHashing.sol
- [ ] FuzzOptimismPortal.sol
- [ ] FuzzResourceMetering.sol

The first 4 files listed are much simpler to work with, so I'd suggest starting from the top.

**Comment by Ratimon** [comment]
@maurelian Hi, I think this issue is now resolved, so it might be closed now, or should there be any possible contributions I should make here?

**Comment by maurelian** [comment]
LGTM, thank you so much for your help here!
