### ISSUE TITLE
Improve L1 Contract Upgradability 

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/optimism#499]
**Is your feature request related to a problem? Please describe.**
In https://github.com/ethereum-optimism/optimism/issues/498 we implement the new deployment system (code name `chugsplash`) that automates / simplifies much of our upgrade process in L2. In order to avoid having two totally different deployment systems, one for L1 contracts & one for L2 contracts, we need to add an L1 backend for our new deployer.

**Describe the solution you'd like**
Add delegate proxies in front of all of our L1 contracts, and then use the exact same flow defined here: https://github.com/ethereum-optimism/optimism/issues/498 but for L1 contract upgrades.

TODO:
- [ ] Migrate all L1 contracts to use upgradable proxies.
  - These proxies must expose `setCode` and `setStorage` as well as `pause` which pauses the contracts during an upgrade
- [ ] Modify the "chugsplash" tooling to use the same deployment API that we use on L2
  - [ ] Write an L1 `UpgradeExecutor` which calls `setCode` & `setStorage` on all of our L1 proxies
- [ ] Ensure all of the tooling that we build for L2 works well during an L1 upgrade as well.

**Comment by smartcontracts** [comment]
I think this ticket is a bit too vague and is going to end up sitting here for a really long time without much movement. I'd rather we represent these sort of "epic" tickets separately.

**Comment by karlfloersch** [comment]
Closing because it's too vague & is the same as a major project of ours. This should be a project charter.
