### ISSUE TITLE
`solidity-gas-reporter` shows ~400k gas usage for an empty function call

### ISSUE THREAD

**Issue by TransmissionsDev** [ethereum-optimism/optimism#504]
**Describe the bug**
Calling an empty function takes up 400k gas units (according to solidity-gas-reporter) when interacting with l2geth

**To Reproduce**
See this reproduction branch: https://github.com/Rari-Capital/nova/tree/reproCaseForEmptyFunctionGasUsage

Can also view this run of CI which shows the crazy high gas usage in the "Run tests" section: https://github.com/Rari-Capital/nova/runs/2386486739

<img width="827" alt="Screen Shot 2021-04-19 at 6 40 28 PM" src="https://user-images.githubusercontent.com/26209401/115324429-b7492300-a13e-11eb-96ba-be32098ab3b8.png">

**Expected behavior**
I don't think a simple empty call like this is meant to take up this much gas.

**Comment by snario** [comment]
We're working on better gas metering right now which will give a much better analysis for this kind of thing.

**Comment by TransmissionsDev** [comment]
![Screen Shot 2021-05-05 at 9 06 13 PM](https://user-images.githubusercontent.com/26209401/117240514-d81fa280-ade5-11eb-8190-e0f4a052eed1.png)
I don't think an ERC20 approve should take 500k gas either...

**Comment by snario** [comment]
cc @elenadimitrova as well who has recently added automated gas reporting: https://github.com/ethereum-optimism/optimism/pull/603/checks?check_run_id=2511987843

**Comment by snario** [comment]
@TransmissionsDev there is a constant value overhead of about 400k L2 gas right now. We'll add more information about this in the docs shortly.

**Comment by TransmissionsDev** [comment]
> @TransmissionsDev there is a constant value overhead of about 400k L2 gas right now. We'll add more information about this in the docs shortly.

Does this apply to enqueue'd transactions? If so, should seriously consider removing the fractional gas payment entirely imo (or lower the divisor)
