### ISSUE TITLE
Migration have error expected storage slots

### ISSUE THREAD

**Issue by hungzinza** [ethereum-optimism/optimism#5048]
**Describe the bug**
My test-node was stopped at height 4,061,223
Network: goerli
I run bedrock-init to upgrade it.
I enable flag: `no-check` when run command 
  ```
./bin/op-migrate \
    --l1-rpc-url $OP_NODE__RPC_ENDPOINT \
    --ovm-addresses $WITNESS_OUT_PATH/data/ovm-addresses.json \
    --evm-addresses $WITNESS_OUT_PATH/data/evm-addresses.json \
    --ovm-messages $WITNESS_OUT_PATH/data/ovm-messages.json \
    --evm-messages $WITNESS_OUT_PATH/data/evm-messages.json \
    --ovm-allowances $WITNESS_OUT_PATH/data/ovm-allowances.json \
    --network $ETH_NETWORK \
    --no-check \
    --deploy-config ../packages/contracts-bedrock/deploy-config/$ETH_NETWORK.json \
    --rollup-config-out ../packages/contracts-bedrock/deploy-config/$ETH_NETWORK.json \
    --hardhat-deployments ../packages/contracts-bedrock/deployments,../packages/contracts/deployments,../packages/contracts-periphery/deployments \
    --db-path $LEGACY_GETH_COPY_DIR
```
I have an error:
`expected 6 storage slots for L2CrossDomainMessenger but got 4`

![Screenshot from 2023-03-03 11-53-07](https://user-images.githubusercontent.com/96384818/222634626-88cd2ee3-287a-42d2-8883-f2e8791f725e.png)

**System Specs:**
I use latest version of this repo: https://github.com/smartcontracts/simple-optimism-node

**Additional context**

**Comment by NatLukcrypto** [comment]
interesting

**Comment by hungzinza** [comment]
Hi @NatLukcrypto, Could you help me check it? I'm stuck at this error for a long time

**Comment by tynes** [comment]
This is a known bug based on changes to the cross domain messenger, fixes are incoming

**Comment by hungzinza** [comment]
@tyne
I'm waiting for it. Thank you
