### ISSUE TITLE
FXS token deposit stuck

### ISSUE THREAD

**Issue by quantbrothers** [ethereum-optimism/optimism#5049]
**Describe the bug**
I have a transaction of FXS token deposit from MainNet to Optimism network
And this deposit still not received

**To Reproduce**
This is the transaction on MainNet
0xcfd53e1df2a095739fd87952f2b0cff163d04e0dd093c0bea508e9e2e8ee3d39

**Expected behavior**
Expected receive after 20min but almost 9 hours passed

**Comment by zainbacchus** [comment]
Hi @quantbrothers 

You can see your failed deposit here: https://optimistic.etherscan.io/tx/0x06f9caf63e103e5be8d23ac22bf3f94d64e55c9d16b7cf2575097e95e67e07f5#eventlog

If a user tries to deposit a token to Optimism from L1 with the wrong parameters then the deposit will fail on L2 and the bridge contracts will automatically send the funds back to L1.

You can get your deposit back by using the relayer: https://optimistic.etherscan.io/messagerelayer?search=0x06f9caf63e103e5be8d23ac22bf3f94d64e55c9d16b7cf2575097e95e67e07f5

**Comment by quantbrothers** [comment]
![image](https://user-images.githubusercontent.com/443938/223093941-b19b3fe7-5d11-4d27-8de1-f55fbaa14eaf.png)
When i clicked 'Execute' transaction did not sent. I see 'undefined'

**Comment by smartcontracts** [comment]
Hi @quantbrothers please make sure you're connected to Ethereum Mainnet and not Optimism Mainnet when trying to execute.

**Comment by quantbrothers** [comment]
Yes, i am sure i was connected to MainNet

**Comment by quantbrothers** [comment]
But now works! thank you
