### ISSUE TITLE
Differentiating between `eth_call` and not

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#506]
**Describe the bug**
There are sometimes situations in which we want code to conditionally run in the state transition code path. An example is that we do not want to actually write to the `diffdb` during an `eth_call`. We currently handle this case by looking for the `evm.Context.EthCallSender`, but things like `debug_traceBlockByNumber` do not set the `EthCallSender`. We need a better way to specify that a particular EVM execution is not meant to have actual side effects or make the side effects as part of a post processing stage.

**To Reproduce**
Sync a replica using the script: https://github.com/ethereum-optimism/optimism/issues/473

```bash
$ curl -X POST \
    --data '{"jsonrpc": "2.0", "method": "debug_traceBlockByNumber", "params": ["0x18", {"tracer": "callTracer"}], "id": 1}' \
    -H "Content-Type: application/json" http://localhost:8045
```

This results in the logs:
```
ERROR[04-19|18:24:36.209] Cannot set diff key                      err="DiffDB not set"
ERROR[04-19|18:24:36.216] Cannot set diff key                      err="DiffDB not set"
ERROR[04-19|18:24:36.223] Cannot set diff key                      err="DiffDB not set"
ERROR[04-19|18:24:36.230] Cannot set diff key                      err="DiffDB not set"
ERROR[04-19|18:24:36.237] Cannot set diff key                      err="DiffDB not set"
ERROR[04-19|18:24:36.244] Cannot set diff key                      err="DiffDB not set"
ERROR[04-19|18:24:36.257] Cannot set diff key                      err="DiffDB not set"
```

**Expected behavior**
No error logs when doing a `debug_traceBlockByNumber`

**Comment by snario** [comment]
Why does this error manifest as something _we_ need to fix? Is it handled in upstream `geth`?

**Comment by smartcontracts** [comment]
We no longer spam logs like this, so I think we're fine to close.
