### ISSUE TITLE
[go package] missing required field 'gasPrice' for txdata while calling BlockByNumber function

### ISSUE THREAD

**Issue by GraceFNR** [ethereum-optimism/optimism#5079]
**Describe the bug**
Hello, while i'm using golang package and call BlockByNumber function, it occurs an error called "missing required field 'gasPrice' for txdata". It seems like in bedrock version, we do not have gasPrice but effectiveGasPrice in txdata.

go package version:
github.com/ethereum-optimism/optimism/l2geth v0.0.0-20230308033043-83b6312df7a5
rpc:
https://opt-goerli.g.alchemy.com/v2/{apikey}

**Expected behavior**
BlockByNumber function runs correctly.

**System Specs:**
 - OS: mac os
 - Package Version (or commit hash): github.com/ethereum-optimism/optimism/l2geth v0.0.0-20230308033043-83b6312df7a5
 - https://pkg.go.dev/github.com/ethereum-optimism/optimism/l2geth?tab=versions

**Comment by ajsutton** [comment]
gasPrice is present for normal L2 transactions, but was previously absent from deposit transactions in bedrock. The next version of op-geth will include gasPrice as 0 for deposit transactions to improve compatibility with existing tools that expect all transactions to have this field.  It was added in https://github.com/ethereum-optimism/op-geth/pull/48
