### ISSUE TITLE
debug_traceTransactions are overloading the node

### ISSUE THREAD

**Issue by fmira21** [ethereum-optimism/optimism#5096]
Hi guys!

I am maintaining an archive Dockerised Optimism node, and my service needs to poll it with `debug_traceTransaction` calls.
When I try to poll the node, it gets out of sync and remains about 300 blocks behind the tip. Moreover, about 3 out of 10 calls themselves are timed out.
I know that this call is quite heavy. 
Will Bedrock fix this? Is there any workaround so far?

Thank you in advance!

**Comment by smartcontracts** [comment]
Yeah Bedrock fixes this. Unfortunately the lift required to fix this for the legacy node isn't worth it since Bedrock is around the corner. We may revisit this for legacy nodes down the line.

**Comment by fmira21** [comment]
@smartcontracts 
Thank you for the answer!
In this case, I will be waiting for the hardfork.
Do you have assumptions when it may take place?

**Comment by smartcontracts** [comment]
It will likely take place next month
