### ISSUE TITLE
devnet does not initialize the liquidity pool of OptimismPortal

### ISSUE THREAD

**Issue by brew0722** [ethereum-optimism/optimism#5118]
**Is your feature request related to a problem? Please describe.**
This is not a bug report.

However, it seems to be a bit of a headache for beginners trying to understand the Optimism structure based on `devnet`.
During devnet's initialization, it doesn't initialize a sufficient liquidity pool for the `OptimismPortal`, causing `withdraw` to fail when running the bridge tutorials provided [here](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/cross-dom-bridge-eth).

More little detail, If the liquidity pool of `OptimismPortal` is insufficient, the process of making a payable call to `relayMessage` of `L1CrossDomainMessenger` will fail.
However, `OptimismPortal` uses `safecall` to ignore the revert and raise an event, making it very difficult to determine the cause of the failure.

Please consider initializing the liquidity pool from devnet though.
https://github.com/ethereum-optimism/optimism/blob/35d4a37c2b9a59e9bf16fa4c5e22283f2348c3d2/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L373

**Comment by tynes** [comment]
You should do some deposits to put eth in the portal

**Comment by brew0722** [comment]
Yes, but in the example provided in the tutorial, deposits are smaller than withdrawals.
https://github.com/ethereum-optimism/optimism-tutorial/blob/d4f521ce1cc806c0820eaee9f8b8f3984faffb66/cross-dom-bridge-eth/index.js#L72
https://github.com/ethereum-optimism/optimism-tutorial/blob/d4f521ce1cc806c0820eaee9f8b8f3984faffb66/cross-dom-bridge-eth/index.js#L94

However, the test account used as an example sets a very large L1/L2 balance at devnet initialization.
https://github.com/ethereum-optimism/optimism-tutorial/blob/d4f521ce1cc806c0820eaee9f8b8f3984faffb66/cross-dom-bridge-eth/.env.example#L2

So it should be able to run even if the deposits are smaller than the withdrawals in the first place.

If don't have any balances on devnet L2, we're going to be bridging from L1 anyway, so it makes sense. 
However, This behavior is caused by the fact that devnet is also funding the test account on L2, but not the bridge pool.

**Comment by tynes** [comment]
Not fixing this, perhaps the guide should be updated to ensure that its not undercollateralized
