### ISSUE TITLE
Migrate legacy data but error: no migrated slot found for legacy slot

### ISSUE THREAD

**Issue by hungzinza** [ethereum-optimism/optimism#5130]
**Describe the bug**
I had a node on goerli network and it was stuck at bedrock event.

I used repository https://github.com/smartcontracts/simple-optimism-node to migrate my legacy data, but It has error:

`CRIT [03-14|02:19:51.385] error in migration err="error checking storage slots: no migrated slot found for legacy slot 0x66d0e64c572504a1bdcd6fbc980665db787d816aba72b35278ed61082d8894cf"`

![Screenshot from 2023-03-14 13-11-13](https://user-images.githubusercontent.com/96384818/224920365-fefc74ca-662b-41a6-a2ac-8e4226c4ca72.png)

Please check it. Thanh you.

**Comment by tynes** [comment]
This should work now if you use the latest data
