### ISSUE TITLE
Propose bulk proposing feature.

### ISSUE THREAD

**Issue by egonspace** [ethereum-optimism/optimism#5131]
**Is your feature request related to a problem? Please describe.**

I am practicing building a private local L2 chain using Optimism. While doing so, I experienced that if the proposer is down for some reason for a few hours, it takes too long to propose up to the latest L2 block when it is run later. This is due to the fixed value of the SUBMISSION_INTERVAL setting in the `L2OutputOracle` contract. In other words, only a certain number of L2 blocks can be uploaded at a given time, and if the proposer is down for a while, it takes too long to upload the Output root to the latest block after restarting, which poses a significant problem for processing bridge tx during this time. 

Of course, we should pay attention to preventing the proposer from shutting down, but to prepare for various failure scenarios, it seems necessary to have the ability for proposer to upload Output root in bulk. 

For example, a function similar to `L2OutputOralce.proposeL2Output` could be `proposeL2OutputBulk`, where we can provide a long L2 block root as input, wouldn't that be nice?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tynes** [comment]
I think that the fix here is to make the `op-proposer` submit transactions faster. You could also set the proposer account to an ownable multicall and then update the batcher to call the multicall

**Comment by tynes** [comment]
You can find a multicall implementation here: https://github.com/mds1/multicall

There is no fix right now unfortunately. Going to close this issue as its not something we are going to build
