### ISSUE TITLE
Account for zero vs non-zero calldata bytes for L2 gas estimation

### ISSUE THREAD

**Issue by K-Ho** [ethereum-optimism/optimism#515]
**Describe the bug**
Current Fee estimation logic: https://github.com/ethereum-optimism/optimism/blob/41cfbd166e9a1c52a9caf7782662bcda2cc2dd9f/l2geth/core/rollup_fee.go#L16-L19

Rather than logic being `gasPrice * dataLen + executionPrice * gasUsed`, logic should be:
`gasPrice * (4*zeroDataBytes + 16*nonZeroDataBytes + nonCallDataL1GasOverhead) + executionPrice * gasUsed`

1. dataPrice is currently the L1 gas price, not the price per byte of data. Non-zero data bytes cost 16 gas and zero data bytes cost 4 gas. We must iterate through the data, count # of zero, non-zero bytes, then calculate the cost.
2. There is currently a non-calldata per tx overhead for batch submission. The naive solution is to have this parameterizable in the config. Ideally we can query the L1 CTC to find a running average of the tx batch size and use that to parameterize this added cost.

Non calldata cost per tx (Assuming each tx has its own batch context): 

**Batches of 10 txs**:
9145 gas per tx

**Batches of 50 txs:** 
5253 gas per tx

**Batches of 200 txs:**
2661 gas per tx

**Comment by gakonst** [comment]
Regarding the zero/non-zero bytes, agreed. 

The `nonCallDataL1GasOverhead` seems harder to properly price since the overhead varies depending on the number of transactions batched, and we cannot know that when the user submits their transaction?

**Comment by tynes** [comment]
Perhaps we have a target batch size and assume that? Ideally the `nonCallDataL1GasOverhead` is configurable at runtime or potentially via IPC. This is related to https://github.com/ethereum-optimism/optimism/issues/528, we need a longer term and more scalable way of doing fees.

I thought it would be interesting to put some of the information about fees in the state (L1 or L2), assuming that its ok to require that the user has a fully synced node before sending transactions, but I think thats a fine assumption to make in the Ethereum ecosystem. Then users wouldn't need to call out to a centralized place for fee estimation. Perhaps the `BASEFEE` opcode would be useful
