### ISSUE TITLE
common-ts unit test failed

### ISSUE THREAD

**Issue by dandan2095op** [ethereum-optimism/optimism#5214]
**Describe the bug**
common-ts unit test failed with TypeError: src_1.Metrics is not a constructor

```shell
~/code/optimism/packages/common-ts$ yarn test
yarn run v1.22.19
$ ts-mocha test/*.spec.ts


  Metrics
    1) shoud serve metrics


  0 passing (13ms)
  1 failing

  1) Metrics
       shoud serve metrics:
     TypeError: src_1.Metrics is not a constructor
      at Context.<anonymous> (test/metrics.spec.ts:10:21)
      at processImmediate (node:internal/timers:466:21)



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
1. Go to 'packages/common-ts'
2. run 'yarn test'
3. See error

**Expected behavior**
Unit tests run successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/105788743/226528544-7f1c0552-d067-4597-98ce-1aedf61148b6.png)

**System Specs:**
 - OS: Linux Ubuntu
 - Package Version (or commit hash): 7d0c54cdb2c7887d69093bf0427d30ae42017b61

**Comment by dandan2095op** [comment]
> Confirmed! Thank you for the report. Opened a PR to fix.

Thanks, unit tests are running now. 
FYI, I think you should add Go in the dependencies list. https://github.com/ethereum-optimism/optimism/blob/develop/CONTRIBUTING.md#dependencies

**Comment by dandan2095op** [comment]
Hi @smartcontracts , there are still 3 unit tests failing, shall I reopen this issue?
![image](https://user-images.githubusercontent.com/105788743/226802819-eb110b90-69c8-4039-8269-30b636a2b668.png)

**Comment by smartcontracts** [comment]
@dandan2095op could you open a new issue for that?

**Comment by dandan2095op** [comment]
> @dandan2095op could you open a new issue for that?

sure
