### ISSUE TITLE
Stop synchronization

### ISSUE THREAD

**Issue by dg123lzk** [ethereum-optimism/optimism#5216]
The node stopped synchronizing at 19913924 block height

+++ cast call 0xcbebc5ba53ff12165239cbb3d310fda2236d6ad2 'config(address,string)(string)' 0x68108902De3A5031197a6eB3b74b3b033e8E8e4d bedrock/mainnet/ready --rpc-url https://goerli.infura.io/v3/84842078b09946638c03157f83405213
++ echo ''
+ BEDROCK_FLAG=
+ '[' '' == true ']'
+ echo 'Bedrock flag not set, waiting...'
Bedrock flag not set, waiting...

Waiting for Bedrock node to initialize...
Waiting for Bedrock node to initialize...
Waiting for Bedrock node to initialize...
Waiting for Bedrock node to initialize...
Waiting for Bedrock node to initialize...
Waiting for Bedrock node to initialize...
Waiting for Bedrock node to initialize...
Waiting for Bedrock node to initialize...
Waiting for Bedrock node to initialize...

**Comment by smartcontracts** [comment]
Hi, would you mind transferring this issue over to https://github.com/smartcontracts/simple-optimism-node?
