### ISSUE TITLE
Incorrect Error Message: Invalid Deposit Event -> Invalid System Config Update Event

### ISSUE THREAD

**Issue by sam-iamm** [ethereum-optimism/optimism#5272]
https://github.com/ethereum-optimism/optimism/blob/a70a4e3e130c2c8ae54d72f6a0baca6927d252ae/op-node/rollup/derive/system_config.go#L73

this line references the deposit event instead of the config update event. this is simply an error message, and does not effect control flow logic, but it could confuse developers debugging errors in the future.

**Comment by smartcontracts** [comment]
Good catch. Easy first issue for someone to tackle.

**Comment by Karthik-Gupta** [comment]
Fix for this is merged part of PR https://github.com/ethereum-optimism/optimism/pull/5302
