### ISSUE TITLE
Propose a slower L2 compared to L1

### ISSUE THREAD

**Issue by egonspace** [ethereum-optimism/optimism#5275]
**Is your feature request related to a problem? Please describe.**

Hello. We are a team looking to build our own L2 chain using Optimism. The biggest obstacle in building L2 right now is the fee cost of the Batcher. So, we are considering an L3 that looks at L2. The problem is that since the block time of L2(Optimism mainnet or Base testnet? mainnet?) is 2 seconds, L3 can only have a maximum block time of 2 seconds as well, which means the cost of L3's batcher is not insignificant. What we want is to build an L3 that is slower than the L2 block time. For example, we would like to build an L3 with a 12-second block time on an L2 with a 2-second block time. It seems structurally possible, but the current implementation of Optimism seems to make it impossible. If such a proposal is valid, our team would like to try implementing it. Are you willing to include such a proposal in the Optimism code?

I apologize in advance if this sounds completely strange as I am still a beginner with Optimism.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by egonspace** [comment]
Thank you for your positive response.

Regarding your opinion of 4, I have a different thought. The batch submission rate does not seem to have a significant impact on fee cost. Delaying the frequency results in more batch bodies accumulating. The cost of a batch is proportional to the number of transactions accumulated in L2, and it seems unrelated to the rate of batches.

If the congestion on L2 is low, I discovered that the cost of the tx updating `L1Block` contract, which is executed by default for every block, is not negligible. In other words, even if there are no user transactions in L2, it doesn't create an empty block; instead, it includes at least one transaction, which is the `L1Block` update transaction. I cannot be assured if this is an important factor worth paying for. I am analyzing the effects of delaying the update frequency or updating it in bulk.

Any comments on this would be appreciated.

**Comment by egonspace** [comment]
I think we need to slightly modify the concept for this. Currently, the op-node assumes at least one L2 block is created per epoch. It seems that too many changes would be needed to modify this concept, so I've been considering an alternative. What if we don't break the assumption that at least one L2 block is created per epoch, but instead break the assumption that the `L1 block number = the epoch number`? In other words, we would use a subset of L1 instead of the entire L1 set. For example, if we only use L1 blocks where (L1 block number % n) = 0, there wouldn't be a need to modify many concepts in the op-node. By managing the subset set of L1 in the `L1 Traversal` stage, and adding the `epoch parent hash` to the block instead of using the original `parent hash` included in the block, wouldn't it be possible without major conceptual changes?
However, since a batch can be uploaded to any L1 block, it seems that we still need to read all L1 blocks during the derivation process.

**Comment by cifer76** [comment]
just wondering, why 2-second block time L2 makes it's impossible for 12-second time L3?

**Comment by protolambda** [comment]
@cryptocifer it can be done, but requires protocol changes, as the current protocol assumes every L1 block is registered in the L2 chain (this helps a lot with various consistency/safety checks in the block-derivation protocol). Every such registration of L1 data into L2 requires one special top-of-block system transaction, thus requiring one L2 block per L1 block. And for the L2 chain to keep up with the L1 chain, the block-time thus has to be shorter than that of the L1 chain.

**Comment by protolambda** [comment]
Please re-open if you have any questions, I hope the above answer helped explain the L2/L1 block-time constraints.
