### ISSUE TITLE
Replicas do not have a way to get the execution gas price from sequencers

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#528]
The sequencer is ultimately in control of choosing what the fees are. Right now (https://github.com/ethereum-optimism/optimism/pull/519), replicas compute client side what the fee is using the same algorithm as the sequencer. This is not scalable long term as the replicas are unaware of the congestion. A possible work around would be to put information about the congestion into the state. Another solution would be to have all replicas query out to the sequencer, but this is not scalable for the sequencer as it could ddos the node. The proposed solution involves having a single source of truth that lives outside of geth and the replicas that is referenced for the fees.

---

From https://github.com/ethereum-optimism/optimism/pull/557

After some brainstorming about setting the ExecutionPrice longer term, if it is set via IPC then the problem is that it will also need to be set via IPC for all replicas/verifiers at the same time. This is a large coordination problem that adds a lot of overhead, basically if we want to up the fee then we will need to have everybody reconfigure their nodes. Longer term the ExecutionPrice could live in the L2 state. The value could be updated behind an onlySequener modifier and the Sequencer RPC would reject transactions that do not pay a large enough fee. A problem with this approach is that verifiers that listen to L1 will have a lag in updates to the value since they will not see the updates until the transactions are batch submitted. This problem could be mitigated by only allowing fee changes every so many blocks and allowing it to only change by deterministic amounts, but that adds complexity and the problem space should be explored in greater depth. Verifiers will always be at a disadvantage compared to replicas, since replicas sync from the sequencer but there is risk involved since that data isn't technically the source of truth. A malicious sequencer may lie.

Short term we do not need this value to be pulled from the L2 state but we definitely would like it to be pulled from the L2 state before the Uniswap v3 launch. We would be able send transactions to the sequencer that updates the ExecutionPrice from a multisig to make sure the system does not get overwhelmed

**Comment by K-Ho** [comment]
Another concern: Data price for replicas and the sequencer will be queried from different sources (e.g. maybe infura vs. alchemy vs. hosted geth node) This could cause the replica to quote a dataPrice of 100 gwei, whereas the sequencer would have quoted a dataPrice of 150 gwei

One potential solution is that replica DTLs query the dataprice (and executionPrice?) from the sequencer and then replica geth nodes set their execution and data price via their replica DTL

**Comment by tynes** [comment]
>  Data price for replicas and the sequencer will be queried from different sources (e.g. maybe infura vs. alchemy vs. hosted geth node)

I don't think this is that large of a problem. EIP 1559 will help a lot with this. This can be ran experimentally by calling `eth_gasPrice` on Alchemy and Infura and seeing how much they differ over time.

**Comment by gakonst** [comment]
The smart contract based solution sounds good to me. I am OK with having a static EOA/multisig control the execution/data price in the short term, stored in a smart contract, while accessing the value form state directly similarly to how we access OVM-ETH balances. This value would be cached in memory, and we'd have the sync service update it once every some interval.

Longer term, taking into account a multi-sequencer system, we'd want the currently elected sequencer to be the party that can set these values.

**Comment by smartcontracts** [comment]
@tynes is this fixed now with the introduction of `OVM_GasPriceOracle`?

**Comment by smartcontracts** [comment]
Closing after convo with @tynes, should be fixed because of `OVM_GasPriceOracle`
