### ISSUE TITLE
contracts-bedrock: eip 1967 constants in Constants.sol

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#5300]
**Is your feature request related to a problem? Please describe.**
There are multiple places where the EIP 1967 constants are used and they are defined inline multiple times. We should deduplicate the values.

**Describe the solution you'd like**
We should hardcode the constants into `Constants.sol` and then also have unit tests that the values are correct and also import the values from the constants library into all the places where they are used.

**Comment by kamlesh11839** [comment]
Very nice

**Comment by ashutosh887** [comment]
I would like to work on this @fgimenez @tynes if not resolved :)

**Comment by fgimenez** [comment]
hey @ashutosh887 there's an approved PR for this issue here https://github.com/ethereum-optimism/optimism/pull/5329

**Comment by ashutosh887** [comment]
HI @fgimenez 
Is the PR merged?


cc: @tynes 

> hey @ashutosh887 there's an approved PR for this issue here #5329

**Comment by fgimenez** [comment]
nope, not merged

**Comment by Sabnock01** [comment]
Looks like this issue can be closed @tynes
