### ISSUE TITLE
Transactions get stuck for hours (even days) and they never get included on-chain

### ISSUE THREAD

**Issue by dimriou** [ethereum-optimism/optimism#5301]
**Describe the bug**
Over the past few weeks, we’ve encountered an issue on Optimism Goerli. Our transactions are getting stuck for hours (even days) and they never get included on-chain even though the gas values are aligned with the market prices. For example I found one specific tx that has been stuck for at least 12 hours (`0x9c6c7497c33188c2fdb2dfaa019bc5f282f3a111afe2f18fe66a392c01ed9e26`) with  feeCap=6.450009038 gwei while other transactions get included with far less feeCap (i.e. [1 Gwei](https://goerli-optimism.etherscan.io/tx/0x91b593da5c7f88037573f642b0404d79921eb3b9a8b3c3ffdba8d21c66b95ffb)). It would be expected for our transaction not to be included if we only tried once, but we have a retry mechanism that re-sends the same attempt over and over and the response is always that it is already known (classified as [TransactionAlreadyInMempool](https://github.com/smartcontractkit/chainlink/blob/develop/core/chains/evm/client/errors.go#L82) error in our transaction manager). I would assume that eventually a tx that is already in mempool, will be included in a future block at some point, especially if the price is higher than the rest txs. We also utilize at least 2 different RPC endpoints from external providers so the chance of being a provider issue is very low.

**To Reproduce**
This occurs from time to time on CL's nodes deployed on testnet.

**Expected behavior**
We expect transactions that include gas prices close to the market fees, to eventually be included and not stay in mempool for multiple hours.

**Comment by K-Ho** [comment]
In discussion with Chainlink, we've identified that the root cause of this issue was CL getting false confirmations of txs being confirmed, and then sending transactions with future nonces, which then got stuck in the mempool. We believe this should fix the issue that was causing transactions to be treated as confirmed, when they were never actually included by the sequencer:

https://github.com/ethereum-optimism/op-geth/pull/80

**Comment by smartcontracts** [comment]
@K-Ho is this resolved?

**Comment by K-Ho** [comment]
the fix should be included in https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101105.1 , but let us know if the issue goes away @dimriou

**Comment by smartcontracts** [comment]
Going to close but happy to re-open if the issue appears again

**Comment by dimriou** [comment]
Issue seems to have been fixed. Thanks.
