### ISSUE TITLE
Propose an option for not to submit empty batch

### ISSUE THREAD

**Issue by jyeoniii** [ethereum-optimism/optimism#5328]
**Is your feature request related to a problem? Please describe.**

I'm new to Optimism and currently trying to understand how it works. 
If I understand it correctly, current implementation of `op-batcher` always submits the batch even when there is no transaction. If there is no valid batch available for derivation, `op-node` automatically create an empty batch for derivation. Since batcher tx fee is quite a burden for operators, I think we can skip the batcher tx when there is no transaction included in the batch. 
Event though in that case we must wait for SWS to derive the block of that epoch, I think it's quite reasonable if chain operator prefers to reduce cost than faster derivation. 
Please let me know if my suggestion sounds completely strange, since i'm still a beginner. 

**Describe the solution you'd like**

Add an option for `op-batcher` to disable batch submission on empty batch.  

**Describe alternatives you've considered**

**Additional context**

**Comment by tynes** [comment]
This sort of change would require a more thought through proposal of the code diff but you are right that it would be helpful
