### ISSUE TITLE
I want to deploy an op stack ,I got an error when deploy the L1 contract

### ISSUE THREAD

**Issue by WSbaikaishui** [ethereum-optimism/optimism#5399]
**Describe the bug**
this bug is used this order：
```
npx hardhat deploy --network getting-started
```
it takes more than 5 geth in my account ,and I dont know whether if this is due to the fact that I am using a public rpc node
```https://rpc.ankr.com/eth_goerli```
and it got error like this 
![image](https://user-images.githubusercontent.com/46080358/230873768-279e91c1-143c-4a0e-ba65-9aea3af0aee6.png)

**To Reproduce**
just  follow the docs step by step

**Screenshots**

**System Specs:**
 - OS:  Ubuntu 20.04
 - Package Version (or commit hash):git clone it in 03/04/2023,last week

**Comment by wuzhanfly** [comment]
@smartcontracts  I also encountered the same problem

**Comment by d-smith** [comment]
I have encountered the same problem, both against a local geth dev node and the sepolia test network.

**Comment by dariacherniakk** [comment]
@smartcontracts  I have the same issue. Firstly it requires more than 0.2 eth on Admin account to deploy all contracts, for me it took around 3.7eth. Secondly, it fails with 2 errors both on local node and goerli testnet: 
The first one says that 
```
Error: ERROR processing .../optimism/packages/contracts-bedrock/deploy/101-L2CrossDomainMessengerImpl.ts:
TypeError: Cannot read property 'deployments' of undefined`
```
After running the same command the second time I get the next error:
```
Error: ERROR processing .../optimism/packages/contracts-bedrock/deploy/019-SystemDictatorInit.ts:
TypeError: SystemDictatorProxyWithSigner.transferOwnership is not a function
```

**Comment by WSbaikaishui** [comment]
is there are someone can help us?

**Comment by WSbaikaishui** [comment]
I have tried that if we can change another version like v1.0.1, this version is ok, maybe just because the docs is not update

**Comment by CRBl69** [comment]
It looks like the doc just got updated from:

```bash
npx hardhat deploy --network getting-started
```

to

```bash
npx hardhat deploy --network getting-started --tags l1
```

It now works.

Don't forget to clean first with:

```bash
rm -fr deployments/getting-started
```

**Comment by wuzhanfly** [comment]
> It looks like the doc just got updated from:
> 
> ```shell
> npx hardhat deploy --network getting-started
> ```
> 
> to
> 
> ```shell
> npx hardhat deploy --network getting-started --tags l1
> ```
> 
> It now works.
> 
> Don't forget to clean first with:
> 
> ```shell
> rm -fr deployments/getting-started
> ```


How to deploy the l2 contract?

**Comment by smartcontracts** [comment]
@CRBl69 correctly points out that there was a bug in the docs because of something that changed in the deploy scripts. You need to use `--tags l1` now to avoid trying to deploy the L2 contracts to L1.

**Comment by smartcontracts** [comment]
Going to close for now, feel free to request to reopen if still facing the issue
