### ISSUE TITLE
Inaccurate Comment: L1Traversal Reset Method

### ISSUE THREAD

**Issue by sam-iamm** [ethereum-optimism/optimism#5458]
A comment for the [Reset method](https://github.com/ethereum-optimism/optimism/blob/develop/op-node/rollup/derive/l1_traversal.go#L91) of the L1Traversal struct says:
```
// Note that the next call to `NextL1Block` will return the block after `base`
// TODO: Walk one back/figure this out.
```
Yet, the Reset function sets the following:
```
l1t.block = base
l1t.done = false
```
which should mean that the next call to [NextL1Block](https://github.com/ethereum-optimism/optimism/blob/develop/op-node/rollup/derive/l1_traversal.go#L50) will in fact return the base block, not the block after the base block.

**Comment by smartcontracts** [comment]
cc @trianglesphere is that correct? If so then fixing this would be a good first issue for someone.

**Comment by smartcontracts** [comment]
Ty, marked as `good first issue` for someone
