### ISSUE TITLE
Huge block number

### ISSUE THREAD

**Issue by unlimittt** [ethereum-optimism/optimism#5461]
Dtl sync L2 mainnet

```
{"level":30,"time":1681527189788,"fromBlock":71937001,"toBlock":71938001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
```

Is it ok to poll block number 71 937 001?

**Comment by smartcontracts** [comment]
Yep. Current block number is very high. This is because the protocol currently produces one block per transaction. After Bedrock there will be one block every 2 seconds.
