### ISSUE TITLE
It takes long time to sync to the latest block.. more than 3 weeks 

### ISSUE THREAD

**Issue by luwang920** [ethereum-optimism/optimism#5462]
**Describe the bug**
Since the 'nonce too high error' I have to resync the optimism node 
I use the snapshot https://archive.org/download/optimism-snapshot/op-replica_geth-2023-02-20.tar.zst and https://archive.org/download/optimism-snapshot/op-replica_dtl-2023-02-20.tar.zst
Sync L2 from alchemy.
But I need to sync from block 75xxxxxx to 90795825  , the node synced around 600 block/min , it will take several weeks to reach the latest block.
Can I make it faster ?  
I have another node which synced L1 from my erigon achive node ... I guess it will be in syncing forever ... 1 week only 10 million blocks..

**System Specs:**
System : aws t2.xlarge (4 CPU,16G MEM, 600G volume)

Please help , thanks 
Br
Lu

**Comment by smartcontracts** [comment]
I'm working on providing a snapshot to increase sync speed, will keep you updated.

**Comment by ajb** [comment]
> I'm working on providing a snapshot to increase sync speed, will keep you updated.

Please let us know - it's nearly impossible to sync a node right now.

**Comment by luwang920** [comment]
> > I'm working on providing a snapshot to increase sync speed, will keep you updated.
> 
> Please let us know - it's nearly impossible to sync a node right now.

L2 sync from alchemy : half a million per day .  (totally 15 million blocks sync from the current snapshot 2.20 ) more than 30 days
L1 sync from my erigon archive node : one million per day . (from scratch totally 92 million blocks )  more than 3 month . 
Did I get it right??
Is there anything wrong with my node ?
Br
Lu

**Comment by smartcontracts** [comment]
L1 sync is really slow right now. I have some tricks up my sleeve to make it a little faster but unfortunately with the Bedrock upgrade coming so soon it's been de-prioritized.

@ajb in the meantime you can use these community provided snapshots. Not maintained by OP Labs or anything so use at your own risk: https://archive.org/download/optimism-snapshot

**Comment by ajb** [comment]
> L1 sync is really slow right now. I have some tricks up my sleeve to make it a little faster but unfortunately with the Bedrock upgrade coming so soon it's been de-prioritized.

L2 sync is also quite slow, even when you already have the data in DTL. (It was just my l2geth database that got borked on a restart.)

@smartcontracts I am already using these snapshots.

**Comment by smartcontracts** [comment]
Yeah it's all slow :-/ running on like 3 year old Geth. Unfortunately the legacy l2geth gets limited support right now because of the push to Bedrock. With Bedrock these sort of issues should go away but it's an awkward middle period at the moment. I can make more recent snapshots.

**Comment by ajb** [comment]
> I can make more recent snapshots.

This will certainly alleviate the issue.

**Comment by smartcontracts** [comment]
Gotcha. Can get on this end of next week at the earliest.

**Comment by ajb** [comment]
Cool, thanks for the update.

I don't really know how it works, but my node is almost synced and I could upload it to archive.org as well.

**Comment by luwang920** [comment]
Looking forward to the new snapshots ， thanks

**Comment by bsantoni-bc** [comment]
I have a similar issue, where the muy node got borked just after the DTL finished syncing and l2geth was just about starting to sync.

I have tried using the archive.org snapshots, but it doesn't look like they are getting used at all, as I see the DTL syncing from block 13596466, like the snapshot files were't even there.

Is there any additional config I am missing to use the snapshots?

**Comment by luwang920** [comment]
I got the 'nonce too high' error again at the block 81829227, sync from Alchemy L2
I am afraid I cannot set up the optimism node without the new snapshot .. 
I got 'nonce too high' error 4 times , and this time it took me 3 weeks to resync it , still failed  , this is too depressing ...

**Comment by joslee7410** [comment]
Not sure why my `simple-optimism-node-l2geth-1` container will being restart randomly.

Within this month already resync more than 3 times with 2 nodes. I did make it synced, but suddenly the container will restart.

```
DEBUG[04-26|02:17:43.505] Applying transaction to tip              index=94277066 hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471 origin=sequencer
DEBUG[04-26|02:17:43.505] Attempting to commit rollup transaction  hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471
INFO [04-26|02:17:43.511] New block                                index=94277066 l1-timestamp=1682475447 l1-blocknumber=17127328 tx-hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471 queue-orign=sequencer gas=70978    fees=8.51736e-08     elapsed=6.335ms
DEBUG[04-26|02:17:43.513] Miner got new head                       height=94277067 block-hash=0xab57c14ef00ac31b1b7ee96d18fc7272ccd0c35cfc11fc2fdc24608e574060d0 tx-hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471 tx-hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471
DEBUG[04-26|02:17:43.605] Served eth_gasPrice                      conn=18.139.81.231:54273  reqid=671311  t=43.34µs
DEBUG[04-26|02:17:44.008] Served eth_gasPrice                      conn=18.139.81.231:25839  reqid=676949  t=45.417µs
DEBUG[04-26|02:17:44.546] Served eth_gasPrice                      conn=18.143.94.160:34176  reqid=440575  t=36.599µs
DEBUG[04-26|02:17:44.634] Served eth_gasPrice                      conn=18.140.83.19:38924   reqid=609028  t=81.648µs
DEBUG[04-26|02:17:44.700] Served eth_chainId                       conn=172.30.0.2:59170     reqid=417949  t=41.016µs
DEBUG[04-26|02:17:44.701] Served eth_getBlockByNumber              conn=172.30.0.2:59180     reqid=417950  t=166.514µs
DEBUG[04-26|02:17:44.731] Served eth_gasPrice                      conn=18.140.83.19:50821   reqid=593393  t=29.241µs
+ GETH_DATA_DIR=/geth
+ GETH_CHAINDATA_DIR=/geth/geth/chaindata
+ GETH_KEYSTORE_DIR=/geth/keystore
+ '[' '!' -d /geth/keystore ]
+ '[' '!' -d /geth/geth/chaindata ]
+ echo '/geth/geth/chaindata exists, checking for hardfork.'
+ echo 'Chain config:'
+ geth dump-chain-cfg '--datadir=/geth'
/geth/geth/chaindata exists, checking for hardfork.
Chain config:
INFO [04-26|02:17:50.472] Maximum peer count                       ETH=50 LES=0 total=50
```

I running with 8 CPU 32G ram still able to met this problem.

**Comment by luwang920** [comment]
> Not sure why my `simple-optimism-node-l2geth-1` container will being restart randomly.
> 
> Within this month already resync more than 3 times with 2 nodes. I did make it synced, but suddenly the container will restart.
> 
> ```
> DEBUG[04-26|02:17:43.505] Applying transaction to tip              index=94277066 hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471 origin=sequencer
> DEBUG[04-26|02:17:43.505] Attempting to commit rollup transaction  hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471
> INFO [04-26|02:17:43.511] New block                                index=94277066 l1-timestamp=1682475447 l1-blocknumber=17127328 tx-hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471 queue-orign=sequencer gas=70978    fees=8.51736e-08     elapsed=6.335ms
> DEBUG[04-26|02:17:43.513] Miner got new head                       height=94277067 block-hash=0xab57c14ef00ac31b1b7ee96d18fc7272ccd0c35cfc11fc2fdc24608e574060d0 tx-hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471 tx-hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471
> DEBUG[04-26|02:17:43.605] Served eth_gasPrice                      conn=18.139.81.231:54273  reqid=671311  t=43.34µs
> DEBUG[04-26|02:17:44.008] Served eth_gasPrice                      conn=18.139.81.231:25839  reqid=676949  t=45.417µs
> DEBUG[04-26|02:17:44.546] Served eth_gasPrice                      conn=18.143.94.160:34176  reqid=440575  t=36.599µs
> DEBUG[04-26|02:17:44.634] Served eth_gasPrice                      conn=18.140.83.19:38924   reqid=609028  t=81.648µs
> DEBUG[04-26|02:17:44.700] Served eth_chainId                       conn=172.30.0.2:59170     reqid=417949  t=41.016µs
> DEBUG[04-26|02:17:44.701] Served eth_getBlockByNumber              conn=172.30.0.2:59180     reqid=417950  t=166.514µs
> DEBUG[04-26|02:17:44.731] Served eth_gasPrice                      conn=18.140.83.19:50821   reqid=593393  t=29.241µs
> + GETH_DATA_DIR=/geth
> + GETH_CHAINDATA_DIR=/geth/geth/chaindata
> + GETH_KEYSTORE_DIR=/geth/keystore
> + '[' '!' -d /geth/keystore ]
> + '[' '!' -d /geth/geth/chaindata ]
> + echo '/geth/geth/chaindata exists, checking for hardfork.'
> + echo 'Chain config:'
> + geth dump-chain-cfg '--datadir=/geth'
> /geth/geth/chaindata exists, checking for hardfork.
> Chain config:
> INFO [04-26|02:17:50.472] Maximum peer count                       ETH=50 LES=0 total=50
> ```
> 
> I running with 8 CPU 32G ram still able to met this problem.

check your docker container exit code

**Comment by blazelee7410** [comment]
> > Not sure why my `simple-optimism-node-l2geth-1` container will being restart randomly.
> > Within this month already resync more than 3 times with 2 nodes. I did make it synced, but suddenly the container will restart.
> > ```
> > DEBUG[04-26|02:17:43.505] Applying transaction to tip              index=94277066 hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471 origin=sequencer
> > DEBUG[04-26|02:17:43.505] Attempting to commit rollup transaction  hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471
> > INFO [04-26|02:17:43.511] New block                                index=94277066 l1-timestamp=1682475447 l1-blocknumber=17127328 tx-hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471 queue-orign=sequencer gas=70978    fees=8.51736e-08     elapsed=6.335ms
> > DEBUG[04-26|02:17:43.513] Miner got new head                       height=94277067 block-hash=0xab57c14ef00ac31b1b7ee96d18fc7272ccd0c35cfc11fc2fdc24608e574060d0 tx-hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471 tx-hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471
> > DEBUG[04-26|02:17:43.605] Served eth_gasPrice                      conn=18.139.81.231:54273  reqid=671311  t=43.34µs
> > DEBUG[04-26|02:17:44.008] Served eth_gasPrice                      conn=18.139.81.231:25839  reqid=676949  t=45.417µs
> > DEBUG[04-26|02:17:44.546] Served eth_gasPrice                      conn=18.143.94.160:34176  reqid=440575  t=36.599µs
> > DEBUG[04-26|02:17:44.634] Served eth_gasPrice                      conn=18.140.83.19:38924   reqid=609028  t=81.648µs
> > DEBUG[04-26|02:17:44.700] Served eth_chainId                       conn=172.30.0.2:59170     reqid=417949  t=41.016µs
> > DEBUG[04-26|02:17:44.701] Served eth_getBlockByNumber              conn=172.30.0.2:59180     reqid=417950  t=166.514µs
> > DEBUG[04-26|02:17:44.731] Served eth_gasPrice                      conn=18.140.83.19:50821   reqid=593393  t=29.241µs
> > + GETH_DATA_DIR=/geth
> > + GETH_CHAINDATA_DIR=/geth/geth/chaindata
> > + GETH_KEYSTORE_DIR=/geth/keystore
> > + '[' '!' -d /geth/keystore ]
> > + '[' '!' -d /geth/geth/chaindata ]
> > + echo '/geth/geth/chaindata exists, checking for hardfork.'
> > + echo 'Chain config:'
> > + geth dump-chain-cfg '--datadir=/geth'
> > /geth/geth/chaindata exists, checking for hardfork.
> > Chain config:
> > INFO [04-26|02:17:50.472] Maximum peer count                       ETH=50 LES=0 total=50
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I running with 8 CPU 32G ram still able to met this problem.
> 
> check your docker container exit code

It does not have exit code, cause the container auto restart already.

**Comment by joslee7410** [comment]
> > Not sure why my `simple-optimism-node-l2geth-1` container will being restart randomly.
> > Within this month already resync more than 3 times with 2 nodes. I did make it synced, but suddenly the container will restart.
> > ```
> > DEBUG[04-26|02:17:43.505] Applying transaction to tip              index=94277066 hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471 origin=sequencer
> > DEBUG[04-26|02:17:43.505] Attempting to commit rollup transaction  hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471
> > INFO [04-26|02:17:43.511] New block                                index=94277066 l1-timestamp=1682475447 l1-blocknumber=17127328 tx-hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471 queue-orign=sequencer gas=70978    fees=8.51736e-08     elapsed=6.335ms
> > DEBUG[04-26|02:17:43.513] Miner got new head                       height=94277067 block-hash=0xab57c14ef00ac31b1b7ee96d18fc7272ccd0c35cfc11fc2fdc24608e574060d0 tx-hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471 tx-hash=0xd9e6b0461318663e84851b8a9886be6168c1e99376e9c2ac512c4c8a93b81471
> > DEBUG[04-26|02:17:43.605] Served eth_gasPrice                      conn=18.139.81.231:54273  reqid=671311  t=43.34µs
> > DEBUG[04-26|02:17:44.008] Served eth_gasPrice                      conn=18.139.81.231:25839  reqid=676949  t=45.417µs
> > DEBUG[04-26|02:17:44.546] Served eth_gasPrice                      conn=18.143.94.160:34176  reqid=440575  t=36.599µs
> > DEBUG[04-26|02:17:44.634] Served eth_gasPrice                      conn=18.140.83.19:38924   reqid=609028  t=81.648µs
> > DEBUG[04-26|02:17:44.700] Served eth_chainId                       conn=172.30.0.2:59170     reqid=417949  t=41.016µs
> > DEBUG[04-26|02:17:44.701] Served eth_getBlockByNumber              conn=172.30.0.2:59180     reqid=417950  t=166.514µs
> > DEBUG[04-26|02:17:44.731] Served eth_gasPrice                      conn=18.140.83.19:50821   reqid=593393  t=29.241µs
> > + GETH_DATA_DIR=/geth
> > + GETH_CHAINDATA_DIR=/geth/geth/chaindata
> > + GETH_KEYSTORE_DIR=/geth/keystore
> > + '[' '!' -d /geth/keystore ]
> > + '[' '!' -d /geth/geth/chaindata ]
> > + echo '/geth/geth/chaindata exists, checking for hardfork.'
> > + echo 'Chain config:'
> > + geth dump-chain-cfg '--datadir=/geth'
> > /geth/geth/chaindata exists, checking for hardfork.
> > Chain config:
> > INFO [04-26|02:17:50.472] Maximum peer count                       ETH=50 LES=0 total=50
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I running with 8 CPU 32G ram still able to met this problem.
> 
> check your docker container exit code

It does not have exit code, cause the container auto restart already.

**Comment by thezillo** [comment]
I also have this problem, sync takes a long time
How much disk space does an archive node need now? My disk is filled with more than 2TB, the increase is ~2GB per hour and at the end of the synchronization the total volume is about 6TB, is that true?

**Comment by luwang920** [comment]
Hi again
Any news for the new snapshot？
Thanks
Br
Lu

**Comment by git-ljm** [comment]
Do you have the latest news about snapshots? We have encountered similar problems many times, which have lasted for about a month.

**Comment by smohite03** [comment]
How can I get latest snapshots of optimism node both (l2geth & DTL) can anyone please share.

**Comment by pavel-bc** [comment]
> How can I get latest snapshots of optimism node both (l2geth & DTL) can anyone please share.

+1

**Comment by git-ljm** [comment]
I hope to update the snapshot progress quickly.

**Comment by tynes** [comment]
Closing this because bedrock snapshots are available

**Comment by sajal** [comment]
I think this issue is still relevant. The bedrock snapshot is from ages ago, currently a fresh installation (using bedrock snapshot) is syncing at ~800ms per block... at this rate it would take me roughly 2.8 months to finish syncing. 

I have verified that L1 RPC is not the bottleneck as it responds to each `eth_getBlockByHash` within 30ms.

**Comment by zainirfan13** [comment]
@sajal facing the same issue.
I just upgraded my optimism node and now i am stuck in 12 hours syncing it's too slow.
