### ISSUE TITLE
insufficient balance for transfer

### ISSUE THREAD

**Issue by oleksandrmarkelov** [ethereum-optimism/optimism#5464]
**Describe the bug**
Sync from L2 stops on block 87079654 with error insufficient balance for transfer

**To Reproduce**
ENV vars:
###### DTL ENV ######

DATA_TRANSPORT_LAYER__ADDRESS_MANAGER=0xdE1FCfB0851916CA5101820A69b13a4E276bd81F
DATA_TRANSPORT_LAYER__L1_START_HEIGHT=13596466
DATA_TRANSPORT_LAYER__CONFIRMATIONS=12
DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS=true
DATA_TRANSPORT_LAYER__DB_PATH=/datadrive/opti/.local/share/optimism/dtl/datadir
DATA_TRANSPORT_LAYER__ENABLE_METRICS=true
DATA_TRANSPORT_LAYER__ETH_NETWORK_NAME=mainnet
DATA_TRANSPORT_LAYER__L2_CHAIN_ID=10
DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL=2000
DATA_TRANSPORT_LAYER__NODE_ENV=production
DATA_TRANSPORT_LAYER__POLLING_INTERVAL=500
DATA_TRANSPORT_LAYER__SENTRY_TRACE_RATE=0.05
DATA_TRANSPORT_LAYER__SERVER_HOSTNAME=0.0.0.0
DATA_TRANSPORT_LAYER__SERVER_PORT=7878
DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL=1000
DATA_TRANSPORT_LAYER__SYNC_FROM_L1=false
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=https://eth-mainnet.g.alchemy.com/XXXX
DATA_TRANSPORT_LAYER__SYNC_FROM_L2=true
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://opt-mainnet.g.alchemy.com/XXXX

###### L2 GETH OP ENV ######

NETWORK_NAME=mainnet
NODE_TYPE=archive
USING_OVM=true
SEQUENCER_CLIENT_HTTP=https://mainnet.optimism.io
BLOCK_SIGNER_ADDRESS=0x00000398232E2064F896018496b4b44b3D62751F
BLOCK_SIGNER_PRIVATE_KEY=6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27
ETH1_CTC_DEPLOYMENT_HEIGHT=13596466
ETH1_SYNC_SERVICE_ENABLE=true
ROLLUP_CLIENT_HTTP=http://0.0.0.0:7878
ROLLUP_MAX_CALLDATA_SIZE=40000
ROLLUP_POLL_INTERVAL_FLAG=1s
ROLLUP_VERIFIER_ENABLE=true
ROLLUP_DISABLE_TRANSFERS=false
ROLLUP_ENABLE_L2_GAS_POLLING=false
ROLLUP_GAS_PRICE_ORACLE_OWNER_ADDRESS=0x648E3e8101BFaB7bf5997Bd007Fb473786019159
ROLLUP_BACKEND=l2

###### L2 GETH ENV ######

GCMODE=archive
DATADIR=/datadrive/opti/.local/share/optimism/l2geth/datadir
CHAIN_ID=10
NETWORK_ID=10
NO_DISCOVER=true
NO_USB=true
GASPRICE=0
TARGET_GAS_LIMIT=1500000000
RPC_ADDR=0.0.0.0
RPC_API=eth,rollup,net,web3,debug
RPC_CORS_DOMAIN=*
RPC_ENABLE=true
RPC_PORT=9657
RPC_VHOSTS=*
WS_ADDR=0.0.0.0
WS_API=eth,rollup,net,web3,debug
WS_ORIGINS=*
WS=true

**Screenshots**
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/63374230/232254078-87f5a74e-c5d5-4f8f-ac36-74e22b922f1c.png">

**System Specs:**
 - OS: ubuntu 20.02
 - Package Version (or commit hash): 1.9.10-stable

**Additional context**

**Comment by smartcontracts** [comment]
Unfortunately happens sometimes if the node was not shut down properly. Unclear why this happens but this is fixed by Bedrock. You will need to resync your node and try to avoid a hard shutdown.

**Comment by oleksandrmarkelov** [comment]
there were no hard shut down. The node just stopped syncing. 

Anyway, if such time of issue happened, is it possible to recover from it?

**Comment by smartcontracts** [comment]
Hm node just stopped out of the blue?

**Comment by oleksandrmarkelov** [comment]
noded haven't stopped but syncing from L2 stopped

**Comment by tynes** [comment]
The system has been upgraded to bedrock
