### ISSUE TITLE
OVM_L1ETHGateway accepts deposits from users when it should not

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#547]
**Describe the bug**
[`OVM_L1ETHGateway.sol`](https://github.com/ethereum-optimism/optimism/blob/master/packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1ETHGateway.sol) accepts ETH deposits from users when it should only accept deposits from `Proxy__OVM_L1ETHGateway`.

You can see that people were able to make deposits to `OVM_L1ETHGateway` on Kovan when you look at [the balance of the contract on etherscan](https://kovan.etherscan.io/address/0x0E8917aF9eB7812c7819EF4e80D2217679d11324). The last deposit was made on 4/21/2021 at 8:51:56.

**Expected behavior**
`Proxy__OVM_L1ETHGateway` should be the only contract able to make deposit calls to `OVM_L1ETHGateway`.

**Additional context**
This issue was surfaced after a discord member pointed out that in our integration docs, we recommend using `OVM_L1ETHGateway` to deposit ETH to L2, an issue that will be fixed in it's own PR in [community-hub](https://github.com/ethereum-optimism/community-hub/pulls)

**Comment by maurelian** [comment]
I think the fix is to just make sure we don't publish the implementation addresses anywhere. :)

**Comment by K-Ho** [comment]
+1^

**Comment by gakonst** [comment]
To ask the obvious question: Why should direct transactions to the contract be disabled? 

You can add a `require(msg.sender == proxyAddress)` if you wanted to enforce it, but not sure what this really achieves? As a user, I'd maybe want to opt-out of the upgradeable contract model.

**Comment by K-Ho** [comment]
The L2 `OVM_ETH` contract specifies that its counterpart on L1 is at the `Proxy_OVM_L1ETHGateway` address

**Comment by smartcontracts** [comment]
> I think the fix is to just make sure we don't publish the implementation addresses anywhere. :)
But I will inquire with OZ as to whether they might have any other suggestions.

@maurelian were you able to reach out to OZ to get a recommendation?

**Comment by maurelian** [comment]
> @maurelian were you able to reach out to OZ to get a recommendation?

Just asked

**Comment by maurelian** [comment]
So, we could do the opposite of this to prevent direct calls to the contract (h/t @frangio):

https://github.com/Uniswap/uniswap-v3-core/blob/e3589b192d0be27e100cd0daaf6c97204fdb1899/contracts/NoDelegateCall.sol#L10-L20

It's not hard to include, and probably not that expensive (the address is stored as a constant). But then also:

> we've heard of people putting this protection measure in place, but i don't think i had ever heard of someone actually making that mistake

- @frangio

> a fix on the docs is definitely easier than one in the contracts

- @spalladino

Do we know how that address got into the docs, how likely is this to happen again? I'm assuming it was read from a regenesis file somewhere, which does feel like an easy enough mistake to make.

**Comment by maurelian** [comment]
Seems like the best thing to do here is to just never publicize the underlying implementation address.
