### ISSUE TITLE
debug_traceBlockByNumber taking too much time(1 minute) to respond. Can't trace this slow!

### ISSUE THREAD

**Issue by Aman-Maheshwari7** [ethereum-optimism/optimism#5526]
**Describe the bug**
debug_traceBlockByNumber taking too much time(1 minute) to respond for many blocks. Infact two or more simultaneuous requests increases this response time to more than 200s for individual requests(which ultimately results in timeout). One such example being block number=0x4C52940. Around 30 percent of blocks are like these.

**To Reproduce**
1.  Send rpc request debug_traceBlockByNumber of block number: 0x4C52940
2.  Note the time taken for response. It is too high

**Expected behavior**
1. I should receive the trace within a second

**System Specs:**
Tried with 32 vcpu's as well. But same issue.

**Comment by tynes** [comment]
There are a bunch of closed issues that describe the problem and solution. Bedrock fixes this fwiw
