### ISSUE TITLE
Building `smock` in CI fails

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#554]
**Describe the bug**
There is an unrelated bug happening in https://github.com/ethereum-optimism/optimism/pull/544

```
Error: src/smockit/binding.ts(2,43): error TS2307: Cannot find module 
'hardhat/internal/hardhat-network/provider/errors' or its corresponding type declarations.
```

**To Reproduce**
Look at the failing tests, the log show that `smock` fails to build. https://github.com/ethereum-optimism/optimism/pull/544

**Expected behavior**
`smock` should build without a problem

**Comment by smoove** [comment]
Any workarounds for the time being?
The file 'hardhat/internal/hardhat-network/provider/errors' was indeed removed from hardhat-core.

**Comment by smartcontracts** [comment]
Checking this out

**Comment by smartcontracts** [comment]
Working on this over at #576

**Comment by smartcontracts** [comment]
#576 was merged. Can we check if this is still happening?

**Comment by gakonst** [comment]
I cannot repro this any more, it was published in https://github.com/ethereum-optimism/optimism/pull/582. If anyone still encounters it, please reopen
