### ISSUE TITLE
yarn run build exited 1 in '@eth-optimism/contracts-bedrock'

### ISSUE THREAD

**Issue by Ayodeji63** [ethereum-optimism/optimism#5543]
**Describe the bug**
When i run yarn build i go this error: 
yarn run v1.22.19
$ yarn lerna run build
$ /home/user/OP/optimism/node_modules/.bin/lerna run build
lerna notice cli v4.0.0
lerna info versioning independent
lerna info Executing command in 16 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@eth-optimism/atst' in 3.1s:
$ yarn tsup
$ /home/user/OP/optimism/node_modules/.bin/tsup
[@ETH-OPTIMISM/ATST] CLI Building entry: src/index.ts, src/cli.ts, src/react.ts
[@ETH-OPTIMISM/ATST] CLI Using tsconfig: tsconfig.json
[@ETH-OPTIMISM/ATST] CLI tsup v6.5.0
[@ETH-OPTIMISM/ATST] CLI Using tsup config: /home/user/OP/optimism/packages/atst/tsup.config.ts
[@ETH-OPTIMISM/ATST] CLI Target: es2021
[@ETH-OPTIMISM/ATST] CLI Cleaning output folder
[@ETH-OPTIMISM/ATST] ESM Build start
[@ETH-OPTIMISM/ATST] CJS Build start
[@ETH-OPTIMISM/ATST] ESM You have emitDecoratorMetadata enabled but @swc/core was not installed, skipping swc plugin
[@ETH-OPTIMISM/ATST] CJS You have emitDecoratorMetadata enabled but @swc/core was not installed, skipping swc plugin
[@ETH-OPTIMISM/ATST] ESM dist/index.js     9.85 KB
[@ETH-OPTIMISM/ATST] ESM dist/cli.js       20.89 KB
[@ETH-OPTIMISM/ATST] ESM dist/react.js     5.56 KB
[@ETH-OPTIMISM/ATST] ESM dist/index.js.map 23.95 KB
[@ETH-OPTIMISM/ATST] ESM dist/cli.js.map   37.93 KB
[@ETH-OPTIMISM/ATST] ESM dist/react.js.map 19.30 KB
[@ETH-OPTIMISM/ATST] ESM ⚡️ Build success in 278ms
[@ETH-OPTIMISM/ATST] CJS dist/index.cjs     12.00 KB
[@ETH-OPTIMISM/ATST] CJS dist/cli.cjs       22.68 KB
[@ETH-OPTIMISM/ATST] CJS dist/react.cjs     7.63 KB
[@ETH-OPTIMISM/ATST] CJS dist/index.cjs.map 25.24 KB
[@ETH-OPTIMISM/ATST] CJS dist/cli.cjs.map   38.11 KB
[@ETH-OPTIMISM/ATST] CJS dist/react.cjs.map 19.35 KB
[@ETH-OPTIMISM/ATST] CJS ⚡️ Build success in 288ms
lerna info run Ran npm script 'build' in '@eth-optimism/core-utils' in 15.4s:
$ tsc -p tsconfig.json
lerna info run Ran npm script 'build' in '@eth-optimism/balance-monitor' in 21.5s:
$ tsc -p tsconfig.json
lerna info run Ran npm script 'build' in '@eth-optimism/hardhat-deploy-config' in 21.6s:
$ tsc -p tsconfig.json
lerna info run Ran npm script 'build' in '@eth-optimism/common-ts' in 21.0s:
$ tsc -p tsconfig.json
lerna ERR! yarn run build exited 1 in '@eth-optimism/contracts-bedrock'
lerna ERR! yarn run build stdout:
$ yarn ts-node scripts/verify-foundry-install.ts
$ /home/user/OP/optimism/node_modules/.bin/ts-node scripts/verify-foundry-install.ts
$ hardhat compile && yarn autogen:artifacts && yarn build:ts && yarn typechain

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
Solidity 0.8.15 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/reference/solidity-support

ZOE ERROR (from forge): zoeParseOptions: unknown option (--build-info)
ZOE library version 2013-02-16
An unexpected error occurred:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at spawnConfigSync (/home/user/OP/optimism/packages/contracts-bedrock/node_modules/@foundry-rs/hardhat-forge/src/forge/config/index.ts:40:15)
    at /home/user/OP/optimism/packages/contracts-bedrock/node_modules/@foundry-rs/hardhat-forge/src/index.ts:18:35
    at getRealTarget (/home/user/OP/optimism/node_modules/hardhat/src/internal/util/lazy.ts:112:22)
    at Object.get (/home/user/OP/optimism/node_modules/hardhat/src/internal/util/lazy.ts:185:26)
    at OverriddenTaskDefinition._action (/home/user/OP/optimism/packages/contracts-bedrock/node_modules/@foundry-rs/hardhat-forge/src/forge/build/index.ts:23:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Environment._runTaskDefinition (/home/user/OP/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/home/user/OP/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async main (/home/user/OP/optimism/node_modules/hardhat/src/internal/cli/cli.ts:218:5)
error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in '@eth-optimism/contracts-bedrock'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Expected behavior**
Buid Successful 
**Screenshots**

**System Specs:**
 - OS: Ubuntu 20.04
 - Package Version (or commit hash): Yarn v1.22.19

**Comment by tynes** [comment]
Update foundry with `foundryup`

**Comment by Ayodeji63** [comment]
I have resolved the issue thanks
