### ISSUE TITLE
Integration test services are inflexible and depend on a single `docker-compose.yml` config

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#556]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to define multiple configuration sets for the integration tests and have different sets of tests run against fresh instances of the system. Right now it is impossible to use this repo to write integration tests for the verifier as `l2geth` always comes up in sequencer mode. In `optimism-integration` this was possible, although much more complex. Perhaps there is a happy medium.

**Describe the solution you'd like**
`optimism-integration` would iterate through a series of test suites and bring up the full system for each test suite. This would give a fresh state for each test suite as well as giving an opportunity to merge configs using `docker-compose -f base.yml specific-to-test-suite.yml`. I am not exactly sure how this is possible with the current setup.

**Describe alternatives you've considered**
It is possible to put verifier tests in a different repo, but that kind of defeats the purpose of the monorepo

**Comment by gakonst** [comment]
Isn't bringing the sequencer up in verfier mode a matter of setting an env var? 

If so, we can allow that env var to be set in the `docker-compose.yml` file, and simply bring up 2 l2geth instances, one in sequencer mode, one in verifier mode.

**Comment by tynes** [comment]
> If so, we can allow that env var to be set in the docker-compose.yml file, and simply bring up 2 l2geth instances

This is possible, but then we would need to run 3 l2geth instances (sequencer, verifier, replica) to be able to test all of the code paths. Sometimes it would also be nice to cut out some codepaths, ie submit batches directly from the tests instead of sending transactions to the sequencer and having the batch submitter submit them

**Comment by tynes** [comment]
Closing, will add the extra l2geth in the future but hopefully it doesn't price people out from local dev
