### ISSUE TITLE
"cannot unmarshal deploy config: hex number > 64 bits"

### ISSUE THREAD

**Issue by Ayodeji63** [ethereum-optimism/optimism#5561]
**Describe the bug**
Am trying to generate the genesis.json and rollup.json file, i got error when i ran the code provided in the document.

**To Reproduce**
I run this in my terminal
go run cmd/main.go genesis l2 \
    --deploy-config ../packages/contracts-bedrock/deploy-config/getting-started.json \
    --deployment-dir ../packages/contracts-bedrock/deployments/getting-started/ \
    --outfile.l2 genesis.json \
    --outfile.rollup rollup.json \
    --l1-rpc <RPC>

**Screenshots**
![Screenshot from 2023-04-28 20-38-16](https://user-images.githubusercontent.com/75380773/235239254-c40d8b81-f7f0-4f64-b4ba-316fed2b4f04.png)

**System Specs:**
 - OS: Ubuntu 20.04
 - Package Version (or commit hash):

**Comment by tynes** [comment]
Be sure to follow the instructions such that all fields are set correctly in the deploy config

**Comment by longfin** [comment]
In my case, the block hash on `l1StartingBlockTag` field had been a blocker. after changing that value to as block index (with `0x` prefix), the problem has been solved.

https://github.com/ethereum-optimism/optimism/blob/a6e6988cbd89985a72c1fa2fcb9549e6a6ddfbba/op-chain-ops/genesis/config.go#L36 

May needed to check `MarshalableRPCBlockNumberOrHash` type 🤔
