### ISSUE TITLE
Contracts do not deploy on Windows due to filenames with colons (i.e., ":") in them

### ISSUE THREAD

**Issue by joshstevens19** [ethereum-optimism/optimism#558]
It seems the ovm compiler does not work on windows. When you try to deploy to one of the L2 nodes with windows it just throws a transaction error. If you do the same command on a Linux subsystem it works fine and it's fine on macs.

Error on windows:

![image](https://user-images.githubusercontent.com/18472422/115743999-1189f400-a38a-11eb-97e2-757e8d75c9df.png)

Success on windows subsystem Linux:

![image](https://user-images.githubusercontent.com/18472422/115744064-22d30080-a38a-11eb-8d66-f8fd98a74e94.png)

You can see a big difference in the input data on windows vs Linux:

![image](https://user-images.githubusercontent.com/18472422/115744173-3b431b00-a38a-11eb-9943-068b74b8b492.png)

The left one is the successful deployment on Linux and the right one is the bad deployment on windows. both using the same code. As you can see the successful one is double the length. 

it would be great if you guys did document this for windows users. The solution is to install Linux windows system on your windows machine and then execute the deploy script through your Linux windows system and it all works fine!

It also seems that your repo itself has `:` in file names, which means you can not clone it successfully on windows as windows does not support `:` in file names:

![image](https://user-images.githubusercontent.com/18472422/115745055-fe2b5880-a38a-11eb-82a4-6e117624a794.png)

Be great if you could change these so it supports cloning on every OS this could also be why it does not deploy on windows. Thanks

**Comment by snario** [comment]
Fixed by #662

**Comment by tan-wei** [comment]
It seems the issue should be reopened due to some new files are added whose names contain colons.

**Comment by snario** [comment]
https://github.com/ethereum-optimism/optimism/pull/953
