### ISSUE TITLE
NFT bridging between L1 and L2 (testnet)

### ISSUE THREAD

**Issue by eskrano** [ethereum-optimism/optimism#5580]
**Problem with L1 -> L2 bridging ERC721 tokens**
When im trying to use L1ERC721Bridge im getting revert for L2 message to relay and message status - fail.

Here's txns which I did

https://goerli-optimism.etherscan.io/tx/0xe553e416e19457af65f46591148af99fd7d0a831d44b461f4be8ed70e19f4b28 - relay tx.
https://goerli.etherscan.io/tx/0x8b284d668426f49d7d6dd39f34ec7960f958fe2896bb8fb00bbe3dfd7732527b - nft transfer to l1 bridge tx.

**To Reproduce**
Im using next code : 
`
    const txBridge = await L1Bridge.connect(walletL1).bridgeERC721(
        process.env.L1_NFT_ADDR,
        process.env.L2_NFT_ADDR,
        process.env.TOKEN_ID,
        1_200_000,
        ethers.utils.hexlify(ethers.utils.toUtf8Bytes("bridge")),
        {
            gasLimit: 2_000_000
        }
    )
`

Here's .env file

`
L1_NFT_ADDR=0x1F359C32b5D8c9678b076eAac411A4d2Eb11E697
L2_NFT_ADDR=0x5e3e2404c549E066D98c5d1C1B1ABC054c3540d6

TOKEN_ID=5

MINTABLE_ERC721_FACTORY_ADDRESS=0x13DcfC403eCEF3E8Eab66C00dC64e793dc40Be1d

L1_BRIDGE=0x0F9C590b958002E8B10a7431979c1aF882772E88
L2_BRIDGE=0x4200000000000000000000000000000000000014
`

L2 nft was created by MintableFactory which is deployed at L2 goerli testnet at address 0x13DcfC403eCEF3E8Eab66C00dC64e793dc40Be1d

**Expected behavior**
Get NFT token at L2

**System Specs:**
 - OS: mac os
 - Package Version (or commit hash): latest sdk

**Additional context**
Im also trying to use sdk estimateL2MessageGasLimit~ method and got 27k gas  but im only able to estimate for L1 bridge because L2 bridge finalizeERc721 func callable only from MESSENGER or OTHER_BRIDGE so I found qx.app code and just saw they're using 1.2kk gas hardcoded but it didnt help me .

I suppose maybe its not a bug and im just lost some details.

**Comment by tynes** [comment]
It looks like you are interacting with the implementation and not the proxy. The address of the proxy can be found here:
https://goerli.etherscan.io/address/0x8dd330dde8d9898d43b4dc840da27a07df91b3c9

This value was found by looking at the `OTHER_BRIDGE()(address)` method on the L2ERC721Bridge

**Comment by eskrano** [comment]
> It looks like you are interacting with the implementation and not the proxy. The address of the proxy can be found here: https://goerli.etherscan.io/address/0x8dd330dde8d9898d43b4dc840da27a07df91b3c9
> 
> This value was found by looking at the `OTHER_BRIDGE()(address)` method on the L2ERC721Bridge

Thanks for idea, I just did a try (https://goerli-optimism.etherscan.io/tx/0xbd4c1fd1c7e2dcb3860c89b2b430f72d4e388b632f84a451a56fbeefe4614a71 - relay tx, l1 bridge tx - 0x63f299655624b331b78b4105c127d6ae9db098439154159002935d0de62fee0a ). But got reverted relay

**Comment by eskrano** [comment]
Still need help. Thanks.

**Comment by tynes** [comment]
This is better to ask in https://github.com/ethereum-optimism/developers/discussions
