### ISSUE TITLE
Transferring WETH on Optimistic Kovan testnet confirms but balances remain unchanged

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#559]
**Describe the bug**
When doing L2 WETH transfer from one address to another, balances do not change

**To Reproduce**
1. Have an acct on L2 with Kovan WETH (`0x420...6`)
2. Use WETH's built-in send feature (via MetaMask)
3. Observe that balances are not changing on either the sending or receiving address

**Expected behavior**
Balances should reflect the amount of WETH that was transferred

**Comment by K-Ho** [comment]
This works for me. I've seen it happen before though. If you try to send an ETH value transfer, your metamask will increment your nonce, but the sequencer will not. Then any further metamask txs will every w/ invalid nonce

**Comment by tynes** [comment]
> This works fine for me. I've seen it happen before though. If you try to send an ETH value transfer, your metamask will increment your nonce, but the sequencer will not. Then any further metamask txs will every w/ invalid nonce

This PR was created to solve the problem: https://github.com/ethereum-optimism/optimism/pull/435
It has been merged

**Comment by K-Ho** [comment]
Go to advanced settings and "Reset Account"

**Comment by platocrat** [comment]
> Go to advanced settings and "Reset Account"

This "unbricks" an account. But, this isn't the ideal solution

**Comment by snario** [comment]
Fixed by #435
