### ISSUE TITLE
Handle OVM_DeployerWhitelist initialization automatically

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#560]
`OVM_DeployerWhitelist` has a function [`initialize()`](https://github.com/ethereum-optimism/optimism/blob/318857e28c36bdf9e1ec4fd9c7f42af1703ece8a/packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_DeployerWhitelist.sol#L54) which *must* be called after the contract is created. We currently have a manual process for doing this. Ideally, this process would be handled automatically during the state dump generation step. It's necessary to note that we *cannot* call `initialize()` directly because the state dump is generated by deploying to an L1 chain (the contract is compiled for L2). Instead, we would need to directly manipulate the relevant storage slots chugsplash style (chugsplash could easily handle this case).

---

This contract can't have a constructor that sets the owner? We can't forget to call this on L2 post regenesis
Other solutions:
- `take-dump.ts` calls `initialize()` with a configurable value
- We use the geth config option `address-manager-owner` and set the storage slot on startup

_Originally posted by @tynes in https://github.com/ethereum-optimism/optimism/issues/548#issuecomment-824434199_

**Comment by tynes** [comment]
Another solution is to set the owner in the constructor and then have a geth flag set the owner storage slot `0x00...0000` to the same address as the address manager owner at runtime. The owner could be set to `msg.sender`. We would need another flag for arbitrary contract deployment which is kind of annoying to add more flags but forgetting to set `initialize()`/being front-ran is really bad

**Comment by smartcontracts** [comment]
Note: we've decided that this will be handled by `chugsplash`. I'm going to leave this issue open as a reminder for ourselves.
