### ISSUE TITLE
Handling blob TX on L2

### ISSUE THREAD

**Issue by ImTei** [ethereum-optimism/optimism#5655]
Hi! I'm Tei from Test in Prod, working on [op-erigon](https://github.com/testinprod-io/op-erigon).

While merging erigon upstream into op-erigon, I noticed EIP-4844 blob TX was added to [erigon's latest release](https://github.com/ledgerwatch/erigon/releases/tag/v2.43.0).

It seems there's no spec about handling blob TX on L2, and blob TX is not yet merged to op-geth.

Is blob TX supported on L2? if not, how should it be blocked? (e.g. return specific error code)

I think it would be very helpful to exec-engine developers if there are specs for handling each EIP-2718 transaction type on L2.

Thank you!

**Comment by ajsutton** [comment]
We probably should add this to the specs somewhere but the L2 execution engine (op-geth or op-erigon) should be configured to support the Paris hard fork (ie the merge) as a base with the additional functionality from the bedrock spec like deposit transactions added on.  As such, EIP-4844 and blob TX aren't supported on L2. The rejection should be done in the same way that current L1 mainnet does as EIP-4844 isn't active there yet either. Usually this kind of functionality is controlled by the fork schedule specified in the genesis config (or chain spec for clients that use those).

**Comment by ImTei** [comment]
I understand. Thank you!

**Comment by emailtovamos** [comment]
Just curious on what all changes are scheduled to be made in Optimism once Ethereum supports protodanksharding?
