### ISSUE TITLE
BUG: the .sample.env should have DISABLE_LIVE_DEPLOYER=false

### ISSUE THREAD

**Issue by pedrovalido** [ethereum-optimism/optimism#5703]
**Describe the bug**

The .sample.env in packages/bedrock-contracts/ folder should have DISABLE_LIVE_DEPLOYER=false instead of true. This is causing the deploy contracts script to get stuck.

**To Reproduce**
In https://stack.optimism.io/docs/build/getting-started/#deploy-the-l1-contracts, trying the "npx hardhat deploy --network getting-started --tags l1" command get stuck.

**Expected behavior**
 The script should finish deploying the contracts and run the l1 rpc.

**Screenshots**
<img width="1670" alt="Screenshot 2023-05-13 at 17 38 52" src="https://github.com/ethereum-optimism/optimism/assets/80268365/49d913f2-98dd-4ed0-a0c2-f4768f916956">

**System Specs:**
 - OS: MacOs
 - Package Version (or commit hash): 4611198bf8bfd16563cc6bdf49bb35eed2e46801

**Additional context**

**Comment by nitantchhajed** [comment]
I changed it in my .env to false, but it still gets stuck

**Comment by devrajsinghrawat** [comment]
I am working on the resent update , I also faced this issue. 

I had to manually exit the process and restart again . 

![image](https://github.com/ethereum-optimism/optimism/assets/44597990/c2e2870e-067f-4b6a-aa38-d24d24134df0)

After restart, It moved further but then stuck at "Transferring ownership of the SystemDictator proxy.."
![image](https://github.com/ethereum-optimism/optimism/assets/44597990/243c3c65-1f85-4810-9cfc-3ac43c08cd6a)

Did you faced this?

**Comment by devrajsinghrawat** [comment]
I had to comment the code at 3 places 

![image](https://github.com/ethereum-optimism/optimism/assets/44597990/20ea1d05-ea62-482e-be0a-5ea3d353613b)

and here .. 

![image](https://github.com/ethereum-optimism/optimism/assets/44597990/d977d30d-dd87-4f59-8da7-c1212ca952e8)

**Comment by nitantchhajed** [comment]
I used this .env file and it runs smoothly.

# RPC for the L1 network to deploy to
L1_RPC=

# Private key for the deployer account
PRIVATE_KEY_DEPLOYER=

# Optional Tenderly details for a simulation link during deployment
TENDERLY_PROJECT=
TENDERLY_USERNAME=

# Optional boolean to define if cast commands should be printed.
# Useful during migration testing
CAST_COMMANDS=1

**Comment by pedrovalido** [comment]
> I would like to work on this @pedrovalido @chriswessels if still not resolved

@ashutosh887 , @chriswessels opened a PR and is working on it. If you want me to be a reviewer, I'd be glad to

**Comment by tynes** [comment]
This code has been removed and it should work now as expected
