### ISSUE TITLE
proxyd failover is not working

### ISSUE THREAD

**Issue by umeshtyagitvz** [ethereum-optimism/optimism#5717]
## Issue Description

Deployed proxyd in the kubernetes and i have been using two ethereum rpc node as its backends. But when first backend goes down it does not send the request to second backend.

## Steps to Reproduce

1. Clone this repository: [](https://github.com/ethereum-optimism/optimism/proxyd)
2. Build the docker image using given Dockerfile in the same repo
3. This is the proxyd config 
`whitelist_error_message = "rpc method is not whitelisted"
 ws_method_whitelist = [
  "eth_subscribe",
  "eth_accounts",
  "eth_call",
  "eth_chainId"
]
ws_backend_group = "providers"
[server]
rpc_host = "0.0.0.0"
rpc_port = 8888
ws_host = "0.0.0.0"
ws_port = 8889
max_body_size_bytes = 10485760
max_concurrent_rpcs = 1000
log_level = "info"
[metrics]
enabled = true
host = "0.0.0.0"
port = 9761
[backend]
response_timeout_seconds = 5
max_retries = 3
out_of_service_seconds = 180
max_latency_threshold = "30s"
max_degraded_latency_threshold = "10s"
max_error_rate_threshold = 0.3
[backends]
[backends.ethereum-1]
rpc_url = "http://ethereum-archive-node-erigon.ethereum-archive:8545"
ws_url = "ws://ethereum-archive-node-erigon.ethereum-archive:8545"
[backends.ethereum-2]
rpc_url = "http://ethereum-archive-n0-erigon.ethereum-archive-n0:8545"
ws_url = "ws://ethereum-archive-n0-erigon.ethereum-archive-n0:8545"
[backend_groups]
[backend_groups.providers]
backends = ["ethereum-1", "ethereum-2"]
[rpc_method_mappings]
eth_chainId = "providers"
[rate_limit]
enable_backend_rate_limiter = true`

## Expected Behavior

When first backend of the group fails, proxyd automatically marks it as out of service for a configurable period of time and fails over to another backend.

## Current Behavior

It is giving the error `context deadline exceeded` for both backends.

## Environment

- Kubernetes 

## Screenshots

![Screenshot from 2023-05-15 09-55-03](https://github.com/ethereum-optimism/optimism/assets/118340191/0391ae6f-a213-4f22-bebd-bd38a1d22fb1)

**Comment by rbalman** [comment]
@umeshtyagitvz
I don't see any activity in the issue however issue is closed. I am also seeing the same issue, just curious how have you been dealing with the issues?
