### ISSUE TITLE
Transaction Gossiping between L2 Execution Clients

### ISSUE THREAD

**Issue by pcw109550** [ethereum-optimism/optimism#5718]
Hi. According to the [Node Operator Guide Docs - configuring op-geth](https://community.optimism.io/docs/developers/bedrock/node-operator-guide/#configuring-op-geth),
> --rollup.disabletxpoolgossip: Disables transaction pool gossiping. While not required, it's useful to set this to true since transaction pool gossip is currently unsupported.

Does this mean there may a change to enable transaction pools between L2 execution clients in the future? Or L2 execution is strictly not allowed for tx gossiping? I think tx gossiping is needed for decentralized sequencer.

Also, can you please elaborate the sentence: `since transaction pool gossip is currently unsupported`? If we do not set `rollup.disabletxpoolgossip` flag, tx gossip works fine between two op-geth clients. Confirmed using hive integration tests - https://github.com/testinprod-io/hive/pull/9. So, technically tx gossiping IS supported, but not used. Also https://github.com/ethereum-optimism/hive/pull/54 mentions that tx gossiping works. 

My understanding is that, because we have explicit sequencer transaction forwarding using `rollup.sequencerhttp`, we do not need transaction pool gossiping yet, so we explicitly disabled tx gossiping(although it is not required). However in the near future, we will use tx gossiping for something, such as sequencer decentralization.

**Comment by protolambda** [comment]
> Does this mean there may a change to enable transaction pools between L2 execution clients in the future?

Maybe, this likely first has to be approved by governance. It does not break the state-transition, but does affect users who assume transaction-privacy in the current deployments.

> I think tx gossiping is needed for decentralized sequencer.

I think so as well

> So, technically tx gossiping IS supported, but not used.

Indeed. Tx-gossip can be useful between internal geth nodes, for tx-pool redundancy, without exposing transactions to the open. Users are free to enable it in their nodes, if they want to share their transactions. But we recommend not to, if they rely on tx-privacy. 

> My understanding is that, because we have explicit sequencer transaction forwarding using rollup.sequencerhttp, we do not need transaction pool gossiping yet, so we explicitly disabled tx gossiping(although it is not required). However in the near future, we will use tx gossiping for something, such as sequencer decentralization.

Exactly, no need to enable it if you configure the node to forward it to the sequencer endpoint directly. And long-term it may be enabled by users, if the transactions are to be routed to a distributed set of independent validators.
