### ISSUE TITLE
Using TypeChain for L1 artifacts overwrites L2 artifacts typescript bindings and vice versa

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#573]
**Describe the bug**
Not sure of the best place to put this issue but here.
@TransmissionsDev  noted some odd behavior when getting typescript bindings when using TypeChain.
Using TypeChain for L1 artifacts overwrites pre-existing L2 artifacts typescript bindings and vice versa

**Expected behavior**
Getting TypeScript bindings for L1 contract artifacts should not overwrite pre-existing TypeScript bindings for L2 contract artifacts or vice versa.

**Comment by TransmissionsDev** [comment]
I don't think this is really an issue with Optimism (probs need to be solved on typechain's port), but yea if you run compile twice (one for L1 contracts and one for l2 contracts), whichever layer was compiled for last will override the typechain defs for other layer.

**Comment by TransmissionsDev** [comment]
oo okay i guess this can be solved by optimism :o
