### ISSUE TITLE
Interact with private network

### ISSUE THREAD

**Issue by Neoblock8** [ethereum-optimism/optimism#5755]
Hi,
 Need to interact Optimism with Private network. Where to give URL of the private network?
 Can anyone provide me a solution?

**Comment by tynes** [comment]
Use the local devnet, you should be able to run `make devnet-up` in the root

**Comment by Neoblock8** [comment]
> Use the local devnet, you should be able to run `make devnet-up` in the root

Can i give any other server ip, instead of localhost?

If yes, where can i change the ip?

**Comment by Neoblock8** [comment]
> Use the local devnet, you should be able to run `make devnet-up` in the root

Hi @tynes 

when i deploying the contract, Iam getting this error:

![image](https://github.com/ethereum-optimism/optimism/assets/81068101/30c504ad-b108-421e-9924-45cc1001dd39)
