### ISSUE TITLE
Flickering integration test #2 (symptom: gas estimation value mismatch)

### ISSUE THREAD

**Issue by snario** [ethereum-optimism/optimism#585]
We're seeing a flickering integration test related to ETH gas estimation:

**Example**
https://github.com/ethereum-optimism/optimism/runs/2415971705?check_suite_focus=true

**Log**
```
  1) Native ETH Integration Tests
       estimateGas
         Should estimate gas for ETH transfer:
      AssertionError: expected { Object (_hex, _isBigNumber) } to deeply equal { Object (_hex, _isBigNumber) }
      + expected - actual
       {
      -  "_hex": "0x0341be"
      +  "_hex": "0x03422a"
         "_isBigNumber": true
       }
      at Context.<anonymous> (test/native-eth.spec.ts:38:43)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by tynes** [comment]
Tracking the different times that it fails to observe the non-determinism:

https://github.com/ethereum-optimism/optimism/pull/593/checks?check_run_id=2422317833
```
      AssertionError: expected { Object (_hex, _isBigNumber) } to deeply equal { Object (_hex, _isBigNumber) }
      + expected - actual

       {
      -  "_hex": "0x0341be"
      +  "_hex": "0x03422a"
         "_isBigNumber": true
       }
```

**Comment by tynes** [comment]
https://github.com/ethereum-optimism/optimism/pull/592/checks?check_run_id=2422353003
```
     AssertionError: expected { Object (_hex, _isBigNumber) } to deeply equal { Object (_hex, _isBigNumber) }
      + expected - actual

       {
      -  "_hex": "0x0341be"
      +  "_hex": "0x03422a"
         "_isBigNumber": true
       }
      
```

It appears to be deterministically different. My guess is that it is a race condition in hardhat

**Comment by smartcontracts** [comment]
> It appears to be deterministically different. My guess is that it is a race condition in hardhat

The test in question is https://github.com/ethereum-optimism/optimism/blob/eef1df4d63fd1b483beda63293ea1746861c3e2a/integration-tests/test/native-eth.spec.ts#L44-L49, which tests `estimateGas` inside of `l2geth`.

I wonder if this could be caused by the use of a random address. I guess that could maybe change the number of zero bytes in the calldata and cause the gas estimation to differ? I'll try to use a fixed address and see what happens.

**Comment by snario** [comment]
@gakonst is this fixed?

**Comment by gakonst** [comment]
[Should be.](https://github.com/ethereum-optimism/optimism/blame/master/integration-tests/test/native-eth.spec.ts#L46) Closing optimistically.
