### ISSUE TITLE
err="failed to determine L2BlockRef of height 4061224, could not get payload: not found"

### ISSUE THREAD

**Issue by timurgum** [ethereum-optimism/optimism#5855]
Faced such an error when deploying optimism bedrock goerli, if anyone has encountered such an error, tell me?

`op.node    | t=2023-06-01T16:50:15+0000 lvl=info msg="Rollup Config"            l2_chain_id=420 l2_network=goerli l1_chain_id=5 l1_network=goerli l2_start_time=1,673,550,516 l2_block_hash=0x0f783549ea4313b784eadd9b8e8a69913b368b7366363ea814d7707ac505175f l2_block_number=4,061,224 l1_block_hash=0x6ffc1bf3754c01f6bb9fe057c1578b87a8571ce2e9be5ca14bace6eccfd336c7 l1_block_number=8,300,214 regolith_time="@ 1679079600 ~ Fri Mar 17 19:00:00 UTC 2023"
op.node    | t=2023-06-01T16:50:16+0000 lvl=info msg="loaded new runtime config values!" p2p_seq_address=0x715b7219D986641DF9eFd9C7Ef01218D528e19ec
op.node    | t=2023-06-01T16:50:16+0000 lvl=eror msg="Error initializing the rollup node" err="failed to determine L2BlockRef of height 4061224, could not get payload: not found"
op.node    | t=2023-06-01T16:50:16+0000 lvl=eror msg="Unable to create the rollup node"   error="failed to determine L2BlockRef of height 4061224, could not get payload: not found"
op.node    | t=2023-06-01T16:50:16+0000 lvl=crit msg="Application failed"                 message="failed to determine L2BlockRef of height 4061224, could not get payload: not found"`

my op-node config

`   command: >
      op-node
      --network=goerli
      --l2.jwt-secret=./jwt.txt
      --l2=http://op.geth:8551
      --rpc.addr=0.0.0.0
      --rpc.port=9545
      --l1=https://rpc.ankr.com/eth_goerli
      --rollup.config=/opt/bedrock/node/op/rollup.json`

**Comment by tynes** [comment]
This looks like a misconfiguration

**Comment by jungrae-prestolabs** [comment]
Me too. (op-node/v1.1.1)
command is below with masking
```
op-node --l1=https://{}:8545 --l2=ws://127.0.0.1:8546 --network=mainnet --rpc.addr=0.0.0.0
--rpc.port=9545 --l2.jwt-secret=/pvc/jwt.txt --rollup.config=../rollup.json
```

**Comment by tynes** [comment]
Try using the `--network` flag instead of passing a rollup config

**Comment by protolambda** [comment]
You should not pass both `--network` and `--rollup.config` flags. You can choose a pre-configured network with the first flag, and a custom network with the latter. And op-geth has to run `geth init` with the corresponding `genesis.json` to set up the data-dir, or start with a prepared data-dir in case of op-mainnet / op-goerli (download links can be found in the docs site). 

Hope that helps, please re-open this issue if the problem persists, cheers.
