### ISSUE TITLE
OP Stack docs broken - links on the left nav dont work

### ISSUE THREAD

**Issue by momack2** [ethereum-optimism/optimism#5863]
Hi friends! I believe the left nav links in the OP Stack docs are broken right now: https://stack.optimism.io/

<img width="316" alt="CleanShot 2023-06-01 at 20 13 14@2x" src="https://github.com/ethereum-optimism/optimism/assets/618519/9f6babfa-aa43-4794-89c9-f7d909aa5927">

All of these just link to the getting started page, instead of the pages they're supposed to. They change the url in the address bar, but just display the same page.

**Comment by smartcontracts** [comment]
On it, thank you! https://github.com/ethereum-optimism/optimism/pull/5881

**Comment by qbzzt** [comment]
Thank you for the error report. We are pretty sure we fixed it - can you verify it works OK for you?

**Comment by momack2** [comment]
Yep! Good now
