### ISSUE TITLE
Emit event for a relayed message even if the call reverts

### ISSUE THREAD

**Issue by TransmissionsDev** [ethereum-optimism/optimism#587]
**Is your feature request related to a problem? Please describe.**
If a relayed message performs a call that fails, the `RelayedMessage` event is not emitted (only on success). This means that the watcher will not pick up the relayed event. There are many applications I can think of where a user needs to be able to detect if a relayed message failed with the watcher, and this is currently not possible.

**Describe the solution you'd like**
I can think of a couple methods:
- Add a `success` param to the `RelayedMessage` event and emit it in both cases.
- Add a `FailedRelayedMessage` event and emit that if the call fails.
- Emit `RelayedMessage` in both cases with no additional context.

**Comment by smartcontracts** [comment]
I think some of our off-chain services rely on the current `RelayedMessage` event, so I'm gonna go with the strategy of adding a new `FailedRelayedMessage` event instead. Will make a PR in a sec.

**Comment by TransmissionsDev** [comment]
Awesome. @smartcontracts would you also be able to make a PR to update the watcher's `getL2TransactionReceipt` function to support the failed messages as well?
