### ISSUE TITLE
op-node  invalid network mainnet

### ISSUE THREAD

**Issue by zhy827827** [ethereum-optimism/optimism#5891]
op-node --l1=http://192.1.1.9:8545 --l2=http://127.0.0.1:8551 --network=mainnet --l1.trustrpc --rpc.addr=0.0.0.0 --rpc.port=9545 --l2.jwt-secret=/mnt/secrets/jwt.txt --log.level debug

t=2023-06-05T09:07:18+0000 lvl=info msg="Initializing Rollup Node"
ERROR[06-05|09:07:18.067] Unable to create the rollup node config  error="invalid network mainnet"
CRIT [06-05|09:07:18.067] Application failed                       message="invalid network mainnet"

Is it necessary to run after a hard fork?

**Comment by tynes** [comment]
Try the following release: https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.1.0

**Comment by smartcontracts** [comment]
Seems to work fine. Make sure to use the latest release.
