### ISSUE TITLE
OP Stack getting started guide is broken

### ISSUE THREAD

**Issue by tobias-malm** [ethereum-optimism/optimism#5930]
The OP Stack guide for deploying a Bedrock optimistic roll-up gets stuck during L1 contract deployment.
Specifically, the initializing transactions do not go through.

**To Reproduce**
Precisely follow the guide at [https://stack.optimism.io/docs/build/getting-started/#deploy-the-l1-contracts](https://stack.optimism.io/docs/build/getting-started/#deploy-the-l1-contracts)

Deployment gets stuck around [step 19, initialize SystemDictator](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/deploy/019-SystemDictatorInit.ts)

Running the script for the first time gets stuck after all contracts are deployed + one more transaction (`upgradeToAndCall`). Logs attached, "appendix 1".
Subsequent runs of the script get stuck on the next transaction (`changeAdmin`). Logs attached, "appendix 2".

**Reproducibility**
Looking on-chain, there seem to be several people who tried deploying the OP Stack and got stuck on the same step.
Notice how all these addresses get stuck trying to call `changeAdmin` over and over.
[this person, 8 days ago](https://goerli.etherscan.io/address/0xf1531525e400939f8d23a8382b593cc1abb00eb8)
[this person, 5 days ago](https://goerli.etherscan.io/address/0xacabac3922cfe82d781ef4af9c101b51382948db)
[this person, 1 day ago](https://goerli.etherscan.io/address/0x115d0d47ec3c1237827ca6c79ba07a6fa0c7d552)

**Appendix 1, logs of initial run**
```
<...>
Deployed SystemDictator at 0x671870A12D48BC4F9212B2392934131CB9B715De
Upgrading the SystemDictator proxy...
Live deployer manually disabled

    Please transfer ProxyAdmin (proxy) owner to MSD
      - ProxyAdmin address: 0xEA279c896029051278476411b7b71598804ef102
      - MSD address: 0x9311EC21cB0541965CBE225a2B9E58D1B8E34a25

JSON transaction parameters:
{
  "from": "0xd4C54f52B5beC574AE113DfEfBc88999c3535bD2",
  "to": "0xEA279c896029051278476411b7b71598804ef102",
  "data": "0xf2fde38b0000000000000000000000009311ec21cb0541965cbe225a2b9e58d1b8e34a25"
}
cast send 0xEA279c896029051278476411b7b71598804ef102 0xf2fde38b0000000000000000000000009311ec21cb0541965cbe225a2b9e58d1b8e34a25 --from 0xd4C54f52B5beC574AE113DfEfBc88999c3535bD2

    Please transfer AddressManager (proxy) owner to MSD
      - AddressManager address: 0x3dE6faF81C1B11cD6ea6E7e1655b975e0785b83e
      - MSD address: 0x9311EC21cB0541965CBE225a2B9E58D1B8E34a25

JSON transaction parameters:
{
  "from": "0xd4C54f52B5beC574AE113DfEfBc88999c3535bD2",
  "to": "0x3dE6faF81C1B11cD6ea6E7e1655b975e0785b83e",
  "data": "0xf2fde38b0000000000000000000000009311ec21cb0541965cbe225a2b9e58d1b8e34a25"
}
cast send 0x3dE6faF81C1B11cD6ea6E7e1655b975e0785b83e 0xf2fde38b0000000000000000000000009311ec21cb0541965cbe225a2b9e58d1b8e34a25 --from 0xd4C54f52B5beC574AE113DfEfBc88999c3535bD2

    Please transfer L1StandardBridgeProxy (proxy) owner to MSD
      - L1StandardBridgeProxy address: 0xBC01e4EeF571EC46adDDCCc1a8288F4573e66a11
      - MSD address: 0x9311EC21cB0541965CBE225a2B9E58D1B8E34a25

JSON transaction parameters:
{
  "from": "0xd4C54f52B5beC574AE113DfEfBc88999c3535bD2",
  "to": "0xBC01e4EeF571EC46adDDCCc1a8288F4573e66a11",
  "data": "0x13af40350000000000000000000000009311ec21cb0541965cbe225a2b9e58d1b8e34a25"
}
cast send 0xBC01e4EeF571EC46adDDCCc1a8288F4573e66a11 0x13af40350000000000000000000000009311ec21cb0541965cbe225a2b9e58d1b8e34a25 --from 0xd4C54f52B5beC574AE113DfEfBc88999c3535bD2

    Please transfer L1ERC721BridgeProxy (proxy) owner to MSD
      - L1ERC721BridgeProxy address: 0x8Fc2551b37720f8846034aEa255A9454Fe053AE5
      - MSD address: 0x9311EC21cB0541965CBE225a2B9E58D1B8E34a25

JSON transaction parameters:
{
  "from": "0xd4C54f52B5beC574AE113DfEfBc88999c3535bD2",
  "to": "0x8Fc2551b37720f8846034aEa255A9454Fe053AE5",
  "data": "0x8f2839700000000000000000000000009311ec21cb0541965cbe225a2b9e58d1b8e34a25"
}
cast send 0x8Fc2551b37720f8846034aEa255A9454Fe053AE5 0x8f2839700000000000000000000000009311ec21cb0541965cbe225a2b9e58d1b8e34a25 --from 0xd4C54f52B5beC574AE113DfEfBc88999c3535bD2
<stuck here for 20 minutes, no changes>
```

**Appendix 2, logs of subsequent runs**
```
No files changed, compilation skipped
skipping ProxyAdmin, using existing at 0xEA279c896029051278476411b7b71598804ef102
skipping Lib_AddressManager, using existing at 0x3dE6faF81C1B11cD6ea6E7e1655b975e0785b83e
skipping Proxy__OVM_L1StandardBridge, using existing at 0xBC01e4EeF571EC46adDDCCc1a8288F4573e66a11
skipping L2OutputOracleProxy, using existing at 0x515Ac9A83F0e6690f0cbDdf31C69a57658d20bFe
skipping Proxy__OVM_L1CrossDomainMessenger, using existing at 0x9C3452b75d174E44936fD7CE54e514B9CDA7AB5A
skipping OptimismPortalProxy, using existing at 0x186800567BD3513a7d5Fa92B09F04F285999D569
skipping OptimismMintableERC20FactoryProxy, using existing at 0x57E85A732C4B386fFb665D9BbAfF15c5B45504Fb
skipping L1ERC721BridgeProxy, using existing at 0x8Fc2551b37720f8846034aEa255A9454Fe053AE5
skipping SystemConfigProxy, using existing at 0x617940b6a9715bbf64546C66d0B1b39fcA57C8B4
skipping SystemDictatorProxy, using existing at 0x9311EC21cB0541965CBE225a2B9E58D1B8E34a25
skipping L1CrossDomainMessenger, using existing at 0xE50036d9423c58D98cF546A3C610e5b70c9e3389
skipping L1StandardBridge, using existing at 0xb41cc07697794F4AcDD379C3977d206e3698e958
skipping L2OutputOracle, using existing at 0x68283f43CbE9dA77657a2F71acD4Fa70e1dfF38E
WARNING: setting OptimismPortal.GUARDIAN to 0xd4c54f52b5bec574ae113dfefbc88999c3535bd2 and it has no code
skipping OptimismPortal, using existing at 0x76f5B15E94aD58bB92Cb57dc68970b8f5B96d458
skipping OptimismMintableERC20Factory, using existing at 0xf85BF44F8E745E3a0C27d43468F3f92A4780B573
skipping L1ERC721Bridge, using existing at 0x3d2b13365A7FB751255e0Ac922994fF28226a75f
skipping PortalSender, using existing at 0x56fC18e7940f392694834319fB94881F83d1Ba65
skipping SystemConfig, using existing at 0xa525e382De4597e438ffD8e085151226DEBB378C
skipping SystemDictator, using existing at 0x671870A12D48BC4F9212B2392934131CB9B715De
Transferring ownership of the SystemDictator proxy...
<stuck here for 20 minutes, no changes>
```

**Comment by zeeshanhanif** [comment]
Hi I'm facing the same problem

I tried to find the bug and it seems there is problem in deployment scripts
There is scripts file named '019-SystemDictatorInit.ts' in code folder '\optimism\packages\contracts-bedrock\deploy\019-SystemDictatorInit.ts'
Whenever script reachs to line number 133 at which there is await call for 'awaitCondition' function this function keeps waiting for right condition, which never happens and code keep waiting for it
Same goes for line number 187 of same file

Also in file '020-SystemDictatorSteps-1.ts' and '021-SystemDictatorSteps-2.ts' we have same problem.
Script stuck on 'awaitCondition'
And 'awaitCondition' is provided with very high repetition number like 1000

**Comment by smartcontracts** [comment]
Seems to be a valid report. Going to send this over to the docs squad to get this resolved.

**Comment by nitantchhajed** [comment]
@zeeshanhanif @tobias-malm change the `.env` in `packages/contracts-bedrock` to -

`# RPC for the L1 network to deploy to
L1_RPC=<L1_RPC>

# Private key for the deployer account
PRIVATE_KEY_DEPLOYER=<PRIVATE_KEY>

# Optional Tenderly details for a simulation link during deployment
TENDERLY_PROJECT=
TENDERLY_USERNAME=

# Optional boolean to define if cast commands should be printed.
# Useful during migration testing
CAST_COMMANDS=1`

It worked for me

**Comment by zeeshanhanif** [comment]
@nitantchhajed : 
I already have `L1_RPC`, `PRIVATE_KEY_DEPLOYER` and `CAST_COMMANDS=1` in .env.
Now I have added other two add as well `TENDERLY_PROJECT` and `TENDERLY_USERNAME`

But I'm still facing the same issue

**Comment by nitantchhajed** [comment]
@zeeshanhanif  try `DISABLE_LIVE_DEPLOYER=false` bcs the above .env worked for me. Optimism have made many changes in their deployment typescript files

**Comment by zeeshanhanif** [comment]
@nitantchhajed : No, still the same issue

**Comment by nitantchhajed** [comment]
@zeeshanhanif  can you please look into this? this may be helpful https://github.com/ethereum-optimism/optimism/pull/5993/files

**Comment by cspannos** [comment]
That worked for me. Thanks!

**Comment by zeeshanhanif** [comment]
@nitantchhajed : it worked for file named '019-SystemDictatorInit.ts' but now its stuck on file named '020-SystemDictatorSteps-1.ts' and at same 'awaitCondition' at line 146.
I tried to apply same lower case function in this file as well but it didn't worked

**Comment by nitantchhajed** [comment]
@smartcontracts can you please look into this? Lots of people facing this issue while deploying the `L1 Contracts`. Thank you!

**Comment by zeeshanhanif** [comment]
Anyone can look into this? This is critical step for anyone who wants to setup OP Stack and facing problem on L1 contracts deployment

**Comment by nitantchhajed** [comment]
@zeeshanhanif  see https://github.com/ethereum-optimism/optimism/issues/5703 they mentioned that code is fixed, I suggest to to pull the latest code and try the process again.

**Comment by zeeshanhanif** [comment]
Thanks @nitantchhajed :
I tried the required changes mentioned in #5703 , process moves forward and start executing. 
Now it ended with following message can you please see if this is right message to finish the L1 contract deployment.

![image](https://github.com/ethereum-optimism/optimism/assets/1311782/47c109fa-34b8-4c20-a87e-fdb4f56fcae1)

**Comment by cspannos** [comment]
My deployment keeps hanging at 
`Upgraded and initialized OptimismPortal
OptimismPortal version: 1.7.0`
 
It seems to be repeating `eth_chainId` and `eht_call` methods. Any tips are greatly apprecaited. 

More logs:
<img width="988" alt="Screenshot 2023-06-21 at 10 19 33" src="https://github.com/ethereum-optimism/optimism/assets/5671161/30e9806a-4187-441c-8970-c56e22f27f87">

**Comment by matjazv** [comment]
> My deployment keeps hanging at `Upgraded and initialized OptimismPortal OptimismPortal version: 1.7.0`
> 
> It seems to be repeating `eth_chainId` and `eht_call` methods. Any tips are greatly apprecaited.
> 
> More logs: <img alt="Screenshot 2023-06-21 at 10 19 33" width="988" src="https://user-images.githubusercontent.com/5671161/247499958-30e9806a-4187-441c-8970-c56e22f27f87.png">

Same here. I have exactly the same problem.
It stucks at `OptimismPortal version: 1.7.0` and repeatedly calls `eth_chainId` and `eht_call` methods.

**Comment by tynes** [comment]
The guide has been redone, please reopen an issue if you continue to have problems
