### ISSUE TITLE
Issue in withdrawETH() : STATE_ROOT_NOTPUBLISHED message status: 2

### ISSUE THREAD

**Issue by nitantchhajed** [ethereum-optimism/optimism#5992]
**Describe the bug**
I am running and OP-Stack Based chain, Depostis are working fine, but my withdrawals are stuck. It is stuck at the `crossChainMessenger.waitForMessageStatus(response.hash, optimismSDK.MessageStatus.READY_TO_PROVE)` **Line no.60** for a long period of time. I don't know where is the problem coming from. I have attached the Screenshot of the code and console output. I have all the components running `op-geth` , `op-node`, `op-batcher`, `op-proposer`. My challenge period is 60 seconds.

`
           AddressManager: "0xBd3cbCe7Dbc6Bb7c33b36D4B5E2adf3F186701E4",   
            L1CrossDomainMessenger: "0x3B251e2998009AB5034228CB71E95D71D9869322",    
            L1StandardBridge: "0x40DB2D3424286bEc850Aeec030cA6cCf17D07636",   
            OptimismPortal: "0xfEEE0247901eCE2FD8a72371e0C8F4F5b081CacA",  
            L2OutputOracle: "0xe2A596B5cb0134b60FC0396c9cA82867F5b35073" 
`

OP-Batcher - 
`./bin/op-batcher \
    --l2-eth-rpc=http://0.0.0.0:8545 \
    --rollup-rpc=http://0.0.0.0:8547 \
    --poll-interval=1s \
    --sub-safety-margin=6 \
    --num-confirmations=1 \
    --safe-abort-nonce-too-low-count=3 \
    --resubmission-timeout=30s \
    --rpc.addr=0.0.0.0 \
    --rpc.port=8548 \
    --rpc.enable-admin \
    --max-channel-duration=5 \
    --l1-eth-rpc=https://eth-goerli.g.alchemy.com/v2/.. \
    --private-key=f********************************************
`

OP-proposer
`./bin/op-proposer \
    --poll-interval 12s \
    --rpc.port 8560 \
    --rollup-rpc http://localhost:8547 \
    --l2oo-address 0x555E7FB9E8743e28fF0c8b02f1F96503E0F615c3 \
    --private-key ********************************* \
    --l1-eth-rpc https://eth-goerli.g.alchemy.com/v2/..
`
OP-node
`./bin/op-node \
        --l2=http://localhost:8551 \
        --l2.jwt-secret=./jwt.txt \
        --sequencer.enabled \
        --sequencer.l1-confs=3 \
        --verifier.l1-confs=3 \
        --rollup.config=./rollup.json \
        --rpc.addr=0.0.0.0 \
        --rpc.port=8547 \
        --p2p.listen.ip=0.0.0.0 \
        --p2p.listen.tcp=9003 \
        --p2p.listen.udp=9003 \
        --rpc.enable-admin \
        --p2p.sequencer.key=******************************** \
        --l1=https://eth-goerli.g.alchemy.com/v2/.. \
        --l1.rpckind=alchemy
`

RPC: https://racetestnet.io
Chain ID: 90001
BlockExplorer : https://testnet.racescan.io

**Screenshots**

![Screenshot from 2023-06-12 14-28-00](https://github.com/ethereum-optimism/optimism/assets/96972634/c009036b-9e88-4dee-9f3b-3c9c440b6eaf)

**Comment by qbzzt** [comment]
The most likely source of this problem is that `op-proposer` does not have the ETH for output proposals, however, that is clearly not the case. [New output proposals are happening](https://goerli.etherscan.io/address/0x555E7FB9E8743e28fF0c8b02f1F96503E0F615c3). 

This being the case, can you check the message status? 

```js
crossChainMessenger.getMessageStatus(response.hash)
```

What happens if you restart `op-proposer`?

@smartcontracts , this is beyond my skillset.

**Comment by nitantchhajed** [comment]
Hey @qbzzt thanks for digging into it, I found the solution for it. Can you please check if it is the correct explanation or not ?

https://github.com/ethereum-optimism/optimism/issues/5507#issuecomment-1587457337

**Comment by nitantchhajed** [comment]
@qbzzt It still works the same, STATE_ROOT doesn't publish.
