### ISSUE TITLE
Can't run op-proposer

### ISSUE THREAD

**Issue by JohnOldman0202** [ethereum-optimism/optimism#6003]
I try run optimism follow document. Everything working fine. But when i run op-proposer
```
./bin/op-proposer \
    --poll-interval 12s \
    --rpc.port 8560 \
    --rollup-rpc http://localhost:8547 \
    --l2oo-address $L2OO_ADDR \
    --private-key $PROPOSER_KEY \
    --l1-eth-rpc $L1_RPC
```
Can't run this command
Error:
```
INFO [06-13|08:28:14.341] Initializing L2 Output Submitter 
ERROR[06-13|08:28:14.612] Unable to create the L2 Output Submitter error="execution reverted: Proxy: implementation not initialized"
CRIT [06-13|08:28:14.612] Application failed                       message="execution reverted: Proxy: implementation not initialized"
```

**Comment by dandlezzz** [comment]
Experiencing the same issue.

**Comment by nitantchhajed** [comment]
make sure you have all the [contracts ](https://stack.optimism.io/docs/build/getting-started/#deploy-the-l1-contracts) deployed successfully and you are using the correct private key `$PROPOSER_KEY` for the `PROPOSER` address you have entered in `getting-started.json`

**Comment by dandlezzz** [comment]
@nitantchhajed  yes, that was the problem.

**Comment by smartcontracts** [comment]
Yeah like @nitantchhajed said, likely an issue with either contracts not being deployed, using the wrong address, or possibly also using the wrong RPC
