### ISSUE TITLE
Are there any official public nodes available for syncing my node?

### ISSUE THREAD

**Issue by VetchM** [ethereum-optimism/optimism#6014]
To start my own OP node, I'll need one L1 URL for `op-geth` and one L2 URL for `op-node`. Using server from node providers (like Alchemy) may eventually reach their free trial limit, and I will have to pay a premium to keep my node running. Is there a plan to provide an official public node?

**Comment by smartcontracts** [comment]
Free tier alchemy can successfully sync `op-geth` if you specify `--l1.rpckind=alchemy`, the L2 URL that you need for `op-node` is just the `op-geth` authenticated API usually located on port 8551

**Comment by protolambda** [comment]
Docs: https://docs.optimism.io/builders/node-operators/rollup-node
