### ISSUE TITLE
Move ECDSAContractAccount + ProxyEOA into predeploys

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#605]
**Is your feature request related to a problem? Please describe.**
`OVM_ECDSAContractAccount` and `OVM_ProxyEOA` are predeployed contracts that are currently sitting in their own `accounts` folder. I'd like to move them into the `predeploys` folder instead.

**Describe the solution you'd like**
I'd like to move `OVM_ECDSAContractAccount` and `OVM_ProxyEOA` into the `predeploy` folders. I don't really see the need for a separate `accounts` folder, especially since these contracts *are* indeed predeployed.

**Comment by maurelian** [comment]
Seems reasonable to me!
