### ISSUE TITLE
Cannot send a tx with a gasLimit over 9m

### ISSUE THREAD

**Issue by K-Ho** [ethereum-optimism/optimism#607]
**Is your feature request related to a problem? Please describe.**
If a transaction is going to have a fee of over 9m gwei, `estimateGas` will return a value higher than 9m and then we will need to send it with a gasLimit of over 9m. 
We're getting an error: `ProviderError: Transaction gasLimit (11027224) is greater than max gasLimit (9000000)`

**Describe the solution you'd like**
Allow users to send transactions with a gasLimit > the transaction gasLimit.

**Describe alternatives you've considered**
Definitely worth brainstorming medium-term solutions around our hacky "estimateGas is calculateFeeInGwei".

**Additional context**

**Comment by smartcontracts** [comment]
Closed by #695
