### ISSUE TITLE
estimateGas can return under 21000

### ISSUE THREAD

**Issue by K-Ho** [ethereum-optimism/optimism#608]
**Is your feature request related to a problem? Please describe.**
Right now, estimateGas can return under 21000 if the "feeInGwei" is less than 21000 gwei. However, Metamask prevents sending transactions with a gasLimit of under 21000. 

**Describe the solution you'd like**
A potential hack here is for `estimateGas` to return the `Max(21000, estimateGas(tx))`

**Describe alternatives you've considered**
Really, we need to look into alternatives, as it appears the downstream effects of this hack will be very numerous.

**Comment by smartcontracts** [comment]
> it appears the downstream effects of this hack will be very numerous.

What sort of downstream effects have you observed?

**Comment by K-Ho** [comment]
To clarify: there are downstream effects of having estimateGas be “estimateFeeInGwei” - results in confusion around gasUsed being > that gasLimit, these metamask issues, issues with sending a tx with a gasLimit greater than the block gas limit.

**Comment by smartcontracts** [comment]
Closed by #695
