### ISSUE TITLE
l2_network = unknown L2 in Op-Stack chain

### ISSUE THREAD

**Issue by nitantchhajed** [ethereum-optimism/optimism#6106]
How to change this l2_network in OP-node, there is no configuration parameter in getting-started.JSON for it, neither in Rollup.json file.

this is my OP-stack chain

![clipboard-image_5](https://github.com/ethereum-optimism/optimism/assets/96972634/b8605f27-e777-4afb-b0db-b0901061034b)

**Comment by huihzhao** [comment]
Also encoutner this problem 
<img width="814" alt="image" src="https://github.com/ethereum-optimism/optimism/assets/98204090/bec9d180-b1f6-45d1-a7df-2a3c86daffed">

**Comment by nitantchhajed** [comment]
@smartcontracts @tynes any solution for this ??

**Comment by Kelvyne** [comment]
I believe the mapping here has to be updated https://github.com/ethereum-optimism/optimism/blob/e4985632b33861c27cc939b84ef30e94f137b609/op-node/chaincfg/chains.go#L13

**Comment by qbzzt** [comment]
To use the SDK in OP Stack you need to give it the contract addresses. See https://stack.optimism.io/docs/build/sdk/#contract-addresses

**Comment by nitantchhajed** [comment]
@qbzzt I think you got me wrong, I am not using SDK here.

**Comment by nitantchhajed** [comment]
> I believe the mapping here has to be updated
> 
> https://github.com/ethereum-optimism/optimism/blob/e4985632b33861c27cc939b84ef30e94f137b609/op-node/chaincfg/chains.go#L13

@Kelvyne do you mean I have to update this mapping with the configuration in my getting-started.json, after I update it what should I do, because I have to mention this `Mainnet` mapping somewhere to use it, where it would be ??

**Comment by Kelvyne** [comment]
In order to replace `unknown L2` with your L2 name, you would have to add your Rollup configuration in the chaincfg/chains.go file. This way when logging the rollup config at startup, op-node would correctly log the name of the L2.

**Comment by Kelvyne** [comment]
`op-node` uses chaincfg to retrieve known chain names : 
https://github.com/ethereum-optimism/optimism/blob/develop/op-node/cmd/main.go#L109

**Comment by nitantchhajed** [comment]
@Kelvyne Thanks for the help !
