### ISSUE TITLE
Deploying L1 contracts on Goerli fails when following instructions of OP Stack Docs

### ISSUE THREAD

**Issue by AndreasKendziorra** [ethereum-optimism/optimism#6141]
**Describe the bug**
When following the [current](https://github.com/ethereum-optimism/optimism/blob/15660862779df0d171e7725050d5f1483c8d8f95/docs/op-stack/src/docs/build/getting-started.md) _getting started_ page of the OP Stack documentation, one gets at the [first deployment step](https://github.com/ethereum-optimism/optimism/blob/15660862779df0d171e7725050d5f1483c8d8f95/docs/op-stack/src/docs/build/getting-started.md?plain=1#L243), which is this one:
```bash
forge script scripts/Deploy.s.sol:Deploy --private-key $PRIVATE_KEY --broadcast --rpc-url $ETH_RPC_URL
```
The following error will be shown
```
, $.l2GenesisRegolithTimeOffset) 
    │   │   └─ ← "No matching value or array found for key $.l2GenesisRegolithTimeOffset"
    │   └─ ← 0 bytes of code
    └─ ← "No matching value or array found for key $.l2GenesisRegolithTimeOffset"



== Logs ==
  Connected to network with chainid 5
  Storing temp deployment data in /Users/userA/OP_stack_deployment/optimism/packages/contracts-bedrock/deployments/goerli/.deploy
  DeployConfig: reading file /Users/userA/OP_stack_deployment/optimism/packages/contracts-bedrock/deploy-config/goerli.json
Error: 
Script failed.
```

**To Reproduce**
1. Follow all steps of the  [getting started](https://github.com/ethereum-optimism/optimism/blob/15660862779df0d171e7725050d5f1483c8d8f95/docs/op-stack/src/docs/build/getting-started.md) page of the OP Stack doc up to [this line](https://github.com/ethereum-optimism/optimism/blob/15660862779df0d171e7725050d5f1483c8d8f95/docs/op-stack/src/docs/build/getting-started.md?plain=1#L243) (inclusive).

**Expected behavior**
Deployment succeeds.

**System Specs:**
 - OS: mac OS
 - commit hash: [1566086](https://github.com/ethereum-optimism/optimism/commit/15660862779df0d171e7725050d5f1483c8d8f95)

**Comment by tynes** [comment]
Be sure to set the environment variables, try again after setting them correctly

**Comment by tynes** [comment]
In particular `DEPLOYMENT_CONTEXT` is not set

**Comment by AndreasKendziorra** [comment]
>In particular DEPLOYMENT_CONTEXT is not set

I also followed [these instructions](https://github.com/ethereum-optimism/optimism/blob/15660862779df0d171e7725050d5f1483c8d8f95/docs/op-stack/src/docs/build/getting-started.md?plain=1#L195-L211) regarding environment variables. So, my `.envrc` file contains
```
export DEPLOYMENT_CONTEXT=getting-started
```
What actually fixed it for me was adding the following line to [goerli.json](https://github.com/ethereum-optimism/optimism/blob/0e2e7112feb8f2a62d463be298409ba09cb0d8f5/packages/contracts-bedrock/deploy-config/goerli.json):
```json
"l2GenesisRegolithTimeOffset": "0x0",
```
But I'm not sure if this value was missing on purpose in this file or not.

**Comment by qbzzt** [comment]
Can you try the latest instructions? I updated them with some missing steps (or at least, missing if you don't have a recent enough version of Foundry).

https://stack.optimism.io/docs/build/getting-started/

**Comment by AndreasKendziorra** [comment]
Right. direnv was not properly set up. Now it is indeed using `getting-started.json`, but this time I get the following error when executing [this line](https://github.com/ethereum-optimism/optimism/blob/d5ccf81966bc2fc650c802fd4b80a30e98843a0b/docs/op-stack/src/docs/build/getting-started.md?plain=1#L252):
```
, $.faultGameAbsolutePrestate) 
    │   │   └─ ← "No matching value or array found for key $.faultGameAbsolutePrestate"
    │   └─ ← 0 bytes of code
    └─ ← "No matching value or array found for key $.faultGameAbsolutePrestate"



== Logs ==
  Connected to network with chainid 5
  Storing temp deployment data in /Users/userA/optimism/packages/contracts-bedrock/deployments/getting-started/.deploy
  DeployConfig: reading file /Users/userA/optimism/packages/contracts-bedrock/deploy-config/getting-started.json
Error: 
Script failed.
```
There is no value set for `faultGameAbsolutePrestate` in `getting-started.json`. But again, I'm not sure if this is on purpose or not.

**Comment by AndreasKendziorra** [comment]
Please note that if I add a value for `faultGameAbsolutePrestate`, it will then complain about `faultGameMaxDepth`. But after adding a value for this one to getting-started.json, it works.
I copied the values from [devnetL1.json](https://github.com/ethereum-optimism/optimism/blob/4d7798f750779ad248d0d61637b4892f53b7a599/packages/contracts-bedrock/deploy-config/devnetL1.json#L47-L48), but I'm not sure if these are the right ones in this case.

**Comment by cspannos** [comment]
I'm getting the same error:
```== Logs ==
  Connected to network with chainid 5
  Storing temp deployment data in /home//optimism/packages/contracts-bedrock/deployments/getting-started/.deploy
  DeployConfig: reading file /home/optimism/packages/contracts-bedrock/deploy-config/getting-started.json
Error:
Script failed.```



> Please note that if I add a value for `faultGameAbsolutePrestate`, it will then complain about `faultGameMaxDepth`. But after adding a value for this one to getting-started.json, it works. I copied the values from [devnetL1.json](https://github.com/ethereum-optimism/optimism/blob/4d7798f750779ad248d0d61637b4892f53b7a599/packages/contracts-bedrock/deploy-config/devnetL1.json#L47-L48), but I'm not sure if these are the right ones in this case.

**Comment by tynes** [comment]
We will have a fix for this shortly

**Comment by Aymen-Tirchi** [comment]
im facing the same issue which is "No matching value or array found for key $.l2GenesisRegolithTimeOffset" any suggested solutions
