### ISSUE TITLE
Relay event only emitted if call doesn't revert

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#615]
**Describe the bug**
@TransmissionsDev reported this bug recently in our Discord and could provide some more context. I'll quote what he said here and let him expand on what was said:

### What happens if the contract a cross domain message calls reverts?
1. Doesn’t seem like I’m like able to pick that up with the watcher
    * Would like to be able to get the revert messages of relayed relayed messages, is that not possible?
    * Relay event only emitted if call doesn’t revert
    * Watcher looks for relay events

2. Does the RelayedMessage event have to be emitted only on success? 
    * Don’t see why that can’t also be on failure (it literally gets stored as a relayed message even if it reverts)
    * Maybe a separate event like SuccessfulMessage or something would be useful?
    * Being able to detect a relayed message that didn’t succeed seems pretty important

**To Reproduce**
@TransmissionsDev could you possibly provide a repro case?

**Expected behavior**
Should be able to retrieve revert reasons from cross-domain message call reversions.

**Comment by TransmissionsDev** [comment]
This was already solved @platocrat https://github.com/ethereum-optimism/optimism/issues/587

**Comment by TransmissionsDev** [comment]
However this change should be followed up with a PR to allow the watcher to handle the new event. I have created an issue for discussion: https://github.com/ethereum-optimism/optimism/issues/602
