### ISSUE TITLE
op-proposer failing

### ISSUE THREAD

**Issue by cspannos** [ethereum-optimism/optimism#6174]
**Describe the bug**
`op-proposer` does not start.

**To Reproduce**

1. Run through the getting started docs up the point of [starting op-proposer](https://stack.optimism.io/docs/build/getting-started/#op-proposer). Then run the cmd:

```
./bin/op-proposer \
    --poll-interval 12s \
    --rpc.port 8560 \
    --rollup-rpc http://localhost:8547 \
    --l2oo-address $L2OO_ADDR \
    --private-key $PROPOSER_KEY \
    --l1-eth-rpc $L1_RPC
```
2. See error in this screenshot:
![Screenshot 2023-06-27 at 21 24 29](https://github.com/ethereum-optimism/optimism/assets/5671161/4e936b00-1360-4650-839a-4b8a8c5478f4)

**Expected behavior**
Upon successfully running the cmd in step 1, I would expect some logs indicating `op-proposer` is successfully proposing new state roots.

**Additional context**
For context `op-geth`, `op-node` and `op-batcher` are all running and I am trying to start `op-proposer` last.

My branch is: `origin/develop`

**Comment by tynes** [comment]
Is your `L1_RPC` environment variable set?

**Comment by cspannos** [comment]
> Is your `L1_RPC` environment variable set?

Yes. I set it in the `op-proposer` dir with `export L1_RPC=http://myrpc/?apiKey=1234` so I'm not sure what is wrong.

**Comment by cspannos** [comment]
> Is your `L1_RPC` environment variable set?

I now think the error above is misleading. I've made a pull request to expose what I think is the underlying error:
https://github.com/ethereum-optimism/optimism/pull/6179

Regarding the underlying error, how do I:
1. retrieve the address for L2 Output Submitter
2. set the address variable

Thank you!

**Comment by cspannos** [comment]
I'm closing this ticket due to: https://github.com/ethereum-optimism/optimism/pull/6179. I have opened a new issue with the updated error: https://github.com/ethereum-optimism/optimism/issues/6194
