### ISSUE TITLE
Op-Proposer L2 Output Submitter error

### ISSUE THREAD

**Issue by cspannos** [ethereum-optimism/optimism#6194]
**Describe the bug**
I start `op-proposer` with the script:
./bin/op-proposer \
    --poll-interval=12s \
    --rpc.port=8560 \
    --rollup-rpc=http://localhost:8547 \
    --l2oo-address=$L2OO_ADDR \
    --private-key=$PROPOSER_KEY \
    --l1-eth-rpc=$L1_RPC

And get this error:
```
INFO [06-28|15:22:40.444] Initializing L2 Output Submitter 
ERROR[06-28|15:22:40.444] Unable to create the L2 Output Submitter error="invalid address: " 
CRIT [06-28|15:22:40.444] Application failed                       message="invalid address: " 
```

1. How do I retrieve the address for L2 Output Submitter?
2. How do I set the address?

**To Reproduce**
Run through the getting started docs up the point of [starting op-proposer](https://stack.optimism.io/docs/build/getting-started/#op-proposer). Then run the cmd to start `op-proposer`.

**Expected behavior**
Upon successfully running the cmd in step 1, I would expect some logs indicating op-proposer is successfully proposing new state roots.

**Additional context**
My branch is `origin/develop`.
I start and run op-geth, op-node and op-batcher first, and I am trying to start op-proposer last.

**Comment by vjaiman** [comment]
@cspannos It should be the address of the `L2OutputOracleProxy`, available at `~/optimism/packages/contracts-bedrock/deployments/getting-started/L2OutputOracleProxy.json`, particularly LOC 131.

**Comment by cspannos** [comment]
> @cspannos It should be the address of the `L2OutputOracleProxy`, available at `~/optimism/packages/contracts-bedrock/deployments/getting-started/L2OutputOracleProxy.json`, particularly LOC 131.

Thanks for your suggestion. It seems `op-proposer` didn't like the L1 rpc provider I gave for other components in the stack. Not sure why. I pointed it at an alchemy endpoint and it is now working as expected. Seeing as my main issue is resolved, I am closing this issue.

**Comment by DramaCrypto** [comment]
I can not see the json file under this path
~/optimism/packages/contracts-bedrock/deployments/getting-started/L2OutputOracleProxy.json
How can I get it?

**Comment by kgmiles** [comment]
[This](https://github.com/search?q=repo%3Aethereum-optimism%2Foptimism+4265aa5c1830facc0f3382552954f2946a73caf5&type=commits) commit deleted L2OutputOracleProxy.json:
```
commit 4265aa5c1830facc0f3382552954f2946a73caf5
Author: Mark Tyneway <mark.tyneway@gmail.com>
Date:   Thu Oct 5 10:52:19 2023 -0700

    contracts-bedrock: delete fake internal-devnet artifacts

    Remove the `internal-devnet` artifacts from the monorepo
    because they are not correct. These come from an earlier
    iteration of the internal devnet so delete them to prevent
    confusion in the future.
```
 I updated my op-proposer start command to get the address with `jq -r '.transactions[] | select(.contractName=="L2OutputOracle") | .contractAddress' /root/optimism/packages/contracts-bedrock/broadcast/Deploy.s.sol/11155420/run-latest.json`.  

I also encountered a problem when I tried to start op-node:
```
failed to validate the L1 config: incorrect L1 RPC chain id 11155420, expected 11155111root@8a7632a84660:~/optimism/packages/contracts-bedrock# #failed to setup: unable to create the rollup node: failed to init L1: failed to validate the L1 config: incorrect L1 RPC chain id 11155420, expected 11155111
```
[Chainlist.org](https://chainlist.org/chain/11155111) says chain 11155111 is Sepolia.  For 11155420, [it says](https://chainlist.org/chain/11155420) "OP Sepolia Testnet".   I ended up changing `"l1ChainID": 11155111` to `l1ChainID": 11155420` in `packages/contracts-bedrock/scripts/getting-started/config.sh` and repeating all subsequent steps.
