### ISSUE TITLE
Pinning Forge Binary will cause CI failure

### ISSUE THREAD

**Issue by sambacha** [ethereum-optimism/optimism#6195]
POV: You are a mn engineer working late when suddenly all your work in CI pipelines stops.

You spend a few hours looking at what you did wrong possibly.

Then you make a horrid discovery.
![image](https://github.com/ethereum-optimism/optimism/assets/32783916/5d40c9cc-7841-4b24-89b7-08c1987de595)
> If only 

Foundry deleted the binaries of nightly and only keeps the latest 5 versions. Relying on their github actions release archive will invariably cause CI failures after the pined binary is eventually deleted.

> Additionally, the version identifier is ~~fucked~~ not friendly, they put short git hash infront of the timestamp, making it harder to sort 😑

We maintain our own release pipeline for building binaries for CI usage and for developer environments (we use a different macOS lld that results in better performance in compiling, etc). As an example their macOS pipeline had not actually been creating release binaries and were 2 version releases behind the linux binaries.

The alternative is adopting nix. If you have yet to hear the good word of our lord and saviour I promise you wont ever look back.

 

Regards,

Sam Bacha

**Comment by sambacha** [comment]
> ![7qzsxr](https://user-images.githubusercontent.com/23033765/249829472-655e0ab3-274f-499f-8558-5a52848681db.jpg)
> 
> > Foundry deleted the binaries of nightly and only keeps the latest 5 versions. Relying on their github actions release archive will invariably cause CI failures after the pined binary is eventually deleted.
> 
> Is this a recent change that Foundry has adopted? We've been pinning our foundry version for quite some time. Before we adopted that approach things would often break _due to_ an update.
> 
> Also, can you clarify precisely what you're suggesting we do?

Keep the pinned forge binary you are using in a forked repo or a repo in which you upload the binary to a release so you can point to that binary for the release to download.

Foundry deletes nightly releases since it at least v0.1.0. Its in the workflow scripts as part of the release process to prune the oldest release when adding a new one.

**Comment by sambacha** [comment]
> I see. The reason this is not an issue for us in CI is that we build from source:
> 
> https://github.com/ethereum-optimism/optimism/blob/6856455cbf524d7e6c5e5ac07d5483068b477dec/ops/docker/ci-builder/Dockerfile#L20-L21

why do you hate yourself so ser?

**Comment by clabby** [comment]
> > I see. The reason this is not an issue for us in CI is that we build from source:
> > https://github.com/ethereum-optimism/optimism/blob/6856455cbf524d7e6c5e5ac07d5483068b477dec/ops/docker/ci-builder/Dockerfile#L20-L21
> 
> why do you hate yourself so ser?

![image](https://github.com/ethereum-optimism/optimism/assets/8406232/57110b78-282e-4eed-b543-a00e6c04012e)

**Comment by maurelian** [comment]
`foundryup -C SHA` is lawful good until you have to update `SHA` in [more than one place](https://github.com/ethereum-optimism/optimism/pull/6162/files), at which point it instantly flips to chaotic evil.

**Comment by sambacha** [comment]
Inshallah more robust CI is provided for you, I would very much be interested in the time benchmarks of the current system. 

![image](https://github.com/ethereum-optimism/optimism/assets/32783916/6918db43-45b1-4929-b856-7717a87ebd0a)

**Comment by tynes** [comment]
Closing this because things are working fine
