### ISSUE TITLE
Is cannon fraud proof implementation ready now?

### ISSUE THREAD

**Issue by David-Web3** [ethereum-optimism/optimism#6228]
It seems that the cannon implementation has been merged into this repo under the `op-program` and `cannon` folder.  May I know how to test it and will it be in production for next release?

**Comment by ajsutton** [comment]
Cannon is still under development, it has just moved from a separate repository into the monorepo. It is one of four key components that make up the full fault proof system:
 - `op-program` which executes the derivation pipeline to determine if an output root is correct or not
 - `cannon` which is the VM that allows `op-program` to execute on chain
 - The dispute game contracts which allow bisecting the execution trace from cannon so just a single instruction actually needs to be executed on chain (makes the cost of disputes affordable)
 - `op-challenger` which interacts with the dispute game contracts to play the game, defending or challenging published output roots.

There isn't currently a timeline for deploying these to production but keep an eye on the Optimism blog for more info on how the fault proof system works and for updates as these components go through various stages of testing etc.
