### ISSUE TITLE
Links to bridge contracts in the documentation give you a 404

### ISSUE THREAD

**Issue by oveddan** [ethereum-optimism/optimism#6230]
**Describe the bug**

If you open the [bridge contracts](https://community.optimism.io/docs/protocol/protocol-2.0/#bridge-contracts) documentation, and click on any of the links to go to the contract source code, you get a 404.  

For example, this link (copied from the documentation: [L1CrossDomainMessenger(opens new window)](https://github.com/ethereum-optimism/optimism/blob/master/packages/contracts/contracts/L1/messaging/L1CrossDomainMessenger.sol) gives a 404.  Same goes for the rest of the contract links.

**Comment by brianjohnson5972** [comment]
All the links in https://github.com/ethereum-optimism/community-hub/edit/main/src/docs/protocol/protocol-2.0.md are broken. I tried replacing "master" branch with "v1.0.9" which worked for all except .../L2/predeploys/iOVM_L1MessageSender.sol. Obviously this needs to be updated to match the current code, but at least pointing it back to the moment in time that it was correct would be better than getting the 404.
