### ISSUE TITLE
L2 contracts be deployed to L1 chain?

### ISSUE THREAD

**Issue by cifer76** [ethereum-optimism/optimism#6231]
**Describe the bug**

Just followed [this tutorial](https://stack.optimism.io/docs/build/getting-started/#deploy-the-l1-contracts) to have my own op stack chain set up.
During the step of deploying L1 contracts, I found the contracts under the `packages/contracts-bedrock/contracts/L2/` folder were also deployed to L1.

**Expected behavior**
I think only the contracts under `packages/contracts-bedrock/contracts/L1/` should be deployed to L1, contracts under the `.../L2/` folder should be the pre-compiled contracts and pre-deployed into the L2 chain?

**Comment by tynes** [comment]
Are you sure about this? Please share etherscan links. The deploy script does not deploy the L2 contracts to L1
