### ISSUE TITLE
GetProof and GetStorageAt does not follow EIP-1898 when querying using blockHash

### ISSUE THREAD

**Issue by javiersuweijie** [ethereum-optimism/optimism#6232]
**Describe the bug**

[GetProof](https://github.com/ethereum-optimism/optimism/blob/d80c145e0acf23a49c6a6588524f57e32e33b91c/op-node/sources/eth_client.go#L397) and [GetStorageAt](https://github.com/ethereum-optimism/optimism/blob/d80c145e0acf23a49c6a6588524f57e32e33b91c/op-node/sources/eth_client.go#L405) (maybe others as well) does not follow [EIP-1898](https://eips.ethereum.org/EIPS/eip-1898) when querying using blockHash

Currently, the two methods calls the L1 RPC with 
```
{
    "jsonrpc": "2.0",
    "method": "eth_getProof",
    "params": [
        "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
        [
            "0x65a7ed542fb37fe237fdfbdd70b31598523fe5b32879e307bae27a0bd9581c08"
        ],
        "0xc5d324f4bb9694a438b6b5b5ed374faf5f09c9e7a44ec03aa924163576a34913"}
    ],
    "id": 1
}

### Response returns this error when the RPC follows EIP-1898 strictly (anvil for example)
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32602,
        "message": "Invalid string length"
    }
}
```
When it should be
```
{
    "jsonrpc": "2.0",
    "method": "eth_getProof",
    "params": [
        "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
        [
            "0x65a7ed542fb37fe237fdfbdd70b31598523fe5b32879e307bae27a0bd9581c08"
        ],
        {"blockHash": "0xc5d324f4bb9694a438b6b5b5ed374faf5f09c9e7a44ec03aa924163576a34913"}
    ],
    "id": 1
}
```

**Expected behavior**

**Screenshots**

**System Specs:**
 - OS:
 - Package Version (or commit hash):

**Additional context**

**Comment by tynes** [comment]
Thank you for opening this PR. If there was some way you could repro an error that would be very helpful because the RPC requests seem to be working fine as is and are running in production

**Comment by smartcontracts** [comment]
Closing as stale, no repro was provided
