### ISSUE TITLE
Hi, may i ask what's the timeline of op-geth snap sync feature ready?

### ISSUE THREAD

**Issue by ghost** [ethereum-optimism/optimism#6233]
**Is your feature request related to a problem? Please describe.**
bootstrap a optimism fullnode takes too long without snap sync enabled

**Describe the solution you'd like**
enable snap sync

**Describe alternatives you've considered**
do we have a timeline plan for snap sync? thanks

**Additional context**

**Comment by Realrobwoodx** [comment]
I need help my OP is locked somewhere I have no clue how this even happened ![image](https://github.com/ethereum-optimism/optimism/assets/135924793/938ee146-3b7c-4419-b20f-68d185d1f51b)

**Comment by protolambda** [comment]
@nolanxyg snap-sync is already supported, but it's experimental, something you can unlock with flags in the CLI. There are not that many geth peers to sync from yet either. You start the geth node from genesis, or from the bedrock data-dir in case of op-goerli/op-mainnet. And then `--syncmode=snap` in op-geth and `--l2.skip-sync-start-check` and `--l2.engine-sync` in op-node.

**Comment by protolambda** [comment]
@Realrobwoodx this is not the right place to post user-wallet issues, this github issue is about node syncing, something very different. Please request help in the Optimism discord to resolve your transfer issue.

**Comment by Realrobwoodx** [comment]
Hello, I’m not sure what I am supposed to do my OP MAINNET has problems on
my browser are you talking about that 1 eth testnet?
