### ISSUE TITLE
L1 to L2 bridge proxy not working, while setting up Op Stack Node

### ISSUE THREAD

**Issue by devudilip** [ethereum-optimism/optimism#6236]
Successfully set up the RollUp, using the below Doc. 
Not able to get the Eth on L2 after transferring to L1 bridge proxy contract address. 

https://goerli.etherscan.io/address/0x9566d077ddf649e8f399e119c34609e16385e9e9

**Comment by rjamalijam** [comment]
Good

**Comment by tynes** [comment]
Did you use `forge` or `hardhat` to deploy?

**Comment by devudilip** [comment]
I have followed the [op stack Doc](https://stack.optimism.io/docs/build/getting-started/#configure-your-network). 
which uses **forge**

**Comment by smartcontracts** [comment]
Doc referenced in this issue is now very out of date, closing.
