### ISSUE TITLE
`network_id` mismatch when running integration tests against Kovan

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#624]
**Describe the bug**
Running integration tests against our Kovan testnet using Truffle results in the following error:
```
Error: The network id specified in the truffle config (69) does not match
the one returned by the network (1337).  Ensure that both the network 
and the provider are properly configured.
```

**To Reproduce**
1. `git clone https://github.com/ethereum-optimism/optimism.git`
1. `git checkout ci/examples` 
1. `yarn && yarn build`
1. `cd optimism/examples/Truffle-ERC20-Example`
1. `yarn`
1. Update the `truffle-config-ovm.js` file's `providerOrUrl` field to `https://kovan.optimism.io`
1. `yarn truffle test ./test/erc20.spec.js --network optimistic_ethereum --config truffle-config-ovm.js`
1. See error shown above.

**Expected behavior**
Tests should run successfully and pass (this PR excludes the `eth_estimateGas` issue with l2geth).

**Additional context**
If you change the `network_id` to `1337`and re-run the test command, then you will see a different, but still unhelpful error:
```
Error: while migrating ERC20: invalid transaction: invalid sender
```

**Comment by gakonst** [comment]
The correct network config should be `1337` (using `https://kovan.optimism.io` instead of localhost as the URL). The "invalid sender" error I believe is an instance of https://github.com/trufflesuite/truffle/issues/3961

**Comment by platocrat** [comment]
> The correct network config should be `1337` (using `https://kovan.optimism.io` instead of localhost as the URL).

What's the difference between the `network_id` and the `ChainID`?
I thought the `network_id` field was equal to the `ChainID`. So, I assumed this value was `69.

**Comment by bstchow** [comment]
@platocrat From some brief research, it looks like eth_chainId should be considered the canonical chain ID. network_id and chainId will usually refer to the same value, but they can be differentiated in order to identify specific nodes.

Good breakdown of distinction:
https://besu.hyperledger.org/en/stable/Concepts/NetworkID-And-ChainID/

Helpful context:
https://eips.ethereum.org/EIPS/eip-695
https://github.com/ethereum/eth2.0-specs/issues/2163
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md

**Comment by K-Ho** [comment]
> The correct network config should be `1337` (using `https://kovan.optimism.io` instead of localhost as the URL). The "invalid sender" error I believe is an instance of [trufflesuite/truffle#3961](https://github.com/trufflesuite/truffle/issues/3961), so not on us.
> 
> ```
> $ curl -k -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"net_version","id":1}' https://kovan.optimism.io
> {"jsonrpc":"2.0","id":1,"result":"1337"}
> 
> $ curl -k -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"eth_chainId","id":1}' https://kovan.optimism.io
> {"jsonrpc":"2.0","id":1,"result":"0x45"}
> ```

@gakonst Why would we want our network id to not be the same as our chain id?

**Comment by gakonst** [comment]
I'm not saying we want it, I am saying it _is_ different right now, which makes the example code hit the Truffle bug.

**Comment by gakonst** [comment]
In order to fix this and not wait for Truffle, I recommend we run geth with `--networkid 69`, so that the chainId and networkId match.
