### ISSUE TITLE
[RPC] unexpected statediff format on debug_traceBlockByHash

### ISSUE THREAD

**Issue by mateipopp** [ethereum-optimism/optimism#6244]
**Describe the bug**
The debug_traceBlockByHash method call is returning an unexpected statediff format. Each statediff should have the pre and post fields..

**To Reproduce**
The issue can be reproduced by querying the RPC port using the following command:
```
curl localhost:9991   -X POST   -H "Content-Type: application/json"   --data '{"method":"debug_traceBlockByHash","params":["0x0992b9590dfb570a25724fe339158c809deefce27a7f26fd6b8d860a56166794", {"tracer": "prestateTracer", "tracerConfig": {"onlyTopCall": false, "diffMode": true}}],"id":1,"jsonrpc":"2.0"}'
```
result(removed the values for less spam):
{"jsonrpc":"2.0","id":1,"result":[{"result":{"0x420000000000000000000000000000000000000f":{"balance":"0x0","code":"","nonce":0,"storage":{"0x0000000000000000000000000000000000000000000000000000000000000000":"0x0000000000000000000000007107142636c85c549690b1aca12bdb8052d26ae6","0x0000000000000000000000000000000000000000000000000000000000000002":"0x0000000000000000000000000000000000000000000000000000002b5ad7d8e5"}},"0x7107142636c85c549690b1aca12bdb8052d26ae6":{"balance":"0x0","code":"0x","nonce":13645,"storage":{}}}}]}

**Expected behavior**
The response body should contain keys labeled "post" and "pre."

**System Specs:**
 - OS: ubuntu22.04
 - Package Version (or commit hash):   op-geth version 0.1.0-unstable-b5fecf58

**Comment by protolambda** [comment]
`debug_traceBlockByHash` matches the L1 geth behavior I believe, which is documented here: https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugtraceblockbyhash
No modifications have been made to this format. Is the `pre`/`post` fields behavior documented somewhere? Is it pre-bedrock behavior (old version of geth)?

**Comment by mateipopp** [comment]
This is a pre-bedrock behavior. For a block post bedrock the geth node response is as expected:
```{'result': {'post': {'0x4200000000000000000000000000000000000015': {'storage': {'0x0000000000000000000000000000000000000000000000000000000000000003': '0x0000000000000000000000000000000000000000000000000000000000000001'}}, '0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001': {'nonce': 1496710}}, 'pre': {'0x4200000000000000000000000000000000000015': {'balance': '0x0', 'code': ''}, '0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001': {'balance': '0x0', 'nonce': 1496709}}}} ```

**Comment by tynes** [comment]
Closing this issue, feel free to reopen if necessary
