### ISSUE TITLE
op-geth starting node

### ISSUE THREAD

**Issue by Aymen-Tirchi** [ethereum-optimism/optimism#6245]
## description 
I'm following [Getting Started](https://stack.optimism.io/docs/build/getting-started/#) doc of op stack
in [op-geth](https://stack.optimism.io/docs/build/getting-started/#run-the-node-software) section after running this command
```bash
./build/deb/ethereum/completions/bash/geth \
	--datadir ./datadir \
	--http \
	--http.corsdomain="*" \
	--http.vhosts="*" \
	--http.addr=0.0.0.0 \
	--http.api=web3,debug,eth,txpool,net,engine \
	--ws \
	--ws.addr=0.0.0.0 \
	--ws.port=8546 \
	--ws.origins="*" \
	--ws.api=debug,eth,txpool,net,engine \
	--syncmode=full \
	--gcmode=archive \
	--nodiscover \
	--maxpeers=0 \
	--networkid=42069 \
	--authrpc.vhosts="*" \
	--authrpc.addr=0.0.0.0 \
	--authrpc.port=8551 \
	--authrpc.jwtsecret=./jwt.txt \
	--rollup.disabletxpoolgossip=true \
	--password=./datadir/password \
	--allow-insecure-unlock \
	--mine \
	--miner.etherbase=$SEQ_ADDR \
	--unlock=$SEQ_ADDR
```
nothing happens no errors it just doesn't start the op-geth
I also changed the path of the geth because it's not on the same path as mine 
and set all the environment variables as the op stack doc
but still with the same issue

I also couldn't find the `genesis.json` and `rollup.json`
## Expected behavior
it should start the op-geth node

## System Specs:
 - OS: Ubuntu-20.04

**Comment by protolambda** [comment]
- The `genesis.json` and `rollup.json` are created with genesis preparation tools (see above section in same docs page)
- When creating a network from scratch using (op-)geth, you first need to first run the `init` sub-command of geth to create your datadir using the `genesis.json`
- The key-import thing into geth is pre-bedrock, something not actually necessary. (pre-bedrock is used mock clique signatures to create geth-compatible blocks). Skip that.
- You need to run both `op-geth` and `op-node` to run a network
- The op-node needs sequencer flags to build blocks

If you instead intend to join an existing network with pre-bedrock history, you need to start from a prepared datadir, not config files + init.

**Comment by qbzzt** [comment]
The step which you need is https://stack.optimism.io/docs/build/getting-started/#generate-the-l2-config-files.

**Comment by protolambda** [comment]
The docs are up-to-date now, so I'm closing this issue. Let us know if it does not work.

**Comment by Aymen-Tirchi** [comment]
I have replayed the steps from [Generate the L2 config files](https://stack.optimism.io/docs/build/getting-started/#generate-the-l2-config-files) I have noticed that the `geth` file in the `build/bin` directory has not been created that's why the `op-geth` doesn't run in my case and now the issue is fixed after reinitializing the `op-geth`, thanks for your help.
