### ISSUE TITLE
Are there any dispute game smart contracts implemented for cannon?

### ISSUE THREAD

**Issue by David-Web3** [ethereum-optimism/optimism#6265]
Hi, 

I am investigating how the dispute game works for cannon, and I have seen there are several related` .sol` files such as `packages/contracts-bedrock/contracts/dispute/interfaces/IFaultDisputeGame.sol`, but I fail to find out the `.sol ` targeting at gaming with cannon. So is there such one existed at present? 
If not, I would like to try out writing an example my self, is there any sample code I can refer to?

Thanks!

**Comment by tynes** [comment]
The contracts are a WIP, you can find them here - https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts-bedrock/contracts/cannon

**Comment by David-Web3** [comment]
> The contracts are a WIP, you can find them here - https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts-bedrock/contracts/cannon

Thanks but I got 404 from the link you provide, would like to help confirm? I guess maybe the branch is not develop?

**Comment by smartcontracts** [comment]
For anyone reading this, the contracts can be found in the `dispute` folder in `contracts-bedrock`.
