### ISSUE TITLE
Can not send max amount from my metamask at L2

### ISSUE THREAD

**Issue by eskrano** [ethereum-optimism/optimism#6273]
**Describe the bug**
Can not send max amount of ETH from my metamask wallet at L2.

**To Reproduce**
1. Go to metamask
2. Click on send
3. enter wallet to send
4. click max amount
5. see error

**Expected behavior**
Tx sent with no errors

**Screenshots**
<img width="349" alt="image" src="https://github.com/ethereum-optimism/optimism/assets/10223123/5f767bb2-22e1-4a0f-8157-cbd083905e96">

**System Specs:**
 - OS: MacOS
 - Package Version (or commit hash):

**Additional context**

**Comment by tynes** [comment]
This is a metamax issue regarding the way that they compute the "max amount", they must not be taking into account the L1 fee

**Comment by tynes** [comment]
We are working on a solution to make accurate fee estimation much easier here - https://github.com/ethereum-optimism/optimism/tree/develop/packages/fee-estimation

**Comment by smartcontracts** [comment]
Closing as this is a metamask issue
