### ISSUE TITLE
docs[specs/protocol]: Add detailed explanation of Sequenced Tx execution

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimism#629]
It is becoming a priority to have specs on the flow of a sequenced transaction, in particular: 

- the encoding
- processing in the Sequencer Entrypoint
- processing in the ECDSAContractAccount

**Comment by ben-chain** [comment]
We should wait for the `0.3.0` release on this, as the RLP epic changes how this is handled.
