### ISSUE TITLE
[feature] add BASE mainnet support in the SDK

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/optimism#6297]
**Is your feature request related to a problem? Please describe.**

Not a problem, but an exciting new development: [Base Mainnet is Open for Builders](https://base.mirror.xyz/hwNwqXHVoLlO8s4DZppog4DfGvM34tigaDjOWuEJQfY)! Can we add BASE mainnet support in the SDK?

**Describe the solution you'd like**
The community would like to have BASE mainnet support added to the SDK. I believe these are the relevant files that need to be updated:

- https://github.com/ethereum-optimism/optimism/blob/develop/packages/sdk/src/utils/chain-constants.ts
- https://github.com/ethereum-optimism/optimism/blob/develop/packages/sdk/src/interfaces/types.ts

But I don't know how the SDK works, so I'm sure I'm missing some things.

**Describe alternatives you've considered**

n/a

**Additional context**

I received a request from a discord user who is, "trying to integrate Base Mainnet inside [their] bridge."

**Comment by GabrielBuragev** [comment]
Hello. Yes, we are trying to integrate Base Mainnet (on Beamer Bridge) till end of July. One of our components is using `@eth-optimism/sdk`.
I saw that there is support for Base Goerli however i couldn't find support for Mainnet (also no issues/PRs). 

I previously took a look if i can open a PR for this, but i think i will not be able to as i don't have the Base deployment artifacts.

Here is an example PR of how this should be done: https://github.com/ethereum-optimism/optimism/pull/6261

Btw, adding support for these networks in your SDK provides a very pleasant DX! Really happy to see how the collaboration between the networks in the Superchain is evolving.

**Comment by istankovic** [comment]
Looking forward to this!

**Comment by sbvegan** [comment]
@GabrielBuragev to expedite this are you able to put up the pr and we review? It would need the following changes:

1. Add [L2ChainId](https://github.com/ethereum-optimism/optimism/blob/develop/packages/sdk/src/interfaces/types.ts#L34_
2. Add [confirmation blocks](https://github.com/ethereum-optimism/optimism/blob/develop/packages/sdk/src/utils/chain-constants.ts#L65)
3. Add [L1 addresses](https://github.com/ethereum-optimism/optimism/blob/develop/packages/sdk/src/utils/chain-constants.ts#L205)
4. Ping @roninjin10 for review

**Comment by GabrielBuragev** [comment]
Thank you for resolving this folks!

Is this included in the latest `3.1.0` sdk version? If not, when can we expect it to be released?

**Comment by GabrielBuragev** [comment]
I just noticed that it was already released. Well done!
