### ISSUE TITLE
docs[specs/protocol0]: Specs per opcode

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimism#630]
We should have specs describing the intended functionality and failure modes for each `ovmINSTRUCTION` in the Execution Manager.

This is a major undertaking.

**Comment by ben-chain** [comment]
How do you think this should relate to the docstrings in the EM itself?

**Comment by maurelian** [comment]
> How do you think this should relate to the docstrings in the EM itself?

Good callout, and yes there is danger of duplication here, unfortunately I don't have a great response yet. 
An example of the things that I think need to be spec'd are things like:
> -`ovmCREATE` should set the nonce of a new contract to `1`.
> - `ovmSTATICCALL` should set `messageContext.isStatic` to `true`.

**Comment by maurelian** [comment]
This is now tracked elsewhere as part of another project.

**Comment by liamzebedee** [comment]
@maurelian got a link? 😄
