### ISSUE TITLE
incorrect L2 RPC chain id 19763, expected 42069

### ISSUE THREAD

**Issue by Aymen-Tirchi** [ethereum-optimism/optimism#6312]
## Description
I'm using this command to start the op-node from [op stack doc](https://stack.optimism.io/docs/build/getting-started/#op-node)
```
./bin/op-node \
	--l2=http://localhost:8551 \
	--l2.jwt-secret=./jwt.txt \
	--sequencer.enabled \
	--sequencer.l1-confs=3 \
	--verifier.l1-confs=3 \
	--rollup.config=./rollup.json \
	--rpc.addr=0.0.0.0 \
	--rpc.port=8547 \
	--p2p.disable \
	--rpc.enable-admin \
	--p2p.sequencer.key=$SEQ_KEY \
	--l1=$L1_RPC \
	--l1.rpckind=$RPC_KIND
```
after running it I get this error 
```
ERROR[07-17|11:17:18.192] Error initializing the rollup node       err="incorrect L2 RPC chain id 19763, expected 42069"
ERROR[07-17|11:17:18.193] Unable to create the rollup node         error="incorrect L2 RPC chain id 19763, expected 42069"
CRIT [07-17|11:17:18.193] Application failed                       message="incorrect L2 RPC chain id 19763, expected 42069"
```
knowing that the `op-geth` is running correctly and I've tried to change the `l2_chain_id` in `rollup.json` to 19763 but that didn't fix the issue

**System Specs:**
 - OS: Ubuntu-20.04

**Comment by nitantchhajed** [comment]
can you provide your chain configuration `getting-started.json` and the command you used to start `op-geth` ?

**Comment by Aymen-Tirchi** [comment]
I just restarted the doc from the beginning and the issue was fixed, I think they have updated the doc
