### ISSUE TITLE
"Edit this page" links broken on stack.optimism.io/docs

### ISSUE THREAD

**Issue by karlb** [ethereum-optimism/optimism#6323]
For example the link on https://stack.optimism.io/docs/build/conf/ points to
https://github.com/ethereum-optimism/opstack-docs/edit/main/src/docs/build/conf.md while it probably should point to 
https://github.com/ethereum-optimism/optimism/edit/develop/docs/op-stack/src/docs/build/conf.md .

It looks like it should be fixed in https://github.com/ethereum-optimism/optimism/blob/develop/docs/op-stack/src/.vuepress/theme/components/PageMeta.js#L60.

**Comment by smartcontracts** [comment]
stack.optimism.io is deprecated
