### ISSUE TITLE
Discord invite is broken

### ISSUE THREAD

**Issue by 3esmit** [ethereum-optimism/optimism#6327]
**Describe the bug**
There is something wrong with the discord link in the optimism webpage. When I click to join it says that something went wrong.

**Comment by imtipi** [comment]
https://discord.com/invite/optimism
if you can't,it means you got banned

**Comment by 3esmit** [comment]
Strange, because there is no reason for me being banned. Can you check if there are any bans in my name, and give me the reason? Perhaps also unban me? My username is `3esmit` `3esmit.stateofus.eth`

**Comment by imtipi** [comment]
> 

can you provide your discord user id?i can't search your username if you are not in the server.

**Comment by 3esmit** [comment]
With the recent change on Discord user ids, I am not sure, this is what appears.
Seems like my userid is `3esmit.stateofus.eth`, but my legacy is `3esmit.stateofus.eth#7698`
![image](https://github.com/ethereum-optimism/optimism/assets/224810/2e08b6d2-62d4-488c-85ac-d99b05bb688d)

**Comment by imtipi** [comment]
> With the recent change on Discord user ids, I am not sure, this is what appears. Seems like my userid is `3esmit.stateofus.eth`, but my legacy is `3esmit.stateofus.eth#7698` ![image](https://user-images.githubusercontent.com/224810/255910431-2e08b6d2-62d4-488c-85ac-d99b05bb688d.png)

done,try again

**Comment by 3esmit** [comment]
Thank you, now it worked!
