### ISSUE TITLE
Reorg Sequencer based on observed batches submitted on L1

### ISSUE THREAD

**Issue by snario** [ethereum-optimism/optimism#633]
Work done in the past (i.e., see https://github.com/ethereum-optimism/go-ethereum/pull/300) added support to `geth` to re-org the chain based on transactions submitted to the L1 canonical transaction chain. We'd like to revive this work.

**Comment by smartcontracts** [comment]
Going to be handled as part of Bedrock. Closing since there's no real value in having this issue open here when the work is already scoped out and included as part of the requirements for Bedrock. I'd transfer this over to optimistic-specs but I believe it's already reflected there.
