### ISSUE TITLE
questions about deriving L2 blocks from L1 during sequencer node migrating

### ISSUE THREAD

**Issue by cifer76** [ethereum-optimism/optimism#6347]
recently we're spinning up our own Op Stack chain and noticed a interesting thing wanna discuss with you.

We launched our sequencer node 2 weeks ago, and the `op-batcher` has already written thousands of blocks onto L1.
Yesterday we stopped the previous sequencer node, and setup another identical sequencer node on a new ec2 instance with higher performance, we expect that the our new sequencer node will derive the chain from L1, but it wasn't...

The "new" sequencer node seems unaware of the existing chain that has been written onto L1, the `op-node` just started stimulating `op-geth` to produce a new sequence of blocks. While in the meantime the `op-node` is still traversing the L1 blocks based on the configured L1 block number in `rollup.json`, so certainly it encountered the batcher transaction, but these batcher transactions are just failed on the [CheckBatch](https://github.com/ethereum-optimism/optimism/blob/develop/op-node/rollup/derive/batches.go#L31) function, either being dropped due to `batch with old timestamp` or `ignoring batch with mismatching parent hash`.

I'm not sure if this is by design or we haven't consider this deeply yet, but IMO, when we migrate and restart the sequencer node , it's better to let `op-node` finish traversing all of the batcher transactions on L1 and be aware of the latest state of the L2 before letting it start to emit `op-geth` to produce new blocks.

How do you think about it?

**Comment by cifer76** [comment]
it just came to me that when I migrating the sequencer node, I didn't copy the datadir of op-geth because there's no much data there I thought it would be fast to derive from L1. maybe this is the reason why my new sequencer node produces new blocks that irrelevant to the existing blocks on L1. 
But IMO, given the concrete genesis.json and rollup.json, even with an empty chain datadir, we should derive a consistent chain according to L1

**Comment by tynes** [comment]
Are you sure that you have configured everything correctly?

**Comment by cifer76** [comment]
> Are you sure that you have configured everything correctly?

yes I am sure about that, the second sequencer node is exactly the same with the first one, except I didn't copy the datadir of op-geth (but I initialized the geth state using the same genesis.json)

**Comment by smartcontracts** [comment]
Going to close this for inactivity, if this is still an issue feel free to reopen.
