### ISSUE TITLE
Triggering extraData doing finalizeBridgeERC20

### ISSUE THREAD

**Issue by egonspace** [ethereum-optimism/optimism#6365]
I want to trigger a contract call while bridging the ERC20 token, but `extraData` of `finalizeBridgeERC20()` function is used only as the purpose of event argument(https://github.com/ethereum-optimism/optimism/blob/427f15ba8c56286d647eaa28197144b192623657/packages/contracts-bedrock/contracts/universal/StandardBridge.sol#L274C24-L274C34
) and not used for calldata. So it's inconvenient for implementing various dapp.

I wonder if it's because of security reasons or gas cost issues, but `CrossDomainMessenger` has that feature, so I don't think it's that problem either, so why didn't you implement this feature? Is there another problem?

**Comment by egonspace** [comment]
Of course, it can be a problem for `StandardBridge` to call other contract directly, but isn't it a problem if the Bridge calls it through a proxy in the middle?

**Comment by tynes** [comment]
Can you describe the usecase in more detail so we can learn and consider new uses of `extraData` in the future? One possible future uses it for `permit2` witness data to allow for single tx deposits of ERC20 tokens

**Comment by egonspace** [comment]
Consider, for example, a dapp like a market across multi-chain. The market contract is on L1, but users on Optimism have to buy products after bridging, i.e., he requires two steps.

For user convenience, a payment contract can be deployed on Optimism, and if the user pays for this contract, eth can be bridged to L1 and at the same time call the purchase function of the market in L1.

The current bridge implementation requires passing eth and passing the purchase function call with `CorssDomainMessenger` separately, but it is difficult for the recipient to combine these two calls into one session.
In particular, when a _contract_ receives a deposit of bridge assets, the contract cannot receive any notification.

**Comment by tynes** [comment]
I definitely understand that this would be much cheaper to batch the 2 operations into a single operation. It is possible to do so with a single operation but I am not sure of the security implications of allowing arbitrary extra data to be passed through the bridge calls. This could be considered for a feature in the future, but we would be 100% sure that there are not security issues with this. Until this time, developers will need to send 2 deposits, one for the bridge and one for the call. Note that these will execute atomically on L2 together

**Comment by egonspace** [comment]
The bigger issue is not the transaction cost, but the fact that there's no discernible correlation between the two deposits in the called function.
I sympathize with the security issue anyway. But I think we can solve it by putting a proxy contract in the middle, but I can't sure it either. I hope you continue to think about this problem. Thank you!
