### ISSUE TITLE
Developer Bridge Docs Link not functioning

### ISSUE THREAD

**Issue by RedHorse823** [ethereum-optimism/optimism#6368]
**Describe the bug**
Contract Links in Optimstim docs not working because one of the branch of the repo no longer exists.

**To Reproduce**
1. Go to '[...](https://community.optimism.io/docs/developers/bridge/messaging/)'
2. Click on 'L1CrossDomainMessenger.sol'
3 See error

**Expected behavior**
Go to the right github page

**Screenshots**
![image](https://github.com/ethereum-optimism/optimism/assets/83915728/83aa65d0-7910-4607-bc96-b3e47181e8da)

**Comment by tynes** [comment]
Thank you for reporting this, this is definitely an issue that we can fix. The docs now live in this repo: https://github.com/ethereum-optimism/stack-docs

Update: its actually here: https://github.com/ethereum-optimism/community-hub/blob/e57d46489973298826155c6c814820a24ff3fbfc/src/docs/protocol/protocol-2.0.md?plain=1#L6

**Comment by tynes** [comment]
Open PR to fix some of the issue, will need to circle back around to fix more of it: https://github.com/ethereum-optimism/community-hub/pull/850
