### ISSUE TITLE
feature request: export `chain-constants.ts` from sdk

### ISSUE THREAD

**Issue by oveddan** [ethereum-optimism/optimism#6423]
If you want to build a front-end that doesn't use the sdk functionality, but just wants to know the values in [chain-constants.ts](packages/sdk/src/utils/chain-constants.ts) there is no way to get these values.

Right now you have to copy and past these configuration values into your repo.

It would be ideal if you can do:

```ts
import { chainConstants } from '@eth-optimism/sdk'

const getl1BridgeMessenger = (l2ChainId: number) => {
  return chainConstants[l2ChainId].L1CrossDomainMessenger;
}
```

but right now `chainConstants` is not exported from the package.

**Comment by tynes** [comment]
Can you clarify exactly what you want exported here? Looking at this:

https://github.com/ethereum-optimism/optimism/blob/406e1257e61ad09edd5067f8ffa77a4931efec41/packages/sdk/src/utils/chain-constants.ts#L130

It is exported already

**Comment by tynes** [comment]
Open to a PR for this functionality because looking at the code, it appears to me that everything is already exported

**Comment by oveddan** [comment]
Looks like you're right, as this seems to work:

`import { CONTRACT_ADDRESSES } from '@eth-optimism/sdk'`

Will close for now. Thank you!
