### ISSUE TITLE
[BestPractice] improve name for L2OO_ADDRESS environment variable

### ISSUE THREAD

**Issue by netzulo** [ethereum-optimism/optimism#6479]
## Obtained behavior

Environment variable  `L2OO_ADDRESS` have a high cognitive load derived of  uppercase letters O  `L2oo_`

## Expected behavior

Environment variable  `L2OO_ADDRESS` have a normal cognitive load at understanding cause renamed to `L2OUTORA_ADDRESS` , or `L2ORACLE_ADDRESS`

### Notes

i think the name is for

* `L2` from layer 2
* first `O` from "Output"
* second `O` from "Oracle"
* address for deployed address at Layer 2

**Comment by tynes** [comment]
I would be open to a PR that renames it to `L2_OUTPUT_ORACLE_ADDRESS` which is explicit and explains exactly what it is but I want to be careful of code churn, just changing things for the sake of changing things

**Comment by netzulo** [comment]
i can make for you an initial PR and you just review for missing changes what i can't know, if you are agree, i can help you a lit :-D

**Comment by ajsutton** [comment]
We'd also need to maintain backwards compatibility.  Just changing it will silently ignore the old `L2OO_ADDRESS` and silently break existing users.

**Comment by tynes** [comment]
fwiw, this env var is only really used internally by our devnet tooling. The only way that it would break things for people is if they are not using our orchestration scripts, which they would have to be doing a lot of manual things in that case, so its unlikely to be breaking things

**Comment by netzulo** [comment]
![image](https://github.com/ethereum-optimism/optimism/assets/11871932/b36c9b47-a960-4c58-9530-db64cc109d81)

for each search i found some interesting point to research and i have some doubts
![image](https://github.com/ethereum-optimism/optimism/assets/11871932/fc387487-1ed5-495b-81d9-db29ba675359)
![image](https://github.com/ethereum-optimism/optimism/assets/11871932/b0e791ce-44a0-4262-870b-a37bfd7195f8)

+ a flag in proposer `l2oo-address` , we can rename too to `l2-output-oracle-address` . I know is a long name but in favor of legibility . are you agree?

+ the environment variable will be from `L2OO_ADDRESS` to `L2_OUTPUT_ORACLE_ADDRESS`



im missing some behaviour to review ? if not, can i make the PR?
