### ISSUE TITLE
Add Safety Check failure Integration test

### ISSUE THREAD

**Issue by K-Ho** [ethereum-optimism/optimism#648]
**Is your feature request related to a problem? Please describe.**
We need to ensure that failed safety checks return an error to users.

**Describe the solution you'd like**
Integration test exists trying to deploy unsafe bytecode to confirm that a failed safety check will return a clear error message to users.
* Need one for unsafe bytecode
* Need one for just unsafe deployedBytecode

**Comment by snario** [comment]
Throwback to this for reference: https://github.com/ethereum-optimism/optimism-integration/issues/107#issuecomment-806404488
