### ISSUE TITLE
proposer unable to get sync status

### ISSUE THREAD

**Issue by Aymen-Tirchi** [ethereum-optimism/optimism#6534]
after running this command to start the `op-proposer`
```
./bin/op-proposer \
    --poll-interval=12s \
    --rpc.port=8560 \
    --rollup-rpc=http://localhost:8547 \
    --l2oo-address=$L2OO_ADDR \
    --private-key=$PROPOSER_KEY \
    --l1-eth-rpc=$L1_RPC`
```
I get this error: 
```
ERROR[07-28|13:25:03.900] proposer unable to get sync status       err="Post \"http://localhost:8547\": context deadline exceeded"
```
knowing the op-geth, op-node, and op-batcher are running correctly 
and this is the command I used to start the op-node: 
```
./bin/op-node \
	--l2=http://localhost:8551 \
	--l2.jwt-secret=./jwt.txt \
	--sequencer.enabled \
	--sequencer.l1-confs=3 \
	--verifier.l1-confs=3 \
	--rollup.config=./rollup.json \
	--rpc.addr=0.0.0.0 \
	--rpc.port=8547 \
	--p2p.disable \
	--rpc.enable-admin \
	--p2p.sequencer.key=$SEQ_KEY \
	--l1=$L1_RPC \
	--l1.rpckind=$RPC_KIND
```

**System Specs:**
 - OS: Ubuntu-20.04

**Comment by tynes** [comment]
Is this for a private network or are you syncing a public network like mainnet/testnet?

**Comment by Aymen-Tirchi** [comment]
it's for a test network I'm using Goerli

**Comment by RISHABHAGRAWALZRA** [comment]
Yes, I am also facing the same issue, Pls let me know if you found any solution @Aymen-Tirchi

**Comment by protolambda** [comment]
This timeout may happen if the op-node is too busy to answer a consistent sync-status, which may happen during syncing of the chain.

**Comment by Aymen-Tirchi** [comment]
I got this from [optimism discord](https://discord.gg/optimism) 
Synchronization takes time
op-batcher might have warning messages similar to:
```
WARN [03-21|14:13:55.248] Error calculating L2 block range         err="failed to get sync status: Post \"http://localhost:8547\": context deadline exceeded"
WARN [03-21|14:13:57.328] Error calculating L2 block range         err="failed to get sync status: Post \"http://localhost:8547\": context deadline exceeded"
```
This means that op-node is not yet synchronized up to the present time. Just wait until it is.
check out this [Rollup Operations](https://stack.optimism.io/docs/build/operations/#)
@RISHABHAGRAWALZRA
