### ISSUE TITLE
legacy-geth trace failed because of `out of gas`

### ISSUE THREAD

**Issue by XieSen** [ethereum-optimism/optimism#6537]
**Describe the bug**
I use a self-hosting legacy-geth to trace blocks to get internal transactions.  I find some block trace requests failed with an  `out of gas` error. But its receipt status is success, also they will succeed in https://mainnet.optimism.io/. 
Those error traces occured when block number > 3 million. They cost more gas in executing some instructions than they did in https://mainnet.optimism.io/, so they failed with a `out of gas` error.

I checked logs, got below content:
```
Initialised chain configuration          config="{ChainID: 10 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Engine: clique}"
```
It seems like my chain configuration is broken. This may explain why incorrect gas cost in my fullnode.

I downloaded the chaindata from https://community.optimism.io/docs/useful-tools/networks/#parameters-for-node-operators. I verified the archive through a sha512 checksum calculation, it's ok.

Anyone can help me, thank you!

**To Reproduce**
1. download legacy-geth chaindata from https://community.optimism.io/docs/useful-tools/networks/#parameters-for-node-operators
2. start a legacy-geth using extracted chaindata
3. check the log, you will see the wrong chain configuration. I did multiple times.
4. do a trace block request, example block number: 3950111
```
curl --location 'https://mainnet.optimism.io' \
--header 'Content-Type: application/json' \
--data '{
    "method": "debug_traceBlockByNumber",
    "params": [
        "0x3c461f",
        {
            "tracer": "callTracer"
        }
    ],
    "id": 1,
    "jsonrpc": "2.0"
}'
```

**Expected behavior**
trace got success as it does in https://mainnet.optimism.io/.

**Screenshots**
this is legacy-geth log
![image](https://github.com/ethereum-optimism/optimism/assets/12810364/ddf3f3a0-1ae1-48be-9390-d8e22f9b6de1)

this is docker config
![image](https://github.com/ethereum-optimism/optimism/assets/12810364/b1ad0e40-b12d-4e20-8798-684c8610130d)

this is trace response difference
<img width="1388" alt="image" src="https://github.com/ethereum-optimism/optimism/assets/12810364/675cf980-7a55-4c85-90f9-1ca6161677e2">

**System Specs:**
 - OS: aws linux
 - Package Version (or commit hash): ethereumoptimism/l2geth:0.5.31

**Additional context**

**Comment by XieSen** [comment]
problem fixed, caused by a wrong l2geth version

**Comment by harshsingh-cs** [comment]
@XieSen which l2geth version you used ?
