### ISSUE TITLE
Bridge UI for OP-Stack chain

### ISSUE THREAD

**Issue by nitantchhajed** [ethereum-optimism/optimism#6561]
**Is your feature request related to a problem? Please describe.**
The OP-Stack chain tutorial doesn't provide the UI for the bridge, which makes it difficult for non-so tech users to bridge using the sdk.

**Describe the solution you'd like**
I would like you guys to take a look into the fuctional UI that I've made for my OP-Stack chain, then we can work together to Implement this for the universal OP-Stack chain by making the needed changes into it.

http://testnet-bridge.raceconomy.com/

https://github.com/nitantchhajed/op-stack-bridge.git

**Comment by tynes** [comment]
Thank you for sharing this! cc @binjix23

It is also possible to send ether to L2 by simply using metamask and doing a transfer to the OptimismPortalProxy smart contract

**Comment by roninjin10** [comment]
Open sourcing the bridge UI is work that is in progress. Stay tuned for updates. cc @zainbacchus @nitaliano

**Comment by priyanshuthapliyal** [comment]
> **Is your feature request related to a problem? Please describe.** The OP-Stack chain tutorial doesn't provide the UI for the bridge, which makes it difficult for non-so tech users to bridge using the sdk.
> 
> **Describe the solution you'd like** I would like you guys to take a look into the fuctional UI that I've made for my OP-Stack chain, then we can work together to Implement this for the universal OP-Stack chain by making the needed changes into it.
> 
> http://testnet-bridge.raceconomy.com/
> 
> https://github.com/nitantchhajed/op-stack-bridge.git

Can we use this bridge ui for local devnet that we run using docker?
