### ISSUE TITLE
deriving empty batches from L1

### ISSUE THREAD

**Issue by cifer76** [ethereum-optimism/optimism#6576]
My RPC node print such logs during deriving from L1, it says the batch has 0 transactions which I think it's impossible, at least it should has a L1 deposit tx right?

```
t=2023-08-02T16:47:19+0000 lvl=dbug msg="Adding batch"                           batch_timestamp=1,690,942,370 parent_hash=0x670f81bbb78a8a38a4415037ab9df64758fff80addeca89db313d62fc01cff41 batch_epoch=0x814b83836ac58b28c9c5f814ccd964844fbf690acab2e4a5292a3b63fcd785fb:9447751 txs=0
```

**Comment by tynes** [comment]
The deposit transactions are not submitted as part of the batch, the data is already on L1
