### ISSUE TITLE
An own implemented ERC20 or a created ERC20 by `OptimismMintableERC20Factory`?

### ISSUE THREAD

**Issue by egonspace** [ethereum-optimism/optimism#6595]
Just question.

We are preparing to deploy an ERC20 token on Optimism L2. Our token is already on ETH. We want to deploy a token that implements `IERC1363` for compatibility with the tokens on ETH, and we have confirmed that it can be paired to the origin on the StandardBridge as long as we implements `IOptimismMintableERC20` for the token. But we are debating whether to link our own implemented token or a token created through `createOptimismMintableERC20()`.
When createOptimismMintableERC20() is executed, it seems that the `OptimismMintableERC20Created` event is issued(https://github.com/ethereum-optimism/optimism/blob/38c8a267788f1ffd13139656638bdb31de78eda5/packages/contracts-bedrock/src/universal/OptimismMintableERC20Factory.sol#L83). Is this event particularly important? Can you tell me where it is used?

**Comment by 3esmit** [comment]
If the applications you going to run on the Optimism side require the IERC1363, then you should do your own version of the token. If maybe is the answer, then you should also do it. 

Regarding the event, I don't know the answer, but it seems like its not used by the bridge itself. I've implemented a custom token and deployed it directly (with no factory), and it worked just fine. The event is probably there to make easier for a user/ui to determine the localToken in the transaction receipt, as when createOptimismMintableERC20 called directly you won't have that return used anywhere.

**Comment by tynes** [comment]
Nothing is particularly important about that event. Perhaps it is used for discoverability but adding the token to the token list will get it in the UI. See https://github.com/ethereum-optimism/ethereum-optimism.github.io

**Comment by egonspace** [comment]
It helped me a lot. Thank you so much.
