### ISSUE TITLE
Why we filter out batches that were included too late?

### ISSUE THREAD

**Issue by cifer76** [ethereum-optimism/optimism#6606]
I met the "batch was included too late" issue on production and the blocks can never be proceeded.

after checking the code I found such filtering rule:

https://github.com/ethereum-optimism/optimism/blob/develop/op-node/rollup/derive/batches.go#L64-L67

```
	// Filter out batches that were included too late.
	if uint64(batch.Batch.EpochNum)+cfg.SeqWindowSize < batch.L1InclusionBlock.Number {
		log.Warn("batch was included too late, sequence window expired")
		return BatchDrop
	}
```

If for some reason our batcher stopped running, and then recovers and continues writing batches to L1, the batches will be written to newer L1 blocks so that be even "late".
If we filter out them here, the same batch will never be able to derived right?

**Comment by tynes** [comment]
This is to guarantee liveliness of the system, meaning that deposits will always be included within a time period
