### ISSUE TITLE
feat: Create a @eth-optimism/configs package

### ISSUE THREAD

**Issue by roninjin10** [ethereum-optimism/optimism#6629]
## Affected Packages

All TS packages

## Problem

- Can't reuse our base configs in other repos
- Caches like nx cache are more complicated to configure to break when configs change
- Root of repo is pretty noisy with configs
- It's generally a bad practice in package based repos to do absolute paths to outside of the package

## Proposed solution

1. Create a new package `@eth-optimism/configs` in `packages/configs`
2. Move tsconfig, prettier config, and eslint config to this package
3. Update references to configs from `../../tsconfig.json` to `@eth-optimism/configs/tsconfig.json`
4. Clean up: Remove the configs from nx.json
5. Clean up: remove the configs from `checked-changed` python script

**Comment by Sah314** [comment]
@roninjin10 can you assign me?

**Comment by aliaaquib** [comment]
@roninjin10 I want to work on that issue

**Comment by roninjin10** [comment]
@Sah314 looks like you got first dibs

**Comment by roninjin10** [comment]
@aliaaquib if @Sah314 isn't able to do it you are next up. Keep eyes on issues tab I will be trying to make more good first issues moving forward

**Comment by roninjin10** [comment]
@Sah314 let me know if you still plan on finishing https://github.com/ethereum-optimism/optimism/pull/6649 it was pretty close

**Comment by roninjin10** [comment]
@aliaaquib you are up! Let me know if you need help. #6649 was mostly complete so could pick up there

**Comment by aliaaquib** [comment]
> @aliaaquib you are up! Let me know if you need help. #6649 was mostly complete so could pick up there

Sure

**Comment by aliaaquib** [comment]
@roninjin10 There is no `config` file in `packages/configs` can you please have a look.

**Comment by roninjin10** [comment]
Yes the previous assignee force pushed away the changes. The previous assignee did add the config files as can be seen here https://github.com/ethereum-optimism/optimism/commit/b12d1b126a8dc72e9a15cef51fd5e0e572884af3#diff-7073466fab8833385922059f8cdd3e64df6171df380abde93492b9ed4d5d695e

**Comment by Realrobwoodx** [comment]
I have no clue what this is or why I’m even here
