### ISSUE TITLE
Is it possible to run bundler with OP-Stack chain ?

### ISSUE THREAD

**Issue by nitantchhajed** [ethereum-optimism/optimism#6639]
just wanna know if it is possible to run bundler with OP-Stack chain, if yes, then how to run it ?

**Comment by tynes** [comment]
Its definitely possible, we do not maintain bundler software but you should be able to find a bundler that has docs on how to run it

**Comment by nitantchhajed** [comment]
if it is possible, can you suggest me or provide a link to a compatible bundler ? and one more thing, my op-stack chain will still be eligible for superchain if I use bundler ?
thanks !

**Comment by tynes** [comment]
Yes it is certainly possible to be part of the superchain when running a bundler :)
