### ISSUE TITLE
Unable to broadcast transaction from op-geth

### ISSUE THREAD

**Issue by justsowaka** [ethereum-optimism/optimism#6667]
I run an op full node, the node has been synchronized to the latest block, but I can't broadcast the transaction, that is, I can't transfer eth, but I change to a third-party public node and my transfer is successful, can you tell me Why can't my full node run by myself transfer funds?
My parameters must be fine, because I replaced my local node with a third-party node and the transfer was successful.

**Comment by justsowaka** [comment]
Unable to broadcast transaction from OP node

**Comment by RISHABHAGRAWALZRA** [comment]
Does this is related to #6534 somehow? I am facing both the issues

**Comment by justsowaka** [comment]
I saw the problem you are facing. You should start op-geth first and then start op-node. After the op-node synchronization is completed, op-geth will synchronize the block normally. I have already run the block to normal, but I still Unable to broadcast transactions with self-built nodes

**Comment by protolambda** [comment]
Are you configuring op-geth with `--rollup.sequencerhttp`? And on which chain are you running this on?

**Comment by justsowaka** [comment]
I didn't add this parameter, is this related to my node's inability to send transactions？

**Comment by justsowaka** [comment]
Thanks a lot, it's time to broadcast the deal

**Comment by justsowaka** [comment]
I have no problem sending eth with the node I built, but there is still a problem sending erc20, or is there a problem with my configuration?
