### ISSUE TITLE
Unable to run op-stack with local L1 layer like with ganache or anvil

### ISSUE THREAD

**Issue by RISHABHAGRAWALZRA** [ethereum-optimism/optimism#6698]
I am unable to deploy the L1 contracts, I am following the [Getting-Started doc](https://stack.optimism.io/docs/build/getting-started/#configure-your-network)

I am getting this error of `script failed` while running this command `forge script scripts/Deploy.s.sol:Deploy --private-key $PRIVATE_KEY --broadcast --rpc-url $ETH_RPC_URL`

> rishabhagrawal@192 contracts-bedrock % forge script scripts/Deploy.s.sol:Deploy --private-key $PRIVATE_KEY --broadcast --rpc-url $ETH_RPC_URL
> [⠃] Compiling...
> No files changed, compilation skipped
> Traces:
>   [43008596] → new Deploy@0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519
>     └─ ← 214183 bytes of code
> 
>   [3026838] Deploy::setUp() 
>     ├─ [0] VM::projectRoot() [staticcall]
>     │   └─ ← /Users/rishabhagrawal/Data/Workspace/Avail/optimism/packages/contracts-bedrock
>     ├─ [0] VM::envOr(DEPLOY_SCRIPT, Deploy) 
>     │   └─ ← <env var value>
>     ├─ [0] VM::envOr(DEPLOYMENT_CONTEXT, ) 
>     │   └─ ← <env var value>
>     ├─ [0] VM::envOr(DEPLOY_FILE, run-latest.json) 
>     │   └─ ← <env var value>
>     ├─ [0] VM::envOr(CHAIN_ID, 1337) 
>     │   └─ ← <env var value>
>     ├─ [0] VM::toString(1337) [staticcall]
>     │   └─ ← 0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000043133333700000000000000000000000000000000000000000000000000000000
>     ├─ [0] VM::createDir(/Users/rishabhagrawal/Data/Workspace/Avail/optimism/packages/contracts-bedrock/deployments/getting-started, true) 
>     │   └─ ← ()
>     ├─ [0] VM::readFile(/Users/rishabhagrawal/Data/Workspace/Avail/optimism/packages/contracts-bedrock/deployments/getting-started/.chainId) [staticcall]
>     │   └─ ← <file>
>     ├─ [0] VM::envOr(STRICT_DEPLOYMENT, true) 
>     │   └─ ← <env var value>
>     ├─ [0] VM::parseUint(1337) [staticcall]
>     │   └─ ← 1337
>     ├─ [0] console::log(Connected to network with chainid %s, 1337) [staticcall]
>     │   └─ ← ()
>     ├─ [0] VM::readFile(/Users/rishabhagrawal/Data/Workspace/Avail/optimism/packages/contracts-bedrock/deployments/getting-started/.deploy) [staticcall]
>     │   └─ ← <file>
>     ├─ [0] console::log(Storing temp deployment data in %s, /Users/rishabhagrawal/Data/Workspace/Avail/optimism/packages/contracts-bedrock/deployments/getting-started/.deploy) [staticcall]
>     │   └─ ← ()
>     ├─ [0] VM::projectRoot() [staticcall]
>     │   └─ ← /Users/rishabhagrawal/Data/Workspace/Avail/optimism/packages/contracts-bedrock
>     ├─ [2583705] → new <Unknown>@0xC7f2Cf4845C6db0e1a1e91ED41Bcd0FcC1b0E141
>     │   ├─ [0] console::log(DeployConfig: reading file %s, /Users/rishabhagrawal/Data/Workspace/Avail/optimism/packages/contracts-bedrock/deploy-config/getting-started.json) [staticcall]
>     │   │   └─ ← ()
>     │   ├─ [0] VM::readFile(/Users/rishabhagrawal/Data/Workspace/Avail/optimism/packages/contracts-bedrock/deploy-config/getting-started.json) [staticcall]
>     │   │   └─ ← <file>
>     │   ├─ [0] VM::parseJsonAddress(<stringified JSON>, $.finalSystemOwner) 
>     │   │   └─ ← 0xe42a3E5D36265D5bce471b7eDa3D3fD018991fBC
>     │   ├─ [0] VM::parseJsonAddress(<stringified JSON>, $.portalGuardian) 
>     │   │   └─ ← 0xe42a3E5D36265D5bce471b7eDa3D3fD018991fBC
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.l1ChainID) 
>     │   │   └─ ← 1337
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.l2ChainID) 
>     │   │   └─ ← 42069 [4.206e4]
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.l2BlockTime) 
>     │   │   └─ ← 2
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.maxSequencerDrift) 
>     │   │   └─ ← 600
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.sequencerWindowSize) 
>     │   │   └─ ← 3600
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.channelTimeout) 
>     │   │   └─ ← 300
>     │   ├─ [0] VM::parseJsonAddress(<stringified JSON>, $.p2pSequencerAddress) 
>     │   │   └─ ← 0x7B66446cF8a193d3241bD86F95211144948E12d6
>     │   ├─ [0] VM::parseJsonAddress(<stringified JSON>, $.batchInboxAddress) 
>     │   │   └─ ← 0xFf00000000000000000000000000000000042069
>     │   ├─ [0] VM::parseJsonAddress(<stringified JSON>, $.batchSenderAddress) 
>     │   │   └─ ← 0xF511CccF2304FB1bC433a1d38C535fC655a6F6F7
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.l2OutputOracleSubmissionInterval) 
>     │   │   └─ ← 120
>     │   ├─ [0] VM::parseJsonInt(<stringified JSON>, $.l2OutputOracleStartingTimestamp) 
>     │   │   └─ ← 1691604266
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.l2OutputOracleStartingBlockNumber) 
>     │   │   └─ ← 0
>     │   ├─ [0] VM::parseJsonAddress(<stringified JSON>, $.l2OutputOracleProposer) 
>     │   │   └─ ← 0x65E5dD681f21D1614b12E623ebe1366543093815
>     │   ├─ [0] VM::parseJsonAddress(<stringified JSON>, $.l2OutputOracleChallenger) 
>     │   │   └─ ← 0xe42a3E5D36265D5bce471b7eDa3D3fD018991fBC
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.finalizationPeriodSeconds) 
>     │   │   └─ ← 12
>     │   ├─ [0] VM::parseJsonAddress(<stringified JSON>, $.proxyAdminOwner) 
>     │   │   └─ ← 0xe42a3E5D36265D5bce471b7eDa3D3fD018991fBC
>     │   ├─ [0] VM::parseJsonAddress(<stringified JSON>, $.baseFeeVaultRecipient) 
>     │   │   └─ ← 0xe42a3E5D36265D5bce471b7eDa3D3fD018991fBC
>     │   ├─ [0] VM::parseJsonAddress(<stringified JSON>, $.l1FeeVaultRecipient) 
>     │   │   └─ ← 0xe42a3E5D36265D5bce471b7eDa3D3fD018991fBC
>     │   ├─ [0] VM::parseJsonAddress(<stringified JSON>, $.sequencerFeeVaultRecipient) 
>     │   │   └─ ← 0xe42a3E5D36265D5bce471b7eDa3D3fD018991fBC
>     │   ├─ [0] VM::parseJsonString(<stringified JSON>, $.governanceTokenName) 
>     │   │   └─ ← Optimism
>     │   ├─ [0] VM::parseJsonString(<stringified JSON>, $.governanceTokenSymbol) 
>     │   │   └─ ← OP
>     │   ├─ [0] VM::parseJsonAddress(<stringified JSON>, $.governanceTokenOwner) 
>     │   │   └─ ← 0xe42a3E5D36265D5bce471b7eDa3D3fD018991fBC
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.l2GenesisBlockGasLimit) 
>     │   │   └─ ← 30000000 [3e7]
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.l2GenesisBlockBaseFeePerGas) 
>     │   │   └─ ← 1000000000 [1e9]
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.gasPriceOracleOverhead) 
>     │   │   └─ ← 2100
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.gasPriceOracleScalar) 
>     │   │   └─ ← 1000000 [1e6]
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.eip1559Denominator) 
>     │   │   └─ ← 50
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.eip1559Elasticity) 
>     │   │   └─ ← 10
>     │   ├─ [0] VM::parseJsonUint(<stringified JSON>, $.systemConfigStartBlock) 
>     │   │   └─ ← "No matching value or array found for key $.systemConfigStartBlock"
>     │   └─ ← 0 bytes of code
>     └─ ← "No matching value or array found for key $.systemConfigStartBlock"
> 
> 
> 
> == Logs ==
>   Connected to network with chainid 1337
>   Storing temp deployment data in /Users/rishabhagrawal/Data/Workspace/Avail/optimism/packages/contracts-bedrock/deployments/getting-started/.deploy
>   DeployConfig: reading file /Users/rishabhagrawal/Data/Workspace/Avail/optimism/packages/contracts-bedrock/deploy-config/getting-started.json
> Error: 
> Script failed.

As per my research and understanding, In DeployerConfig.s.sol, it is trying to read systemConfigStartBlock from the getting-started.json file, but there is no such config variable given in that file.

<img width="832" alt="Screenshot 2023-08-10 at 1 02 17 PM" src="https://github.com/ethereum-optimism/optimism/assets/43982251/f18708a2-24ff-4d90-b5cd-23e31264b393">

is this a recent change? Please help if anyone faces the same issue or has any solution and understanding for this.

**Comment by nitantchhajed** [comment]
@RISHABHAGRAWALZRA 
add `"systemConfigStartingBlock" : 0` in your `getting-started.json` file.

And I saw your further Issue using Ganache on Discord,
just replace `1337` in `Chains.sol` with something random number so the script won't require those extra `dispute-game` configurations https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/scripts/Chains.sol

or you can add `faultGameMaxDepth` , `faultGameAbsolutePrestate` , `faultGameMaxDuration` in your `getting-started.json` if you are using Ganache or change the `chain ID` of ganache. : )

**Comment by ishanjain28** [comment]
Hey, The field name here is, `systemConfigStartBlock`.

**Comment by nitantchhajed** [comment]
> Hey, The field name here is, `systemConfigStartBlock`.

my bad.

**Comment by sbvegan** [comment]
I see that `systemConfigStartBlock` has been added to `packages/contracts-bedrock/deploy-config/devnetL1.json` but its not in any of the other configuration files in `packages/contracts-bedrock/deploy-config`.

So instead of adding this to the `packages/contracts-bedrock/deploy-config/getting-started.json`, I think the `packages/contracts-bedrock/scripts/DeployConfig.s.sol` might need to be updated instead.

I wonder if line 91:

```
systemConfigStartBlock = stdJson.readUint(_json, "$.systemConfigStartBlock");
```

should belong in the following conditional statement:

```
if (block.chainid == Chains.LocalDevnet || block.chainid == Chains.GethDevnet) {
...
}
```

**Comment by ec2ainun** [comment]
perhaps you can checkout latest tag?
`git checkout 4ef51e1 -b stable`

i encountered familiar problem today, and now i can interact with OP stack

**Comment by 0xefrain** [comment]
> perhaps you can checkout latest tag? `git checkout 4ef51e1 -b stable`
> 
> i encountered familiar problem today, and now i can interact with OP stack

These work for me thanks !

**Comment by RISHABHAGRAWALZRA** [comment]
> perhaps you can checkout latest tag? `git checkout 4ef51e1 -b stable`
> 
> i encountered familiar problem today, and now i can interact with OP stack

Thanks, yes, there is no check for `systemConfigStartBlock` in this tag.

**Comment by RISHABHAGRAWALZRA** [comment]
But now I am getting this error
<img width="1081" alt="Screenshot 2023-08-11 at 11 46 44 AM" src="https://github.com/ethereum-optimism/optimism/assets/43982251/618b809b-52de-4904-9e57-bd1275f67017">

Basically I am using ganache-cli for local L1 layer and set the chain id 1999, I think this is the reason I am getting this error 

Do anyone how to run OP-Stack locally by using local L1 layer, what other changes required to run it?

**Comment by nitantchhajed** [comment]
@tynes can you please look into this ??

**Comment by RISHABHAGRAWALZRA** [comment]
> But now I am getting this error <img alt="Screenshot 2023-08-11 at 11 46 44 AM" width="1081" src="https://user-images.githubusercontent.com/43982251/259934910-618b809b-52de-4904-9e57-bd1275f67017.png">
> 
> Basically I am using ganache-cli for local L1 layer and set the chain id 1999, I think this is the reason I am getting this error
> 
> Do anyone how to run OP-Stack locally by using local L1 layer, what other changes required to run it?

It been resolved, basically in the `4ef51e1` tag there is `.chainid and .deploy` file already present in the `getting-started` folder which is causing the problem, so I just removed them and then tried again, it worked

**Comment by nitantchhajed** [comment]
@RISHABHAGRAWALZRA thanks for sharing !!, you can close the Issue if you contracts are deployed successfully

**Comment by RISHABHAGRAWALZRA** [comment]
I am now, getting stuck here, my L1 layer block time is 10s but I don't know why it is showing this 

<img width="1078" alt="Screenshot 2023-08-11 at 4 35 00 PM" src="https://github.com/ethereum-optimism/optimism/assets/43982251/2480bc0b-e4ad-42d9-96e4-8f6fffc497fb">

can you pls check or do you know how to resolve it? @nitantchhajed @tynes

**Comment by Aymen-Tirchi** [comment]
just add this line `"l1BlockTime": 3,` to your `getting-started.json`
I used 3 because it's larger than 2
@RISHABHAGRAWALZRA

**Comment by norfolkpine** [comment]
> just add this line `"l1BlockTime": 3,` to your `getting-started.json` I used 3 because it's larger than 2 @RISHABHAGRAWALZRA

I think this is just a hack to get around the error.
Blocktime for L1 should be 12, so there must be an error in the code somewhere
https://stack.optimism.io/docs/build/conf/#misc

**Comment by RISHABHAGRAWALZRA** [comment]
I am getting this error on running op-node using local L1 layer like with anvil or ganache

<img width="1140" alt="Screenshot 2023-08-13 at 1 09 51 PM" src="https://github.com/ethereum-optimism/optimism/assets/43982251/ac1a6b39-eadc-413c-97db-44c8ccb1ddc2">

**Comment by RISHABHAGRAWALZRA** [comment]
What does this proof of storage slot and unsafe block signing? @tynes

**Comment by tynes** [comment]
This is a recent change, a fix has been merged. It seemed like you were almost able to solve the issue, we are open to you opening PRs with solutions in the future :)

**Comment by tynes** [comment]
> I am getting this error on running op-node using local L1 layer like with anvil or ganache
> 
> <img width="1140" alt="Screenshot 2023-08-13 at 1 09 51 PM" src="https://github.com/ethereum-optimism/optimism/assets/43982251/ac1a6b39-eadc-413c-97db-44c8ccb1ddc2">
> 

The L1 contracts must be deployed. There is no guarantee opnode will work with ganache/anvil. We have a devnet that you can develop against using `make devnet-up`

**Comment by RISHABHAGRAWALZRA** [comment]
Which L1 contracts have to deploy, I think they are not given in this doc https://community.optimism.io/docs/protocol/protocol-2.0/# @tynes

**Comment by tynes** [comment]
> Which L1 contracts have to deploy, I think they are not given in this doc https://community.optimism.io/docs/protocol/protocol-2.0/# @tynes 

You will want to run the same command you posted in your first comment to deploy the L1 contracts

**Comment by RISHABHAGRAWALZRA** [comment]
Does this include every L1 contract https://community.optimism.io/docs/protocol/protocol-2.0/#l1-contracts? @tynes

**Comment by nitantchhajed** [comment]
> Does this include every L1 contract https://community.optimism.io/docs/protocol/protocol-2.0/#l1-contracts? @tynes

No that list does not include all the contracts that are deployed on L1. 

Here are the Contracts which are deployed on L1 -

```
AddressManager
ProxyAdmin
OptimismPortalProxy
L2OutputOracleProxy
SystemConfigProxy
L1StandardBridgeProxy
L1CrossDomainMessengerProxy
OptimismMintableERC20FactoryProxy
L1ERC721BridgeProxy
OptimismPortal
L1CrossDomainMessenger
L2OutputOracle
OptimismMintableERC20Factory
```

**Comment by roninjin10** [comment]
I don't believe anvil has ever worked with running op stack chains though I haven't checked the status of some blockers there in a while. If only one chain is needed forking a live chain with anvil is a great approach but if you need cross chain messages or any actual rollup functionality using the optimism devnet is the best approach

**Comment by nitantchhajed** [comment]
> I don't believe anvil has ever worked with running op stack chains though I haven't checked the status of some blockers there in a while. If only one chain is needed forking a live chain with anvil is a great approach but if you need cross chain messages or any actual rollup functionality using the optimism devnet is the best approach

Is Optimism devnet an L1 CHAIN ??

**Comment by roninjin10** [comment]
> > I don't believe anvil has ever worked with running op stack chains though I haven't checked the status of some blockers there in a while. If only one chain is needed forking a live chain with anvil is a great approach but if you need cross chain messages or any actual rollup functionality using the optimism devnet is the best approach
> 
> Is Optimism devnet an L1 CHAIN ??

L1 and L2 as specified in the docker-compose https://github.com/ethereum-optimism/optimism/blob/develop/ops-bedrock/docker-compose.yml#L14

**Comment by tynes** [comment]
We do not support running `op-node` against ganache or anvil
