### ISSUE TITLE
Will the non-sequencer op-node relay blocks received from the sequencer?

### ISSUE THREAD

**Issue by cifer76** [ethereum-optimism/optimism#6700]
Hi team, have a question about the op-node p2p sync, as my understanding, the sequencer is the source of the block broadcast messages, other op-nodes connects to sequencer to get notified about the new blocks.
While we know that not all op-nodes connect to sequencer directly, the topology could be:
```
sequencer <-> op-nodeA <-> op-nodeB
```
so now when a new block is produced, op-nodeA will firstly get notified by the sequencer, but how about op-nodeB, will op-nodeA forward the new block message to op-nodeB?
I guess so based on my observing, just want to double confirm with you

**Comment by ajsutton** [comment]
Yes the gossip protocol forms a mesh of nodes that gossip the blocks between them, in the same way that happens on L1 (exactly the same as for the L1 consensus layer right down to using the same protocol). It's the libp2p gossipsub protocol that's used.
