### ISSUE TITLE
op-service: backoff package improvements

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#6730]
op-service `backoff` package improvements:
https://github.com/ethereum-optimism/optimism/tree/develop/op-service/backoff

Refactor utils + usages to use `time.Duration` instead of `float`/`int`.

**Comment by Rcontre360** [comment]
Hi! First time here. Would like to work on this, seems simple and perfect for someone starting to contribute :). I have a doubt as I see is only changing few value types to "time.Duration". It says “Refactor” so is there any other change apart from that one?

**Comment by mslipper** [comment]
Hi @Rcontre360!

The refactor part is referring to changing the usages of the backoff functions to use the `time.Duration` API. Apart from that you'll need to change few value types to `time.Duration` and update the logic to use the `time.Duration` values.

If you're interested in taking this, please go ahead and open a PR!

**Comment by protolambda** [comment]
Don't forget that the usages across the monorepo also need to be updated. But yes, it should be a small change

**Comment by mslipper** [comment]
Fixed in https://github.com/ethereum-optimism/optimism/pull/6823.
