### ISSUE TITLE
op-service: cleanup stringer types with `~string` generic

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#6732]
`Stringered` / `StringeredList` / `EnumString` are hacky. We can get rid of the `Stringer` stuff, and use `~string` (generic type, captures types of underlying string type) and use that to support `EnumString`. These helper funcs are used in things like the CLI flag construction, of which the usage will have to be updated.

**Comment by CarterBloop** [comment]
Hello, I'd like to work on this issue. It would be my first issue, so other than testing the op-service package and any other packages that use EnumString, what else should look for? Thank you!

**Comment by protolambda** [comment]
@CarterBloop sounds good! PRs welcome. I think the description covers everything, let me know if you have questions.
