### ISSUE TITLE
op-service: cleanup logging service utils

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#6734]
- [ ] We should refactor the log flags to use `cli.GenericFlag`, which can then validate the flag value during flag-parsing time, instead of requiring `config.Check()`
- [ ] The log writes to `os.Stdout` but should be writing to `app.Writer`, so we can test the CLI better, by running the urfave app commands and outputting into a buffer/checker.
- [ ] Remove side-effects: The local logger config affects the global logger: this is undocumented/bad side-effect behavior. `NewLogger` should not touch `log.Root()`.
- [ ] Log-level should be runtime-configurable. We can have an `admin_setLogLevel` RPC endpoint to change it.
- [ ] Move testlog package from op-node to op-service

**Comment by dhanusaputra** [comment]
hi, can I help with this task please?

**Comment by protolambda** [comment]
@dhanusaputra sure, PRs are welcome. Please ensure not to break CLI flag compatibility with the current logging.

**Comment by trianglesphere** [comment]
> Remove side-effects: The local logger config affects the global logger: this is undocumented/bad side-effect behavior. NewLogger should not touch log.Root().

The stated reason for doing this in the code was the set geth's logger. I feel like we would still want this otherwise we might have two different logging formats. The other option is that the comment was wrong & this isn't an issue.

**Comment by protolambda** [comment]
@trianglesphere we should just set the geth logger explicitly, rather than relying on side-effects

**Comment by trianglesphere** [comment]
> we should just set the geth logger explicitly, rather than relying on side-effects


Let's add this to the ticket. TBH I'm not sure how to do this, but also haven't looked closely.
