### ISSUE TITLE
fix: Use RefMetrics and Event from op-service/metrics package

### ISSUE THREAD

**Issue by sebastianst** [ethereum-optimism/optimism#6735]
### Description

While implementing batcher metrics (https://github.com/ethereum-optimism/optimism/pull/5167), reusable metrics components were copied from the `op-node/metrics` package into `op-service/metrics`, but not used in the op-node metrics itself yet.

Goal of this issue is to use `RefMetrics` and `Event` from package `op-service/metrics` in the op-node metrics and then remove the unused code there.

### Metadata
* Contact: @refcell 
* Closes CLI-3642

**Comment by refcell** [comment]
Fixed in #7329
