### ISSUE TITLE
Insufficiently descriptive error messages 

### ISSUE THREAD

**Issue by vladopajic** [ethereum-optimism/optimism#6736]
Error messages are not sufficiency descriptive when starting applications (eg. `op-node`). They should provide more information (possibly entire error stack) to the user in order for them to be able to pinpoint issue. 

In the below example there is log output of `op-node` app, please note that this log output does not have enough description for user to understand issue without digging deep into source code.
```
t=2023-08-11T13:32:41+0000 lvl=eror msg="Unable to create the rollup node"      error="401 Unauthorized: user project is inactive\n"
t=2023-08-11T13:32:41+0000 lvl=crit msg="Application failed"                    message="401 Unauthorized: user project is inactive\n"
```

**Comment by protolambda** [comment]
It looks like the node hit an RPC error on the L1 RPC endpoint you provided to it. Since the L2 RPC is your local node. The Error should indeed be more descriptive to include the information about the L1 RPC source being the cause of the error.

**Comment by tynes** [comment]
@vladopajic Definitely open to a PR fixing this :D

**Comment by vladopajic** [comment]
@tynes unfortunately i don't have bandwidth to work on that.


----

similar issue: 

```
t=2023-08-15T09:37:55+0000 lvl=eror msg="Error initializing the rollup node" err="Post \"http://eth-node.local:8545\": context deadline exceeded"
t=2023-08-15T09:37:55+0000 lvl=eror msg="Unable to create the rollup node"   error="Post \"http://eth-node.local:8545\": context deadline exceeded"
t=2023-08-15T09:37:55+0000 lvl=crit msg="Application failed"                 message="Post \"http://eth-node.local:8545\": context deadline exceeded"
```
