### ISSUE TITLE
op-service: pprof util package improvements

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#6739]
- [ ] profile from start of program
  We should add the option to start profiling from the start of the program (with one of the profile types) to capture program start-up performance, and not have to call the pprof http API after startup.
- [ ] Use `cli.GenericFlag` to validate flag contents upon CLI flag parsing time.

**Comment by shubhamshd** [comment]
Hi @protolambda & @refcell I would like to work on this issue, if its fine?
One small request though, if you could please explain the issue in a bit detail?
many thanks!!!

**Comment by protolambda** [comment]
@shubhamshd you can search more info about pprof online, it's a pretty common performance testing library. It can be used via API, or started programmatically. We have the former, but also want the option to use the latter.

**Comment by shubhamshd** [comment]
ok sure @protolambda I'd research and then add my contribution to the repo, thanks!!!

**Comment by shubhamshd** [comment]
apologies @protolambda but with my limited knowledge of this repo and pprof library, it seems to me that we already have cli driven pprof setup and not the api driven as you mentioned earlier?

**Comment by protolambda** [comment]
@shubhamshd the API is configurable through CLI, but profiling is not yet possible to enable at startup through the CLI.

**Comment by shubhamshd** [comment]
@protolambda I see the pprof server being started in different modules based on pprof.enabled flag, here is an example
https://github.com/ethereum-optimism/optimism/blob/18bcfb0dcc16de4287cb614f0a0b7bb3c276cbd3/op-node/cmd/main.go#L153C1-L153C1 

This makes me believe that starting pprof server through cli is already implemented and I am not able to exactly understand as to how is this API enabled and not programatically enabled specially with above example setup in place!!!

Please bear my noob questions, I just don't want to give up.
However, if this is high priority issue then I am ready to hand this over to any expert if available!!!

Thanks :)

**Comment by shubhamshd** [comment]
Follow up question to the above one, is there any specific file/module, where I need to enable the pprof server to make it run at the program startup?
