### ISSUE TITLE
op-service: opio change to use cleaner urfave v2 shutdown pattern

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#6742]
- [ ] `opio` waits for interrupt signal, but doesn’t cleanly close urfave CLI, we should use `app.RunContext` (urfave v2) and close the context on interrupt.
- [ ] Update the main entrypoints of all services to use the cleaner shutdown pattern.
- [ ] Force-exit on e.g. receiving 10 consecutive interrupts.

**Comment by ethenotethan** [comment]
Heyo, is this one still awaiting action? I'd love to take it on if possible!

**Comment by protolambda** [comment]
@epociask yes, let me know if you have more questions.

**Comment by hyunchel** [comment]
@protolambda I'm giving a shot since the other PR is closed.
Would you mind advising the PR? I'm looking for a help on adding tests.

**Comment by protolambda** [comment]
This isssue is as stale as the PR attempt, but thank you for checking @hyunchel, sorry I couldn't provide you with the right context earlier. See comment in #7664 for the path forward I am planning on.
