### ISSUE TITLE
Optional `L1StartingHeight` Param for OP Indexer

### ISSUE THREAD

**Issue by ethenotethan** [ethereum-optimism/optimism#6794]
**Is your feature request related to a problem? Please describe.**
Currently, running the OP Indexer with a blank database results in the application indexing all layer-1 blocks from genesis. This is very time consuming and blocks the `L2Processor` from traversing to head until correlated L1 system contract bridge events can be detected. In some circumstances this could be unnecessary since all OP Stack chains have (L2->L1) genesis commitments much later in the Ethereum ledger. Ideally, an OP Indexer user should be able to specify some L1 starting height that's indicative of some L2 genesis on L1 and the point where the `L1Processor` begins traversal. 

**Describe the solution you'd like**
Add support for an optional indexer config value (`L1StartingHeight`) that specifies a starting l1 block height for which to begin indexing chain data from.

**Describe alternatives you've considered**
* You could bypass having to reindex from L1 genesis by providing a dummy row into the `l1_block_header` psql table with the L1 (block_number - 1) height that you'd like to start sequentially indexing from. This works but is rather counterintuitive and requires a few calculated steps to properly execute. Furthermore, this assumes that a user has arbitrary write access to the indexer managed database. 

**Additional context**

**Comment by tynes** [comment]
The latest version of the system config has a `startHeight` that can be used for this
