### ISSUE TITLE
Update from golang-lru v1 to golang-lru v2 to use generics

### ISSUE THREAD

**Issue by trianglesphere** [ethereum-optimism/optimism#6892]
With the addition of golang generics, it is possible to build type safe generic containers. The golang-lru package pre-dates generics so it returned an `interface{}` and the result had to be cast.

V2 of the package now uses generics.

We use v1 in the following files:
* op-node/p2p/gossip.go
* op-node/sources/caching/cache.go

The import should be updated to V2 & the type signature will need to be added & the casting should be removed.

**Comment by ArmanMazdaee** [comment]
Hi, I'm new to the project and I'd like to start contributing. If this issue is not assigned, may I start working on it?

**Comment by trianglesphere** [comment]
Yep, assign yourself and feel free to start working on it.

**Comment by ArmanMazdaee** [comment]
I have made a pull request which updates:
- op-node/p2p/gossip.go
- op-node/sources/caching/cache.go

Also, there is another golang-lru v1 use in:
op-heartbeat/metrics.go

Do you think I should update that too? Or is that out of the scope of this issue?

**Comment by tynes** [comment]
Updating `op-heartbeat` would also be great

**Comment by ArmanMazdaee** [comment]
Sure. Pushed the op-heartbeat update too.
