### ISSUE TITLE
Fix safe head stuck for 1hour

### ISSUE THREAD

**Issue by ghost** [ethereum-optimism/optimism#6902]
**Is your feature request related to a problem? Please describe.**

Yes, safe head may stop increase for 1hour(==channelTimeOut), which is a problem to some DAPPs since they may require safe head increasing timely

I found that the team already identified this issue: https://status.optimism.io/clkhjkmre549295iqomx3wh79jr 
and revealed that team is actively working on a fix.

1. could the team describe more about the fix tech-plan? 
* plan-A: optimize op-node to support read multi-channels from channel queue 
* or plan-B: just optimize op-batcher to avoid submitting broken channel(some frame in channel is missed, which result to channel time out)
plan-B seems can not fix the issue perfectly, if batcher submitted a frame, the tx is on-chain successfully but rpc client return error to batcher due to network issue, so batcher will submit it again, this duplicated frame may cause channel queue stuck for 1hour
* or plan-C?

2. when will this be fixed?
thanks!

**Comment by tynes** [comment]
We would like to include a fix for this in the next network upgrade/hard fork. The idea would be that the next channel that is considered canonical is the first channel that closes rather than the first channel that is seen. Until then, the solution is plan B

**Comment by huihzhao** [comment]
@tynes do you have any consideration why Plan A is not good idea? want to hear more

**Comment by smartcontracts** [comment]
@tynes was this fixed?

**Comment by tynes** [comment]
This was fixed as part of the canyon network upgrade
