### ISSUE TITLE
op-service: RPC client code organization cleanup

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#6936]
Move op-node client package and base sources utils into op-service
  - [ ] `op-node/client` contains generic RPC client utils/wrappers that should be available to all services. Move all package contents.
  - [ ] `op-node/sources` contains `EthClient` and RPC batching/types utils that should be part of the op-service client package instead.
  - [ ] `op-node/testutils` contains mock bindings for the RPC interfaces, move this over too.

Split out of #6740

**Comment by Rcontre360** [comment]
Ill be working on this one then :+1:

**Comment by seungjulee** [comment]
@Rcontre360 Are you still working on this? I notice you just closed the PR. I can finish where you've left off, and get it merged.
