### ISSUE TITLE
Configurable Polling Intervals for Indexer

### ISSUE THREAD

**Issue by ethenotethan** [ethereum-optimism/optimism#6964]
**Is your feature request related to a problem? Please describe.**
Currently the op-indexer ETL [polls](https://github.com/ethereum-optimism/optimism/blob/0200fa460f03382bb4d3ec4c80c165ebf6bf485b/indexer/etl/etl.go#L16-L22) both L1 and L2 for new block events every 5 seconds. These values could be irrespective or non-proportional to actual block production rates for some L1/L2 chains. Additionally a default interval of 5 seconds may be too slow for reading L2 blocks provided the current rate of L2 block production on OP Stack chains (2 seconds per block). 

**Describe the solution you'd like**
Add support for configurable millisecond poll interval values (`L1_POLL_INTERVAL`, `L2_POLL_INTERVAL`) that allow a user to configure the respective polling rates per each chain. 

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by roninjin10** [comment]
Seems like a good idea but not necessarily something that will be needed anytime soon

**Comment by hamdiallam** [comment]
At the very minimum, we need to update the harcoded values since they should be running at a larger interval than the block times. Def would take a PR that makes these configurable! (although a reasonable default in the config should work for anyone running the indexer)

**Comment by hamdiallam** [comment]
Actually configurable is probably good since for unit tests those loops should be running like every second.

With different values for mainnet/testnet. Maybe can derive the defaults based on the existing preset key?
