### ISSUE TITLE
Unknown field "numDeployConfirmations"

### ISSUE THREAD

**Issue by carletex** [ethereum-optimism/optimism#6971]
I'm following the getting started guide https://stack.optimism.io/docs/build/getting-started/ to spin up my own OP Stack chain.

Everything works great until the "Generate the L2 config files" section. When I run:

```bash
go run cmd/main.go genesis l2 \
    --deploy-config ../packages/contracts-bedrock/deploy-config/getting-started.json \
    --deployment-dir ../packages/contracts-bedrock/deployments/getting-started/ \
    --outfile.l2 genesis.json \
    --outfile.rollup rollup.json \
    --l1-rpc **redacted**
```

I get the following error:

```bash
t=2023-08-23T09:29:16+0000 lvl=info msg="Deploy config" path=../packages/contracts-bedrock/deploy-config/getting-started.json
t=2023-08-23T09:29:16+0000 lvl=crit msg="Application failed" message="cannot unmarshal deploy config: json: unknown field \"numDeployConfirmations\""
exit status 1
```

It seems that it doesn't like the `numDeployConfirmations` field in `contracts-bedrock/deploy-config/getting-started.json`. For testing purposes I removed it, and then I get:

```bash
t=2023-08-23T09:32:29+0000 lvl=info msg="Deploy config" path=../packages/contracts-bedrock/deploy-config/getting-started.json
t=2023-08-23T09:32:29+0000 lvl=info msg="Deployment directory" path=../packages/contracts-bedrock/deployments/getting-started/
t=2023-08-23T09:32:29+0000 lvl=warn msg="L2OutputOracleStartingBlockNumber is 0, should only be 0 for fresh chains"
t=2023-08-23T09:32:29+0000 lvl=crit msg="Application failed"   message="L2 block time (2) is larger than L1 block time (0)"

```

**To Reproduce**
1. Follow the getting started guide https://stack.optimism.io/docs/build/getting-started/
2. Run the `go run cmd/main.go genesis l2` command
3. See error

**System Specs:**
 - OS:  Ubuntu 20.04 LTS
 - Package Version (or commit hash): 1736e83558e34cc8b03009136a8ed27bcc09d656

---

I might be missing something.

Thanks!

**Comment by Aymen-Tirchi** [comment]
- I was having the same issue I removed the `numDeployConfirmations` from `getting-started.json` I got another issue which is : 
```
t=2023-08-23T12:29:29+0100 lvl=info msg="Deploy config" path=../packages/contracts-bedrock/deploy-config/getting-started.json
t=2023-08-23T12:29:29+0100 lvl=crit msg="Application failed" message="cannot unmarshal deploy config: json: unknown field \"controller\""
```
so I also removed `controller` and it works 
- to solve the `L2 block time (2) is larger than L1 block time (0)` issue
add this `"l1BlockTime": 12,` to your `getting-started.json`

**Comment by deanrubin** [comment]
I have the same issue as-well

**Comment by carletex** [comment]
Thanks all! <3

Working now after https://github.com/ethereum-optimism/optimism/pull/6991
