### ISSUE TITLE
Devnet setup instructions are out of date

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/optimism#6976]
**Describe the bug**

Following the instructions outlined in [Bedrock Local Devnet Setup](https://github.com/ethereum-optimism/optimism/blob/develop/specs/meta/devnet.md) fail to bring up the devnet.

**To Reproduce**
1. Go to [Bedrock Local Devnet Setup](https://github.com/ethereum-optimism/optimism/blob/develop/specs/meta/devnet.md) to follow instructions.
2. Start docker daemon
3. cd into `packages/bedrock-contracts`
4. run `pnpm i` followed by `pnpm build`
5. cd into root of monorepo
6. `make devnet-up`

**Expected behavior**

I'd expect the devnet to run successfully.

**Screenshots**

The failure logs:
```
[INFO|08-23-2023 10:41:20] Devnet starting
[INFO|08-23-2023 10:41:20] Generating L1 genesis.
[INFO|08-23-2023 10:41:20] Generating L1 genesis state
Traceback (most recent call last):
  File "/Users/soyboy/Desktop/optimism/./bedrock-devnet/main.py", line 9, in <module>
    main()
  File "/Users/soyboy/Desktop/optimism/./bedrock-devnet/main.py", line 5, in main
    devnet.main()
  File "/Users/soyboy/Desktop/optimism/bedrock-devnet/devnet/__init__.py", line 101, in main
    devnet_deploy(paths)
  File "/Users/soyboy/Desktop/optimism/bedrock-devnet/devnet/__init__.py", line 158, in devnet_deploy
    devnet_l1_genesis(paths)
  File "/Users/soyboy/Desktop/optimism/bedrock-devnet/devnet/__init__.py", line 131, in devnet_l1_genesis
    geth = subprocess.Popen([
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geth'
make: *** [devnet-up] Error 1
soyboy@soyboys-MacBook-Air optimism %
```

**System Specs:**
 - OS: macOS Ventura Version 13.4
 - Package Version (or commit hash): `ba1a5942af9ad0313f7f3e87df757d048f7234f0`

**Additional context**

There are additional requirements/dependencies in the Makefile that I believe need to be run first:

```
make install-geth
make cannon-prestate
make devnet-allocs
```

cc @Chomtana @opfocus please feel free to share any additional context you both have

**Comment by opfocus** [comment]
> make install-geth

I've located the downloaded location of geth, in the go/bin directory. I'm wondering if using geth smoothly would be possible without setting up the geth environment variables.

**Comment by opfocus** [comment]
> **Describe the bug**
> 
> Following the instructions outlined in [Bedrock Local Devnet Setup](https://github.com/ethereum-optimism/optimism/blob/develop/specs/meta/devnet.md) fail to bring up the devnet.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to [Bedrock Local Devnet Setup](https://github.com/ethereum-optimism/optimism/blob/develop/specs/meta/devnet.md) to follow instructions.
> 2. Start docker daemon
> 3. cd into `packages/bedrock-contracts`
> 4. run `pnpm i` followed by `pnpm build`
> 5. cd into root of monorepo
> 6. `make devnet-up`
> 
> **Expected behavior**
> 
> I'd expect the devnet to run successfully.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> The failure logs:
> 
> ```
> [INFO|08-23-2023 10:41:20] Devnet starting
> [INFO|08-23-2023 10:41:20] Generating L1 genesis.
> [INFO|08-23-2023 10:41:20] Generating L1 genesis state
> Traceback (most recent call last):
>   File "/Users/soyboy/Desktop/optimism/./bedrock-devnet/main.py", line 9, in <module>
>     main()
>   File "/Users/soyboy/Desktop/optimism/./bedrock-devnet/main.py", line 5, in main
>     devnet.main()
>   File "/Users/soyboy/Desktop/optimism/bedrock-devnet/devnet/__init__.py", line 101, in main
>     devnet_deploy(paths)
>   File "/Users/soyboy/Desktop/optimism/bedrock-devnet/devnet/__init__.py", line 158, in devnet_deploy
>     devnet_l1_genesis(paths)
>   File "/Users/soyboy/Desktop/optimism/bedrock-devnet/devnet/__init__.py", line 131, in devnet_l1_genesis
>     geth = subprocess.Popen([
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'geth'
> make: *** [devnet-up] Error 1
> soyboy@soyboys-MacBook-Air optimism %
> ```
> 
> **System Specs:**
> 
> * OS: macOS Ventura Version 13.4
> * Package Version (or commit hash): `ba1a5942af9ad0313f7f3e87df757d048f7234f0`
> 
> **Additional context**
> 
> There are additional requirements/dependencies in the Makefile that I believe need to be run first:
> 
> ```
> make install-geth
> make cannon-prestate
> make devnet-allocs
> ```
> 
> cc @Chomtana @opfocus please feel free to share any additional context you both have

I ran it on a fresh Ubuntu 22.04 installation and observed the following points:

- Software Installation Needed: `Go, Node.js, Pnpm, Foundry, Make, Docker, Docker Compose`.

- After installing `geth` with` make install-geth`, it appears that I still need to add the path to the environment variables.

- The command `make devnet-allocs` can be replaced with` make devnet-up`.

- There's a typo in the command "`cd into packages/bedrock-contracts`." `It should be "cd into packages/contracts-bedrock.`"

**Comment by tynes** [comment]
We should replace the hardhat task with a `cast send --value ... --private-key $PORTAL_PROXY` command. The hh task doesn't exist anymore

**Comment by tynes** [comment]
There is also no `.dotenv` anymore and there is also an http server at `localhost:8080` that serves the L1 contract addresses at `/addresses.json`

**Comment by upnodedev** [comment]
Hi @sbvegan @tynes 

We have made a pull request for this https://github.com/ethereum-optimism/optimism/pull/7443

Our script will automatically execute `make install-geth` to install geth if it isn't exists

And we have tested that it is working after implementing this
