### ISSUE TITLE
Unable to run OP-Node:  failed to fetch runtime config data

### ISSUE THREAD

**Issue by Abhijaypaliwal** [ethereum-optimism/optimism#7000]
I was trying to run Optimism L2 while L1 as local anvil chain. However during the setup of OP-Node, I am getting following error: 
![image](https://github.com/ethereum-optimism/optimism/assets/138877287/3372a0ed-aa28-461a-bcf9-8eafb9967da0)
Can anyone help me solve the error?

**Comment by opfocus** [comment]
> I was trying to run Optimism L2 while L1 as local anvil chain. However during the setup of OP-Node, I am getting following error: ![image](https://user-images.githubusercontent.com/138877287/262891764-3372a0ed-aa28-461a-bcf9-8eafb9967da0.png) Can anyone help me solve the error?

What is your L1 data layer?

**Comment by Abhijaypaliwal** [comment]
> > I was trying to run Optimism L2 while L1 as local anvil chain. However during the setup of OP-Node, I am getting following error: ![image](https://user-images.githubusercontent.com/138877287/262891764-3372a0ed-aa28-461a-bcf9-8eafb9967da0.png) Can anyone help me solve the error?
> 
> What is your L1 data layer?

I am using anvil as L1

**Comment by opfocus** [comment]
> > > I was trying to run Optimism L2 while L1 as local anvil chain. However during the setup of OP-Node, I am getting following error: ![image](https://user-images.githubusercontent.com/138877287/262891764-3372a0ed-aa28-461a-bcf9-8eafb9967da0.png) Can anyone help me solve the error?
> > 
> > 
> > What is your L1 data layer?
> 
> I am using anvil as L1

This is typically due to an unsupported L1 data layer. I'm not sure how to support it. However, you can easily verify this: replacing L1RPC with a public Goerli RPC will not cause this issue."

**Comment by mikhail-khalizev** [comment]
I will assume that there was a timeout for a request to L1.

**Comment by tynes** [comment]
You need to have the smart contracts deployed to the L1. Unfortunately, anvil does not work with `op-node` due to some issues with its RPC responses.

**Comment by DavidCoder88** [comment]
same error,but I am using Sepolia as L1, following show you my error:
ubuntu@ip-172-31-42-83:~/op/optimism/op-node$ ./bin/op-node   --l2=http://localhost:8521   --l2.jwt-secret=./jwt.txt   --sequencer.enabled   --sequencer.l1-confs=5   --verifier.l1-confs=4   --rollup.config=./rollup.json   --rpc.addr=0.0.0.0   --rpc.port=8517   --p2p.disable   --rpc.enable-admin   --p2p.sequencer.key=$GS_SEQUENCER_PRIVATE_KEY   --l1=$L1_RPC_URL   --l1.rpckind=$L1_RPC_KIND

INFO [05-17|05:53:20.796] Not opted in to ProtocolVersions signal loading, disabling ProtocolVersions contract now.
INFO [05-17|05:53:20.797] No persisted sequencer state loaded
INFO [05-17|05:53:20.797] Rollup Config                            l2_chain_id=42069 l2_network="unknown L2" l1_chain_id=11,155,111 l1_network=sepolia l2_start_time=1,715,343,840 l2_block_hash=0x3ad88f3aeebe94efe2fa31fee3f0b7cb5af881fc9a49ee6354f7739e11088208 l2_block_number=0 l1_block_hash=0xa6d527fb4c8dc2ad217497252a09e9d80290357639450e0f37078adddcb7d492 l1_block_number=5,874,244 regolith_time="@ genesis" canyon_time="@ genesis" delta_time="(not configured)" ecotone_time="(not configured)" fjord_time="(not configured)" interop_time="(not configured)"
INFO [05-17|05:53:20.797] Initializing rollup node                 version=v0.0.0-a06cae81-1705510057
WARN [05-17|05:53:20.918] No beacon endpoint configured. Configuration is mandatory for the Ecotone upgrade
ERROR[05-17|05:53:21.258] failed to fetch runtime config data      err="failed to fetch unsafe block signing address from system config: failed to verify retrieved proof against state root: failed to verify storage value 0 with key 0x65a7ed542fb37fe237fdfbdd70b31598523fe5b32879e307bae27a0bd9581c08 (path 31a88f3936348d602f3078126bdcd162c575cb17fb9bbfe2dab00b167bd295c3) in storage trie 0x0000000000000000000000000000000000000000000000000000000000000000: proof node 0 (hash 0000000000000000000000000000000000000000000000000000000000000000) missing"

**Comment by opfocus** [comment]
Maybe you can try changing the provider of L1RPC

**Comment by tynes** [comment]
Anvil doesn't support `op-node`
