### ISSUE TITLE
Add L1 Proxy Contract with ability to pause during upgrade

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/optimism#707]
**Is your feature request related to a problem? Please describe.**
We need to pause all interactions with our L1 contracts during an upgrade. If we don't then we don't know what crazy interactions might happen if someone sent a transaction mid deploy. 

**Describe the solution you'd like**
Implement a ChugSplashProxy which, before executing any transactions, checks to see if a deployment is currently under-way. This should be called in the fallback function before any interactions with the contract. Also, to enable folks to `eth_call` even during an upgrade, we can use the following logic:

```
function() {
  if (isUpgradeHappening()) {
    require(msg.sender == 0, "Only eth_call is allowed during an upgrade!");
  }
}
```

**Blockers**
https://github.com/ethereum-optimism/optimism/issues/703

**Comment by tynes** [comment]
You can set any `from` address during `eth_call` so the function listed above is not sufficient.

Would be nice to have `IS_STATIC` - https://eips.ethereum.org/EIPS/eip-2970
