### ISSUE TITLE
"Set L1Block Values" transaction is not eth-compatible

### ISSUE THREAD

**Issue by envestcc** [ethereum-optimism/optimism#7072]
**Describe the bug**
`Set L1Block Values` transaction is not eth-compatible

**To Reproduce**
1. calling `eth_getTransactionByHash` for transaction `0x2c23a2e9f4766906572f0c2446fdf78724f898e1f6c261e5cf1acc64d4de1ad8` by [ethclient v1.12.2](https://github.com/ethereum/go-ethereum/tree/v1.12.2/ethclient) 
2. it returns `transaction type not supported`

```go
package main

import (
	"context"
	"math/big"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/stretchr/testify/require"
)

func TestOptimismRead(t *testing.T) {
	r := require.New(t)
	cli, err := ethclient.Dial("https://mainnet.optimism.io")
	r.NoError(err)
	tx, isPending, err := cli.TransactionByHash(context.Background(), common.HexToHash("0x2c23a2e9f4766906572f0c2446fdf78724f898e1f6c261e5cf1acc64d4de1ad8"))
	r.NoError(err)
	r.False(isPending)
	r.NotNil(tx)
	t.Logf("%+v", tx)
}
```

**Expected behavior**
should return transaction infomation

**Screenshots**

**System Specs:**
 - OS:
 - Package Version (or commit hash):

**Additional context**

**Comment by tynes** [comment]
You need to be using `op-geth` as a library and not `geth`. The deserialization of the new tx type is not supported by `geth`
