### ISSUE TITLE
Can not start new node with /usr/local/bin/op-node  command

### ISSUE THREAD

**Issue by xt-com** [ethereum-optimism/optimism#7076]
Logs for opt_geth and opt_node are abnormal.

ssh root@172.17.0.8
cd /opt

root@172.17.0.8:/opt# /usr/local/bin/geth version
Geth
Version: 0.1.0-unstable
Git Commit: b9c6d36ae9b84ef82430311ddf03dc16f9be505b
Upstream Version: 1.12.0-stable
Architecture: amd64
Go Version: go1.20.7
Operating System: linux
GOPATH=
GOROOT=

run command :

```
geth --datadir /opt \
--ws \
--ws.port=8546 \
--ws.addr=0.0.0.0 \
--ws.origins='*'  \
--ws.api=debug,eth,txpool,net,engine   \
--http.api=web3,debug,eth,txpool,net,engine \
--http \
--http.port=8545 \
--http.addr=0.0.0.0 \
--http.vhosts="\*" \
--http.corsdomain="\*" \
--authrpc.addr=0.0.0.0 \
--authrpc.jwtsecret=/opt/jwt.txt \
--authrpc.port=8551 \
--authrpc.vhosts="\*" \
--verbosity=3 \
--rollup.disabletxpoolgossip=true \
--rollup.sequencerhttp=https://mainnet-sequencer.optimism.io/ \
--nodiscover \
--syncmode=full \
--maxpeers=0
```

log-info:

INFO [08-31|10:27:47.450] Starting Geth on Ethereum mainnet...
INFO [08-31|10:27:47.451] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [08-31|10:27:47.456] Maximum peer count                       ETH=0 LES=0 total=0
INFO [08-31|10:27:47.458] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-31|10:27:47.464] Set global gas cap                       cap=50,000,000
INFO [08-31|10:27:47.465] Initializing the KZG library             backend=gokzg
INFO [08-31|10:27:47.517] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
INFO [08-31|10:27:47.518] Using leveldb as the backing database
INFO [08-31|10:27:47.518] Allocated cache and file handles         database=/opt/geth/chaindata cache=2.00GiB handles=524,288
INFO [08-31|10:27:47.546] Using LevelDB as the backing database
INFO [08-31|10:27:47.548] Opened ancient database                  database=/opt/geth/chaindata/ancient/chain readonly=false
INFO [08-31|10:27:47.766]
INFO [08-31|10:27:47.766] ---------------------------------------------------------------------------------------------------------------------------------------------------------
INFO [08-31|10:27:47.766] Chain ID:  1 (mainnet)
INFO [08-31|10:27:47.766] Consensus: Beacon (proof-of-stake), merged from Ethash (proof-of-work)
INFO [08-31|10:27:47.766]
INFO [08-31|10:27:47.766] Pre-Merge hard forks (block based):
INFO [08-31|10:27:47.766]  - Homestead:                   #1150000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/homestead.md)
INFO [08-31|10:27:47.766]  - DAO Fork:                    #1920000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/dao-fork.md)
INFO [08-31|10:27:47.766]  - Tangerine Whistle (EIP 150): #2463000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/tangerine-whistle.md)
INFO [08-31|10:27:47.766]  - Spurious Dragon/1 (EIP 155): #2675000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
INFO [08-31|10:27:47.766]  - Spurious Dragon/2 (EIP 158): #2675000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
INFO [08-31|10:27:47.766]  - Byzantium:                   #4370000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/byzantium.md)
INFO [08-31|10:27:47.766]  - Constantinople:              #7280000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/constantinople.md)
INFO [08-31|10:27:47.766]  - Petersburg:                  #7280000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/petersburg.md)
INFO [08-31|10:27:47.766]  - Istanbul:                    #9069000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/istanbul.md)
INFO [08-31|10:27:47.766]  - Muir Glacier:                #9200000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/muir-glacier.md)
INFO [08-31|10:27:47.766]  - Berlin:                      #12244000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/berlin.md)
INFO [08-31|10:27:47.766]  - London:                      #12965000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/london.md)
INFO [08-31|10:27:47.766]  - Arrow Glacier:               #13773000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/arrow-glacier.md)
INFO [08-31|10:27:47.767]  - Gray Glacier:                #15050000 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/gray-glacier.md)
INFO [08-31|10:27:47.767]
INFO [08-31|10:27:47.767] Merge configured:
INFO [08-31|10:27:47.767]  - Hard-fork specification:    https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md
INFO [08-31|10:27:47.767]  - Network known to be merged: true
INFO [08-31|10:27:47.767]  - Total terminal difficulty:  58750000000000000000000
INFO [08-31|10:27:47.767]
INFO [08-31|10:27:47.767] Post-Merge hard forks (timestamp based):
INFO [08-31|10:27:47.767]  - Shanghai:                    @1681338455 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md)
INFO [08-31|10:27:47.767]
INFO [08-31|10:27:47.767] ---------------------------------------------------------------------------------------------------------------------------------------------------------
INFO [08-31|10:27:47.767]
INFO [08-31|10:27:47.767] Loaded most recent local block           number=0 hash=d4e567..cb8fa3 td=17,179,869,184 age=54y5mo1w
WARN [08-31|10:27:47.768] Loaded snapshot journal                  diffs=missing
INFO [08-31|10:27:47.768] Initialising Ethereum protocol           network=1 dbversion=8
INFO [08-31|10:27:47.769] Loaded local transaction journal         transactions=0 dropped=0
INFO [08-31|10:27:47.769] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-31|10:27:47.770] Chain post-merge, sync via beacon client
INFO [08-31|10:27:47.770] Gasprice oracle is ignoring threshold set threshold=2
WARN [08-31|10:27:47.770] Unclean shutdown detected                booted=2023-08-30T06:11:28+0000 age=1d4h16m
WARN [08-31|10:27:47.770] Unclean shutdown detected                booted=2023-08-31T02:29:52+0000 age=7h57m55s
WARN [08-31|10:27:47.770] Unclean shutdown detected                booted=2023-08-31T03:02:40+0000 age=7h25m7s
WARN [08-31|10:27:47.770] Unclean shutdown detected                booted=2023-08-31T03:14:24+0000 age=7h13m23s
WARN [08-31|10:27:47.770] Unclean shutdown detected                booted=2023-08-31T03:28:27+0000 age=6h59m20s
WARN [08-31|10:27:47.770] Unclean shutdown detected                booted=2023-08-31T07:52:16+0000 age=2h35m31s
WARN [08-31|10:27:47.770] Unclean shutdown detected                booted=2023-08-31T08:43:50+0000 age=1h43m57s
WARN [08-31|10:27:47.770] Unclean shutdown detected                booted=2023-08-31T09:42:10+0000 age=45m37s
WARN [08-31|10:27:47.770] Unclean shutdown detected                booted=2023-08-31T10:24:28+0000 age=3m19s
WARN [08-31|10:27:47.770] Engine API enabled                       protocol=eth
INFO [08-31|10:27:47.771] Starting peer-to-peer node               instance=Geth/v0.1.0-unstable-b9c6d36a/linux-amd64/go1.20.7
INFO [08-31|10:27:47.959] IPC endpoint opened                      url=/opt/geth.ipc
INFO [08-31|10:27:47.959] New local node record                    seq=1,692,716,788,856 id=16db3bc6c2f04bbb ip=127.0.0.1 udp=0 tcp=30303
INFO [08-31|10:27:47.960] Started P2P networking                   self="enode://9ef67558b011d454ccbd8b04365a2295036e59fae88e8253cf0fe7872a1b5ed68f804a50191f81e32b0ede3db3464926996525a969a82ec03cbedcb7667b058e@127.0.0.1:30303?discport=0"
INFO [08-31|10:27:47.960] Loaded JWT secret file                   path=/opt/jwt.txt crc32=0x327f1d11
INFO [08-31|10:27:47.960] HTTP server started                      endpoint=[::]:8545 auth=false prefix= cors=* vhosts=*
INFO [08-31|10:27:47.960] WebSocket enabled                        url=ws://[::]:8546
INFO [08-31|10:27:47.960] WebSocket enabled                        url=ws://[::]:8551
INFO [08-31|10:27:47.960] HTTP server started                      endpoint=[::]:8551 auth=true  prefix= cors=localhost vhosts=*
WARN [08-31|10:28:22.771] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [08-31|10:33:22.823] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [08-31|10:38:22.859] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [08-31|10:43:22.901] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [08-31|10:48:22.935] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [08-31|10:53:22.976] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [08-31|10:58:23.013] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [08-31|11:03:23.052] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [08-31|11:08:23.089] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [08-31|11:13:23.121] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
WARN [08-31|11:18:23.161] Post-merge network, but no beacon client seen. Please launch one to follow the chain!

--------------------------------------------

[op_node]

run command :

	op-node --l1=http://172.17.0.8:8545  --l2=http://172.17.0.8:8551 --network=mainnet --l2.jwt-secret=/opt/jwt.txt --rpc.addr=0.0.0.0 --rpc.port=8545 

log Info:

t=2023-08-31T16:33:33+0000 lvl=info msg="Initializing Rollup Node"
INFO [08-31|16:33:33.926] Rollup Config                            l2_chain_id=10 l2_network=mainnet l1_chain_id=1 l1_network=mainnet l2_start_time=1,686,068,903 l2_block_hash=0xdbf6a80fef073de06add9b0d14026d6e5a86c85f6d102c36d3d8e9cf89c2afd3 l2_block_number=105,235,063 l1_block_hash=0x438335a20d98863a4c0c97999eb2481921ccd28553eac6f913af7c12aec04108 l1_block_number=17,422,590 regolith_time="@ genesis"
ERROR[08-31|16:33:33.968] Error initializing the rollup node       err="failed to fetch header by num 17422590: not found"
ERROR[08-31|16:33:33.970] Unable to create the rollup node         error="failed to fetch header by num 17422590: not found"
CRIT [08-31|16:33:33.970] Application failed                       message="failed to fetch header by num 17422590: not found"

**System Specs:**
 - OS: ubuntu 20.04

Is there any information that can help me? pls.

**Comment by opfocus** [comment]
Have you download data?   This is typically because no data was found under the path /opt in geth --datadir.

**Comment by xt-com** [comment]
> Have you download data? This is typically because no data was found under the path /opt in geth --datadir.

Thank you, I downloaded a snapshot file from  https://community.optimism.io/docs/developers/build/run-a-node/#initializing-op-geth  (https://datadirs.optimism.io/mainnet-bedrock.tar.zst),  decompressed it, and run geth  again, the log shows that it is still abnormal.
Log information:

INFO [09-03|15:49:17.835] Starting Geth on Ethereum mainnet...
INFO [09-03|15:49:17.835] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [09-03|15:49:17.842] Maximum peer count                       ETH=0 LES=0 total=0
INFO [09-03|15:49:17.843] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [09-03|15:49:17.850] Set global gas cap                       cap=50,000,000
INFO [09-03|15:49:17.851] Initializing the KZG library             backend=gokzg
INFO [09-03|15:49:17.931] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
INFO [09-03|15:49:18.092] Using pebble as the backing database
INFO [09-03|15:49:18.093] Allocated cache and file handles         database=/opt/geth/chaindata cache=2.00GiB handles=524,288
Fatal: Failed to register the Ethereum service: pebble: files 1186099 and 1186099 collided on sort keys
Fatal: Failed to register the Ethereum service: pebble: files 1186099 and 1186099 collided on sort keys
INFO [09-03|15:49:19.528] Starting Geth on Ethereum mainnet...
INFO [09-03|15:49:19.528] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [09-03|15:49:19.534] Maximum peer count                       ETH=0 LES=0 total=0
INFO [09-03|15:49:19.534] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [09-03|15:49:19.540] Set global gas cap                       cap=50,000,000
INFO [09-03|15:49:19.540] Initializing the KZG library             backend=gokzg
INFO [09-03|15:49:19.587] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
INFO [09-03|15:49:19.744] Using pebble as the backing database
INFO [09-03|15:49:19.745] Allocated cache and file handles         database=/opt/geth/chaindata cache=2.00GiB handles=524,288
Fatal: Failed to register the Ethereum service: pebble: files 1186099 and 1186099 collided on sort keys
Fatal: Failed to register the Ethereum service: pebble: files 1186099 and 1186099 collided on sort keys
INFO [09-03|15:49:21.176] Starting Geth on Ethereum mainnet...
INFO [09-03|15:49:21.176] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [09-03|15:49:21.182] Maximum peer count                       ETH=0 LES=0 total=0
INFO [09-03|15:49:21.182] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [09-03|15:49:21.187] Set global gas cap                       cap=50,000,000
INFO [09-03|15:49:21.188] Initializing the KZG library             backend=gokzg
INFO [09-03|15:49:21.234] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
INFO [09-03|15:49:21.488] Using pebble as the backing database
INFO [09-03|15:49:21.488] Allocated cache and file handles         database=/opt/geth/chaindata cache=2.00GiB handles=524,288
Fatal: Failed to register the Ethereum service: pebble: files 1186099 and 1186099 collided on sort keys
Fatal: Failed to register the Ethereum service: pebble: files 1186099 and 1186099 collided on sort keys
INFO [09-03|15:49:23.205] Starting Geth on Ethereum mainnet...
INFO [09-03|15:49:23.206] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [09-03|15:49:23.211] Maximum peer count                       ETH=0 LES=0 total=0
INFO [09-03|15:49:23.212] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [09-03|15:49:23.217] Set global gas cap                       cap=50,000,000
INFO [09-03|15:49:23.218] Initializing the KZG library             backend=gokzg
INFO [09-03|15:49:23.265] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
INFO [09-03|15:49:23.433] Using pebble as the backing database
INFO [09-03|15:49:23.433] Allocated cache and file handles         database=/opt/geth/chaindata cache=2.00GiB handles=524,288
Fatal: Failed to register the Ethereum service: pebble: files 1186099 and 1186099 collided on sort keys
Fatal: Failed to register the Ethereum service: pebble: files 1186099 and 1186099 collided on sort keys

**Comment by opfocus** [comment]
-l1=http://172.17.0.8:8545  maybe because this config.  what is your L1 data layer?    I think when you change to a public goerli or eht-mainnet RPC ,it will work well

**Comment by tynes** [comment]
This is better to ask in https://github.com/ethereum-optimism/developers/discussions
