### ISSUE TITLE
Add script which deploys our contract to L1 & L2 as needed using ChugSplash

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/optimism#708]
**Is your feature request related to a problem? Please describe.**
With all of this chugsplash infrastructure, we need a script to actually automate a deployment. Additionally this script must be used in our CI in place of the current `deployer`.

**Describe the solution you'd like**
Create a script which, using the smart contract work & off-chain scripts that were developed in: https://github.com/ethereum-optimism/optimism/issues/696 https://github.com/ethereum-optimism/optimism/issues/697 https://github.com/ethereum-optimism/optimism/issues/703 https://github.com/ethereum-optimism/optimism/issues/706 and https://github.com/ethereum-optimism/optimism/issues/707 performs a full chugsplash deployment.

After this has been implemented and tested in a 1-off environment, this should be hooked up to our CI and replace our current `deployer`! In order for this to be possible, we will need to:
1. Remove constructors from our contracts as all environment variables will be set in the deployment step. Additionally, remove our address manager as it will no longer be used to resolve contract addresses.
2. Write a chugsplash deploy template for L1 and L2 contracts.
3. Update the env of our `deployer` image & make sure it is now using the new deployment mechanism by updating `yarn deploy`

All integration tests should still pass even though we are now using a new deployment mechanism!

**Blockers**
https://github.com/ethereum-optimism/optimism/issues/696 https://github.com/ethereum-optimism/optimism/issues/697 https://github.com/ethereum-optimism/optimism/issues/703 https://github.com/ethereum-optimism/optimism/issues/706 and https://github.com/ethereum-optimism/optimism/issues/707

**Comment by annieke** [comment]
## Most minimal 
- Take a json contract file and turn it into a series of inputs to a smart contract
- A script/service which will making transactions and sending them to the chain
- Open Qs: How do we want to handle errors? We can parallelize sending transactions that don't depend on each other (order of actions doesn't matter! yay)
- Error cases: two clients trying to upgrade at the same time, avoid conflicts by randomizing the ordering and handling how clashing is still handled

## Notes
- deploy.ts (https://github.com/ethereum-optimism/optimism/blob/eef1df4d63fd1b483beda63293ea1746861c3e2a/packages/contracts/bin/deploy.ts) is for layer 1 but we want to get this for layer 2
- we should get everything working on layer 2 first and then port back to layer 1, so this ticket should just be scoped to l2 for now
- Next steps: thinking about the whole process of automating all of this; end goal is that we merge to master and all upgrades just happen (continuous contract deployment)

### Background
- 3 types of contracts on l2: systems (must haves, eg execution manager, state manager, etc), predeployed contracts (useful but not CRUCIAL, contract wallets, messaging contracts), user contracts 
- execution manager really only needs to live on l2 until fraud proof, which requires a copy on l1 to verify execution
- l2 contracts based on what we need: to prove correctness of executions - we need l2 smart contracts to match what an l1 smart contract would have done; blurry line of what should be executed by the sequencer: maybe everything should be written in go

### L1 contracts 
- ideally: execution manager doesn't exist on l1; current version only gets deployed when there's a fraud proof
- ctc, scc, fraud verifier are the only technically necessary contracts for l1; x-domain messaging contracts COULD be deployed by someone else 


## Action items
- get https://github.com/ethereum-optimism/optimism/pull/749 running locally and see if can add tests
- also need https://github.com/ethereum-optimism/optimism/pull/755 before working
- spec out what exactly we want with @smartcontracts

**Comment by smartcontracts** [comment]
Closing this, we'll be reworking the ChugSplash project plan
