### ISSUE TITLE
sequencer broadcast failed

### ISSUE THREAD

**Issue by xuan-io** [ethereum-optimism/optimism#7083]
https://github.com/ethereum-optimism/optimism/blob/develop/op-node/p2p/gossip.go#L295
![image](https://github.com/ethereum-optimism/optimism/assets/6736516/a908e39a-c1fa-4ed4-80cc-e75bebae79b3)

The verification of p2p broadcast will prevent the sequencer’s block from being broadcast to other nodes.
Why add such a check?

**Comment by xuan-io** [comment]
When l1 is abnormal and then recovered, it will cause The verification of p2p broadcast will prevent the sequencer’s block from being broadcast to other nodes.

**Comment by sbvegan** [comment]
I got some information from @ajsutton about this behavior.

>That's expected, if you gossiped invalid messages other nodes would ignore it anyway and they'd downscore and potentially disconnect you. P2P alt sync will kick in to backfill any blocks that are missed because they weren't published on time once a more recent block is received.
