### ISSUE TITLE
Implement strategy to distribute contract addresses and ABIs (artifacts) over npm

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/optimism#709]
**Is your feature request related to a problem? Please describe.**
We need a place to store the contract names (both L1 and L2), addresses, deployment configs, and ABIs for all of our environments. 

**Describe the solution you'd like**
Publish the contract information for all of our chains to npm  (similar to this: https://github.com/graphprotocol/common-ts/blob/master/packages/common-ts/src/contracts/index.ts ) and hook it up to our deployments so that whenever there is a new deployment we are updating those addresses / that information.

Most of the information should be retrievable from L1 by reading events emitted by the deployment. For instance, the version information, contract names, and addresses are all easily recoverable from the `DeploymentManager`. There will be some information that is easier to store off-chain like the ABI and Solidity source.

It is not a requirement that at first we actually recover the information from L1, but it should be possible to do so.

**Completion requirements**
- also generate markdown as we already do with addresses
- abi accessible at `@eth-optimism/contracts/abis/blahblah.json`
- solidity accessible at `@eth-optimism/contracts/sol/whatevr.sol`
- `connectContracts` accessible at `@eth-optimism/contracts`
- info should be able to be generated by L1, but we can be lazy and store it off-chain as well for easy access.

**Blockers**
https://github.com/ethereum-optimism/optimism/issues/708

**Comment by gakonst** [comment]
I think the artifacts under https://github.com/ethereum-optimism/optimism/tree/master/packages/contracts/deployments already provide that. May be worth exposing them in an easier place.

**Comment by snario** [comment]
I think @karlfloersch is partially alluding to how it ought to work post-upgradability deployment changes are in (#708)

**Comment by smartcontracts** [comment]
Going to close this out. It's a very vague issue and we already sort of have this for the existing deployment. We can open another issue if we ever decide to go back and take a second look at our deployment + distribution process.
