### ISSUE TITLE
Add auto-publish for release candidate branches

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/optimism#710]
**Is your feature request related to a problem? Please describe.**
We currently do not have automation around publishing release candidate versions to docker hub. This significantly slows down our ability to iterate on release candidates. 

**Describe the solution you'd like**
Add some basic automation around publishing `rc` versions of our releases. I'm open to specific implementation details here, or particular branching patterns that folks suggest. There are also probably standard ways to handle release candidates when using changesets that we are currently just not implementing. Therefore to complete this ticket we should do something like:

- [ ] Look into how best to handle publishing release candidates considering our monorepo setup -- this might also inform our branching patterns
- [ ] Update our CI so that we publish release candidates for all of our packages to dockerhub / npm.
- [ ] Push new release candidate branches which follow this format & ensure that images are correctly created based on this new release & branching structure. One example branch is: https://github.com/ethereum-optimism/optimism/tree/v0.3.0-rc

**Additional context**
Some extra notes that I see are:
- We release versions for all packages independently. Do we want to: a) increment all packages by a major version bump whenever we ship a major release, or b) create a tagged release of the whole monorepo (not just a single package) which represents the `vX.X.0` version of the whole software suite. I don't know!

**Comment by smartcontracts** [comment]
After chatting with @snario I think we can close this because we have Canary releases that we can create for release candidate branches.
