### ISSUE TITLE
Cannot build op-node Docker Image from Dockerfile

### ISSUE THREAD

**Issue by nitantchhajed** [ethereum-optimism/optimism#7153]
getting this error while building docker image of op-node, I've checked that i have go.mod, go.sum and other files in my directory, but is is still showing this error -

![image](https://github.com/ethereum-optimism/optimism/assets/96972634/d34d009c-5044-4dcd-bc33-e1a99972c4ae)

**Comment by tynes** [comment]
The docker image must be built from the root of the repo, not from withing `op-node` directory
