### ISSUE TITLE
op-service: standard admin RPC building block

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#7417]
Standard RPC methods to support:
- `admin_setLogLevel` (already supported in op-node)
- maybe metrics related endpoint

The admin RPC namespace should be extensible, i.e. services may add additional admin RPC endpoints.

**Comment by seungjulee** [comment]
@protolambda I've created a PR that solves this problem. Please let me know if this is different from the structure you were imagining. https://github.com/ethereum-optimism/optimism/pull/7482
