### ISSUE TITLE
Implement Span Batches

### ISSUE THREAD

**Issue by trianglesphere** [ethereum-optimism/optimism#7454]
Implementation and spec completed. [Notion Doc](https://www.notion.so/oplabs/Low-cost-Bedrock-for-op-chains-Span-Batches-b8c929833fe94862afbab981ed25244f). See the monorepo PRs

* https://github.com/ethereum-optimism/optimism/pull/7291
* https://github.com/ethereum-optimism/optimism/pull/7290
* https://github.com/ethereum-optimism/optimism/pull/7289
* https://github.com/ethereum-optimism/optimism/pull/7288
* https://github.com/ethereum-optimism/optimism/pull/7287
* https://github.com/ethereum-optimism/optimism/pull/7621
* [x] complete follow-ups from encoding/typing PR: https://github.com/ethereum-optimism/optimism/pull/7288#issuecomment-1756153736
    * https://github.com/ethereum-optimism/optimism/pull/7752
* [x] complete follow-ups from derivation PR https://github.com/ethereum-optimism/optimism/pull/7289#issuecomment-1756315597
    * https://github.com/ethereum-optimism/optimism/pull/7751
* https://github.com/ethereum-optimism/optimism/pull/7828
* https://github.com/ethereum-optimism/optimism/pull/7953
* https://github.com/ethereum-optimism/optimism/pull/7813
* https://github.com/ethereum-optimism/optimism/pull/7867
* https://github.com/ethereum-optimism/optimism/pull/8047 (e2e span-batch test parametrization cleanup)
* https://github.com/ethereum-optimism/optimism/pull/7259

**Comment by adelowo** [comment]
@trianglesphere the docs doesn't seem to be publicly available ( if that is your intention )

**Comment by trianglesphere** [comment]
> @trianglesphere the docs doesn't seem to be publicly available ( if that is your intention )

Yea, those are internal tracking docs. See https://github.com/ethereum-optimism/optimism/blob/develop/specs/span-batches.md for the latest specs on span batches.

**Comment by pcw109550** [comment]
@trianglesphere we have opened two followup PRs:
- encoding/typing PR follow-up: https://github.com/ethereum-optimism/optimism/pull/7752
- derivation PR follow-up(span batch limit): https://github.com/ethereum-optimism/optimism/pull/7751

All other diffs for derivation PR follow-up is at https://github.com/ethereum-optimism/optimism/pull/7621

**Comment by pcw109550** [comment]
Also, e2e tests(https://github.com/ethereum-optimism/optimism/pull/7291) PR got stale and closed. Please reopen ‎😃.

**Comment by pcw109550** [comment]
@trianglesphere we have opened another follow up PR:
- span-batch HF-activation specs: https://github.com/ethereum-optimism/optimism/pull/7813

**Comment by taempark** [comment]
Think we also need to add #7828 for tracking purpose

**Comment by ImTei** [comment]
Just opened the new follow-up PR about span batch atomicity. https://github.com/ethereum-optimism/optimism/pull/7867

**Comment by ImTei** [comment]
opened PR for https://github.com/ethereum-optimism/optimism/issues/7853: https://github.com/ethereum-optimism/optimism/pull/7953

**Comment by mslipper** [comment]
Closing as complete!
