### ISSUE TITLE
Exception occurred in child process: [Errno 2] No such file or directory: 'cast'

### ISSUE THREAD

**Issue by sameplacewei** [ethereum-optimism/optimism#7516]
I clone the latest optimism code,run make devnet-up,the fellowing err occur:

> make[1]: enter path“/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism”
PYTHONPATH=./bedrock-devnet python3 ./bedrock-devnet/main.py --monorepo-dir=. --allocs
[INFO|10-02-2023 10:47:53] Generating L1 genesis state
==================================================
<devnet.Bunch object at 0x7f6c7e5d8eb0>
[INFO|10-02-2023 10:47:53] Trying 127.0.0.1:8545
[INFO|10-02-2023 10:47:53] Connected 127.0.0.1:8545
[INFO|10-02-2023 10:47:53] Waiting for RPC server at 127.0.0.1:8545
DEBUG[10-02|22:47:53.215] Served eth_chainId                       conn=127.0.0.1:48034 reqid=1 duration="439.605µs"
[INFO|10-02-2023 10:47:53] RPC server at 127.0.0.1:8545 ready
[INFO|10-02-2023 10:47:53] Fetch eth_accounts 127.0.0.1:8545
DEBUG[10-02|22:47:53.221] Served eth_accounts                      conn=127.0.0.1:48048 reqid=2 duration="42.992µs"
[INFO|10-02-2023 10:47:53] Deploying with 0xa56222cb89bfc647296ec74331b9b47aaf6b4fea
Traceback (most recent call last):
  File "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/./bedrock-devnet/main.py", line 9, in <module>
    main()
  File "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/./bedrock-devnet/main.py", line 5, in main
    devnet.main()
  File "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/bedrock-devnet/devnet/__init__.py", line 94, in main
    devnet_l1_genesis(paths)
  File "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/bedrock-devnet/devnet/__init__.py", line 166, in devnet_l1_genesis
    raise Exception(f"Exception occurred in child process: {err}")
Exception: Exception occurred in child process: [Errno 2] No such file or directory: 'cast'
make[1]: *** [Makefile:120：devnet-allocs] error 1
make[1]: leave path“/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism”
make: *** [Makefile:91：devnet-up] error 2

who can help me ,why?

**To Reproduce**
1. git clone https://github.com/ethereum-optimism/optimism.git
2. cd optimism
3. make devnet-up

**Expected behavior**
no errors.

**System Specs:**
 - OS:ubuntu20.04
 - python 3.9.18
 - optimism: 5e6b7f1edd1398858c3dcdcf250a977cd70d0cb6 (HEAD -> develop, origin/develop, origin/HEAD)

**Comment by Sabnock01** [comment]
This is because the `bedrock-devnet` [script](https://github.com/ethereum-optimism/optimism/blob/0025fff177d656fc14d64c174eef3b69a03413dc/bedrock-devnet/devnet/__init__.py#L116)  is running a series of `cast` commands. Do you have [Foundry](https://github.com/foundry-rs/foundry) installed?

**Comment by sameplacewei** [comment]
I am a beginner and installing for the first time, what should I do,or what to install first.

**Comment by Sabnock01** [comment]
Since `cast` is part of Foundry so the first thing you'd need to do is install it which you can find instructions for from the above link but specifically can be found [here](https://book.getfoundry.sh/getting-started/installation).

**Comment by sameplacewei** [comment]
Thanks ,I try again.

**Comment by sameplacewei** [comment]
I have installed Foundry,node.when i run make devnet-up,the fellowing err occur:

> INFO [10-04|19:41:40.796] Maximum peer count                       ETH=50 LES=0 total=50
INFO [10-04|19:41:40.797] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
DEBUG[10-04|19:41:40.797] FS scan times                            list="34.487µs" set=380ns diff="1.233µs"
WARN [10-04|19:41:40.798] Disable transaction unindexing for archive node 
DEBUG[10-04|19:41:40.799] Sanitizing Go's GC trigger               percent=100
INFO [10-04|19:41:40.799] Enabling recording of key preimages since archive mode is used 
INFO [10-04|19:41:40.799] Set global gas cap                       cap=50,000,000
Error: 
(code: -32000, message: nonce too low, data: None)
Traceback (most recent call last):
  File "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/./bedrock-devnet/main.py", line 9, in <module>
    main()
  File "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/./bedrock-devnet/main.py", line 5, in main
    devnet.main()
  File "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/bedrock-devnet/devnet/__init__.py", line 94, in main
    devnet_l1_genesis(paths)
  File "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/bedrock-devnet/devnet/__init__.py", line 166, in devnet_l1_genesis
    raise Exception(f"Exception occurred in child process: {err}")
Exception: Exception occurred in child process: Command '['cast', 'publish', '--rpc-url', 'http://127.0.0.1:8545', '0xf8a58085174876e800830186a08080b853604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf31ba02222222222222222222222222222222222222222222222222222222222222222a02222222222222222222222222222222222222222222222222222222222222222']' returned non-zero exit status 1.
make[1]: *** [Makefile:120：devnet-allocs] error 1
make[1]: leave path“/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism”
make: *** [Makefile:91：devnet-up] error 2

Is there anything else I need to do? I just want to set up a local test environment first

I followed this step([Running a local development environment](https://community.optimism.io/docs/developers/build/dev-node/)), but it seems that this is not suitable for beginners, is there any other suitable for beginners guide?

**Comment by Sabnock01** [comment]
Is
 
>  Exception: Exception occurred in child process: Command '['cast', 'publish', '--rpc-url', 'http://127.0.0.1:8545', '0xf8a58085174876e800830186a08080b853604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf31ba02222222222222222222222222222222222222222222222222222222222222222a02222222222222222222222222222222222222222222222222222222222222222']' returned non-zero exit status 1.

the only error you see?

**Comment by tynes** [comment]
This is certainly because you do not have `cast` in your `PATH`

**Comment by sameplacewei** [comment]
> Is
> 
> > Exception: Exception occurred in child process: Command '['cast', 'publish', '--rpc-url', 'http://127.0.0.1:8545', '0xf8a58085174876e800830186a08080b853604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf31ba02222222222222222222222222222222222222222222222222222222222222222a02222222222222222222222222222222222222222222222222222222222222222']' returned non-zero exit status 1.
> 
> the only error you see?

this is all the information I get

> PYTHONPATH=./bedrock-devnet python3 ./bedrock-devnet/main.py --monorepo-dir=. --allocs
[INFO|10-04-2023 07:41:40] Generating L1 genesis state
==================================================
<devnet.Bunch object at 0x7f59fb148f40>
[INFO|10-04-2023 07:41:40] Trying 127.0.0.1:8545
[INFO|10-04-2023 07:41:40] Connected 127.0.0.1:8545
[INFO|10-04-2023 07:41:40] Waiting for RPC server at 127.0.0.1:8545
[INFO|10-04-2023 07:41:40] RPC server at 127.0.0.1:8545 ready
[INFO|10-04-2023 07:41:40] Fetch eth_accounts 127.0.0.1:8545
[INFO|10-04-2023 07:41:40] Deploying with 0xa56222cb89bfc647296ec74331b9b47aaf6b4fea
INFO [10-04|19:41:40.791] Starting Geth in ephemeral dev mode... 
WARN [10-04|19:41:40.791] You are running Geth in --dev mode. Please note the following:

  1. This mode is only intended for fast, iterative development without assumptions on
     security or persistence.
  2. The database is created in memory unless specified otherwise. Therefore, shutting down
     your computer or losing power will wipe your entire block data and chain state for
     your dev environment.
  3. A random, pre-allocated developer account will be available and unlocked as
     eth.coinbase, which can be used for testing. The random dev account is temporary,
     stored on a ramdisk, and will be lost if your machine is restarted.
  4. Mining is enabled by default. However, the client will only seal blocks if transactions
     are pending in the mempool. The miner's minimum accepted gas price is 1.
  5. Networking is disabled; there is no listen-address, the maximum number of peers is set
     to 0, and discovery is disabled.
 

blockHash               0x279c2953f2082e254d5345ea7c48904f6afb1d66fbe062f5b90fe83349b73356
blockNumber             6
contractAddress         
cumulativeGasUsed       21000
effectiveGasPrice       3449445906
gasUsed                 21000
logs                    []
logsBloom               0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
root                    
status                  1
transactionHash         0x01ea91f03c2308123fb0a0c38438c13fde1e1b0bf1c32517e87dac4bccb64ef1
transactionIndex        0
type                    2
INFO [10-04|19:41:40.796] Maximum peer count                       ETH=50 LES=0 total=50
INFO [10-04|19:41:40.797] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
DEBUG[10-04|19:41:40.797] FS scan times                            list="34.487µs" set=380ns diff="1.233µs"
WARN [10-04|19:41:40.798] Disable transaction unindexing for archive node 
DEBUG[10-04|19:41:40.799] Sanitizing Go's GC trigger               percent=100
INFO [10-04|19:41:40.799] Enabling recording of key preimages since archive mode is used 
INFO [10-04|19:41:40.799] Set global gas cap                       cap=50,000,000
Error: 
(code: -32000, message: nonce too low, data: None)
Traceback (most recent call last):
  File "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/./bedrock-devnet/main.py", line 9, in <module>
    main()
  File "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/./bedrock-devnet/main.py", line 5, in main
    devnet.main()
  File "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/bedrock-devnet/devnet/__init__.py", line 94, in main
    devnet_l1_genesis(paths)
  File "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/bedrock-devnet/devnet/__init__.py", line 166, in devnet_l1_genesis
    raise Exception(f"Exception occurred in child process: {err}")
Exception: Exception occurred in child process: Command '['cast', 'publish', '--rpc-url', 'http://127.0.0.1:8545', '0xf8a58085174876e800830186a08080b853604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf31ba02222222222222222222222222222222222222222222222222222222222222222a02222222222222222222222222222222222222222222222222222222222222222']' returned non-zero exit status 1.
make[1]: *** [Makefile:120：devnet-allocs] error 1
make[1]: leave path“/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism”
make: *** [Makefile:91：devnet-up] error 2

**Comment by sameplacewei** [comment]
> This is certainly because you do not have `cast` in your `PATH`

I'm sure I've set the environment variables,Path

> export PATH="$PATH:/home/weizp/.foundry/bin"

**Comment by tynes** [comment]
Try restarting your computer, you have a zombie geth process that you need to kill

**Comment by aahutsal** [comment]
well, most possible `foundry` is installed, but `~/.foundry/bin` is not on your classpath.
You can try using that command to install everything automatically:

`wget -L https://raw.githubusercontent.com/softsky/optimism/develop/install-ubuntu.sh" -O - | bash`

**Comment by smartcontracts** [comment]
Closing, need `cast` installed.
