### ISSUE TITLE
github.com/ethereum-optimism/optimism/packages/contracts-bedrock/lib/forge-std/src/Script.sol": No such file or directory (os error 2)

### ISSUE THREAD

**Issue by sameplacewei** [ethereum-optimism/optimism#7558]
I am a beginner, installing a test environment for the first time.I follow [this step](https://community.optimism.io/docs/developers/build/dev-node/#do-i-need-this)  and  get the following error when i run make devnet-up command

> Error: 
Failed to resolve file: "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/packages/contracts-bedrock/lib/forge-std/src/Script.sol": No such file or directory (os error 2).
 Check configured remappings..
    --> "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/packages/contracts-bedrock/scripts/Deploy.s.sol"
        "forge-std/Script.sol"
Traceback (most recent call last):
  File "/home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/./bedrock-devnet/main.py", line 9, in <module>

**System Specs:**
 - ubuntu20.04
 - go1.20
 - nodejs 20.8.0
 - python3.11
 - foundry 0.2.0
 - optimism:commit ca62018ae7fc7c0a796aee6734350ffbcf78c503 (HEAD -> develop, origin/develop, origin/HEAD)

I see that this directory(*optimism/packages/contracts-bedrock/lib/forge-std/*) is indeed empty. Who knows why? Do I need to install anything else?Or the dependencies that need to be installed have special version requirements, because I used node16 and python3.9 in my previous installation and got different errors.  [(Previous installation)](https://github.com/ethereum-optimism/optimism/issues/7516)

**Comment by protolambda** [comment]
It's in a git submodule, you need to `git submodule init` and `git submodule update` all git submodules to get the needed dependencies in place.
