### ISSUE TITLE
Fix Broken Links

### ISSUE THREAD

**Issue by fujiar10** [ethereum-optimism/optimism#7574]
**Describe the bug**
broken links on the website. When the user clicked on the 'wannabe-NERD form' link on the path https://community.optimism.io/docs/contribute/contribution-path/nerd-req/#becoming-a-supnerd the link was 'blank or not displayed' instead of the expected contact page..

**To Reproduce**
1. Go to 'https://community.optimism.io/docs/contribute/contribution-path/nerd-req/#becoming-a-supnerd'
2. Click on 'wannabe-NERD form'
3. Scroll down to 'The form does not display'

**Expected behavior**
Hoping to fix it to sync with the discord form

**Screenshots**
![image](https://github.com/ethereum-optimism/optimism/assets/118127172/534ec2cf-6ea0-4735-acbf-2a5f4ffc21c1)

**System Specs:**
 - OS: IOS / CHROME

**Additional context**
The correct link is this if the form is still active for the reviewer 'https://docs.google.com/forms/d/e/1FAIpQLSfkGa_wlwWj9MVx8KdDfGhpuzU6lzLRnlndvCQ8-VavXQdgFA/viewform'

**Comment by Sabnock01** [comment]
Can you open this issue over at the [community-hub](https://github.com/ethereum-optimism/community-hub) repo and close this one?

**Comment by fujiar10** [comment]
Ohh sorry , thankyou
