### ISSUE TITLE
Block skipped on synchronisation process after performing a deposit

### ISSUE THREAD

**Issue by djav35** [ethereum-optimism/optimism#7580]
When using OP Stack, the funds of L2 accounts are set/updated according to the events emitted by L1 contract when performing a deposit. If the L2 block synchronisation process happen to skip the block containing the event (for any reason, such as resetting the network starting from a more recent L1 block), the deposit funds will not be reflected on the corresponding L2 account. In this kind of scenario what is the best way to “recover” these funds? Whats the best strategy to “re-sync” the network in case something fails?

**To Reproduce**
1. Set up an OP Stack L2 network.
2. Start syncing blocks providing B1 as genesis L1 block
3. Perform a deposit (send L1 Eth to L1 Bridge contract). This emits an event in block B5.
4. Stop the L2 network when it had synced up to block B4. 
5. Restart the L2 network providing block B6 as starting block.

I am aware that this may not be a bug in itself, but im wondering what is the best way to navigate around this issue. And an additional question: how much time does it take to sync blocks?

**Comment by ajsutton** [comment]
The derivation rules do not allow the L2 to skip L1 blocks.  Step 5 as described is not restarting the network, but creating an entirely new, alternate network. There isn't an easy way to do that with the current OP Stack.

If you stop the sequencer for some period of time, and then start it again, it will resume processing from where it left off on the L1 chain.
