### ISSUE TITLE
Initializing Rollup Node error: OP Goerli node failed to load p2p config

### ISSUE THREAD

**Issue by opfocus** [ethereum-optimism/optimism#7590]
**Describe the bug**
The issue is described as follows, adding '--p2p.disable' can avoid this error, but it will also disable P2P synchronization

**To Reproduce**

**Expected behavior**

**Screenshots**
t=2023-10-08T14:53:22+0000 lvl=info msg="Initializing Rollup Node"
ERROR[10-08|14:53:22.529] Unable to create the rollup node config  error="failed to load p2p config: failed to load p2p discovery options: failed to open discovery db: resource temporarily unavailable"
CRIT [10-08|14:53:22.529] Application failed                       message="failed to load p2p config: failed to load p2p discovery options: failed to open discovery db: resource temporarily unavailable"

**System Specs:**
 - OS: ubuntu 22,04
 - Package Version (or commit hash):
commit b3c77b0aba751401a3b2e7415454caa5a06afeb2 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: 80fdee6cf ea12a7aeb
Author: OptimismBot <112345690+OptimismBot@users.noreply.github.com>
Date:   Fri Sep 15 08:08:00 2023 -0400

**Additional context**
cd ~/optimism/op-node

./bin/op-node \
        --l2=ws://localhost:8551 \
        --l2.jwt-secret=./jwt.txt \
        --rpc.addr=0.0.0.0 \
        --rpc.port=8847 \
        --l1=https://ethereum-goerli.publicnode.com \
        --l1.rpckind=basic \
        --network=goerli

**Comment by protolambda** [comment]
I believe "resource unavailable" happens when your P2P discovery directory is locked or in use by another process. Are you running two op-nodes with the same discovery DB path? Or maybe there's a stray `LOCK` file?
This is configured with `--p2p.discovery.path`, and the default is `opnode_discovery_db`. If you remove it then it should work.
Also see `--p2p.peerstore.path`, you may have a similar problem there.

**Comment by opfocus** [comment]
> I believe "resource unavailable" happens when your P2P discovery directory is locked or in use by another process. Are you running two op-nodes with the same discovery DB path? Or maybe there's a stray `LOCK` file? This is configured with `--p2p.discovery.path`, and the default is `opnode_discovery_db`. If you remove it then it should work. Also see `--p2p.peerstore.path`, you may have a similar problem there.

Thank you very much, it's back to normal after deletion. Yes, I was running multiple op-nodes with the same default --p2p.discovery.path setting.
