### ISSUE TITLE
Replace burning gas logic in CanonicalTransactionChain

### ISSUE THREAD

**Issue by elenadimitrova** [ethereum-optimism/optimism#762]
The `OVM_CanonicalTransactionChain.enqueue()` function currently burns through `1/32th` of the `gasLimit` the cross domain message is sent with. This gas represents the "L2 fee" and thus instead of burning it, should be distributed accordingly. 

**Additional context**
This was also discussed in the context of reducing the cost of `deposit` here 
https://github.com/ethereum-optimism/optimism/pull/667#discussion_r624045036

**Comment by smartcontracts** [comment]
I think this would be a good topic for a GH discussion.

**Comment by smartcontracts** [comment]
Discussion is here now: https://github.com/ethereum-optimism/optimistic-specs/discussions/32
