### ISSUE TITLE
Codechecks failures in CI

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#767]
**Describe the bug**
Codechecks is failing in CI, the offending line is:
https://github.com/codechecks/monorepo/blob/13986fee646918b63841f04bc4a2f3d0cf9c7000/packages/client/src/getExecutionContext.ts#L24

The checks are:
- https://github.com/codechecks/monorepo/blob/ba52ad88a50898bf4ad246fd16ce5f7f7ada4034/packages/client/src/ci-providers/GithubActions.ts#L14
- https://github.com/codechecks/monorepo/blob/ba52ad88a50898bf4ad246fd16ce5f7f7ada4034/packages/client/src/ci-providers/GithubActions.ts#L27

See: https://github.com/codechecks/monorepo/issues/80

**To Reproduce**
1. Open a PR that changes the typescript code or contracts

**Expected behavior**
CI passes

**Comment by snario** [comment]
cc @krzkaczor

**Comment by krzkaczor** [comment]
It should be fixed in: `@codechecks/client@0.1.10-beta` Can you update?

Changes: https://github.com/codechecks/monorepo/pull/81

**Comment by smartcontracts** [comment]
Seems to be working. Closing unless anyone has further issues.

**Comment by smartcontracts** [comment]
Ty @krzkaczor!!!
