### ISSUE TITLE
Extend op-service LifecycleCmd usage to all long-running Go services

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#7671]
Op-node uses `cliapp.LifecycleCmd` to handle startup/shutdown/force-shutdown, while ensuring resources are closed and any shutdown errors are propagated properly.

Previous context-based shutdown patterns encouraged bad code that shuts down like `defer thing.Close()` without propagating the error, or even returning before go-routines of the service fully shutdown, since context closure triggers shutdown, but does not await the results.

Services to update:
- [x] op-batcher
- [x] op-proposer
- [x] endpoint-monitor
- [x] indexer
- [x] op-wheel (`engine auto` sub-command is long-running, other sub-commands are not, may require some more work)
- [x] op-bootnode
- [x] op-heartbeat
- [x] op-challenger

**Comment by mslipper** [comment]
@protolambda are you still working on this?

**Comment by protolambda** [comment]
@mslipper an external contributor implemented the op-proposer changes last week. op-batcher and op-node are already done. Op-challenger remains I think.

**Comment by protolambda** [comment]
The indexer is also done. And I think op-bootnode, op-heartbeat and op-wheel are nice to have; they work relatively well as-is since they don't have a lot of resources to start/close, but I may be able to implement the changes there soon now that I'm back from devconnect.
