### ISSUE TITLE
error creating l2 genesis: block base fee not set

### ISSUE THREAD

**Issue by sameplacewei** [ethereum-optimism/optimism#7681]
I began to learn the [document](https://stack.optimism.io/docs/build/getting-started/#deploy-the-l1-contracts) and follow the steps prompted. When I do this step [Generate the L2 config files] , I get the following error message:
      **error creating l2 genesis: block base fee not set**

The orders I carried out were this:
    go run cmd/main.go genesis l2 \
    --deploy-config ../packages/contracts-bedrock/deploy-config/getting-started.json \
    --deployment-dir ../packages/contracts-bedrock/deployments/getting-started/ \
    --outfile.l2 genesis.json \
    --outfile.rollup rollup.json \
    --l1-rpc http://localhost:7545 

Can someone tell me where to configure this parameter？

**Comment by smartcontracts** [comment]
Linked doc is out of date, please use the new docs: docs.optimism.io
