### ISSUE TITLE
op-proposer,challenger: start/stop balance-metrics like op-batcher

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#7684]
`StartBalanceMetrics` in op-batcher creates a background loop that can be closed gracefully. This same pattern should be applied to the proposer/challenger, so the loop is closed before the RPC clients are closed.

See https://github.com/ethereum-optimism/optimism/pull/7682 for context.

**Comment by smartcontracts** [comment]
Was this fixed?

**Comment by protolambda** [comment]
fixed in https://github.com/ethereum-optimism/optimism/pull/8235
and https://github.com/ethereum-optimism/optimism/pull/8040
