### ISSUE TITLE
Support for shorter `l2blocktime` in deploy-config

### ISSUE THREAD

**Issue by shaspitz** [ethereum-optimism/optimism#7706]
**Is your feature request related to a problem? Please describe.**

I'm looking to spin up a op-stack rollup which uses a block time that is shorter than 1 second. The [l2blocktime](https://github.com/ethereum-optimism/optimism/blob/f514eac8f2a63632caad7ae2cba0c90bd251492b/op-chain-ops/genesis/config.go#L47) config value is a uint64, with units as seconds. This prevents target block times that are sub 1 second from being possible. 

**Describe the solution you'd like**

It would be nice if the `l2blocktime` config value could be of the `time.Time` type, or stay as an integer with units as milliseconds. This way, more granular target block times could be used for custom rollups. 

**Additional context**

I've read through op-stack documentation, and did not find a concrete reason why sub 1 second bock times would be unachievable from a protocol design perspective. Maybe there's some context I'm missing here as to 
1. Why 2 seconds was chosen as the target block time for OP Mainnet
2. If shorter block times are possible (akin to Arbitrum's ~0.26sec avg blocktime). 

Thank you!

**Comment by tynes** [comment]
This is not something that we are prioritizing internally at the moment. There are tradeoffs here as faster blocktimes result in the db growing larger over time resulting in slower i/o as well as overall performance issues in the node itself. The real solution here is to give better preconfirmations, ie the block builder optimistically returns the receipt as if the block has already been mined. This obviously introduces some amount of trust if there is not a cryptographic/economic scheme enforcing it.

Do you think that supporting lower L2 blocktime is possible with a small diff? Do you think its possible without a hardfork? This is not a small task to take on as its very consensus critical

**Comment by tynes** [comment]
@shaspitz open your twitter dms plz

**Comment by shaspitz** [comment]
Valid points all around, thank you! I'll give this issue more thought. DMs have been opened
