### ISSUE TITLE
Parse Solidity Deploy Config Lazily

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#7711]
**Is your feature request related to a problem? Please describe.**

The [DeployConfig](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/scripts/DeployConfig.s.sol) contract is used to parse the JSON deploy config files. The problem is that some deploy config values are for testnet only features, like the fault proof. Since all config is parsed in the constructor, this means that all deploy config files need to contain all of the config values even if the config values aren't used in a particular script execution. The deploy config contract should be updated to parse lazily, meaning that it no longer reads the entire JSON file in the constructor but instead it has a getter for each value and reads the JSON file inside of each getter for the particular value.

**Comment by Ekzer** [comment]
Hi @tynes,
Is it still accurate? Happy to jump on this one :D

**Comment by smartcontracts** [comment]
Is this still something we want to do? @tynes
