### ISSUE TITLE
Update Geth to produce revert reasoning instead of UNPREDICTABLE_GAS_LIMIT

### ISSUE THREAD

**Issue by TransmissionsDev** [ethereum-optimism/optimism#773]
Currently if a transaction reverts geth reports this error:
![image](https://user-images.githubusercontent.com/26209401/117220858-f0c79280-adbc-11eb-9c52-56aaddb5dabe.png)
This makes it impossible to write tests that assert about revert reasons and is overall a big devex pain.

After talking with @smartcontracts, he said that updating Geth to use it's newer revert handling would fix this issue.

Here's what that updated error handling looks like:
https://github.com/ethereum/go-ethereum/blob/37b5595456e7049e3ed487c41564281de52e00ab/internal/ethapi/api.go#L1048-L1063

Here's the current error handling:
https://github.com/ethereum-optimism/go-ethereum/blob/beed9003d2f191befa91dde2a50f421c986bdc21/internal/ethapi/api.go#L1087-L1091

**Comment by TransmissionsDev** [comment]
fyi this is not fixed by `v0.3-rc` :)

**Comment by platocrat** [comment]
@TransmissionsDev This looks like a duplicate of #664.

**Comment by K-Ho** [comment]
> @TransmissionsDev This looks like a duplicate of #664.
No, they're different issues. This is the issue that revert reasons don't appear when running estimateGas on a tx that will revert. https://github.com/ethereum-optimism/optimism/issues/664 is that estimateGas reverts when the tx should actually succeed.

**Comment by smartcontracts** [comment]
Closed by #774!
