### ISSUE TITLE
Testing Plan for Canyon Network Upgrade

### ISSUE THREAD

**Issue by trianglesphere** [ethereum-optimism/optimism#7731]
The features currently planned for canyon are the following:

* Activating Shapella
* Changing EIP-1559 parameters
* Adjusting the channel ordering in the channel bank
* Adding span batches
* Fixing an op-geth receipt hashing bug
* Adding the create2Deployer on base

We have unit tests for each of these features are part of our normal development process, but would like to test the activation & assert that the behavior is as expected before and after the network upgrade.

To test the above, we want to have scripts which do the following:

* Shapella Before
    * Block RLP **does not** contains withdrawals
    * PUSH0 instruction **does not** work
* Shalella After
    * Block RLP **does** contains withdrawals
    * PUSH0 instruction **does** work
    * P2P gossip continues to work
* EIP-1559 Changes
    * Check that the new parameters are being used only after activation by calculating the basefee by the old formula & also by the new formula 
* Channel Ordering Fix
    * Submit a dangling channel prior to the upgrade & observe a safe head stall
    * Submit a dangling channel after the upgrade & observe no safe head stalls
* Span Batches
    * Submit span batches prior to activation & assert that no L2 blocks are derived from them.
    * Submit span batches after activation & assert that the L2 safe chain advances.
    * Submit normal batches after activation & assert that those still work.
* op-geth receipt hashing bug
    * Manually RLP encode & hash a pre & post canyon deposit receipt. Verify that the hash is in the receipts trie
* create2Deployer
    * Assert that the codehash pre-canyon is the empty code hash. Assert that post-canyon on specific chains that it is the expected code hash
    * If testing the activation of multiple chains, it should remain the empty code hash on some chains
    * Post-Canyon, send a transaction that uses this contract

**Comment by ajsutton** [comment]
If its possible for span batches to be submitted across multiple transactions like regular batches, we should also test the behaviour when the span batch starts prior to the fork activating and is completed after the fork activates.

Probably also worth a test to confirm that chain derivation works correctly when there is a mix of span and normal batches.

Otherwise looks good.

**Comment by trianglesphere** [comment]
Status Update. The following have testing scripts & I have confirmed that they work

* Withdrawals in the L2 block body
* Deposit Receipt Hash (there may be a bug in the json RPC being returned, but the block hash is working correctly)
* 1559 Basefee calculation changes at the right time
