### ISSUE TITLE
Cannot install `@eth-optimism/contracts` in `optimism/examples/l1-l2-deposit-withdrawal`

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#775]
**Describe the bug**
I tried to install `@eth-optimism/contracts` in `optimism/examples/l1-l2-deposit-withdrawal` but the package does not appear in the local `node_modules`.

**To Reproduce**
1. Clone monorepo: `git clone https://github.com/ethereum-optimism/optimism.git`
2. Checkout the `l1-l2-deposit-withdrawal` branch: `git checkout docs/l1-l2-deposit-withdrawal`
3. Install deps: `yarn`
4. Inspect local `node_modules`: `cd node_modules/@eth-optimism` && ls`
5. See that `@eth-optimism/contracts` is not present

**Additional context**
I expected for this package to be installable so that we could use the contracts during testing. Otherwise, there's no easy way to import and use `Abs_L2DepositedToken.sol` contract for `L2DepositedToken.sol` in `optimism/examples/l1-l2-deposit-withdrawal`, which is required in this example.

**Comment by snario** [comment]
This is how monorepos using Yarn workspaces works, the root level `node_modules` contains `@eth-optimism/contracts`
