### ISSUE TITLE
span-batch validation test improvements 

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#7853]
Test coverage:
- for `batch.GetTimestamp() > l2SafeHead.Time ` (related to below)
- for `startEpochNum > parentBlock.L1Origin.Number+1` check span-batch validation
- for `startEpochNum == parentBlock.L1Origin.Number+1 ` check in span-batch validation
- for ` batch.GetBlockTimestamp(i) <= l2SafeHead.Time {` in span batch validation
- for `if batch.GetBlockEpochNum(i) > batch.GetBlockEpochNum(i-1) {` in span batch validation
- for `!bytes.Equal(safeBlockTxs[j+depositCount], batchTxs[j])` in span-batch validation

Test coverage ideas by @ajsutton

**Comment by ImTei** [comment]
opened PR: https://github.com/ethereum-optimism/optimism/pull/7953
