### ISSUE TITLE
Contract deployments to Kovan fail with a `Reverted` error on the tx explorer

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#786]
**Describe the bug**
An issue was raised in Discord by the @funfair-tech team, by Mark and Josh, that re-deploys of all of their contracts to Kovan fail with a revert error.
You can [see this error on the transaction explorer](https://kovan-l2-explorer.surge.sh/tx/0x55d15ff9f9734aedd2fa3723ac60d7783aec9c2352fa6d6a4e3ce14560500c0c).

Snapshot of the transaction on the OE transaction explorer is below:

<img width="943" alt="Screen Shot 2021-05-06 at 9 22 30 AM" src="https://user-images.githubusercontent.com/37757724/117314665-9b3ac680-ae4c-11eb-8e1d-b195cb12383a.png">

Mark noted that re-deploys of their contracts with the _same source code and build settings_ worked previously, but now they are failing as well.
Additionally, they deployed their contracts to Kovan many times in the past, using hardhat, and they "worked all the time before".

This is a critical blocker for Mark and Josh as they "were hoping to be getting everything to a state where we could do a run-trough for the video today, but we're blocked until its all back

**Additional context**
Mark and Josh shared what think might be causing this issue. I'll quote them below:

Mark: 
> That looks like its down to a too high nonce occurring.  Is there any way through JSON-RPC we can detect this is the reason - this error comes from a headless server (which we run multiple of in a cluster on standard Ethereum using the one account) which expects that TX with nonces that are too high just get queued or dropped rather than reverted.

Josh: 
> @K-Ho We'll have downtime for the next few hours, at which point the state will remain < isnt the nonce part of the state? thought that was staying the same?

**Comment by smartcontracts** [comment]
Is this still happening?

**Comment by smartcontracts** [comment]
I'm going to close this issue because I think it's a bit too vague. Needs more information before we can figure out what's going on (if anything).
