### ISSUE TITLE
msgHash of L1 to L2 deposit is `undefined`

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#787]
**Describe the bug**
@anthonymartin @gdsoumya (ScalingEthereum hackers) reported an issue with using the `watcher` to get an L1 to L2 message hash for a Kovan deposit. The message hash being returned is `undefined`.
This prevents them from being able to retrieve the L2 transaction receipt by using the `watcher`.

Contract deployments to Kovan work. The message hash being undefined is the only issue blocking their project.
They are using logic from the `l1-l2-deposit-withdrawal` example script to get the message hash. You can find this logic in their [`deploy-kovan.js` script](https://github.com/gdsoumya/scaling-eth-hackathon/blob/2786c318c1fd6b3b9e6ceb7518f725d77f4cedd7/packages/hardhat/deploy-kovan.js#L165-L171). It is shared below for convenience:
```js
  // Wait for the message to be relayed to L2.
  console.log("Waiting for deposit to be relayed to L2...");

  const [msgHash1] = await watcher.getMessageHashesFromL1Tx(tx2.hash);
  console.log(msgHash1, tx2.hash);
  await watcher.getL2TransactionReceipt(msgHash1);
```

**Expected behavior**
Message passing works as expected locally. So, the same behavior is should be expected on Kovan.

**Additional context**
@anthonymartin and @gdsoumya will share additional comments as needed.

**Comment by gdsoumya** [comment]
The issue was with the L1 messenger address, once the updated address was used the correct msgHash was returned @platocrat
