### ISSUE TITLE
Make @eth-optimism/contracts browser-compatible

### ISSUE THREAD

**Issue by gigamesh** [ethereum-optimism/optimism#790]
(surfaced from: https://github.com/ethereum-optimism/optimism/pull/713)

@eth-optimism/contracts now has `connectToL1Contracts` and `connectToL2Contracts` functions that work in the browser, but its other code is not fully compatible

I think we have two options:

1. Isolate the browser-friendly code in a new package 
2. Refactor existing package to be fully browser compatible

**Comment by smartcontracts** [comment]
Hmmm... do you know exactly *why* `@eth-optimism/contracts` isn't browser compatible?

**Comment by tynes** [comment]
I believe this has been closed by https://github.com/ethereum-optimism/optimism/commit/5e5d4a1872da893b51ea5047f215d3df52672855
