### ISSUE TITLE
Proposal to have inbox transaction registry ( or snapshot ) instead of scanning every blocks

### ISSUE THREAD

**Issue by ghost** [ethereum-optimism/optimism#7933]
Instead of scanning every blocks looking for a inbox transaction it would be useful to have a snapshot or collection of L1 transactions submitted by a sequencer.

**Comment by ghost** [comment]
I think this could be included on IPFS and maintained by multisig contract for every specific window if submitting an array of bytes32 transaction hashes to an emitter contract sounds costy.

**Comment by tynes** [comment]
It is not clear what you are proposing. Have you ever used IPFS for storing a lot of data in production? Companies have full devops teams for running that infrastructure. Please reopen with a more thorough proposal

**Comment by ghost** [comment]
I think someone already implemented the similar feature https://github.com/EspressoSystems/op-leader-election/pull/48
