### ISSUE TITLE
Indexer(feat) API - support withdrawal lookups by message hash

### ISSUE THREAD

**Issue by ethenotethan** [ethereum-optimism/optimism#7942]
**Is your feature request related to a problem? Please describe.**
The Indexer API can be extended to support better specificity with an additional request query field (`message_hash`) that can be used for O(1) lookups on withdrawal. This is especially useful in circumstances when a client is trying to find indexed withdrawal metadata (balances, L2 tx, etc.) using an L1 withdrawal event (`WithdrawalProven`, `WithdrawalFinalized`). 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hamdiallam** [comment]
Sweet this sounds good to me! Should the withdrawal always be key'd by the transaction hash?

Or would you also like to be able to do an O(1) based on the cross domain message hash?

**Comment by ethenotethan** [comment]
Probably the former, ideally we could use the l2 withdrawal tx hash for a consistent lookup since its channeled through all three key events in a withdrawal flow `(MessagePassed, WithdrawalProven, WithdrawalFinalized)`.

**Comment by hamdiallam** [comment]
okay cool i'd imagine we would want two different endpoints for transactions and messages

**Comment by tynes** [comment]
The indexer has been deprecated
