### ISSUE TITLE
Tslint is deprecated, use eslint instead

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#795]
As @tynes and @gakonst have pointed out, `tslint` is deprecated. We should be using eslint instead. Probably requires an hour or two of minor tweaks.

---
tslint is deprecated by the way: https://github.com/palantir/tslint

_Originally posted by @tynes in https://github.com/ethereum-optimism/optimism/pull/794#issuecomment-833838838_

**Comment by rajivpo** [comment]
Happy to try and tackle this if still unclaimed

**Comment by gakonst** [comment]
Go for it :) I'll review your PR

**Comment by smartcontracts** [comment]
> Happy to try and tackle this if still unclaimed

Definitely still unclaimed!

**Comment by rajivpo** [comment]
Ok will try to wrap this up and submit a PR later today
