### ISSUE TITLE
Add a unit test to validate that every flag has a corresponding ENV Var

### ISSUE THREAD

**Issue by trianglesphere** [ethereum-optimism/optimism#7976]
It's too easy to forgot to add env vars, so write a test for it.
Could consider automatically generating the env var, but we'd need a test to validate that the generated env vars are the same as the current env vars.

**Comment by fahimahmedx** [comment]
Interested in taking this on! I'm still learning the codebase, and was wondering what are some examples of flags in this context?

**Comment by trianglesphere** [comment]
Fixed in https://github.com/ethereum-optimism/optimism/pull/8596
