### ISSUE TITLE
Removing necessity of an archive node used for op-proposer

### ISSUE THREAD

**Issue by ghost** [ethereum-optimism/optimism#7984]
I might be blind but I could not find any necessity or proof that op-proposer will require historic states of the contract.

As written on the docs https://stack.optimism.io/docs/build/getting-started/#op-geth, op-proposer would require an archive node but asking to the Geth devs if we supply `reexec` option to the `debug_traceTransaction` method it would be able to fetch and trace calls for past 10K blocks by default, without running an archive node which Geth isn't optimized for.

**Comment by smartcontracts** [comment]
cc @protolambda can you confirm whether this works? We need the storage slot for the message passer but idk if it's possible to get this with the `reexec` option.

**Comment by ajsutton** [comment]
I'm not sure anyone has tried the reexec option to be honest.

The risk with not using an actual archive node is that the proposer is required to submit proposals at a specific interval - the L2 output oracle contract will not allow it to skip proposals (https://github.com/ethereum-optimism/optimism/blob/f4a234c29b90f2a86e61fc897db343bda651202c/packages/contracts-bedrock/src/L1/L2OutputOracle.sol#L187-L190).  If the proposer is always up and functioning that's not an issue, but if it's down for a period of time then it will need old world state to catch up.  10k block history would allow less than 6 hours of downtime before the proposer couldn't recover.

A large L1 reorg can also cause a very large L2 reorg to be required which an archive node can handle but we've seen cases on goerli where a full node hit the limit of what geth would reorg. Again, not sure if the reexec option would help there or not.

So I'd be happy to be corrected, but I suspect the official docs should continue say to use an archive node as it avoids all those risks. People can obviously make their own risk trade offs for their own deployments though.

**Comment by ghost** [comment]
@ajsutton I see, so sticking on an archive node would be good but hosting some large L2 like Optimism or Base would require several TB of disk space and extra hardware resources to run it properly. Given that, would it be possible to fetch those required state calls from an alternative archive node endpoint like from op-erigon or op-reth?

**Comment by ghost** [comment]
Also, could it be considered to emit the outputRoot from L2 as a contract event? Fetching historic contract events doesn't require archive node since it is saved on transaction receipts.

**Comment by ajsutton** [comment]
Probably more likely would be to include the output root in the block header which would make it easily available for non-archive nodes and even light clients, but that's not something we're currently working on.

**Comment by ghost** [comment]
Seems like extraData field is empty, do you think it is a good place to insert those values? ( Like, clique PoA using it for recording signers? )

**Comment by ajsutton** [comment]
It's an option. I don't think anyones tried to think through the specific details.

**Comment by ghost** [comment]
@ajsutton I have tracked down to find the source of where the outputRoot is coming from

1. op-proposer calls op-node with `optimism_outputAtBlock` method

https://github.com/ethereum-optimism/optimism/blob/develop/op-proposer/proposer/l2_output_submitter.go#L293

2. output is fetched from `OutputV0AtBlock` func

https://github.com/ethereum-optimism/optimism/blob/develop/op-node/node/api.go#L98C26-L98C41

3. op-node calls op-geth for block header information and verifies the outputRoot of block header to see if it actually contains a storage proof

https://github.com/ethereum-optimism/optimism/blob/develop/op-service/sources/l2_client.go#L179C43-L179C66

4. outputRoot is encoded with storage proof

https://github.com/ethereum-optimism/optimism/blob/develop/op-service/sources/l2_client.go#L190
https://github.com/ethereum-optimism/optimism/blob/develop/op-service/eth/output.go#L55

So since it calls the `eth_getProof` not `eth_call`, I think reexec option isn't available for use

> If the proposer is always up and functioning that's not an issue, but if it's down for a period of time then it will need old world state to catch up. 10k block history would allow less than 6 hours of downtime before the proposer couldn't recover.

Are you actually concerned about the proposer being down and the sequencer keep running, producing new blocks?

**Comment by ajsutton** [comment]
The output root is not the same as the header root. The specification for it is at https://github.com/ethereum-optimism/optimism/blob/develop/specs/proposals.md

**Comment by ghost** [comment]
Yeah I forgot the keccak digest https://github.com/ethereum-optimism/optimism/blob/develop/op-service/eth/output.go#L55, it is detailed here I think https://github.com/ethereum-optimism/optimism/blob/develop/op-service/eth/output.go#L55

**Comment by ghost** [comment]
@ajsutton If the sequencer is down, outputRoot will remain unchanged since there will be no new blocks right? So the sequencer going down wouldn't be an issue for the network recovery or the problem for calling `proposeL2Output` function after the downtime right? https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/L1/L2OutputOracle.sol#L176

**Comment by ajsutton** [comment]
No that's not necessarily correct.  Blocks are forced to be produced if the sequencer window to ensure that deposit transactions are always able to be includable.

Also the output root differs from the block root by more than just the keccak hash - it hoists the state root and message passer contract storage root to reduce the size of proofs.

**Comment by ajsutton** [comment]
I'm going to close this one. For the reasons I mentioned in https://github.com/ethereum-optimism/optimism/issues/7984#issuecomment-1789726206 we're going to continue recommending using an archive node as the source for the proposer. It may be possible to use a full node, but not recommended.

Output roots can be retrieved from full nodes today, just potentially not far enough back for the actual proposer.

**Comment by ghost** [comment]
@ajsutton What I was suggesting is that since the outputRoot depends on the block generated by the sequencer would be great if the sequencer calculate the value and add the value to the block header so that without running an historic state node would be possible to retrieve the value.
