### ISSUE TITLE
Tips to run op-stack programmatically 

### ISSUE THREAD

**Issue by ghost** [ethereum-optimism/optimism#8008]
Hello,

I see many monitoring tools and devops related codes but I am not sure which package should I refer to run op-stack programmatically.

Would like to subscribe on any kind of unhealthy event and attempt to recover on failure.

Is there any tip or an advice on this?

Thanks.

**Comment by tynes** [comment]
You should consider deploying to an orchestration framework like kubernetes instead of implementing that event handling yourself. Kubernetes is battle tested and it restarts containers when they fail

**Comment by ghost** [comment]
@tynes Could I analysis the reason of failure and combat some possible DB corruption programmatically? https://github.com/ethereum/go-ethereum/issues/16607. Since the simple retrial would loop the failure

**Comment by tynes** [comment]
Yes you could likely do that although I do not have any good suggestions on how to do that off of the top of my head. It really depends on your setup. Are you experiencing DB corruption issues? I am not aware of this being a huge issue right now

**Comment by ghost** [comment]
@tynes No I was just curious if your team have faced and tried to solve the problem when it happened ( especially while running a node inside containers )

**Comment by smartcontracts** [comment]
I think the docs will hopefully soon get a section that gives advice for running a prod OP Stack chain.
