### ISSUE TITLE
@eth-optimism/contracts@0.2.10 does not package artifacts

### ISSUE THREAD

**Issue by krebernisak** [ethereum-optimism/optimism#802]
**Describe the bug**
`@eth-optimism/contracts@0.2.10` does not package `artifacts` or `artifacts-ovm` like it did in v0.2.9, which breaks packaged functions like `getContractDefinition`.

**To Reproduce**
1. Update to `@eth-optimism/contracts@0.2.10` from NPM
2. Try to use `import { getContractFactory } from '@eth-optimism/contracts'`

**Expected behavior**
Expecting `getContractDefinition` not to throw, for example on `getContractFactory('Lib_AddressManager')`.

**Screenshots**

`@eth-optimism/contracts@0.2.9`:
<img width="246" alt="Screenshot 2021-05-07 at 13 01 23" src="https://user-images.githubusercontent.com/615877/117441809-38255e80-af36-11eb-9b52-9a33b68e81f4.png">

`@eth-optimism/contracts@0.2.10`:
<img width="252" alt="Screenshot 2021-05-07 at 13 03 05" src="https://user-images.githubusercontent.com/615877/117441811-39ef2200-af36-11eb-8ea8-a6d8a3c29856.png">

**Comment by gakonst** [comment]
https://github.com/ethereum-optimism/optimism/commit/6dc1877490535dabc6ed5f127b5269cd5316e7e6 probably related - @smartcontracts

**Comment by smartcontracts** [comment]
Sorry - confirmed. Correct export should've been `"artifacts/contracts/**/*.json"` and not `"artifacts/contracts/*.json"`. Will have a fix ASAP.

**Comment by smartcontracts** [comment]
Created a PR to fix this. Sorry about that!

**Comment by gakonst** [comment]
@eth-optimism/contracts@0.2.11 is published, thanks.

**Comment by smartcontracts** [comment]
@krzkaczor can you confirm that this is fixed in 0.2.11?

**Comment by smartcontracts** [comment]
Just checked for myself and can confirm that 0.2.11 is fixed.

**Comment by krebernisak** [comment]
Great, confirmed! Thanks for a quick turnaround.
