### ISSUE TITLE
Make consistent default addresses

### ISSUE THREAD

**Issue by elenadimitrova** [ethereum-optimism/optimism#803]
We should use the same default values as currently in the Execution manager we use `0xdEfa017defA017DeFA017DEfa017DeFA017DeFa0` to signify a default address and in the Cross domain messengers we use `0x000000000000000000000000000000000000dEaD` for the default sender.

It would also be nice to move this (as well as the DEFAULT_UINT256 from the Execution Manager) into a small library.

Logged as a result of https://github.com/ethereum-optimism/optimism/pull/667#discussion_r627532765

**Comment by ben-chain** [comment]
Quick note here that this address is also duplicated in both L1 and L2 cross domain messengers right now, so we will be able to eliminate from both. :)
