### ISSUE TITLE
Multisig based stateRoot submission ( aka Authoritarianism )

### ISSUE THREAD

**Issue by ghost** [ethereum-optimism/optimism#8037]
Multisig based stateRoot submission would possibly remove the 7 days challenge and on-chain fault prover.

https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/L1/L2OutputOracle.sol#L176

If the multisig participants are trusted parties running some application to retrieve stateRoot with a dedicated resources I think there is no need to sacrifice users for the 7 days challenge period which would enhance user experience and would enable real-time L2 -> L1 data submission.

( It would also enable running some gas costy operation with L2 from L1, for example Tornado Cash Nova does this with Gnosis Chain with the bridge. L1 -> L2 -> L1 )

https://tornado-cash.medium.com/tornado-cash-introduces-arbitrary-amounts-shielded-transfers-8df92d93c37c

**Comment by ajsutton** [comment]
You can set this up today by setting a smart contract as the authorised proposer address and then having it require multiple confirmations.  However it is still fundamentally a centralised proposer model that requires trust in the authorised proposers as trust parties.  The fault proof system, when fully complete and the ability to override it is removed, provides a completely trustless, decentralised solution where the proposer is no longer a permissioned role and invalid proposals are removed by proving them to be invalid via the fault proof system.

**Comment by ghost** [comment]
@ajsutton Means that once the proof system is available, op-stack chains will remove the 7 day widow challenge?

**Comment by ajsutton** [comment]
No, the 7 day challenge window is an important part of security for an optimistic rollup.

**Comment by ghost** [comment]
I see, so 7 day widow challenge lives with the fault proof system even when the design is complete, thank you! For better understanding the problem for the community, could you leave something similar to the thread here? https://github.com/ethereum-optimism/developers/discussions/47
