### ISSUE TITLE
Client diversity around op-proposer

### ISSUE THREAD

**Issue by ghost** [ethereum-optimism/optimism#8038]
It would be great if the op-proposer could aggregate block header root and storage proofs from different optimism node implementations ( op-erigon, op-reth, nethermind ) and throw an error if one of the results differ from others.

Could be possibly utilized with https://github.com/ethereum-optimism/optimism/issues/8037 if we want to compare those with different infrastructure, different parties like how consensus works on L1.

**Comment by ajsutton** [comment]
This isn't something we're likely to add to op-proposer. It can already be achieved via off-chain monitoring or by setting the authorised proposer to be a contract that multiple op-proposers submit to and it then forwards on the proposal when some threshold is met.

**Comment by ghost** [comment]
@ajsutton I understand, for implementing a such system, would it be possible to be supported from op labs as an alternative setting of op-stack?

**Comment by ajsutton** [comment]
It's not something that's a priority for us as we're focussed on fault proofs currently. The OP Stack is MIT licensed so there's nothing stopping you from building this, but it's not something we'd merge into the official version and so not something we'd have capacity to invest time into supporting currently.

**Comment by ghost** [comment]
@ajsutton I think some financial support or an endorsement like retropgf would be good, what do you think?

**Comment by ajsutton** [comment]
RPGF and grants are not run by OP Labs and I have no say into how they're allocated. You'd need to look into the governance processes applicable to those.
