### ISSUE TITLE
Feat(indexer) - Support Bridge Tx Type Filtering in API

### ISSUE THREAD

**Issue by ethenotethan** [ethereum-optimism/optimism#8062]
**Is your feature request related to a problem? Please describe.**
Indexer API endpoints for fetching withdrawal and deposits currently expose all bridge txs independent of origination type. 

**Describe the solution you'd like**
Introduce a lightweight classification system for bridge tx types that can be filtered by when doing API lookups. This type enum can be passed as a query param when fetching deposits or withdrawals:
```
GET /api/v0/withdrawals/0x6969?type=standard_bridge
```

Type enums should be supported for `native`, `standard_bridge`, and `message` bridge transaction types. 

**Describe alternatives you've considered**

**Additional context**

**Comment by hamdiallam** [comment]
This looks good to me! cc @roninjin10. @nitaliano would be good to get your input here as well on what API would be fine for the UI

How should we handle ETH transfers to the OptimismPortal/L2ToL1MessagePasser? Should they only be coalesced in the response if the type is ommitted?

**Comment by hamdiallam** [comment]
@nitaliano would be good to get your input here as well on what API would be fine for the UI

**Comment by ethenotethan** [comment]
CC @lukasrosario for any additional requirements necessary for Base UI

**Comment by tynes** [comment]
The indexer has been deprecated
