### ISSUE TITLE
How will your code be adjusted after Eip4844 goes online?

### ISSUE THREAD

**Issue by guoshijiang** [ethereum-optimism/optimism#8097]
As we know, There is a data validity period in eip4844, about 30 days. If eip4844 launch mainnet, what will happen to the process of verifier synchronizing rollup data and derivation in op-stack? Will the data 30 days ago become finalized directly, or should I use a data snapshot?

**Comment by ghost** [comment]
Hello, you can track the whole process here https://github.com/ethereum-optimism/optimism/pull/7349

**Comment by smartcontracts** [comment]
Please refer to the Ecotone Upgrade Proposal for detailed information about the proposed changes for 4844: https://gov.optimism.io/t/upgrade-proposal-5-ecotone-network-upgrade/7669
