### ISSUE TITLE
Error Running go run cmd/main.go in op-node: JSON Unmarshal Issue

### ISSUE THREAD

**Issue by ZentaChainAdmin** [ethereum-optimism/optimism#8168]
**Describe the bug**
When running the `go run cmd/main.go` command for the op-node with specific flags and parameters, the application fails with a critical error related to JSON unmarshaling. The error message indicates an issue with unmarshaling a string into a Go struct field of type `[]interface {}`.

**To Reproduce**
1. Set up the environment with the specified versions of Go, Node, and other dependencies on macOS 14.
2. Navigate to the op-node directory in the terminal.
3. Execute the following command:

```
go run cmd/main.go genesis l2 \
--deploy-config ../packages/contracts-bedrock/deploy-config/getting-started.json \
--deployment-dir ../packages/contracts-bedrock/deployments/getting-started/ \
--outfile.l2 genesis.json \
--outfile.rollup rollup.json \
--l1-rpc $L1_RPC_URL
```

**Expected behavior**
I expected the `go run` command to execute successfully without critical failures, generating the specified genesis and rollup JSON files.

**System Specs:**
- Operating System: macOS 14 Sonoma
- Node Version: 20.9.0
- Go Version: 1.21.4
- Other Relevant Versions:
- git: 2.42.0
- pnpm: 16.14
- foundry: 0.2.0
- make: 3.81
- jq: 1.7
- direnv: 2.32.3

**Additional context**
3 attempts, all without success.

**Comment by ZentaChainAdmin** [comment]
## Issue Closure

Report: The key to solving the problem was switching from `make` to `gmake`. Additionally, during the process, I reinstalled Homebrew and encountered some challenges with `direnv`. However, this was addressed by reconfiguring `direnv` in the `.bashrc` file, ensuring its proper functionality.

Thank you for the support.

**Comment by evanlikn** [comment]
> ## Issue Closure
> Report: The key to solving the problem was switching from `make` to `gmake`. Additionally, during the process, I reinstalled Homebrew and encountered some challenges with `direnv`. However, this was addressed by reconfiguring `direnv` in the `.bashrc` file, ensuring its proper functionality.
> 
> Thank you for the support.

How did you solved this issue by switching from `make` to `gmake`, it seems to me was no difference, could you explained with more details, thanks very much.

**Comment by rbrick** [comment]
Following up to this. I ran into this issue. It seems like Forge as of the recent nightly builds are escaping strings passed into constructor (and likely other places) in the broadcast JSON. 

Forge v0.2.0 (commit 5b7e4cb)

```solidity
pragma solidity ^0.8.13;

contract Test {

   string public s;

   constructor(string memory _s) {
    s = _s;
   }

}
```

```json
"arguments": [
        "\"HelloWorld\""
 ]
```

This escaping leads to it being encoded as a string:

```json
{
 "arguments": "[\"0x6E5ed6320F977a956fA446EDF43Ab8DaABc274D4\",\"\\OVM_L1CrossDomainMessenger\\\"]"
}
```

Where as Go expects an `[]any` slice/array.

A solution I found for this was to change the Deployer.sol script:

https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/scripts/Deployer.sol#L382

and use `jq` to parse the escaped string as JSON: 

original:
```solidity
     cmd[2] = string.concat(Executables.jq, " -r '.arguments' <<< '", _transaction, "'");
```

new:

```solidity
     cmd[2] = string.concat(Executables.jq, " -r 'try(.arguments|map_values(try(fromjson),.))' <<< '", _transaction, "'");
```

**Comment by Sallery-X** [comment]
I have the same issue
t=2023-12-05T09:37:45+0000 lvl=info msg="Deploy config" path=/app/deploy-config/142095.json
t=2023-12-05T09:37:45+0000 lvl=info msg="Deployment directory" path=/app/deployments/142095
t=2023-12-05T09:37:45+0000 lvl=crit msg="Application failed"   message="json: cannot unmarshal string into Go struct field Deployment.args of type []interface {}"

**Comment by Sallery-X** [comment]
> Following up to this. I ran into this issue. It seems like Forge as of the recent nightly builds are escaping strings passed into constructor (and likely other places) in the broadcast JSON.
> 
> Forge v0.2.0 (commit 5b7e4cb)
> 
> ```solidity
> pragma solidity ^0.8.13;
> 
> contract Test {
> 
>    string public s;
> 
>    constructor(string memory _s) {
>     s = _s;
>    }
> 
> }
> ```
> 
> ```json
> "arguments": [
>         "\"HelloWorld\""
>  ]
> ```
> 
> This escaping leads to it being encoded as a string:
> 
> ```json
> {
>  "arguments": "[\"0x6E5ed6320F977a956fA446EDF43Ab8DaABc274D4\",\"\\OVM_L1CrossDomainMessenger\\\"]"
> }
> ```
> 
> Where as Go expects an `[]any` slice/array.
> 
> A solution I found for this was to change the Deployer.sol script:
> 
> https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/scripts/Deployer.sol#L382
> 
> and use `jq` to parse the escaped string as JSON:
> 
> original:
> 
> ```solidity
>      cmd[2] = string.concat(Executables.jq, " -r '.arguments' <<< '", _transaction, "'");
> ```
> 
> new:
> 
> ```solidity
>      cmd[2] = string.concat(Executables.jq, " -r 'try(.arguments|map_values(try(fromjson),.))' <<< '", _transaction, "'");
> ```

I tried it, but it did not work

**Comment by smartcontracts** [comment]
Please make sure that you're running the correct foundry version by running `pnpm update:foundry` in the root of this repo.

**Comment by smartcontracts** [comment]
Closing, make sure that you're always using the correct version of foundry by running `pnpm update:foundry`.
