### ISSUE TITLE
Error running OP Stack as a private rollup

### ISSUE THREAD

**Issue by maodaishan** [ethereum-optimism/optimism#8178]
**Describe the bug**
Hi team,
I'm using OP Stack to run a local rollup, it uses Optimism Georli as L1, so I'm building a rollup upon Optimism Georli.
Everything goes well at first, but it stucked on building a block. 
The OPStack will check the root of receipts of L1 block, it will compute it locally , and check whether it's the same as we got from L1 RPC. here they're different, so I think there must be some difference on computing the root of receipts between Optimism Georli and current OP Stack code.
Here's the err log of op-node :
`t=2023-11-15T03:08:13+0800 lvl=info msg="creating new block"                     parent=0x5bfc05cc50dad95ccea6fa79a37f83cb1e8a8928484ba579fed4b02063a2b9e2:16748 l1Origin=0xc7cd736cf95856a9c63578690e97fcd43133f5d7d919882d3f7e5348d1935f02:17276564
t=2023-11-15T03:08:13+0800 lvl=info msg="sequencer started building new block"   payload_id=0x89a2c4af9dc1d5b2 l2_parent_block=0x5bfc05cc50dad95ccea6fa79a37f83cb1e8a8928484ba579fed4b02063a2b9e2:16748 l2_parent_block_time=1,699,981,362
t=2023-11-15T03:08:13+0800 lvl=info msg="inserted block"                         hash=0x6bbfcb4ce1c7f5c93cc83aa709807f2583ad6832be86e1d0f5e05b04e1957286 number=16749 state_root=0xf83f005dcaba278fdccdb8f37fe9d3df37f7370cb97df3acb1ce53b910b33cb9 timestamp=1,699,981,364 parent=0x5bfc05cc50dad95ccea6fa79a37f83cb1e8a8928484ba579fed4b02063a2b9e2 prev_randao=0x3c6cfc1ee8795baaabdaa28e11f357ccb5ddea424c7f067999201161d791c11f fee_recipient=0x4200000000000000000000000000000000000011 txs=1 update_safe=false
t=2023-11-15T03:08:13+0800 lvl=info msg="sequencer successfully built a new block" block=0x6bbfcb4ce1c7f5c93cc83aa709807f2583ad6832be86e1d0f5e05b04e1957286:16749 time=1,699,981,364 txs=1
t=2023-11-15T03:08:14+0800 lvl=info msg="creating new block"                     parent=0x6bbfcb4ce1c7f5c93cc83aa709807f2583ad6832be86e1d0f5e05b04e1957286:16749 l1Origin=0x88776a73adfa67a147faa64bddfad8d26ce2b01d62289f68486cb2e1cac61166:17276565
t=2023-11-15T03:08:14+0800 lvl=info msg="sequencer started building new block"   payload_id=0x146c8804694e92f0 l2_parent_block=0x6bbfcb4ce1c7f5c93cc83aa709807f2583ad6832be86e1d0f5e05b04e1957286:16749 l2_parent_block_time=1,699,981,364
t=2023-11-15T03:08:14+0800 lvl=info msg="inserted block"                         hash=0x229509ca50d41828507c6311f06c351140033ee68a00a75e11cb6070bc547d32 number=16750 state_root=0xee644daef5d805bbe855b39a591fd687111cdb2f95558f5f0da3e5d107dfc201 timestamp=1,699,981,366 parent=0x6bbfcb4ce1c7f5c93cc83aa709807f2583ad6832be86e1d0f5e05b04e1957286 prev_randao=0x3c6cfc1ee8795baaabdaa28e11f357ccb5ddea424c7f067999201161d791c11f fee_recipient=0x4200000000000000000000000000000000000011 txs=1 update_safe=false
t=2023-11-15T03:08:14+0800 lvl=info msg="sequencer successfully built a new block" block=0x229509ca50d41828507c6311f06c351140033ee68a00a75e11cb6070bc547d32:16750 time=1,699,981,366 txs=1
t=2023-11-15T03:08:14+0800 lvl=info msg="creating new block"                     parent=0x229509ca50d41828507c6311f06c351140033ee68a00a75e11cb6070bc547d32:16750 l1Origin=0x401dcce2442d9f99e8fc561ce39594c36a4bc472414f996dc6850ea56e274de6:17276566
t=2023-11-15T03:08:15+0800 lvl=eror msg="sequencer temporarily failed to start building new block" err="temp: failed to fetch L1 block info and receipts: failed to fetch list of receipts: expected receipt root 0x945a28aedddb630acbdc3085c1a4f2b09e863cb2d99c25b96ff9be002a9258c8 but computed 0x65ced2cd63b31f55bc3aed4b3ebdc49feea4422e6e853c57eb97fa301759460f from retrieved receipts"
t=2023-11-15T03:08:15+0800 lvl=info msg="creating new block"                     parent=0x229509ca50d41828507c6311f06c351140033ee68a00a75e11cb6070bc547d32:16750 l1Origin=0x401dcce2442d9f99e8fc561ce39594c36a4bc472414f996dc6850ea56e274de6:17276566
t=2023-11-15T03:08:15+0800 lvl=eror msg="sequencer temporarily failed to start building new block" err="temp: failed to fetch L1 block info and receipts: failed to fetch list of receipts: expected receipt root 0x945a28aedddb630acbdc3085c1a4f2b09e863cb2d99c25b96ff9be002a9258c8 but computed 0x65ced2cd63b31f55bc3aed4b3ebdc49feea4422e6e853c57eb97fa301759460f from retrieved receipts"
t=2023-11-15T03:08:15+0800 lvl=info msg="creating new block"                     parent=0x229509ca50d41828507c6311f06c351140033ee68a00a75e11cb6070bc547d32:16750 l1Origin=0x401dcce2442d9f99e8fc561ce39594c36a4bc472414f996dc6850ea56e274de6:17276566
t=2023-11-15T03:08:16+0800 lvl=eror msg="sequencer temporarily failed to start building new block" err="temp: failed to fetch L1 block info and receipts: failed to fetch list of receipts: expected receipt root 0x945a28aedddb630acbdc3085c1a4f2b09e863cb2d99c25b96ff9be002a9258c8 but computed 0x65ced2cd63b31f55bc3aed4b3ebdc49feea4422e6e853c57eb97fa301759460f from retrieved receipts"
` 

**To Reproduce**
Run the OP Stack over Optimism Georli. After some time, the error happened.
code branch:TAG  op-node/v1.3.1 
Using Alchemy as L1 RPC .

**Expected behavior**
Wish team could give out the reason why this happened, thanks.

**Screenshots**

**System Specs:**
 - OS: Linux version 5.15.0-86-generic (buildd@lcy02-amd64-086) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023

 - Package Version (or commit hash):
 optimism TAG: op-node/v1.3.1

**Additional context**
I stored the log of op-geth, op-node, op-batcher,op-proposer, if you need any, please tell me, thanks.

**Comment by tynes** [comment]
Better to ask this in https://github.com/ethereum-optimism/developers/discussions
