### ISSUE TITLE
feat(devnet): Move from `geth` -> `anvil` for `make devnet-allocs`

### ISSUE THREAD

**Issue by clabby** [ethereum-optimism/optimism#8180]
## Overview

Currently, the `make devnet-allocs` job uses `geth` to deploy L1 contracts and generate the genesis state of L1 for `op-e2e`. `geth` is a bit heavy for what we need here.

**Describe the solution you'd like**
The `geth` invocation can be found [here](https://github.com/ethereum-optimism/optimism/blob/develop/bedrock-devnet/devnet/__init__.py#L163-L187) in the devnet script. Rather than using `debug_dumpBlock` in `geth`, we should just be able to use `anvil`'s `anvil_dumpState` endpoint.

Anvil's `anvil_dumpState` endpoint returns a gzip compressed hex string of a JSON object with the following schema:
```json
{
    "accounts": {
        "0x...00": {
            "nonce": "<hex_number>",
            "balance": "<hex_number>",
            "code": "<bytes>",
            "storage": {
                 "<32b_slot>": "<32b_value>"
            }
        },
        ...
    }
}
```

To easily convert the gzipped state back to JSON:
```sh
cast rpc anvil_dumpState --rpc-url http://localhost:8545 | jq -r | xxd -r -p | gzip -d
```

In addition, there are several default accounts in anvil that will be present within this state dump. To avoid this, pass `-a 1` to the anvil binary to only generate 1 default account, and filter it out when serializing the allocs in the devnet script. The create2 deployer is also deployed by default @ `0x4e59b44847b379578588920ca78fbf26c0b4956c`

### Output

The end result should be that the devnet is no longer reliant on `geth` to generate the state snapshots for `op-e2e` L1 allocs.

**Comment by tynes** [comment]
Closed as part of https://github.com/ethereum-optimism/optimism/pull/8517
