### ISSUE TITLE
`optimism-tutorial` tests fail with `CALL_EXCEPTION`

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#830]
**Describe the bug**
**Without having changed the test script nor the contracts**, the integration test fails at the beforeEach step that deploys the ERC20 contract.

The shorthand of the error log is below:
```
Error: transaction failed
```

The error code is `CALL_EXCEPTION`.

**To Reproduce**
1. `git clone https://github.com/ethereum-optimism/optimism-tutorial.git`
2. Install deps: `yarn`
3. Compile ERC20 contract: `yarn hardhat compile --network optimism`
4. Run tests and see error: `yarn hardhat test --network optimism`

The truncated error log is below, truncating tx data:
<img width="926" alt="Screen Shot 2021-05-10 at 1 58 28 PM" src="https://user-images.githubusercontent.com/37757724/117710500-ccdac700-b197-11eb-99d5-8450e8f8d3c7.png">

**Expected behavior**
Tests should pass, since no logic was changed in the repository except for hardcoding `gasPrice: 0` and `gasLimit: 8999999` to contract calls. 
Without hardcoding `gasLimit: 8999999` to the call to deploy the contract in the integration test, I receive the `UNPREDICTABLE_GAS_LIMIT` error.

**Additional context**
Tests were made against `v0.3.0-rc` of the optimism/ops tool.

**Comment by smartcontracts** [comment]
I think this bug might be different from the one reported on `optimism-tutorial`.

**Comment by smartcontracts** [comment]
Fixed in https://github.com/ethereum-optimism/optimism-tutorial/pull/29
