### ISSUE TITLE
Snap Sync: Simple checkpoint block flag

### ISSUE THREAD

**Issue by trianglesphere** [ethereum-optimism/optimism#8307]
Add a flag which specifies an L2 checkpoint block.

**Comment by sebastianst** [comment]
@trianglesphere and I just discussed that we probably want to drop this one, as it's not critical to get snap sync to work and adds complexity. Can also add later after Snap Sync is already prod ready.

**Comment by trianglesphere** [comment]
Closing this because we're going to have to finalize whatever block we finish syncing to when done with EL sync & this checkpoint block flag doesn't work.
