### ISSUE TITLE
Snap Sync: Modify op-node to use the P2P unsafe block as the syncing target

### ISSUE THREAD

**Issue by trianglesphere** [ethereum-optimism/optimism#8308]
The op-node will now need to handle long syncing gaps and needs to handle finalization which doesn't start from genesis.

**Comment by protolambda** [comment]
A draft of this exact thing has already been implemented as part of https://github.com/ethereum-optimism/optimism/pull/8106
The derivation-pipeline is able to operate in a state where there's no "chain" on the EL side, and the engine-queue new-payload queue feeds into the engine as it's syncing. The engine handles the new payloads by extending the skeleton header chain, maintaining an accurate sync target, while continuing snap-sync, just like it would on a L1 CL<>EL optimistic beacon-chain sync.
This has been tested to successfully sync the op-goerli network, without prior datadir on the op-geth side. We may still want to decouple more of the engine-controls from the engine-queue / derivation pipeline, to encapsulate this syncing state better from the derivation work.

The remaining feature is the finalization: the op-node needs a way to turn the resulting synced chain into a finalized chain.

**Comment by trianglesphere** [comment]
> We may still want to decouple more of the engine-controls from the engine-queue / derivation pipeline, to encapsulate this syncing state better from the derivation work.

Yep. This is going to be the bulk of the work on the op-node. The current interactions are already pretty complex & I want to make sure that they stay manageable.
