### ISSUE TITLE
contracts-bedrock: initializable test coverage

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#8382]
We look through the various contracts to see which have `_initialized` and then assert that they cannot be initialized again. Right now we only do this for contracts in `src/{L1,L2}` but we should instead be testing all of the contracts in `src`.

See https://github.com/ethereum-optimism/optimism/pull/8377 for more details

**Comment by smartcontracts** [comment]
What happened to this? cc @tynes

**Comment by tynes** [comment]
this has been completed
