### ISSUE TITLE
op-node: cleanup error declarations & error-case tests

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#8388]
The base errors should be declared as variables, wrapped with fmt.Errorf for additional error details. Tests should then assert the base error was returned when expected.

This cleanup task applies to the whole code-base, but in particular to code-paths like the derivation-code, where we want clean error-case testing.

**Comment by dhir1007** [comment]
Hello @protolambda I'd like to take this issue and help standardize error handling in op-node. Proposed approach:

1. Define base errors as package-level variables
2. Update error wrapping to use fmt.Errorf with base errors
3. Enhance tests to verify specific error cases
4. Start with the derivation package as suggested

Happy to begin with a focused PR on the derivation package if this approach aligns with your expectations.

**Comment by protolambda** [comment]
Sorry, this issue is stale and was completed long ago. Closing it.
