### ISSUE TITLE
Switch formatter from prettier to biome

### ISSUE THREAD

**Issue by roninjin10** [ethereum-optimism/optimism#8397]
## Description

This task is an easy good first issue to replace prettier formatting for JavaScript files with biome.

- [Biome is 25x faster than prettier](https://github.com/biomejs/biome/tree/main/benchmark#formatting) 
- [They recently reached the ability to be pretty prettier equivelent passing over 95% of the prettier test suite](https://prettier.io/blog/2023/11/27/20k-bounty-was-claimed)

An example of using biome can be found [here](https://github.com/wevm/viem/blob/main/biome.json#L25)

Note: This does not include linting! Though we may switch to biome for linting in future for now we don't want to because it will not have many of the linting rules we currently have turned on via eslint. We only want to use biome format as a prettier replacement

## Tasks

- [ ] Add biome
- [ ] Remove prettier
- [ ] Configure biome so it is maximally equivalent to existing prettier formatting. Create smallest diff possible in the actual source code

**Comment by tynes** [comment]
I wonder what it would take to use biome for linting

**Comment by roninjin10** [comment]
We could use it for linting and I would actually recommend it. It does not have EVERY rule we have in our eslint config but it has all the ones that actually matter.

I personally use biome for linting and formatting on all projects these days and it's blazingly fast even on large monorepos
<img width="610" alt="image" src="https://github.com/ethereum-optimism/optimism/assets/35039927/872627b0-1749-4eb9-8cf9-666bcfc1d840">

**Comment by tynes** [comment]
I would def prefer removing eslint in favor of biome to reduce the number of deps that we depend on. If it has all the rules that matters, then I would be supportive of using it

**Comment by enjojoy** [comment]
Hey, I'd like to work on this issue, is that ok? :)

**Comment by AbhinavMir** [comment]
Hi @tynes ! Did some digging around, there are some rules which are simply unavailable. If there's a list of absolutely required ∩ unavailable rules, I could open a PR with biomejs and get it accepted or work off of a fork. Are there any such rules? I'd love to get this closed. :)
