### ISSUE TITLE
Issue Running DTL on Kovan

### ISSUE THREAD

**Issue by Enigmatic331** [ethereum-optimism/optimism#851]
**Describe the bug**
Kovan-V3 (or are we now on V4? Yikes sorry...) - Connected via https://kovan.optimism.io - blockhash 0xa809d5e7f682d232058675a00d676337d90ef0f6049c046b6d10b4a0e452a6f5 returns a transaction of gasPrice 0xf423f (999999), while the ecdsa-coder seeks out a gasPrice of a factor of 1,000,000 (https://github.com/ethereum-optimism/optimism/blob/develop/packages/core-utils/src/coders/ecdsa-coder.ts#L101)

**To Reproduce**
1. Start afresh, pull the master branch
2. Compile and configure the DTL, connecting to https://kovan.optimism.io with DATA_TRANSPORT_LAYER__SYNC_FROM_L2=true
3. Yarn start on the DTL package - The DTL will not be able to sync past the initial 1000 transactions 

Said transaction:
![image](https://user-images.githubusercontent.com/28551011/118017408-29510880-b389-11eb-9d19-0f100cf7b43f.png)

Screenshot of error:
![image](https://user-images.githubusercontent.com/28551011/118017281-00307800-b389-11eb-8bd4-0ef5553cbec2.png)

I could remove that check for now... But I'd prefer to defer to the experts... 🙇

**Comment by platocrat** [comment]
@Enigmatic331  We're currently pushing our recent changes to the `develop` branch, and leaving the `master` branch for production changes to Mainnet.

Could you see if this error is still received when using the `develop` branch?

**Comment by tynes** [comment]
It sounds like you have the wrong version of the DTL trying to sync kovan - try it with the version `v0.3.x`. Currently the minor versions are compatible with each other. The reason why its breaking is because the on chain serialization changed from v2 to v3

**Comment by platocrat** [comment]
@Enigmatic331 we're still on v3, v4 will come in the next regenesis, which we have not performed yet.

**Comment by smartcontracts** [comment]
> @Enigmatic331 we're still on v3, v4 will come in the next regenesis, which we have not performed yet.

I think the OP meant Kovan v3 and not `optimism@v0.3.0`.

**Comment by Enigmatic331** [comment]
This is what I've (re)tested amidst the craziness happening over at cryptotwitter earlier today:

- Develop branch: No go.
![image](https://user-images.githubusercontent.com/28551011/118078628-30a7fe80-b3e9-11eb-8712-7ec24388c5bd.png)

- 0.3.0rc (and Master): No go.
![image](https://user-images.githubusercontent.com/28551011/118078688-4c130980-b3e9-11eb-8b67-00af72112139.png)

Is there another branch I should try out?

Sorry if I am Greek with the versioning, will try to keep up. ❤️

**Comment by platocrat** [comment]
> > @Enigmatic331 we're still on v3, v4 will come in the next regenesis, which we have not performed yet.
> 
> I think the OP meant Kovan v3 and not `optimism@v0.3.0`.

I was referring to Kovan v3 as well 😛

**Comment by Enigmatic331** [comment]
Retried this today - Pulled from develop, nuked my previous build + reran - DTL seems to be running fine now.

Closing this and gonna go get Kovan all set up in full right away. :D Thanks a ton!

**Comment by Enigmatic331** [comment]
Ah was being overly zealous. With develop branch the replica data did not seem to match up with kovan.optimism.io (note blockhash with the blockNumber being 0x43):

![image](https://user-images.githubusercontent.com/28551011/118317209-5557bf80-b52a-11eb-89ff-4117afb6384b.png)

Am gonna take a step back first, get a couple hours forty winks and take a better look later in the morning, in case it's something obvious I'm missing...

**Comment by Enigmatic331** [comment]
Mark explained how the blockhashes are different - So that's a non-issue at the moment. Kovan is syncing fine now, am reviewing, should be good.
