### ISSUE TITLE
How can I identify which issue is not start yet?

### ISSUE THREAD

**Issue by JohnwickBC** [ethereum-optimism/optimism#8613]
Hi team, I appreciate it that you guys use issues to sync your work step and used it like milestone, I really want to do some help from these issue, but Im not sure the status of these issue. 
It will be perfect if I can know which is not start yet.

thanks!

**Comment by smartcontracts** [comment]
Generally it's best to look at Mission Requests or to look at anything tagged with `good-first-issue`.
