### ISSUE TITLE
Cannot find `op-stack-go:devnet` image when running local chain

### ISSUE THREAD

**Issue by boundless-forest** [ethereum-optimism/optimism#8614]
I want to run a local development environment following the https://docs.optimism.io/chain/testing/dev-node guide.  After typing `make devnet-up`, run into the error:

```sh
#15 [ops-bedrock_l2 internal] load metadata for us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:optimism
#15 CANCELED
------
 > [us-docker.pkg.dev/oplabs-tools-artifacts/images/op-proposer:devnet internal] load metadata for us-docker.pkg.dev/oplabs-tools-artifacts/images/op-stack-go:devnet:
------
failed to solve: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-stack-go:devnet: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-stack-go:devnet: not found
Traceback (most recent call last):
  File "/home/bear/coding/rust-space/optimism/./bedrock-devnet/main.py", line 9, in <module>
    main()
  File "/home/bear/coding/rust-space/optimism/./bedrock-devnet/main.py", line 5, in main
    devnet.main()
  File "/home/bear/coding/rust-space/optimism/bedrock-devnet/devnet/__init__.py", line 109, in main
    run_command(['docker', 'compose', 'build', '--progress', 'plain',
  File "/home/bear/coding/rust-space/optimism/bedrock-devnet/devnet/__init__.py", line 392, in run_command
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'compose', 'build', '--progress', 'plain', '--build-arg', 'GIT_COMMIT=5fb16e2fb07b25212c2b2ae08d246642240f9fd6', '--build-arg', 'GIT_DATE=1702436055']' returned non-zero exit status 17.
make: *** [Makefile:124: devnet-up] Error 1
```
It seems that there is no such an image called `op-stack-go:devnet` anymore in the https://console.cloud.google.com/artifacts/docker/oplabs-tools-artifacts/us/images. Any insight from the maintainers of this repo?

**Comment by sveitser** [comment]
I"m also affected. What seems even weirder to me is that building the missing image locally doesn't seem to help either.

Running the following from https://github.com/ethereum-optimism/optimism/blob/develop/CONTRIBUTING.md#building-the-rest-of-the-system

```
cd ops-bedrock
export COMPOSE_DOCKER_CLI_BUILD=1
export DOCKER_BUILDKIT=1
docker compose build
```
Leads to the same error as OP
```
...
 => => loading layer 2a3c70920cf9 196.61kB / 19.33MB                                                                                                                                     0.3s
 => [op-node internal] load build definition from Dockerfile                                                                                                                             0.2s
 => => transferring dockerfile: 464B                                                                                                                                                     0.0s
 => ERROR [op-node internal] load metadata for us-docker.pkg.dev/oplabs-tools-artifacts/images/op-stack-go:devnet                                                                        0.2s
------
 > [op-node internal] load metadata for us-docker.pkg.dev/oplabs-tools-artifacts/images/op-stack-go:devnet:
------
failed to solve: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-stack-go:devnet: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-stack-go:devnet: not found
```

Building the missing image locally with

```
docker compose build op_stack_go_builder
```
succeeds:
```
$ docker images|grep op-stack-go     
us-docker.pkg.dev/oplabs-tools-artifacts/images/op-stack-go   devnet            04ee7a199867   4 minutes ago   330MB
```

But I still get the same error when running `docker compose build`.

I think everyone who starts building now is affected. A colleague who seems to have downloaded the "existing but still not resolvable" image earlier is able to build.

**Comment by smartcontracts** [comment]
Hi, I noticed @opfocus created a PR in the docs repo to update things there. Do you get the same issue with the updated docs?

**Comment by boundless-forest** [comment]
Looks the PR linked in this issue. Seems not fix the issue.

**Comment by opfocus** [comment]
> Looks the PR linked in this issue. Seems not fix the issue.

Which commit and branch are you currently using

I don't have much knowledge about this. If it were me, I would probably first check for possible version issues with Docker Compose. Docker Engine [link](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) Compose [link](https://docs.docker.com/compose/install/linux/#install-the-plugin-manually).

**Comment by OCookman** [comment]
A temporary workaround is to go into the compose-file and update all references to us-docker.pkg.dev/oplabs-tools-artifacts/images/op-stack-go:devnet with a reference to your own image. 

E.g myDockerHubRepo/op-stack-go:devnet

The compose file is: https://github.com/ethereum-optimism/optimism/blob/develop/ops-bedrock/docker-compose.yml

**Comment by Vincent4AI** [comment]
why not use dockerhub

**Comment by Vincent4AI** [comment]
> why not use dockerhub

change to  rss3/op-stack-go:07317038d021591298ec2b237328d587e2fca93f
