### ISSUE TITLE
Too many predeploy proxies generated in genesis.json

### ISSUE THREAD

**Issue by drinkius** [ethereum-optimism/optimism#8616]
**Describe the bug**
When running the default own L2 deploy instructions found [here](https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#generate-the-l2-config-files), the genesis script generates 2048 proxies which in the end seem to be unused, the really needed ones are around 40 proxies corresponding to the predeploy addresses. If they are unneeded then it might be wise to lower the number of proxies generated

**To Reproduce**
1. Follow L2 [deploy instructions](https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup)
2. Check generated genesis.json file
3. See that it's over 9 megabytes

**Expected behavior**
If the proxies are indeed unused and this value was selected arbitrarily, it's better to lower it to a reasonable number, around 50, which would cover additional predeploy contracts that can be created in the near future. This can be done by changing the value found [here](https://github.com/ethereum-optimism/optimism/blob/6e371b4bc31b99f726f439da8b82186d2e084475/op-chain-ops/genesis/layer_two.go#L42):

`err = setProxies(db, predeploys.ProxyAdminAddr, BigL2PredeployNamespace, 2048)`

**Additional context**
This issue can be the cause for bloated genesis files on OP Stack rollups that are launched by many players in RaaS field, an already deployed example can be the Zora Mainnet, [here is the genesis.json](https://api.conduit.xyz/file/v1/optimism/genesis/zora-mainnet-0) they provide. I can provide a PR and run all the tests with the fix if needed

**Comment by tynes** [comment]
This is expected behavior. This allows for many new predeploys to be added by governance. We do not plan on reducing this number
