### ISSUE TITLE
pnpm build error

### ISSUE THREAD

**Issue by sameplacewei** [ethereum-optimism/optimism#8646]
**Describe the bug**
I am a beginner and I follow the [documentation](https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup) to build my own L2. When I run to the [location](https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#build-the-optimism-monorepo) ,run pnpm build , the following error occurs
        ✖  nx run @eth-optimism/contracts-bedrock:build
       > @eth-optimism/contracts-bedrock@0.16.2 prebuild /home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/packages/contracts-bedrock
       > ./scripts/verify-foundry-install.sh
       
       Using foundry version: forge 0.2.0 (3d6bfdd 2023-12-16T00:17:23.049683682Z)
       
       > @eth-optimism/contracts-bedrock@0.16.2 build /home/weizp/work/gows/src/github.com/ethereum-optimism/optimism/packages/contracts-bedrock
       > forge build
       
       Compiling 1 files with 0.5.17
       Compiling 324 files with 0.8.15
       Solc 0.5.17 finished in 38.99ms
       Compiling 129 files with 0.8.19
       Solc 0.8.19 finished in 14.24s
       Error: 
       solc exited with signal: 9 (SIGKILL)
       <empty output>
        ELIFECYCLE  Command failed with exit code 1.
       
       

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for 8 projects (4m)
 
    ✔    2/3 succeeded [2 read from cache]
 
    ✖    1/3 targets failed, including the following:
         - nx run @eth-optimism/contracts-bedrock:build
 
   View structured, searchable error logs at https://nx.app/runs/sOc3IaTMFk

**System Specs:**
 - OS:ubuntu 20.04
 - Package Version (or commit hash):8b39517e9b0c47e41f4c70b976fb2abbe20df5c1
other version
![1702715625843](https://github.com/ethereum-optimism/optimism/assets/33245656/55a856b4-d070-458e-a80b-2d2420cc27c9)

Can someone tell me why this error occurred? Thank you very much.

**Comment by sameplacewei** [comment]
The cause has been identified. Out of memory.
solc requires up to 12 G of memory.

**Comment by 69popovvlad** [comment]
Same error, but I allocated 20GB for the project

```
root@ubuntu:/mnt/volume_sfo3_01/optimism# pnpm build

> optimism@1.0.0 build /mnt/volume_sfo3_01/optimism
> npx nx run-many --target=build


    ✔  nx run @eth-optimism/core-utils:build  [existing outputs match the cache, left as is]
    ✔  nx run @eth-optimism/common-ts:build  [existing outputs match the cache, left as is]

    ✖  nx run @eth-optimism/contracts-bedrock:build
       > @eth-optimism/contracts-bedrock@0.16.2 prebuild /mnt/volume_sfo3_01/optimism/packages/contracts-bedrock
       > ./scripts/verify-foundry-install.sh

       Using foundry version: forge 0.2.0 (88ae503 2023-12-17T00:18:48.520002484Z)

       > @eth-optimism/contracts-bedrock@0.16.2 build /mnt/volume_sfo3_01/optimism/packages/contracts-bedrock
       > forge build

       Compiling 1 files with 0.5.17
       Compiling 323 files with 0.8.15
       Solc 0.5.17 finished in 63.82ms
       Compiling 127 files with 0.8.19
       Solc 0.8.19 finished in 298.54s
       Error:
       solc exited with signal: 9 (SIGKILL)
       <empty output>
        ELIFECYCLE  Command failed with exit code 1.



 ——————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for 8 projects (5m)

    ✔    2/3 succeeded [2 read from cache]

    ✖    1/3 targets failed, including the following:
         - nx run @eth-optimism/contracts-bedrock:build

   View structured, searchable error logs at https://nx.app/runs/HwtY3Ac3Nt

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by 69popovvlad** [comment]
Environment
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic

Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        87G  6.8G   80G   8% /

Dependency | Minimum | Actual
git          2         2.40.1
go           1.21      1.21.5
node         20        20.10.0
pnpm         8         8.12.1
foundry      0.2.0     0.2.0
make         3         4.3
jq           1.6       1.6
direnv       2         2.32.1
```

Commit:
```
commit eb0d89ddaa57e6335d92dfa379f6036847c5cc18 (HEAD, tag: op-proposer/v1.4.0-rc.1, tag: op-node/v1.4.0, tag: op-batcher/v1.4.0)
Author: Joshua Gutow <jgutow@oplabs.co>
Date:   Mon Dec 11 14:34:53 2023 -0800

    op-node: Activate Delta on testnets
```

Commands used before error:
```
git clone https://github.com/ethereum-optimism/optimism.git
cd optimism
git checkout op-node/v1.4.0
pnpm install
make op-node op-batcher op-proposer
pnpm build
```

Error:
```

> optimism@1.0.0 build /root/optimism
> npx nx run-many --target=build


    ✔  nx run @eth-optimism/core-utils:build  [existing outputs match the cache, left as is]
    ✔  nx run @eth-optimism/common-ts:build  [existing outputs match the cache, left as is]

    ✖  nx run @eth-optimism/contracts-bedrock:build
       > @eth-optimism/contracts-bedrock@0.16.2 prebuild /root/optimism/packages/contracts-bedrock
       > ./scripts/verify-foundry-install.sh

       Using foundry version: forge 0.2.0 (477b345 2023-12-18T00:22:09.434601489Z)

       > @eth-optimism/contracts-bedrock@0.16.2 build /root/optimism/packages/contracts-bedrock
       > forge build

       Compiling 1 files with 0.5.17
       Compiling 323 files with 0.8.15
       Solc 0.5.17 finished in 47.93ms
       Compiling 127 files with 0.8.19
       Solc 0.8.19 finished in 276.81s
       Error:
       solc exited with signal: 9 (SIGKILL)
       <empty output>
        ELIFECYCLE  Command failed with exit code 1.



 ——————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for 8 projects (5m)

    ✔    2/3 succeeded [2 read from cache]

    ✖    1/3 targets failed, including the following:
         - nx run @eth-optimism/contracts-bedrock:build

   View structured, searchable error logs at https://nx.app/runs/OabAAeY9az

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by smartcontracts** [comment]
Thanks for the report. Going to look into this.

**Comment by 69popovvlad** [comment]
@smartcontracts 
This is my mistake, I thought 12GB of disk space, but it was said about RAM.
This is of course inconvenient for a build on a dedicated server, but I got it done. Thank you

**Comment by smartcontracts** [comment]
I was able to build correctly with a docker container with 8gb ram

```
root@c3ef57f59f63:/optimism# free
               total        used        free      shared  buff/cache   available
Mem:         8032524      808036     5546772        2620     1677716     6873572
Swap:        1048572       80472      968100
```

Going to try a dedicated server with 8gb ram to see what happens

**Comment by smartcontracts** [comment]
@mslipper says this is a "known issue" with the solidity compiler when compiling many files at the same time. Going to see if foundry can potentially address this by limiting the number of files per compiler run.

**Comment by SquilliamX** [comment]
> I was able to build correctly with a docker container with 8gb ram
> 
> ```
> root@c3ef57f59f63:/optimism# free
>                total        used        free      shared  buff/cache   available
> Mem:         8032524      808036     5546772        2620     1677716     6873572
> Swap:        1048572       80472      968100
> ```
> 
> Going to try a dedicated server with 8gb ram to see what happens

I am getting this issue as well an I only have 8GB of memory, how did you get it to build?

**Comment by pegahcarter** [comment]
@smartcontracts @mslipper I am getting the same issue when trying to build the contracts locally (8GB ram):

```
carter@laptop:~/optimism/packages/contracts-bedrock$ forge build
Missing dependencies found. Installing now...

...

[⠆] Compiling...
[⠰] Compiling 16 files with Solc 0.8.19
[⠔] Compiling 394 files with Solc 0.8.15
[⠰] Compiling 138 files with Solc 0.8.25
[⠢] Solc 0.8.19 finished in 2.79s
[⠊] Solc 0.8.25 finished in 35.60s
Error: 
solc exited with signal: 9 (SIGKILL)
```

Is there a way around this?

**Comment by prey801** [comment]
![Image](https://github.com/user-attachments/assets/b9f0ba49-11d9-45aa-b70a-27efc8ab1d26)
anyone who got this error and knows how to fix it i tried  online i  couldn't find  how to fix it just explanation of what it implies
