### ISSUE TITLE
`getLastSequencerTimestamp` returns zero after deployment

### ISSUE THREAD

**Issue by gigamesh** [ethereum-optimism/optimism#876]
Currently, `getLastSequencerTimestamp` returns zero after deployment. This isn't accurate/useful. 

Mark is thinking we should set `_lastSequencerTimestamp` to block.timestamp in the constructor of the state commitment contract.

**Comment by snario** [comment]
Likely going to hold off on the contract code changes for this due to circular dependency complexity

**Comment by smartcontracts** [comment]
Honestly I think this behavior makes sense. Sequencer hasn't submitted any transactions, so the timestamp is zero. We can just handle this edge-case on the front-end if we really care about it.
