### ISSUE TITLE
Put the Optimism dockers on a registry

### ISSUE THREAD

**Issue by qbzzt** [ethereum-optimism/optimism#888]
**Is your feature request related to a problem? Please describe.**

In the tutorial there are a number of time consuming steps that are necessary to create the docker images for running Optimism:

> git clone https://github.com/ethereum-optimism/optimism.git
> cd optimism
> yarn install
> yarn build
> cd ops
> docker-compose build

This is a slow process, and it hurts the developer's experience. Most of us don't want to deal with Optimism internals, any more than we need to see how the compiler we use is built. We just want to use the tools to build our own thing.

This is particularly problematic because it's something that happens extremely early in the process, possibly when a developer is still thinking whether to use Optimism or some other competing mechanism. People are impatient, and it's best to accomodate that if we want them to use our stuff.

**Describe the solution you'd like**

Have the Optimism team run a script somewhere that creates the images and then uploads them to a registry. Rerun as needed (when there is a major update, an important bug fix, or a security vulnerability fix).

**Additional context**

Originally posted in https://github.com/ethereum-optimism/optimism-tutorial/issues/35, @smartcontracts told me it's better to put it here.

**Comment by gakonst** [comment]
They're already there: http://hub.docker.com/r/ethereumoptimism/

**Comment by qbzzt** [comment]
Thank you. I'll submit a pull request to update the tutorial later today.

**Comment by tynes** [comment]
Since the `latest` images are not published and the tags are not specified in the `docker-compose.yml`, you can't do a `docker-compose pull` to pull the images. The config file will need to be edited with the exact tags

**Comment by qbzzt** [comment]
> Since the `latest` images are not published and the tags are not specified in the `docker-compose.yml`, you can't do a `docker-compose pull` to pull the images. The config file will need to be edited with the exact tags

Is there a reason not to have tags, either `latest` or a more modest `known-to-work`?

**Comment by qbzzt** [comment]
> Since the `latest` images are not published and the tags are not specified in the `docker-compose.yml`, you can't do a `docker-compose pull` to pull the images. The config file will need to be edited with the exact tags

Another possibility is to use the current tags. Do you keep old versions on the hub, or delete them?

**Comment by gakonst** [comment]
Older versions are going to be kept around, so it's safe to use them!
