### ISSUE TITLE
Get frame_data failed on sepolia by L2 Chain Derivation Specification.

### ISSUE THREAD

**Issue by liucan163** [ethereum-optimism/optimism#8882]
I attempted to parse the frame_data from the input of a Batcher Transaction, and ultimately retrieved the data using zlib.inflateSync. This process works successfully on the mainnet, but fails to parse the input on the testnet. Could you please explain the differences between the mainnet and testnet that might impact this logic?

https://github.com/ethereum-optimism/optimism/blob/v1.1.4/specs/derivation.md#eager-block-derivation
![image](https://github.com/ethereum-optimism/optimism/assets/145973583/747d6237-1e92-4670-825c-6168c10df29d)

https://etherscan.io/tx/0x4eb0b76a7b55e66399729dc77e9baa0857ac614e7670dbd4176d151c1e1e3167
https://sepolia.etherscan.io/tx/0x68f305520fee621b015b0999a4d536cecefedd9594f613f5ead107d79db33731

**Comment by liucan163** [comment]
const decompressChannel = async (frameData) => {
    const maxOutputLength = 10_000_000
    const channelCompressed = Buffer.concat([frameData])
    return zlib.inflateSync(channelCompressed, { maxOutputLength: 10_000_000 })
  }
"Error: unexpected end of file, code: 'Z_BUF_ERROR'"

**Comment by tynes** [comment]
span batches are on testnet - https://github.com/ethereum-optimism/optimism/blob/develop/specs/span-batches.md

**Comment by liucan163** [comment]
Thank you very much. Are you suggesting that the method of batch submission from the L2 to L1 on the testnet has changed?

**Comment by tynes** [comment]
That batch serialization has changed

**Comment by liucan163** [comment]
Is there a method for reverse parsing the latest batch serialization scheme, ultimately allowing the extraction of the L2 transaction hash?

**Comment by pcw109550** [comment]
You may use the batch decoder supporting span batch introduced at https://github.com/ethereum-optimism/optimism/pull/8416. Refer to https://github.com/ethereum-optimism/optimism/tree/develop/op-node/cmd/batch_decoder.

The tool fetches L1 transactions, reassembles frames, extract channels, and decode/derive L2 transactions. 

In your case, however, you need a transaction hash. We do not write L2 transaction hash to L1, rather, the info to recover the entire transaction itself. If you extract channels, you will find list of L2 transactions which is in RLP form. You can keccak them to get L2 tx hashes.

**Comment by pcw109550** [comment]
If you need hashes for deposit tx, you may need to use L1 event logs. Please refer to the [derivation specs](https://github.com/ethereum-optimism/optimism/blob/develop/specs/derivation.md).

**Comment by liucan163** [comment]
Ok, thanks, I will take a look!

**Comment by varasev** [comment]
@liucan163 Have you resolved the issue somehow? I also cannot decompress the frame data after Delta upgrade of the network. The same error: `unexpected end of file`
