### ISSUE TITLE
SDK update 3.1.7 broke estimateTotalGasCost

### ISSUE THREAD

**Issue by maxklenk** [ethereum-optimism/optimism#8890]
**Describe the bug**
The lastest SDK release introduced a bug in its fix https://github.com/ethereum-optimism/optimism/pull/8836 
The[ `estimateTotalGasCost`](https://github.com/ethereum-optimism/optimism/blob/develop/packages/sdk/src/l2-provider.ts#L133) function calls internally the updated `estimateL1GasCost` function and `estimateL2GasCost` function. While the first one does not allow a `from` address the second one requires a `from` address to work. 

**To Reproduce**
1. Call `estimateTotalGasCost` with a valid transaction including a from address (e.g. a simple approval)
```json
{
  "data":"0x095ea7b30000000000000000000000001231deb6f5749ef6ce6943a275a1d3e7486f4eaeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
  "to":"0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85",
  "from":"0x56F19F4F9A4cbd98C222bB5A79B9255CD4d9D0B0",
}
```
2. The call fails with
```
invalid object key - from (argument=\"transaction:from\", value={\"data\":\"0x095ea7b30000000000000000000000001231deb6f5749ef6ce6943a275a1d3e7486f4eaeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\",\"to\":\"0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85\",\"from\":\"0x56F19F4F9A4cbd98C222bB5A79B9255CD4d9D0B0\",\"nonce\":0}, code=INVALID_ARGUMENT, version=properties/5.7.0)
```

**Expected behavior**
The estimate should return a valid BigNumber which combines both l1 and l2 gas costs.

**Additional context**
I would recommend that `estimateL1GasCost` is updated again to omit the `from` address and any other parameters that are not allowed (e.g. `maxFeePerGas`) so it can be called with any transaction again.

**Comment by smartcontracts** [comment]
Opened a PR to fix this

**Comment by maxklenk** [comment]
@smartcontracts thanks for looking into the issue. Sadly the update does not really solve the issue, now other arguments are required, e.g. `maxFeePerGas`.
