### ISSUE TITLE
Optimism node synchronization is very slow, and the official has not yet provided a snapshot

### ISSUE THREAD

**Issue by zhy827827** [ethereum-optimism/optimism#8950]
As the title suggests

op-geth version:v1.101304.2
op-node version: v1.4.0

```
op-geth \
  --ws \
  --ws.port=9994 \
  --ws.addr=0.0.0.0 \
  --ws.origins="*" \
  --http \
  --http.port=9993 \
  --http.addr=0.0.0.0 \
  --http.vhosts="*" \
  --http.corsdomain="*" \
  --authrpc.addr=0.0.0.0 \
  --authrpc.jwtsecret=/opt/secrets/jwt.txt \
  --authrpc.port=8551 \
  --authrpc.vhosts="*" \
  --ws.api=debug,eth,txpool,net,engine,web3 \
  --http.api=web3,debug,eth,txpool,net,engine \
  --datadir=/opt/op-geth \
  --verbosity=3 \
  --rollup.disabletxpoolgossip=true \
  --rollup.sequencerhttp=https://mainnet-sequencer.optimism.io \
  --nodiscover \
  --syncmode=full \
  --gcmode=full \
  --txlookuplimit 0 \
  --maxpeers=0
```

```
op-node --l1=http://127.0.0.1:8545 \
        --l2=http://127.0.0.1:8551  \
	--network=mainnet \
	--l1.trustrpc \
        --rpc.addr=0.0.0.0 \
        --rpc.port=9545 \
	--l1.rpckind=basic \
        --l2.jwt-secret=/opt/secrets/jwt.txt \
```

op-geth logs:

INFO [01-11|03:33:33.700] Chain head was updated                   number=111,968,152 hash=0c998f..e305fa root=a47128..27b9ba elapsed="173.043µs" age=2mo2d14h

##I have been syncing for a month now, but I still diff 3 million block from the main network

how to fix this issues!

**Comment by eldimious** [comment]
Any idea how can we fix this one? cause we are facing same issue

**Comment by smartcontracts** [comment]
Fastnode provides some snapshots. I have not verified the validity of the snapshots but they should work for you for now. Snap sync is also coming soon. https://datapoint.fastnode.io/

**Comment by tynes** [comment]
snap sync works in prod now
