### ISSUE TITLE
Transaction receipt contractAddress populated on failed contract creation

### ISSUE THREAD

**Issue by elenadimitrova** [ethereum-optimism/optimism#899]
**Describe the bug**
Create contract transactions that fail have a transaction receipt which contains a non-null value for `contractAddress` receipt property. This is the case when no contract was actually created. This behaviour is inconsistent with the EVM which returns null if contract instantiation fails.

This behavior was noticed when a contract deployment failed because of out-of-gas rather than other constructor failures which have not been tested for the presence of this sympthom. 

**Expected behavior**
`contractAddress` should be null in addition to the remaining symptoms of a failed contract creation, including `status = 0`, available revert error message etc.

**Comment by smartcontracts** [comment]
Are you sure this should be `null`? Upstream geth seems to set the `ContractAddress` no matter what: https://github.com/ethereum/go-ethereum/blob/154ca32a8ade0a7d2461d0eb432361261a51a395/core/state_processor.go#L124-L126

**Comment by elenadimitrova** [comment]
@gakonst confirmed it although you might be right as when looking at specific contract creation failures they all output a `contractAddress`, some real world examples below:

Contract creation execution failure
https://kovan.etherscan.io/tx/0xde2e85f2705f54075f03bb9fe73b7e301ca6632e10a9eb3619e989c681e5936b

Contract creation inner `delegatecall` failure
https://ropsten.etherscan.io/tx/0x6c71a83593223de24c665978ce23bd1bee0b7e4cff98707728e88a360bbe5768
https://ropsten.etherscan.io/tx/0x14750f58c5a9f03d1f805430263d3822fbe1ad2eb02ebbb5c69de9d5f137f739

Contract creation running out of gas
https://ropsten.etherscan.io/tx/0x96346a2f0084f3078e7a957eb1d4bdc6799ae3d01678554311624d7013ca2c33

Closing for now @gakonst can reopen if there's something I've overlooked.
