### ISSUE TITLE
Improve error message for empty payload (payload with zero transactions)

### ISSUE THREAD

**Issue by mattsse** [ethereum-optimism/optimism#8993]
**Is your feature request related to a problem? Please describe.**

https://github.com/ethereum-optimism/optimism/blob/f2229b8b955e53408be0775a22d7f9f162b0de66/op-node/rollup/derive/engine_queue.go#L663-L666

This error can also occur if the payload is empty (deposit txs == 0)

https://github.com/ethereum-optimism/optimism/blob/f2229b8b955e53408be0775a22d7f9f162b0de66/op-node/rollup/derive/engine_queue.go#L654-L654

whether a payload with zero transactions only contains deposit txs, is semantics. But imo it would be more clear to have a different error for this case.

**Describe the solution you'd like**
check if depositCount is 0 and adjust the error message

**Describe alternatives you've considered**
-
**Additional context**
This was highlighted by an op-reth bug:
![telegram-cloud-photo-size-5-6132094275480043498-y](https://github.com/ethereum-optimism/optimism/assets/19890894/95208484-c0c4-4226-be44-07bfdfac1bad)

**Comment by tynes** [comment]
Looks like this is no longer necessary
