### ISSUE TITLE
op-conductor: Dencun ExecutionPayloadEnvelope change

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#9064]
Update server-side and client-side RPC usage of posting payloads to use the execution payload envelope.

The Dencun change implemented this server-side, but may have broken more unknown client-side calls of the RPC method.
See https://github.com/ethereum-optimism/optimism/pull/8707

**Comment by protolambda** [comment]
Created this to track any necessary changes here, cc @0x00101010

**Comment by 0x00101010** [comment]
Done by https://github.com/ethereum-optimism/optimism/pull/9106, can close now

**Comment by ajsutton** [comment]
Reopening as there's still a TODO for this issue:

```
[Error]: Issue #9064 is closed. Please remove the TODO in op-node/node/api.go:74 referencing ethereum-optimism/optimism#9064 (https://github.com/ethereum-optimism/optimism/issues/9064)
```
