### ISSUE TITLE
Add L2Geth endpoint `rollup_getEncodedGasLimit`

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/optimism#907]
**Is your feature request related to a problem? Please describe.**
Folks want the ability to determine the encodedGasLimit for their transactions given a specific actualGasLimit.

Terminology refresher:
- `actualGasLimit` = amount of gas which must be provided to execute the transaction.
- `encodedGasLimit` = `fee + actualGasLimit`

**Describe the solution you'd like**
Add a L2Geth endpoint `rollup_getEncodedGasLimit` which accepts:

- Input:
  - `transaction` following EIP155 where `gasLimit` is provided & equals `actualGasLimit`.
- Output:
  - `encodedGasLimit` - calculated using the formulas outlined in: https://github.com/ethereum-optimism/optimism/issues/823

**Comment by karlfloersch** [comment]
@K-Ho would love if you could fill in any missing details or context here!

**Comment by K-Ho** [comment]
Don't need, replacing instead with a js tool to `getEncodedGasLimit(l1GasPrice, txCalldata, l2ExecutionPrice, l2GasLimit, scalar)`
