### ISSUE TITLE
Regression on data-transport-layer metrics

### ISSUE THREAD

**Issue by optimisticben** [ethereum-optimism/optimism#910]
**Describe the bug**
From the current develop branch tip, the `dtl` service in the docker-compose project build returns a 404 for `/metrics`.

**To Reproduce**
1. git checkout develop
2. git pull
3. cd ops
4. docker-compose up --build --detached
5. curl -v http://127.0.0.1:7878/metrics

That's giving me a 404. If we go back to https://github.com/ethereum-optimism/optimism/commit/e6350e2e25d8271aeded5ee414ca37ff633678fa it seems to work fine.

1. git checkout e6350e2e25d8271aeded5ee414ca37ff633678fa
2. cd ops
3. docker-compose up --build --detached
4. curl -v http://127.0.0.1:7878/metrics

I'm not sure if I need to add any settings now that we updated the common-ts for metrics in https://github.com/ethereum-optimism/optimism/commit/0c1680533c870efed3e5335f53c03996413daf4e

**Expected behavior**
The curl request should return a list off metrics and values like:
```
$ curl http://127.0.0.1:7878/metrics
# HELP L1_Data_Transport_Serviceprocess_cpu_user_seconds_total Total user CPU time spent in seconds.
# TYPE L1_Data_Transport_Serviceprocess_cpu_user_seconds_total counter
L1_Data_Transport_Serviceprocess_cpu_user_seconds_total 17.375885

# HELP L1_Data_Transport_Serviceprocess_cpu_system_seconds_total Total system CPU time spent in seconds.
# TYPE L1_Data_Transport_Serviceprocess_cpu_system_seconds_total counter
L1_Data_Transport_Serviceprocess_cpu_system_seconds_total 3.836926

# HELP L1_Data_Transport_Serviceprocess_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE L1_Data_Transport_Serviceprocess_cpu_seconds_total counter
L1_Data_Transport_Serviceprocess_cpu_seconds_total 21.212811000000002
...
```

]

**Comment by smartcontracts** [comment]
Do you know if this config option is being set? https://github.com/ethereum-optimism/optimism/blob/10d29f06cd44a1294037a3ec202374092a462a66/packages/data-transport-layer/src/services/server/service.ts#L109

I'd assume the environment variable would have to be `DATA_TRANSPORT_LAYER_ETH_NETWORK_NAME` as per: https://github.com/ethereum-optimism/optimism/blob/10d29f06cd44a1294037a3ec202374092a462a66/packages/data-transport-layer/src/services/run.ts#L22

**Comment by optimisticben** [comment]
> Do you know if this config option is being set?

It was not, setting this worked!
```
DATA_TRANSPORT_LAYER__ETH_NETWORK_NAME: local
```

Notice the double `_`, not sure why thats required, but the other env name had it too.

I guessed on "local", either that's a good guess, or any setting will enable the metrics route?

**Comment by tynes** [comment]
The double underscore is not required but is still parsed correctly by `bcfg`

**Comment by tynes** [comment]
A side effect of an unrelated named environment variable shouldn't be enabling metrics - we should be sure to enable metrics with something like `DATA_TRANSPORT_LAYER_ENABLE_METRICS`
