### ISSUE TITLE
Node behind the tip

### ISSUE THREAD

**Issue by tmeinlschmidt** [ethereum-optimism/optimism#9101]
Hi,

we're experiencing node being behind the tip for cca 200secs, it looks like waves - going up to 200-220secs (last block timestamp vs actual datetime), then it quickly sync up. 

is that a feature or I can improve our config? Using latest 1.4.2 op-node.

```
      --network=op-mainnet
      --rpc.addr=0.0.0.0
      --rpc.port=<port>
      --p2p.disable
      --l1=<l1 url>
      --l2=<l2 url>
      --l2.jwt-secret=/shared/jwt.txt
      --l1.max-concurrency 20
      --l1.rpc-max-batch-size 60
      --l1.http-poll-interval 1s
      --l1.epoch-poll-interval 60s
      --p2p.peers.hi 50
```

tried to play with `max-concurrency` and the rest, no effect.

node: 128G RAM, NVME, 32 cores AMD EPYC 7371

Thanks
tom

**Comment by smartcontracts** [comment]
What chain is this for?

**Comment by ajsutton** [comment]
You're disabling gossip with:
```
      --p2p.disable
```
so will not receive unsafe heads and thus only update the chain from data from L1. The batcher has up to 12 hours to submit data to L1 so this is much higher latency. If you remove that option you should start tracking the unsafe head correctly.

Also for future reference these kinds of user support queries are better directed to the discussions forum: https://github.com/ethereum-optimism/developers/discussions

**Comment by tmeinlschmidt** [comment]
thanks!
