### ISSUE TITLE
op-node failed to get receipts from L1

### ISSUE THREAD

**Issue by wangjiangw** [ethereum-optimism/optimism#9170]
**Describe the bug**
In my environment, the node can't get block receipts from L1 node, which caused the L2 block can't be confirmed. once the node restart, it will take long time to recover.

the error log 
![image](https://github.com/ethereum-optimism/optimism/assets/7013043/802dd4d8-c795-4567-96ff-1db67781e5a0)

op-node version : v1.4.0

**Additional context**
the L1 node has not been changed in restart period.

**Comment by tynes** [comment]
This is a bug with your remote node likely

**Comment by wangjiangw** [comment]
> This is a bug with your remote node likely

@tynes yes，i have found it, because i use two eth nodes backup, i think when new block comes, op-node query latest block in node 1 while query receipts in node 2, if node 2 has no latest block, getBlockReceipts will return null，this may be the root cause for this problem, will you consider this situation ?

**Comment by tynes** [comment]
This is not something that we will fix within `op-node` as it adds extra complexity in consensus critical code. `op-node` assumes a consistent RPC

**Comment by smartcontracts** [comment]
Closing as wontfix for the moment, reducing the critical code within `op-node` is worth making some assumptions about upstream RPC consistency.
