### ISSUE TITLE
Integration tests timing out when running using yarn test:integration

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimism#922]
**Describe the bug**

When I run the integration tests locally, all the before hooks time out on me.

ie. 
```
       "before all" hook for "should read transfer events from a proxy ERC20":
     Error: Timeout of 100000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/primary/Projects/O/monorepo-one/integration-tests/test/read-proxy-event.spec.ts)
```

**To Reproduce**
This currently seems to be isolated to my machine, but I'm recording for posterity. Here's what I'm doing:

First, I'm testing on [this commit](https://github.com/ethereum-optimism/optimism/commit/5b7e13c671c97892566e824499bf823108cccdde), since it was working in CI just fine.

This works:
1. `cd ops`
2. `docker-compose up -d`
3. `docker-compose run integration_tests`
4. All tests pass. 

The following does not work:
1. `cd ops`
2. `docker-compose up -d`
3. `cd ../integration-test`
4. `yarn test:integration`
5. The timeout error pasted above eventually appears.

**System Specs:**
 - OS: MacOs BigSur
 - Package Version (or commit hash): 5b7e13c671c97892566e824499bf823108cccdde

**Observations**

* The fact that all 8 test files have the same failure indicates, and it's in the before all hook tell us that it must be something common to all of them. The only common step across all of them is the call to [`await OptimismEnv.new()`](https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/integration-tests/test/fee-payment.spec.ts#L12).
* Within that operation, the location of the timeout is specifically happening on this funduser step:

https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/integration-tests/test/shared/env.ts#L61

* The logs for `l2geth` sometimes include this message shortly after the `fundUser` call starts:
`l2geth_1 | DEBUG[05-19|17:53:17.652] Reached the end of an OVM execution ID=f9bea6be Return Data=0x000000000000000000000000defa017defa017defa017defa017defa017defa0 Error=nil`
* Unfortunately they sometimes don't seem to include that error.

**Comment by maurelian** [comment]
Adding this as a comment, since I'm not sure it's relevant or not: 

Given that the issue does not occur when running the`integration_tests` service, that might be instructive. I noticed in the Dockerfile:

https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/ops/docker/Dockerfile.integration-tests#L25-L27

That it copies this script which ends with an `npx hardhat` command: 

https://github.com/ethereum-optimism/optimism/blob/5b7e13c671c97892566e824499bf823108cccdde/ops/scripts/integration-tests.sh#L26

However that command is not run in the Dockerfile. Instead the entrypoint is `yarn test:integration`, which ( unlike the command in `integration-tests.sh`) is simply `hardhat --network optimism test`.


2:03
which ends with npx hardhat test --network optimism --no-compile
2:03
but then it doesn’t run it, and runs yarn test:integration instead.
2:03
which is hardhat --network optimism test … at least in  ./integration-tests/package.json

**Comment by maurelian** [comment]
Another observation. Once again I'm running on the same commit hash above (for which all checks pass in CI):

I paid closer attention to the results of the `docker-compose run integration_tests`, and I see that there are actually 3 test _cases_ failing (though not in the 'before all' hook). These cases all involve the `withdraw` step: 

```
  1) Native ETH Integration Tests
       withdraw:
     Error: Timeout of 100000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/opt/optimism/integration-tests/test/native-eth.spec.ts)
      at listOnTimeout (internal/timers.js:555:17)
      at processTimers (internal/timers.js:498:7)

  2) Native ETH Integration Tests
       withdrawTo:
     Error: Timeout of 100000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/opt/optimism/integration-tests/test/native-eth.spec.ts)
      at listOnTimeout (internal/timers.js:555:17)
      at processTimers (internal/timers.js:498:7)

  3) Native ETH Integration Tests
       deposit, transfer, withdraw:
     Error: Timeout of 100000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/opt/optimism/integration-tests/test/native-eth.spec.ts)
      at listOnTimeout (internal/timers.js:555:17)
      at processTimers (internal/timers.js:498:7)
```

**Comment by smartcontracts** [comment]
@maurelian I'm unable to reproduce your initial issue on my local machine. Were you able to reproduce after running `yarn clean && yarn build`?

**Comment by maurelian** [comment]
Yes it persists after clean and build. 

I have had the most progress with `docker system prune --all`

**Comment by maurelian** [comment]
I just had my first fully successful run of integration tests. This is what I did: 
1. Create a new commit checking in the yarn.lock updates that were created but not checked in by some ancestral commit
2. `docker system prune --all --volumes`
2. `yarn clean` (in root and integration-tests dirs)
2. `yarn && yarn build` and yarn && yarn build:integrations`
3. `yarn test:integration` 

I don't know which of those steps is or is not required, but aside from number 2, I will likely repeat them out of pure superstition should I end up in this situation again.

**Comment by platocrat** [comment]
> I just had my first fully successful run of integration tests. This is what I did:
> 
> 1. Create a new commit checking in the yarn.lock updates that were created but not checked in by some ancestral commit
> 2. `docker system prune --all --volumes`
> 3. `yarn clean` (in root and integration-tests dirs)
> 4. `yarn && yarn build` and yarn && yarn build:integrations`
> 5. `yarn test:integration`
> 
> I don't know which of those steps is or is not required, but aside from number 2, I will likely repeat them out of pure superstition should I end up in this situation again.

Step 2 should _generally_ not be required if you're always running `docker-compose down -v` after you shut down the running containers. Same as Step 2.

The only times I re-run `docker system prune -a` and `yarn clean` is after pulling recent changes.

**Comment by maurelian** [comment]
I have resolved my issues. First I had to upgrade my docker engine to a new version with better support for the M1 chip. 

Following that, these are the steps that always reliably work for me. Some of them may not be strictly required, but for now I am playing it safe as it's faster to go slow and get the right docker images built:

From the root: 
```
yarn clean
yarn build
cd integration-tests
yarn build:integration
cd ../ops
docker-compose down
docker-compose build -- builder deployer
docker-compose up -d
cd ../integration-tests
yarn test:integration
```
