### ISSUE TITLE
There is no problem with the setting of the transaction broadcast fee, but the transaction does not go up the chain.

### ISSUE THREAD

**Issue by zelonH** [ethereum-optimism/optimism#9227]
broadcasttime 2024-01-29 08:37:50.710

0x02f8760a831128d58411e1a3008502540be400830249f094b4472c3d895ee11a13137dd74331cad3ccdbe494877c58508723800080c001a077b9966ce1bb30ebf092ad53cf9bec75a1a4596b0b55187e55e56a12ad2abce3a0080dda7f2b3446e9f6affd716920d4ef5eff4c41fd61793b46de4b2368968168

0x596f42c732caf27c0e37bb74f9cb59fcf6275cfb5c074b52df285d97cd76567b

oker@okerdeMacBook-Pro golandProject % curl -X POST  https://rpc.ankr.com/optimism --data '{
  "jsonrpc": "2.0",
  "id": "1",
  "method": "eth_sendRawTransaction",
  "params": [ "0x02f8760a831128d58411e1a3008502540be400830249f094b4472c3d895ee11a13137dd74331cad3ccdbe494877c58508723800080c001a077b9966ce1bb30ebf092ad53cf9bec75a1a4596b0b55187e55e56a12ad2abce3a0080dda7f2b3446e9f6affd716920d4ef5eff4c41fd61793b46de4b2368968168" ]
}' -H "Content-Type: application/json"
{"jsonrpc":"2.0","id":"1","error":{"code":-32000,"message":"already known"}}%
![image](https://github.com/ethereum-optimism/optimism/assets/25896081/db7a2780-b558-4fb5-bfc2-943ab42ace97)

**Comment by zelonH** [comment]
Please help me look into this problem. This situation has been happening frequently recently.

**Comment by smartcontracts** [comment]
@sbvegan can this be moved to the developer support repo?

**Comment by zelonH** [comment]
> @sbvegan can this be moved to the developer support repo?

@smartcontracts @sbvegan  I discussed this issue with @sbvegan. He said that it was a configuration issue with the upstream op-geth txpool.accountslots, which caused the transaction to be discarded. However, why the discarded transaction was rebroadcast is already known. It is not clear yet. Please help me take a look.
