### ISSUE TITLE
Panic when unmarshalling devnet allocs file

### ISSUE THREAD

**Issue by ImTei** [ethereum-optimism/optimism#9271]
**Describe the bug**
In the current develop branch([`9a59811f51`](https://github.com/ethereum-optimism/optimism/tree/9a59811f53960e0fae39a1c7cbcc25c3dfc808e6)), the type of `nonce` is string hexadecimal in the generated devnet l1 alloc file (`.devnet/allocs-l1.json`). It makes panic when trying to run any e2e test, with the following message.
```
panic: cannot unmarshal dump: json: cannot unmarshal string into Go struct field DumpAccount.accounts.nonce of type uint64

goroutine 1 [running]:
github.com/ethereum-optimism/optimism/op-e2e/config.init.0()
	/Users/tei/tip-optimism/op-e2e/config/init.go:93 +0x730
exit status 2
```

The content of the `.devnet/allocs-l1.json`:
```
...
  "accounts": {
    "0x2abb7cbb720020ee3c9ecf3915d14b6d1886a577": {
      "nonce": "0x2",
      "balance": "0x0",
      "code": "0x60806040523...",
      "storage": {
        "0x0000000000000000000000000000000000000000000000000000000000000000": "0x0000000000000000000000006153107879eb0f3743b33091206fd2946833c35b"
      }
    },
...
```

**To Reproduce**
1. Checkout the latest develop branch (`9a59811f51`)
2. Rebuild everything (following `CONTRIBUTING.md`)
3. Generate devnet alloc file (following `op-e2e/README.md`)
4. Run e2e test (e.g. `go test -run TestOutputCannonGame` in `op-e2e/faultproofs`)

**Expected behavior**
The type of nonce must be an integer, or the code can unmarshal hex string.

**System Specs:**
 - OS: macOS Sonoma 14.3 (M1 pro)
 - Package Version (or commit hash): `9a59811f51`

**Comment by tynes** [comment]
We have encountered this issue in https://github.com/ethereum-optimism/optimism/pull/9313

It looks like its related to the foundry version. Likely due to an alloy migration internal to forge

**Comment by tynes** [comment]
db7f837ed20807444fb7659eb209dfc7b2f29947 is an attempt to fix this
