### ISSUE TITLE
critical rollup parameters should be read from L1

### ISSUE THREAD

**Issue by zhiqiangxu** [ethereum-optimism/optimism#9273]
Parameters like [`ChannelTimeout`](https://github.com/ethereum-optimism/optimism/blob/c874ecc9f195b340d9cb3ae6dc9f8f9731254e1e/op-node/rollup/types.go#L66) will affect the derivation result, but now it's directly read from local instead of from L1.

It's like missing some constraints in zk circuits, probably will cause trouble for dispute, since different setting of `ChannelTimeout` may cause the data frame treated differently(valid or ignored).

**Comment by tynes** [comment]
They are constant values as part of the chainspec, similar to how L1 has constant values as part of its chainspec. They could be read from L1 but the do not need to be. They are not meant to be dynamic values. I do think that the config should use default values if they are not present in the config

**Comment by zhiqiangxu** [comment]
I see, maybe better to classify the fields of rollup config into mutable and immutable then.

**UPDATE**

Well, it seems not, these constants are supposed to be reflected in the `faultGameAbsolutePrestate`, right? But `faultGameAbsolutePrestate` is now hardcoded no matter what values constants like `ChannelTimeout` are set to.

This may not be a problem for official instances of OP stack, but I suspect it may become a *critical* problem for private deployments.

**Comment by tynes** [comment]
We would definitely like to move as much config on chain as possible. Things that are committed to in the absolute prestate will need an entry in the superchain registry with the value hardcoded there or a fork of the software. We will move more things on chain over time. We are discussing the next hardfork here: https://github.com/ethereum-optimism/specs/discussions/241
