### ISSUE TITLE
failed to fetch L1 head for runtime config initialization

### ISSUE THREAD

**Issue by nitantchhajed** [ethereum-optimism/optimism#9280]
My op-stack chain was running smoothly since last 2 months, it stopped yesterday. what is the reason behind it ?? and how to fix it

these are the op-node logs -

![image](https://github.com/ethereum-optimism/optimism/assets/96972634/2680b70f-61c3-483d-84f4-c52a3ca5df93)

**Comment by tynes** [comment]
Be sure to update to the latest releases of the software that support the ecotone hardfork

**Comment by nitantchhajed** [comment]
@tynes so should I create new docker image for my op-node by using latest release, and replace it with the current op-node docker image ? 

Ps- It is my op-stack chain with L1 as sepolia. Using release v1.30

**Comment by smartcontracts** [comment]
Yeah, need to use the latest op-node because Sepolia was updated to support 4844
