### ISSUE TITLE
cannot estimateGas on ETH value sends 

### ISSUE THREAD

**Issue by K-Ho** [ethereum-optimism/optimism#930]
**Describe the bug**
When sending eth value, we want users to `estimateGas` to get the encoded gasLimit to send their tx with. However, we currently do not allow calling `estimateGas` with no data: https://github.com/ethereum-optimism/optimism/blob/8d67991aba584c1703692ea46273ea8a1ef45f56/l2geth/internal/ethapi/api.go#L1024-L1026

**To Reproduce**
Try calling estimateGas with no calldata.

**Expected behavior**
We can call estimateGas when sending a transaction with ETH value 

**Additional Context**
It's unclear whether this integration test will set the `gasLimit` to 21,000 by default or if it does call `estimateGas` https://github.com/ethereum-optimism/optimism/blob/dcb538d459940a021c580ec33e96a663a972ee49/integration-tests/test/rpc.spec.ts#L102

**Comment by K-Ho** [comment]
This was reported by Metamask, I have not yet confirmed. I would confirm by checking the gasLimit that is set in this test (https://github.com/ethereum-optimism/optimism/blob/dcb538d459940a021c580ec33e96a663a972ee49/integration-tests/test/rpc.spec.ts#L102) and seeing if it is set via `estimateGas` (meaning this issue was a false alarm) or if it is set by ethers to be 21000, in which case this issue could still exist.

**Comment by gakonst** [comment]
We were not hitting this error before because we hard-code the [gasLimit](https://github.com/ethereum-optimism/optimism/blob/dcb538d459940a021c580ec33e96a663a972ee49/integration-tests/test/rpc.spec.ts#L22).
