### ISSUE TITLE
Disable EIP1559 on L1

### ISSUE THREAD

**Issue by sbarratt** [ethereum-optimism/optimism#9330]
**Is your feature request related to a problem? Please describe.**
I am trying to deploy the op stack on a chain that doesn't have EIP-1559 functionality (block basefee).
Is there an easy way to turn this off in the op-stack?

**Describe the solution you'd like**
I would like an argument or config that turns EIP-1559 functionality off, or an implementation of op-geth without EIP-1559 functionality.

**Describe alternatives you've considered**
I see mustBePostMerge, but changing that to false didn't initially work.

**Additional context**
On the command
```
go run cmd/main.go genesis l2 \
  --deploy-config ../packages/contracts-bedrock/deploy-config/getting-started.json \
  --deployment-dir ../packages/contracts-bedrock/deployments/getting-started/ \
  --outfile.l2 genesis.json \
  --outfile.rollup rollup.json \
  --l1-rpc $L1_RPC_URL
```
I get the error
```
message="error creating l2 genesis: block base fee not set"
```

**Comment by ajsutton** [comment]
The OP Stack is built on the assumption of working from a merged Ethereum chain which includes EIP1559.  There's a fair bit of functionality around calculating the L1 fees to charge transactions which depends on the concept of base fee.
