### ISSUE TITLE
Centralized node balance query delay problem

### ISSUE THREAD

**Issue by zelonH** [ethereum-optimism/optimism#9348]
For example, I transferred some coins from address A to address B, and then used address B to transfer, but the result was an error message of insufficient funds.  I confirmed that the coins have been transferred to address B.，It takes multiple attempts to broadcast later to succeed.

zhenlong han, [Feb 4, 2024 at 14:16:42]:
This scenario is quite extreme. This problem occurs when I transfer and receive coins and then immediately go to trade.

OP Mainnet Transaction Hash (Txhash) Details | Optimism
OP Mainnet detailed transaction info for txhash 0x495a91663e7f9a948430790f52e43ea2892bfa30c100a2ae131b779b77614394. The transaction status, block confirmation, gas fee, ETH, and token transfer are shown.

https://optimistic.etherscan.io/tx/0x495a91663e7f9a948430790f52e43ea2892bfa30c100a2ae131b779b77614394

{
  "nonce": 0,
  "gasLimit": 150000,
  "to": "0x7f5c764cbc14f9669b88837ca1490cca17c31607",
  "value": 0,
  "data": "a9059cbb000000000000000000000000ebe80f029b1c02862b9e8a70a7e5317c06f62cae00000000000000000000000000000000000000000000000000000000fb881700",
  "maxFeePerGas": 200000000,
  "maxPriorityFeePerGas": 100000000,
  "pubkey": "d91f12da46d5b12193567ca4f68b393fbbf00c1f831db04c8af813f4e933832998a21c1498312119f799cd4689f561abe0b1e8a3db7e9c1c9618eecde00430fa",
  "from": "0x37760cd9532645877f1cd967dcb2c38f83e14db4",
  "hash": "0x495a91663e7f9a948430790f52e43ea2892bfa30c100a2ae131b779b77614394",
  "r": "0xc1788e481db9e7a2fed333ca765c70931cc19ff915881b981ba2d870cffd40d4",
  "v": "0x01",
  "s": "0x7cf0f8f9bf9dab9bea328c50fd13e40fcfe9b338c97d883d2935c294bfff91b7"
}

**Comment by smartcontracts** [comment]
What RPC provider are you using?

**Comment by zelonH** [comment]
> What RPC provider are you using?

- "--rollup.sequencerhttp=https://mainnet-sequencer.optimism.io"
-

**Comment by smartcontracts** [comment]
Are you running your own node?

**Comment by zelonH** [comment]
> Are you running your own node?

Yes, we run our own nodes, but our sequencer configuration is this

**Comment by smartcontracts** [comment]
I believe transactions are not applied to the local pending state, so you have to wait for the block that includes your transaction to be gossiped to you from the Sequencer. This can take several seconds after the transaction gets sent, you won't see the balance update immediately. How much of a delay are you observing?

**Comment by zelonH** [comment]
It feels like about a minute or so, and you can check the transaction that was successfully retried.

**Comment by tynes** [comment]
This is an unsafe block latency issue that we can optimize for in the future
