### ISSUE TITLE
Hardhat ethers does not correctly instantiate a provider with the OVM

### ISSUE THREAD

**Issue by shanefontaine** [ethereum-optimism/optimism#935]
**Describe the bug**
Using Hardhat's built-in ethers object does not correctly instantiate a provider using the OVM. Because of this, you cannot perform tasks like deploying a contract.

This only happens when `ovm: true` is set in hardhat.config.js.

**To Reproduce**
1. Clone [this](https://github.com/shanefontaine/optimism-tutorial) forked repo of the optimism-tutorial
2. Follow the README instructions to run the deployment
3. Observe that the deployment does not work and produces the following error `Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.1.2)`
4. In `deploy/ERC20.deploy.js`, comment out [lines 11-12](https://github.com/shanefontaine/optimism-tutorial/blob/main/deploy/ERC20.deploy.js#L11-L12) (Hardhat ethers instantiation) and comment in [lines 6-8](https://github.com/shanefontaine/optimism-tutorial/blob/main/deploy/ERC20.deploy.js#L6-L8) (native ethers instantiation).
5. Run the deployment again and observe that the contract gets deployed.

**Expected behavior**
I would expect the Hardhat ethers implementation to work the same as the native ethers implementation when deploying a contract.

**System Specs:**
All relevant packages are in the [forked repo](https://github.com/shanefontaine/optimism-tutorial).

**Additional context**
Another way to verify that the provider is not working correctly is by inserting `await ethers.provider.ready` and observing that the script execution never passes that line.

**Comment by shanefontaine** [comment]
It looks like the issue may be [this](https://github.com/ethereum-optimism/optimism/blob/68871b7a9e0989a7b126e800ab1b6b19edab2293/packages/hardhat-ovm/src/index.ts#L251) line in @eth-optimism/hardhat-ovm.

When running the script, I see that `hre.ethers.provider.url` is `undefined`. If I switch it to `hre.network.config.url` instead, everyting appears to work as expected.

**Comment by platocrat** [comment]
> It looks like the issue may be [this](https://github.com/ethereum-optimism/optimism/blob/68871b7a9e0989a7b126e800ab1b6b19edab2293/packages/hardhat-ovm/src/index.ts#L251) line in @eth-optimism/hardhat-ovm.
> 
> When running the script, I see that `hre.ethers.provider.url` is `undefined`. If I switch it to `hre.network.config.url` instead, everyting appears to work as expected.
> 
> Edit: it appears as though unexpected signers are used when this line is changed, so maybe this is not a fix.

Hey @shanefontaine, I just went through your repro steps and didn't see any issues with Hardhat ethers deployment. 
Both HH and native ethers deployments ran in the same fashion.

So, I'm sure why you're getting this error.
cc: @smartcontracts

**Comment by smartcontracts** [comment]
Ok I was able to reproduce this! Taking a look.

**Comment by smartcontracts** [comment]
I think this should fix: https://github.com/ethereum-optimism/optimism/pull/938

**Comment by gakonst** [comment]
@shanefontaine #938 should address this issue, could you please confirm that Kelvin's fix was correct? Thank you for reporting.

**Comment by shanefontaine** [comment]
It appears as though that has fixed the provider issue. I am still seeing odd Signer behavior. Specifically, the array of private keys I am using for `accounts` in `hardhat.config.ts` is seemingly ignored.

I believe #946 may resolve this specific issue. @miguelmota (author of that PR) has been debugging this with me.
