### ISSUE TITLE
Add checks to DisputeGameFactory deployment

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/optimism#9354]
DisputeGameFactory gets deployed in the current deploy scripts but does not have a corresponding checkDisputeGameFactory function, this needs to be added.

**Comment by smartcontracts** [comment]
@clabby what checks actually need to happen here? It's not super clear to me

**Comment by clabby** [comment]
Closing this as a duplicate issue: https://github.com/ethereum-optimism/client-pod/issues/529
