### ISSUE TITLE
Generate contract artifacts fails with missing null.json file

### ISSUE THREAD

**Issue by 0x70626a** [ethereum-optimism/optimism#9427]
**Describe the bug**
I am following the steps in the `Creating your own L2 Rollup Testnet` document and have an error at "Generate contract artifacts" - https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#deploy-the-l1-contracts

**To Reproduce**

`forge script scripts/Deploy.s.sol:Deploy --sig 'sync()' --rpc-url $L1_RPC_URL`

returns the following output:

<img width="1599" alt="image" src="https://github.com/ethereum-optimism/optimism/assets/99218061/fc4a51da-e43e-430c-a833-4da9e7821081">

**System Specs:**
 - See required tools and versions:
<img width="583" alt="image" src="https://github.com/ethereum-optimism/optimism/assets/99218061/6eac8977-a192-49d5-a5e5-669a0ab41fc9">

 - OS: Apple M1 Max, macOS Sonoma, v14.2.1
 - Package Version (or commit hash): https://github.com/ethereum-optimism/optimism/tree/tutorials/chain

**Additional context**

**Comment by smartcontracts** [comment]
Are you using `develop`? Please make sure to use the `tutorials/chain` branch which trails `develop` because `develop` gets updated frequently. This is mentioned in the [Build the Optimism Monorepo](https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#build-the-optimism-monorepo) section of the tutorial but maybe needs to be made more obvious.

**Comment by 0x70626a** [comment]
Yes, I made sure to checkout the correct branch, see below 

<img width="1665" alt="image" src="https://github.com/ethereum-optimism/optimism/assets/99218061/927bebee-8607-47a5-a271-68957bf9c277">

**Comment by smartcontracts** [comment]
Strange, will look into this...

**Comment by 0x70626a** [comment]
I installed the latest (nightly) build of Foundry, is the missing file `null.sol` part of that package? 
<img width="929" alt="image" src="https://github.com/ethereum-optimism/optimism/assets/99218061/41a18a7b-ccc6-4f59-ba80-08bf35c69bdb">

**Comment by smartcontracts** [comment]
Can you try `pnpm update:foundry`? That will install the version of foundry used in that branch. Once you update, try `pnpm clean` then `pnpm build` again and rerun the deploy script.

**Comment by 0x70626a** [comment]
Something's not right with the version in the repo `9e2830d7f0566e0d00b1104eeaedd5032a4e556e`. Keeps erroring out with this when I try `pnpm update:foundry` or `foundryup -C 9e2830d7f0566e0d00b1104eeaedd5032a4e556e`

<img width="1217" alt="image" src="https://github.com/ethereum-optimism/optimism/assets/99218061/91b6ef71-4ff7-464c-a912-568da523fb15">

Doesn't happen with the nightly builds `foundryup -v nightly-293fad73670b7b59ca901c7f2105bf7a29165a90`

**Comment by smartcontracts** [comment]
Can you try using version `84d9842`? I just used that version on a clean install for the tutorial and it seemed to work.
