### ISSUE TITLE
cantina-MCP-L1-review: Inconsistent version updates

### ISSUE THREAD

**Issue by 0xfuturistic** [ethereum-optimism/optimism#9491]
Context: [L2CrossDomainMessenger.sol#L18-L19](https://github.com/ethereum-optimism/optimism/blob/e6ef3a900c42c8722e72c2e2314027f85d12ced5/packages/contracts-bedrock/src/L2/L2CrossDomainMessenger.sol#L18-L19), [L1CrossDomainMessenger.sol#L23-L25](https://github.com/ethereum-optimism/optimism/blob/e6ef3a900c42c8722e72c2e2314027f85d12ced5/packages/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L23-L25)

Description: The reviewed MCP L1 upgrade doesn't assume backward incompatible changes. Indeed, the changes made in [L1CrossDomainMessenger](https://github.com/ethereum-optimism/optimism/blob/e6ef3a900c42c8722e72c2e2314027f85d12ced5/packages/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L15), [L2CrossDomainMessenger](https://github.com/ethereum-optimism/optimism/blob/e6ef3a900c42c8722e72c2e2314027f85d12ced5/packages/contracts-bedrock/src/L2/L2CrossDomainMessenger.sol#L17), and [CrossDomainMessenger](https://github.com/ethereum-optimism/optimism/blob/e6ef3a900c42c8722e72c2e2314027f85d12ced5/packages/contracts-bedrock/src/universal/CrossDomainMessenger.sol#L87) didn't break backward compatibility.

However, L1CrossDomainMessenger and L2CrossDomainMessenger received different version updates:

L1CrossDomainMessenger was [updated from 2.2.0 to 2.3.0](https://github.com/ethereum-optimism/optimism/commit/e6ef3a900c42c8722e72c2e2314027f85d12ced5#diff-758b0324563ef5a12c2a621194fc988535939aba35f80f43f30c36c0c8f5affdL25-R25) (a minor update).
L2CrossDomainMessenger was [updated from 1.9.0 to 2.0.0](https://github.com/ethereum-optimism/optimism/commit/e6ef3a900c42c8722e72c2e2314027f85d12ced5#diff-a05e63d94979f621f79dd9dd22c9efb7f7033bbe460410a5fe55199b962a2ffbL18-R19) (a major update).
As a result, the upgrade will signal an incorrect version update, which may impact third-party integrations and off-chain tools.

Recommendation: In L2CrossDomainMessenger, consider setting version to 1.10.0.

**Comment by mds1** [comment]
Chatted with @maurelian and this will not break anything. We don't want to downgrade the semver after a release, so we'll just stick with the major version bump and close this issue
