### ISSUE TITLE
cantina-MCP-L1-review: Resource config values can be modified during the MCP L1 upgrade

### ISSUE THREAD

**Issue by 0xfuturistic** [ethereum-optimism/optimism#9494]
Context: [l1.go#L728](https://github.com/ethereum-optimism/optimism/blob/e6ef3a900c42c8722e72c2e2314027f85d12ced5/op-chain-ops/upgrades/l1.go#L728)

Description: The deployment process implemented in the op-chain-ops/upgrades/l1.go file is intended to carry over the values of the removed immutable variables to their mutable counterparts. Additionally, the process sets values of newly added variables (e.g. [SystemConfig's stratBlock](https://github.com/ethereum-optimism/optimism/blob/e6ef3a900c42c8722e72c2e2314027f85d12ced5/op-chain-ops/upgrades/l1.go#L625-L629)). If the initialization of a contract requires setting variables that were not part of the MCP L1 upgrade, their values are carried over without modification (e.g. [the SystemConfig settings](https://github.com/ethereum-optimism/optimism/blob/e6ef3a900c42c8722e72c2e2314027f85d12ced5/op-chain-ops/upgrades/l1.go#L669-L697)).

However, the resource config of SystemConfig is set to the default value during the upgrade of the contract ([l1.go#L728](https://github.com/ethereum-optimism/optimism/blob/e6ef3a900c42c8722e72c2e2314027f85d12ced5/op-chain-ops/upgrades/l1.go#L728)):

```
calldata, err := systemConfigABI.Pack(
	"initialize",
	finalSystemOwner,
	gasPriceOracleOverhead,
	gasPriceOracleScalar,
	batcherHash,
	l2GenesisBlockGasLimit,
	p2pSequencerAddress,
	genesis.DefaultResourceConfig, // @audit sets default values
	chainConfig.BatchInboxAddr,
	bindings.SystemConfigAddresses{
		L1CrossDomainMessenger:       common.Address(list.L1CrossDomainMessengerProxy),
		L1ERC721Bridge:               common.Address(list.L1ERC721BridgeProxy),
		L1StandardBridge:             common.Address(list.L1StandardBridgeProxy),
		L2OutputOracle:               common.Address(list.L2OutputOracleProxy),
		OptimismPortal:               common.Address(list.OptimismPortalProxy),
		OptimismMintableERC20Factory: common.Address(list.OptimismMintableERC20FactoryProxy),
	},
)
```
The resource config of a SystemConfig can have values that differ from the default ones as a result of a call to [SystemConfig.setResourceConfig()](https://github.com/ethereum-optimism/optimism/blob/e6ef3a900c42c8722e72c2e2314027f85d12ced5/packages/contracts-bedrock/src/L1/SystemConfig.sol#L339).

As a result, the upgrade can modify the resource config of a deployed SystemConfig contract. The resource config represents the configuration for the EIP-1559 based curve for the deposit gas market. Unintentional modification of the values can impact the gas metering of deposits of an OP chain.

Recommendation: In the [upgrades.SystemConfig()](https://github.com/ethereum-optimism/optimism/blob/e6ef3a900c42c8722e72c2e2314027f85d12ced5/op-chain-ops/upgrades/l1.go#L612) function, consider reading the current values of the SystemConfig's resource config and carrying them over to the initialize() function call.

**Comment by t-maker564** [comment]
why are you putting these findings here ?

**Comment by 0xfuturistic** [comment]
@mds1 asked me to since the cantina repo is private and not everyone at optimism has access. also serves as backup in case the cantina repo gets deleted

**Comment by t-maker564** [comment]
you do know that others will report these ?

**Comment by 0xfuturistic** [comment]
moved to https://github.com/ethereum-optimism/client-pod/issues/575

**Comment by t-maker564** [comment]
yep but some findings are out of scope only few contracts are in scope
