### ISSUE TITLE
Create the ChugSplash CLI deployment tool

### ISSUE THREAD

**Issue by annieke** [ethereum-optimism/optimism#951]
The ChugSplash CLI tool is the last piece in the ChugSplash puzzle. This tool needs to compose all of the features we've built to make ChugSplash possible. The tool only needs to have a single command for this ticket: `chugsplash deploy`. This command takes the following arguments:

- `node endpoint`
- `deployer address`
- `private key`
- `github url`
- `commit hash or tag`
- `build command`
- `path to contract artifacts`
- `path to chugsplash config file`

We then need to use these parameters to perform the following actions:

1. Connect to `node endpoint`
2. Connect to `deployer address`
3. Create a wallet instance with `private key`
4. Clone `github url`
5. Check out `commit hash or tag`
6. Run `build command`
7. Extract artifacts from `path to contract artifacts`
8. Extract config file from `path to chugsplash config file`
9. Use config file and artifacts to build the chugsplash upgrade bundle
10. Wait for the bundle to be approved
11. Execute each action in the bundle

We should take care to design this tool so that steps [1-9] can easily be extracted and reused for other ChugSplash-related tasks (e.g., generating bundle parameters to sign).

**Describe alternatives you've considered**

First iteration is described in https://github.com/ethereum-optimism/optimism/issues/708, which we're pivoting from since ChugSplash is moving into its own package. 

**Additional context**
Re-using code from https://github.com/ethereum-optimism/optimism/pull/855

**Comment by smartcontracts** [comment]
Going to close this out, we'll reopen ChugSplash-related issues once we start work on it again.
