### ISSUE TITLE
Add Deposit / Withdrawal Integrity Tester

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/optimism#959]
**Is your feature request related to a problem? Please describe.**
We have found that a majority of our bugs come from the connection between L1 and L2. This is where we have the most moving parts. Specifically we encounter the following errors:

1. Deposits are double played.
2. Deposits are skipped.

We would like to be able to perform (load) tests which catch these sorts of issues.

**Describe the solution you'd like**
Create an L1 contract which sends messages into L2 that makes it really easy to track if messages were skipped, double played, or generally delayed.

The message sent from L1 to L2 should contain the following information:
- `index`
- `initiatedTimestamp`
- `initiatedBlockNumber`

When the deposit is received in L2, the following information about the deposit should be stored in an append only array:
- `index`
- `initiatedTimestamp`
- `initiatedBlockNumber`
- `receivedTimestamp`
- `receivedBlockNumber`

By storing this information, we can iterate over the list of deposits and check to see if:

1. Any are double played
2. Any are skipped
3. Any were ingested at a timestamp that is != to the timestamp that the deposit was received in. Note `initiatedTimestamp` and `receivedTimestamp` should always be equal.

We should then add an integration test which demonstrates this contract's functionality -- performing a deposit & verifying its integrity. This contract & test can then be used inside of a load test which will make it easy to detect if deposits were double played or skipped.

**Alternate Solution**
Submit any deposit and scan the Geth's blockchain (`eth_getBlockByNumber`) and determine if there were any deposits that were either skipped or double played. The benefit of this approach is that it can also be used to detect monotonicity failures which we should also write tests around.

**Comment by karlfloersch** [comment]
@K-Ho do you have a WIP implementation of this? Would be great to link it!

**Comment by karlfloersch** [comment]
We may want to extend this or create another issue to similarly write a contract which will help us track withdrawals.

**Comment by K-Ho** [comment]
First pass - was on the old integration tests though so will need a re-factor: https://github.com/ethereum-optimism/integration-tests/pull/58/files

**Comment by snario** [comment]
What is the advantage of using this contract based testing approach as opposed to one which is inspecting `geth` directly?

**Comment by karlfloersch** [comment]
> What is the advantage of using this contract based testing approach as opposed to one which is inspecting `geth` directly?

When we originally scoped this out it felt simpler to have the contract store the relevant metrics that we want to keep track of vs doing a O(n) search through all the blocks to detect anomalies. I'm personally not opinionated about which is better & would lean towards whatever is easier.

One benefit of doing the integrity checks on Geth's entire blockchain (not using the contract) is that it might be easier to slot in the monotonicity checks as well. Might end up being a more flexible approach though I think also depends on the overall architecture of the load tests. I'll add this as an alternative solution.

**Comment by smartcontracts** [comment]
We have stress tests now that check for this sort of stuff. We haven't had any of these issues since 11/11. I don't think we'll be able to do much better than that until bedrock (when this will be less of a concern). I think we can safely close this issue.
