### ISSUE TITLE
 undefined: params.ProtocolVersionV0

### ISSUE THREAD

**Issue by iteyelmp** [ethereum-optimism/optimism#9622]
Import the latest v1.6.1 package, the compilation prompts "undefined: params.ProtocolVersionV0"
<img width="1048" alt="image" src="https://github.com/ethereum-optimism/optimism/assets/6647261/b9324519-4b4c-4b32-af1a-fe691655df22">

In addition, the go-etherum package was also forced to upgrade, resulting in many log-related conflicts.

**Comment by protolambda** [comment]
Stale issue, closing. Looks like dependencies there were not updated. A simple `go mod tidy` would fix that. Or in Intellij (the IDE from screenshot): "sync dependencies" correction on imports or within `go.mod` file.
