### ISSUE TITLE
`ProxyAdmin.sol` is not two-step

### ISSUE THREAD

**Issue by pegahcarter** [ethereum-optimism/optimism#9639]
**Is your feature request related to a problem? Please describe.**
The `ProxyAdmin` is, I believe, one of the most crucial pieces within the OP Stack.  That being said, transferring ownership for the `ProxyAdmin` is only a single step.  So, as soon as the ownership transfer tx is submitted, the `ProxyAdmin` owner is changed.

This can be an issue for several reasons:
- There's always the possibility of fat-finger ownership transfer to an unintended recipient (which may or may not have control over their PK).
- The fact that the `ProxyAdmin` can be changed and modify all controlled contracts within the same tx is quite uneasing.

**Describe the solution you'd like**
I suggest using OZ's [Ownable2Step](https://docs.openzeppelin.com/contracts/5.x/api/access#Ownable2Step) to further solidify ownership transfer.  With this module, ownership is not transferred *until* the recipient accepts the transfer.  Therefore:
- It is impossible to accidentally transfer `ProxyAdmin` ownership.
- Ownership transfer and controlled contract execution is impossible within the same transaction as there needs to be a transaction by the owner to submit ownership transfer, and a second tx for the recipient to accept.

I'm not sure if this can be done with the current `ProxyAdmin` on OP mainnet and live  Superchains.  At the minimum, it's worth adding for future OP Stack buidlers.

**Comment by tynes** [comment]
I agree that using an `Ownable2Step` is a great idea. We do want to move in this direction but it would require a bunch of tooling updates for management of OP Mainnet. We use [this](https://github.com/ethereum-optimism/superchain-ops) repo for these sorts of upgrades. We are currently focused on shipping fault proofs and use simulation + state diff assertions to ensure that ownership transfers happen safely

**Comment by pegahcarter** [comment]
Is there a template / public-facing repository the OP team generally uses for fault proofs and state diff assertions that OP-stack teams can use?

**Comment by tynes** [comment]
See [this](https://github.com/ethereum-optimism/optimism/blob/3179d49f1cdbf7cea384544f250b4762a43222f1/packages/contracts-bedrock/scripts/Deploy.s.sol#L104) for an example of generating a state diff. [superchain-ops](https://github.com/ethereum-optimism/superchain-ops) contains a [template](https://github.com/ethereum-optimism/superchain-ops/tree/main/tasks/templates/00-default) for gnosis safe multisig operations

Fault proofs are not live yet but you can follow along with their progress in this repo

**Comment by pegahcarter** [comment]
@tynes are the fault proofs to show that proxy storage stays the same?  I'm looking for something like hardhat's [`validateUpgrade`](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#validate-upgrade).
