### ISSUE TITLE
Sending to portal implementation leads to frozen funds.

### ISSUE THREAD

**Issue by pegahcarter** [ethereum-optimism/optimism#9710]
**Bug Description**
The Optimism Portal operates through a front-facing proxy with implementation. When a user wants to manually send ETH to Optimism mainnet, they send the ETH to the proxy contract. From there, Optimism reads events from the proxy to mint ETH for the user on L2.

As Optimism reads events from the Portal proxy, any transactions sent directly to the implementation will not be seen. Specifically, the `TransactionDeposited()` event that is emitted on `depositTransaction()` will never be picked up by Optimism.

In addition, a user should be able to withdraw from the L2 to the implementation directly. However, the user is unable to replay the transaction with `proveWithdrawalTransaction()` as the implementation is paused.

**Impact Details**
This impacts all OP-stack chains as none of the implementations revert on receiving assets.  I stumbled upon this by sending ETH to the Fraxtal portal implementation:
https://etherscan.io/address/0x59b6903044fa9439a5d621d3605789a6e654b1d6

**Expected behavior**
- Balance transfers to L2
OR
- tx reverts on L1 

**Potential Solutions**
- Add a paused check to the implementation for `receive()`
- Have `receive()` revert if `(address(this) == implementation)`
- Additionally revert for non-ETH based OP-stack chains if transferring the chain native token to the implementation.

**Comment by tynes** [comment]
Interacting with the implementation of the portal will never result in a balance transfer to L2. It would break the idea of being able to upgrade the contracts. It could be possible to have the tx revert on L1 if calling the implementation directly, this is a footgun for users. Pretty easy to implement `(address(this) == implementation)` where `implementation` is an `immutable` and set in the constructor

**Comment by pegahcarter** [comment]
Exactly.
