### ISSUE TITLE
Proposal to increase maxSequencerDrift to 30 minutes

### ISSUE THREAD

**Issue by henridevieux** [ethereum-optimism/optimism#9739]
**Is your feature request related to a problem? Please describe.**
A `maxSequencerDrift` of 600s is very limiting for resolving L1 node issues.

**Describe the solution you'd like**
The Base team proposes raising the `maxSequencerDrift` to 1800s. This could be included in the upcoming Fjord hard fork

**Describe alternatives you've considered**
<n/a>

**Additional context**

**Comment by tynes** [comment]
Please open an issue or pull request to the [specs](https://github.com/ethereum-optimism/specs) repo to discuss this kind of thing. To have this seriously considered, you will need to provide more detail, including security considerations

**Comment by henridevieux** [comment]
Will re-open with more detail in the specs repo
