### ISSUE TITLE
Docs: Create L2 Rollup Demo - failed to init L2: incorrect L2 RPC chain id 1, expected 42069

### ISSUE THREAD

**Issue by blmalone** [ethereum-optimism/optimism#9752]
**Bug Description**

Failing at step 3 of ['Start Op Node'](https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#start-op-node)

After following through the [documentation](https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup): I'm running into the following error.

[Line in codebase](https://github.com/ethereum-optimism/optimism/blob/eac79900756b78374893b2a88e034f9d60d91fd7/op-node/rollup/types.go#L210)

Was the `eth_chainId` updated in this test to be 1?

```
INFO [03-05|17:31:34.859] Not opted in to ProtocolVersions signal loading, disabling ProtocolVersions contract now.
INFO [03-05|17:31:34.860] No persisted sequencer state loaded
INFO [03-05|17:31:34.860] Rollup Config                            l2_chain_id=42069 l2_network="unknown L2" l1_chain_id=11,155,111 l1_network=sepolia l2_start_time=1,709,673,312 l2_block_hash=0x5746de1aa18a7b68a7df895b67d6324c7c2b5fedf42a055a955edcaf0012f570 l2_block_number=0 l1_block_hash=0xbf8c2691038c3bac147d4fda7d1c4f16f8a27de28743aa1309e5fbc369bc2217 l1_block_number=5,424,053 regolith_time="@ genesis" canyon_time="@ genesis" delta_time="(not configured)" ecotone_time="(not configured)" fjord_time="(not configured)" interop_time="(not configured)"
INFO [03-05|17:31:34.860] Initializing rollup node                 version=v0.0.0-a06cae81-1705510057
WARN [03-05|17:31:35.096] No beacon endpoint configured. Configuration is mandatory for the Ecotone upgrade
ERROR[03-05|17:31:35.102] Error initializing the rollup node       err="failed to init L2: incorrect L2 RPC chain id 1, expected 42069"
CRIT [03-05|17:31:35.102] Application failed                       message="failed to setup: unable to create the rollup node: failed to init L2: incorrect L2 RPC chain id 1, expected 42069"
```

**Steps to Reproduce**

Followed the demo to step 3 of the section titled `Start Op-Node`.

**Expected behavior**

Expected the op-node to boot successfully on my local machine.

**Environment Information:**
 - Operating System: MacOS 14.2.1
 - Package Version (or commit hash): [a06cae81ed60c85d1566f48f45d9f9c0e48cc47c](https://github.com/ethereum-optimism/optimism/commit/a06cae81ed60c85d1566f48f45d9f9c0e48cc47c) - Branch: [tutorials/chain](https://github.com/ethereum-optimism/optimism/tree/tutorials/chain)

Configuration files that were generated as part of the setup:

- [getting-started.json](https://github.com/ethereum-optimism/optimism/files/14502396/getting-started.json)
- [genesis.json](https://github.com/ethereum-optimism/optimism/files/14502390/genesis.json)
- [rollup.json](https://github.com/ethereum-optimism/optimism/files/14502374/rollup.json)

**Comment by tynes** [comment]
However you are configuring your `op-node`, the RPC is pointing to mainnet when it should be pointing to the local L2 node

**Comment by blmalone** [comment]
**Resolved:**

I was able to get it working. I deleted the `datadir`, imported the `genesis.json` file manually then ran the `op-geth` node. At that point you'll notice the logs show the correct chainId: 

```
INFO [03-06|11:45:03.662] ---------------------------------------------------------------------------------------------------------------------------------------------------------
INFO [03-06|11:45:03.662] Chain ID:  42069 (unknown)
INFO [03-06|11:45:03.662] Consensus: Optimism
```

Whereas before it was defaulting the Chain ID to `1`, mainnet. 

**Steps to fix:** 

```
cd op-geth

rm -rf datadir

./build/bin/geth \
  --datadir ./datadir \
  --http \
  --http.corsdomain="*" \
  --http.vhosts="*" \
  --http.addr=0.0.0.0 \
  --http.api=web3,debug,eth,txpool,net,engine \
  --ws \
  --ws.addr=0.0.0.0 \
  --ws.port=8546 \
  --ws.origins="*" \
  --ws.api=debug,eth,txpool,net,engine \
  --syncmode=full \
  --gcmode=archive \
  --nodiscover \
  --maxpeers=0 \
  --networkid=42069 \
  --authrpc.vhosts="*" \
  --authrpc.addr=0.0.0.0 \
  --authrpc.port=8551 \
  --authrpc.jwtsecret=./jwt.txt \
  --rollup.disabletxpoolgossip=true \
  init genesis.json

./build/bin/geth \
  --datadir ./datadir \
  --http \
  --http.corsdomain="*" \
  --http.vhosts="*" \
  --http.addr=0.0.0.0 \
  --http.api=web3,debug,eth,txpool,net,engine \
  --ws \
  --ws.addr=0.0.0.0 \
  --ws.port=8546 \
  --ws.origins="*" \
  --ws.api=debug,eth,txpool,net,engine \
  --syncmode=full \
  --gcmode=archive \
  --nodiscover \
  --maxpeers=0 \
  --networkid=42069 \
  --authrpc.vhosts="*" \
  --authrpc.addr=0.0.0.0 \
  --authrpc.port=8551 \
  --authrpc.jwtsecret=./jwt.txt \
  --rollup.disabletxpoolgossip=true
```

This may require a PR to update the documentation with a command that imports the `genesis.json` file. I can look into doing this.

**Comment by 1xAhmed** [comment]
I am facing exact same issue. 

I am running the network with ansible and service scripts.

here is op-geth.service

Description=op-geth
After=network-online.target
[Service]
User=ern
EnvironmentFile=/opt/ern-chain/etc/environment
ExecStart=/opt/ern-chain/bin/op-geth \
  --datadir ./datadir \
  --http --http.corsdomain="*" --http.vhosts="*" --http.addr=0.0.0.0 \
  --http.api=web3,debug,eth,txpool,net,engine \
  --ws --ws.addr=0.0.0.0 --ws.port=8546 --ws.origins="*" \
  --ws.api=debug,eth,txpool,net,engine \
  --syncmode=full \
  --gcmode=archive \
  --nodiscover \
  --maxpeers=0 \
  --networkid=42069 \
  --authrpc.vhosts="*" --authrpc.addr=0.0.0.0 --authrpc.port=8551 \
  --authrpc.jwtsecret=/opt/ern-chain/etc/jwt.txt \
  --rollup.disabletxpoolgossip=true
WorkingDirectory=/opt/ern-chain/var/lib/op-geth
Restart=always
RestartSec=3
LimitNOFILE=infinity
[Install]
WantedBy=multi-user.target


what do i have to do to fix it. Kindly help asap. thanks

these are op-node logs
```
May 02 13:31:48 ethernity-chain op-node[116279]: t=2024-05-02T13:31:48+0000 lvl=info msg="Initializing rollup node"            version=v0.0.0-a06cae81-1705510057
May 02 13:31:48 ethernity-chain op-node[116279]: t=2024-05-02T13:31:48+0000 lvl=warn msg="No beacon endpoint configured. Configuration is mandatory for the Ecotone upgrade"
May 02 13:31:48 ethernity-chain op-node[116279]: t=2024-05-02T13:31:48+0000 lvl=eror msg="Error initializing the rollup node"  err="failed to init L2: incorrect L2 RPC chain id 1, expected 42069"
May 02 13:31:48 ethernity-chain op-node[116279]: t=2024-05-02T13:31:48+0000 lvl=crit msg="Application failed"                  message="failed to setup: unable to create the rollup node: failed to init L2: incorrect L2 RPC chain id 1, expected 42069"
May 02 13:31:48 ethernity-chain systemd[1]: op-node.service: Main process exited, code=exited, status=1/FAILURE
May 02 13:31:48 ethernity-chain systemd[1]: op-node.service: Failed with result 'exit-code'.
```

If i delete the the database 
/opt/ern-chain/var/lib/op-geth/datadir, the op-node starts and works fine but the problem starts with op-geth.

kindly help, thanks
