### ISSUE TITLE
Unreliable portal `depositTransaction()` for contract

### ISSUE THREAD

**Issue by pegahcarter** [ethereum-optimism/optimism#9782]
**Bug Description**
As mentioned within `OptimismPortal.depositTransaction()`:
https://github.com/ethereum-optimism/optimism/blob/70c0778dc1f2ee3addc733b264da3f0d3bf7761a/packages/contracts-bedrock/src/L1/OptimismPortal.sol#L365-L367

A contract should not be calling this method as if the deposit does not succeed, the ETH is deposited to the contract alias and is not replayable.  

Given this, I do not believe there should be a reason for a contract to be depositing to the Portal.

**Suggestion**
Add the following protection to `depositTransaction()`:

```solidity
require(msg.sender == tx.origin, "OptimismPortal: cannot deposit from contract");
```

**Comment by tynes** [comment]
Simply send another deposit to assume the identity of the aliased account on L2
