### ISSUE TITLE
`make devnet-up` throws error `No target contract named scripts/ForgeArtifacts.sol:ForgeArtifacts`

### ISSUE THREAD

**Issue by seaona** [ethereum-optimism/optimism#9799]
**Bug Description**
I am unable to set up the devnet locally using the command `make devnet-up`. I get the error `Message:  No target contract named scripts/ForgeArtifacts.sol:ForgeArtifacts`.

Do  you think it could be related to this recent PR? https://github.com/ethereum-optimism/optimism/commit/cf9785348934de92766fb9051e305666e9a463c7

![Screenshot from 2024-03-08 20-15-45](https://github.com/ethereum-optimism/optimism/assets/54408225/cd98e86f-0ea8-4700-a4d9-ed52b38b61e9)

I've checkout some older commit and I see that contracts are being deployed and I can make more progress with the network setup. However, at some point the process also fails (with a different error).

![Screenshot from 2024-03-08 20-35-59](https://github.com/ethereum-optimism/optimism/assets/54408225/cce61bee-9b80-406a-8244-2df4b4e12fc5)

**Steps to Reproduce**

1. Run `make devnet-up`

**Expected behavior**
L1 and L2 networks should be running. 

**Environment Information:**
 - Operating System: Ubuntu
 - Package Version: `develop` branch - commit 7d3922c8758541a9d0413cb65c99050c14003374

**Configurations:**
No flag set

**Logs:**
Logs and/or error messages that help illustrate the issue.

**Additional context**

---

⚠️ **Notice:** Issues that do not include the following sections will be subject to closure:
- Bug Description
- Steps to Reproduce
- Environment Information

Please ensure all required sections are filled out accurately to expedite the debugging process and improve issue resolution efficiency.

**Comment by tynes** [comment]
Make sure to clean and rebuild everything. This problem does not occur on fresh builds in CI so it leads me to believe it is an issue with forge caching. `pnpm clean` in `contracts-bedrock`

**Comment by seaona** [comment]
thank you for the suggestion @tynes ! I've tried `pnpm clean` in the folder but unfortunately still seeing the same error :thinking: However, since this is working in ci I close the issue and I'll try to further investigate what's happening with my setup.
Thanks once again :pray:
