### ISSUE TITLE
Feat: Upgrade to Ethers v6 from v5

### ISSUE THREAD

**Issue by sambacha** [ethereum-optimism/optimism#9824]
**Is your feature request related to a problem? Please describe.**
Dependency on Ethers v5 should be depreciated and a migration path to v6 should be assessed. There are significant breaking change of moving to ES2020 BigInt and other modern JS features that make moving to v6 in my view worthwhile. Additionally, test network Holesky isn't supported on v5.

**Describe the solution you'd like**
Catalog all current packages dependent upon Ethers
Assess the complexity of migration. For example v5 and v6 providers aren’t interchangeable. An example of an easier migration update is depicted below:

Old Ethers v5
```ts
import { providers } from 'ethers'
import { providers, Wallet } from "ethers";
const provider = providers.getDefaultProvider('goerli')
```

New Ethers v6 
```ts
import { getDefaultProvider } from 'ethers'
import { JsonRpcProvider, Wallet } from "ethers";
const provider = getDefaultProvider('goerli')
```

Old

```diff
const tx = {
    from: wallet.address,
    to: wallet.address,
    value: "0x42",
-    gasPrice: BigNumber.from(99).mul(1e9), // 99 gwei
-    gasLimit: BigNumber.from(21000),
}
```

```diff
const tx = {
    from: wallet.address,
    to: wallet.address,
    value: "0x42",
+   gasPrice: 99n * BigInt(1e9), // 99 gwei
+   gasLimit: 21000n,
}
```

**Describe alternatives you've considered**
Forking the codebase and just YOLO the changes

**Additional context**
I am not suggesting someone actually does this shit by hand. Instead, something like a codemod (see for example Nextjs usage here: https://nextjs.org/docs/app/building-your-application/upgrading/codemods) should be utilized or bounty given. Lets be reasonable here comrades.

**Comment by tynes** [comment]
We are planning on fully deprecating the sdk so it was decided to not update it. It doesn't have great test coverage and adds a massive amount of size to any frontend bundle.

Viem is recommended now. I do have an old branch someplace where I did the migration, it took maybe 45 mins or so of replacing stuff

cc @roninjin10

**Comment by roninjin10** [comment]
Correct. @sambacha there are no plans to upgrade the optimism sdk. More users actually use ethers v5 still than ethers v6 atm so this sdk is considered the ethers v5 sdk.

If anybody was looking to contribute an ethers v6 sdk get in contact with me. [We would want to build it here](https://github.com/ethers-io/ext-utils-optimism).  Ideally both ethers and viem support the op stack but natively not via a custom sdk.

Have you tried viem @sambacha ? [Viem has native OP-Stack support](https://viem.sh/op-stack)

**Comment by roninjin10** [comment]
@sambacha feel free to dm me on tg if ethers v5 is blocking you

**Comment by sambacha** [comment]
Thanks for the clarification and quick response! Cheers
