### ISSUE TITLE
op build error

### ISSUE THREAD

**Issue by zhouhanker** [ethereum-optimism/optimism#9870]
hello
setting branch is develop
centos7
foundry version -> 4.7.0
go version -> go version go1.22.1 linux/amd64
node version -> v20.11.1
pnpm version -> 8.15.4
make version -> 4.3

execute pnpm install is success but execute pnpm build is error
![error](https://github.com/ethereum-optimism/optimism/assets/93653642/e2ddcb36-afe7-4134-95b5-a768177486d3)

What should I do to compile successfully ?
Ths

**Comment by friendwu** [comment]
As the error message shows: 
```
foundry is missing from /soft/optimism/versions.json
```

Suggesting to check whether foundry is installed properly, also `packages/contracts-bedrock/scripts/verify-foundry-install.sh` can do this.

**Comment by zhouhanker** [comment]
yes l check
***@***.*** optimism]# forge --version
forge 0.2.0 (3fa0270 2024-03-15T00:16:56.190232509Z)
***@***.*** optimism]# sh /soft/optimism/packages/contracts-bedrock/scripts/checks/check-foundry-install.sh
'foundry' is missing from /soft/optimism/versions.json
***@***.*** optimism]#

Is there a requirement for the Forge version?



***@***.***
From: friendwu
Date: 2024-03-15 17:16
To: ethereum-optimism/optimism
CC: lemons; Author
Subject: Re: [ethereum-optimism/optimism] op build error (Issue #9870)
As the error message shows:
foundry is missing from /soft/optimism/versions.json

Suggesting to check whether foundry is installed properly, also packages/contracts-bedrock/scripts/verify-foundry-install.sh can do this.

**Comment by smilenow** [comment]
I met the same issue and solve it by installing `jq`.
Check more at https://github.com/ethereum-optimism/optimism/commit/8432a71b8d70099cfed8d8df7c8a0b2c96e0e313.

**Comment by zhouhanker** [comment]
okay I'll give it a try!
