### ISSUE TITLE
When deploying an L1 smart contract, is it normal to consume 10  Sepolia  ETH?

### ISSUE THREAD

**Issue by lichong2005** [ethereum-optimism/optimism#9880]
**Bug Description**
I fellow the tutorial 《Creating Your Own L2 Rollup Testnet》,
When deploying an L1 smart contract, is it normal to consume 10+  Sepolia  ETH and 46 txes?

![1](https://github.com/ethereum-optimism/optimism/assets/3353561/e2b34fac-ed56-44d9-9963-235d5fe29630)

**Comment by lichong2005** [comment]
Fixed!  Operating during the early morning hours can result in lower gas fees. Thank you.

**Comment by blmalone** [comment]
Closing as user resolved their own issue.
