### ISSUE TITLE
Up-to-date docker images

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#992]
Another question coming from Discord.

**Question**
> I'm interested in running my own node, so I checked https://github.com/ethereum-optimism/optimism/tree/develop/l2geth and read :
> A prebuilt Docker image is available at ethereumoptimism/go-ethereum
> 
> I wonder if docker images on the user https://hub.docker.com/u/ethereumoptimism are official and maintained. Thank you in advance

**Comment by gakonst** [comment]
Yes they are being [automatically released](https://github.com/ethereum-optimism/optimism/blob/develop/.github/workflows/release.yml) whenever there's a new merge to master
