### ISSUE TITLE
How to get "Prove Transaction hash" for a L2 withdrawal?

### ISSUE THREAD

**Issue by gndelia** [ethereum-optimism/optimism#9974]
Not an actual bug (I think, unless the feature is missing), but a question. According to [this](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/sdk-trace-tx#tracing-a-withdrawal), given a L2 transaction hash for a withdrawal, we can use

```js
const l1Rcpt = await crossChainMessenger.getMessageReceipt(l2TxHash)
const l1TxHash = l1Rcpt.transactionReceipt.transactionHash
```
and `l1TxHash` will be the finalized tx hash on L1. How can we get the Tx hash of the "Prove Withdraw" operation in L1 ?  
If the withdrawal is not finalized, would that `l1Rcpt.transactionReceipt.transactionHash` be empty, or would it be the Prove hash? If so, how can I get both transaction hashes once the withdrawal is finalized?

**Comment by tynes** [comment]
Better to ask this question here: https://github.com/ethereum-optimism/developers/discussions
